### ISSUE TITLE
What port does the web interface of elementum listen to?

### ISSUE THREAD

**Issue by pitsi** [elgatito/plugin.video.elementum#10]
Dear maintainer.

Being a new user of elementum as of... today and an old user of quasar since mid-to-late 2016, I am trying to verify how things work here or how they have changed. One thing I use a lot is the web interface, which listens to 

`http://some-ip-of-my-local-network:65251/web/`

While this does work on quasar, it does not work on elementum. Assuming it does have a web interface, which port does it listen to? And please write a small documentation about it too.

Please note that I can not find the relevant info about the web interface on quasar's github, but I do remember it was added on 0.9.47, so the only reference to it is this

https://github.com/scakemyer/plugin.video.quasar/releases/tag/v0.9.47

Thank you in advance.

**Comment by pitsi** [comment]
As noted here, the port is 65220, so I am closing this one.
https://github.com/elgatito/plugin.video.elementum/issues/3

p.s. Please add new, elementum related, images for resources/web/static/media/header.something.jpg and resources/web/static/media/title.something.png

**Comment by elgatito** [comment]
Yes, the port is 65220. This was made to make Elementum and Quasar independent, they can work on same device.

Elementum is in *early beta* state, so documentation is not even started, don't expect it to work without errors, all error are now submitted in gitter channel with a kodi.log provided.

**Comment by pitsi** [comment]
Thank you for the clarification :)
