### ISSUE TITLE
[Request] Add ability to assign torrent/magnet manually for TMDB item

### ISSUE THREAD

**Issue by johndoe71rus** [elgatito/plugin.video.elementum#100]
хотелка.
Возможность привязать к объекту в медиатеке локальный .torrent файл.
Вроде на глаза попадался пункт меню "выбрать/указать стрим" но сейчас специально не могу найти где.

Пробовал через "добавить торрент" проигрывать из локального файла, но на данные медиатеки и истории это не отразилось.

**Comment by alexviean** [comment]
Hi @elgatito. Thank you so much for your good work. Any update on this feature?

**Comment by johndoe71rus** [comment]
"Development of this addon has been stopped!"

**Comment by antonsoroko** [comment]
should be available in next elementum release.
also please note how it works: https://github.com/elgatito/context.elementum/pull/13#issue-615408894
