### ISSUE TITLE
Assign torrent context menu links to the wrong section in elementum

### ISSUE THREAD

**Issue by VisionaiR3D** [elgatito/plugin.video.elementum#1000]
When you go to the context menu and select assign torrent kodi goes to elementum->torrent history. If you select a torrent from this list it wont work. Instead you have to go to elementum->torrents and select a file from there. 

## Expected Behavior
Assign torrent jumps to elementum->torrents

## Current Behavior
Assign torrent jumps to elementum->torrent history 

## Possible Solution
Make it jump to the correct section in elementum

edit context.elementum\plugin.py

edit line 74 and 76 to the following

file = xbmcgui.Dialog().browseSingle(1, ADDON.getLocalizedString(32010), 'files', '', False, False, 'plugin://plugin.video.elementum/torrents/')

if not file or file == 'plugin://plugin.video.elementum/torrents/':

## Steps to Reproduce (for bugs)
Play a torrent in elementum. > select a title from your database > open the elementum context menu >  click assign torrent

**Comment by VisionaiR3D** [comment]
edit context.elementum\plugin.py

edit line 74 and 76 to the following to fix the problem.

file = xbmcgui.Dialog().browseSingle(1, ADDON.getLocalizedString(32010), 'files', '', False, False, 'plugin://plugin.video.elementum/torrents/')

if not file or file == 'plugin://plugin.video.elementum/torrents/':

**Comment by elgatito** [comment]
It should be an issue in context.elementum.
