### ISSUE TITLE
Update Elementum Subtitles from Opensubtitles.org to Opensubtitles.com. .ORG is now deprcated, it loads blank subs.

### ISSUE THREAD

**Issue by Kristijan1001** [elgatito/plugin.video.elementum#1001]
.ORG API has been discontinued so it loads Buy VIP subs instead of the movie subs. .COM Still works any chance this gets updated ?

**Comment by antonsoroko** [comment]
you could use search before creating issue.
see https://github.com/elgatito/plugin.video.elementum/issues/952
