### ISSUE TITLE
Tagline for TV Shows

### ISSUE THREAD

**Issue by matke-84** [elgatito/plugin.video.elementum#1008]
@elgatito @antonsoroko
We have it for movies but the TV Show doesn't show it.

![Screenshot 2024-03-15 090235](https://github.com/elgatito/plugin.video.elementum/assets/74268331/1fa4fb8d-112e-4975-aac3-22ea5dbab598)

**Comment by elgatito** [comment]
@matke-84 I will add this. We are missing fields in the TV Show coming from TMDB (new fields)

**Comment by elgatito** [comment]
@matke-84 Added it to the code. You should see it using the next build/release (and making sure TMDB cache is wiped).

**Comment by matke-84** [comment]
@elgatito 
Ok. Thanks.
