### ISSUE TITLE
Interface language buttons, usefulness "prefer use of original title" option and update for language logic

### ISSUE THREAD

**Issue by matke-84** [elgatito/plugin.video.elementum#1009]
1. Does this have to be split into two buttons? I think it will confuse people. Why not put only button "Interface language" and "interface fallback language".
![lang](https://github.com/elgatito/plugin.video.elementum/assets/74268331/50b46fad-20a0-4ce1-ae20-87f1063cfc19)

2. Are this option necessary now (Prefer use of original title)?
![org title](https://github.com/elgatito/plugin.video.elementum/assets/74268331/930513fa-6bbe-4d5c-9caa-21af8b8c8dae)

3. Update for language logic. If we set non-EN as primary and non-EN as secondary language, then instead of "original" it should be EN as the third option and only then "original".

**Comment by antonsoroko** [comment]
2. i think we can delete it. i think it was designed for Europeans users and USAian videos, but nowadays we have videos from all around the world, and user most likely will not be able to read their titles.
3. i think it makes sense.

**Comment by elgatito** [comment]
I have pushed changes to have single setting for selecting a language in settings.
And I think @antonsoroko landed a fix for 3. ?

**Comment by matke-84** [comment]
@elgatito
Great. What will we do with 2? Do we need that option?

**Comment by antonsoroko** [comment]
>I have pushed changes to have single setting for selecting a language in settings.

just tested it. looks good!
to note: now to "reset" language value user must press "delete" button on keyboard. which is not possible on android (w/o connecting keyboard, of course). but this is not very important since user can simply set correct language instead of resetting the option.

>What will we do with 2?

my take on this option is above. i vote for deletion.

**Comment by antonsoroko** [comment]
@matke-84 №2 is done (that option was deleted). So this issue can be closed, I believe.

**Comment by matke-84** [comment]
Yep. Closed.
