### ISSUE TITLE
"Strm files language" logic is broken

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/plugin.video.elementum#1013]
## Current Behavior

by default this option is set to "Original"
https://github.com/elgatito/plugin.video.elementum/blob/bc63d8e5164fd691ee12f8cb8abe291883f2c48b/resources/settings.xml#L111
https://github.com/elgatito/elementum/blob/7de33f4471afe6793c37d73c3e005ec80ced123e/api/misc.go#L233

but then we set it to user's language!
https://github.com/elgatito/elementum/blob/7de33f4471afe6793c37d73c3e005ec80ced123e/config/config.go#L844

and then the logic for strm language is very strange
https://github.com/elgatito/elementum/blob/7de33f4471afe6793c37d73c3e005ec80ced123e/library/library.go#L476

if strm language is not equal to user's language (which will not happen by default since above we set strm language to user's language, so they are equal) then we use user's language, otherwise we use original language.

**so for strm language:**
* with default "Original" value we will use original language, but this is a just a side effect of incorrect logic.
* and with any language except user's language - we will use user's language - which does not make any sense.
* and with user's language - we will use original language, which again does not make any sense.

also i think we should rename "#30477" from "Original" to "Original language" to avoid confusion for translators.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

**Comment by elgatito** [comment]
@antonsoroko I have pushed a change for use of strm language - https://github.com/elgatito/elementum/commit/7e159164f567d56ea122ea1fd9a47ed679a5ec8f

It was initially planned to use original titles as a default. 
But I am not sure that it is what I want, having japanese/chinese titles on the disk - does not look fine. 
It is more human-friendly to have titles on the disk in Kodi language.

So I seem to fix the use of strm, but I liked the "wrong" logic.

**Comment by antonsoroko** [comment]
@elgatito лучше, но всё равно странновато.

(содержимое файлов не имеет текста, только идентификаторы, так что фокусируемся на названиях файлов.)

по умолчанию стоит "Original", как и было.
если выбрано значение "original" - то названия на ФС пишутся в original (иероглифы у меня тоже, но зато и кириллица тоже). логично.
если выбрать значение равное значению опции "первый язык" - то будет на "первый язык". логично.
**но**, если выбрать как значение "любой другой язык" - то всё равно будет на "первый язык". это разве норм?
например, человек использует японский как основной, но писать на диск хочет на английском - сейчас так сделать не выйдет.

---

дополнительно:
1. можно было бы использовать локализованное "#30477" вместо жесткого "Original" в питон и го коде, но тогда надо переписать `if !strings.Contains(strings.ToLower(newConfig.StrmLanguage), "original") {` чтобы наоборот было - любое значение, которое не является языком, будет считаться "original". но это опциональное.
2. про rename "#30477" from "Original" to "Original language" to avoid confusion for translators - сделал https://github.com/elgatito/plugin.video.elementum/pull/1015
3. кажется что в RemoveEpisode https://github.com/elgatito/elementum/blob/2747a837faca7299b757a5c7155849ac5f75b80f/library/library.go#L777 стоит использовать getShowPath https://github.com/elgatito/elementum/blob/2747a837faca7299b757a5c7155849ac5f75b80f/library/library.go#L1446 , так же как это сделано в RemoveShow , учитывая что в getShowPath написано `// If this show already uses any directory - we should write there, to avoid having duplicates` - **соответственно в RemoveEpisode может быть баг**.

**Comment by elgatito** [comment]
> но, если выбрать как значение "любой другой язык" - то всё равно будет на "первый язык". это разве норм?

Я не вижу как это может быть. Если выбрать язык конкретный для `strm_language` то для этого языка подгрузится вся информация и будет использоваться название:

```go
	movie := tmdb.GetMovieByID(tmdbID, config.GetStrmLanguage())
	if movie == nil {
		return nil, errors.New("Can't find the movie")
	}

	movieName := movie.OriginalTitle
	if config.Get().StrmLanguage != "" && movie.Title != "" {
		movieName = movie.Title
	}
```

> если выбрано значение "original" - то названия на ФС пишутся в original (иероглифы у меня тоже, но зато и кириллица тоже). логично.

`strm_language` в принципе не имеет ни на что влияния, на каком языке его не пиши.

**Comment by elgatito** [comment]
> кажется что в RemoveEpisode https://github.com/elgatito/elementum/blob/2747a837faca7299b757a5c7155849ac5f75b80f/library/library.go#L777 стоит использовать getShowPath

Да. Но я не уверен что туда вообще заходит когда-то.

**Comment by antonsoroko** [comment]
>Я не вижу как это может быть. 

тут я ошибся и не заметил, что инфа о фильме получается с использованием StrmLanguage, соотв и movie.Title переведён на него. всё ок.

>strm_language в принципе не имеет ни на что влияния, на каком языке его не пиши.

не понял. он же влияет на название файла. или что-то другое имелось ввиду?

>Да. Но я не уверен что туда вообще заходит когда-то.

тут я тоже не знаю, так как не использую библиотеку. я только вижу, что он используется в Notification() https://github.com/search?q=repo%3Aelgatito%2Felementum+RefreshEpisode%28&type=code через RefreshEpisode().

**Comment by elgatito** [comment]
> не понял. он же влияет на название файла. или что-то другое имелось ввиду?

Для библиотеки не имеет значение. Даже если будет случайно сгенерированное название, читается файл nfo внутри папки.
Поэтому видеть на "своём" языке названия папок обычно удобнее.

**Comment by antonsoroko** [comment]
@elgatito 

>Поэтому видеть на "своём" языке названия папок обычно удобнее.

тогда может стоит по-умолчанию не Original, а язык коди? как для первого языка сделано. или это усложнит логику выбора?

**Comment by elgatito** [comment]
> @elgatito
> 
> > Поэтому видеть на "своём" языке названия папок обычно удобнее.
> 
> тогда может стоит по-умолчанию не Original, а язык коди? как для первого языка сделано. или это усложнит логику выбора?

Поменял значение по-умолчанию и выбор языка поправил чтоб было читабельно.

**Comment by antonsoroko** [comment]
@elgatito проверил, вроде теперь всё четко с логикой и локализация есть. отлично!
