### ISSUE TITLE
Remove duplicate functions do now work with special:// paths

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/plugin.video.elementum#1023]
## Current Behavior

1. после фикса языков файлы в библиотеке elementum стали писаться папки/файлы на новом языке (о этого был язык оригинала) и я вижу что были фиксы на удаление дубликатов, но они позоже не учитывают `special://` пути:

`2024-04-16 14:12:50.935 T:165699 warning <general>: [plugin.video.elementum] DEBU  library      ▶ removeMovieDuplicates  Removing duplicate movie 'The Upside' from 'special:/home/elementum_library/Movies/11 Голливудская история (2019)'`

2. интересно ещё что первым считается англ название (из-за алфавитной сортировки или из-за того что оно было добавлено первым), соотв удаляется локализованное название - не будет ли вечного конфликта (проверил: **будет**) - сначала добавляем новый strm, а потом пытаемся его удалить как дубликат? и ещё сканирование каждый раз будет запускаться.

## Possible Solution

1. add support of `special://`
to https://github.com/elgatito/elementum/blob/ace7ff413e6e8e318288f802e539eceb88fd288b/library/library.go#L1734C26-L1734C29 and similar functions

2. тут не знаю даже, может при добавлении нового strm проверять на дубликат и удалять старый strm?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

**Comment by elgatito** [comment]
Поиск дубликатов берется не из сканирования файлов, а из базы Kodi. Если в Kodi добавлено несколько записей то оставляем только самую старую - остальные удаляем из диска и командуем удалить из Kodi. Если нету физически доступа к файлам, или Kodi отдаёт специфические пути (как `special:://` или `smb://` например), то Kodi их передобавил после очередного сканирования, так как файты останутся за своих местах.

Во время записи фильма/сериала мы смотрим в текущую библиотеку Kodi и используем путь из библиотеки, но только если он физически нам доступен. Иначе будут писаться в дефолтную папку. 

В фильтре дубликатов нету поддержки `special://` но дубли не должны писаться в принципе, если папка доступна физически с той записью что уже есть в библиотеке Kodi.

**Comment by elgatito** [comment]
> но на самом деле нет, так как он делает os.RemoveAll на special:/) и потом запускается длинное сканирование tmdb.

Как пути добавлены вообще в Коди?

**Comment by antonsoroko** [comment]
может просто добавим резолвинг путей как тут https://github.com/elgatito/elementum/pull/88/files ?

**Comment by antonsoroko** [comment]
>Как пути добавлены вообще в Коди?

https://github.com/elgatito/plugin.video.elementum/issues/949#issuecomment-1856570380

вот тут конфиг и скиншоты

**Comment by elgatito** [comment]
@antonsoroko 
https://github.com/elgatito/elementum/commit/56e609e26eaeaae6e40fd8b4b1a93679bf40c9ad

А если так?

**Comment by antonsoroko** [comment]
@elgatito так сработало, спасибо. поудаляло все дубликаты которые добавились на русском недавно.
правда почему-то не с первого раза, после 4-5 перезапусков удалило всё, последние 2 запуска по 16 удаляло за старт.

**Comment by antonsoroko** [comment]
вроде больше дубликаты не появляются. спасибо.
