### ISSUE TITLE
Video stops playing after 30 or 40 min

### ISSUE THREAD

**Issue by Insomniac412** [elgatito/plugin.video.elementum#1024]
Without any fixed pattern, randomly but mostly after 30 or 40 min playing, the video stops.  
The sound will go on for a few more seconds and then it will shut down.
Here is my log file: https://paste.kodi.tv/bigomumopa
Can you help me please? All of my familly suffer)

**Comment by Insomniac412** [comment]
Sorry, How can i make that kind of log? BTW my TV android stick shuts down when this issue happens? so i need to reboot it

**Comment by elgatito** [comment]
Shuts down what? Device, kodi, or elementum? Any chance you run out of memory?

**Comment by Insomniac412** [comment]
The device shuts down. I'm not sure, but i guess it's not memory, because all other apps (even hard ones runs for infinite time with no problems). My device have 4 GB RAM. When I've started debugging mod to make a log, there was a onscreen information, when my issue happens the picture freezes for some time, before the device shuts down and the memory was not full i guess. At least according to that onscreen info

**Comment by antonsoroko** [comment]
@Insomniac412 try to check your CPU temperature during playback. install some android app that shows temperature, for  example.

**Comment by Insomniac412** [comment]
Thank you very much, reflashing helped me. In the new firmware version they added the function “CPU and GPU frequency blocking at the maximum value”, and when I turned it on as root, the problem went away. Your addon is great, I will definitely donate
