### ISSUE TITLE
[BUG] Wrong percentage calculation

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#103]
## Current Behavior
When the torrent finished the download and reached to 100%, in Kodi, Elementum showed 33% (instead 100%), the status in the log changed from 'Downloading' to 'Queued'. It seems that all the percentage calculation during the download was wrong.

## Expected Behavior
Follow the actual downloading state according to the torrent status.

## Steps to Reproduce (for bugs)
Just check a one of the torrents in kodi and verify it with the torrent itself.

## Your Environment
* Version used: Elementu, 0.0.42 (File storage)
* Environment name and version: Kodi 17.6
* Operating System and version: Windows 10, 64 bit
* Link to Kodi debug log: https://paste.ubuntu.com/p/2j9r9pN3jd
```
02:06:12.627 T:568  NOTICE: [plugin.video.elementum] DEBU  bittorrent   ▶ progressEvent    PR: 446499 (524288)/1782; "Downloading" = 33.33
02:06:13.625 T:568  NOTICE: [plugin.video.elementum] DEBU  bittorrent   ▶ progressEvent    PR: 453107 (376832)/1667; "Queued" = 33.33
```
* Link to torrent log: https://paste.ubuntu.com/p/DY7N9WvzkV (You can see it reached to 100% file)
* Screenshot: https://postimg.org/image/e3uxugbat/494ec939

**Comment by elgatito** [comment]
Things changed in 0.0.43.

**Comment by burekas7** [comment]
Thanks, I will check.

**Comment by Comawhite54** [comment]
Still not working properly with the %, my download is now completed, but shows 50.44% .
+ I always have to wait the end of the download before watching. The streaming doesn't work (I can only see a few minutes then video stops, even when the download is almost finished...

**Comment by rschee** [comment]
Yep. Unstable download speed and the math is wrong for % download and total dl. I don't know if the download speed is correct either.  It's also trying to buffer up to 10-15 % of a large movie before it even starts playing. Quasar buffered 1-2%. It finally seems to totally lose track of where it's at and just stops.

**Comment by burekas7** [comment]
>  It's also trying to buffer up to 10-15 % of a large movie before it even starts playing.

**Comment by burekas7** [comment]
> It's also trying to buffer up to 10-15 % of a large movie before it even starts playing.

The init buffer size can be set in the Settings, you can change it.

**Comment by burekas7** [comment]
> It's also trying to buffer up to 10-15 % of a large movie before it even starts playing.

The init buffer size can be set in the Settings, you can change it.

Regarding the unstable speed etc, there is another issue of mine.

**Comment by burekas7** [comment]
@elgatito 
The original bug still exist, look in the log what happens in 71.54%,
still keep downloading while the percentage is stuck on 71.54%, and continue to download until it finish but still the same percentage value, 71.54%
(Version 0.0.43)

**Comment by burekas7** [comment]
@elgatito 
Is there any progress regarding this bug?

**Comment by elgatito** [comment]
@burekas7 for memory storage there is no perfect way to calculate progress percentage (because we operate data numbers, that changes as we delete non-needed pieces of torrent).
For file storage we take numbers from torrent engine.

If you have the described error with 0.0.44, please, provide a new log file.

**Comment by burekas7** [comment]
@elgatito 
But I didn't use Memory storage, I'm using the File storage option.

I will check it with 0.0.44 and update if this will happen again.

**Comment by burekas7** [comment]
@elgatito 

Update:
The problem is still exist in 0.0.44.
The progress stop twice, on 20.49% for a while and then it continued until 33.33% which is actually was the 100%.
https://s31.postimg.cc/9tk735wob/screenshot018.png
https://s31.postimg.cc/mkyd9oe63/screenshot019.png


* By the way, I had a strange behavior that I paused the video for short period, and the dialog of the init buffer progress jumps again.
Screenshot: https://s31.postimg.cc/nzzxydke3/screenshot007.png

Kodi Log: https://paste.ubuntu.com/p/mVyYksFyq8

**Comment by rschee** [comment]
It did work on Quasar....

**Comment by elgatito** [comment]
We use numbers, that we get from torrent engine for torrent progress. It depends on many options how they calculate bytes count. But we don't influence it.
