### ISSUE TITLE
Trakt -> Shows -> My Progress doesn't show unaired episodes

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#1035]
Hi, @elgatito 

It seems that with version 0.1.102 unaired episodes aren't shown in the Trakt -> Shows -> My Progress lisr,
While in 0.1.99 it was there.
I didn't change anything in the settings.
Install 0.1.99 back, it works again.
Install 0.1.102, it isn't working as it worked before.

With 0.1.102
![image](https://github.com/elgatito/plugin.video.elementum/assets/13424257/8da002c5-fec9-45af-9b27-cbd77b935adf)

With 0.1.99
![image](https://github.com/elgatito/plugin.video.elementum/assets/13424257/bafc20b5-8662-4bef-ba4d-3d1e37450565)

**Comment by elgatito** [comment]
Can you show the log with latest version to see what is enabled? That is house of dragons?

**Comment by burekas7** [comment]
@elgatito 

Log: 
(0.1.102)
https://paste.ubuntu.com/p/zC4qRcw7R7/plain

**Comment by elgatito** [comment]
You have this enabled:

```
TraktProgressHideUnaired: true
```

That was a new setting to avoid having unaired episodes in the progress.

**Comment by burekas7** [comment]
> You have this enabled:
> 
> ```
> TraktProgressHideUnaired: true
> ```
> 
> That was a new setting to avoid having unaired episodes in the progress.

This new setting was added after 0.1.99?

**Comment by elgatito** [comment]
@burekas7 Yes, that is a new setting and by default it is set to `true`, so in case you update Elementum - it would enable it by default.

**Comment by burekas7** [comment]
@elgatito 
Previously, when standing on an episode it shown the episode image as background, now it shows the TV Show background.
How can I change it to be as it was?

**Comment by elgatito** [comment]
@burekas7 It was part of big https://github.com/elgatito/plugin.video.elementum/issues/945 changes that were reassigning arts to proper values. 

@matke-84 I guess it was decided that Episode Still should not be set as a background (that sounds logical)?

**Comment by matke-84** [comment]
@elgatito
Yes, that's how it should be. Episode still is usually of lower quality and is not intended for fullscreen. Also, just as landscape is for movies and tv shows, so is episode still for episodes.
