### ISSUE TITLE
nice jobs 

### ISSUE THREAD

**Issue by tomtomclub** [elgatito/plugin.video.elementum#104]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

step by step becoming better xcellent work  Brother
love the  v 0.0.43

**Comment by elgatito** [comment]
Thanks, but don't use the issue tracker for this kind of messages. There is a chat for that - https://gitter.im/ElementumApp/Lobby
Cheers
