### ISSUE TITLE
Xbox Support

### ISSUE THREAD

**Issue by Dodo21odoD** [elgatito/plugin.video.elementum#1047]
Can you add support for watching movies from elementium on Xbox Series X/S?

**Comment by antonsoroko** [comment]
please use search https://github.com/elgatito/plugin.video.elementum/issues?q=is%3Aissue+Xbox
it was discussed many times already.
the only way with xbox is to use client-server approach: you run kodi+elementum as client on xbox and then elementum as server on PC. see the end of https://github.com/elgatito/plugin.video.elementum/issues/2

**Comment by elgatito** [comment]
Duplicate of #844
