### ISSUE TITLE
TMDb Connection Error and Missing Providers in Burst List

### ISSUE THREAD

**Issue by ajay01994** [elgatito/plugin.video.elementum#1049]
Describe the bug
 I am experiencing a connection error with TMDb, and as a result, many providers do not appear in the Burst list.
Steps to Reproduce Open Elementum on Kodi.Navigate to any menu option that requires TMDb data (e.g., top-rated movies).Observe the connection error message.

Expected behavior Providers should appear in the Burst list, and TMDb connections should work without errors.

Debug Log I have enabled debug logging and captured the error. The debug log can be found at: https://paste.kodi.tv/iwawojjlixScreenshots (Include any relevant screenshots here if you have them)

Additional ContextI have disabled the internal DNS resolver and built-in HTTP proxy settings in Elementum. Despite this, the error persists.Many providers that used to appear in the Burst list are now missing.I appreciate any assistance you can provide to resolve this issue. Thank you for your time and support.

**Comment by antonsoroko** [comment]
@ajay01994 link to log file is broken. please re-upload.

i guess this is continuation of https://github.com/elgatito/plugin.video.elementum/issues/1027
please try with any VPN just to test if your ISP started to block TMDB more aggressively.

**Comment by ajay01994** [comment]
**Title:** TMDb Connection Error Causes Torrent Providers to Disappear

**Description:**

I am encountering an issue with Elementum where everything works fine until a TMDb connection error occurs. After this error, the torrent providers no longer show up in the list. The specific error message and details can be found at the following Pastebin link: [https://paste.kodi.tv/palocohore](https://paste.kodi.tv/palocohore).

**Steps to Reproduce:**
1. Use Elementum normally.
2. Observe that all torrent providers are listed correctly.
3. Encounter a TMDb connection error.
4. Check the list of torrent providers.

**Expected Behavior:**
Torrent providers should remain listed and functional even after a TMDb connection error.

**Actual Behavior:**
After the TMDb connection error, the torrent providers disappear from the list.



**Logs:**
Please refer to the logs for more details: [https://paste.kodi.tv/palocohore](https://paste.kodi.tv/palocohore).

---

**Comment by antonsoroko** [comment]
@ajay01994 i do not see any error in log. i see that you did search for show (and in the end for movie) and some providers returned results and some "timed out" (but this is not b/c of TMDB but b/c of your network or anti-bot protection).

but to be clear - elementum **heavily uses** TMDB, so if you do not have access to TMDB then many many things will not work. if you do not have access to TMDB - you can use VPN (or internal DNS , but it works only for simple DNS based block).
context: elementum takes all relevant for searching info about movies/shows from TMDB, like translated titles and year, so if you do not have access to TMDB - then elementum can't provide that info to burst. nothing can be done here, unless you are willing to completely rewrite this logic, that was formed for years of coding.

if i misunderstood you - then please provide better explanation of the issue and step-by-step guide of reproducing the issue.

**Comment by ajay01994** [comment]
Hi @antonsoroko , thanks for your reply..in my case TMDB is working fine .i mean to say TMDB doesn't crash rather ot shows a nework connection error then the error closes post which TMDB works usually only as its supposed to show TV shows , movie list etc however after that error the number of provoders in burst reduces significantly and only 1 oe 2 providers show up instead of many. Also thatTMDB connection error comes randomly. Before the error pops us , the number of providers are more say 10 but after that error it reduces to 2 . Also i have installed two different TMDB helper repos could that cause an issue ?

**Comment by antonsoroko** [comment]
@ajay01994 looks like you are confusing "tmdb helper" addon and elementum addon.
those are 2 different addons and they are not connected. 
i see connection error from plugin.video.themoviedb.helper in your log, but no error from elementum.
so i think you saw error about TMDB and you thought that this is elementum error, but no - this is "tmdb helper" error.

to make it very clear: "tmdb helper" addon is not connected anyhow to elementum addon, thus error in tmdb helper can not affect elementum.

1. **you have not enabled debug log in kodi and in elementum**. follow https://elementum.surge.sh/contribute/log/ guide.
your log files are not very useful, since they do not have debug messages.
since i do not see debug messages from Burst - i can't say why you see different number of results each time you do search.
Most likely it is because your network issues or anti-bot protection.
**Do this:**
a. increase provider timeout in **both (!)** elementum and burst, e.g. to 60 for test
b. enable debug in kodi make a log file with debug.

2. if you do not use "tmdb helper" addon - just remove it, so you will not see its error messages. anyway, it is not connected to elementum. remove it at least for testing purposes.

**Comment by ajay01994** [comment]
Hi Thanks for the brief information and test case pointers ..increasing the timeout to 60 seconds resolved all the issue now i can see almost all providers and its working perfect, Also i cross checked  yes the TMDB connection error is not an elementum issue its an issue with TMDB helper repository shows and shows information is not updated. This is simply because TMDB is blocked in india..However if you can tell me how to bypass TMDB the way elementum resolved this issue ..the last time in mentioned for TMDb error than it would be helpful as i can tell the TMDB repository owner  to do the same.

**Comment by antonsoroko** [comment]
@ajay01994 as you probably already have seen in https://github.com/elgatito/plugin.video.elementum/issues/1027
we added https://api.tmdb.org/3/ as a fallback URL for TMDB API.

You can share this solution with "tmdb helper"  addon develop if you want.

**Comment by elgatito** [comment]
@ajay01994 Any updates on this issue? Should it be closed?

**Comment by ajay01994** [comment]
HI @elgatito , i am experimenting over it  allow me 2 -3 days.. after new burst update i had to increase the timeout from modified 60 seconds to now 100 seconds for all providers ti show up.. Also at times the artwork doesn't update immediately episode wise rather takes more time ..text comes in time but images takes time i will update the full debug log file in couple of days so that we are able to see where is the issue..

**Comment by ajay01994** [comment]
Hi please refer the log file with debug once 
[bundle_2024_7_19_14_28.log.txt](https://github.com/user-attachments/files/16309793/bundle_2024_7_19_14_28.log.txt)

For some reason pastebin didn't generate a link of i have downloaded it .pls have a look and see if it gives you enough information so that we can resolve the issue..

**Comment by antonsoroko** [comment]
@ajay01994 
1. Burst is not connected to tmdb. If you have to increase timeout it means that your network is slow. (or it is slow in regards to countries where pirate sites are located.)
2. In Elementum settings set TMDB image quality to "medium" or even "low" . Again, it looks like you have slow network.

**Comment by ajay01994** [comment]
Could be , log file might have all ghe details needed

**Comment by elgatito** [comment]
@ajay01994 I can't see anything bad in the log file. You have enabled many providers, and some of them cannot return anything (it looks like a firewall that blocks connections). So Burst waits till the timeout and then returns everything that is found.

So you should probably disable providers, that do not work from your location.

```
[script.elementum.burst] RuTor, TorrentDownloads timed out
```

**Comment by ajay01994** [comment]
Ya actually i increased the number of providers because a lot of times existing providers didn't use to return results..is there any way to unblock firewall or allow other providers to show up ?

**Comment by elgatito** [comment]
@ajay01994 Burst is doing usual https requests, like your browser does, so it should not be firewalled by your own firewall. But due to destination address it can be blocked globally in your country. 
Also your Burst settings ask to use `opennic` domains if possible, and that can be also not working in your location.

I don't see any issues left for TMDB connectivity, so this issue should be considered resolved.

**Comment by antonsoroko** [comment]
@ajay01994 the only real solution for you us to use vpn (simple solution) or proxy (configure it in both burst and Elementum, in your case).

**Comment by ajay01994** [comment]
As of now the fix is i turned off torrent domain alias and turned on IP6 resolving. After which i can see some more providers ..but its random so when i restart kodi again  some providers come consistently for the same episode and some times they don't come only 1 provider comes .i am not an expert but there is no pattern its random. I suspect it as a bug but i can't confirm it at times elementum shows its still starting..its possible that my platform libreelec and its version coulf also have some bug.

**Comment by antonsoroko** [comment]
@ajay01994 about "still string" - try to reboot your device. 

About providers - try to use vpn it proxy . 

If you will have issues with providers - create issue in burst repo https://github.com/elgatito/script.elementum.burst/issues since providers are fron burst , not from Elementum.
