### ISSUE TITLE
Looks like Elementum is still starting up....

### ISSUE THREAD

**Issue by fmas2** [elgatito/plugin.video.elementum#1050]
Hi, I've just installed Kodi 21.0 on muy Android 5.0 phone. After I've installed Elementum 0.1.103 having a popup saying addon installed. When trying to open Elementum It shows always the sentence on subjet. I've tried with file: plugin.video.elementum-0.1.103.android_arm.zip and also with android_arm64.zip
On both I had the same problem when trying to open It.
Any help will be appreciated

**Comment by antonsoroko** [comment]
@fmas2 not sure that elementum can work on android 5.
but anyway, **make a proper debug log - guide was in issue template**.
without **proper** debug log file we can't say anything.

**Comment by fmas2** [comment]
@antonsoroko many thanks for your comments.
I've finally installed elementum in another android 13 phone and it works great !!!!

**Comment by antonsoroko** [comment]
@fmas2 nice. if you do not plan to create a debug log file on your android 5 device - then close the issue (so it will not hang opened forever).
otherwise - we can try to see why it have not worked on android 5.

**Comment by fmas2** [comment]
OK. Thanks I'll do so
