### ISSUE TITLE
Elementum does not want to use public ip

### ISSUE THREAD

**Issue by ladoba** [elgatito/plugin.video.elementum#1054]
Hi,
is there a chance to use it with a public ip address?
kodi runs on a remote server in docker in host mode with elementum plugin, the same runs locally.I can use search,download torrents etc, except stream from the remote server.I think the problem is that the remote plugin gives the local ip address (172.x.x.x) to the local plugin.
<img width="445" alt="Screenshot 2024-07-17 at 09 23 47" src="https://github.com/user-attachments/assets/9e6ca9bd-3536-4eb3-adba-85bbc9351092">
<img width="449" alt="Screenshot 2024-07-17 at 09 22 59" src="https://github.com/user-attachments/assets/70e46a5b-d644-469a-8d06-58b3751eb42f">

**Comment by elgatito** [comment]
@ladoba I am not sure there is something Elementum can do. Inside docker it does not know about any other network interfaces apart from local one. By default, if you don't select which interface to listen - it would stick to `0.0.0.0`.

**Comment by ladoba** [comment]
You see kodi gets the public ip but element doesn't. I don't understand how, because in host mode it should get the same public IP as kodi.I selected enps0xxx as the incoming and outgoing interface, but the element always returns the default bridge ip (docker0) address, and it is not in bridge mode.
Any idea how could I use it on a remote server and not locally?

**Comment by elgatito** [comment]
@ladoba I was not running Elementum binary in docker. Can you share elementum log after you start it, it can say something about listened interfaces.

**Comment by ladoba** [comment]
@elgatito 
[https://paste.kodi.tv/qodoxofuge](url)
[https://paste.kodi.tv/elosolizev](url)

**Comment by ladoba** [comment]
@elgatito I found a solution.It works remotely now.

**Comment by elgatito** [comment]
@ladoba  Your log says:

```
2024-07-18 17:29:50.713 T:186   warning <general>: [plugin.video.elementum]   ListenInterfaces: "enp0s31f6",
2024-07-18 17:29:50.713 T:186   warning <general>: [plugin.video.elementum]   OutgoingInterfaces: "enp0s31f6",
```

Which says libtorrent to listen on that specific interface. And I guess interface binding is broken due to #899

**Comment by ladoba** [comment]
I tried it with wireguard and it's still working pretty well.
