### ISSUE TITLE
Problem with elementum on kodi smart tv philips

### ISSUE THREAD

**Issue by peke198822** [elgatito/plugin.video.elementum#1056]
Hello crack, first tell you that you are an artist, I have had a problem for 1 month, before that it has been working without problemsIt's a Philips smart TV, For a month or so I have been getting an elementum connection error:

There is no JSON-RPC connection available for Kodi. Enable options in Application Control in Settings > Service Settings > Control and restart Kodi.

But when I go to this configuration, it tells me startup error, I have tried a thousand things, reinstall kodi, tv, restart router..., it only happens to me on this tv , I also have a fire tv max, this doesn't give me any problems, if you have any idea why this happens to me, before it was going great but now I don't know what to do, thank you.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

**Comment by antonsoroko** [comment]
@peke198822 try to reinstall Kodi (remove and install again, so Kodi will have default configuration).

If it will not help - make debug log file , see http://elementum.surge.sh/contribute/log/

**Comment by peke198822** [comment]
Thank you very much for the quick response, I reinstalled the entire Kodi,
I reinstalled the entire TV, it didn't work either, I reinstalled the
router, it didn't work either, I don't know what else to do. I've been
adding these days to upload movies in blue crystal via acestream, I don't
know if it has anything to do with it, I hope you have a solution for my
case.

**Comment by peke198822** [comment]
Hi again, with the last thing I meant that after starting movies via
acestream then elementum loaded, and I exited Kodi, I re-entered and it
worked without problems.

**Comment by peke198822** [comment]
But when I turn the TV off and on again, it no longer works, nor does it
work following the steps above. I would love to know where the problem is.
I am sending you the two images that I get.

**Comment by peke198822** [comment]
What Kodi tells me to do, it doesn't let me activate it, it tells me there
is no connection to the local server.

**Comment by antonsoroko** [comment]
@peke198822 I do not see images, I think you need to attach them here in browser, not via email. 

Also, create the debug log file, guide is above. 


My guess is that  you installed some android application that uses the same port that kodi uses (port 9090) thus Kodi can't use that port anymore. 
But without log file I can't be sure .

**Comment by peke198822** [comment]
Thanks Antón, I'm attaching the .log. I don't know if you can open it,
there are some errors that have to do with json that I mentioned.

**Comment by peke198822** [comment]
I attach the image of the error that appears to me.
![IMG_20240805_020014](https://github.com/user-attachments/assets/db7102eb-b3d5-4c19-8154-2708ffe1d028)

**Comment by peke198822** [comment]
I will look for this setting in settings, services, it appears activated.

**Comment by peke198822** [comment]
I attached the .log here.
[kodi.log](https://github.com/user-attachments/files/16618568/kodi.log)
[kodi.old.log](https://github.com/user-attachments/files/16618569/kodi.old.log)

**Comment by peke198822** [comment]
> @peke198822No veo las imágenes, creo que debes adjuntarlas aquí en el navegador, no por correo electrónico.
> 
> Además, cree el archivo de registro de depuración, la guía se encuentra más arriba.
> 
> Supongo que instalaste alguna aplicación de Android que usa el mismo puerto que usa Kodi (puerto 9090), por lo que Kodi ya no puede usar ese puerto. Pero sin el archivo de registro, no puedo estar seguro.

Ummm I'll check this out, but I've always had all the same apps and haven't installed anything new, I'll check this out as you say, thanks.

**Comment by peke198822** [comment]
Hi Anton, regarding the ports coming from the TV, only the ones I attached, then port 9090 I don't see that any other applications use it.
![Screenshot_20240814_223844_com android chrome](https://github.com/user-attachments/assets/dbf52bf9-59b5-4629-9552-dbb6f20e73f0)

**Comment by peke198822** [comment]
Hi Anton, you are a genius, I found the apk that used this port, I really don't know what it's for but it lets me stop it, disable it no, but well knowing that it comes from here I can now fix it Attached is a photo of the apk, it is called UcService, Greetings and thanks again Antón.
![IMG_20240815_215333](https://github.com/user-attachments/assets/588114a8-9bd1-4959-8bb6-a287797a8744)

**Comment by antonsoroko** [comment]
@peke198822 awesome! Thanks for sharing this application name, so now other users can learn about this fix.

**Comment by peke198822** [comment]
Quiero añadir que la apk SddpService tambien utiliza el puerto de kodi no dejando cargar bien la apk.

![17240613649086526323830539461370](https://github.com/user-attachments/assets/a568767d-e72f-4081-9cff-ee783f942132)

**Comment by peke198822** [comment]
> I want to add that the SddpService apk also uses the kodi port without allowing the apk to load properly.
> 
> ![17240613649086526323830539461370](https://private-user-images.githubusercontent.com/96132309/359061505-a568767d-e72f-4081-9cff-ee783f942132.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNjE2ODgsIm5iZiI6MTcyNDA2MTM4OCwicGF0aCI6Ii85NjEzMjMwOS8zNTkwNjE1MDUtYTU2ODc2N2QtZTcyZi00MDgxLTljZmYtZWU3ODNmOTQyMTMyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDA5NTYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzMGFjOTAyNzY2MGVhM2E0OGUxY2Q5ZWFlMWE2NDc2ZWQ0NmJiMzIyMzRmY2I2ODVjODYzM2RkMGFjMmFjMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DvQZJPjwXt4R-abuArkWwINxmyECS05HTOivaxCSGVw)
