### ISSUE TITLE
Elementum stoped playing torrent files

### ISSUE THREAD

**Issue by mita4e** [elgatito/plugin.video.elementum#1057]
## Expected Behavior

Playing a video torrent files
## Current Behavior

Files downloads but video player not start
## Steps to Reproduce (for bugs)

1. Chose video file
2. Download
3. Error message - one or more items failed to play.

## Context

Video playback stopped suddenly. Previous night everything was fine and on the next day video not working. No Android updates(firmware, core, etc), no Kodi update, no Elementum update. Tried to reinstall Elementum, reinstall Kodi, factory reset on TV.
## Your Environment

* Version used:  Elementum 0.1.103

* Environment name and version: Kodi 21.0 Omega

* Operating System and version: Philips Android TV v12

* Link to Kodi debug log: https://paste.kodi.tv/abosadecag

**Comment by antonsoroko** [comment]
@mita4e 
In log I see that buffering was finished, then Elementum tried to start playback, but failed:
`Playback was unable to start after 60 seconds. Aborting...`

Unfortunately there is no error in log that can clarify why this happened. 

Also strange that factory reset did not help. 

But there is other new issue for Philips Android TV - #1056 
So probably something was updated.

**Comment by mita4e** [comment]
After force stop all internal apps like Youtube, Netflix, Rakuten and etc., Kodi start working . So probably some internal apps conflict occured.

**Comment by antonsoroko** [comment]
@mita4e from log
```
2024-08-07 15:21:09.650 T:14124   debug <general>: JSONRPC Server: Failed to bind IPv4 serversocket
```

so some app "took" port that Kodi uses for JSONRPC server (and elementum uses JSONRPC client to communicate with Kodi). without JSONRPC - elementum was not able to ask Kodi to run playback.
same issue as https://github.com/elgatito/plugin.video.elementum/issues/1056

Most likely Philips people added/updated some of "bloatware" and now port 9090 is taken by some internal app.

**Comment by antonsoroko** [comment]
@mita4e from log
```
2024-08-07 15:21:09.650 T:14124   debug <general>: JSONRPC Server: Failed to bind IPv4 serversocket
```

so some app "took" port that Kodi uses for JSONRPC server (and elementum uses JSONRPC client to communicate with Kodi). without JSONRPC - elementum was not able to ask Kodi to run playback.
same issue as https://github.com/elgatito/plugin.video.elementum/issues/1056

Most likely Philips added/updated some of "bloatware" and now port 9090 is taken by some internal app.

if you want to make your solution permanent - stop those apps one by one and then find which one took the port and then disable it.
