### ISSUE TITLE
Ошибка при передаче с другого плагина

### ISSUE THREAD

**Issue by spawnlmg** [elgatito/plugin.video.elementum#106]
Случайно попал на момент, когда elementum крашится при запуске торрента, который ему передает другой плагин. Проверил и под виндой и под андроидом, везде крашится. Вот лог
https://ru.files.fm/u/t5d6pr9d

**Comment by spawnlmg** [comment]
Разобрался, почему-то с некторыми торрентами с этого трекера так себя ведет элементум.
Вот такой торрент, проверь
https://ru.files.fm/u/4n5uxkse

**Comment by elgatito** [comment]
kodi.log ?
