### ISSUE TITLE
Download movies to seperate folders

### ISSUE THREAD

**Issue by VisionaiR3D** [elgatito/plugin.video.elementum#1060]
Elementum used to download files to seperate folders, with each folder named after the movie title. 
Nowadays it still does this for tvshows. But it dumps all movies in the same folder.

I'm using Nvidia shield on android.

Expected behavior
Download the movie batman from Tim Burton to \movies\batman (1989)\batman.mkv

Behavior
It downloads the movie to \movies\batman.mkv

It would keep things more organized.

**Comment by antonsoroko** [comment]
@VisionaiR3D 

>Elementum used to download files to seperate folders, with each folder named after the movie title.

i do not remember such option and i can't find such code or leftovers of such code.
maybe previously you downloaded only torrents that already had top level folder thus you got the impression that it is elementum who created such folder.

same for tv shows. but for tv shows torrents it is standard to have top level folder.

try to use any desktop bittorrent client to see how different torrents are organised.

---

but if course i might be wrong and many years ago elementum had such option.
(although such option would not work for manual torrent search (without TMDB info) for obvious reasons.)

**Comment by VisionaiR3D** [comment]
Yes well it was a long time ago. I believe it might have been around 0.1.87 when it was a feature.

**Comment by antonsoroko** [comment]
@VisionaiR3D I see. I will take a look into old code "snapshot".

**Comment by antonsoroko** [comment]
@VisionaiR3D so i do not see any code for movies about what you said. related code logic was not changed for last 7 years.

but for tv shows - you are correct, if you enable "move on complete" -  there is code to create new folder.

see https://github.com/elgatito/elementum/blame/v0.1.85/bittorrent/service.go#L1474

and compare to original (7 years old) code https://github.com/elgatito/elementum/blame/c2f57fde1544955fcd3abb32a7c8619f370c8d49/bittorrent/service.go#L749

for movies it always just move movie to destination folder.

my guess that you just downloaded movie's torrents that had top level folder. i have not other explanation.

**Comment by elgatito** [comment]
@VisionaiR3D Question is - you mean the "move on complete" option, when downloaded items are moved to another folder? 

It does make sense to always create a folder for moved content, even for movies. 

@antonsoroko  I am even thinking maybe it makes sense to create proper folders in the "download" folder for every item that is added to download queue. Then also we can add `nfo` file inside to describe the content.

**Comment by antonsoroko** [comment]
> I am even thinking maybe it makes sense to create proper folders in the "download" folder for every item that is added to download queue. Then also we can add nfo file inside to describe the content.

this might be more convenient than current situation where we have mix of files (movies) and folders (tv shows).

but then - what if i download several torrents for same movie/show? i guess if names are not same - then it is ok, but such situation can create some "mix" of files.

**Comment by VisionaiR3D** [comment]
Yes it was on "move on complete"
I am absolutely sure it used to create folders for each movie in an older version. I still have some directories with movies created this way. But Im having a hard time finding the version. It was around 2 years ago.

**Comment by VisionaiR3D** [comment]
Tvshows are still put into folders and is working great.

**Comment by VisionaiR3D** [comment]
Folders for movies is also better to store subtitles with the movie (better organizing)

**Comment by elgatito** [comment]
@VisionaiR3D I have added this functionality into version 0.1.105. Every movie would land into specific folders.
