### ISSUE TITLE
https://elementum.surge.sh/ is dead

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/plugin.video.elementum#1061]
https://elementum.surge.sh/ shows
```
503 Service Unavailable
No server is available to handle this request.
```

https://elementumorg.github.io/ works. 

But old link is used in repo description, in readme, in issue template and probably in more places.

**Comment by Anju023** [comment]
maybe this will help
https://bit.ly/3XQLHlH
I put the necessary dlls in the archive

**Comment by antonsoroko** [comment]
looks like it works now. but maybe it makes sense to migrate to second site.

**Comment by elgatito** [comment]
@antonsoroko They have issues from time to time, with uptime or deployments. 

There are not too many options that would not limit traffic or requests and won't just silently remove domain. 
We added github for backup purposes, but I am still not sure if we can rely on github.

**Comment by antonsoroko** [comment]
@elgatito i see. thanks for info.
