### ISSUE TITLE
[Request] Use persistent torrent ordering, based on added time

### ISSUE THREAD

**Issue by guindous** [elgatito/plugin.video.elementum#107]
Using web ui makes almost impossible using multiple section item, because on every refresh the list order changes.

## Expected Behavior
The torrent list, either webui and kodi torrent's option, should stick to an predictable order criteria.

## Current Behavior
Look a this screen cast to see the web ui behavior: https://screencast-o-matic.com/watch/cFnFogoL4k

## Possible Solution
Add a configurable torrent list order criteria. For example older fisrt, alfabetical order, etc.

## Steps to Reproduce (for bugs)
Just access to web ui or open Torrent Kodi option with a download list of 4 or 5 items to experiment the list order changes. 

## Context
Two functionalities are affected. First I use Kodi Torrent list to access to downloaded item. Every time I access order changes and that difficulties searching for Season multi-file like of torrents. In second order, multiple selection in WebUI is almost impossible. 

## Your Environment
* Version used: 0.0.43
* Environment name and version: Kodi 17
* Operating System and version: Ubuntu 14.04.5 LTS / Kernel info: Linux nena 4.4.0-112-generic i686 athlon i686 GNU/Linux

**Comment by elgatito** [comment]
This is a "projected" feature, that needs an implementation of torrents queue, as a proxy to gotorrent's list.

**Comment by antonsoroko** [comment]
It would be great to have persistent order of torrents in torrents listing inside the plug-in. Thank you in advance.

**Comment by elgatito** [comment]
Latest version is using ordering based on torrent added time.
