### ISSUE TITLE
request: RSS direct download and filter for BT/PT sites

### ISSUE THREAD

**Issue by i990049** [elgatito/plugin.video.elementum#1073]
If elementum RSS can direct RSS from BT/PT sites, auto/manual download option, plus filter of max/min peer, max/min file size, max/min age and word match/exclude such as "720P 2160P 3D UHD HDR DOVI", it will be convenient to direct download on TV BOX. Thank you.

**Comment by elgatito** [comment]
@i990049 Elementum is not doing any searches and it not based on websites. It is based on media library, taken from TMDB, and for each media item (movie / tv show) Elementum wants to get torrent sources, found by other addons (for example script.elementum.burst). 

Elementum is not pulling periodically and torrents and won't do that in the future. I think there should be other addons/software to do that.
