### ISSUE TITLE
V0.1.106 update on Kodi causing crash?

### ISSUE THREAD

**Issue by Djtrip83** [elgatito/plugin.video.elementum#1078]
Kodi tries to update Elementum and the whole of Kodi crashes after 10 seconds. I was able to get Kodi going by disabling Elementum, removing auto update and then using the current version I have (v0.1.104). Anyone experiencing something similar?

**Comment by antonsoroko** [comment]
Debug log file would be helpful. Otherwise hard to say something. Guide how to create log file was in issue template.

**Comment by Djtrip83** [comment]
Ok - will jump to v106 at the weekend manually. I was probably reporting an older issue.

PS: on GitHub mobile, there was no issue template and could not attach any file... Hence no log

**Comment by antonsoroko** [comment]
@Djtrip83 jfyi: you can update disabled addon via repository, so no need to download zip file. 
Or uninstall **with keeping configs** and install again.

>on GitHub mobile, there was no issue template and could not attach any file

This is sad news. Thanks for info.
