### ISSUE TITLE
Crash kodi elementul 

### ISSUE THREAD

**Issue by AlinnRT** [elgatito/plugin.video.elementum#1081]
Hi! I am experiencing problems with the Elementum plugin. After 5-10 minutes when I start a movie, I get crash and kodi closed.  With all kodi versions I've tried and I still get crash.  Can you help me? In the past I have used this plugin without problems
![17307170350943475344633331580760](https://github.com/user-attachments/assets/bf80fc88-c886-401e-bf43-4c134ae7a46c)
![17307171380027493485500047947950](https://github.com/user-attachments/assets/bacf68df-fc42-4899-b73e-8c9ac218420f)

**Comment by antonsoroko** [comment]
@AlinnRT you skipped all the important information that was requested in issue template. impossible to help you without this information. either add here all missing info from template (especially debug log file, guide was in template), or close this issue and create new issue with correct info.
template is available in browser (not in mobile app, for some reason).
