### ISSUE TITLE
Стримы не найдены

### ISSUE THREAD

**Issue by b0g0m0l** [elgatito/plugin.video.elementum#109]
На последних версиях Элементум и Бурст стримы не найдены. Выбраны kinozal и рутрекер. https://kinozal-tv.appspot.com открывается в браузере без проблем
https://paste.ubuntu.com/p/J6fHtTYpWK/

**Comment by ClassicDoctor** [comment]
Скорее всего дело в том,что на Кинозале стала нужна авторизация для поиска.
Если перейти по ссылке в логе,то кинет как раз на страницу логина.

**Comment by b0g0m0l** [comment]
может добавите в след. обновлениях? А как быть с рутрекер. lib?

**Comment by Kmartynov** [comment]
тут столкнулся с проблемой "стримы не найдены" на агентах щит, с остальным проблем нет

**Comment by elgatito** [comment]
Проблемы с Burst стоит репортить в соответствующий раздел: https://github.com/elgatito/script.elementum.burst/issues
