### ISSUE TITLE
"Use Memory" Download Storage Type

### ISSUE THREAD

**Issue by syneox** [elgatito/plugin.video.elementum#11]
This option is the most promising one and I can't wait to fully use it. Is it still in beta because I have tried to use it couple of times but with limited success?

My device is Xiaomi MIBOX3 with 2GB of RAM and Android TV 7.0. Memory size to use for each torrent is set to 350MB and download path is set to USB flash drive connected to a device. I am not sure why there is download path available because I don't see anything downloading there while playing. It does however when I use other storage options, like Use Files for example.

Some content plays fine but more often than less playback suddenly ends. I wonder if initial limit of 350MB is the reason why, I can put higher number but I think this memory option is dynamic by design, it should always have upcoming data available in memory and dynamically delete already watched parts?

Also, seems like pressing pause makes things slightly worse because playback usually breaks after resuming.

I'm looking forward for any troubleshooting you may need so please hit me with any request you may have.

Thank you.

EDIT: Some cleanup

**Comment by elgatito** [comment]
Download path is not only for downloading files, but also saving torrent files, so that path can be any folder.

Memory storage is more to less usable in the latest version. But the plugin itself is still in the beta state and error catched from time to time.
150Mb should be enough for memory storage if you have reliable internet connection. I have tested with 8gb files and it's played just fine.

The log file is not usable, better upload all kodi.log to paste.ubuntu.com, for example and better with debug mode enabled in kodi.

**Comment by elgatito** [comment]
This is the log for latest version?
Do you see playback stop when using file storage (if you tried).

**Comment by syneox** [comment]
yes, it is with latest version and here are two logs with Files option, both with SPMC and KODI. In both cases, torrent was choosen > buffering > elementum timed out > ok > buffering until 100% > play again > playback never starts even if I see torrent downloading in the background.

SPMC: http://paste.ubuntu.com/26193804/

KODI: http://paste.ubuntu.com/26193807/

**Comment by elgatito** [comment]
Your Kodi is setted up to bigger buffer size
`<memorysize>139460608</memorysize>`. That means Kodi expect to download 140Mb of data before starting a playback.

You can remove big buffer in Kodi (1), or setup Buffer size on Bittorrent tab in Elementum settings to about 150mb. You will have to wait until it's downloaded, but Kodi will be able to start then.

**Comment by syneox** [comment]
I understand this, reason why I used advancedsettings.xml was to try to improve Elementum for me and it was in SPMC only, KODI log was using defaults.

Now I am testing Elementum in SPMC and Quasar in KODI, both apps on same MIBOX3 device. Quasar downloading speeds are much faster than Elementum and I think this is mostly reason why it's not working for me.

I am curious to see any info from other users using Android boxes or Android TV devices like MIBOX or Shield?

**Comment by elgatito** [comment]
On Android it is better to use memory storage, due to system limitation on opened files and connections. Elementum's torrent client use different files management, compared to Quasar. So on Linux Elementum show good performance, on Android and Windows it's not so good.

**Comment by syneox** [comment]
Just a follow up:

After reverting to official v6.0 version of MIBOX3 (I was using v7.0 Nougat Beta's), making factory reset and installing latest v0.0.24 version of Elementum I have successfully used Memory Storage option and watched 9GB content without any problem! 

File Storage option is still slower than Quasar but I am really more interested in this Memory Storage more, incredible job!

**Comment by elgatito** [comment]
Should we close this issue?
