### ISSUE TITLE
Затыки во время просмотра

### ISSUE THREAD

**Issue by promidrol** [elgatito/plugin.video.elementum#110]
Приветствую.
Периодически случаются затыки (воспроизведение останавливается на миллисекунды замирает картинка и продолжает дальше) во время просмотра, причем всегда в разное время и абсолютно на разных типах и размерах файлов. Перегрева устройства нет (максимальная температура 45°С) С чем подобное может быть связано? Спасибо.

**Comment by elgatito** [comment]
Нужен kodi.log в режиме отладки.
https://kodi.wiki/view/Log_file/Easy

**Comment by promidrol** [comment]
Сейчас сделаю) Как понял надо запустить какой либо фильм дождаться затыков и скинуть лог верно?)

**Comment by elgatito** [comment]
Да

**Comment by promidrol** [comment]
Готово вот ссылка на лог https://paste.ubuntu.com/p/CPq23Mtr9S/
