### ISSUE TITLE
Cannot Install

### ISSUE THREAD

**Issue by Jcaezza** [elgatito/plugin.video.elementum#111]
After installing the Elementum add-on I get an error that says " Daemon Error (AttributeError: 'module' object has no attribute 'fork')." When I go to open the add-on it says that I need to restart Kodi which I have done and it keeps saying to restart. I am using Kodi 17 on an Apple TV 4K running iOS 11.3. The log file is https://paste.ubuntu.com/p/7Wf3CCrvRy/.

**Comment by elgatito** [comment]
The build for ios are not working. See earlier issues opened here.
