### ISSUE TITLE
[Bug] Different results between Elementum and Quasar

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#112]
## Current Behavior
Searching the same movie in both addons gives different results.
Quasasr give more results which doesn't exist in Elementum and they are more accurate.
(Same providers set in both Burst addons)
So the specific torrent's release that I needed, wasn't exist in Elementum list, while in Quasar it was there.

* Quasar results:
https://s18.postimg.org/c99eyjhpl/screenshot009.png
* Elementum results:
https://s18.postimg.org/xix19bdex/screenshot004.png

## Possible Solution
Maybe it relates to Burst, but I don't know so I opened it here for now.

## Steps to Reproduce (for bugs)
The example tested for this movie "Daddy's Home 2" (Daddys Home 2)
(It chosen from the Trakt Movie collection) 

## Your Environment
* Version used: Elementum 0.0.43 | Burst 0.0.16
* Environment name and version: Kodi 17.6
* Operating System and version: Win 10, 64 bit
* Link to Kodi debug log: https://paste.ubuntu.com/p/mdDhjQrJ6b

**Comment by Rick987** [comment]
Did you enable the sources in both quasar and elementum burst?

**Comment by burekas7** [comment]
Of course, I forgot to mention that.
For example, the "idop.e" itself gave different results.

**Comment by unster** [comment]
I have often similar problem and it happens that i.e. idope gives timeout in Elementum and is working normally in Quasar

**Comment by tomtomclub** [comment]
not always working at Quasar

**Comment by ianwrd4** [comment]
I find that Quasar always works fine, but Elementum streams dont play at all so there must be somethingf missing :-)

**Comment by elgatito** [comment]
Quasar is parsing stream resolution and quality in a different way. As well as Elementum is giving more filtering options to remove low-quality items. 
You won't get 100% same results. 

If you feel Elementum is filtering more than needed - create an issue for Elementum.
If you feel Burst is not finding something - create an issue for Burst.
