### ISSUE TITLE
Резкое падение FPS с 60 до 11(30) Всегда по разному

### ISSUE THREAD

**Issue by promidrol** [elgatito/plugin.video.elementum#113]
## Время ошибки
* Приблизительное время ошибки: 22.02.2018 16:16 - 16:18
## Your Environment

* Version used: Elementum 0.0.43 | Burst 0.0.16

* Environment name and version: Kodi 17.4

* Operating System and version: Android 7.1.1

* Link to Kodi debug log: https://paste.ubuntu.com/p/Cr86QCY6Jt/

**Comment by tomtomclub** [comment]
Well, for anyone that ever has an issue like this (regarding large thumbnails directory), here's what you do.

Delete or rename textures.db from your database folder

Delete thumbnails folder from userdata folder

This causes xbmc to re-download your thumbnails data.

**Comment by elgatito** [comment]
Maybe you have big CPU load because of big memory size (and buffer size). 
You can try limiting download speed or play with memory size.

**Comment by elgatito** [comment]
@promidrol есть изменения с версией 0.0.44 ?

**Comment by promidrol** [comment]
Еще не проверял, проверю отпишу тут.
