### ISSUE TITLE
[Request] Allow to not close torrent results window after selection

### ISSUE THREAD

**Issue by spawnlmg** [elgatito/plugin.video.elementum#114]
Сделайте пожалуйста так, чтобы при выходе из просмотра или при запуске просмотра, окно с найденными раздачами не закрывалось! Просто сейчас запустив выбранный торрент, если не понравилось качество/перевод/не хватает скорости, нажимаешь стоп в плеере и всё нужно начинать сначала, выбирать название, опять тратится время на поиск/скачивание/анализ торрентов, зачем? Просто нужно не закрывать окно с найденными раздачами! Если не нужно, нажимаешь назад, и попадаешь уже в предыдущее окно.
Я про это окно
![elementum](https://user-images.githubusercontent.com/23347625/36569877-3194209e-1838-11e8-9831-351cafebada5.jpg)

**Comment by elgatito** [comment]
Will not persist search results, but instead, in 0.0.48 added caching of search results, time of cache configurable in Kodi settings (by default 180 seconds). If will allow quick resolve of search results.

**Comment by elgatito** [comment]
Closing the issue.
