### ISSUE TITLE
[Request] Not able to start Elementum binary with fork() on Xbox

### ISSUE THREAD

**Issue by pigbait** [elgatito/plugin.video.elementum#115]
Element v.0.0.4.3 kodi 18.0 alpha1 on Xbox will not work

Here is the log from fresh start.

http://ix.io/O8Y

Let me know if this is correct log

**Comment by pigbait** [comment]
Any luck?

**Comment by flotron** [comment]
I don't know if there is some limitation with the xbox or it's just a problem of kodi's being in alpha. I don't know if xbox OS is windows?? or something different

**Comment by compyy** [comment]
Your answer is here:
"Python _subprocess module is not available on UWP, so an author of the add-on must work around or not use it for UWP"

**Comment by pigbait** [comment]
Thanks for posting this.. so from the sound of it unless the dev finds away to by pass python. We have no hope for this addon correct?

**Comment by elgatito** [comment]
So it's the same problem as it is with iOS/tvos. 
I don't have ideas how to deal with it. Hope someone will come over with an idea.

**Comment by deleder2k** [comment]
Has anyone come up with an idea to deal with it?

**Comment by pigbait** [comment]
I dont see this being fixed for awhile.. if they haven't found a solution for iOS..  it will take time for xbox..

**Comment by deleder2k** [comment]
Ok, thanks. If theres a working torrent downloader for Xbox one that could work, or is there an easy torrent streaming addon that works for xbox one?

**Comment by compyy** [comment]
simple way forward is not to use subprocess, i see that it is used to shutdown the process, may be if we have another way to shutdown the process, we dont need subprocess.

**Comment by elgatito** [comment]
@compyy subprocess is used to run binary in another process, because we need to run binary and python.

**Comment by compyy** [comment]
oh ok.

**Comment by elgatito** [comment]
Would be great, if someone can help to find a way to run the binary without subprocess.fork. 
This is related also to iOS.

Related to #4

**Comment by elgatito** [comment]
@pigbait @deleder2k @compyy @flotron please, try to download and install the plugin v0.0.50. 

There is a test fix for Xbox/iOS problem, so testing would be much appreciated!

**Comment by pigbait** [comment]
I will keep you posted later tomorrow.. 1 am here and just about to go to sleep.. thanks for this I really appreciate your work

**Comment by elgatito** [comment]
Try universal and send a log file then, if possible.

**Comment by pigbait** [comment]
Ok universal wont install. But windows x64 will.. but I get daemon error: memory error()

Here is a log

https://paste.kodi.tv/ipohocepon

**Comment by elgatito** [comment]
Ouch. I see, will make a fix for the next version.

**Comment by pigbait** [comment]
Lol awesome.  Thanks allot for your work on this btw.

**Comment by elgatito** [comment]
Can you try to reinstall from archive?
[plugin.video.elementum-0.0.51.windows_x64.zip](https://github.com/elgatito/plugin.video.elementum/files/2120599/plugin.video.elementum-0.0.51.windows_x64.zip)

**Comment by flotron** [comment]
Universal installs fine on me but I get memory error

**Comment by elgatito** [comment]
@flotron @pigbait can you try to install from zip archive from previous message?

**Comment by pigbait** [comment]
@elgatito same error 

Log: https://paste.kodi.tv/muwificota

**Comment by pigbait** [comment]
@foot on to get log go to kodi repo and under program addons you will see an addon called "Kodi logfile uploader"

**Comment by flotron** [comment]
Thanks https://paste.kodi.tv/zuzeluyuke

**Comment by elgatito** [comment]
Sorry, fix was not included.
Please, try this one:
[plugin.video.elementum-0.0.51.windows_x64.zip](https://github.com/elgatito/plugin.video.elementum/files/2120877/plugin.video.elementum-0.0.51.windows_x64.zip)

**Comment by pigbait** [comment]
https://paste.kodi.tv/efehibokiz

Same error

**Comment by elgatito** [comment]
One more fix.
[plugin.video.elementum-0.0.51.windows_x64.zip](https://github.com/elgatito/plugin.video.elementum/files/2120990/plugin.video.elementum-0.0.51.windows_x64.zip)

**Comment by pigbait** [comment]
Looks like the like memory error is fixed..
But new one came up..

https://paste.kodi.tv/usomelegal

**Comment by pigbait** [comment]
Keep me posted I'll keep testing

**Comment by flotron** [comment]
There are torrent clients for xbox like torrex in the Microsoft Store in the case if some third party app is needed

**Comment by gurhangur** [comment]
Can you find a solution to your number elgatito

**Comment by gurhangur** [comment]
did you develop a solution for Mr. elgatito xbox one?

**Comment by elgatito** [comment]
This plugin needs a binary to be run on a device. And it looks like this can't be done on xbox. 
So you can use another device for running Elementum (#2 ) and use xbox as a client of Elementum. Or just use another plugin, that will run on a box.

**Comment by pigbait** [comment]
Thanks for taking your time to see if it could work.. very pleased with what you have done and I want to  say thank you.

**Comment by elgatito** [comment]
There is a test work with a version that uses another approach to start Elementum.
https://github.com/elgatito/plugin.video.elementum/issues/669#issuecomment-1369529351

Would be great if someone could try it on Xbox.

**Comment by killwarez** [comment]
``> There is a test work with a version that uses another approach to start Elementum. [#669 (comment)](https://github.com/elgatito/plugin.video.elementum/issues/669#issuecomment-1369529351)
> 
> Would be great if someone could try it on Xbox.

Hi.

Just tested plugin.video.elementum-0.1.87.zip (universal, 260 mbs) on Xbox Series S and Kodi 20. Elementum doesn't start. Attached error from log while starting addon.

[Kodi20_XBoxSeriesX_ElementumStartLog.txt](https://github.com/elgatito/plugin.video.elementum/files/10578095/Kodi20_XBoxSeriesX_ElementumStartLog.txt)

**Comment by killwarez** [comment]
Maybe I'm wrong, but [looks like](https://github.com/xbmc/xbmc/pull/22023) Python calls to OS have to be updated within Kodi to make Xbox OS calls correctly.

**Comment by elgatito** [comment]
It looks that Python is modified not only for `fork` functionality. 
Probably will close this one, can't see other options we can run a binary.
