### ISSUE TITLE
Рандомно вылетает при просмотре фильма.

### ISSUE THREAD

**Issue by chetvertakov** [elgatito/plugin.video.elementum#116]
Некоторое время назад столкнулся с проблемой - при воспроизведении может произвольно выкинуть из фильма в меню. По ощущениям - как будто кто-то кнопку stop на пульте нажал.
Никакой зависимости не нашел - может спокойно проиграть без затыков целый 3часовой фильм, а может вылететь в начале 20-минутной серии.

Kodi 17.6 Android 7 (Nvidia Shield)
Лог: [https://paste.ubuntu.com/p/Ps296H8fBf/](url)
Пытался что-то выяснить на форуме XBMC.ru, насколько я понимаю, с такой проблемой я не один столкнулся.
Есть ли варианты вылечить?

**Comment by tomtomclub** [comment]
log not working

**Comment by chetvertakov** [comment]
@tomtomclub It will work, if You copy url to browser address bar

**Comment by tomtomclub** [comment]
There is database corruption detection try deleting it

**Comment by elgatito** [comment]
@chetvertakov in the log file movies are stopped at 97-99%, which is normal to me. Any more information about this?

**Comment by elgatito** [comment]
@chetvertakov I will close if there is no more information.
