### ISSUE TITLE
[Request] Clear search history

### ISSUE THREAD

**Issue by brentonv** [elgatito/plugin.video.elementum#117]
Best kodi addon ever works perfect. Just need a clear search feature if possible. Thanks

**Comment by tomtomclub** [comment]
well reboot and in setting clear it

**Comment by brentonv** [comment]
The only setting I'm aware if is clear cache and that doesn't work

**Comment by brentonv** [comment]
The only setting I'm aware of is clear cache and that doesn't work

**Comment by compyy** [comment]
i had a same issue, had to remove file in user data folder.

**Comment by brentonv** [comment]
Clear search is no big deal I'll try rename this as feature request not bug

**Comment by compyy** [comment]
basically in Quasar you can clear your search, strange its not here

**Comment by DONKEYOTI** [comment]
Compyy, Which file did you remove from the user data folder please?

**Comment by pavelmxx** [comment]
I think you can remove it from "history_queries" table in ".\userdata\addon_data\plugin.video.elementum\app.db" manually with some sql tools, like sqlite. Maybe possible to find tool for batch from cmd file and make some script for clearing. It seems like the easiest way.

**Comment by elgatito** [comment]
Please, try with 0.0.49.
There is a context menu item on each search query, which removes it from the history. 
Total cleanup with "one click" will be added later.

**Comment by brentonv** [comment]
Thank you Elgatito

**Comment by elgatito** [comment]
Closing this as a partly-implemented. 
There will be total cleanup handler in plugin Settings later.
