### ISSUE TITLE
Infinite loop, reloading configuration file (Android 6.0.1,Kodi 17.6,Elementum 0.0.43)

### ISSUE THREAD

**Issue by sparomba** [elgatito/plugin.video.elementum#118]
Android 6.0.1 (rooted), Kodi 17.6, Elementum 0.0.43

Kodi reports the installation process for Elementum was successful and then displays a "reloading Elementum configuration" notification. It fails with a beep (no error message is displayed) and the configuration window does not pop up. Kodi shows the "reloading Elementum configuration" notification again. Infinite loop...

Closing/Restarting Kodi and Rebooting the device does not clear the Error.

Disabling the Addon and opening the configuration window manually works. Changing the configuration and saving it works too. But when I re-enable the Addon, the same "reloading configuration" notification is shown and Kodi gets stuck in this loop again.

The Kodi log shows an Error at the first try of starting up Elementum:

`ERROR: GetDirectory - Error getting`

then Kodi restarts Elementum repeatedly, the Error is gone.

A Warning is shown during all tries of starting up the Addon:

`WARNING: [plugin.video.elementum] Destination path is a directory, expected previous binary file, removing...`

So maybe some path is set incorrectly?

Complete log file here: https://paste.ubuntu.com/p/yPqYwkFvqH/

**Comment by hoshsadiq** [comment]
Have you set the destination path in the settings in Elementum?

**Comment by sparomba** [comment]
Download&Library path are set. Tho I'd like Elementum to use the Memory (RAM) instead of the internal storage.

I don't think it has anything to do with the paths that you can set as a user via the user interface tho.


The Kodi Log/Warning says that the Addon is looking for a binary but finds a folder instead.

**Comment by tomtomclub** [comment]
lol its your pad or no space

**Comment by elgatito** [comment]
```
Addon settings not properly set, opening settings window
```

You should set normal download/library path. Non-network share. Even if you want to use memory storage.

**Comment by elgatito** [comment]
Closing without response.
