### ISSUE TITLE
[Bug] Plugin won't close "Resolving torrent files" from time to time

### ISSUE THREAD

**Issue by Enialixe** [elgatito/plugin.video.elementum#119]
С помощью провайдера Nova ищу на nnmclub.me сериал Stargate:Origins 1 сезон. После корректно отработавшего поиска плагин зависает на этапе Проверяем торрент файлы. Сам торрент нашёлся корректно, перепроверил через сайт, что-то не устраивает в нём сам Elementum. По логу не ясно, чем плох данный файл, лог https://pastebin.com/Taes1FEc. При необходимости могу скинуть сам торрент файл/тему с ним, если нет проблем с правообладателями.

**Comment by tomtomclub** [comment]
please engelish

**Comment by elgatito** [comment]
Я не вижу в логе никаких ошибок и информации тоже. 
Лог не полный?

**Comment by elgatito** [comment]
Please, try with 0.0.44

**Comment by Nemiroff** [comment]
[LOG](http://paste.kodi.tv/yayunivaxa.sql) from v0.0.45
hang on the resolve only from the tracker Nnm-club.lib

**Comment by elgatito** [comment]
Please, try with 0.0.46.

**Comment by Nemiroff** [comment]
on 0.0.46 nnm-club work fine! No more stuck on resolve torrents

**Comment by elgatito** [comment]
Closing as not getting more evidences.
