### ISSUE TITLE
Elementum is listening to other process

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#120]
I look into the logs and I see that Elementum is responding to interrupt and process that not relating to him.

For example, if I start/stop/finish watching a video in other video addon, it reacted to this statuses while it should not.
Also, almost each process that run by Quasar, Elementum catch it and responds like it was its process.

You can see it in the log file.
For example:
`01:34:25.784 T:4252  NOTICE: [plugin.video.elementum] DEBU  main         ▶ Notification     Got notification from xbmc/Player.OnPause: {"item":{"title":"4x06 The Laws of Gods and Men","type":"video","year":2014},"player":{"playerid":1,"speed":0}}`

`01:34:29.188 T:4252  NOTICE: [plugin.video.elementum] DEBU  main         ▶ Notification     Got notification from xbmc/Player.OnPlay: {"item":{"title":"4x06 The Laws of Gods and Men","type":"video","year":2014},"player":{"playerid":1,"speed":1}}`

`01:41:08.334 T:4252  NOTICE: [plugin.video.elementum] DEBU  main         ▶ Notification     Got notification from xbmc/Player.OnStop: {"end":true,"item":{"title":"4x06 The Laws of Gods and Men","type":"video","year":2014}}`

`01:41:08.386 T:4252  NOTICE: [plugin.video.elementum] DEBU  main         ▶ Notification     Got notification from xbmc/VideoLibrary.OnUpdate: {"id":-1,"type":"video"}`

`02:31:25.116 T:4252  NOTICE: [plugin.video.elementum] DEBU  main         ▶ Notification     Got notification from xbmc/Player.OnPause: {"item":{"title":"פאודה","type":"movie"},"player":{"playerid":1,"speed":0}}`

## Your Environment
* Version used: 0.0.43
* Environment name and version: Kodi 17.6
* Operating System and version: Win 10 , 64 bit
* Link to Kodi debug log: https://paste.ubuntu.com/p/RnNgnVrxYr

**Comment by elgatito** [comment]
Kodi sends notifications to any process, who is waiting for notifications. It's fine and expected.
