### ISSUE TITLE
[Bug] 'TV Shows -> Progress' isn't synchronizing and updating

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#121]
In comparing to Trakt progress section and SALTS implementation, the 'TV Shows -> Progress' in Elementum isn't synchronizing and updating as well.

## Current Behavior
Missed items: Elementum -> 'TV Shows -> Progress'
![s1](https://user-images.githubusercontent.com/13424257/37315893-f5402320-2653-11e8-8413-983dd31175a1.png)

## Expected Behavior
Actual Trakt Progress / Salts Implementation
![s2](https://user-images.githubusercontent.com/13424257/37315898-fc57f2d2-2653-11e8-9267-6728f01759cb.png)

## Possible Solution
I think the problem is because of using TMDB for TV Shows.
So the info of TV Shows should be based on Trakt or TVDB and not on TMDB.

## Your Environment
* Version used: Elementum 0.0.43
* Environment name and version: Kodi 17.6
* Operating System and version: Windows 10, 64bit
* Link to Kodi debug log: https://paste.ubuntu.com/p/vvXddFP6cY

**Comment by elgatito** [comment]
And what is wrong on that screenshot?

**Comment by elgatito** [comment]
Should be better after Progress page remastering.
