### ISSUE TITLE
Is this project already abandoned?

### ISSUE THREAD

**Issue by unster** [elgatito/plugin.video.elementum#122]
Hi @elgatito !

Thank you so much for all your work done so far. Due to the lack of recent commits, should be assume that Elementum is now in same state as Quasar and no further work is planned to develop new functionalities and to remove current issues?

**Comment by hoshsadiq** [comment]
I think so :(

**Comment by hoshsadiq** [comment]
I hope not :(

**Comment by elgatito** [comment]
Project is active, but i don't have enough time for it now.
Will continue when possible.
