### ISSUE TITLE
[Request] Artwork should be generated from Trakt and TMDB, if not available from single source

### ISSUE THREAD

**Issue by inkubux** [elgatito/plugin.video.elementum#124]
Some categories in Movies and TV Shows are not displaying any artwork 
 eg: 

- Movies -> Trending
- Movies -> Most Popular
- TV Shows -> Trending
- TV Shows -> Most Popular

The only ones working are the one coming from Trakt eg:
- Movies -> Watchlist
- TV Shows -> Watchlist

## Expected Behavior
Artwork should appear on every list of media

## Current Behavior
Artwork is not displayed in 
- Movies -> Trending
- Movies -> Most Popular
- TV Shows -> Trending
- TV Shows -> Most Popular

## Steps to Reproduce (for bugs)
1. Open Elementum
2. Navigate to Movies -> Trending
3. Observe the lack of artwork in all the different views of the themes. 

## Context
I was trying to sert widgets for my theme when discovered that the artwork was missing for the media files

## Your Environment

* Version used:
0.0.43
* Environment name and version:
Kodi Krypton Android /  Nvidia Shield 
* Operating System and version:
Android 7

## NOTES
I tried to deactivate the option use default artwork but it did not change anything.

**Comment by meteoro** [comment]
Same here, I generated a key in the TMDB API without success as well.

**Comment by felixgonsug** [comment]
Same here, any update??

**Comment by kyh3im** [comment]
Same here, i guess it has something todo with migration on new db engine

**Comment by elgatito** [comment]
Tmdb data is used in Trakt directories. So if Tmdb lacks some art - you will not see it.

**Comment by elgatito** [comment]
@inkubux @meteoro @felixgonsug @kyh3im I'd ask for a screenshot from anyone, to understand what you mean, where you miss something and where you have it (to see the difference). That would cost more than a ten log files.

**Comment by acsterf** [comment]
This is how it looks for me.
https://ibb.co/efiTW7

**Comment by elgatito** [comment]
@acsterf can you write the path how you get there (and where specifically)?

**Comment by acsterf** [comment]
@elgatito it occurs in various paths, for sure in TVShows/Movies> Trending/Collections. I'm using Elementum 0.0.45 in AFTV2 SPMC 16.4 and in Sony UHD 2017 Android TV Kodi 17.4. Same behavior in both.

**Comment by elgatito** [comment]
Trakt is not returning any images in their API. So when you select "Use Trakt information if available" you will not see images.
I have made a change to fill it with TMDB images. Will be added in 0.0.53.

**Comment by elgatito** [comment]
Added in 0.0.53.
