### ISSUE TITLE
Movie folder is empty

### ISSUE THREAD

**Issue by SG5** [elgatito/plugin.video.elementum#126]
First folder, `movies`, has only two dots that return to top level
Second folder, `serials`, contains many subfolders like `trends, top, popular, favorite`

## Your Environment

* Version used: 0.0.43

* Environment name and version: LibreELEC 8.2.4

* Operating System and version: Linux x86_64

* Link to Kodi debug log:

**Comment by elgatito** [comment]
Can;t reproduce it.
