### ISSUE TITLE
Elementum daemon crashed two times, then black screen. 

### ISSUE THREAD

**Issue by hmvs** [elgatito/plugin.video.elementum#127]
First of all thanks for the efforts and your work. 

## Expected Behavior
Should not have any crashes. 

## Steps to Reproduce (for bugs)
1. Selected movie "Downsizing" from Trends
2. Watched it more than 1  hour
3. Got "Elementum daemon crashed"
4. Movie continue playing.
5. In a couple of seconds movie stopped. 
6. Then I started movie again and selected to continue from that time when I had finished. 
7. Got crash, movie stopped again.
8. I've resumed it again. 
9. While starting I got black screen from my TV that there is no source any more on HDMI. 
10. Then TV got signal and I got some sound but screen was black.
11. Pressed Stop on remote and restarted movie.
12. Got just black screen and sound. 
13. Reboot.

## Environment

* Version used:
v0.0.43
* Environment name and version:
17.6 Git:20171114-a9a7a20
* Operating System and version:
Originally was KODIbuntu but upgraded to Ubuntu 16.04.4 LTS
* Link to Kodi debug log:
https://www.dropbox.com/s/ub8zr6x3fg8b47h/toreport.kodi.log?dl=1

**Comment by hmvs** [comment]
Reported crashes here: 
https://github.com/anacrolix/torrent/issues/240

**Comment by anacrolix** [comment]
Is https://github.com/anacrolix/go-libutp/commit/89a35c2661e99e6d1c14b1096bed2ed0d59a84a0 included and cgo enabled?

**Comment by hmvs** [comment]
@elgatito could you please answer?

**Comment by elgatito** [comment]
elementum 0.0.43 was built on 14th of February, so has all the packages for that date. 
CGO is always enabled.

**Comment by elgatito** [comment]
@anacrolix selected commit was added day later, so we don't have it. 
Will make a new version with the latest packages.

**Comment by hmvs** [comment]
@elgatito thank you

**Comment by hmvs** [comment]
@elegatio sorry for disturbing. But could you please publish new version?
