### ISSUE TITLE
Зависает намертво при просмотре

### ISSUE THREAD

**Issue by promidrol** [elgatito/plugin.video.elementum#129]
## Устройство на котором использую элементум.
RPI 3B (малинка)

## Резкое зависание при просмотре
Сейчас вроде начинает работать отлично, но через 5-7 минут просмотра малинка просто замирает и помогает только передергивание из сети. Из настроек сейчас: буфер - 50, как использовать - ОЗУ(250-не стартует, 100-стартует но мертво виснет через 10-15 минут просмотра, 50-виснем намертво через 5-7 минут)

## Your Environment
* Version used: Elementum 0.0.43 | Burst 0.0.16
* Environment name and version: KODI 17.6
* Operating System and version: Libreelec 8.2.4

* Link to Kodi debug log: https://paste.ubuntu.com/p/t5FRQjhSWD/

**Comment by elgatito** [comment]
Дополнение к зависаниям отношения прямого не имеет. Зависает система, 
Возможно из-за недостатка памяти. Для малины даже 100мб это может быть много, учитывая что тратится больше 100мб. 
Плюс, включенный в advancedsettings.xml размер буффера в 150мб выделяет для Коди 150*3 мб памяти. 
В общем меняйте настройки Коди и плагина в сторону уменьшения использования памяти.

**Comment by promidrol** [comment]
Да проблема решилась уменьшением буфера в advancedsettings.xml со 150 до 50. Теперь все работает прекрасно)

**Comment by bam80** [comment]
>Из настроек сейчас: буфер - 50, как использовать - ОЗУ(250-не стартует, 100-стартует но мертво виснет через 10-15 минут просмотра, 50-виснем намертво через 5-7 минут)

@promidrol можно уточнить, про какие размеры вы здесь говорите и где их менять?

**Comment by promidrol** [comment]
Это все настраивается в плагине elementum точнее в его настройках)
