### ISSUE TITLE
Problems with the Elementum subtitles addon?

### ISSUE THREAD

**Issue by patillerox** [elgatito/plugin.video.elementum#130]
Hi! First of all, thanks for your work, elgatito. 

Yesterday i moved into elementum. 

I configured everything as it was in quasar, but sadly i found that the subs part on elementum (with an ok user and password) doesnt show anything. While the addon of opensubtitles (installed separately from elementum) shows everything ok. 

Do you have any idea? 

Thanks! :)

**Comment by hmvs** [comment]
Used yesterday. Everything was fine. Have you tried to run custom search? Maybe it just haven't found the title of the movie.

**Comment by elgatito** [comment]
When I tested opensubtitles - it was working fine when login/password was entered correctly. Check your credentials once again.

**Comment by elgatito** [comment]
@patillerox if you still have the issue - post a kodi.log file (https://kodi.wiki/view/Log_file/Easy), if not - we can close the issue.

**Comment by elgatito** [comment]
Closing without response.
