### ISSUE TITLE
CVideoPlayerAudio::Process - stream stalled

### ISSUE THREAD

**Issue by hmvs** [elgatito/plugin.video.elementum#131]
## Steps to Reproduce (for bugs)
1. Dowload storage type: File
2. Buffer size: 20
3. Initial buffering: 300
4. Start some popular torrent (Downsizing)
5. Movie starts lagging while downloading
6. Got video stopped by itself after pause/resume
7. Restarted video 
8. Still lags

Checked CPU: seems to be everything fine:
https://www.dropbox.com/s/sdzhuejfuazr691/Screenshot%20from%202018-03-27%2023-44-05.png?dl=1

Logs have 
`CVideoPlayerAudio::Process - stream stalled`

Version used:
v0.0.43
Environment name and version:
17.6 Git:20171114-a9a7a20
Operating System and version:
Originally was KODIbuntu but upgraded to Ubuntu 16.04.4 LTS
Link to Kodi debug log:
https://www.dropbox.com/s/ens1iokmr306b2s/toreport3.kodi.log?dl=1

**Comment by elgatito** [comment]
```
Rate limiting upload to 520kB/s
```

Try increasing that limit. For 18gb files 520kb is too slow.

**Comment by hmvs** [comment]
@elgatito it's upload. not download. download speed was something around 30 MB per second (not megabit but megabyte). I thought disk speed was a bottleneck, so I had limited download to 8 megabyte per second. Unfortunately, that didn't work either.

**Comment by elgatito** [comment]
Try to run with a memory storage (let's say buffer: up to 50mb, memory size: 50-100mb). It's to take away your disks in the process.
If it runs fine then it's all about disk write/read (the reason there's a memory storage, really).

**Comment by hmvs** [comment]
With memory storage it works fine. But I would like to use disk to be able to preload file if there are not many peers around.

**Comment by elgatito** [comment]
@hmvs disk storage is done on the torrent engine's side, so we can't influence it and not controlling as well.

**Comment by elgatito** [comment]
Closing as no response here.

**Comment by hmvs** [comment]
Thanks for the response. Don't know how should I proceed.

**Comment by elgatito** [comment]
@hmvs  There is an issue in torrent library repository for slow download as per file storage: https://github.com/anacrolix/torrent/issues/234

**Comment by hmvs** [comment]
Seems it's different one. Download speed is super fast in my case, it is arround 30 megabytes per second. But playback is lagging

**Comment by hmvs** [comment]
And the most weird thing that I have 30% downloaded movie and it can still lag. 
`23:44:53.924 T:140199701952256  NOTICE: [plugin.video.elementum] [36mDEBU  bittorrent   ▶ progressEvent    [0m03bfc4: 43 MB/160 kB | Downloading (31.65%)`
And I was on the first minutes of the movie.

**Comment by elgatito** [comment]
Can you make another log with the latest plugin version?

**Comment by hmvs** [comment]
Sure. Will do it later today.

**Comment by hmvs** [comment]
Here is the fresh log:
https://www.dropbox.com/s/7awe7zru9lboy1d/toreport4.kodi.log?dl=1

I've tried to start and stop movie multiple times. Even when I had >20% of the movie I still had issues.
It showed the progress circle bar like 0 percentage is buffered and that's all, When I press pause/play it plays couple of seconds and then again stucks with this circle with 0. 
```
20:35:41.624 T:139761633117952   DEBUG: [plugin.video.elementum] Watched: 6.72700023651, duration: 8120.40625
20:35:41.681 T:139761599547136  NOTICE: [plugin.video.elementum] [36mDEBU  bittorrent   ▶ progressEvent    [0m03bfc4: 7.7 MB/0 B | Downloading (24.15%)
20:35:41.688 T:139761599547136  NOTICE: [plugin.video.elementum] [36mDEBU  bittorrent   ▶ progressEvent    [0m03bfc4: 6.1 MB/0 B | Downloading (24.83%)
20:35:41.688 T:139761599547136  NOTICE: [plugin.video.elementum] [36mDEBU  bittorrent   ▶ progressEvent    [0m03bfc4: 6.1 MB/0 B | Downloading (24.80%)
20:35:42.338 T:139761599547136  NOTICE: [plugin.video.elementum] [36mDEBU  bittorrent   ▶ progressEvent    [0m03bfc4: 6.1 MB/0 B | Downloading (24.18%)
20:35:42.625 T:139761633117952   DEBUG: [plugin.video.elementum] Watched: 6.50900030136, duration: 8120.40625
20:35:42.997 T:139761599547136  NOTICE: [plugin.video.elementum] [36mDEBU  bittorrent   ▶ progressEvent    [0m03bfc4: 4.6 MB/0 B | Downloading (24.83%)
20:35:43.002 T:139761599547136  NOTICE: [plugin.video.elementum] [36mDEBU  bittorrent   ▶ progressEvent    [0m03bfc4: 4.5 MB/0 B | Downloading (24.80%)
20:35:43.024 T:139761599547136  NOTICE: [plugin.video.elementum] [36mDEBU  bittorrent   ▶ progressEvent    [0m03bfc4: 4.7 MB/0 B | Downloading (24.19%)
20:35:43.627 T:139761633117952   DEBUG: [plugin.video.elementum] Watched: 6.72700023651, duration: 8120.40625
20:35:43.709 T:139761599547136  NOTICE: [plugin.video.elementum] [36mDEBU  bittorrent   ▶ progressEvent    [0m03bfc4: 5.3 MB/0 B | Downloading (24.83%)
20:35:43.710 T:139761599547136  NOTICE: [plugin.video.elementum] [36mDEBU  bittorrent   ▶ progressEvent    [0m03bfc4: 5.3 MB/0 B | Downloading (24.80%)
20:35:44.626 T:139761633117952   DEBUG: [plugin.video.elementum] Watched: 6.72700023651, duration: 8120.40625
```

**Comment by schirin** [comment]
HI all! Same issue with memmory playback large streams over 8-10Gigs usually...
https://paste.ubuntu.com/p/VpV9WwFtKg/

**Comment by elgatito** [comment]
@schirin When you see that bug next time, can you open http://192.168.0.1:65220/debug/bundle (replace 192.168.0.1 with your Kodi IP) and share downloaded log?

**Comment by elgatito** [comment]
@hmvs same to you. When you see a lag - open `/debug/bundle` and share the log.

**Comment by hmvs** [comment]
Sure!

**Comment by schirin** [comment]
[bundle_2018_6_18_21_55.log](https://github.com/elgatito/plugin.video.elementum/files/2113140/bundle_2018_6_18_21_55.log)

**Comment by elgatito** [comment]
@schirin the log is not complete, only a part of it.

**Comment by schirin** [comment]
The board hang during playback...so i dumped the log after hardreset.
Will post any new logs if will catch that issue another time.

**Comment by elgatito** [comment]
@hmvs @schirin I'm closing this issue, as it's one of those, that are influenced by file storage issue, which is reported to the torrent library issue tracker. 
Can be tracked here: https://github.com/anacrolix/torrent/issues/265
