### ISSUE TITLE
Wants to update to different os binary which breaks add-on

### ISSUE THREAD

**Issue by Pandoriaantje** [elgatito/plugin.video.elementum#132]
## Expected Behavior

Pull in update for currently installed os (linux x64)
## Current Behavior

Pulls in update for different os (windows x86) and leads to breakage.

## Steps to Reproduce (for bugs)

1.install gaia add-on/repo
2.install elementum from zip
3.reboot
4.new update message apears, and upon inspection, it wants to install windows x86 binary

## Context

Should not be able to 'update' to a different binary meant for different os then the one installed
## Your Environment

* Version used: Elementum 0.0.43.linux_x64

* Operating System and version: Libreelec 8.2.4 linux_x64, Kodi 17.6 git:a9a7a20

**Comment by Pandoriaantje** [comment]
The issue is that kodi want to pull in the windows binary although i'm running linux. So this breaks elementum.

Upon further investigation, believe the problem is with the gaia repo.
I've openend a bug report with them.
https://github.com/gaiaorigin/gaiaorigin/issues/3

**Comment by elgatito** [comment]
You can't use one userdata directory for different platforms. Each platform is unique for Elementum and needs own binary file.
Elementum is using own virtual repository for checking for new versions and getting updates.

**Comment by Pandoriaantje** [comment]
I am aware that every os/cpu/bitness has itsw own unique elementum binary. I am runni g the correct lunix x64 binary, but it seems that the way gaia set their repo, kodi believes there is an update available, and want to 'upgrade' to the windows x86 binary/userdata. 

So to me this looks like a problem with the way the gaia repo is set up.
Which makes this report invalid, and the error is on gaia's end.

**Comment by reiji01** [comment]
I have this same issue. I tried to uninstall the Elementum i installed via Gaia repo and reinstall via the zip file downloaded here but still getting the same issues.

**Comment by elgatito** [comment]
You should not use any external repository for Elementum updates. 
Install from zip file and you will have proper repository installed.
