### ISSUE TITLE
Хранить библиотеку на smb

### ISSUE THREAD

**Issue by Kmartynov** [elgatito/plugin.video.elementum#133]
У меня есть куча устройств, хотелось бы хранить для них общую библиотеку на шаре. Файлы качаю в память и не храню. В настройках плагина можно выбрать шару, но при таком выборе не работает. :(

**Comment by elgatito** [comment]
Для работы с smb/nfs нужно делать реализацию работы с этими протоколами. 
Единственный вариант работы - делать в системе ссылку на папку, чтоб система делала всё сама.

**Comment by Kmartynov** [comment]
Win и Линукс не вопрос, но как быть с андроид ТВ?

**Comment by Shkanik** [comment]
У меня три устройства,и нет возможности также хранить. Библиотеку  на nas,может сделаете поддержку nfs?

**Comment by elgatito** [comment]
Всё еще актуально:
> Для работы с smb/nfs нужно делать реализацию работы с этими протоколами.
> Единственный вариант работы - делать в системе ссылку на папку, чтоб система делала всё сама.

**Comment by Shkanik** [comment]
Реализовать с вашей стороны сложно? Shield не пишет на внешний носитель...
