### ISSUE TITLE
поиск сереала

### ISSUE THREAD

**Issue by Kmartynov** [elgatito/plugin.video.elementum#134]
Есть сериал marvel's agents of s.h.i.e.l.d, но вот беда на всех русскоязычных трекерах название его звучит как "Agents of S.H.I.E.L.D.", и результат выдачи, следовательно, пустой.

**Comment by elgatito** [comment]
С этим ничего не сделаешь если сайт не умеет правильно искать или не умеет правильно заполнять названия, это общая проблема с такими названиями.
