### ISSUE TITLE
Некорректное добавление сериалов в базу elementum. Дублирование данных сериалов в базе elementum.

### ISSUE THREAD

**Issue by pavelmxx** [elgatito/plugin.video.elementum#135]
Windows 7 64, Kodi 17.6, elementum-0.0.43, burst 0.0.16.
Пробовал все сносить и ставить elementum заново на чистую Kodi.

Имею 70 фильмов и 110 сериалов. Сразу скажу, что все вполне юзабельно, все проигрывает, все открывается, но:
При добавлении сериалов способом копирования strm файлов в путь папки библиотеки они не появляются в таблице "library_items " файла "app.db" в отличие от фильмов, которые туда попадают всегда. Как следствие, не добавляются новые серии (если должны без trakt), т.к. сериалы не являются частью библиотеки. При добавлении сериалов через синхронизацию trakt или GUI elementum все отлично.
Но при любом способе добавления сериалов, записи в таблице "library_uids" файла "app.db" начинают дублироваться при каждом обновлении библиотеки elementum, которое нельзя отключить и которое происходит каждый раз после запуска Kodi. В результате размер файла "app.db" увеличивается на 1 мегабайт после каждого старта Kodi, а синхронизация history с trakt показывает 2500 plays для сериала на 25 серий, более того, расставляет неправильные "watched" на половину библиотеки. А именно, ставит "watched" на часть, недосмотренных до конца, сериалов. Видимо из-за "2500 plays" API trakt дуреет.

Обновление базы elementum производит какие-то нелогичные изменения в "app.db", а в логах ничего конкретного не видно. Тут после очередного ручного обновления из настроек elementum, в "library_uids" прибавилось 27 строк. По логам вот:
```
17:46:52.460 T:9152  NOTICE: [plugin.video.elementum] DEBU  main         ▶ Notification     Got notification from xbmc/VideoLibrary.OnScanFinished: null
17:47:21.667 T:9152  NOTICE: [plugin.video.elementum] DEBU  library      ▶ func2            Fetched 70 movies from Kodi Library in 33.0042ms
17:47:21.667 T:9152  NOTICE: [plugin.video.elementum] DEBU  library      ▶ RefreshUIDs      UIDs refresh finished
17:47:21.679 T:9152  NOTICE: [plugin.video.elementum] DEBU  library      ▶ func1            Fetched 3 seasons from Kodi Library in 6.0008ms
17:47:21.688 T:9152  NOTICE: [plugin.video.elementum] DEBU  library      ▶ func1            Fetched 24 episodes from Kodi Library in 10.0012ms
17:47:21.703 T:9152  NOTICE: [plugin.video.elementum] DEBU  library      ▶ func2            Fetched 2 shows from Kodi Library in 36.0046ms
17:47:21.703 T:9152  NOTICE: [plugin.video.elementum] DEBU  library      ▶ RefreshUIDs      UIDs refresh finished
17:47:21.703 T:9152  NOTICE: [plugin.video.elementum] DEBU  library      ▶ Refresh          Library refresh finished
```
Видно, что 27 новых строк = 3 сезона + 24 эпизода.

Пользуясь случаем: и уберите, пожалуйста, этот Pride 2004 https://www.themoviedb.org/tv/1-pride , под гордым номером один на themoviedb.org, из стоковой библиотеки.

**Comment by elgatito** [comment]
Вообще ничего не понял, каким ручным копированием какие файлы куда и как добавляются.

**Comment by pavelmxx** [comment]
Про файлы *.strm из "папка для библиотеки" оно же "Library path" . Такого вида и содержимого:

> "Accident Man (2018).strm"
> plugin://plugin.video.elementum/library/movie/play/455236

Может оно так и не задумывалось, но для удобства переноса библиотеки фильмов на другие устройства с Kodi удобно забирать из "папка для библиотеки" файлы *.strm, и класть их в такую же папку на другой компьютер с Kodi. Весьма себе успешно переносится. И как метод бэкапа библиотеки удобно. Собственно, про файлы только это было. Остальное не про файлы.

**Comment by elgatito** [comment]
Синхронизация переносомм файлов не планировалась и не реализовывалась. 
Для синхронизации между устройствами лучше использовать Trakt. Другие варианты на свой страх и риск.
