### ISSUE TITLE
[Request] Save OSDB subtitles for further usage

### ISSUE THREAD

**Issue by bam80** [elgatito/plugin.video.elementum#137]
Being set, the subtitles settings (selected subtitle itself, time offset) are not saved and reset once video stops

**Comment by elgatito** [comment]
You give too much information about the problem.
Subtitles are controlled by Kodi.

**Comment by bam80** [comment]
@elgatito 
Sorry for that, I'm ready to supply information needed.
I tested with OpenSubtitles add-on. When subtitles are set for a file playing locally, all their settings are saved for the file, and will be restored when the file is played later.
It doesn't happen for a video played by Elementum.

**Comment by elgatito** [comment]
@bam80 all the plugin does - give srt file to Kodi. Selection of files and other settings is done fully by Kodi. All we can take from Kodi - subtitles language settings (in the Regional settings of Kodi you can select what language to use for subtitles). So Elementum is search for subtitles and give that file to Kodi. 
Enable subtitles by default and which language to use - it's all controlled by Kodi.

**Comment by elgatito** [comment]
Please, try 0.0.46. There is a separate setting in Elementum settings to set up language for searching OSDB. If not set - will use Kodi Subtitles languages setting, as it was before 0.0.46.

**Comment by bam80** [comment]
Thanks Denis, I'll try

**Comment by bam80** [comment]
Hm, I'm afraid still doesn't work for me. I didn't add torrent to Library though.
I set 'en' language for searching OSDB, then started torrent and chose appropriate subtitle. If I stop the movie and immediately start it again - I can resume to the previous position, of the same torrent. But previously set subtitle and it's settings are lost.
PS: in-memory storage was used

**Comment by elgatito** [comment]
@bam80 as I've said before, that is controlled by Kodi. Kodi is requesting for subtitles, plugin is giving it. 
Saving subtitles someway and forcing it's usage is a big work, and will raise more issues here.

**Comment by elgatito** [comment]
If subtitles used in traditional way - downloading and deletion of it is done by Kodi.
If you use auto-download feature (build in Elementum), you can configure to leave subtitles files.

We cannot control Kodi to leave files.
