### ISSUE TITLE
[request] keep .torrent files

### ISSUE THREAD

**Issue by bam80** [elgatito/plugin.video.elementum#138]
Feature request: keep .torrent files even if torrent Data was deleted, or downloaded to in-memory storage.
These .torrent files could be used later to easy resume playing after it was stopped.

For now, Torrents menu items are deleted too if torrent Data is deleted.
For in-memory storage, there is even no possibility to keep Torrents menu item after playing stops. It's a pain to resume playing after that.

**Comment by elgatito** [comment]
@bam80  When you open stream for specific movie/episode (from Kodi library, or from Elementum lists, not just a specific torrent-file or magnet), it's saved in the database and linked to played item. So next time you select same movie/episode - Elementum will ask to use previous torrent/magnet.

For memory-storage there is no way to keep torrents, each torrent needs own memory allocated. 
There are no plans to keep torrent files somewhere (except the way it's done now), it needs a lot of changes and will bring more issues to keeping things clean.

**Comment by bam80** [comment]
I just see no other way to easy resume playing for memory-storage torrents after stop, do you?

**Comment by syneox** [comment]
But it is easy, when you choose to watch same title Elementum will ask you to reuse already downloaded torrent and even offer you to continue from the point you've stopped watching before, is that what you are missing?

**Comment by elgatito** [comment]
@bam80 no, there is no way if you don't use the Kodi library, or your Kodi does not resume playback when you start playback from Elementum lists. 

If you want to resume memory-storaged torrent - add it to Kodi library, then Elementum will sync playback progress and will resume playback from saved place.
