### ISSUE TITLE
[Request] Allow disabling of .torrent auto-load on startup

### ISSUE THREAD

**Issue by johndoe71rus** [elgatito/plugin.video.elementum#139]
вопрос.
Если после просмотра не удалять скачанные файлы, закачка в файл. То при следующем запуске коди в углу вертится "бегунок" от элементума. Типа что-то качает.
Захожу в раздел элементума "торрент" там тот торрент что смотрел раньше. Кликаю на него, для сериала предлагает выбрать серию из списка. Отказываюсь и на вопрос удалить файлы снова говорю "нет".
 Бегунок в углу исчезает.
Что он качает при запуске? Можно обойтись без этих манипуляций?

**Comment by elgatito** [comment]
https://kodi.wiki/view/Log_file/Easy

**Comment by johndoe71rus** [comment]
ок. Я думал ты сразу скажешь по логике работы. 
Вот лог, https://paste.ubuntu.com/p/rzxcNCDrvZ/ как и описывал.
Запускается элементум начинает подкачивать торрент. Потом вручную отключил.

**Comment by elgatito** [comment]
Попробуйте, пожалуйста, с 0.0.45, если остаётся то попрошу еще раз новый лог.

**Comment by johndoe71rus** [comment]
как только сохранил изменения настроек для сохранения в файлы. Плагин тут же вспомнил про мр робот, которого я закончил смотреть неделю назад. Тогда удалил все скачанное и переключился снова на память. А вот прям сейчас он про него вспомнил и начал опять качать/проверять.
https://paste.ubuntu.com/p/kjYvgf99fp/
опять по тому же алгоритму снова удалил робота. Сейчас еще раз попробую запустить коди с 45 элементумом.

**Comment by johndoe71rus** [comment]
https://paste.ubuntu.com/p/6Vm4tDXjhw/
не помогло. Опять вспомнил про робота.

**Comment by johndoe71rus** [comment]
прошу прощения за введение в заблуждение.
Выяснил причину. В папке "путь для загрузок"/torrents я сам оставил торрент файл. Изначально там был файл с непроизносимым названием и удалялся каждый раз. Что бы не проводить поиск, я его переименовал и оставил в этой папке. 
Так что элементум делал то что от него ожидаемо. То есть он как любой торрент клиент делал проверку содержимого и автоматом начинал качать?

**Comment by elgatito** [comment]
@johndoe71rus elementum при старте читает из папки, которая указана для торрентов, и добавляет всё в работу, если торрент новый - будет качать, если старый, проверит и будет раздавать (если включена раздача), это еще сохранилось от Quasar. В планах есть хранить именно очередь, а не заполнять её из сохраненных торрент-файлов, но пока так. Для записи в память подгрузка старых файлов не включается, потому что на каждый нужна память.

**Comment by elgatito** [comment]
Закрываем тикет?

**Comment by johndoe71rus** [comment]
да, раз "выключателя" для фичи еще не реализовано. Закрываем

**Comment by elgatito** [comment]
Option is added to 0.0.53
