### ISSUE TITLE
Clicking recent shows crashes the addon

### ISSUE THREAD

**Issue by madeforonlyyou** [elgatito/plugin.video.elementum#14]
## Current Behavior

Clicking recent shows crashes the addon
529 00:48:04.878 T:1524364272  NOTICE: [plugin.video.elementum] panic: runtime error: invalid memory address or nil pointer dereference
530 00:48:04.879 T:1524364272  NOTICE: [plugin.video.elementum] [signal SIGSEGV: segmentation violation code=0x1 addr=0xc pc=0x55ae60]
531 00:48:04.879 T:1524364272  NOTICE: [plugin.video.elementum]
532 00:48:04.880 T:1524364272  NOTICE: [plugin.video.elementum] goroutine 5261 [running]:
533 00:48:04.880 T:1524364272  NOTICE: [plugin.video.elementum] github.com/elgatito/elementum/tmdb.listShows.func1(0x11fdc170, 0x4, 0x12401260, 0x8ba4eb, 0xb, 0x11fdc140, 0x11ebc518, 0x12012060, 0x28, 0x11ea20d0
534 00:48:04.881 T:1524364272  NOTICE: [plugin.video.elementum]     /ext-go/1/src/github.com/elgatito/elementum/tmdb/show.go:227 +0x27c
535 00:48:04.881 T:1524364272  NOTICE: [plugin.video.elementum] created by github.com/elgatito/elementum/tmdb.listShows
536 00:48:04.881 T:1524364272  NOTICE: [plugin.video.elementum]     /ext-go/1/src/github.com/elgatito/elementum/tmdb/show.go:192 +0x440
537 00:48:04.887 T:1524364272  NOTICE: [plugin.video.elementum] System information: linux_arm-7 4.9.29-10-osmc
538 00:48:04.887 T:1524364272  NOTICE: [plugin.video.elementum] Kodi build version: 17.5
539 00:48:04.887 T:1524364272  NOTICE: [plugin.video.elementum] OS type: Linux
540 00:48:04.888 T:1524364272  NOTICE: [plugin.video.elementum] uname: ('Linux', 'osmc', '4.9.29-10-osmc', '#1 SMP PREEMPT Mon Oct 9 02:18:18 UTC 2017', 'armv7l', '')
541 00:48:04.894 T:1937765360   ERROR: [plugin.video.elementum] Traceback (most recent call last):
542 00:48:04.894 T:1937765360   ERROR: [plugin.video.elementum]   File "/home/osmc/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/navigation.py", line 184, in run
543 00:48:04.894 T:1937765360   ERROR: [plugin.video.elementum]     data = _json(url)
544 00:48:04.894 T:1937765360   ERROR: [plugin.video.elementum]   File "/home/osmc/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/navigation.py", line 127, in _json
545 00:48:04.895 T:1937765360   ERROR: [plugin.video.elementum]     with closing(urllib2.urlopen(url)) as response:
546 00:48:04.895 T:1937765360   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
547 00:48:04.895 T:1937765360   ERROR: [plugin.video.elementum]     return opener.open(url, data, timeout)
548 00:48:04.895 T:1937765360   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/urllib2.py", line 431, in open
549 00:48:04.895 T:1937765360   ERROR: [plugin.video.elementum]     response = self._open(req, data)
550 00:48:04.896 T:1937765360   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/urllib2.py", line 449, in _open
551 00:48:04.896 T:1937765360   ERROR: [plugin.video.elementum]     '_open', req)
552 00:48:04.896 T:1937765360   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
553 00:48:04.896 T:1937765360   ERROR: [plugin.video.elementum]     result = func(*args)
554 00:48:04.896 T:1937765360   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/urllib2.py", line 1227, in http_open
555 00:48:04.896 T:1937765360   ERROR: [plugin.video.elementum]     return self.do_open(httplib.HTTPConnection, req)
556 00:48:04.897 T:1937765360   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/urllib2.py", line 1200, in do_open
557 00:48:04.897 T:1937765360   ERROR: [plugin.video.elementum]     r = h.getresponse(buffering=True)
558 00:48:04.897 T:1937765360   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/httplib.py", line 1111, in getresponse
559 00:48:04.897 T:1937765360   ERROR: [plugin.video.elementum]     response.begin()
560 00:48:04.897 T:1937765360   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/httplib.py", line 444, in begin
561 00:48:04.898 T:1937765360   ERROR: [plugin.video.elementum]     version, status, reason = self._read_status()
562 00:48:04.898 T:1937765360   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/httplib.py", line 408, in _read_status
563 00:48:04.898 T:1937765360   ERROR: [plugin.video.elementum]     raise BadStatusLine(line)
564 00:48:04.898 T:1937765360   ERROR: [plugin.video.elementum] BadStatusLine: ''
565 00:48:04.898 T:1937765360   ERROR: [plugin.video.elementum]
## Steps to Reproduce (for bugs)

1. Open the addon
2.  Go to TV shows
3. Click on recent shows
4.

## Your Environment

  3 00:45:40.665 T:1958526976  NOTICE: Starting Kodi (17.5). Platform: Linux ARM (Thumb) 32-bit
  4 00:45:40.665 T:1958526976  NOTICE: Using Release Kodi x32 build (version for Raspberry Pi)
  5 00:45:40.665 T:1958526976  NOTICE: Kodi compiled Oct 29 2017 by GCC 4.9.2 for Linux ARM (Thumb) 32-bit version 3.16.39 (200743)
  6 00:45:40.666 T:1958526976  NOTICE: Running on Open Source Media Center 2017.10-1, kernel: Linux ARM 32-bit version 4.9.29-10-osmc
  7 00:45:40.666 T:1958526976  NOTICE: FFmpeg version/source: ffmpeg-3.1-kodi
  8 00:45:40.666 T:1958526976  NOTICE: Host CPU: ARMv7 Processor rev 4 (v7l), 4 cores available

**Comment by elgatito** [comment]
Do you see this error with the latest version?

**Comment by elgatito** [comment]
Should be fixed with Client creation checks.
