### ISSUE TITLE
Adult Contents

### ISSUE THREAD

**Issue by usphil** [elgatito/plugin.video.elementum#140]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

Hi, Does this addon support adult contents like Quasar. I did a search with very few results, most can not play (no seed) while they're available in the website.

**Comment by elgatito** [comment]
Elementum does not filter by keywords, other than "trailer" and something like that to remove non-relevant results.
