### ISSUE TITLE
[Bug] Possibly faulty port management

### ISSUE THREAD

**Issue by diabl0w** [elgatito/plugin.video.elementum#143]
## Expected Behavior

Elementum torrent client should utilize a port within the given port range set in elementum settings

## Current Behavior

Elementum torrent client assigns a random port

## Possible Solution

A similar issue was reported with quasar here: https://github.com/scakemyer/plugin.video.quasar/issues/744
However, that issue is different in the sense that quasar is giving out a static port and the reason is given that libtorrent uses that port by default (different than this issue because elementum is able assign random ports)

## Steps to Reproduce (for bugs)

1. Disable automatic port selection in settings
2. Set desired port range
3. Reboot or dont reboot, doesnt matter
4. Go to elementum UI web page and see that a random port is being used out of range

## Context

This greatly affects download speeds because a user cant set a static port in the router to open for elementum, so elementum is trying to run through a closed port

## Your Environment

* Version used: Latest

* Environment name and version: Kodi 17/18

* Operating System and version: LibreELEC

* Link to Kodi debug log:

**Comment by elgatito** [comment]
Where is the log file?

**Comment by diabl0w** [comment]
<code>17:01:42.374 T:3667792768  NOTICE: [plugin.video.elementum] [36mDEBU  bittorrent   ▶ configure        [0mBitClient config: &torrent.Config{DataDir:"/storage/downloads", ListenHost:(func(string) string)(0x7a6d84), ListenPort:0, NoDefaultPortForwarding:true, DisableTrackers:false, DisablePEX:false, NoDHT:true, DhtStartingNodes:(dht.StartingNodesGetter)(0x5aa1d0), NoUpload:false, DisableAggressiveUpload:false, Seed:true, UploadRateLimiter:(*rate.Limiter)(0x11a47090), DownloadRateLimiter:(*rate.Limiter)(0x11a47040), PeerID:"-GT0001-T3HEYHK3B72R", DisableUTP:false, DisableTCP:false, DefaultStorage:(*memory.Storage)(0x12095460), EncryptionPolicy:torrent.EncryptionPolicy{DisableEncryption:false, ForceEncryption:false, PreferNoEncryption:false}, IPBlocklist:iplist.Ranger(nil), DisableIPv6:false, DisableIPv4:false, DisableIPv4Peers:false, Debug:false, HTTP:(*http.Client)(nil), HTTPUserAgent:"Elementum/v0.0.44", ExtendedHandshakeClientVersion:"", Bep20:"-GT0001-", NominalDialTimeout:0, MinDialTimeout:0, EstablishedConnsPerTorrent:0, HalfOpenConnsPerTorrent:0, TorrentPeersHighWater:0, TorrentPeersLowWater:0, HandshakesTimeout:0, PublicIp4:net.IP(nil), PublicIp6:net.IP(nil)}
17:01:42.379 T:3667792768  NOTICE: [plugin.video.elementum] INFO  bittorrent   ▶ configure        [0mClient created successfully
17:01:42.381 T:3667792768  NOTICE: [plugin.video.elementum] [36mDEBU  bittorrent   ▶ configure        [0mClient listening on: 0.0.0.0:39769
17:01:42.383 T:3667792768  NOTICE: [plugin.video.elementum] [36mDEBU  bittorrent   ▶ configure        [0mClient listening on: [::]:39769
17:01:42.385 T:3667792768  NOTICE: [plugin.video.elementum] [36mDEBU  bittorrent   ▶ configure        [0mClient listening on: 0.0.0.0:39769
17:01:42.386 T:3667792768  NOTICE: [plugin.video.elementum] [36mDEBU  bittorrent   ▶ configure        [0mClient listening on: [::]:39769
17:01:42.387 T:3667792768  NOTICE: [plugin.video.elementum] [GIN] 2018/04/23 - 21:01:42 | 200 |    9.573789ms |       127.0.0.1 | GET      /cmd/clear_page_cache
</code>

that is when setting port between 6881-6891

**Comment by diabl0w** [comment]
Edit: upnp doesn't seem to work either (my transmission client works so it's not a upnp issue with my router) the log file says <code>17:08:26.892 T:3667792768  NOTICE: [plugin.video.elementum] portfwd.go:32: discovered 0 upnp devices, map[]</code>

**Comment by elgatito** [comment]
Should be better with 0.0.45.

**Comment by Pepe-Lucas** [comment]
I was going to report same issue until I read this one. Fortunately will be fixed in next release. static port is very important for users like me who use VPN and need a static port to get high speed since most of the VPN services only allow you to open 3 to 5 ports.

**Comment by diabl0w** [comment]
^exactly my situation... makes me wonder why no one else is bringing this situation up. are people using this without VPN?

**Comment by elgatito** [comment]
> ^exactly my situation... makes me wonder why no one else is bringing this situation up. are people using this without VPN?

Because before 0.0.44 it was working fine, before we upgrade to the latest version of torrent library.

**Comment by diabl0w** [comment]
okay awesome, I'm a new user so I wasn't aware. Thanks for the update, looking forward to next release

**Comment by diabl0w** [comment]
fixed 0.45

**Comment by elgatito** [comment]
Please, try with the 0.0.46, library was fixed to avoid listening the TCPv6 when not needed.
