### ISSUE TITLE
[Request] Fallback to default language for TMDB responses

### ISSUE THREAD

**Issue by Shut3n** [elgatito/plugin.video.elementum#146]
I suppose Elementum doesn't have Catalan translation, cause it falls back to English for menus. But on genres submenu, text on item is missing even the English

It doesn't occurs when kodi set to Spanish or English, does make well the change

Not sure if occurs for other languages not included on the addon

**Comment by elgatito** [comment]
Names of genres comes from the TMDB, probably, they are not having that language. I will look if it's possible to fallback to default language.

**Comment by elgatito** [comment]
@Shut3n  do you have problems with language for, say, list of movies, or movie information (when you browse through Elementum)? Or it's only about genres list?

**Comment by Shut3n** [comment]
It's only about genres text, no text appears when kodi is set in Catalan language (it appears well when set to English or Spanish)

**Comment by elgatito** [comment]
Added fallbacks in v0.0.61.
