### ISSUE TITLE
[Request] New 'language' category for Movies and TV Shows

### ISSUE THREAD

**Issue by Shut3n** [elgatito/plugin.video.elementum#148]
To list movies and series by their original speaking (English, Spanish, French, German, Chinese,..). It can be as Movies or TV Shows new submenus, like trending, popular, genres ones

**Comment by elgatito** [comment]
I don't understand this issue.

**Comment by Shut3n** [comment]
A list classified by different languages. For example:
Languages
  |___ English
  |___ French
  |___ Spanish
  |___ Hindi
........

Based on the language of original version. Perhaps is possible to extract this info from TMDB, but searching by original title

**Comment by elgatito** [comment]
Please, see the 0.0.46 for Languages/Countries menu. But take into mind - we take languages from TMDB, and we show what they give us. Sometimes output looks bad.
