### ISSUE TITLE
Не работает плагин внезапно

### ISSUE THREAD

**Issue by yatsek20** [elgatito/plugin.video.elementum#149]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

**Comment by yatsek20** [comment]
Добрый день. Сегодня плагин начал выдавать ошибку на версии 0,44 , вчера все было окей. настройки не менял плагин не обновлял, после данной ошибки обновил плагин на ту же версию из репозитария но проблема осталась. Вроде бы ошибка с местом на сохранение ,но ни чего не менял .
вот ошибка
17:43:45.569 T:3641631584   ERROR: TypeError: 'NoneType' object has no attribute '__getitem__'
17:43:47.604 T:3215979360  NOTICE: [plugin.video.elementum] INFO  main         ▶ main             [0mStarting Elementum daemon
17:43:47.617 T:3215979360  NOTICE: [plugin.video.elementum] INFO  main         ▶ main             [0mVersion: v0.0.44 Go: go1.10.1
17:43:47.618 T:3215979360  NOTICE: [plugin.video.elementum] INFO  config       ▶ Reload           [0mReloading configuration...
17:43:47.732 T:3333649248   ERROR: GetDirectory - Error getting
17:43:47.733 T:3333649248   ERROR: Previous line repeats 3 times.
17:43:47.733 T:3333649248   ERROR: GetDirectory - Error getting description
17:43:47.733 T:3333649248   ERROR: GetDirectory - Error getting include
17:43:47.733 T:3333649248   ERROR: Previous line repeats 1 times.
17:43:47.733 T:3333649248   ERROR: GetDirectory - Error getting description
17:43:47.733 T:3333649248   ERROR: GetDirectory - Error getting include
17:43:47.733 T:3333649248   ERROR: GetDirectory - Error getting description
17:43:47.733 T:3333649248   ERROR: Previous line repeats 1 times.
17:43:47.733 T:3333649248   ERROR: GetDirectory - Error getting include
17:43:47.734 T:3333649248   ERROR: Previous line repeats 3 times.
17:43:47.734 T:3333649248   ERROR: GetDirectory - Error getting description
17:43:47.734 T:3333649248   ERROR: Previous line repeats 5 times.
17:43:47.734 T:3333649248   ERROR: GetDirectory - Error getting include
17:43:47.735 T:3333649248   ERROR: Previous line repeats 1 times.
17:43:47.735 T:3333649248   ERROR: GetDirectory - Error getting description
17:43:48.271 T:3215979360   ERROR: Previous line repeats 1 times.
17:43:48.271 T:3215979360  NOTICE: [plugin.video.elementum] INFO  config       ▶ Reload           [0mUsing download path: /storage/downloads
17:43:48.292 T:3215979360  NOTICE: [plugin.video.elementum] INFO  config       ▶ Reload           [0mUsing library path: /storage/downloads
17:43:48.349 T:3215979360  NOTICE: [plugin.video.elementum] INFO  main         ▶ main             [0mAddon: plugin.video.elementum v0.0.44
17:43:48.651 T:3215979360  NOTICE: [plugin.video.elementum] [31mERRO  database     ▶ InitCacheDB      [0mwrite /storage/.kodi/userdata/addon_data/plugin.video.elementum/cache.db: file too large
17:43:48.653 T:3215979360  NOTICE: [plugin.video.elementum] [31mERRO  main         ▶ main             [0mwrite /storage/.kodi/userdata/addon_data/plugin.video.elementum/cache.db: file too large

**Comment by elgatito** [comment]
/storage/.kodi/userdata/addon_data/plugin.video.elementum/cache.db - удалите этот файл и cache_backup тоже, если есть.
Я посмотрю в чем может быть причина.

**Comment by elgatito** [comment]
Размер файла перед удалением посмотрите только.

**Comment by yatsek20** [comment]
cache.db - 39,1мб , cache_backup 22,3мб Удалять оба?

**Comment by elgatito** [comment]
Да.

**Comment by yatsek20** [comment]
удалил, плагин заработал ,но вроде бы стал чуть медленее работать  скорее всего это после удаления и что кеш не набрался после удаления. Спасибо огромное за помощь.
