### ISSUE TITLE
How Do I Install

### ISSUE THREAD

**Issue by aybesea** [elgatito/plugin.video.elementum#15]
I really want to learn but I Googled addon.xml and don't understand how to manually add elementum. 

The quasar install started with a download page listing many architectures. I don't find anything even remotely similar in the elementum github.com page. 

I am quick to Google first, but I really can't seem to get started here. Any direction would be most appreciated. 

Thanks.

**Comment by elgatito** [comment]
There is no welcome page or documentation for Elementum, yet.
You can browse Release page, download the biggest zip file for latest release and install from zip. Updates will automatically come from built-in repository.
https://github.com/elgatito/plugin.video.elementum/releases
