### ISSUE TITLE
No playback on latest CoreELEC 8.90.1 (Kodi 18.0-ALPHA2 Git:af4a548)

### ISSUE THREAD

**Issue by vevsvevs** [elgatito/plugin.video.elementum#150]
## Expected Behavior
Playing selected item.

## Current Behavior
Falling back to the list without playing.

## Context
After update from CoreELEC 8.90.0 (Kodi 18.0-ALPHA2 Git:72f69fc) to 8.90.1 (Kodi 18.0-ALPHA2 Git:af4a548), none selected torrent can be played.

## Your Environment
Clean installed CoreELEC on Mecool K1 Pro (Amlogic S905D).
8.90.0 log (good): https://pastebin.com/iNFTBrh4
8.90.1 log (bad): https://pastebin.com/46yZu5Vf

**Comment by kostaboxon** [comment]
Confirming behaviour. https://paste.kodi.tv/sugafabibe

**Comment by diabl0w** [comment]
confirmed here

**Comment by elgatito** [comment]
I don't see any problem in the log. Kodi starts a video player and stops it. 
Maybe they have posted some bug or a change in Kodi.

**Comment by diabl0w** [comment]
@elgatito [code] [plugin.video.elementum] [GIN] 2018/05/01 - 16:29:25 | 302 |  9.791235746s |       127.0.0.1 | GET      /movie/299536/links
12:29:25.827 T:3517105024  NOTICE: [plugin.video.elementum] [GIN] 2018/05/01 - 16:29:25 | 200 |   43.513285ms |       127.0.0.1 | GET      /movie/299536/infolabels
12:29:25.871 T:3266302848   ERROR: NEWADDON Unknown Video Info Key "artbanner"
12:29:25.871 T:3266302848   ERROR: NEWADDON Unknown Video Info Key "artfanart"
12:29:25.871 T:3266302848   ERROR: NEWADDON Unknown Video Info Key "artposter"
12:29:25.871 T:3266302848   ERROR: NEWADDON Unknown Video Info Key "artthumb"
12:29:25.871 T:3266302848   ERROR: NEWADDON Unknown Video Info Key "dbtype"
12:29:25.871 T:3266302848   ERROR: NEWADDON Unknown Video Info Key "icon"
12:29:25.871 T:3266302848   ERROR: NEWADDON Unknown Video Info Key "is_playable"
12:29:25.871 T:3266302848   ERROR: NEWADDON Unknown Video Info Key "label"
12:29:25.871 T:3266302848   ERROR: NEWADDON Unknown Video Info Key "label2"
12:29:25.872 T:3266302848   ERROR: NEWADDON Unknown Video Info Key "thumbnail"
12:29:25.906 T:4096003200  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.elementum/movie/299536/links
12:29:25.907 T:3215946624  NOTICE: Creating InputStream
12:29:25.909 T:3215946624   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.elementum/movie/299536/links]
12:29:25.910 T:3215946624  NOTICE: CVideoPlayer::OnExit()
12:29:26.210 T:3517105024  NOTICE: [plugin.video.elementum] [36mDEBU  main         ▶ Notification     [0mGot notification from xbmc/Info.OnChanged: null
12:29:26.228 T:3517105024  NOTICE: [plugin.video.elementum] [36mDEBU  main         ▶ Notification     [0mGot notification from xbmc/Player.OnPlay: {"item":{"title":"Avengers: Infinity War","type":"movie","year":2018},"player":{"playerid":1,"speed":1}}
12:29:27.258 T:3517105024  NOTICE: [plugin.video.elementum] [36mDEBU  main         ▶ Notification     [0mGot notification from xbmc/Player.OnStop: {"end":false,"item":{"title":"Avengers: Infinity War","type":"movie","year":2018}} [/code]

**Comment by vevsvevs** [comment]
Никого не обижу, если продолжу на русском?
В "новой" версии ничего не изменилось, да и не могло - там авторы только местами брэндинг подправили после ухода из LE-комьюнити.
В моих логах есть существенная разница - совершенно разные вещи передаются плееру, и похоже это связано с отсутствием вызова easy_acquire в "сломанной" версии.
Рабочий вариант:
```
INFO: easy_acquire - Created session to http://localhost
DEBUG: CCurlFile::GetMimeType - http://localhost:65220/files/Dedpul_2016_r5_HDRip__[scarabey.org].avi -> video/avi
DEBUG: CPlayerCoreFactory::GetPlayers(http://localhost:65220/files/Dedpul_2016_r5_HDRip__[scarabey.org].avi)
```
Нерабочий вариант:
`CPlayerCoreFactory::GetPlayers(plugin://plugin.video.elementum/movie/293660/links)`

**Comment by kostaboxon** [comment]
This is not a CoreELEC issue. 
The same behaviour using LE Leia on rock64 nightlies

**Comment by elgatito** [comment]
@kostaboxon yes, it looks like a Kodi issue. They have made some changes.

**Comment by vevsvevs** [comment]
That's why i posted issue here (rather than in CE) with Kodi git stamps ;)
@elgatito, is there any chance to fix (if you have time to investigate this)?
TIA

**Comment by elgatito** [comment]
@vevsvevs there is no visible problem and no error message. I will, probably, try to install latest Kodi on linux and test with it.

**Comment by cata747** [comment]
Adding magnet links via yatse addon helper works. I am using latest coreelec.

**Comment by vevsvevs** [comment]
Yep, CE 8.90.2 runs Elementum just fine :) @elgatito, sorry for disturbing you.

**Comment by elgatito** [comment]
That is fine. Thanks for the report
