### ISSUE TITLE
(Bug?/Request?)Traktv movies added from website do not update do Kodi Library automatically. Have to ask Elementum to update Traktv

### ISSUE THREAD

**Issue by rafaelfrota** [elgatito/plugin.video.elementum#151]
Hello, first of all, thank you very much for this awesome app.
So, about the integration with traktv. I have 3 options to add a movie to my library. 
1. I go to Elementum, look for a movie, choose it and select Add to Library: BAM, it gets added to my Kodi Library.
2. I do the same as above, but choose Add my Watchlist (which updates my traktv watchlist). If I go to my Kodi Library and update ir, nothing happens. I have to go to Elementum settings, choose Update Traktv and then update my Kodi Library so I can I have my movie on the library.
3. I add a movie to my watchlist through Traktv website. I have to do the same steps in option 2 to add the movie to my library

## Expected Behavior
When I add a movie to my watchlist through Elementum, it should update the Elementum library automatically (generate the strm files) so Kodi can locate them and update kodi library.
Also, it should do the same when I boot kodi, so 

## Current Behavior
Kodi Library does not get the movies unless I mannually ask Elementum to update its library from traktv

## Possible Solution
The command Update Traktv should be done on boot, on a timer, and after adding a movie to the watch list

## Context
I like to add movies to my traktv watchlist through my phone. When I boot Kodi, it would be great to have those movies already on my library.

## Your Environment
Kodi 17
Elementum 0.0.45
Windows 10

**Comment by elgatito** [comment]
There is no "Elementum library", there are Kodi library and Trakt Collection/Watchlist/Userlists.

Trakt sync is run on a timer, period of update is configured in plugin settings.
Currently adding to the Kodi library does not add item to Trakt. When you add item to Trakt - it will be added to Kodi library after next update.

**Comment by rafaelfrota** [comment]
By Elementum library, I meant the folder that contais strm files which is kodi library, but I get it.
So, if I choose the timer to 1 hour, it runs 1 hour after I start kodi right? If I choose 0, what happens?

**Comment by elgatito** [comment]
With 0.0.46 Trakt sync will start after Kodi startup (and then in periods, configured in plugin settings).

**Comment by elgatito** [comment]
I'm closing this issue.

If you want to quickly add something to your library - you can add it to your userlist or "Collection", it will be added to Kodi library on next update.

Updates now run after plugin startup and then periodically, so would be much better (or you can start trakt update from plugin settings).
