### ISSUE TITLE
One or more items could not be played

### ISSUE THREAD

**Issue by shmox75** [elgatito/plugin.video.elementum#154]
Many streaming torrent could not be played i tried on windows 10 and android same issue

Here is my windows 10 log

01:29.225 T:8304 NOTICE: [plugin.video.elementum] DEBU bittorrent â�¶ progressEvent 7dc42a: 167 kB/0 B | Downloading (10.29%)
12:01:30.227 T:8304 NOTICE: [plugin.video.elementum] DEBU bittorrent â�¶ progressEvent 7dc42a: 177 kB/0 B | Downloading (10.29%)
12:01:31.225 T:8304 NOTICE: [plugin.video.elementum] DEBU bittorrent â�¶ progressEvent 7dc42a: 167 kB/0 B | Downloading (10.29%)
12:01:32.225 T:8304 NOTICE: [plugin.video.elementum] DEBU bittorrent â�¶ progressEvent 7dc42a: 184 kB/0 B | Downloading (10.29%)
12:01:33.226 T:8304 NOTICE: [plugin.video.elementum] DEBU bittorrent â�¶ progressEvent 7dc42a: 164 kB/0 B | Downloading (10.29%)
12:01:34.228 T:8304 NOTICE: [plugin.video.elementum] DEBU bittorrent â�¶ progressEvent 7dc42a: 144 kB/0 B | Downloading (10.29%)
12:01:35.226 T:8304 NOTICE: [plugin.video.elementum] DEBU bittorrent â�¶ progressEvent 7dc42a: 141 kB/0 B | Downloading (10.29%)
12:01:38.226 T:8304 NOTICE: Previous line repeats 2 times.
12:01:38.226 T:8304 NOTICE: [plugin.video.elementum] DEBU bittorrent â�¶ progressEvent 7dc42a: 134 kB/0 B | Downloading (10.29%)
12:01:39.226 T:8304 NOTICE: [plugin.video.elementum] DEBU bittorrent â�¶ progressEvent 7dc42a: 174 kB/0 B | Downloading (10.29%)
12:01:39.591 T:856 ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
12:01:39.591 T:8500 ERROR: CDVDDemuxFFmpeg::Open - Error, could not open file http://localhost:65220/files/It.2017.TRUEFRENCH.BDRip.XviD-GZR.WwW.HIDDEN.pe/It.2017.TRUEFRENCH.BDRip.XviD-GZR.avi
12:01:39.591 T:8500 ERROR: CVideoPlayer::OpenDemuxStream - Error creating demuxer
12:01:39.591 T:8500 NOTICE: CVideoPlayer::OnExit()
12:01:39.591 T:8304 NOTICE: [plugin.video.elementum] DEBU bittorrent â�¶ Close Closing reader: 343400390
12:01:39.591 T:8304 NOTICE: [plugin.video.elementum] DEBU bittorrent â�¶ Close Active readers: 1
12:01:39.592 T:8304 NOTICE: [plugin.video.elementum] DEBU bittorrent â�¶ Close Closing reader: 1611252826
12:01:39.594 T:9604 ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.elementum/play?episode=&resume=7dc42a9bede9b7b29f1bb0f5c5c72f41b9c17c4d&season=&show=&tmdb=&type=]
12:01:39.595 T:8304 NOTICE: [plugin.video.elementum] DEBU bittorrent â�¶ Close Active readers: 0
12:01:39.596 T:9604 NOTICE: CVideoPlayer::CloseFile()
12:01:39.596 T:9604 NOTICE: VideoPlayer: waiting for threads to exit
12:01:39.596 T:9604 NOTICE: VideoPlayer: finished waiting
12:01:39.596 T:9604 NOTICE: CVideoPlayer::CloseFile()
12:01:39.596 T:9604 NOTICE: VideoPlayer: waiting for threads to exit
12:01:39.596 T:9604 NOTICE: VideoPlayer: finished waiting
12:01:39.658 T:8304 NOTICE: [plugin.video.elementum] DEBU main â�¶ Notification Got notification from xbmc/Player.OnStop: {"end":false,"item":{"title":"It.2017.TRUEFRENCH.BDRip.XviD-GZR.WwW.HIDDEN.pe","type":"movie"}}
12:01:40.227 T:8304 NOTICE: [plugin.video.elementum] DEBU bittorrent â�¶ progressEvent 7dc42a: 151 kB/0 B | Downloading (10.29%)
12:01:40.390 T:10840 ERROR: EXCEPTION: XBMC is not playing any media file
12:01:40.393 T:8304 NOTICE: [plugin.video.elementum] INFO btplayer â�¶ playerLoop Stopped playback
12:01:40.394 T:8304 NOTICE: [plugin.video.elementum] DEBU btplayer â�¶ UpdateWatched Updating Watched state: &bittorrent.PlayerParams{Playing:true, Paused:false, Seeked:false, WasPlaying:false, KodiPosition:-1, WatchedTime:0, VideoDuration:0, URI:"", FileIndex:-1, ResumeIndex:-1, ContentType:"", KodiID:0, TMDBId:0, ShowID:0, Season:0, Episode:0, Resume:(*library.Resume)(nil)}
12:01:41.226 T:8304 NOTICE: [plugin.video.elementum] DEBU bittorrent â�¶ progressEvent 7dc42a: 157 kB/0 B | Downloading (10.29%)
12:01:42.224 T:8304 NOTICE: [plugin.video.elementum] DEBU bittorrent â�¶ progressEvent 7dc42a: 154 kB/0 B | Downloading (10.29%)
12:01:43.226 T:8304 NOTICE: [plugin.video.elementum] DEBU bittorrent â�¶ progressEvent 7dc42a: 141 kB/0 B | Downloading (10.29%)
12:01:44.226 T:8304 NOTICE: [plugin.video.elementum] DEBU bittorrent â�¶ progressEvent 7dc42a: 167 kB/0 B | Downloading (10.29%)
12:01:45.225 T:8304 NOTICE: [plugin.video.elementum] DEBU bittorrent â�¶ progressEvent 7dc42a: 180 kB/0 B | Downloading (10.29%)
12:01:46.225 T:8304 NOTICE: [plugin.video.elementum] DEBU bittorrent â�¶ progressEvent 7dc42a: 187 kB/0 B | Downloading (10.29%)
12:01:47.226 T:8304 NOTICE: [plugin.video.elementum] DEBU bittorrent â�¶ progressEvent 7dc42a: 161 kB/0 B | Downloading (10.29%)
12:01:48.227 T:8304 NOTICE: [plugin.video.elementum] DEBU bittorrent â�¶ progressEvent 7dc42a: 164 kB/0 B | Downloading (10.29%)
12:01:49.225 T:8304 NOTICE: [plugin.video.elementum] DEBU bittorrent â�¶ progressEvent 7dc42a: 134 kB/0 B | Downloading (10.29%)
12:01:50.225 T:8304 NOTICE: [plugin.video.elementum] DEBU bittorrent â�¶ progressEvent 7dc42a: 131 kB/0 B | Downloading (10.29%)
12:01:51.225 T:8304 NOTICE: [plugin.video.elementum] DEBU bittorrent â�¶ progressEvent 7dc42a: 164 kB/0 B | Downloading (10.29%)
12:01:52.225 T:8304 NOTICE: [plugin.video.elementum] DEBU bittorrent â�¶ progressEvent 7dc42a: 121 kB/0 B | Downloading (10.29%)
12:01:53.225 T:8304 NOTICE: [plugin.video.elementum] DEBU bittorrent â�¶ progressEvent 7dc42a: 174 kB/0 B | Downloading (10.29%)
12:01:54.225 T:8304 NOTICE: [plugin.video.elementum] DEBU bittorrent â�¶ progressEvent 7dc42a: 164 kB/0 B | Downloading (10.29%)
12:01:56.226 T:8304 NOTICE: Previous line repeats 1 times.
12:01:56.226 T:8304 NOTICE: [plugin.video.elementum] DEBU bittorrent â�¶ progressEvent 7dc42a: 167 kB/0 B | Downloading (10.29%)
12:01:57.226 T:8304 NOTICE: [plugin.video.elementum] DEBU bittorrent â�¶ progressEvent 7dc42a: 131 kB/0 B | Downloading (10.29%)
12:01:58.226 T:8304 NOTICE: [plugin.video.elementum] DEBU bittorrent â�¶ progressEvent 7dc42a: 141 kB/0 B | Downloading (10.29%)
12:01:59.225 T:8304 NOTICE: [plugin.video.elementum] DEBU bittorrent â�¶ progressEvent 7dc42a: 154 kB/0 B | Downloading (10.29%)
12:02:00.226 T:8304 NOTICE: [plugin.video.elementum] DEBU bittorrent â�¶ progressEvent 7dc42a: 164 kB/0 B | Downloading (10.29%)
12:02:01.225 T:8304 NOTICE: [plugin.video.elementum] DEBU bittorrent â�¶ progressEvent 7dc42a: 167 kB/0 B | Downloading (10.29%)
12:02:01.451 T:8304 NOTICE: [plugin.video.elementum] DEBU bittorrent â�¶ PlayerStop PlayerStop
12:02:01.464 T:10840 ERROR: EXCEPTION: XBMC is not playing any media file
12:02:01.471 T:8304 NOTICE: [plugin.video.elementum] INFO btplayer â�¶ playerLoop Stopped playback
12:02:01.471 T:8304 NOTICE: [plugin.video.elementum] DEBU btplayer â�¶ UpdateWatched Updating Watched state: &bittorrent.PlayerParams{Playing:true, Paused:false, Seeked:false, WasPlaying:false, KodiPosition:-1, WatchedTime:0, VideoDuration:0, URI:"C:\Users\Mok\AppData\Roaming\Kodi\cache\elementum\7dc42a9bede9b7b29f1bb0f5c5c72f41b9c17c4d.torrent", FileIndex:-1, ResumeIndex:-1, ContentType:"", KodiID:0, TMDBId:0, ShowID:0, Season:0, Episode:0, Resume:(*library.Resume)(nil)}
12:02:02.225 T:8304 NOTICE: [plugin.video.elementum] DEBU bittorrent â�¶ progressEvent 7dc42a: 193 kB/0 B | Downloading (10.29%)
12:02:03.226 T:8304 NOTICE: [plugin.video.elementum] DEBU bittorrent â�¶ progressEvent 7dc42a: 134 kB/0 B | Downloading (10.29%)
12:02:04.225 T:8304 NOTICE: [plugin.video.elementum] DEBU bittorrent â�¶ progressEvent 7dc42a: 187 kB/0 B | Downloading (10.29%)
12:02:04.551 T:8304 NOTICE: [plugin.video.elementum] DEBU bittorrent â�¶ PlayerStop PlayerStop
12:02:05.226 T:8304 NOTICE: [plugin.video.elementum] DEBU bittorrent â�¶ progressEvent 7dc42a: 170 kB/0 B | Downloading (10.29%)
12:02:05.441 T:3612 ERROR: InputStream: Error opening, plugin://plugin.video.elementum/play?episode=&resume=7dc42a9bede9b7b29f1bb0f5c5c72f41b9c17c4d&season=&show=&tmdb=&type=
12:02:05.479 T:8304 NOTICE: [plugin.video.elementum] DEBU main â�¶ Notification Got notification from xbmc/Playlist.OnClear: {"playlistid":1}
12:02:06.225 T:8304 NOTICE: [plugin.video.elementum] DEBU bittorrent â�¶ progressEvent 7dc42a: 148 kB/0 B | Downloading (10.29%)
12:02:07.226 T:8304 NOTICE: [plugin.video.elementum] DEBU bittorrent â�¶ progressEvent 7dc42a: 184 kB/0 B | Downloading (10.29%)

NOTICE THE

CDVDDemuxFFmpeg::Open - Error, could not open file http://localhost:65220/files/It.2017.TRUEFRENCH.BDRip.XviD-GZR.WwW.HIDDEN.pe/It.2017.TRUEFRENCH.BDRip.XviD-GZR.avi

ERROR: CVideoPlayer::OpenDemuxStream - Error creating demuxer

I AM ON KODY 17.4

**Comment by elgatito** [comment]
@shmox75 You have this issue with the latest version or I can close it?

**Comment by elgatito** [comment]
Closing without getting response.
