### ISSUE TITLE
One or more items couldn't be played

### ISSUE THREAD

**Issue by mok2013** [elgatito/plugin.video.elementum#155]
I've got this isue on many avi streaming on both windows 10 and android 
I'm on kodi 17.4

here is a part of log

ERROR: CDVDDemuxFFmpeg::Open - Error, could not open file "http://........../file.avi"
ERROR: CVideoPlayer::OpenDemuxStream - Error creating demuxer

**Comment by elgatito** [comment]
No log = no help.

**Comment by mok2013** [comment]
I posted log first time but my account was disabled by stackoverflow.
I registred second account and reposted the log, and again my account was disabled.
So i registred for the 3rd time and here is why i posted just sample.

Can you tel me how can I post my log file bypassing stackoverflow ? 

Thank you, because you have an awesome plugin

**Comment by elgatito** [comment]
Stackoverflow? Just go to paste.ubuntu.com and post there anonymously.

**Comment by mok2013** [comment]
Okay thanks, here it is (thanks for the tip):

https://paste.ubuntu.com/p/DwxCN2BRyz/

Please tell me if you want more infos (PS: i am newbie & your plugin is just awesome)

**Comment by elgatito** [comment]
@mok2013 your download speed is too low. Maybe, because of file storage. Try changing to memory storage (first tab of plugin settings in Kodi). Leave all other memory size options as defaults and try again.

**Comment by mok2013** [comment]
I have a low 2mb/s internet connexion, i'll try memory and see. but with my android box i have only 2gb of ram I'll try on windows 10 i have 16gb ram

**Comment by mok2013** [comment]
I tried it but nothing happened after 100% loading the window vanishes without any message and the movie don't start playing

**Comment by elgatito** [comment]
can't see any problem in the log. Kodi is just stopping the playback somewhy... I'd ask to try memory storage, just to see if that makes any difference. 
I see such behavior first time. Also, you can try to enable debug mode in Kodi and re-send a log file, there will be more information.

```
Turn debugging on:
From the Main menu, select Settings (gear icon at top of the menu) → System Settings → Logging and turn on Enable debug logging. You will see some weird text pop up on the screen.
```

**Comment by mok2013** [comment]
Thank you, I have enable logging and obviously the video plays well
The strange thing is when i've redisabled logging the video don't plays .

What do you think the problem was ? When logging on the vid plays when off no ???

Do you want to send you the log when logging is on even when the video plays well ?

**Comment by mok2013** [comment]
In case you want to test here is a torrent file causing issues:

https://www84.zippyshare.com/v/Sfzw78wE/file.html

Tell me if you need more ifos thanks

**Comment by mok2013** [comment]
ANd here is log when storage = memory and debugging = off:

https://paste.ubuntu.com/p/hqMb8wjwtD/

**Comment by elgatito** [comment]
```
What do you think the problem was ? When debug logging on the vid plays when off no ???
```

@mok2013 debugging is only writing more information in the log (from Kodi's side), it should not influence anything at all. I don't know what can go wrong here. 
```
10:02:16.347 T:4388   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
```

It just cannot read the amount of file it wants to start playback. 
Can you try to set Buffer at Bittorrent settings tab to 30mb (instead of 20mb).

**Comment by elgatito** [comment]
@mok2013 any news on this issue?

**Comment by elgatito** [comment]
Closing as a no-response.
Will reopen if still needed.
