### ISSUE TITLE
Elementum crash all the time

### ISSUE THREAD

**Issue by Jezze83** [elgatito/plugin.video.elementum#160]
Im using latest kodi with windows 10. Elementum crash all the time and correct version is installed, this addon is useless because never worked fine.

16:55:41.767 T:4344  NOTICE: [plugin.video.elementum] elementum: starting jsonrpc service
16:55:41.767 T:6000  NOTICE: [plugin.video.elementum] elementumd: starting elementumd
16:55:41.767 T:8576   DEBUG: JSONRPC Server: New connection detected
16:55:41.768 T:8576    INFO: JSONRPC Server: New connection added
16:55:41.768 T:8576    INFO: JSONRPC Server: Disconnection detected
16:55:41.768 T:6000  NOTICE: [plugin.video.elementum] Kodi's JSON-RPC service is available, starting up...
16:55:41.768 T:6000  NOTICE: [plugin.video.elementum] Binary detection. Source: C:\Users\Jesse\AppData\Roaming\Kodi\addons\plugin.video.elementum\resources\bin\windows_x64\elementum.exe, Destination: C:\Users\Jesse\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.elementum\bin\windows_x64\elementum.exe
16:55:41.946 T:908   DEBUG: CRecentlyAddedJob::UpdateTotal() - Running RecentlyAdded home screen update
16:55:41.999 T:908   DEBUG: CMusicDatabase::GetArtistsByWhere query: SELECT COUNT(DISTINCT artistview.idArtist) FROM artistview  WHERE ((EXISTS (SELECT 1 FROM song_artist WHERE song_artist.idArtist = artistview.idArtist AND song_artist.idRole = 1) OR EXISTS (SELECT 1 FROM album_artist WHERE album_artist.idArtist = artistview.idArtist)) AND (artistview.strArtist != '')) AND (artistview.strArtist <> 'Eri esittäjiä')
16:55:43.835 T:6000  NOTICE: [plugin.video.elementum] Deleting stale files set([])
16:55:43.835 T:6000  NOTICE: [plugin.video.elementum] Binary detection: [ Source: C:\Users\Jesse\AppData\Roaming\Kodi\addons\plugin.video.elementum\resources\bin\windows_x64\elementum.exe, Destination: C:\Users\Jesse\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.elementum\bin\windows_x64\elementum.exe ]
16:55:43.836 T:6000  NOTICE: [plugin.video.elementum] Binary dir: C:\Users\Jesse\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.elementum\bin\windows_x64, item: C:\Users\Jesse\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.elementum\bin\windows_x64\elementum.exe
16:55:43.859 T:6000 WARNING: [plugin.video.elementum] Existing process found from lockfile, killing...
16:55:43.860 T:6000   ERROR: [plugin.video.elementum] WindowsError(5, 'K\xe4ytt\xf6 estetty')
16:55:43.861 T:6000 WARNING: [plugin.video.elementum] Removing library.db.lock file...
16:55:43.862 T:6000   ERROR: [plugin.video.elementum] WindowsError(2, 'M\xe4\xe4ritetty\xe4 tiedostoa ei l\xf6ydy')

**Comment by elgatito** [comment]
Thanks for your feedback.

**Comment by Jezze83** [comment]
”Thanks for your feedback?” Thats it? Lol. Would be nice to know how to fix this.
