### ISSUE TITLE
[Request] Allow setting specific language for strm files naming

### ISSUE THREAD

**Issue by jorgecardoso220** [elgatito/plugin.video.elementum#161]
Hello,

Is there any way, when Elementum imports a TV Shows from a trakt list to Kodi library, to use the TV Show title in English instead of the title in the original language? 
For exemple, I have "Dragon Ball Super" in a trakt list but Elementum imports it with the name in japanese and Kodi can't find it.

Thanks for the help

**Comment by elgatito** [comment]
@jorgecardoso220  it does not, Elementum is writing in unicode. If you look with file manager (any) - you will see proper japanese/korean/other characters, in Kodi you will probably see ◻︎ because that language is not installed in Kodi.

**Comment by elgatito** [comment]
I'm changing this issue to become a feature request to allow setting language for writing strm files. If language not available - will revert to Kodi's language, then - Original language.

**Comment by elgatito** [comment]
Added option to force specific language for strm files. By default we use original titles (depending on the origin country).
