### ISSUE TITLE
Adding custom providers?

### ISSUE THREAD

**Issue by peter099** [elgatito/plugin.video.elementum#163]
Is there a guide how to add custom providers? I want to add this site: arenabg.com

**Comment by hoshsadiq** [comment]
The repository you'll need to contribute to is https://github.com/elgatito/script.elementum.burst.. an example commit that contains one provider added is this commit: 
https://github.com/elgatito/script.elementum.burst/commit/7f29665f7980eed9c25e3c5189d195a6fc0bb290

**Comment by elgatito** [comment]
Some documentation should be added for describing it. But that is related to Burst, not Elementum.
