### ISSUE TITLE
seeding not working & ...

### ISSUE THREAD

**Issue by tomtomclub** [elgatito/plugin.video.elementum#164]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

hi seeding is not working   v0.0.46 and interface is not working http://192.168.1.193:65220/
linux 64 bit

**Comment by elgatito** [comment]
Log file?

**Comment by elgatito** [comment]
Closing due to no response.
