### ISSUE TITLE
Stream from elementum UI web.

### ISSUE THREAD

**Issue by 9acca9** [elgatito/plugin.video.elementum#167]
Hi.
Im using the last release of OSMC.  in a rpi2.
Im trying to add a magnet link manually through the web of Elementum. 65220/web.
If i select "stream" the circle of the skin of the OSMC start to roll, like if the magnet it would have been received, and in fact the "download/stream" start but......... it take to long to show the download box, that is, I do not mean that it takes a long time to download, but to load the magnet (like 5 minutes...).
On the other hand if I add for download and not for stream, then I do not add it.

Can somebody give me a hand?

Thanks.
(i dont speak english)

**Comment by rossi29** [comment]
Bonjour a tous,
Comment faite vous pour aller Elementum WebUI
Merci

**Comment by elgatito** [comment]
@9acca9 , please, provide a kodi.log  - https://kodi.wiki/view/Log_file/Easy

**Comment by rossi29** [comment]
Bonjour elgatito,
Je veut seulement avoir accès a l'interface web.
Merci a toi pour tout tes effort.

**Comment by elgatito** [comment]
@rossi29 I don't speak french.

**Comment by rossi29** [comment]
hello,
how to get access to elementum web interface ?
Thank you

**Comment by elgatito** [comment]
@rossi29  http://KODI_IP:65520/web/ (insert IP of Kodi device).

**Comment by elgatito** [comment]
@rossi29  KODI_IP -> 192.168.X.XX

**Comment by rossi29** [comment]
http://KODI_IP192.168.X.XX:65520/web/   ?

**Comment by elgatito** [comment]
@rossi29 Just open http://IP:65520/web/ , where "IP" is replaced but your IP. I will not respond to this anymore.

**Comment by rossi29** [comment]
pity it does not work for me, thanks elgatito

**Comment by MasterSoft24** [comment]
Does not work for me too. Browser says "Could not connect"

**Comment by elgatito** [comment]
@MasterSoft24 you have to open IP of device, that runs Kodi with Elementum. Then open it with "65520" port in browser.

**Comment by MasterSoft24** [comment]
OK. Thanx

**Comment by elgatito** [comment]
Closing as issue reported is not responding.

**Comment by elgatito** [comment]
@rossi29  @MasterSoft24 with 0.0.49 there is Status menu item in Elementum main menu. It will show proper WebUI address, to access from other devices.
