### ISSUE TITLE
[Enhancement] TMDB lists should not be limited or hide "next page"

### ISSUE THREAD

**Issue by ssmol** [elgatito/plugin.video.elementum#168]
TMDB жанры. ограничение в 100 пунктов.
возможно ли его убрать

**Comment by elgatito** [comment]
Какое ограничение? Каких пунктов?

**Comment by ssmol** [comment]
там где по жанры максимум загружает три страницы по 30 и одну 10 и выдает internal server error на любом жанре

**Comment by elgatito** [comment]
Можете прислать лог? https://kodi.wiki/view/Log_file/Easy

**Comment by ssmol** [comment]
https://pastebin.com/t4KUejwG

**Comment by elgatito** [comment]
Fixed in 0.0.54.
