### ISSUE TITLE
Elementum 0.0.46 buffers extremely slow, if it does so at all, and never actually plays a torrent.

### ISSUE THREAD

**Issue by nvpl** [elgatito/plugin.video.elementum#169]
Hello,

I have been trying to get Elementum 0.0.46 to work for quite a while on my NVIDIA Shield TV; however, I have never any luck in doing so. I initially tried Quasar and it seemed to download a torrent extremely quick, but the torrent itself never played either. I have enabled remote control in Kodi, tried all different storage types in settings, uninstalling/reinstalling, and searched the web tirelessly for a solution to no avail.

What tends to happen with Elementum is that it will begin buffering (stay on 0% for about 5 minutes) then state "Playback failed" then begin buffering (at a painfully slow speed <200kbps) then state "Playback failed" again. Bear in mind, my internet speed over my VPN is roughly 80mbps/20mbps. Although Quasar never successfully played a torrent either and presented me with the same "Playback Failed" message, the buffering is consistently >1500kbps, and never takes more than five seconds to begin buffering. I tried this test on identical torrents within five minutes of each other (Elementum and Quasar weren't simultaneously installed) on different occasions.

I have pasted my Kodi log below for Elementum, and for Quasar if that would help fix the speed issue in Elementum. Any help would be much appreciated!

## Your Environment
Elementum 0.0.46
Kodi 17.6
NVIDIA Shield TV (Android 7/SHIELD Android TV SW Version 6.3)

Elementum Log: https://paste.ubuntu.com/p/rvnjXY6F4m/
Quasar Log: https://paste.ubuntu.com/p/snNXKBJFGW/

**Comment by strummerj** [comment]
I am seeing a similar issue on my Vero 4k. Torrents all stay around 0kb/s. Used to work fine and I'm certain that the connection is solid.

Elementum 0.0.46

Kodi Debug Logs: https://paste.ubuntu.com/p/3XPsckvQPj/

**Comment by nvpl** [comment]
Hi Strummer, that is interesting you are facing a similar issue. Unfortunately, I have never gotten it to work successfully even in version 0.0.45.

**Comment by elgatito** [comment]
@nvpl  can you try memory storage, not using files? 

@strummerj I need full log, not a small cut.

**Comment by nvpl** [comment]
Thank you @elgatito  for your response. I tried all four file storage types in the past with no success. Nonetheless, I went ahead and tried again with "memory storage" with no luck.

Pasted below is my log when using "memory storage."

https://paste.ubuntu.com/p/WsZBrYj6BM/

**Comment by elgatito** [comment]
@nvpl very strange log. Can you open http://KODI_IP:65520/info url and save the page? It will show torrent library information.

**Comment by nvpl** [comment]
@elgatito I believe you meant to say: http://KODI_IP:**65220**/info instead of http://KODI_IP:**65520**/info

Here is the log/torrent library information about 30 seconds after I clicked on the torrent: https://paste.ubuntu.com/p/ynw7B54d6H/

Here is the log/torrent library information after the "Playback failed" message displayed: https://paste.ubuntu.com/p/GW3BKR3QXs/

**Comment by elgatito** [comment]
@nvpl very strange log. Torrent information looks good to me and there are active peers, but download is so slow.

casting @anacrolix help :)

**Comment by anacrolix** [comment]
It would appear the network is going very slowly. The playback failed is very likely a timeout occurring due to a timeout from Kodi. At the time that the error occurs, there's only a single peer uploading to you with only 75KiB/s. There appears to be plenty of peers, it's strange there's only 10 connected, and they're all TCP. They're also all outbound, meaning connections likely aren't being received (due to firewall or NAT).

I'd go through the following checklist:

- Ensure global connections/connections per torrent is at least 30
- Do a network performance test (speedtest.net or something similar)
- Tell us your ISP, and cable/ADSL whatever, it may be your traffic is being shaped or tampered with

The fact that other plugins have the same issue suggests that either your network, or something else with your setup is bad.

**Comment by nvpl** [comment]
@anacrolix 

- Upon checking my settings under Elementum > Addon Settings > BitTorrent > Connections limit, there is no limit specified for "Connections limit." Am I referencing the correct option?
- Speedtest over VPN from NVIDIA Shield TV pasted below.
- I am using cable internet. My NVDIA Shield is hard wired to the router with OpenVPN running in the background. Using the same VPN and network, I am able to download torrents on my laptop over wifi at ~ 7mbps. Which causes me to doubt that my ISP tampering with my network traffic.
- I don't know if the issue could be network related as I have no issue torrenting on other devices on the same network; however, I am no expert. Other plugins such as Quasar do not experience the same issue entirely because that plugin reaches download speeds similar to what I am able to achieve on my laptop while torrenting. However, I still receive the playback failed message on Quasar.

![speedtest](https://user-images.githubusercontent.com/39887752/41173059-78383510-6b0a-11e8-98a9-79346d12a04d.png)

**Comment by anacrolix** [comment]
@elgatito will know the connection limit set. I don't think that's it if you can torrent otherwise as you say. Speeds look fine. The main reason speeds might appear lower with elementum is the torrent package is a lot more selective and conservative about what it downloads than the implementations other clients use, so I think that's to be expected unless you run them neck and neck. I think the issue lies with Quasar on your system which isn't an area I'm familiar with.

**Comment by elgatito** [comment]
@anacrolix 
```
EstablishedConnsPerTorrent:0, HalfOpenConnsPerTorrent:0, TorrentPeersHighWater:0, TorrentPeersLowWater:0, HandshakesTimeout:0
```

We don't set any max/min options by default. This one also has `0` settings.

**Comment by nvpl** [comment]
@elgatito Apologies for all the different logs ahead of time. I figured I should be provide as much info as possible with the new settings applied/new version of Elementum being released.

**Logs—version 0.0.46** after disabling "Auto-assign network IP" and "Listen interfaces" set to "tun1":

- Info page ~ 1 minute after torrent clicked: https://paste.ubuntu.com/p/9m5VYCt4Tz/

- Info page immediately after "Playback failed"/"Elementum timed out" message: https://paste.ubuntu.com/p/4B45grWXKd/

- Debug Page ~ 1 minute after: https://paste.ubuntu.com/p/Hr2YR5J88Y/

- Debug page immediately after "Playback failed"/"Elementum timed out" message: https://paste.ubuntu.com/p/sHVQWtw5mv/

**Logs—version 0.0.46** after disabling "Auto-assign network IP" and "Listen interfaces" set to "tun0":

- Info page ~ 1 minute after torrent clicked:  https://paste.ubuntu.com/p/csPbYdpKRS/

- Info page immediately after "Playback failed"/"Elementum timed out" message: https://paste.ubuntu.com/p/nYRCW3nSGs/

- Debug Page ~ 1 minute after: https://paste.ubuntu.com/p/YfW4JccDyr/

- Debug page immediately after "Playback failed"/"Elementum timed out" message: https://paste.ubuntu.com/p/T6rXRF35dj/

**Logs—version 0.0.47** after disabling "Auto-assign network IP" and "Listen interfaces" set to "tun0":

- Info Page ~ 1 minute after torrent clicked:  https://paste.ubuntu.com/p/7zRCY7yp95/

- Info Page immediately after "Playback failed"/"Elementum timed out" message: https://paste.ubuntu.com/p/TYDsbBDKDY/

- Debug Page ~ 1 minute after torrent clicked: https://paste.ubuntu.com/p/PjqmSJZKnk/

- Debug Page immediately after "Playback failed"/"Elementum timed out" message: https://paste.ubuntu.com/p/kmPHx9yq4W/

- LockTimes Page ~ 1 minute after torrent clicked: https://paste.ubuntu.com/p/XpffNnWcjH/

- LockTimes Page immediately after "Playback failed"/"Elementum timed out" message: https://paste.ubuntu.com/p/s2Vw6zw7PQ/

Moreover, this is not an issue for me at all but I thought I would mention this since it may be related. Upon first installing the last three versions of Elementum (0.0.45/46/47), it crashed about five times before the plugin decided to just not start at all. Once I exit/reenter Kodi though, the plugin acts perfectly normal (other than the preexisting issues being addressed here). In other words, the crashing only happens upon initial installation and never again after the fact.

- Elementum 0.0.47 installation crash log—(debug page loaded while Elementum was in the middle of crashing/restarting): https://paste.ubuntu.com/p/ck6ChsRjF4/

**Comment by elgatito** [comment]
@nvpl , great, you've posted all these logs, but kodi.log is very needed to see what happens in that moment, when you open /debug/ links. Because I don't even see how speed changes with different test environments.

**Comment by nvpl** [comment]
@elgatito I completely forgot about those logs. I am not too familiar with how the logs work; however, to my understanding Kodi creates a new log every time I exit the application. So  I will attach the last two logs I have from Kodi which I assume correspond to the initial installation/crashing of the new 0.0.47 version (**Kodi old log**) and test performed in the previous message 0.0.47 with "Listen interfaces" set to "tun0" (**Kodi new log**) respectively.

**Kodi old log:** https://paste.ubuntu.com/p/jShRdXB5qR/

**Kodi new log:** https://paste.ubuntu.com/p/7htd6C5XqQ/

Thanks again.

**Comment by anacrolix** [comment]
I don't see anything unexpected in the pages or logs from the torrent perspective.

**Comment by elgatito** [comment]
@nvpl can you try with the latest version, setting listen interface to "tun0" (if it's tun0), run download for about a minute. Then, set connections limit (bittorrent settings tab) to about 30, run another download. And then paste full kodi.log (it can be one for all tests). 
Also can you watch CPU usage while download is in progress?

**Comment by nvpl** [comment]
@elgatito 
- How can I tell which listen interface is the correct one to use?

Kodi Log with Listen interface set to "tun0" on latest version (0.0.47 both tests combined in one log): https://paste.ubuntu.com/p/cnKcNP49v8/

Elementum Info page with connections limit set to 30 on "tun0" listen interface: https://paste.ubuntu.com/p/txrP88RvtJ/

Elementum Debug page with connections limit set to 30 on "tun0" listen interface: https://paste.ubuntu.com/p/dYGp56Xn5t/

Link to video of CPU usage: https://streamable.com/ixut1

**Comment by nvpl** [comment]
@elgatito Okay, I have removed connections limit and cleared the "listen interface" but left "auto-assign network IP" off. Feel free to review the video below to make sure my BitTorrent settings tab looks correct. If it makes any difference, while I was installing version 0.0.48 and the initial crashing upon installation occurred again which should be included in the bundle log.

Debug Bundle Log During Download ~ 1 minute: https://paste.ubuntu.com/p/HGp4DmXZNy/

Debug Bundle Log After Clicking Cancel and ~ 1 minute of downloading: https://paste.ubuntu.com/p/qRxpkmJfjK/

Video (CPU Usage/Settings): https://streamable.com/g3q1p

**Comment by elgatito** [comment]
Thanks for providing the logs. 
Have you tried non rarbg torrents? Another tracker/webite?

**Comment by nvpl** [comment]
@elgatito I don't believe I've been selecting ragbg's torrents. I've been using YTS in my video tests. However, I have tried other uploaders as well. If you'd like to provide me with a sample torrent to download I can try that as well.

I just performed another test from a different uploader (MagnetDL) yielding similar results to the rest. Here is the log: https://paste.ubuntu.com/p/hkFYKDQfMc/

**Comment by nvpl** [comment]
@elgatito I wanted to check in and see if I provided the correct logs/see if there is any update regarding this issue.

Thanks again.

**Comment by elgatito** [comment]
```
22:49:41.738 [0mBuffer loop
22:49:42.675 [0m3f2a44: 36 kB/0 B | Buffering (0.01%)
22:49:43.676 [0m3f2a44: 246 kB/0 B | Buffering (0.08%)
22:49:44.677 [0m3f2a44: 891 kB/0 B | Buffering (0.30%)
22:49:45.676 [0m3f2a44: 1.8 MB/0 B | Buffering (0.61%)
22:49:46.678 [0m3f2a44: 2.0 MB/0 B | Buffering (0.71%)
22:49:47.675 [0m3f2a44: 2.3 MB/0 B | Buffering (0.86%)
22:49:48.676 [0m3f2a44: 1.8 MB/0 B | Buffering (0.91%)
22:49:49.676 [0m3f2a44: 904 kB/0 B | Buffering (0.91%)
22:49:50.679 [0m3f2a44: 626 kB/0 B | Buffering (0.91%)
22:49:51.679 [0m3f2a44: 164 kB/0 B | Buffering (0.91%)
22:49:52.676 [0m3f2a44: 0 B/0 B | Buffering (0.91%)
22:49:53.676 [0m3f2a44: 0 B/0 B | Buffering (0.91%)
```
So the speed first was good, then dropped to 0, then upped to 200kb/s after about 30 seconds.
For me it still looks like a network or firewalling issue...
Can you try to set connections limit to 20, start a download, open http://127.0.0.1:65220/info after few seconds, then after another minute.

**Comment by nvpl** [comment]
Not important since the issue doesn't persist after initial installation but, I am pasting this debug bundle installation log which contains the initial crashes here again since you released a new version (0.0.49): https://paste.ubuntu.com/p/Sf4mRRMYft/

Anyways, here is what you requested:

**Connections Limit Set to none**

- Elementum Info Page after ~ 20 Seconds: https://paste.ubuntu.com/p/8QRDmjp8q9/

- Debug Bundle after ~ 20 Seconds: https://paste.ubuntu.com/p/fFfrWsBy5J/

- Elementum Info Page after ~ 1 minute: https://paste.ubuntu.com/p/Zj7b3MknFY/

- Debug Bundle after ~ 1 minute: https://paste.ubuntu.com/p/VGsSzFqgY2/

**Connections Limit Set to 20**

- Elementum Info Page after ~ 20 Seconds: https://paste.ubuntu.com/p/KgvYBHVrYk/

- Debug Bundle after ~ 20 Seconds: https://paste.ubuntu.com/p/ZQkDQchg2W/

- Elementum Info Page after ~ 1 minute: https://paste.ubuntu.com/p/3NrdW6Ncs9/

- Debug Bundle after ~ 1 minute: https://paste.ubuntu.com/p/htzpGH8BQy/

It seems that the buffer did not go above 0 kbps when the connections limit was set to 20. I have pasted logs for both situations using identical torrents.

**Comment by elgatito** [comment]
@anacrolix what do you think?

From the last log (so it's about a minute after start):
```
 TotalPeers: (int) 502,
 PendingPeers: (int) 497,
 ActivePeers: (int) 0,
 ConnectedSeeders: (int) 0,
 HalfOpenPeers: (int) 10
```

**Comment by nvpl** [comment]
Hey @anacrolix, any new insight in regards to @elgatito's message?

Some more info: I tried switching off my VPN to see if that would fix the issue but I received the exact same results. I also tried using my mobile hotspot rather than my home internet without a VPN which also yielded the same results. Hence, I highly doubt it is a firewall issue.

**Comment by anacrolix** [comment]
I'm not sure. I'm suspecting maybe dial timeouts are too high and there are too many bad peers to work through. I'll await @elgatito 's next update, where a lot more information is exposed for debugging.

**Comment by elgatito** [comment]
@nvpl do you still have the issue? Can you test the latest version?

**Comment by nvpl** [comment]
Hi @elgatito,

I apologize for the late response.

I have updated to version 0.0.53 and the speeds seem to have become somewhat functional. Yet, it still pales in comparison to Quasar. Additionally, I think I've finally found the reason as to why the torrent itself never plays (as shown in video) even after buffering. This seems to be a compatibility issue that both Elementum and Quasar have with NVIDIA Shield TVs and official Kodi. The reason I have come to this conclusion is because I installed SPMC (a modified Kodi for Android based systems) and tried Elementum and Quasar on there and both plugins play torrents successfully. However, Quasar buffers at nearly 5x the speed that Elementum does. I would much prefer to use Elementum though because it is being regularly updated. Quasar also has an issue where the video frame stutters every ~3-5 seconds rendering it unusable to watch movies on.

In other words as of version 0.0.53,
- Elementum's speed issue seems to have been fixed to the point that it will complete a buffer (though it won't go above ~1500kbps in official Kodi).
- If using official Kodi from Google Play Store in conjunction with Elementum, playing torrents still fails after the torrent fully buffers.
- If using SPMC 17.6a2 on NVIDIA Shield TV in conjunction with Elementum (with identical settings), buffering speeds are slightly improved (~2000kbps) in comparison to official Kodi; however, still slower than Quasar. Most importantly, the torrent will complete the buffer and play (shown in video below).
- When looking at speeds of Quasar running for a minute on the webUI, the speeds stay pretty stable at around ~7000kbps
- When looking at speeds of Elementum running for a minute on the webUI, the speeds heavily fluctuate after reaching a peak of 2000kbps during buffering then dropping down to 400kbps to 1kbps and kind of float between 1-400kbps for the rest of the time during the video playing.
	- Screenshot of Quasar speeds after 1 minute (webUI): 
![quasar screenshot](https://user-images.githubusercontent.com/39887752/42727449-b9c90e4c-875b-11e8-9515-a50b0fc4d3cc.png)

		- Video displaying my current settings in Quasar (SPMC) along with the buffer and successful play (take note of the significantly higher speeds on the same torrent): https://streamable.com/3qpe6
	- Screenshot of Elementum speeds after 1 minute (webUI): 
![elementum screenshot](https://user-images.githubusercontent.com/39887752/42727455-cddb3400-875b-11e8-849d-f0c9a74b1c30.png)

		- Video displaying my current settings in Elementum (SPMC) along with the buffer and successful play: https://streamable.com/4r6l9

Elementum log from /debug/all after one minute in official Kodi (video fails to play): https://paste.ubuntu.com/p/3kZvdrBVdF/

Elementum log from /debug/all after one minute in SPMC (video successfully plays): https://paste.ubuntu.com/p/2Ws7Qw7FDD/

SPMC debug log Quasar (I used SPMC debug because I don't know where to find debug logs in Quasar): https://paste.ubuntu.com/p/VKXS4GphMK/

Video displaying my current settings in Elementum (Kodi official) along with the buffer and failure to play: https://streamable.com/d3y96

**Comment by elgatito** [comment]
@nvpl thanks for such detailed information. 

When you set memory storage - it downloads only few pieces of file, then download more when needed from Kodi, so you won't see the best speeds and it drops before it gets to the maximum. You can try to set about 300mb per torrent, to see bigger speeds. While you get all you need - speed will be about 0 kb/s, then again rising and falling and so on.

@anacrolix do you anything useful in `/debug/all` dumps? writeChunk speed is good, maxxed at 5ms, but this video it strange - https://streamable.com/4r6l9 , there are so many peers and enough connected, and no write issues, but so small speed and so slowly raising.

**Comment by elgatito** [comment]
@nvpl can you send the kodi.log (of one from /debug/bundle) where playback can't be started with elementum?

**Comment by anacrolix** [comment]
I notice no incoming connections complete handshaking, and there's no incoming TCP connections at all. Everything else looks good.

**Comment by dadittoz** [comment]
There's something really going on with number of connections. I've got it set to 15, but sometimes elementum bursts out with connections:

`
conntrack -L | wc -l
conntrack v1.4.4 (conntrack-tools): 58687 flow entries have been shown.
58687
`
to the point it can no longer make a connection

`
Aug 31 15:59:43 host kernel: [1436784.235951] nf_conntrack: nf_conntrack: table full, dropping packet
`
Hopefully it is related to https://github.com/anacrolix/torrent/issues/234 and will probably be resolved some day.

My ISP goes crazy with a number of connections like this.

**Comment by dadittoz** [comment]
@anacrolix Thank you. But it looks like other torrent clients don't do this at the rate as anacrolix torrent does. This is really problem for, say, routers with NAT or mobile network providers with grey addresses and NAT. Routers surely have linux with conntrack there. It would be nice to have an ability to throttle down these connections.  Because currently it renders unusable anacrolix client for any user behind NAT. 

I would love global connections limit to be applied to DHT connections also. Default nf_conntrack_udp_timeout is set to 30. It would be nice to implement a way to count active and inactive DHT connections and keep them under connection limit.

**Comment by elgatito** [comment]
Please, try with 0.0.63.

**Comment by elgatito** [comment]
@nvpl @strummerj do you still have this issue with the latest Elementum?

**Comment by antonsoroko** [comment]
@JORGETECH 
https://github.com/anacrolix/torrent/issues/265
