### ISSUE TITLE
0.0.46. Loads the buffer but does not play the video

### ISSUE THREAD

**Issue by 000cuenta0001** [elgatito/plugin.video.elementum#171]
0.0.46. version in Libreelec 8.2.3.1. TVbox KI PRO (Amlogic s905D). Loads the buffer but does not play the video:

https://mega.nz/#!vxtwkYZb!lrIQknnklVvCrSdz2E9QIgIv-leXdGN0zsFidoSkQp0

Quasar 9.33 work fine.

I am sorry for my bad english. I hope you can help me. A greeting.

**Comment by elgatito** [comment]
Your Kodi is configured with 40Mb buffer, this means it waits until 40Mb is available to download.
Open Elementum settings, Bittorrent tab and change buffer size from 20mb to 40mb, then try again.

**Comment by 000cuenta0001** [comment]
He found the problem, but I do not know how to fix it. If I deactivate OSCAM, the video plays without problems. I enclose OSCAM configuration files in case you discover any incompatibility with elementum:
https://mega.nz/#!2hlnzLZC!yZx8UKPnmlsojqlpVzHwuJ1qCloivNUPSsa2xogrXrk
A greeting.

**Comment by elgatito** [comment]
If you don't want (or can't) remove buffer for Kodi, then increase bittorrent buffer in Elementum.
OScam is not related to buffers.

**Comment by 000cuenta0001** [comment]
Thanks for your reply. I increased the buffer to 40mb, as he told me, but the problem continued.
As I said, the problem is related to OSCAM, when it is activated, the buffer loads, but the video does not play because OSCAM prevents kodi from connecting to the remote server. It is the same as if the options "allow remote control from applications on this computer" and "allow remote control from applications on other computers" were disabled, that's why I sent you the OSCAM configuration file.

**Comment by elgatito** [comment]
I don't know how oscam can influence Elementum.

**Comment by 000cuenta0001** [comment]
I think it may be because the OSCAM configuration panel works through http: 192.168.x.x: 8.8.8.8
I enclose a detailed log in case it helps you in something: https://paste.kodi.tv/ijudagazor

**Comment by elgatito** [comment]
I don't see any problem from Elementum side in the file.

**Comment by elgatito** [comment]
Try the latest version and set the buffer size to 100mb (just to make sure you have enough before giving playback to Kodi).

**Comment by 000cuenta0001** [comment]
The same problem. If I deactivate OSCAM, the video plays without problems.

**Comment by 000cuenta0001** [comment]
https://mega.nz/#!jlFxzZIY!1KuRaIE5OEE3DoiKlfYQBp2nQllTMKW5VFLaUEoj2Ro

**Comment by elgatito** [comment]
And without oscam same torrent works fine?

It's very strange.
```
13:25:00.037 T:3480220576  NOTICE: [plugin.video.elementum] [33mWARN  btplayer     ▶ playerLoop       [0mPlayback was unable to start after 30 seconds. Aborting...
```

Elementum waits for Kodi to start playback, and Kodi is not requesting data, but nothing happens. 
It looks like it's a known issue with Oscam:
https://www.digital-eliteboard.com/threads/oscam-webif-blocking-localhost-127-0-0-1.428904/

```
Config under [webif] section

httpallowed = 0.0.0.0-255.255.255.255
```

**Comment by elgatito** [comment]
Please, try to update to v0.0.50 and try again with and without oscam. Thanks

**Comment by 000cuenta0001** [comment]
Hi. The same problem.

**Comment by 000cuenta0001** [comment]
I have already found the solution. The OSCAM configuration must not use port 9090. It is used by kodi for the remote server and blocks it.

**Comment by elgatito** [comment]
Ha... funny :) 
Good to hear!
