### ISSUE TITLE
[Bug] v0.47 doesn't keep port assigned

### ISSUE THREAD

**Issue by Pepe-Lucas** [elgatito/plugin.video.elementum#173]
v0.47 alway assigns random ports doesn't matter if I had been assigned it manually. Same happened on v0.4.5 https://github.com/elgatito/plugin.video.elementum/issues/143 and was fixed on v0.4.6.

I'm using CoreELEC 8.90.3 [kodi19] at the same time in my case Elementum doesn't work in CoreELEC. When I try to stream something in Elementum kodi crash but that another issue when I get the log I'll let you know with more details.

**Comment by elgatito** [comment]
Provide a kodi.log.

**Comment by diabl0w** [comment]
[code] 23:24:46.761 T:3747521392  NOTICE: [plugin.video.elementum] INFO  config       ▶ Reload           [0mReloading configuration...
23:24:46.815 T:3747521392  NOTICE: [plugin.video.elementum] INFO  config       ▶ Reload           [0mUsing download path: /storage/download
23:24:46.829 T:3747521392  NOTICE: [plugin.video.elementum] INFO  config       ▶ Reload           [0mUsing library path: /storage
23:24:46.869 T:3747521392  NOTICE: [plugin.video.elementum] [36mDEBU  config       ▶ Reload           [0mTotal system memory: 1.9 GB
23:24:46.870 T:3747521392  NOTICE: [plugin.video.elementum] [36mDEBU  config       ▶ Reload           [0mAutomatically selected memory size: 95 MB
23:24:46.871 T:3747521392  NOTICE: [plugin.video.elementum] INFO  bittorrent   ▶ configure        [0mConfiguring client...
23:24:46.877 T:3747521392  NOTICE: [plugin.video.elementum] INFO  bittorrent   ▶ configure        [0mListenIP=, ListenIPv6=, ListenPort=0, DisableIPv6=false
23:24:46.878 T:3747521392  NOTICE: [plugin.video.elementum] INFO  bittorrent   ▶ configure        [0mUserAgent: Elementum/0.0.47, PeerID: -GT0001-
23:24:46.880 T:3747521392  NOTICE: [plugin.video.elementum] INFO  bittorrent   ▶ configure        [0mDownloadStorage: Memory
23:24:46.882 T:3747521392  NOTICE: [plugin.video.elementum] [36mDEBU  memory       ▶ NewMemoryStorage  [0mInitializing memory storage of size: 95 MB
23:24:46.890 T:3747521392  NOTICE: [plugin.video.elementum] [36mDEBU  bittorrent   ▶ configure        [0mBitClient config: &torrent.Config{DataDir:"/storage/download", ListenHost:(func(string) string)(0x7ebd50), ListenPort:0, NoDefaultPortForwarding:true, DisableTrackers:false, DisablePEX:false, NoDHT:true, DhtStartingNodes:(dht.StartingNodesGetter)(0x5e1acc), NoUpload:false, DisableAggressiveUpload:false, Seed:true, UploadRateLimiter:(*rate.Limiter)(0x11c238b0), DownloadRateLimiter:(*rate.Limiter)(0x11c23860), PeerID:"-GT0001-PXHAXWYTJNXC", DisableUTP:false, DisableTCP:false, DefaultStorage:(*memory.Storage)(0x11fd27e0), EncryptionPolicy:torrent.EncryptionPolicy{DisableEncryption:false, ForceEncryption:false, PreferNoEncryption:false}, ProxyURL:"", IPBlocklist:iplist.Ranger(nil), DisableIPv6:false, DisableIPv4:false, DisableIPv4Peers:false, Debug:false, HTTP:(*http.Client)(nil), HTTPUserAgent:"Elementum/0.0.47", ExtendedHandshakeClientVersion:"", Bep20:"-GT0001-", NominalDialTimeout:0, MinDialTimeout:0, EstablishedConnsPerTorrent:0, HalfOpenConnsPerTorrent:0, TorrentPeersHighWater:0, TorrentPeersLowWater:0, HandshakesTimeout:0, PublicIp4:net.IP(nil), PublicIp6:net.IP(nil)}
23:24:46.891 T:3747521392  NOTICE: [plugin.video.elementum] INFO  bittorrent   ▶ configure        [0mClient created successfully
23:24:46.892 T:3747521392  NOTICE: [plugin.video.elementum] [36mDEBU  bittorrent   ▶ configure        [0mClient listening on tcp: 0.0.0.0:52713
23:24:46.892 T:3747521392  NOTICE: [plugin.video.elementum] [36mDEBU  bittorrent   ▶ configure        [0mClient listening on tcp: [::]:52713
23:24:46.893 T:3747521392  NOTICE: [plugin.video.elementum] [36mDEBU  bittorrent   ▶ configure        [0mClient listening on udp: 0.0.0.0:52713
23:24:46.893 T:3747521392  NOTICE: [plugin.video.elementum] [36mDEBU  bittorrent   ▶ configure        [0mClient listening on udp: [::]:52713
23:24:46.894 T:3747521392  NOTICE: [plugin.video.elementum] [GIN] 2018/06/12 - 03:24:46 | 200 |    5.850459ms |       127.0.0.1 | GET      /cmd/clear_page_cache [/code]

**Comment by elgatito** [comment]
I see random port assignment in that chunk of log.

**Comment by diabl0w** [comment]
the configured settings for that log were "auto-assign network ports" =
disabled and then manual ports were entered under that setting

**Comment by elgatito** [comment]
@diabl0w thanks, now I see it. Should be fixed in the next version.

**Comment by diabl0w** [comment]
thank you for all your work

**Comment by elgatito** [comment]
Please, try with 0.0.48.

**Comment by diabl0w** [comment]
fixed 0.0.48
