### ISSUE TITLE
"Watched" mark in "TV shows" library

### ISSUE THREAD

**Issue by bart02** [elgatito/plugin.video.elementum#177]
The "Watched" mark does not work when added to the library and watching through "TV shows" in the menu on the left.

## Your Environment

* Version used:
Elementum 0.0.49
* Environment name and version:
Kodi 17.6 Krypton
* Operating System and version:
Andorid 7

**Comment by elgatito** [comment]
Reproduce the bug.
Open Status menu item in Elementum main menu. 
Upload downloaded log file into this issue.

**Comment by elgatito** [comment]
```
Can't find episode for these parameters: ... ShowID:48866 Season:2 Episode:2 
```

Elementum could not found show with that TMDB ID, so it could not update watched state in the library.

**Comment by bart02** [comment]
> TMDB ID
I don't use the TMDB account

**Comment by elgatito** [comment]
If you don't scrape shows/movies with TheMovieDB scraper or Universal scrapers (which find TMDB ID and save it) - then Elementum is not able to find item in Kodi library.

**Comment by bart02** [comment]
I use TMDB plugin for information about the shows in the library.
Waht can I do?

**Comment by elgatito** [comment]
I don't know how your Kodi library looks like. 
If your Kodi library is scraped with TMDB, and you play episode of the show, that you see in the library - Elementum will find the match and update it after you finish playback.
You can try re-check if your shows are scraped with TheMovieDB and not TVDB scraper.

**Comment by bart02** [comment]
![photo_2018-06-18_14-57-14](https://user-images.githubusercontent.com/19249148/41524486-e760540e-7307-11e8-92d9-dfcade27d750.jpg)
Yes. I using TheMovieDB.

**Comment by elgatito** [comment]
You can send "app.db" file in plugin.video.elementum directory, I will see what Kodi items Elementum gets.

**Comment by bart02** [comment]
What is the full path to the directory?
I can't find it in `/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum`

**Comment by elgatito** [comment]
https://kodi.wiki/view/Userdata#Android_location
You need another directory. userdata/addon_data/plugin.video.elementum/

**Comment by bart02** [comment]
[db.zip](https://github.com/elgatito/plugin.video.elementum/files/2110448/db.zip)

**Comment by elgatito** [comment]
Very strange. There are not IDs received from Kodi. 
Can you try to delete cache.db and cache-backup.db from that folder and restart Elementum (Kodi)?

**Comment by bart02** [comment]
I checked now. If I add another TV show to library (e.g Game of Thrones), mark is working.

> Can you try to delete cache.db and cache-backup.db

OK. I deleted it. But the mark has not earned for this series.

**Comment by elgatito** [comment]
You are sure that tvshow files are generated by Elementum and are scraped by TMDB? Do you see it in the same directory as Game of Thrones?

**Comment by bart02** [comment]
Yes.

**Comment by elgatito** [comment]
You can try to:
1) remove strm files from disk
2) cleanup Kodi library (it will remove only entries, which are deleted from the disk), 
3) delete app.db
4) restart Kodi
5) readd show to the library.

There is something with that show probably.

**Comment by bart02** [comment]
I reinstall Kodi and plugin, and problem solved.
