### ISSUE TITLE
Tv shows with single quote

### ISSUE THREAD

**Issue by ppaladin01** [elgatito/plugin.video.elementum#179]
Hi!
I would like to thank you for this amazing addon.
However, I realized that tv shows titles with single quotes return with the error "No links were found".
Some examples: The handmaid's tale and all the marvel's shows.
I have tested the last version (0.0.49) and the error persists.

Since Quasar works fine with those titles, I wonder if there's a chance to fix this.

Thanks in advance.

**Comment by elgatito** [comment]
```
Searching with payload (episode): {u'episode': 6, u'title': u'\u0440\u0430\u0441\u0441\u043a\u0430\u0437 \u0441\u043b\u0443\u0436\u0430\u043d\u043a\u0438', u'season': 1, u'tvdb_id': 321239, u'imdb_id': u'tt5834204', u'titles': {u'ru': u'\u0440\u0430\u0441\u0441\u043a\u0430\u0437 \u0441\u043b\u0443\u0436\u0430\u043d\u043a\u0438', u'en': u"the handmaid's tale", u'ua': u'\u0456\u0441\u0442\u043e\u0440\u0456\u044f \u0441\u043b\u0443\u0436\u043d\u0438\u0446\u0456', u'original': u"the handmaid's tale", u'source': u"The Handmaid's Tale"}, u'absolute_number': 0, u'year': 2017}
```

This is all about the searcher. Some trackers find results with quotes, some do not. Quasar was removing quotes, it was helping for some trackers/requests, but some were failing. 
Maybe it will be fixed in burst.
