### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by DFergFLA** [elgatito/plugin.video.elementum#18]
I am unable to find any ansers to my questions so I am posting here.

1.  The add on works great for me, Thanks
2.  I keep getting this status thing over the top off the video while I am watching it.  It gives me download info.  I tried turning off "Enable Overlay Status" and rebooting but the damn overlay will not go away.  It is very anoying.
3.  what is the difference between "Add to Library" and "Merge to Library?"

**Comment by DFergFLA** [comment]
I found by switching the skin this problem goes away

**Comment by elgatito** [comment]
Merge means plugin overwrites the strm file on the disk. 
By default, it skips that operation to avoid corrupting your own strm files and making duplicates.

**Comment by DFergFLA** [comment]
1.  I am having a new issue.  but I can't open a new issue.  It keeps telling me over and over and over I have to read the guidlines.  I have read them, how many times do I have to read them before I can open a new issue?

**Comment by elgatito** [comment]
Github is not owned by me, not a question for me, neither.

**Comment by elgatito** [comment]
I'm closing this issue?
