### ISSUE TITLE
Burst not working with 0.0.50 version

### ISSUE THREAD

**Issue by Jezze83** [elgatito/plugin.video.elementum#180]
When i select episode kodi says error and check from log. Here is log from debug/bundle: http://paste.ulvis.net/CMlNC46r
Kodi log: http://paste.ulvis.net/kPFssiOb

Kodi is restarted after update but still not working.

**Comment by elgatito** [comment]
Please, update to 0.0.51 to fix.

**Comment by Jezze83** [comment]
Thanks, works now.
