### ISSUE TITLE
Can't Add Torrent or Magnet links using the webui.

### ISSUE THREAD

**Issue by xsoalokinx** [elgatito/plugin.video.elementum#181]
Basically, when manually entering in torrent/magnet links and clicking "Stream" does not work.
No links seem to be working. And after hitting Stream, nothing happens on either kodi or the webui.
Selecting and choosing a local torrent file was working in 0.49 but doesn't work anymore in 0.51 as well.

Tested on:
Elementum win-x64 /w Burst 0.0.49-0.0.51
Windows 7 x64
Firefox/Google Chrome Browsers.
Kodi 17.6

The only thing I am seeing in the kodi.log is 

`NOTICE: [plugin.video.elementum] [GIN] 2018/06/21 - 01:35:01 | 200 |            0s |   192.168.0.197 | POST     /playuri`

**Comment by elgatito** [comment]
Thanks, good catch. 
Will be fixed in the next version.

**Comment by xsoalokinx** [comment]
No problem, and thank you as well for the support and maintenance of Elementum :) 
Will be sure to keep a lookout for other bugs.

**Comment by elgatito** [comment]
Should be fixed in v0.0.52

**Comment by abioneperhobby** [comment]
@elgatito yeah, now it also works on amazon fire stick . thanks.
