### ISSUE TITLE
Burst not work with libreelec and cannot find update

### ISSUE THREAD

**Issue by Jezze83** [elgatito/plugin.video.elementum#182]
As title says. Latest version for raspberry libreelec is 0.0.50 and burst not work. It wont find 0.0.51 version when i try update. Same problem lime windows version. I used universal package.

**Comment by elgatito** [comment]
Elementum has a self-maintained repository. So when plugin does not work - it cannot update itself. 
You should download and reinstall the plugin with 0.0.51, it will start working.
