### ISSUE TITLE
Изменения размера буфера не доступно в версии 51

### ISSUE THREAD

**Issue by yatsek20** [elgatito/plugin.video.elementum#184]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

**Comment by yatsek20** [comment]
в версии 51 не дает изменить размер буфера, кнопка отключена на автоматич параметр, но меню изменения не активно. Коди перегружал не сколько раз . Коди 18 альфа 2, но думаю это не важно, система coreelec. https://d.radikal.ru/d41/1806/5e/10e15a432c05.jpg

**Comment by elgatito** [comment]
Скорее всего глюк в Коди. У меня нормально работает на стабильной версии. 
Можете попробовать попереключать автоматический выбор размера.

**Comment by yatsek20** [comment]
спасибо за помощь
