### ISSUE TITLE
Elementum stop playing in the end

### ISSUE THREAD

**Issue by Jezze83** [elgatito/plugin.video.elementum#185]
I use download storage type: use memory. Problem is elementum stop playing about in 97%. It freezes and then just stop playing. I want use that use memory instead download to hdd. With use files option it works normal. Attached bundle/debug log file.
[bundle_2018_6_23_15_30.log](https://github.com/elgatito/plugin.video.elementum/files/2129898/bundle_2018_6_23_15_30.log)

**Comment by elgatito** [comment]
@Jezze83 do you see the issue with the latest version?

**Comment by elgatito** [comment]
Closing non-responded issue.
