### ISSUE TITLE
Elementum deletes file and directory after download or after watching

### ISSUE THREAD

**Issue by JamesDandy** [elgatito/plugin.video.elementum#186]
Elementum 0.0.51 deletes the file and directory after the file is downloaded or watched. If I'm watching the video during download, it remains until I end the video, then it deletes and removes the file and directory. If I'm just downloading and not watching, I can see the file and directory as it downloads but once complete it just goes away. 

I have set the following options:
  Download Path: C:\Downloads\Movies
  Library Path: c:\...\Kodi\userdata\addon_data\plugin.video.elementum
  Download after play: Continue
  Keep files for not finished video: Keep
  Keep files for watched/downloaded video: Keep
  Move finished downloads to separate folders: On
  Movies: C:\Download\Movies
  TV Shows: C:\Download\TVShows

## Expected Behavior
I expect that after either downloading or watching a move as it downloads that the file and its directory remain in the c:\downloads\Movies folder 

## Current Behavior
If I'm watching a movie as it downloads, it removes itself after I'm done watching. Sometimes I exit a movie at the beginning so I can start a second download. While the other files are downloading, the directory and file are created and available but as soon as the download is complete, both the file and directory disappear. The only way I can seemingly save a file after downloading is by watching each movie until it is fully downloaded then I can copy the folder to another name to save it. As soon as I end watching the movie through Elementum, it deletes itself. 

## Your Environment
Windows 10
Kodi 17.6
Elementum 0.0.51
Burst 0.0.17

**Comment by elgatito** [comment]
https://kodi.wiki/view/Log_file/Easy

**Comment by elgatito** [comment]
@JamesDandy  I will close the issue if you won't provide a log file.

**Comment by elgatito** [comment]
Closing as no log provided.

**Comment by JamesDandy** [comment]
I never saw an email asking for a log until I received the email saying that you will close the issue. The message above where you "asked" for a log is just a link and does not actually ask for anything. 

I still have an issue, it's not consistent but I've had to watch a movie or pause a movie until it's fully downloaded, then I copy the movie's folder. Then I can let movie finish or just stop playing it and in some cases it deletes the folder, other times it doesn't. I don't understand the inconsistency. 

The prompt asking if I want to continue downloading doesn't seem to be clear either, especially since I get this when the movie is fully downloaded or not.

I'm happy to provide a log if you reopen the issue.

**Comment by elgatito** [comment]
@JamesDandy if you have an issue - you have to reproduce it and send log file, so it can be found.

**Comment by Jestar342** [comment]
I've just had this same issue. 
[kodi.log](https://github.com/elgatito/plugin.video.elementum/files/2516769/kodi.log)

**Comment by afduggirala** [comment]
I am having a similar issue in Kodi 17 on Debian. Elementum does not “Ask” anything, even though Ii have set it to “Ask to delete” when for “not finished video” and “watched/downloaded video”. A log file here https://pastebin.com/raw/3pY4zpeX ,
thanks
