### ISSUE TITLE
elementum doesn't download torrents sequentially when using file storage

### ISSUE THREAD

**Issue by Timo1979** [elgatito/plugin.video.elementum#189]
Elementum doesn't download torrents sequentially when using file storage.

UPD: I reinstalled libreElec 8.2.5 + elementum 0.0.51 from scratch, erasing all content of sd-card, but still have the same issue.

## Expected Behavior
Elementum must download torrents sequentially to be able to watch movies smoothly

## Current Behavior
Elementum downloads torrent pieces randomly.
I partially downloaded movie with elementum, then upload partially donwloaded movie to PC, and saw this picture: [https://yadi.sk/i/P1c9IIr-3YXVUo](https://yadi.sk/i/P1c9IIr-3YXVUo)

## Possible Solution
enable sequential download

## Steps to Reproduce (for bugs)
1. Enable storing torrents as files
2. Try to watch any movie (not already present as local file)
3. Internet connection must not be very fast. Mine is 10 Mbit/s

## What already done
Tried to find option in plugin's settings - without success.

## My Environment
Raspberry Pi 3 + Libreelec 8.2.5 + elementum 0.0.51

**Comment by rosskopf** [comment]
I have the same problem

LibreELEC-Generic x64 + libreelec 8.2.5 + elementum 0.0.51

**Comment by rosskopf** [comment]
I have the same problem

LibreELEC-Generic x64 + libreelec 8.2.5 + elementum 0.0.51

**Comment by elgatito** [comment]
Elementum is not downloading anything. It's done by torrent library (https://github.com/anacrolix/torrent ) and it uses priorities for torrent pieces. The one that would be needed soon - get more priority and gets download earlier.

If you believe it does not act in that way with the latest version of Elementum - you can create an issue in library's repository.
