### ISSUE TITLE
Starting playback of a previously downloaded/played torrent fails

### ISSUE THREAD

**Issue by DFergFLA** [elgatito/plugin.video.elementum#19]
If I am watching a torrent and I stop playback I am asked if I want to continue downloading.  I say yes.

When I go to restart watching that torrent I get asked "Match found in your active tottent, play it?"  I say Yes

Then I get asked 'Keep Downloading" I say Yes

Then I get "Can't find next item to play"

I have tested this on several TV episodes and movies.

I am running LibraELEC
Kodi 17.6

I can verify that there is the video file in the downloads folder configured in setting that matches the torrennt I want to resume playing.  I can verify that If I use the Kodi "file exporing" and manually navigate to this file, it will play.

**Comment by elgatito** [comment]
It would be better if you can open Kodi, do all the operations and show the log (can use paste.ubuntu.com or whatever).

**Comment by elgatito** [comment]
Can you try your case with the latest version?

**Comment by perflow** [comment]
I had the same issue as the op, 
first attempt with version 0.0.25 worked and played fine
but when I stopped the playback and tried to play again from the torrent menu, it was stuck at buffering.

I've added a log of several unsuccessful attempts of playback a downloading torrent from elementum torrents menu.

https://pastebin.com/XbqxytR8

**Comment by elgatito** [comment]
@perflow , don't know what to look for in that log, but you have probably enabled some features in fanart section of elementum?

```
22:56:30.736 T:17012   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.elementum/extrafanart/
```

**Comment by perflow** [comment]
I think you can re-create this issue, I tried it on Win X64 and android, facing the same issue

play a torrent, let it buffer a little and stop playback
continue downloading in background
go to Torrents menu
start playback this torrent and stop it again
try to play the torrent the 2nd time will lead to Buffering (0.00%) indefinitely

**Comment by burekas7** [comment]
@elgatito 
I have this problem too as the same as @perflow 
It show the dialog with Buffering 0.00% and not play the video.
The download still running in the background.
Image: https://s18.postimg.org/jgw05hku1/screenshot020.png

Version: 0.0.30
Kodi 17.6
Windows 10, 64 bit

**Comment by elgatito** [comment]
Can anybody send the log for this issue with the latest Elementum version?

@perflow , @DFergFLA ?

**Comment by elgatito** [comment]
Log is not needed, I could reproduce on my side.

Can you check the issue with 0.0.32?

**Comment by perflow** [comment]
I've checked, and it seems that you have fixed it. nice job

**Comment by burekas7** [comment]
I've checked it too, and it seems that you have fixed it. Thanks.

But. there is another issue regarding this, when I go in the addon and choose again the Movie, it recognizes it and asking me "Match found in your active torrents, play it?", and when I choose 'Yes', the dialog of "Keep downloading?" jumps instead of play it.
Pressing 'Yes' and it keep downloading in the background, pressing 'No' shows "Playback fail" message and the it still keep downladong in the background.

Log: https://pastebin.com/hezFhbD5

**Comment by elgatito** [comment]
I have also noticed not properly managed active torrents. 
Will rewrite it in the next version. 
I think it's fine to keep in this issue, as long as it's very related.

**Comment by elgatito** [comment]
@burekas7 @perflow @DFergFLA , please, check the latest 0.0.36. It it re-adding previous torrent on restart (only for non-memory storages), and few more fixes mentioned here.

**Comment by burekas7** [comment]
The same problem in comment https://github.com/elgatito/plugin.video.elementum/issues/19#issuecomment-358913817
Nothing have been changed.

**Comment by burekas7** [comment]
@elgatito 
Have you checked the problem I mentioned in #19 (comment) ?
From the torrent list it resumes and play.
But when choosing the same content and confirm to use the active torrent, nothing happens.
(0.0.39)

**Comment by elgatito** [comment]
Should be working fine in latest versions.
