### ISSUE TITLE
Упс перезапуск

### ISSUE THREAD

**Issue by yatsek20** [elgatito/plugin.video.elementum#190]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

**Comment by yatsek20** [comment]
коди 17,6 плагин стоит 51  версия Высккивает ошибка Упс перезапуск много ошибок, в коди либере поставил в лог только ошибки и вот одна ошибка повторяется
 15:45:58.605 T:3755996000   ERROR: [plugin.video.elementum] ValueError("invalid literal for int() with base 10: ''",)
15:46:04.971 T:3755996000   ERROR: [plugin.video.elementum] ValueError("invalid literal for int() with base 10: ''",)
15:46:10.063 T:3755996000   ERROR: [plugin.video.elementum] ValueError("invalid literal for int() with base 10: ''",)
ранее все работало и ни чего не менял. Вкл коди 18 альфа 3 там такой ошибки нет и все работает, но есть свои баги из-за альфа 18.

**Comment by yatsek20** [comment]
переустановил плагин вроде бы работает, спасибо

**Comment by elgatito** [comment]
Коди хранит конфиги и настройки плагинов в одних и тех же папках, вне зависимости от версии Коди, а в новой 18 версии они меняют работу с настройками.
Судя по логу 18 версия изменила настройки, а старая их разобрать не смогла.
