### ISSUE TITLE
[Sugestion] showrss.info

### ISSUE THREAD

**Issue by co5mo** [elgatito/plugin.video.elementum#191]
Hi I would love to be able to add rss from showrss.info into elementum thanks
I use it for late night shows

**Comment by elgatito** [comment]
This is a big bunch of work to add this when we already have providers and searchers.
You can use Trakt to properly track (and add to Kodi library) aired episodes and providers in burst to find them.

**Comment by co5mo** [comment]
but I could use this to launch magnet right?
        `link = 'plugin://plugin.video.elementum/play?uri=%s' % uri_string`
