### ISSUE TITLE
Select torrent option for TV Show Seasons it's not available

### ISSUE THREAD

**Issue by RikrdoPC** [elgatito/plugin.video.elementum#192]
## Expected Behavior
When opening the Context menu over a TV Show Season there should be an option to search and chose one of the found torrents.

## Current Behavior
Currently only the AutoPlay option is available, which automatically selects the first torrent from the list.

## Possible Solution
Treat it as a regular episode where you have the two options.

## Steps to Reproduce (for bugs)
1. Browse through the menus up to a TV Show Season.
2. Open the context menu pressing "c".
3. Only available option is to AutoPlay.

## Context
It'll be better to have the option to select the desired torrent as not always the first one is the best choice.

## Your Environment
Android TV 8.0.0
KODI 17.6
Elementum 0.0.51
Burst 0.0.18

**Comment by Nemiroff** [comment]
https://github.com/elgatito/elementum/issues/5#issuecomment-387304602

**Comment by elgatito** [comment]
I have added another option to season context menu in v0.0.52. 
Now there are both options.

**Comment by dbarev** [comment]
Thanks much!
