### ISSUE TITLE
Elementum daemon won't start

### ISSUE THREAD

**Issue by peter099** [elgatito/plugin.video.elementum#193]
I have Gaia and Elementum installed on the master profile - Gaia is enabled, Elementum is disabled. I created additional profile which i want to use only for torrent streaming with Gaia and Elementum. I enabled only these two addons on the profile but if i try to open Elementum i get error message. And it also doesn't start the elementum daemon. These are the errors in the log file: https://paste.ubuntu.com/p/FktdZJ8WPs/

Any idea what they mean. I am using Kodi 17 on Windows 7 x64.

**Comment by peter099** [comment]
This is the log with debig mode enabled: https://paste.ubuntu.com/p/pppqNkCZvf/

**Comment by elgatito** [comment]
Looks strange. I can't see where it tried to start elementum on Kodi startup.

**Comment by peter099** [comment]
I uninstalled Elementum from the master profile and downloaded the Elementum .zip file for windows x64. Then i installed Elementum from the .zip file on my new profile but i am getting the same error when i try to open elementum and the deamon also do not start. This is the log: https://paste.ubuntu.com/p/FXcWpmc3CP/. I am unable to open elementum repository also, it says it can't connect to repository. It seems that elementum works only when it is installed on the master profile.

**Comment by elgatito** [comment]
Elementum has a self-hosted repository, it manages updates itself. 
If you want to reinstall - download zip file from http://elementum.surge.sh and install it.
I don't see Kodi starting JSONRPC and Elementum trying to start the binary. 
Make sure you enabled remote control when in portable mode.

**Comment by peter099** [comment]
Have you tried to install elementum on a profile that is not the master profile? Does it work for you?

**Comment by elgatito** [comment]
@peter099 I have tried to install on a new profile on Kodi 18, and it worked fine. Maybe they have changed something in 18th.

**Comment by elgatito** [comment]
Is this an issue with the latest version of Elementum?

**Comment by sfjuocekr** [comment]
Delete the file called ".lockfile" in the plugin directory

**Comment by peter099** [comment]
I don't remember what version was. As i wrote in the original post i had this issue on other than the master profile. But i installed elementum on the master profile on a separate kodi install and elementum is working fine.
