### ISSUE TITLE
[QUESTION]Can elementum play local .torrent files?

### ISSUE THREAD

**Issue by bugatsinho** [elgatito/plugin.video.elementum#198]
Hi @elgatito thank you for your work at this project.
i would like to ask if it is possible to load local .torrent files in elementum and if yes how?
i created an addon for a private torrent website after i get  owner's permission and im looking to stream the .torrent files that im downloading from that website!any help or ideas how to workaround this are welcome and really apreciated.
I used yatp addon to stream them but unfortunately i found out that libtorrent doesnt work on android6+ devices.
THANK YOU

**Comment by shizeeg** [comment]
@bugatsinho  Absolutely. Just open http://localhost:65220/web/ in your browser and click <add torrent>

**Comment by elgatito** [comment]
@bugatsinho https://github.com/elgatito/elementum/blob/master/api/torrents.go#L314
You can pass uri with url to torrent file or magnet, or pass "file" in post method with torrent file contents.

**Comment by bugatsinho** [comment]
thank you for your reply

**Comment by elgatito** [comment]
Closing this issue.

**Comment by alexprimaid** [comment]
can i do only download .torrent file ?
