### ISSUE TITLE
Slow speed in elementum 0.0.53

### ISSUE THREAD

**Issue by ilanerukh** [elgatito/plugin.video.elementum#199]
I'm getting very slow speed in the latest elementum version (0.0.53) both in windows 10 and in Android TV Oreo.

The same torrent is downloaded in 3.0 MB/s in qBittorrent. It looks like elementum can not be connected to all peers. I use the Bittorent tab default settings, without any limit on connections.  Using File option. Maybe it's not related, but after it downloads 10 percent, it's still on buffering.

Everything worked well for me until 0.0.51.

Here is a log from the windows machine:
https://paste.ubuntu.com/p/dDSgRHvfS2/

**Comment by elgatito** [comment]
@ilanerukh your log is not informative. 
Download proper information from /debug/bundle link (can find in Elementum -> Status)

**Comment by ilanerukh** [comment]
https://paste.ubuntu.com/p/pDkWHJYrcD/

**Comment by elgatito** [comment]
> Download proper information from /debug/bundle link (can find in Elementum -> Status)

I was asking for this. Not another piece of log.

**Comment by ilanerukh** [comment]
That's the file I get while I download the debug information from Status.

**Comment by elgatito** [comment]
> https://paste.ubuntu.com/p/p7PczfxC2y/

> Updated log.

It is not.

**Comment by ilanerukh** [comment]
That's the entire file that I download in http://KODI_IP/debug/bundle :
https://www.sendspace.com/file/ko1wsn

**Comment by elgatito** [comment]
You have selected file storage, which is not always writing fast, depends on the OS.
Try switching to memory storage, until files are fixed.

**Comment by elgatito** [comment]
Just wait. It's in progress, probably. 
Can track it here: https://github.com/anacrolix/torrent/issues/265

**Comment by ilanerukh** [comment]
In another look, the problem remains even with memory storage.
Here is the file:
https://www.sendspace.com/file/ylb0l8

**Comment by elgatito** [comment]
```
14:24:22.599 T:12576  NOTICE: [plugin.video.elementum] DEBU  bittorrent   ▶ progressEvent    3a2ecc: 3.0 MB/0 B | Buffering (0.51%)
14:24:23.598 T:12576  NOTICE: [plugin.video.elementum] DEBU  bittorrent   ▶ progressEvent    3a2ecc: 2.9 MB/0 B | Buffering (0.62%)
14:24:24.598 T:12576  NOTICE: [plugin.video.elementum] DEBU  bittorrent   ▶ progressEvent    3a2ecc: 3.0 MB/0 B | Buffering (0.73%)
```

Looks fine to me. Memory storage does not download all file, only pieces that needed for Kodi. So it looks like big speed, then even 0 kb/s, then again big speed and so on.

**Comment by ilanerukh** [comment]
That's why I thought it worked fine, but after trying again, the speed is really slow:

> :34:36.910 T:12576  NOTICE: [plugin.video.elementum] DEBU  bittorrent   ג–¶ progressEvent    725607: 351 kB/0 B | Buffering (0.71%)
19:34:36.948 T:12576  NOTICE: [plugin.video.elementum] DEBU  memory       ג–¶ MarkComplete     Complete: 6216
19:34:37.827 T:12576  NOTICE: [plugin.video.elementum] DEBU  memory       ג–¶ Start            Cap: 209715200 | Size: 23412736 | Items: 45 | Capacity: 402
19:34:37.909 T:12576  NOTICE: [plugin.video.elementum] DEBU  bittorrent   ג–¶ progressEvent    725607: 321 kB/0 B | Buffering (0.72%)
19:34:38.827 T:12576  NOTICE: [plugin.video.elementum] DEBU  memory       ג–¶ Start            Cap: 209715200 | Size: 23511040 | Items: 45 | Capacity: 402
19:34:38.909 T:12576  NOTICE: [plugin.video.elementum] DEBU  bittorrent   ג–¶ progressEvent    725607: 262 kB/0 B | Buffering (0.72%)
19:34:39.031 T:12576  NOTICE: [plugin.video.elementum] DEBU  memory       ג–¶ MarkComplete     Complete: 6217
19:34:39.827 T:12576  NOTICE: [plugin.video.elementum] DEBU  memory       ג–¶ Start            Cap: 209715200 | Size: 23937024 | Items: 46 | Capacity: 402
19:34:39.912 T:12576  NOTICE: [plugin.video.elementum] DEBU  bittorrent   ג–¶ progressEvent    725607: 259 kB/0 B | Buffering (0.74%)
``

Again, the same torrent from the same tracker downloads in 3.0 mbps in qBittorent.

**Comment by elgatito** [comment]
> Any update on the issue? 

No. 
It is not the problem with the plugin, so we wait till the fix is there (if there is one).

**Comment by trinaldi** [comment]
I revert to the .48 version and it works fine (i.e "full speed")

**Comment by ilanerukh** [comment]
Indeed the speed in the old versions is way better. Would be happy to revert the changes that caused it in the latest versions with the new features.

Thank you.

**Comment by elgatito** [comment]
Okay. No help with finding the reason, then I'm closing the issue.
Cheers.
