### ISSUE TITLE
Adding and removing movies/shows from Trakt lists

### ISSUE THREAD

**Issue by jorgecardoso220** [elgatito/plugin.video.elementum#200]
Hello,

Is it possible to improve the "Added configuration for adding and removing movies/shows from Trakt lists when operated in Kodi library." so we can choose a specific list instead of "My Collection" or My Watchlist"?

Thanks for all the work

**Comment by elgatito** [comment]
Added in v0.0.54. Choose Userlist and then select list (don't forget to save plugin settings after selecting the list).
Cheers.
