### ISSUE TITLE
Where to set Listening address to tunnel ("ListenAddr:"tun0:8890")

### ISSUE THREAD

**Issue by XanderCam** [elgatito/plugin.video.elementum#203]
I have seen on the forum here mentioned that it is possible to set Elementum to use a tunnel address.
I can't find out where to do that. Is is neccessary to edit a config file ?
If so, which and where ?

##Enviroment
KODI 17 on Raspberry PI 2
Elementum: Newest build

## Request change in GUI
I would like a simple way to choose listening address in the Elementum GUI.
I have set up VPN on my Raspberry PI with a working tunnel.
I would like to be able to make sure Elementum makes use of that tunnel at all times without having to edit any config files. maybe a dropdown box showing the available "adapters" then a setting to choose when and where to use that listening address.

**Comment by elgatito** [comment]
In Elementum settings disable automatic IP/port assignment. Set network interface to "tun0", set port min and port max to 8890, it should resolve to tun0:8890.
