### ISSUE TITLE
[Open Issues] TV Shows -> My Progress

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#206]
According to these issues:
* [Features Request] Regarding the 'TV Shows -> Progress' (#86)
* [Bug] 'TV Shows -> Progress' isn't synchronizing and updating (#121)

First I want to thank you for the implementation, I'm appreciating that.
@elgatito 

I have few open issues regarding the "Progress" section according to 0.0.54 .
I will start with the first one and then I will continue to the next one.

1) I don't understand the "Date Format" setting.
What should I need to enter in order to get this format:  **dd-mm-yyyy** ?
Because each try is changing the Progress list and the dates looks strange.

===
Elementum 0.0.54
Kodi 17.6
Win 10, 64bit

**Comment by elgatito** [comment]
It's how Golang's date formatting works. They don't operate with yy/mm/dd. 
https://golang.org/pkg/time/#pkg-constants
You have to use same numbers, but can place in desired order -> `02-01-2006`

I will try to migrate to usual date formats.

**Comment by burekas7** [comment]
Update regarding to '1' and '2':
It seems that each enter to "My Progress" generates a different list (Sometime 4 episodes are shown, sometimes 6, 3 ,8 etc.), not stable.

5. New issue, the sort order by date (newer/older) doesn't sort it as it should be.

**Comment by elgatito** [comment]
1. There was a bug with list of shows, it's now fixed.

2. Same.

3. Added to settings.

4. It's something with your skin if you still see it with last release.

5. I have checked sort by date and it's working fine. It's sorting by the date, that you see in the list (date when episode was aired).

Try 0.0.55.

**Comment by burekas7** [comment]
Thanks!
So according to 0.0.55 - Updates:

A. Regarding the date sort, as you thought, it seems to be a skin issue. I have changed it to 'default' sorting and it's ok (It seems that there is a problem with the 'Date' sorting)

B. Thanks for the new color option.
But there is a little bug with the string name of the setting. You write 'Color of an episode name' twice.
I think the correct form should be like this:
- Color of an aired episode name
- Color of an unaired episode name
![elsettings](https://user-images.githubusercontent.com/13424257/43002980-4d52c5f0-8c1a-11e8-98e2-f1d77d951db7.png)


C. Regarding to the [/B] there, it seems to be also a skin issue.
For an unknown reason just this View Type shows this, while the others don't.

D. The 'Progress' list is much better now and stable.
**But** there is still one episode which missing (Comparing to the reference image: The Last Ship's episode is missing there).
One reason I can think about is that Elementum is based on tmdb and not tvdb or trakt for TV Showes (Like the reference image)
But maybe there is another reason.
Log will help here?

Elementum:
![ellist](https://user-images.githubusercontent.com/13424257/43003113-cfca38b0-8c1a-11e8-98df-4fe99f491a12.png)

Reference:
![ref](https://user-images.githubusercontent.com/13424257/43003108-c5e95db2-8c1a-11e8-93b5-e7ea22216272.png)

**Comment by elgatito** [comment]
Will be fixed in the next version.

**Comment by elgatito** [comment]
```
But there is still one episode which missing (Comparing to the reference image: The Last Ship's episode is missing there).
One reason I can think about is that Elementum is based on tmdb and not tvdb or trakt for TV Showes (Like the reference image)
```

Please, try 0.0.56. I have changed how Trakt items are printed, so if it's not found in TMDB - you will see the way it looks in Trakt (or if you select to always show Trakt items in Trakt lists).

**Comment by burekas7** [comment]
1. Thanks, it's working.

2. Are you sure? Previously the Fanart and the thumbnail (Which was the same) shows the episode fanart&thumbnail. Currently, The thumbnail shows the TV Show poster image, and the Fanart shows the TV Show's fanart. Something has been changed.

3. Only the sorting by name is working for me. The other sorting by date isn't.
It looks like the list doesn't update the order.
For example, I watched one of the episodes there, and the new one is located now at the first index, and all the rest are sorted by date. And no matter if I'm choosing older/newer, it remains the same.
Kodi sorting is by 'default'.
Strange.

**Comment by elgatito** [comment]
Please, try with 0.0.57, sorting and episodes thumbnails.

**Comment by burekas7** [comment]
OK, so according to version 0.0.58

1) Regarding the sorting by date, now it's working good (by newer/older etc...)

2) Regrading the Fanart & Thumbnail I have noticed that it's working only when the "Use Trakt information in Trakt lists" is disabled.
* When Enable: Thumbnail shows the TV Show poster, and Fanart shows the TV Show fanart.
* When Disable: Thumbnail show the episode fanart, and Fanart shows the episode fanart (As it should be)
-- Is it suppose to work like this? Because as I understand, you said that it should take info from Trakt just in case it doesn't have info from the other place.

* By the way, using TVDB for TV Shows, it's not going to be for now. or maybe there is a little chance in the future?

Thanks

**Comment by elgatito** [comment]
```
When Enable: Thumbnail shows the TV Show poster, and Fanart shows the TV Show fanart.
When Disable: Thumbnail show the episode fanart, and Fanart shows the episode fanart (As it should be)
```

No, should be fine both with Trakt and TMDB lists. The fix will be included in 0.0.59.

**Comment by burekas7** [comment]
@elgatito 
according to 0.0.59:
So I have enabled the option of "Use Trakt information in Trakt lists" ,
But the tv shows fanarts & thumbnails that I get are still from TMDB and not from Trakt.

Does it should be like that or I don't understand it?
Does it should take -all- the info from Trakt no matter what or only when there is no info from TMDB?
(I preferred the first option, by the way)

Because for example, there is an episode that don't have fanart&thumbnail in TMDB but there is in Trakt, In the progress list I see the TV Show poster as thumbnail & fanart.

**Comment by burekas7** [comment]
And by the way, the issue with the [B] tags was because in this specific view mode the skin already wrapping the title with [B], so there was actually duplicate of tags (skin + addon). So currently I removed the [B] from the skin, but it meas that other addons or kodi screens won't show now the title in bold as before.

**Comment by elgatito** [comment]
> But the tv shows fanarts & thumbnails that I get are still from TMDB and not from Trakt.

As I've said before, Trakt is not providing images information.

**Comment by burekas7** [comment]
So if this setting is enabled the meaning is:
All the -text- data except -images- is from Trakt, and the images are from TMDB?

---
I still hope that some day in the future you will add a support for TV Shows getting data from TVDB also.
This will make this addon even better then ever.

Get Images From TVDB:
https://gist.github.com/rectifyer/ce87e4972f24d589d540a16696309dc5

TVDB API:
https://api.thetvdb.com/swagger

**Comment by elgatito** [comment]
```
So if this setting is enabled the meaning is:
All the -text- data except -images- is from Trakt, and the images are from TMDB?
```

Yes.

**Comment by elgatito** [comment]
Is this issue finished, related to Progress changes?

**Comment by burekas7** [comment]
Yes.
Thanks.
