### ISSUE TITLE
Выскакивает окно Trakt

### ISSUE THREAD

**Issue by yatsek20** [elgatito/plugin.video.elementum#208]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

**Comment by yatsek20** [comment]
при вкл Коди выскакивает окно на активацию Trakt  на версии 53 такого не было, все настройки отключены и после перезагрузки приставки оно все равно выскакивает на посл версии. Коди 18 альфа 3 , на версии 53 такого не было в коди 18 альфа 3.

**Comment by elgatito** [comment]
Log?

**Comment by yatsek20** [comment]
куда загрузить?

**Comment by elgatito** [comment]
Уже не надо, нашел.

**Comment by yatsek20** [comment]
если я правильно понял, то в следующем обновлении данная ошибка уйдет?

**Comment by elgatito** [comment]
Да, пробуйте 0.0.55.
