### ISSUE TITLE
[Request] Some sync problems with Trakt Watched status

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#209]
According to a previous issue which got mess 

I still have some sync issues with Trakt regarding the Watched status.

1) Some movies, for example, which have been watched already and are marked as 'watched' in Trakt, they still shown as unwatched in Elementum Movies Collection.

* For example, the movies in the images 'Inside Out', 'Jigsaw'.
(* Just to mention, these movies were marked as watched in Elementum. But after running them again the watched status disappeared)

**My suggestion is to run a new synchronization and update the watch status of all the items.**

![elmoviescol2](https://user-images.githubusercontent.com/13424257/43045895-4fa4fdfe-8db0-11e8-8fd7-b41707309d5d.png)

![movies2](https://user-images.githubusercontent.com/13424257/43045896-58503900-8db0-11e8-8d0e-e60cdb57342a.png)

**Comment by burekas7** [comment]
2) In the TV Shows collection. Some TV Shows marked as watched while the are still unwatched seasons/episodes inside them.

**Comment by elgatito** [comment]
Is this still an issue with the latest version of Elementum?

**Comment by burekas7** [comment]
Yes, still the same issue with 0.66

**Comment by burekas7** [comment]
Also in 0.70

Just to mention, regarding to the movies watched status in the first comment:
In other addons it's ok with the watched status of these two.
I have tried to clear cache etc but it remains the same.

**Comment by elgatito** [comment]
What scrapers you use in Kodi for movies/shows?

**Comment by burekas7** [comment]
For movies: Universal Movie Scraper -> Get data from TMDB
For TV Shows: The TVDB
Kodi libraries are synced with Trakt.

First I need to correct my last comment, with TV Shows Collection the problem seems to be solved and it's OK there, the problem still exist in Movies collection.

I'm attaching a new debug log that includes opening of the Trakt movies collection:
https://paste.ubuntu.com/p/7JHKzJSFc7/

**Comment by burekas7** [comment]
I don't know if it is because the new versoin 0.1.25 or the fact that I press again all of the"Clean and Clear" options in the settings, but it seems the the Trakt is synced correct now and these problematic movis are showing theie correct watched status.

Thanks.
Now it's the time to close this very old issue :)
