### ISSUE TITLE
RPi3 getting temperature warning during buffering, speed close to zero

### ISSUE THREAD

**Issue by makruiten** [elgatito/plugin.video.elementum#21]
## Expected Behavior
Provided there are enough seeders, Elementum should buffer at acceptable speeds and without any temperature warnings.

## Current Behavior
The speed for any movie, no matter how many seeders, is close to zero. Sometimes the initial speed is good, but then it stalls and times out. The Raspberry Pi 3 gets overheated and gives temperature warnings. I tried with default settings as well as with a capped upload and download speed, and with a connection limit. I can't get anything to play. This also happens on another Raspberry Pi 3 with the same Kodi, LibreELEC and Elementum versions.

## Steps to Reproduce
For me this happens any time I want to start a movie or TV series. No special actions needed.

## Context
I was using on older version of Quasar before, which worked fine. I think it was 0.9.48, with magnetic. Quasar and all its related add-ons are disabled.

## Environment
* Version used:
Elementum 0.0.18 ARMv7 (Burst 0.0.7)
* Environment name and version:
Kodi 17.6
* Operating System and version:
LibreELEC 8.2.1
* Link to Kodi debug log:
Full log (too large for pastbin): [kodi.log](https://github.com/elgatito/plugin.video.elementum/files/1574818/kodi.log)

**Comment by elgatito** [comment]
Can you try with the memory storage type?

**Comment by makruiten** [comment]
What do you mean? Like let it download on a flash drive instead of on the sd card?

**Comment by elgatito** [comment]
Open Elementum plugin settings in Kodi. First tab, first setting. Set it to Memory storage, set around 80mb there, and in Bittorrent/Buffer set 20mb.

**Comment by makruiten** [comment]
Thanks, works like a charm. I'll keep it like this. Saves the SD card from a lot of writes too. Is the fat32 setting similar to the default of older versions of Quasar? I remember it specifically mentioning that it needs a fat32 partition for storage. And when should one use mmap?

**Comment by elgatito** [comment]
Fat32 storage is splitting one big file onto many small ones, to keep the size less than 4gb (fat32 limitation). Mmap is a memory mapped file, it's added for testing, but shows not so good performance for me.

**Comment by makruiten** [comment]
Alright, thanks for help! I'm closing the issue.
