### ISSUE TITLE
takes up too much RAM. Not usable on RP2. Latest version around 115MB

### ISSUE THREAD

**Issue by djay** [elgatito/plugin.video.elementum#211]
Seems like latest update has gone from 100MB->115MB. and thats just the coprocess. I'm not sure how much its adding via python in kodi itself. It's possible that 1GB RP2 is not your target but if so its a shame. 
This is without playing anything. And using file system for downloads, even if I did.
Can't get to playing anything as the system gets too slow.

## Expected Behavior

I'm not entirely sure what the expected memory size is for the average plugin. I do expect plugins to be conservative with caching. and I would have thought Golang would do better with memory than this.

## Current Behavior

100MB+ RAM in golang alone.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Just using the plugin causing my system to run out of ram.

## Your Environment

* Version used: 0.0.55

* Environment name and version:

kodi 18 nightly.

* Operating System and version:

osmc

* Link to Kodi debug log:

**Comment by placidities** [comment]
RPi should be using OpenELEC

**Comment by elgatito** [comment]
There were some optimizations in the latest version, to lower memory usage. But do not expect it to not use memory. More functionality = more memory. 
You can use python based plugins, they should use less memory, probably.
