### ISSUE TITLE
Fresh install don't create repository addon.

### ISSUE THREAD

**Issue by Nemiroff** [elgatito/plugin.video.elementum#212]
After change fanart from fanart.jpg to fanart.png your forgote make change in api/repository/repository.go and repository/repository.go in Elementum binaries. 
Error in log:
`NOTICE: [plugin.video.elementum] [31mERRO  main         ▶ Migrate          [0mUnable to create repository add-on: open /storage/.kodi/addons/plugin.video.elementum/fanart.jpg: no such file or directory`

**Comment by elgatito** [comment]
I have changed repository installation and burst check.
Should be better in 0.0.57. Please, check.
