### ISSUE TITLE
Download path when using memory

### ISSUE THREAD

**Issue by john3voltas** [elgatito/plugin.video.elementum#218]
Hello @elgatito .
First of all, let me thank you a lot for sharing your addon with us/me.
I'm running a fresh new install of Elementum 0.0.58 on a Raspberry Pi 3B which has LibreELEC 8.2.5 installed on a 32GB SD Card.
First thing after installing Elementum for the first time is that I get a "nag window" telling me to setup the download path. Okay, makes sense as most the new users will come here opening tickets because Elementum is not working for them when in fact it's just a small mistake on their part forgetting to setup a download folder.

But this setting isn't needed if I am going to use "memory" as my "download storage type", right?
Well, at least to me it doesn't make sense that I'd be using the "memory" for storage and yet Elementum would still nag me to setup a download folder.
But the truth is I just ran into that issue! Elementum would simply not even start before I setup a download folder and yet I had set it up for "memory".

Can you please clarify what the expected behaviour would be for someone wanting to use Elementum with a "Download storage type" set to "Use memory"?
Should we expect Elementum to still ask for a download folder or should Elementum simply skip that nag window when setup to use "memory" as a storage type?

Thanks in advance and keep up the good work.

Cheers

**Comment by elgatito** [comment]
Download folder is used not only for actually downloading files.
Elementum creates Torrents directory in it and stores active torrent files, so you can set that folder to anything, there is no disk usage or downloading.

Maybe in future we will remove that to store in a temporary directory.

**Comment by john3voltas** [comment]
Interesting, quite interesting.
So that folder is where Elementum stores the .torrent files...had never thought of that possibility and hadn't considered that Elementum needed to properly store non-volatile information that couldn't be kept in volatile RAM.
Now, I wonder why I couldn't set that as a subfolder of my home directory of my Pi's SD Card. That would mean that Elementum tried to write to the folder and didn't make it, right?
But it was a home directory subfolder....
I'll try again and check Kodi's log. If I still can't figure that out, could you take a look at the log, please?
Thanks.

**Comment by Harvie** [comment]
When i use "memory" (the default) on raspberry pi. Does this mean my sd card will not get bloated by downloaded videos? i don't want to write too much data (eg. movies) to the sd card, because it will get damaged by so many writes. is this ok? (i don't mind storing .torrent files or some metadata)

**Comment by antonsoroko** [comment]
@Harvie , as stated above - with memory storage elementum will keep in "download path" only internal info (like .torrent files and etc) but not video files. (so the answer is "yes".)
you always can check this by looking into that directory and checking FS space usage.

**Comment by Harvie** [comment]
> @Harvie , as stated above - with memory storage elementum will keep in "download path" only internal info (like .torrent files and etc) but not video files. (so the answer is "yes".)
> you always can check this by looking into that directory and checking FS space usage.

I left the path empty as it came after installation, so i guess some kind of default is used, but i don't know where that is 😀

**Comment by antonsoroko** [comment]
there should be a "button" in settings to open this path. right after `download_path` setting.
