### ISSUE TITLE
[Question] is it possible to run the daemon as a standalone package? 

### ISSUE THREAD

**Issue by Abdulla060** [elgatito/plugin.video.elementum#219]
Hi, i'm using Elementum with Aura skin for kodi. and i was using lists from Elementum as widgets. the problem is since the skin starts before the daemon it fail's to load the list and i have to manually reload the skin in order to fetch the list.so i was thinking of starting the daemon before at boot so i won't run into this problem.is it possible? i know that the daemon need to get the setting from kodi before starting. so i can't just simply run it. also i know that the daemon should only handle the download so why won't Elementum addon load the lists without it?

OS:Xubuntu 18.04
Kodi:17.6
CPU:Intel core i7-4790k
GPU:nvidia gtx 980
RAM:16 gb 

thanks in advance and sorry for my bad English

edit1:added system info

**Comment by elgatito** [comment]
Elementum needs Kodi to be already started, so no, you can't start Elementum before Kodi.
