### ISSUE TITLE
Addon repository not working

### ISSUE THREAD

**Issue by hoshsadiq** [elgatito/plugin.video.elementum#22]
Hi, currently trying to get burst installed through the repository (had to manually push the actual addon), but without any luck. It then tells me to install it through the repository, but when I press the Element Repository, it says "Could not connect to repository". Any ideas what I can do? I'm happy to send the logs but I need to know where to find them.

**Comment by elgatito** [comment]
Please post the full kodi.log
http://kodi.wiki/view/Log_file/Easy

**Comment by hoshsadiq** [comment]
Thanks, here it is: https://pastebin.com/4XW06uJN

**Comment by tomtomclub** [comment]
try reboot 2 or 3 times works four mi

**Comment by elgatito** [comment]
Don't see any messages from the plugin.
Try opening this url on you Kodi device - http://elementum.surge.sh/packages/elgatito/plugin.video.elementum/addon.xml , maybe it's blocked or something like that.
This link should work after all - http://127.0.0.1:65220/repository/elgatito/plugin.video.elementum/addons.xml.md5

**Comment by hoshsadiq** [comment]
Okay, that path url is definitely working. Nothing is blocked on my network as far as I'm aware, so all should work. I will see if I can clear the whole thing and reinstall it

**Comment by hoshsadiq** [comment]
This works fine now. Issue #23 is likely solved too, but I'm testing it now. Will close it if it's okay.
