### ISSUE TITLE
elementum player wont start

### ISSUE THREAD

**Issue by skemayam** [elgatito/plugin.video.elementum#220]
after laumching elementum it says encounter error and please check the log.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: 0.0.58

* Environment name and version:

* Operating System and version: win10

* Link to Kodi debug log:

http://paste.kodi.tv/mexiqoyewa

**Comment by elgatito** [comment]
Have you enabled remote control in Kodi?
Have you set initial Elementum settings? (go to plugin settings and press OK).

**Comment by elgatito** [comment]
Please, try with 0.0.62.
If there is no response - i will close the issue. Thanks
