### ISSUE TITLE
custom_provider_timeout

### ISSUE THREAD

**Issue by pavelmxx** [elgatito/plugin.video.elementum#221]
Рассмотрите, пожалуйста, возможность расширения диапазона значений настроек для элементум
`<setting id="custom_provider_timeout" value="60" />
`и для барст `<setting id="timeout" value="20" />
`
У меня пара разных неттопов не успевает найти по множеству трекеров. Достигает предельных значений таймаута и пишет "трекер работает медленно". Приходится после обновлений или захода в настройки, если сбрасывает, заново руками выставлять в файле настроек xml элементума "180" и для барста "120". Плюс, goodbyedpi, с которым я все это дело использую, местами очень сильно тормозит отклик веб-страниц, особенно при опросе более 20 трекеров. Текущего максимума в виде 60 и 20 секунд явно недостаточно.

**Comment by elgatito** [comment]
Timeouts changed to 180 seconds in 0.0.59.
