### ISSUE TITLE
Resume from Kodi library

### ISSUE THREAD

**Issue by jorgecardoso220** [elgatito/plugin.video.elementum#223]
Hello

Every time I try to resume a movie or a show from Kodi library, it start from the beginning and not from the place I stop watching earlier.
Is this normal or you can fix it?

Thanks

**Comment by elgatito** [comment]
No log = no help.

**Comment by jorgecardoso220** [comment]
I think that's it

[Log.txt](https://github.com/elgatito/plugin.video.elementum/files/2267894/Log.txt)

**Comment by elgatito** [comment]
I don't see anything special. 
You can try a test case:
1) scrape movie/show with TMDB (not TVDB).
2) start a playback, seek to somewhere, stop.
3) start a playback again.

Then post a log file, so I can see what is there.

**Comment by elgatito** [comment]
Any information?

**Comment by elgatito** [comment]
Resume is done and requested by Kodi. 
If item (show/movie) is added to Kodi - we will try to find it and force resume function. 
If not added to Kodi - it's all about Kodi.

**Comment by qzem** [comment]
I have the same problem. I am using elementum with download in memory, and Kodi doesn't even offer me to resume elementum movies. I've added movie to the library, and there si indicator that movie was partially watched, but when trying to play movie there is no resume option. Local movies or shows resume with no problem. Is there anything I need to setup in Elementum addon settings to make this work?

**Comment by elgatito** [comment]
@qzem it will be, probably, fixed in 0.1.* branch, which is in development currently.

**Comment by qzem** [comment]
> @qzem it will be, probably, fixed in 0.1.* branch, which is in development currently.

Thank you for a quick response. BTW, great work so far!
