### ISSUE TITLE
Remove IP from list of blocked IPs

### ISSUE THREAD

**Issue by valentiniljaz** [elgatito/plugin.video.elementum#224]
I have written a provider which access an IP which is listed in resources/misc/pack-iplist and because of that the provider is not working properly.

Can you please tell what kind of tools do you use to change that list. I would like to remove the IP from that list so that my provider will work, but leave all other IPs intact.

Or do you suggest some other way for me to go about this?

**Comment by elgatito** [comment]
File is provided by torrent library https://github.com/anacrolix/torrent
