### ISSUE TITLE
For .torrents with multiple episodes, it'll view only the first one without showing options.  It works fine in Quasar

### ISSUE THREAD

**Issue by lopezvg** [elgatito/plugin.video.elementum#225]
Environment: Windows 10, Kody 17.6, Elementum 0.0.59, called from add-on Alfa 2.6.1

The problem described in the title happens also in Android 7.1.2.

I am a Quasar user, but testing to migrate to Elementum.  Very often series seasons are packed in one .torrent file.  Quasar shows a window with the list of episodes available in the .torrent file, so the user can select the desired episode.  If the Cancel button is clicked, Quasar download all episodes to disk, in a folder.

Log: https://paste.kodi.tv/obebehozut

**Comment by elgatito** [comment]
It works as expected. 
If you play episode and select torrent with many episodes - plugin tries to select proper episode file, without showing options.

**Comment by lopezvg** [comment]
And what do I have to do in order that Elementum show me a option window to select a the right file?

**Comment by elgatito** [comment]
When you select an episode of a show - elementum is trying to find that episode in torrent's files. If it can't find it - it will show you option to select the file.
If you manually add some torrent to elementum it will also ask you to select which file to download.
Elementum is not downloading all files, only one file.
