### ISSUE TITLE
No repository installed

### ISSUE THREAD

**Issue by ilanerukh** [elgatito/plugin.video.elementum#228]
While installing the addon the Elementum repository is not installed, so I do not get automatic updates. Is it possible to install the repo with the zip, or to provide a link to installation?

Thank you.

**Comment by elgatito** [comment]
Repository is installed automatically after plugin.video.elementum is installed. 
If you have problems - provide kodi.log to see the problem.

**Comment by ilanerukh** [comment]
Installed latest version manually and got the repo.
Thank you.

**Comment by m4xc4v413r4** [comment]
Funny enough I just noticed that on my windows store version it doesn't install the repository when installing elementum :/
Is that a known problem?

**Comment by elgatito** [comment]
There are no known problems with repositories.
