### ISSUE TITLE
[Request] Pick torrent from client 

### ISSUE THREAD

**Issue by stuCONNERS1983** [elgatito/plugin.video.elementum#234]
I've got two installs on libreelec and have my client connect to my server but how do I pick the torrent on a client. The server gives me a list of torrents to pick from? It works but not the greatest having to go to another room to pick which torrent to stream

**Comment by elgatito** [comment]
I don't understand what you want.

**Comment by stuCONNERS1983** [comment]
I have two I stalls on elementum on a raspberry pi and linux x64. When using the remote host option on elementum I have to pick the torrent on the remote host and not the client. Is there anyway to pick the torrent on the client when using the remote host option?

**Comment by elgatito** [comment]
There is no "client" torrents. Everything you do when you setup "remote host" is done remotely.

**Comment by stuCONNERS1983** [comment]
So there is no way to pick a torrent on the raspberry pi if I have it connect to the linux x64 via remote host? If I select an episode whilst using the raspberry pi, I have to go to the linux x64 install to pick the torrent. How do I get to pick the torrent on the raspberry pi instead?

**Comment by elgatito** [comment]
You should try before you write.
Kodi is controlling the binary (application), does not matter is kodi on the same same host or not.

If you select something on the client - you ask to do it on the remote host. That is it.
