### ISSUE TITLE
[Request] Add "In Library" folder to see items, added to library by Elementum

### ISSUE THREAD

**Issue by johndoe71rus** [elgatito/plugin.video.elementum#235]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Уменьшить/сделать отключаемые некоторые категории. На данный момент в используемой теме удобно сделать 11 строк на странице без прокрутки. Количество категорий на данный момент превышает это значение.
Понимаю что большинство из них завязаны на Тракт. Но для непользователей тракта остаются загадкой различия между некоторыми категориями.
- В топе
- Самые популярные
- Самые просматриваемые
- Самые популярные (дубль?)

- С лучшим рейтингом
- Самые оцениваемые

Дополнительное предложение сделать категорию "в библиотеке". Для удаления из библиотеки надо найти фильм или сериал в списках элементума и там в контекстном меню выбрать "удалить из библиотеки". Иначе из самой библиотеки элемент удаляется но потом появляется снова. Хорошо если фильм/сериал на первых страницах списков, а если нет листать долго-долго пока не найдешь. 
Из поиска мне кажется нет возможности оперировать с найденным добавить/удалить из библиотеки.

## Your Environment

* Version used:

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

**Comment by elgatito** [comment]
Часть 1: 
Точно не буду делать.

Часть 2:
Смысл есть, но у нас нету сейчас знаний что в библиотеке сделано дополнением, а что нет. 
Плюс, нет возможности сортировать по алфавиту с постраничным выводом, или по алфавиту но всё сразу (и при большой библиотеке можно ждать очень долго), или по страницам и без сортировки (что лишает всего смысла).

**Comment by johndoe71rus** [comment]
по второму пункту. Когда просматриваешь списки, в контекстном меню есть пункты
Добавить в библиотеку / Удалить из библиотеки
Обновить в библиотеке

Значит как то фиксируется.

**Comment by elgatito** [comment]
> Значит как то фиксируется.

Фиксируется что есть в Коди вообще в библиотеке, а не конкретно созданное через дополнение.

**Comment by johndoe71rus** [comment]
формат библиотеки един для всех плагинов?
что будет если попробовать удалить контент добавленный другим плагином?
Этого было бы достаточно. Потому как если удалять из библиотеки, оно потом восстанавливается.

**Comment by elgatito** [comment]
> формат библиотеки един для всех плагинов?
> что будет если попробовать удалить контент добавленный другим плагином?

Не так. Никто не знает кто добавил что-то в библиотеку. Со стороны Коди нет разницы это strm файл или реальный файл. Удалять файлы с диска никто не будет.

**Comment by elgatito** [comment]
"In Kodi library" directories added to 0.1.23.
