### ISSUE TITLE
Low download speed

### ISSUE THREAD

**Issue by joaopauloss** [elgatito/plugin.video.elementum#238]
## Current Behavior
Like issue title says I'm getting low download speeds. My internet has 50mbps and when downloading any video it gets at maximum 600KB/s. When I first installed elementum it was in version 0.0.53, and worked just fine. After a few updates it cames to the current situation.

I'm using "memory" download storage type, with automatically size choose. Tried may other configurations, like minimum and default memory usage, manual memory size, etc.

Everything else is setted to default elementum settings.

Get the same troubles running on my smartphone.

* Version used:
Elementum v0.0.60
* Environment name and version:
Kodi version 17.6 Krypton
* Operating System and version:
Android 5.1 TV BOX 1Gb RAM 4Gb flash
Smartphone Android 7.1.1 4Gb RAM 64Gb flash
* Link to Kodi debug log:
https://paste.kodi.tv/usavuguruc

**Comment by elgatito** [comment]
DON'T CAPS!!!

You should provide log, where you try to download something.

**Comment by joaopauloss** [comment]
The logo I sent the link must have a download part. I did the tests before upload that. Cound't find the download line exactly.

**Comment by elgatito** [comment]
Your log only shows moment when Elementum has been loaded. No downloads there.

**Comment by joaopauloss** [comment]
Sorry, must had some error on log. This is a new one: https://paste.kodi.tv/hosumajiti

**Comment by Lesproges** [comment]
Same here
https://paste.kodi.tv/velaqikesi.makefile

**Comment by Lesproges** [comment]
Download stay at 350kb/s

**Comment by Lesproges** [comment]
Ok, for me, it seems that the vpn is the problem. Without vpn connection, download speed jump to 3 or 4 the speed with the vpn connceted. But it's strange because, I always use this connection before without having speed issue.

**Comment by joaopauloss** [comment]
I don't use any vpn,  and still doesn't work. =/

**Comment by Lesproges** [comment]
Today another try without vpn, but download speed limit to 1.1 mb/s with a torrent with 1440 seeders.
There's a problem ! Video is freezing and sound cuts every 5 sec. impossible to watch.

**Comment by joaopauloss** [comment]
I think there is some problem with the seeds during download.  Tried with different torrents, they show more than 300 seeders,  but when i'm watching it stucks on some number, like 50/289. Sometimes, even showing that a file has 500 seeds during torrent search,  when I play that come to 20/20 or 30/40, it always change.

**Comment by joaopauloss** [comment]
I'm not using a sd card. Just the ram memory storage type

**Comment by elgatito** [comment]
Elementum is not doing any download/upload. It's all made by a torrent library - https://github.com/anacrolix/torrent . 
If you feel it works wrong - you can raise an issue there and ask for any kind of support.

**Comment by ashoktvm** [comment]
Download speed is really low. Its not the problem my connection. SInce quasar is getting full download speed. Definitely a Elementum problem

**Comment by MichaelAndoid** [comment]
Hi after many months using Quasar because having this problem to in 2 android boxs, know with the new migration to libtorrent in V0.1.20 i can use elementum without ptoblems.
And works ok with the default settings, max speed connection.

Thanks for this migration ;)
