### ISSUE TITLE
Issue during opening (kodi 17.6 android ARM 32bit, box android 5.1.1)

### ISSUE THREAD

**Issue by Gregsr** [elgatito/plugin.video.elementum#24]
Hi,
Elementum does not open. It is the first time I install your add-on on my android 5.1.1 box, kodi 17.6 android ARM 32bit.
Here is my log file:
[kodi.log](https://github.com/elgatito/plugin.video.elementum/files/1584695/kodi.log)

Thank you for your help.

**Comment by elgatito** [comment]
Please, try to install the latest version, from the biggest zip file. There was a change related to this.

**Comment by Gregsr** [comment]
It works fine.
Thanks

**Comment by elgatito** [comment]
Glad to hear.
