### ISSUE TITLE
Help trakt

### ISSUE THREAD

**Issue by b0g0m0l** [elgatito/plugin.video.elementum#241]
Привет, можете помочь с синхронизацией тракта, после последнего обновления и синхронизации удалило все мои сериалы из коллекции тракта и добавились какие-то левые. Раньше все работало хорошо теперь не понятно нужен ли ставить отдельно плагин тракта или теперь все в элементуме есть?

**Comment by elgatito** [comment]
Для Elementum отдельного дополнения никогда не нужно было для Trakt.
Удаление из коллекции Тракта происходит только когда выбрать "Удалить из библиотеки" на конкретном сериале или когда Коди присылает что что-то удалено.

**Comment by b0g0m0l** [comment]
Как тогда сделать чтобы сериалы которые остались у меня в библиотеке коди, синхронизировались с трактом и снова появились на сайте? В элементуме есть ведь такая опция, только после нажатия на обновить тракт ничего не добавляется на сайт. Добавляются левые сериалы Shinzo, My Life as a Popat, Tattletales

**Comment by elgatito** [comment]
Скраппер какой в библиотеку Коди?

**Comment by b0g0m0l** [comment]
Для сериалов TVDB. Еще не синхронизируется с трактом просмотренные серии, добавил сериал Касл-рок в коди поставил на сериях просмотрено, и синхронизировал с трактом на сайте ничего не изменилось. Также сделал на сайте тракта добавил сериал в коллекцию, поставил просмотренные серии, в библиотеке коди ничего не поменялось.

**Comment by b0g0m0l** [comment]
Менял скрапер на The Movie Database на сериалах не помогло, не синхронизируются просмотренные сериалы. С фильмами проблем нет.

**Comment by OakSorcerer** [comment]
Для сериалов синхронизация отвалилась, в топике выше кстати описана еще одна проблема. При отметке серий или сезонов из интерфейса коди на сайте тракта появляются тысячи серий из разных сериалов отмеченые одной датой и временем.  По моим наблюдениям произошло это к концу лета, ибо раньше для сериалов статус просмотренного нормально синхронизировался.

**Comment by Exz777** [comment]
Можна ли синхронизировать тракт на на скольких устройствах вместе с данными о просмотре?!

**Comment by elgatito** [comment]
@Exz777 если Тракт авторизован в Elementum, то будет синхронизировать туда и обратно просмотренное.

**Comment by Exz777** [comment]
на устройствах удается синхронизировать только фильми, а сериали полностью не синхронизируются,.Не удаеться переносить сам прогресса просмотра на устройства, или так и должно быть?!

**Comment by elgatito** [comment]
Там ошибка в последних версиях. Я сейчас это исправил. В следующей обновятся и сериалы, при этом дата будет правильная синхронизироваться (дата просмотра, а не синхронизации).

**Comment by Exz777** [comment]
Спасибо

**Comment by Exz777** [comment]
количество просмотренных серий, мы об одном и том же говорим? верно?

**Comment by elgatito** [comment]
Да, не синхронизировались серии и сезоны.

Пробуйте 0.0.62.

**Comment by b0g0m0l** [comment]
Можете посмотреть лог, на компьютере все хорошо синхронизировалось, а вот на Coreelec не все сериалы.
https://paste.ubuntu.com/p/Hzb78w7Mxf/

**Comment by elgatito** [comment]
С виду нормально всё, штук 20 серий проставилось как просмотренные.

**Comment by b0g0m0l** [comment]
А как с остальными быть?

**Comment by elgatito** [comment]
С чем остальным? Если дополнение не может связать что-то из Тракта с тем что в библиотеке в Коди то оно его не обновляет. Почему не может сопоставить причин много. Начиная он скраппера, отличного от TMDB, до непроставленных TMDBID на стороне Trakt.

**Comment by Exz777** [comment]
теперь все пляшет как надо. Спасибо большое

**Comment by b0g0m0l** [comment]
Переустановил Kodi теперь даже скрапер (tvdb) не добавляет описание к сериалам в логе пишет 
ERROR: VideoInfoScanner: Asked to lookup episode C:\Users\Ivan\AppData\Roaming\Kodi\cache\elementum_library\Shows\American Horror Story (2011)\American Horror Story (2011) S01E01.strm online, but we have no episode guide. Check your tvshow.nfo and make sure the <episodeguide> tag is in place.
вот полный лог 
https://paste.ubuntu.com/p/229ZSFCjM5/
Хотя если создать новую папку с сериалами без синхронизации тракта в элементум то скрапер работает. В чем проблема никак не пойму. но грешу на Элементум. Можете помочь.

**Comment by elgatito** [comment]
Добавил опцию отключить создание NFO файлов для фильмов/сериалов. Можете отключить для сериалов и удалить nfo файлы. Если через Trakt добавлены то можно просто удалить сериалы, они создадутся заново.

**Comment by b0g0m0l** [comment]
После обновления удалил все сериалы из библиотеки. Отключил nfo файлы для сериалов. И синхронизировал снова. Добавилось только 2 сериала и из тех что добавились в сериале Титаны проставились все серии как просмотренные. Хотя на сайте тракта отмечены как просмотренные только 2. 
Log https://paste.ubuntu.com/p/hgrS36v6Bv/

**Comment by elgatito** [comment]
Пробуйте версию 0.0.64. Включайте NFO файлы, обновите библиотеку и заставьте tvdb пересканировать все сериалы. 
Поменял под новый формат ссылки, должно просканировать и правильные id сохранить в базе.

**Comment by elgatito** [comment]
Неправильно проставляются сериалы, потому что Коди заменяет старые записи новыми. 
В следующей версии поправлю. 

Если всё через Тракт синхронизируется то лучше удалить и дать пересоздать библиотеку сериалов.
