### ISSUE TITLE
Feature Request - Delayed Start

### ISSUE THREAD

**Issue by riegaz** [elgatito/plugin.video.elementum#244]
I just installed Elementum and it is great. However, I mostly use TVHeadend and when I turn on Elementum on my S905 box, the start of the TVH client gets delayed by about 20s.

I wonder if you could add an option to delay the start of Elementum by a variable amount of seconds. Some other addons offer this as well and I think it makes absolutely sense.

Keep up your great work.

**Comment by elgatito** [comment]
Elementum is not blocking anything, when starting. I don't know why your specific system has such issues.

When to start addon is decided by Kodi.
