### ISSUE TITLE
[Android] Elementum no longer starts on Android Kodi

### ISSUE THREAD

**Issue by hitmancho** [elgatito/plugin.video.elementum#246]
Yesterday Elementum stopped working on my Android tablet. I hadn't updated it at all and it was working fine the day before that. The moment I opened Kodi on my device I got an error that android_arm was missing and that I should reinstall the package using the largest one. On the update screen Elementum was shown as being windows_x86, which is obviously wrong and I hadn't touched anything at all. Any attempt at upgrading to android_arm or uninstalling Elementum and reinstalling either the Android OR universal package met with the same error. It's like the Android package "died" overnight. I even tried updating Kodi to the newest beta and still the same result.

My setup is an ASUS TF701T tablet running on Android 6.0 (KatKiss ROM) with Kodi 17.6 Krypton. I had zero issues before yesterday when this suddenly happened. I updated to Kodi 18 Leia Beta 1 and the issue is exactly the same. I even uninstalled the package with the option to delete its settings but Elementum still persists that it can't find the android_arm package. The device SoC is Tegra 4 so it's an ARM 32-bit.

**Comment by Sandbird** [comment]
Same thing happened to my Windows setup and the Pi3 setup...

**Comment by victorabogado** [comment]
Same here but the problem seems to be Gaia Addon with Elementum combined.

Please help

Victor

**Comment by elgatito** [comment]
So many logs provided to find the reason.

http://elementum.surge.sh/contribute/log/

**Comment by elgatito** [comment]
Please, try with 0.0.62.
And give proper log file if still have an issue.

**Comment by elgatito** [comment]
Please, try with 0.0.63.

Any news?

**Comment by elgatito** [comment]
Closing without no response.
