### ISSUE TITLE
Could not find binary. Elementum cant start.

### ISSUE THREAD

**Issue by Jezze83** [elgatito/plugin.video.elementum#247]
I faced this problem. I already uninstalled addon and manually deleted elementum folder but still not working. I used latest universal version from elementum website. Here is picture and logfile: 
https://pastebin.com/ytbPGQAH

![c0cc545f-b700-478b-b6b3-9cdc777c04c0](https://user-images.githubusercontent.com/10639795/45222675-d2343500-b2bd-11e8-970a-057faed79a53.jpeg)

**Comment by bertin0** [comment]
Same problem, trying to use elementum+gaia, disabled the elementum repo and auto update and installed from the zip.

**Comment by bertin0** [comment]
Well I'd like to use Gaia and elementum. Guess I'll have to choose

**Comment by elgatito** [comment]
@Jezze83 do you have problems with starting Elementum with the latest version?

**Comment by Jezze83** [comment]
Works fine.
