### ISSUE TITLE
Go back elementum

### ISSUE THREAD

**Issue by Dustman71** [elgatito/plugin.video.elementum#248]
Hello, first of all congratulate you on the plugin, it looks very good.
Unfortunately, after having it installed several days, I have never achieved a good download speed and the video stops, either with the memory option selected or the file.
For this reason I have decided to go back quasar again, although I will carefully monitor the progress of Elementum.

My problem is that when installing elementum in the options I chose to migrate from quasar to elementum. Previously I had chosen that the library folder was the same as quasar and after deactivating elementum I can not execute movies added to the library.

Something is broken ...
Do you have any idea how I can make my old library work again with quasar?

regards

**Comment by mriscoc** [comment]
I have the same problem when the number of seeders is high. The download speed is low. Using a Raspberry Pi.

**Comment by robclouth** [comment]
Yep, exact same here. Latest version. Shield TV.

**Comment by elgatito** [comment]
> Something is broken ...
Nothing is broken. When you choose to migrate - Elementum is deleting moving library items from Quasar to Elementum to avoid further duplicates.
You should re-add items to Quasar library. There is no other way to revert.

**Comment by elgatito** [comment]
Quasar migration was removed from settings. Because it creates more questions and does not allow moving back to Quasar.
Perfect solution would be to use separate directory for Elementum and sync your library with Trakt.
