### ISSUE TITLE
art/posters download issue

### ISSUE THREAD

**Issue by froggz19** [elgatito/plugin.video.elementum#249]
For some reason it fails to download the art/posters when navigating through Elementum

> 19:20:07.520 T:6740   ERROR: NEWADDON Unknown Video Info Key "dbtype"
> 19:20:10.035 T:16600   ERROR: Previous line repeats 8 times.
> 19:20:10.035 T:16600   ERROR: CCurlFile::Stat - Failed: Peer certificate cannot be authenticated with given CA certificates(60) for https://assets.fanart.tv/fanart/movies/426814/movieposter/the-domestics-5b37a1f94d559.jpg
> 19:20:10.293 T:16600   ERROR: CCurlFile::FillBuffer - Failed: Peer certificate cannot be authenticated with given CA certificates(60)
> 19:20:10.293 T:16600   ERROR: CCurlFile::Open failed with code 0 for https://assets.fanart.tv/fanart/movies/426814/movieposter/the-domestics-5b37a1f94d559.jpg:
> 19:20:11.138 T:13580   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for https://assets.fanart.tv/fanart/movies/466282/moviebackground/to-all-the-boys-ive-loved-before-5b77ce818a134.jpg

Using **Kodi Leia Beta 1** and **Elementum 0.0.61** on **Windows 10 v1803 64bit**

**Comment by froggz19** [comment]
Forgot to mention I'm using the 64bit version of kodi

**Comment by elgatito** [comment]
Posters are downloaded by Kodi, not related to this plugin.

**Comment by elgatito** [comment]
Please, try search option on 0.0.62.
