### ISSUE TITLE
Kodi crashes when playing Elementum torrent

### ISSUE THREAD

**Issue by Mark-64** [elgatito/plugin.video.elementum#251]
Running LibreElec 8.90.004 (Kodi 18) on Raspberry Pi3.
Torrent search work, but Kodi crashes whenever I try to play any torrent found.
Elementum was working fine on LibreElec 8 with kodi 17

[Kodi log](https://pastebin.com/DNSpF2km)

Any clue ?
Thanks in advance.

**Comment by deleder** [comment]
I got the same issue. Tried Quasar and Elementum. I've tried several trackers. Just crashed when I click on play like you.

**Comment by GavinDarkglider** [comment]
I have the same issue with both Quasar and Elementum with kodi 18.

**Comment by elgatito** [comment]
Please, try with 0.0.62

**Comment by Mark-64** [comment]
It seems to work with 0.0.62 and LibreElec 8.90.007 (Kodi 18) on Raspberry Pi3.
will do more tests tomorrow.
Thanks !

**Comment by dankec2000** [comment]
Not working since 0.0.62 with kodi 17. Worked great with previous version.

**Comment by elgatito** [comment]
I have finished much better solution, it should be available with next version. 
Anyway, thanks for testing.

**Comment by elgatito** [comment]
Please, try with 0.0.63.

**Comment by dankec2000** [comment]
0.0.63 - the same as 0.0.62. Crashing.

**Comment by elgatito** [comment]
@dankec2000, no details = no help.
