### ISSUE TITLE
Cannot display Trakt Lists - Internal Server Error

### ISSUE THREAD

**Issue by navehgrofi** [elgatito/plugin.video.elementum#253]
## Expected Behaviour
Trakt Lists should be visible of course after Authorization 

## Current Behaviour
After successfull Trait Authorization, when i try to enter my show lists I'm getting an error:
Elementum: Internal Server Error 

## Your Environment
Nvidia Shield Running SPMC 17
Elementum version 0.61
* Environment name and version:
* Operating System and version:
Android 8

Log:

https://paste.ubuntu.com/p/xGbqXcM4WW/

**Comment by elgatito** [comment]
Will be fixed in the next version.

**Comment by elgatito** [comment]
Please, try with 0.0.62
