### ISSUE TITLE
Error HTTPError: HTTP Error 401: Unauthorized

### ISSUE THREAD

**Issue by Gianlucas94** [elgatito/plugin.video.elementum#254]
## Expected Behavior
When i try to open Elementum/Quasar or try to configure my trakt account i get a error "unauthorized"

## Your Environment

* Version used: 18.0 Leia, Kodi v17.6

* Environment name and version: 18.0 Leia

* Operating System and version:Windows 10 1809

* Link to Kodi debug log: https://paste.ubuntu.com/p/XSVG9nthWq/

**Comment by elgatito** [comment]
You have some kind of a tunnels? 
Log is non informative.
http://elementum.surge.sh/contribute/log/

**Comment by elgatito** [comment]
Any updates? Can  I close the issue?

**Comment by elgatito** [comment]
Closing without response.
