### ISSUE TITLE
[Request] Add auto-download for subtitles

### ISSUE THREAD

**Issue by dankec2000** [elgatito/plugin.video.elementum#255]
Is there any chance to add functionality of auto-download first adequate subtitle in desired language (from priority list) before start playing stream?

In other words, the same as f.i. Placenta or Exodus are working with subtitles.

**Comment by antonsoroko** [comment]
It would be nice to have something like https://kodi.wiki/view/Add-on:AutoSubs but with "auto-download".
Other option is to ask developers of AutoSubs to implement such feature.

**Comment by elgatito** [comment]
Please try with 0.1.25.

Option added.

**Comment by antonsoroko** [comment]
Usually it works.
But sometimes - it doesn't.
In this log i tried 2 times - no luck
(Might be related to internet speed, e.g. timeouts)
https://paste.ubuntu.com/p/K7tDtqXTbs/

**Comment by elgatito** [comment]
@antonsoroko 
I see it could not find show name, will take a look.

**Comment by antonsoroko** [comment]
Strange, because manual search is working for this episode.

**Comment by elgatito** [comment]
@antonsoroko 0.1.26 has another fix for missing subtitles in automatic mode.

**Comment by antonsoroko** [comment]
Tried 2 times
1) success , no background download
2) fail, there was background download in progress. I stopped downloading - still no luck. Once again - success. Something strang us happening. https://paste.ubuntu.com/p/xfKQtgZTt8/

**Comment by elgatito** [comment]
Please, try version 0.1.28.
In your case you first had normal subtitles search, next time if looks like a local file playback. Probably 100% downloaded?

**Comment by antonsoroko** [comment]
No luck, different torrent

spmc.log: https://paste.ubuntu.com/p/SyTSqgcNpN/
spmc.old.log: https://paste.ubuntu.com/p/PQR4z6bJRr/

**Comment by elgatito** [comment]
Looks like shitty skin that breaks videoplayer labels.

**Comment by elgatito** [comment]
Try one more time with 0.1.29.

**Comment by antonsoroko** [comment]
Looks like it work now. Thank you very much!
