### ISSUE TITLE
Slow buffer filling although high download speed

### ISSUE THREAD

**Issue by gusmin1975** [elgatito/plugin.video.elementum#258]
Thank you for your effort at start.

The issue that i have with elementum 61 and Burst 29 is that when i select a source and starting to download with very good speed the buffer is filling very slow.

The same source in Quasar fills the buffer very quickly - no more than 30 seconds.

I thought it was a source problem because Burst 29 did not show Magnetdl sources, thus i downgrade to Burst 19 where i finally found Magnetdl sources but the slow buffer filling did not changed.

Do you have any solution? I use memory for storing and all the other setttings to default.

**Comment by mymo1982** [comment]
I share the very same problem as yours: the initial buffer is set at 20 MB, but it takes a long time for the bar to fill up and eventually a time out error is displayed before the video even starts. The download speed is around 1400 KB so it should take less the 20 seconds for the video to start. The issue comes up both when the file is downloaded to memory and to internal disk.

**Comment by gusmin1975** [comment]
I want to roll back to older version but I do not know where to find it.

**Comment by konvar** [comment]
@gusmin1975 

https://github.com/elgatito/plugin.video.elementum/releases

**Comment by gusmin1975** [comment]
I tried a couple old releases. 58 59 60 present the same bahavior. Then I moved to 54 and now is working as it should. So hopefully someone who can understand technically maybe can suggest a change in the next version. For now I find previous releases better for both elementum and burst.

**Comment by mymo1982** [comment]
@gusmin1975

Thank you for sharing your experience, I also installe version 0.54 and now it's working!

My only issue now is that a pane pops up asking to synch and activate Elementum to Trakt, which I'm not subscribed to

**Comment by elgatito** [comment]
No log = no help.
http://elementum.surge.sh/contribute/log/

**Comment by mymo1982** [comment]
There you go :)

https://paste.ubuntu.com/p/CjjXphzSwp/

**Comment by elgatito** [comment]
@mymo1982  your advancedsettings.xml file sets buffer to 500mb, so to start playback elementum is trying to download 500mb. If you'd download only 20mb, like you set in Elementum settings - it would not start playback and wait for that 500mb.
You have to wait for 500mb download or remove that setting from advancedsetting. It makes no sense.
