### ISSUE TITLE
Not working on Ubuntu 18.04 Kodi 17

### ISSUE THREAD

**Issue by afduggirala** [elgatito/plugin.video.elementum#259]
I installed the addon as per instructions (and Burst as well) but:
1. Loading of content info is slow when browsing (movies, tv shows)
2. Selecting an item initially had no effect, and then
3. Burst got stuck in looking up in providers.
4. After a few attempts, some results showed.
5. After buffering the content was not played.

Can someone confirm this addon is working on a setup similar to mine?
thanks,

**Comment by elgatito** [comment]
http://elementum.surge.sh/contribute/log/

**Comment by elgatito** [comment]
No response.
