### ISSUE TITLE
Can't write on NTFS / exFat usb

### ISSUE THREAD

**Issue by mbLc** [elgatito/plugin.video.elementum#262]
Hi,

I recently purchase a Philips 55PUS7503 with Android 7 on it and I tried to format my usb drive and my external hard drive to NTFS. Every time I want to select my drive it says that I can't write on this directory. I tried to create the /Android/data/org.xbmc.kodi/files directory manually but it's still the same.
If I use exFAT, I can't even see my usb drive. If I put FAT it's working fine but the download speed is very slow. I also tried to format my drive with Android TV directly but I can't see my usb drive either.

The downloading option with Memory works really well but I'm worried it'll damage my TV overtime. Am I totally wrong and it's perfectly fine to download on memory ?

I also got a small issue, if I want to check my TV settings to change the color for example, it will close the player. Is there anything I can do about that?

Thanks for your help.

**Comment by elgatito** [comment]
> Every time I want to select my drive it says that I can't write on this directory.

We do nothing with storage types. It's all about your OS and security settings. Probably your Android is not allowing to write to desired location. That is one of the main reasons we've done with Memory.

> The downloading option with Memory works really well but I'm worried it'll damage my TV overtime. Am I totally wrong and it's perfectly fine to download on memory ?

Memory storage uses DDR memory, not flash memory. Writes are not harmful for DDR, that is why we use it.

> I also got a small issue, if I want to check my TV settings to change the color for example, it will close the player. Is there anything I can do about that?

Sorry, I don't understand this.

**Comment by mbLc** [comment]
Thanks for your reply and sorry for the dumb questions but I'm new to Kodi.
For the last issue, it's related to Kodi itself and will be corrected in Kodi 18 apparently.

I guess I will only use the memory system since it's working great!

Thanks again.
