### ISSUE TITLE
searching broken?

### ISSUE THREAD

**Issue by Ae3NerdGod** [elgatito/plugin.video.elementum#263]
happening in win10 and libreelec 8.2.5 and 9 remix

search doesnt work unless i search, back out of the loading spinner then select the search history item of the search i just made, im using burst as provider, i put the issue in this category because search works on the web interface as it should from a phone or tablet, making me think the provider is doing its job 
kodi log http://paste.kodi.tv/daqukanoqo
libre logs http://ix.io/1qg9

**Comment by elgatito** [comment]
I don't know the reason for this. It's related only to Kodi 18. Lot of bugs there.

**Comment by Ae3NerdGod** [comment]
libreelec 8.2.5 is kodi 17.6, and has the same behavior from my experience, i can install 17.6 and get a log if necessary

**Comment by elgatito** [comment]
I don't have this problem on Kodi 17, only on Kodi 18.

**Comment by elgatito** [comment]
Please, try with 0.0.62

**Comment by elgatito** [comment]
Still not fully fixed. Will try to make it better in the next version.

**Comment by elgatito** [comment]
Please, try with 0.0.63.
