### ISSUE TITLE
[Request] Use Trakt Slug id instead of username

### ISSUE THREAD

**Issue by jorgecardoso220** [elgatito/plugin.video.elementum#264]
Hello,

When I try to access my lists from trakt I get an error "Bad status getting custom lists from username: 404"

Any ideia what might be?

Thanks

**Comment by elgatito** [comment]
No logs = no ideas.
http://elementum.surge.sh/contribute/log/

**Comment by elgatito** [comment]
@jorgecardoso220 please, provide a log, so I can find a reason. Do you have special characters in the trakt list name?

**Comment by jorgecardoso220** [comment]
i don't know if that's what you need but here it goes.
[log-2018-11-17-11.57.37.zip](https://github.com/elgatito/plugin.video.elementum/files/2591733/log-2018-11-17-11.57.37.zip)

**Comment by elgatito** [comment]
Do you have special characters in your trakt username? We do request to Trakt Api and seems they respond there is no such url.

**Comment by jorgecardoso220** [comment]
No. Not no username and not on list name

**Comment by elgatito** [comment]
Not sure how to help. I can't see the problem in the log.
Can you enable debug logging, restart Kodi, open Trakt lists (until you get an error).
Then do log upload (via Elementum settings).

Details how to make here: http://elementum.surge.sh/contribute/log/

Without log there is no information.

**Comment by elgatito** [comment]
I had just 401 error myself. Re-activated Elementum from Kodi settings and now I see the lists.

**Comment by jorgecardoso220** [comment]
How do i do that?

**Comment by elgatito** [comment]
Elementum settings -> Trakt tab -> Authorize

**Comment by jorgecardoso220** [comment]
didn't work for me. still got the same error as before

**Comment by elgatito** [comment]
Finally I get it. You have a space in your username (not name). Next version will have a fix for that. You will need to re-authorize, to save new information.

**Comment by jorgecardoso220** [comment]
I removed the space in my username and solved it. 
Thanks

**Comment by elgatito** [comment]
Please, try 0.0.67.
Now handling spaces in username.
