### ISSUE TITLE
Предложение: рейтинг

### ISSUE THREAD

**Issue by ElvisPresly** [elgatito/plugin.video.elementum#267]
Привет.
1. Предлагаю ввести синхронизацию в обе стороны рейтинга с Trakt. Посмотрел, оценил - записалось в тракт. Зашел на сайт Trakt оценил фильм, при следующей синхронизации в библиотеке Kodi появился рейтинг к элементу. Реально?

2. Не знаю баг или фича, но очень раздражает. Когда я нахожусь в плагине Elementrum ищу фильмы и добавляю их в библиотеку Kodi. После нажатия на "Добавить в библиотеку" происходит добавление в библиотеку, и я могу дальше гулять по фильмам смотреть описание и тд. Но буквально через несколько секунд интерфейс замирает и крутится кружок "загрузки", в этот момент я не могу добавлять фильмы в библиотеку или просто перемещаться по ним. Возможно ли это как-то убрать?

**Comment by elgatito** [comment]
1. Этим занимается официальное дополнение Trakt. оно спрашивает рейтинги того что просмотрено. Делать синхронизацию не вижу смысла.

2. В настройках Elementum отключается яавтоматическое обновление библиотеки.

**Comment by ElvisPresly** [comment]
@elgatito 
1. Причем тут официальный плагин Trakt если речь о Elementrum. Тем более что оба плагина конфликтуют друг с другом (в плане синхронизации с Trakt, фильмы появляются удаляются самопроизвольно)

2. В настройках отключил обе галочки которые связаны с автоматическим обновлением библиотеки Kodi. Теперь появляется окно "пересканировать библиотеку?" нажимаю нет опять появляется кружок загрузки. Да и вообще смысл в этом окне если я принудительно отключил в настройках, смысл теряется так как заставляет делать лишнее движение нажать кнопку Нет.

Ну и судя по твоему отношению к проекту, лучше его вообще закрой, может кто нибудь да форкнет, человек не с таким отношением к делу как ты. Судя по количеству Issues да и вообще, видно же что запал пропал, нет ни настроения ни желания.

**Comment by elgatito** [comment]
1. Отключаете в плагине Тракта отмечать просмотренное или в Elementum отмечать просмотренное и дублей не будет. 
2. Вы отключаете автоматический запуск обновления. Соответсвенно включается выбор. 

Спасибо за советы, обязательно закрою проект.

**Comment by elgatito** [comment]
2. Auto library update setting was added to Elementum (Yes / Ask / No)

**Comment by ElvisPresly** [comment]
@elgatito спасибо, очень полезная настройка. Подскажите, может быть возможно избавиться от окна которое выскакивает, когда нет подходящего стрима. Например если фильм свежий а торенты для него ещё нет, после запуска поиска стримов иногда появляется бейдж уведомления, что стрима не найдены, а иногда окно на весь экран типа невозможно воспроизвести, которое нужно закрывать в ручную. Или например когда открылось окно с предложенным стримами и ты его закрываешь, иногда выскакивает это окно.

**Comment by elgatito** [comment]
@ElvisPresly это окно выводит сам Коди, так как ожидает получить видеофайл, а его нету. Не уверен что можно обойти.
