### ISSUE TITLE
Initial buffering timeout?

### ISSUE THREAD

**Issue by peter099** [elgatito/plugin.video.elementum#269]
What exactly this option does? I have issue with slow buffering download speed in the beginning, but if i decrease the default value from 300 to 60 this seems to improve the buffering.

**Comment by peter099** [comment]
Nevermind.

**Comment by elgatito** [comment]
TImeout is only about timing out when download takes too much time. 
Buffer size is about getting specific number of Megabytes before giving it to Kodi, if your Kodi has custom buffer size.
