### ISSUE TITLE
TypeError: decoding Unicode is not supported

### ISSUE THREAD

**Issue by adiadi2** [elgatito/plugin.video.elementum#270]
hello,
when I want Elementum to populate any list of movies (trending, most popular...) I get an error message saying check logs for more info, while manually adding torrents plays fine. I think this is part of logs that points to the problem, because after changing Kodi language to english there was no error and everything is working fine. Can this issue be fixed somehow  because I would really like to have Kodi in my own language?

42880  NOTICE: [plugin.video.elementum] Python version: ['2.7.13 (default, Sep 26 2018, 18:42:22) ', '[GCC 6.3.0 20170516]']
                                                dist: ('debian', '9.5', '')
                                                linux_distribution: ('debian', '9.5', '')
                                                system: Linux
                                                machine: arm
                                                platform: Linux-3.14.29-126-osmc-arm-with-debian-9.5
                                                uname: ('Linux', 'vero', '3.14.29-126-osmc', '#1 SMP Wed Oct 31 17:34:23 UTC 2018', 'arm', '')
                                                version: #1 SMP Wed Oct 31 17:34:23 UTC 2018
                                                mac_ver: ('', ('', '', ''), '')
12:59:06.832 T:3390042880  NOTICE: [plugin.video.elementum] CPU: proc0={'CPU implementer': '0x41', 'Features': 'fp asimd evtstrm aes pmull sha1 sha2 crc32 wp half thumb fastmult vfp edsp neon vfpv3 tlsi vfpv4 idiva idivt', 'CPU architecture': '8', 'processor': '3', 'Hardware': 'Vero4KPlus', 'CPU revision': '4', 'CPU part': '0xd03', 'Serial': '210d04005bb0792b46cb763f4192e85e', 'Processor': 'AArch64 Processor rev 4 (aarch64)', 'CPU variant': '0x0'}
12:59:06.833 T:3390042880  NOTICE: [plugin.video.elementum] Exploring model: aarch64 processor rev 4 (aarch64)
12:59:06.833 T:3390042880  NOTICE: [plugin.video.elementum] Using CPU info arch: arm64
12:59:09.321 T:3440374528  NOTICE: [plugin.video.elementum] [GIN] 2018/11/09 - 11:59:09 | 200 |  2.207117467s |       127.0.0.1 | GET      /movies/trakt/popular
12:59:09.667 T:3390042880   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: decoding Unicode is not supported
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.elementum/navigation.py", line 6, in <module>
                                                navigation.run()
                                              File "/home/osmc/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/navigation.py", line 217, in run
                                                item["label"] = unicode(getLocalizedLabel(item["label"]), 'utf-8')
                                            TypeError: decoding Unicode is not supported
                                            -->End of Python script error report<--
12:59:09.891 T:4079174224   ERROR: GetDirectory - Error getting plugin://plugin.video.elementum/movies/trakt/popular
12:59:09.892 T:4079174224   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.elementum/movies/trakt/popular) failed

If you need full logs I'll post it?
Btw it's Kodi v17.6
regards

**Comment by elgatito** [comment]
Full log is needed in debug mode.
http://elementum.surge.sh/contribute/log/

**Comment by adiadi2** [comment]
Here's the link to full log:
https://drive.google.com/open?id=1ifrDrp94sZUvJfyKybIieLHAJc0oohHR

**Comment by adiadi2** [comment]
Sorry,
that logs were without kodi debug enabled. This is new one:
https://drive.google.com/open?id=1k4vetVenvQL_yMR5RMwHAfA2FnG132xt

End 1 more question, why torrents always connects to 50 seeders (slow DL) and I didn't put any limits in connections?

**Comment by elgatito** [comment]
@adiadi2 what do you mean by "50 seeders"? Connection limit is not unlimited by default. If you want more - set to some very big number.

**Comment by adiadi2** [comment]
ok, I thought it's unlimited like in quasar

**Comment by elgatito** [comment]
It's not unlimited in Quasar, it's just a big value. 
It you make unlimited with Elementum's torrent library - you will probably get a network failure, because it's making connections much faster and not every router can handle thousands per second.

**Comment by adiadi2** [comment]
Yes, thats right. I can't get any list of movies when kodi is on cro
language,

Datuma čet, 15. stu 2018. 08:28 Denis <notifications@github.com piše:

**Comment by adiadi2** [comment]
Kodi notification Just say error, Check logs for more info

Datuma čet, 15. stu 2018. 09:40 Armin Avdić <rufo23@gmail.com piše:

**Comment by elgatito** [comment]
Hm... I tried to change language to Croatian and now I can't open even Youtube plugin. 
Very strange. Like something is broken with that locale.

**Comment by elgatito** [comment]
Any changes?

**Comment by adiadi2** [comment]
I'll try it later and let you know.

**Comment by hseskar** [comment]
Hello
I have the same problem with Croatian language setting in Kodi. I am using Slovenian language instead and Elementum works fine (Slovenian have the same special characters as Croatian).
Any hope for solution?
Regards.

**Comment by elgatito** [comment]
@hseskar nothing to do with Elementum, it looks like a Kodi bug when you switch to Croatian.

**Comment by adiadi2** [comment]
Hi, I've found a bug in elementum croatian language file at msgctxt "#30415" ,  (%s) is missing in translated string and that was causing the problem.
bye
