### ISSUE TITLE
"Elementum Play" via context menu: What is the expected behavior?

### ISSUE THREAD

**Issue by metaltermite** [elgatito/plugin.video.elementum#271]
Kindly confirm what the expected behavior of _ELEMENTUM PLAY_ via the context menu is so I can determine if I'm encountering a bug or not.

I was under the impression that this contextual option could be called from any other video add-on, and it would send the item to Elementum Burst to begin scouring for content similar to the Magnetic/Magnetizer add-on. However, when used this way the only result is a pop-up a notification informing the user that th item is playing in Elementum, but nothing happens.

I will be happy to submit logs and other details if I am correct in my assumption of the intended behavior.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

**Comment by metaltermite** [comment]
elgatito, I was trying to play it from the Exodus Redux context menu, "Elementum Play" and nothing happens.

Elementum 0.0.62 GoTorrent: 148bb977 Go: go1.11.2
Kodi (17.6 Git:20171119-ced5097). Platform: Android ARM 64-bit
NVIDIA SHIELD Android TV with Android 8.0.0 API level 26, kernel: Linux ARM 64-bit version 3.10.96-tegra
Full Kodi debug log: https://pastebin.com/raw/gKry4u5j
Relevant portion of debug log: https://pastebin.com/raw/RjuFSEvd

More over, the same non-results happen if I select Elementum Play from the context menu in the Elementum add-on. Here is the full kodi log for that https://pastebin.com/raw/UynwMmQp

Perhaps there is something I haven't set up correctly.

**Comment by metaltermite** [comment]
Does the content that is accessed via "Elementum Play" in the context menu need to be added to the library first? That's the only way I can think of that it will have a TMDB ID assigned to it, and it does work on Library items.

**Comment by elgatito** [comment]
I don't see any information from context plugin in the log. You should enable debug logging  in Kodi to see all the information.

**Comment by elgatito** [comment]
Current implementation can play videos from Kodi library and Elementum items. 
Searching for custom queries was disabled long ago.

**Comment by elgatito** [comment]
I have made a newer version of context.elementum plugin which now uses direct search queries for non-Kodi items.
You will need next version of Elementum to handle them, so "Elementum Play" will search whatever you click it.

**Comment by metaltermite** [comment]
Context menu > Elementum Play > Notification pop-up says, "Playing with Elementum: {Episode name here}" followed by a notification pop-up that says, "Elementum not found"

Elementum Context Helper 0.0,2
Elementum  0.0.62

Relevant portion of debug log: https://pastebin.com/raw/65X2kBju

**Comment by elgatito** [comment]
Please, try with 0.0.63, it should now search, whatever is gotten from Kodi.

**Comment by elgatito** [comment]
@metaltermite  Any feedback?

**Comment by metaltermite** [comment]
@elgatito Sorry for the lack of feedback. I can confirm it works now. TPB times out, but otherwise it works perfectly.

**Comment by elgatito** [comment]
By "Times out" you mean search with Burst is not working for TPB?
