### ISSUE TITLE
searsh for movies/tv-shows dont work

### ISSUE THREAD

**Issue by Mohze** [elgatito/plugin.video.elementum#277]
hello, 
The search function in movie/tv-shows menu doesn't work after updated to 0.0.63.

**Comment by elgatito** [comment]
Log file? Information?

**Comment by Mohze** [comment]
[kodi.log](https://github.com/elgatito/plugin.video.elementum/files/2613003/kodi.log)

Hello I´ve uploaded you the log file & searched for Arrow in Elementum

**Comment by Mohze** [comment]
Yes  , I dont get any results in the search directory (tv shows & movies)

I just tried to downgrade to 0.0.62 and there it works good, without any problem...

**Comment by salashnik** [comment]
same problem

**Comment by elgatito** [comment]
@Mohze  bug will be fixed in the next version of plugin.

**Comment by pitsi** [comment]
@Mohze + @salashnik 
Are you on kodi 18 (beta/rc) by any chance? Because most addons that have a search function "broke" on kodi 18.
And that is the only reason I have not upgraded to kodi 18 rc1 yet, although my hand is "itching" me to do it :P

**Comment by elgatito** [comment]
Please, try v0.0.64.

**Comment by elgatito** [comment]
Any feedback? @Mohze , @salashnik ?

**Comment by pitsi** [comment]
Does my feedback count? No problems with search here, plain and simple.

Kodi 18rc1, debian testing x64 and elementum 0.0.65. Only one provider though...

**Comment by bluenote73** [comment]
I was experiencing this problem just like Mohze described and it now works for me using 0.0.65.
Thanks @elgatito

**Comment by Mohze** [comment]
Hello @elgatito really Good work by you, It works good ! :D

**Comment by Mohze** [comment]
You can close the case !!!!!

**Comment by Mohze** [comment]
thanks a lot!!
