### ISSUE TITLE
Delayed start of download after version 62

### ISSUE THREAD

**Issue by martinstz** [elgatito/plugin.video.elementum#279]
When a movie is started on version 62 download is starting right away. After I updated on version 63 and 64 on some trackers like Zamunda and Zelka after a movie is started you have to wait 1-2 minutes the download to start. I rolled back to version 62 and the issue with the delayed download is no longer present. Everything starts normally. I would be grateful if you could look into the issue. Thank you in advance!

**Comment by elgatito** [comment]
Log file is needed with the latest version.

**Comment by martinstz** [comment]
Log with Elementum 0.0.64:
[kodi-0.0.64.log](https://github.com/elgatito/plugin.video.elementum/files/2618935/kodi-0.0.64.log)
You can see that torrent is adding on 10:17:40.681 but start downloading on 10:18:54.051.

Log with Elementum 0.0.62:
[kodi-0.0.62.log](https://github.com/elgatito/plugin.video.elementum/files/2618942/kodi-0.0.62.log)
You can see that torrent is adding on 10:25:46.835 and start downloading on 10:25:47.913.

Big difference between times.

**Comment by elgatito** [comment]
```

10:17:40.681 T:18364  NOTICE: [plugin.video.elementum] DEBU  bittorrent   ▶ NewTorrent       Waiting for information fetched for torrent: "7231f5b659254ed03681ee3ae235424a74633e62"
10:17:40.687 T:18364  NOTICE: [plugin.video.elementum] 2018/11/27 10:17:40 error looking up "router.silotis.us:6881": lookup router.silotis.us: no such host
10:18:10.645 T:18364  NOTICE: [plugin.video.elementum] 2018-11-27 10:18:10 client.go:305: dht server on 0.0.0.0:3600: dht bootstrap: {855 142}
10:18:54.048 T:18364  NOTICE: [plugin.video.elementum] DEBU  memory       ▶ Start            StorageStart

```

Uf... That is a torrent library changes, we'd have to wait for the fix. You can disable DHT for now, it will help.

**Comment by elgatito** [comment]
I have reported about this issue. Waiting for changes.

**Comment by martinstz** [comment]
Thank you!
Have a nice day!

**Comment by Nuke142** [comment]
Пока без новостей? Где можно понаблюдать за исправлением на уровне торрент-движка?

У меня на 0.66 по-прежнему:

`16:32:57.785 T:11056  NOTICE: URLResolver: Initializing URLResolver version: 5.0.15
16:32:57.802 T:3292  NOTICE: [plugin.video.elementum] DEBU  main         ▶ Notification     Got notification from plugin.video.youtube/Other.check_settings: ["%7B%22httpd_address%22%3A%20%220.0.0.0%22%2C%20%22use_httpd%22%3A%20false%2C%20%22whitelist%22%3A%20%22%22%2C%20%22httpd_port%22%3A%2050152%7D"]
16:32:58.205 T:3292  NOTICE: [plugin.video.elementum] [GIN] 2018/12/12 - 16:32:58 | 200 |         987µs |       127.0.0.1 | GET      /playuri?uri=magnet%3A%3Fxt%3Durn%3Abtih%3Acc57ec00219db73d83fe753aa844d5b8fa21cfe2%26dn%3Drutor.info%26tr%3Dudp%3A%2F%2Fopentor.org%3A2710%26tr%3Dudp%3A%2F%2Fopentor.org%3A2710%26tr%3Dhttp%3A%2F%2Fretracker.local%2Fannounce
16:32:58.479 T:3292  NOTICE: [plugin.video.elementum] DEBU  api          ▶ func1            Playing item: ""
16:32:58.479 T:3292  NOTICE: [plugin.video.elementum] INFO  bittorrent   ▶ AddTorrent       Adding torrent from magnet:?xt=urn:btih:cc57ec00219db73d83fe753aa844d5b8fa21cfe2&dn=rutor.info&tr=udp://opentor.org:2710&tr=udp://opentor.org:2710&tr=http://retracker.local/announce
16:32:58.479 T:3292  NOTICE: [plugin.video.elementum] DEBU  bittorrent   ▶ AddTorrent       Making new torrent item with url = ''
16:32:58.479 T:3292  NOTICE: [plugin.video.elementum] DEBU  bittorrent   ▶ NewTorrent       Waiting for information fetched for torrent: "cc57ec00219db73d83fe753aa844d5b8fa21cfe2"`

**Comment by elgatito** [comment]
@Nuke142  Какие новости ожидаете? У всех всё работает, из тех кто сообщал об ошибках. Кусок лога вообще ни о чем не говорит.

**Comment by Nuke142** [comment]
@elgatito 
https://pastebin.com/Y0ZVV7w8
запустил один фильм с одного трекера, потом другой со второго.
Крутится кружок - начала не дожидался, нажимал esc.
