### ISSUE TITLE
Minor issue: Trakt activation still refers to Quasar

### ISSUE THREAD

**Issue by hoshsadiq** [elgatito/plugin.video.elementum#28]
Trakt still refers to Quasar

<img width="381" alt="image" src="https://user-images.githubusercontent.com/600045/34349161-58a387c4-ea07-11e7-85be-93900e44abce.png">

**Comment by elgatito** [comment]
Try the v0.0.20, will need re-authorize the plugin.

**Comment by hoshsadiq** [comment]
Correct now!

**Comment by elgatito** [comment]
And now we have an auto fetching of logged in username (previously had to enter manually). 
I have some plans on making few changes to trakt to bring more lists.
