### ISSUE TITLE
[Request] Add sort by title option for TV Series

### ISSUE THREAD

**Issue by dancaer69** [elgatito/plugin.video.elementum#280]
Please, add a sort by title option for TV Series. I use elementum very rear because I have a lot of series and the sort types which elementum supports is very unconfortable for me. Also I found very strange to don't have an alphabetical order sort method. I recently tried it again and this time I checked the Movies section and found that there is this sort type for movies. Why not for tv series too?
I have very limitied programming and python knowledge, but by searching in source code I found that this can be done easy. I found that in navigation.py are the sort types and also that needed to just add the line:
xbmcplugin.addSortMethod(HANDLE, xbmcplugin.SORT_METHOD_TITLE_IGNORE_THE)
to add this sort type. 
I solved my problem, but it would be nice to be added so to don't need to edit the file manually in every update.
Thanks in advance.

**Comment by elgatito** [comment]
Sorry, not quite understanding where you want to change sorting?
Lists like "most popular" or "trending" are requested from the remote services page by page, so changing the sort order will influence only one specific page, you see, and not the sort in general.

**Comment by dancaer69** [comment]
I mean the sorting in tv series collection.

**Comment by elgatito** [comment]
> I mean the sorting in tv series collection.

Can you give exact path to where you need the sorting? (How to get there)

**Comment by dancaer69** [comment]
If you mean path in elementum, is Elementum -> Tv Series -> Collection. If you mean the path to the file I edited, is 
plugin.video.elementum -> resources -> site-packages -> elementum -> navigation.py
I added a line above line 216.

**Comment by elgatito** [comment]
Trakt Collections are sorted by collected date and has no configuration.
Adding sorting in the python code does not make sense, it will break any sortings, made by plugin.

**Comment by elgatito** [comment]
Please, try version 0.0.66.

**Comment by elgatito** [comment]
Does that suit you?

**Comment by dancaer69** [comment]
Yes, thank you.

**Comment by dancaer69** [comment]
Yes, I just did it.
