### ISSUE TITLE
Slow download speed using files. Normal speed using memory

### ISSUE THREAD

**Issue by Pinhastest** [elgatito/plugin.video.elementum#285]
If I select to use files on Elementum options, the download speed is always dropping, if I select memory there is no problem at all.
I have this problem on an android box, already done a clean install and there is no problem with the storage speed on the machine. 
I will try to paste logs later.

Nice work maintaining this Addon

**Comment by elgatito** [comment]
You should review existing issues before creating a new one.
It's not in a plugin scope.
https://github.com/anacrolix/torrent/issues/265
