### ISSUE TITLE
Logs upload to pastebin feature does not work

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/plugin.video.elementum#286]
## Expected Behavior

логи должны заливаться как описано тут http://elementum.surge.sh/contribute/log/

## Current Behavior

![img_20181204_233901](https://user-images.githubusercontent.com/17964763/49472437-7fb4d700-f820-11e8-9974-52ecbe44b008.jpg)

ни all ни bundle не загружаются
в веб ui они отдаются (кроме /bundle в spmc - см. ниже)

минорно: в окне результата вместо pastebin paste.ubuntu.com, если имя pastebin используется как дженерик, то ладно.

## Possible Solution

кстати в SPMC используется другой путь к логу - `Android/data/com.semperpax.spmc/file/.smpc/temp/spmc.log` (или `Android/data/com.semperpax.spmc17/file/.smpc/temp/spmc.log`) из-за которого плагины типо "Kodi Logfile Uploader" не работают. у вас может тоже быть такое именно для SPMC. правда он уже не разрабатывается, но думаю много у кого ещё стоит.

## Steps to Reproduce (for bugs)

1. зайти в настройки плагина
2. дополнительно
3. попробовать залить логи
4.

## Your Environment

* Version used: 0.0.66

* Environment name and version: kodi 18 rc2, spmc 17.6

* Operating System and version: android tv 8.0

* Link to Kodi debug log:
https://paste.ubuntu.com/p/q3DJ7pzBWn/

**Comment by elgatito** [comment]
В логе нету вообще никакой информации о попытке загрузки лога. 
Даже не вижу сообщений о запуске дополнения (plugin.video.elementum).
Режим отладки в Kodi включен?

У меня лог загружается нормально. Путь к логу отдаёт Коди.

**Comment by antonsoroko** [comment]
здравстуйте.
>Режим отладки в Kodi включен?
включен был (на скриншоте видно)

>Путь к логу отдаёт Коди.
видно для SPMC это не так, может баг.

>У меня лог загружается нормально
у меня отдавал пустоту и в 0,65 и в 0,66

в этом логе куча сообщений от elementum как я вижу, а в самом конце как раз момент когда я сделал заливку
я конечно могу попробовать ещё один лог сделать, может там будет лучше видно...

**Comment by antonsoroko** [comment]
новый лог c 0.66 https://paste.ubuntu.com/p/JpZxWJMkw4/
коди 18rc3

и ещё один с 0,67 https://paste.ubuntu.com/p/TjNnVc5CWK/
в этом логе ещё для интереса менял шрифт и скин - одинаково, проблема не ui

ситуация всегда как на картинке, неважно заливаешь c или без kodi.log

спасибо

**Comment by elgatito** [comment]
Please, try v0.0.69. There are additional log messages to see what happens.

**Comment by antonsoroko** [comment]
nope :-(
```
16:32:25.326 T:18446744072555850096   DEBUG: [plugin.video.elementum] Requesting http://127.0.0.1:65220/cmd/paste/bundle?resume=false from ['plugin://plugin.video.elementum/cmd/paste/bundle', '-1', '', 'resume:false']
16:32:25.364 T:18446744072815139184   DEBUG: ------ Window Init (DialogExtendedProgressBar.xml) ------
16:32:25.387 T:18446744072526829936  NOTICE: [plugin.video.elementum] INFO  api          ▶ Pastebin         [0mRequesting http://127.0.0.1:65220/debug/bundle before uploading to pastebin
16:32:26.387 T:18446744072526829936  NOTICE: [plugin.video.elementum] [32mNOTI  api          ▶ Pastebin         [0mLog uploaded to: https://paste.ubuntu.com/
16:32:26.416 T:18446744072815139184   DEBUG: ------ Window Init (DialogConfirm.xml) ------
```
https://paste.ubuntu.com/p/xdpmhTQ2gt/

**Comment by antonsoroko** [comment]
one more report about this issue - https://github.com/elgatito/plugin.video.elementum/issues/314#issuecomment-449761888

**Comment by antonsoroko** [comment]
@elgatito 
sorry for bothering you
same for the 0.0.70 https://paste.ubuntu.com/p/hS3GGHstQJ/ (at the very end)

**Comment by elgatito** [comment]
Please, use v0.0.71.
There are more messages in the log. Maybe we'll find the reason.
