### ISSUE TITLE
[Request] Select usage options for proxies in Elementum

### ISSUE THREAD

**Issue by Azat868** [elgatito/plugin.video.elementum#287]
Прописываю прокси в Burst, трекеры опрашиваются без прокси. Прописываю прокси в сам elementum, трекеры опрашиваются через прокси и торренты скачиваются тоже через прокси. Как сделать опрос трекеров через прокси?

**Comment by elgatito** [comment]
Каких трекеров? 
Какие опросы?

**Comment by Azat868** [comment]
>Каких трекеров? 
Торрент трекеров. А есть еще какие то трекеры в вашем дополнении? Какие?
>Какие опросы?
Опросы/запросы трекеров

**Comment by Azat868** [comment]
Также если прописать в настройках Kodi проксю, Burst по прежнему делает запросы к трекерам без прокси.

**Comment by elgatito** [comment]
> Также если прописать в настройках Kodi проксю, Burst по прежнему делает запросы к трекерам без прокси.

Ни Elementum, ни Burst не имеют никакого отношения к прокси прописываемых где либо кроме настроек дополнения.
И прокси в Burst тоже не зависят от Elementum. 

Burst передаёт ссылку на скачивание, Elementum скачивает. запросы к трекерам идут через прокси, прописанные в Elementum.

**Comment by Azat868** [comment]
Я правильно понимаю, запрашивать трекеры через проксю, а скачивать фильмы без прокси нельзя?

**Comment by elgatito** [comment]
Прокси прописанная в самом Elementum используется для скачивания и для трекеров. Или для всего или ни для чего.

**Comment by Azat868** [comment]
Понятно. Спасибо. Думал раз в 2 местах(Burst, Elementum) можно прописать настройки прокси

**Comment by elgatito** [comment]
Можно прописать в Elementum, а в Burst выбрать "использовать настройки Elementum". Тогда и там и там будут точно одинаковые прокси.

**Comment by Azat868** [comment]
Дело не в этом. Большинству скорее всего нужен доступ именно к трекерам через проксю. Так как они заблочены. А само скачивание хочется по основному трафику без прокси. Скорость существенная. 25 мегабит против 100 мегабит.

**Comment by elgatito** [comment]
Ну так это нетрудно сделать.

**Comment by elgatito** [comment]
Опции выбора использования прокси добавлены в 0.0.67

**Comment by elgatito** [comment]
Added to previous versions.
