### ISSUE TITLE
[Request] Add option to disable fanart.tv usage

### ISSUE THREAD

**Issue by MilePule** [elgatito/plugin.video.elementum#288]
No posters for new enteries (movies and shows). The cashed posters are displayed.

**Comment by elgatito** [comment]
Where you see no posters?

**Comment by MilePule** [comment]
Nowhere, in the main menu on the left side and also no posters when I go to info about movie/show. 
I use fresh install of Kodi 18 on a corelec, but also tried on Kodi 17.6 with libreelec.
The device is amlogic s912

**Comment by elgatito** [comment]
If you don't see posters while browsing Elementum categories - then it's something with fanart.tv website.

**Comment by MilePule** [comment]
OK, I will wait and check later.
Thanks.

**Comment by veniciusgp** [comment]
>           If you don't see posters while browsing Elementum categories - then it's something with fanart.tv website.

Does the quasar also use the website fanart.tv? Because in the quasar this problem is not occurring.

**Comment by elgatito** [comment]
> Does the quasar also use the website fanart.tv? 

No.

**Comment by Mohze** [comment]
Hello Elgatito,
I've have same problem no poster are available. The problem started yesterday at evening.

**Comment by elgatito** [comment]
Fanart.tv is not properly giving images. 
Nothing to do by Elementum.

**Comment by elgatito** [comment]
Please, try version 0.0.67. 
Option was added to disable fanart.tv

**Comment by MilePule** [comment]
Much faster poster loading when fanart.tv disabled
