### ISSUE TITLE
Very slow download speed

### ISSUE THREAD

**Issue by heartlogic** [elgatito/plugin.video.elementum#29]
## Expected Behavior
Download torrent speed with Quasar is around 4000 and 5000 Kbps on a VDSL line

## Current Behavior
For the same torrents download speed is around 700 and 800 Kbps

## Your Environment
* Version used: 0.20

* Environment name and version: Libreelec 8.2.2.1 with Kodi Krypton 17.6 on a S905X TV box

* Link to Kodi debug log:
https://paste.ubuntu.com/26259030/

**Comment by heartlogic** [comment]
https://paste.ubuntu.com/26259030/

**Comment by elgatito** [comment]
Plugin is not controlling torrent engine and file storage. Nothing to do from our side. 
You can try creating a feature issue on torrent engine's repository ( https://github.com/anacrolix/torrent )
