### ISSUE TITLE
[Request] Support for hidden shows in Trakt>Progress

### ISSUE THREAD

**Issue by quetzalcoatl82** [elgatito/plugin.video.elementum#290]
## Expected Behavior
Trakt lets you hide shows in the progress page in case you are not watching the show anymore.
The progress page inside Elementum should work in a similar way, hiding all the unwanted shows. Trakt's api is probably providing the information already, since i saw the same feature working inside Incursion/Placenta/Exodus

## Current Behavior
Now the progress page lists every shows you started.

## Possible Solution
This is probably related https://trakt.docs.apiary.io/#reference/users/hidden-items

**Comment by elgatito** [comment]
Need implementing of storing of hidden items and adding it to collections/userlists browsers, but looks good.
