### ISSUE TITLE
Can you make the "add torrent" dialog box more user friendly?

### ISSUE THREAD

**Issue by pitsi** [elgatito/plugin.video.elementum#291]
A few hours ago, I was explaining to a friend how elementum's "add torrent" option works, because he wanted to play a torrent he had stored locally. This is what the add torrent dialog box looks like by default

![screenshot001](https://user-images.githubusercontent.com/5880037/50014238-137a6600-ffcc-11e8-9337-27533c70c03f.png)

As usual, one has to first select "file" from the right side and then click on the almost invisible box under file path to open kodi's built in file browser and find the file. Can this be made more user friendly somehow?

If not, in case there is some limitation within kodi itself for such dialog boxes, how about making 2 entries in the main menu, one for adding a torrent file, which would pop kodi's file browser, and one for adding a magnet link, which would obviously pop up kodi's on screen keyboard?

**Comment by elgatito** [comment]
I have no plans to make this. It need a lot of time. 
If anyone makes that and submits a PR - I would review it, for sure.

**Comment by elgatito** [comment]
If someone wants to make changes to new torrent window - I will review the Pull Request.
I can't see any obvious ways to make if different.

**Comment by pitsi** [comment]
How does the NEW add torrent window look? I made the update to 0.1.28 a couple of minutes ago, restarted kodi just in case, but the add torrent window looks like the one on my pic above.

**Comment by elgatito** [comment]
There is no new window. 
You can make changes and pull request them to include in the plugin.
I have no plans to change that window.

**Comment by pitsi** [comment]
Oh ok. I wish I knew coding so as to help :(
