### ISSUE TITLE
Ask to Delete set but not asking to delete

### ISSUE THREAD

**Issue by afduggirala** [elgatito/plugin.video.elementum#292]
Im running Elementum 0.0.66 in Kodi 17 in Debian 9.0
I have set the option to Ask to Delete files for “not finished video” and “watched/downloaded video”. However, when I finish watching a video or stop a video during playback, I dont get asked if I want to delete the files, Elementum goes ahead and deletes the files and the torrent is not active anymore.
thank you,

**Comment by elgatito** [comment]
Log with debug mode needed.
http://elementum.surge.sh/contribute/log/

**Comment by afduggirala** [comment]
Hope this helps.
https://pastebin.com/raw/3pY4zpeX

**Comment by elgatito** [comment]
You have memory storage, which does not use any files for downloading. 
For memory storage we always stop and remove torrent.
