### ISSUE TITLE
Private Trackers not downloading after 0.0.67

### ISSUE THREAD

**Issue by a-nunes** [elgatito/plugin.video.elementum#293]
I updated elementum earlier this morning, after this my search in private Trackers has improved a lot (iptorrents and torrentleech), but after this, my FileList provider stopped downloading, and even though they're finding torrents in all those private trackers, it doesn't start downloading in none of them. Could you help me with this?

**Comment by elgatito** [comment]
Log file needed. http://elementum.surge.sh/contribute/log/

**Comment by Goga777** [comment]
у меня тоже с 67 версией проблемы - поиском нахожу раздачи,  но при клике на раздачу ничего не происходит. логи тут http://slexy.org/view/s20KQcd3sY
на роутере конфиг опенвпн от спавн

**Comment by Goga777** [comment]
2 вопрос, мой пров не поддерживает ipv6, на роутере и на приставке нвидиа шилд ipv6 тоже отключен. Но в логах элементума вижу
ListenIPv6=, ListenPort=0, DisableIPv6=false
как сменить на ListenIPv6=, ListenPort=0, DisableIPv6=true ?

**Comment by elgatito** [comment]
Please, try Elementum v0.0.68.

**Comment by a-nunes** [comment]
I've tried the new version, but still not working. I've tried with the three different trackers that I said before.

Here's the new log:

https://pastebin.com/VxDQg95K

**Comment by elgatito** [comment]
@a-nunes can you share the http://127.0.0.1:65220/info page output, in the moment when you add torrent and wait for download? It will show trackers status. And also you can enable DHT, you have it disabled.

**Comment by a-nunes** [comment]
@elgatito here it is:

https://pastebin.com/wiXwVj5i

**Comment by elgatito** [comment]
@anacrolix trackers are protected by cloudflare. I have added internal proxy, which bypasses cloudflare challenges. Probably have to add that proxy for http client, that is used in torrent library.

@a-nunes you can enable DHT to bypass trackers defences.

**Comment by elgatito** [comment]
Taking my words back, tracker urls should come directly, without internal proxy, and according to the log it looks like the proxy is used. So it's probably a bug in Elementum.

**Comment by elgatito** [comment]
@a-nunes will be fixed in the next version. Checked with ygg and torrentleech.

**Comment by a-nunes** [comment]
Ok, looking forward for the next version. Once it's done, if you want, may mention me here, I'll test it.

**Comment by a-nunes** [comment]
@elgatito it's working perfectly now. Thank you.

**Comment by petroionut26** [comment]
Hy, I have a problem with same filelist private tracker, search for rodubbed not showing me any results:

https://paste.kodi.tv/tirutikuza
