### ISSUE TITLE
Elementum no Daemon start anymore

### ISSUE THREAD

**Issue by Lola33** [elgatito/plugin.video.elementum#294]
Elementum does not start daemon, will not play anything..., v. 0.67
I reinstalled 5 times..., debug, clear all the cache
edit : delete the "lockfile"
now daemon start but still no luck
playback failed
please help
Thank you

Lola

**Comment by elgatito** [comment]
http://elementum.surge.sh/contribute/log/
Log file needed.

**Comment by Lola33** [comment]
Thank you very much, I fix it by deleting the repo and reinstalled
also desactivate the torrent 1337x which give me a timeout message 
Elementum stop crashing. 
Lola

**Comment by Lola33** [comment]
Again this morning..., Elementum Playback failed or torrents timeout
cannot send you my log because Kodi is installed directly to my Bravia TV
but all my friend having the same issues 
Thank you in advanced for all your work and assiste

Lola33

**Comment by Lola33** [comment]
I found a solution in Proxy setting, I disable "Enable built-in HTTP" and everything is working properly, except the french torrent YGG...
Do you have a solution for YGG
Thank again
 Lola

**Comment by elgatito** [comment]
Please, try Elementum v0.0.68.

**Comment by Lola33** [comment]
I just did..., I need to knows how to setup the proxy in Elementum and Burst 
thank for your help

**Comment by elgatito** [comment]
Elementum settings -> Proxy -> enable internal proxy.

I will close this issue if you don't provide a log file.
http://elementum.surge.sh/contribute/log/

**Comment by Lola33** [comment]
I cannot provide a log file because Kodi and Elementum are install directly on my Bravia TV and I am not tecksavy enough to sent you my log, but thank you for your help. I am ok now, you can close my issue
Lola

**Comment by elgatito** [comment]
@Lola33 If you'd look at the link, you could be you just need to enter Elementum settings and select "upload log" and that is it, it will do all the required actions and give you the link.

**Comment by Lola33** [comment]
Wish I could provide a log file but from an Android TV, you cannot paste the log file..., Elementum is working fine....,  my only problem is I cannot download from the Torrent YGG..., Thank you for All your help...,
You can close the issue now
Lola
