### ISSUE TITLE
0.0.67 not downloading (previous 0.0.66 was/is working fine)

### ISSUE THREAD

**Issue by fastleo63** [elgatito/plugin.video.elementum#295]
## Expected Behavior

When I add a torrent link, and/or make a torrent search and click over one of the results, Elementum starts to download part of the file to buffer, and after a while Kodi starts playback.

## Current Behavior

Clicking on one of the results or adding a torrent link produces nothing at all, download doesn't start.

## Possible Solution

As a temporary workaround I downgraded Elementum to 0.0.66 (without removing any existing settings and leaving current Burst 0.0.32 untouched).

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: Elementum 0.0.67 / Elementum Burst 0.0.32

* Environment name and version: Kodi 17.6 stable (x86) [Krypton]

* Operating System and version: Microsoft Windows 10 Pro (64-bit) version 1809

* Link to Kodi debug log: https://paste.ubuntu.com/p/4nWbS77Zmg/

**Comment by Mohze** [comment]
I think I had same issue . I didn’t  get any results at all  but after disabled Proxy—> “Enable built in http proxy” it works good

**Comment by fastleo63** [comment]
> 
> 
> I think I had same issue . I didn’t get any results at all but after disabled Proxy—> “Enable built in http proxy” it works good
I tried to disable HTTP proxy but I didn't solved the problem.

**Comment by antonsoroko** [comment]
looks like there is a similar issue https://github.com/elgatito/plugin.video.elementum/issues/293

just in case - my log https://paste.ubuntu.com/p/bQtyMN6dkV/

**Comment by elgatito** [comment]
Please, try Elementum v0.0.68.

**Comment by fastleo63** [comment]
> 
> 
> Please, try Elementum v0.0.68.

**Comment by fastleo63** [comment]
I upgraded directly from v0.0.66 to v0.0.68, leaving current Elementum/Burst settings unouched.
All search, trackers and download issues solved.
Thanks a lot,
Leonardo.
