### ISSUE TITLE
0.67 stopped to work, log file attached, last working version 0.65

### ISSUE THREAD

**Issue by Lexa1983** [elgatito/plugin.video.elementum#296]
Torrent download doesn't start.
Tried different storage types. There are some errors in log file.

## Expected Behavior
Torrent buffering starts and then play video.

## Current Behavior
Nothing happens. Dialog where I paste torrent file URL just close.

## Steps to Reproduce (for bugs)
1. Open addon
2. Open dialog "add torrent"
3. Put torrent file URL
4. Press OK

## Your Environment
I installed Kodi + addon on my windows pc (fresh install) - same issue as on Android box.* Version used:
Elementum 0.67
* Environment name and version:
Kodi 17.6 [Krypton])-->
* Operating System and version:
Windows 10 1809
* Link to Kodi debug log:
https://paste.ubuntu.com/p/DvMtP255yS/

P.S. Thanks a lot! This is the most useful addon for Kodi )

**Comment by elgatito** [comment]
Please, try Elementum v0.0.68.
