### ISSUE TITLE
Elementum stopped working

### ISSUE THREAD

**Issue by pazante** [elgatito/plugin.video.elementum#298]
I am trying to play anything but all i get is no links found and one of the cpu cores goes to 100% and after that elementum is pretty much non responding until i restart kodi 
If i use web ui then movies and tvshows starts as suppose to 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: 0.61, 0.65, 0.67

* Environment name and version: 

* Operating System and version: OSMC 17.6

* Link to Kodi debug log: https://pastebin.com/X5ZNpRwi

**Comment by elgatito** [comment]
Please, try Elementum v0.0.68.

**Comment by pazante** [comment]
I still have the same problem with v0.0.68

**Comment by pazante** [comment]
I just reinstalled osmc and elementum and now it seems like it is working
Thanks for a great add-on

**Comment by elgatito** [comment]
Probably in did not update correctly for the first time. You could uninstall and re-install the addon.
