### ISSUE TITLE
Missing Tv Show

### ISSUE THREAD

**Issue by jorgecardoso220** [elgatito/plugin.video.elementum#299]
Hello,

Just wondering if anyone else has the same problem. I search for "Narcos: Mexico" in tv shows and the show does not appear. Any ideas?

Thanks

**Comment by Lola33** [comment]
in Elementum setting disable  Proxy and build-in HTTP, 
force close Kodi, 
 search for your tv show..., should work

**Comment by elgatito** [comment]
I have checked searching "narcos" in Shows and it's found.

**Comment by jorgecardoso220** [comment]
O follow the advice and still no luck 😕

**Comment by elgatito** [comment]
@jorgecardoso220 log log log!
http://elementum.surge.sh/contribute/log/#easy-one

**Comment by elgatito** [comment]
Closing as no response got.
We do not do searches, it's done by TheMovieDB website. 
"Nacros mexico" is successfully searched.
