### ISSUE TITLE
[Request] Hardcoded localhost in daemon

### ISSUE THREAD

**Issue by rogerberm** [elgatito/plugin.video.elementum#3]
Hi,

Since there is no issues tab in the daemon repo, I'd like to report an issue here.

In the code the hostname for the generated http url is hardcoded to "localhost" (util/ip.go GetHTTPHost()). This is not an issue in general. What I'm trying to do in particular is send the http path generated by Elementum to a chromecast (via LocalCast or another app from a Android device), and that would only work if the path had the actual ip address or host name of my device.

I have tried changing the generated url from http://localhost:port/files/blahblahblah.mkv to http://theactualIP:port/files/blahblahblah.mkv and sending that to the chromecast, and it works. I have problems with docker, so I cannot compile Elementum and test the change myself.

Any chance to get the host reference dynamically? Or to configure it on the settings?

Thanks!

**Comment by elgatito** [comment]
You mean, when you send a request to the daemon to get torrent, it returns a 302 reply with a location (virtual one) of file like http://localhost:port/files/blahblahblah.mkv, then you can't use that link on external devices because of the hardcoded IP ?

**Comment by rogerberm** [comment]
Yes. Well, I think.

When I play a video from the ListItems generated by element, I get lines like this:

15:37:40.715 T:139810686530240  NOTICE: VideoPlayer::OpenFile: http://localhost:65220/files/[thetorrent]/[thefile].mkv

which of course plays fine locally. If instead of localhost that line contains the actual name or ip address or something that the other device can resolve, it plays just fine when sent to the chromecast.

**Comment by elgatito** [comment]
This is not relevant in latest versions. 
Elementum now looks it request comes from the network and generates the link accordingly.
