### ISSUE TITLE
after reboot torrent away

### ISSUE THREAD

**Issue by tomtomclub** [elgatito/plugin.video.elementum#30]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

hi after reboot the torrent disappeared   https://paste.ubuntu.com/26274719/
I also can not play the torrent if it is downloading, on menu torrent .
i test it on Quasar en works fine , any suggestion what it can be

**Comment by tomtomclub** [comment]
and download torrent is not play .no matterwhat i try 
it seems better rol back to Quasar 64 bit

**Comment by syneox** [comment]
Download torrent will play with a following workaround:

Choose NO on question about using already available torrent, let it do another search and choose same torrent in new search again, it will play after that.

**Comment by tomtomclub** [comment]
no i try it wont work

**Comment by elgatito** [comment]
If you select memory storage - torrents are not saved after addon restart. 
If you choose another storage engine - it should save in the list.

**Comment by tomtomclub** [comment]
oke thanks men , i give it try ,
