### ISSUE TITLE
Burst (0.32) does not work with new HTTP proxy in elementum (0.67)

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/plugin.video.elementum#300]
## Expected Behavior

search worked fine in 0.66

## Current Behavior

after update both burst and elementum has Proxy-related settings enabled and this leads search to fail

some other reports could be found here (https://github.com/elgatito/plugin.video.elementum/issues/295#issuecomment-448004591 and https://github.com/elgatito/plugin.video.elementum/issues/295#issuecomment-448013873) and here https://4pda.ru/forum/index.php?showtopic=359930&st=18880

## Steps to Reproduce (for bugs)

1. enable HTTP proxy in elementum
2. enable "use elementum as http proxy" in burst
3. try to seatch something
4.

## Your Environment

* Version used: 0.67

* Environment name and version: kodi 18 rc3 / spmc 17.6

* Operating System and version: android 8.0

* Link to Kodi debug log:

https://paste.ubuntu.com/p/7YQsYKprzW/ (logging for proxy was enabled)

**Comment by elgatito** [comment]
Please, try Elementum v0.0.68.

**Comment by antonsoroko** [comment]
заработало, спасибо!
чуть медленнее с прокси. раньше burst хватало таймаута в 10 сек, сейчас 15. поставил пока брать таймаут из elementum. я так понимаю он 30 сек (https://github.com/elgatito/plugin.video.elementum/blob/151659ffe4086f93be0718ca215b357a02d44db5/resources/settings.xml#L141).
ещё раз спасибо.
