### ISSUE TITLE
File backend ignores buffer size. Elementum downloads the whole file and shows wrong completion percentage

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/plugin.video.elementum#301]
## Expected Behavior

to buffer only specified amount (in MB) and the start playing

## Current Behavior

file (1.4GB) was downloaded completely (took a lot of time and debug showed this as well) - now I see why with previous version of elementum I always got "timeout" erros, also I saw similar complains in some other issues
also in interface i saw 42% (after restart it became 100%). in debug it was 100%

## Steps to Reproduce (for bugs)

1. use file storage
2. set buffer to 5MB
3. try to download a file about 1 GB size
4. measure a time and take a look to :65220/debug/all

## Your Environment

* Version used: 0.66

* Environment name and version: kodi 18 rc3

* Operating System and version: android 8.0

* Link to Kodi debug log:

log https://paste.ubuntu.com/p/pHYZ3JzGbZ/
debug https://paste.ubuntu.com/p/RT7M4rsDxV/

**Comment by antonsoroko** [comment]
a bit different for 222MB file
it was downloaded for 80% and then playback was started
log https://paste.ubuntu.com/p/qHtmrk9HsY/
debug1
https://paste.ubuntu.com/p/57ynRk3bPk/
debug2
https://paste.ubuntu.com/p/gpRwnZbjbp/

**Comment by elgatito** [comment]
Your Kodi has 100mb of memory for buffer, that means Elementum will download first 100mb before starting playback. 

```
                                                <memorysize>104857600</memorysize>
```

```
21:43:54.517 T:18446744072826661232  NOTICE: [plugin.video.elementum] [36mDEBU  config       ▶ Reload           [0mAdjusting buffer size according to Kodi advancedsettings.xml configuration to 105 MB
```

**Comment by antonsoroko** [comment]
but it downloaded the whole file - 1400 MB not 100 MB
i will comment out this and see what will happen. thanks.

**Comment by antonsoroko** [comment]
I renamed advancedsettings.xml file
anyway it is almost the same
now it is 60% for 1.4GB
https://paste.ubuntu.com/p/R62qPyfqCW/

**Comment by antonsoroko** [comment]
вообще как-то странно себя ведёт
в логе видно что хочет скачать 52 + 6,2 метра (буфер 50)
но скачало 14% от 1,6 гига
это всё с Linux тачки
```
DEBU  bittorrent   ▶ Buffer           Setting buffer for file: GOGOL_STRASHNAJA_MEST_2018_WEB_DLRip.1.46Gb.MegaPeer.avi (1.6 GB / 1.6 GB). Desired: 52 MB. Pieces: 0-24 + 745-747, PieceLength: 2.1 MB, Pre: 52 MB, Post: 6.2 MB, WithOffset: 0 / 1562378240 (0)
DEBU  bittorrent   ▶ NewFileReader    NewReader: 819069721
DEBU  bittorrent   ▶ NewFileReader    NewReader: 947455638
INFO  btplayer     ▶ playerLoop       Buffer loop
DEBU  bittorrent   ▶ progressEvent    8f176d: 0 B/0 B | Buffering (0.00%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 0 B/0 B | Buffering (0.00%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 0 B/0 B | Buffering (0.00%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 88 kB/0 B | Buffering (0.03%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 773 kB/0 B | Buffering (0.25%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 1.9 MB/0 B | Buffering (0.60%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 3.0 MB/0 B | Buffering (0.96%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 4.0 MB/0 B | Buffering (1.30%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 4.4 MB/0 B | Buffering (1.63%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 4.2 MB/0 B | Buffering (1.88%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 4.2 MB/0 B | Buffering (2.17%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 4.2 MB/0 B | Buffering (2.52%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 4.2 MB/0 B | Buffering (2.83%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 4.3 MB/0 B | Buffering (3.15%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 4.2 MB/0 B | Buffering (3.46%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 4.2 MB/0 B | Buffering (3.79%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 4.3 MB/0 B | Buffering (3.97%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 4.6 MB/0 B | Buffering (4.37%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 4.6 MB/0 B | Buffering (4.82%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 4.8 MB/0 B | Buffering (5.22%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 4.8 MB/0 B | Buffering (5.51%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 4.6 MB/0 B | Buffering (5.83%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 4.5 MB/0 B | Buffering (6.11%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 3.4 MB/0 B | Buffering (6.20%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 2.7 MB/0 B | Buffering (6.32%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 2.0 MB/0 B | Buffering (6.45%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 1.8 MB/0 B | Buffering (6.68%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 2.6 MB/0 B | Buffering (7.01%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 3.5 MB/0 B | Buffering (7.39%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 4.3 MB/0 B | Buffering (7.71%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 4.8 MB/0 B | Buffering (8.05%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 4.6 MB/0 B | Buffering (8.22%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 4.7 MB/0 B | Buffering (8.54%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 4.8 MB/0 B | Buffering (8.84%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 5.2 MB/0 B | Buffering (9.25%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 5.8 MB/0 B | Buffering (9.68%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 6.0 MB/0 B | Buffering (10.11%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 6.1 MB/0 B | Buffering (10.37%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 5.6 MB/0 B | Buffering (10.63%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 5.0 MB/0 B | Buffering (10.88%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 4.9 MB/0 B | Buffering (11.28%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 4.9 MB/0 B | Buffering (11.61%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 5.0 MB/0 B | Buffering (11.97%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 5.3 MB/0 B | Buffering (12.30%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 5.0 MB/0 B | Buffering (12.65%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 4.9 MB/0 B | Buffering (13.01%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 4.8 MB/0 B | Buffering (13.38%)
DEBU  bittorrent   ▶ progressEvent    8f176d: 4.8 MB/0 B | Buffering (13.76%)
DEBU  bittorrent   ▶ bufferFinishedEvent  Buffer finished: true, map[int]float64{12:0, 9:0, 15:0, 20:0, 23:0, 747:0, 1:0, 5:0, 8:0, 17:0, 21:0, 745:0, 4:0, 7:0, 14:0, 22:0, 24:0, 3:0, 18:0, 0:0, 6:0, 13:0, 10:0, 16:0, 19:0, 2:0, 11:0, 746:0}
DEBU  bittorrent   ▶ Close            Closing reader: 819069721
DEBU  bittorrent   ▶ Close            Active readers: 0
DEBU  bittorrent   ▶ Close            Closing reader: 947455638
DEBU  bittorrent   ▶ Close            Active readers: 0
INFO  btplayer     ▶ playerLoop       Waiting for playback...
DEBU  bittorrent   ▶ progressEvent    8f176d: 4.8 MB/0 B | Downloading (14.10%)
```

**Comment by antonsoroko** [comment]
even worse on 0.0.70 - 100% before start play (buffer=50MB, no advancedsettings.xml) :-(
https://paste.ubuntu.com/p/yqQJP9xfkV/

**Comment by antonsoroko** [comment]
I guess the same problem here - https://github.com/anacrolix/torrent/issues/265#issuecomment-449726378

**Comment by entproject** [comment]
> Your Kodi has 100mb of memory for buffer, that means Elementum will download first 100mb before starting playback.
> 
> ```
>                                                 <memorysize>104857600</memorysize>
> ```
> ```
> 21:43:54.517 T:18446744072826661232  NOTICE: [plugin.video.elementum] �[36mDEBU  config       ▶ Reload           �[0mAdjusting buffer size according to Kodi advancedsettings.xml configuration to 105 MB
> ```

Is there a way to make elementum ignore advancesettings.xml and use the cache from its menu?
I have manually set an increased video buffer size in advancedsettings, but I don't want elementum to use that buffer but a smaller one. Is there a way for that?

**Comment by antonsoroko** [comment]
возможно на линуксе лучше чем на андроиде
вот сейчас скачалось 270 метров хотя бы вместо 50 что в настройках
https://paste.ubuntu.com/p/NDmgS2ppzc/
https://paste.ubuntu.com/p/xwK2SsqFCm/
https://paste.ubuntu.com/p/MrJXtKvTTk/

**Comment by elgatito** [comment]
> Is there a way to make elementum ignore advancedsettings.xml and use the cache from its menu?
I have manually set an increased video buffer size in advancedsettings, but I don't want elementum to use that buffer but a smaller one. Is there a way for that?

No. Kodi will not start playback until it downloads all the buffer size.

**Comment by elgatito** [comment]
If you have 50mb buffer size set in Elementum and you use file storage, it does not mean it will download 50mb only and then start playback. It means whole file started to download but first 50mb have higher priority.
Priorities are managed by torrent library.

**Comment by antonsoroko** [comment]
Does not the library support sequential download of pieces?

**Comment by elgatito** [comment]
> Does not the library support sequential download of pieces?

I don't know.

**Comment by elgatito** [comment]
https://github.com/anacrolix/torrent/issues/150#issuecomment-289264973

**Comment by jonian** [comment]
v0.0.71 fixes the issue for me. Thanks @elgatito!

**Comment by ssarava9** [comment]
@antonsoroko what path u set for android for use files storage option?, for me every possible combination including external drives always throws error as "download path not set, check settings"
im using android 7.1 fully rooted box
Pls help

**Comment by antonsoroko** [comment]
@ssarava9 
I have non-rooted device and paths like Android/data/com.semperpax.spmc/elementum. Fir Kodi the path is slightly different.

I guess your issue is caused by recent changes with checks for download path. Please see issues about "crash after install" for more information.

**Comment by antonsoroko** [comment]
@elgatito 
4gb file
looks like elementum downloaded ~65% of the file before playback
elementum also showed "timed out", so playback was not strated actually 

log https://paste.ubuntu.com/p/yWq7ZvX9W5/
debug https://paste.ubuntu.com/p/gCGbK3qwFf/ https://paste.ubuntu.com/p/JpSq8qDKKG/

**Comment by elgatito** [comment]
I'm closing this issue, as long, as we migrate to new torrent engine. See #351
