### ISSUE TITLE
Bad fanart.png file in elementum: No images in series menu and in widget menu

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/plugin.video.elementum#302]
## Expected Behavior

fanart.png should be real image

## Current Behavior

there is no images in series menu and in widget menu, but everything else has images
might be skin specific - mine is https://github.com/jurialmunkey/skin.fuse.neue

![no_images1](https://user-images.githubusercontent.com/17964763/50231113-1952bb80-03bf-11e9-9c50-1267f6f4635d.jpg)
![no_images2](https://user-images.githubusercontent.com/17964763/50231119-1c4dac00-03bf-11e9-96ac-a01d495b1d34.jpg)

## Possible Solution
need to change fanart.png to real image

## Steps to Reproduce (for bugs)

1. install skin.fuse.neue
2. in skin setting set elementum widget for some main menu item
3. hover on elementum nemu item - no images
4. open tv series in elementum - no images

## Your Environment

* Version used: 0.68, 0.66

* Environment name and version: kodi 18 , spmc 17.6

* Operating System and version: android 8.0

* Link to Kodi debug log:

kodi 18 https://paste.ubuntu.com/p/YxYJmV8NxY/
spmc 17 https://paste.ubuntu.com/p/cCrDqs9XJF/

**Comment by elgatito** [comment]
Images for sections of Elementum? Like "Most popular". 
Or items (shows/movies) images?

**Comment by antonsoroko** [comment]
>Images for sections of Elementum? Like "Most popular".
yes
and only for "series menu and widget menu"
please take a look to screenshots

**Comment by antonsoroko** [comment]
@elgatito 
I guess I found the root cause.
could it be because of:
```
00:22:49.650 T:18446744072589146480   DEBUG: Caching image '/storage/emulated/0/Android/data/com.semperpax.spmc17/files/.spmc/addons/plugin.video.elementum/fanart.png' to 'd/d269b093.png':
00:22:49.651 T:18446744072589146480   DEBUG: cached image 'special://masterprofile/Thumbnails/d/d269b093.png' size 3x2
00:22:49.652 T:18446744072589146480   ERROR: Could not encode thumbnail: special://masterprofile/Thumbnails/d/d269b093.png
00:22:49.653 T:18446744072589146480   ERROR: Failed to CreateThumbnailFromSurface for special://masterprofile/Thumbnails/d/d269b093.png
```
?

https://paste.ubuntu.com/p/hkqkYMnQBB/


if I relace fanart.png with different image (e.g. from quasar but converted to png) - everything is fine. 

Could you please change fanart.png to some nice image? :-)

**Comment by elgatito** [comment]
Would appreciate if anyone could make a `fanart` image for Elementum.

**Comment by antonsoroko** [comment]
@elgatito 
can we simply take https://github.com/scakemyer/plugin.video.quasar/blob/master/fanart.jpg
and then change https://github.com/elgatito/plugin.video.elementum/blob/master/addon.xml#L32
to `<fanart>fanart.jpg</fanart>` ? :-)

(convert to png dramatically increase the file size so that's why i don't propose it)
