### ISSUE TITLE
Issue with Trakt lists going to next page

### ISSUE THREAD

**Issue by adamcarter81** [elgatito/plugin.video.elementum#306]
## Expected Behavior
When browsing Lists, My Lists, Custom List name I can view the first page OK (15 items), and when selecting the Next Page  I would expect the next page of films to load.

## Current Behavior
2nd page does not load, instead a notification appears - Elementum: internal server error and the first page remains.

## Steps to Reproduce (for bugs)
1. In Elementum main menu, select Movies, My Movies (Trakt), custom movie list containing more than 15 items
2. Select Next Page
3. Observe error

## Your Environment
Version: 0.68 (latest)
Platform: LibreELEC (Kodi 17.6) on Rasberry Pi3

snip of Kodi.log : https://pastebin.com/wr4paRAX

**Comment by antonsoroko** [comment]
works for me
