### ISSUE TITLE
Does not work with version 67-69(no streams)

### ISSUE THREAD

**Issue by sizzdm** [elgatito/plugin.video.elementum#307]
## Context
Search does not work, no streams. Without a proxy also does not work

## Your Environment
* Version used:
elementum 0.69, burst 0.33
* Environment name and version:
Kodi 17.6
* Operating System and version:
Windows 8.1 x64
* Link to Kodi debug log:
[HTTP PROXY ON](https://paste.kodi.tv/olodiquqom.kodi) 
[HTTP PROXY OFF](https://paste.kodi.tv/vanaqopeti.kodi)

**Comment by elgatito** [comment]
```
WARN: Cannot read TLS response from mitm'd server dial tcp: lookup rutracker.lib: no such host
```
Somehow it was not able to find IP for rutracker.lib.

**Comment by sizzdm** [comment]
> ```
> WARN: Cannot read TLS response from mitm'd server dial tcp: lookup rutracker.lib: no such host
> ```
> Somehow it was not able to find IP for rutracker.lib.


rutracker.org or another also does not work

**Comment by elgatito** [comment]
Please, try v0.0.70.

**Comment by sizzdm** [comment]
> Please, try v0.0.70.


Thank you very much! everything works great!
