### ISSUE TITLE
[Bug] Duplicate settings in Trakt settings

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#308]
There is duplicate in trakt settings:
- Userlist for movies
- Userlist for shows

Does it suppose to be like this?

Image:
![trakt](https://user-images.githubusercontent.com/13424257/50378674-6abdad80-0640-11e9-93e6-21142493aa64.png)

## Your Environment
* Version used: 0.0.70
* Environment name and version: Kodi 17.6
* Operating System and version: Win 10

**Comment by elgatito** [comment]
Selections for adding movies/shows, deleting movies/shows. There are no duplicates.
