### ISSUE TITLE
nil pointer dereference when opening magnet links

### ISSUE THREAD

**Issue by jaydeethree** [elgatito/plugin.video.elementum#31]
## Expected Behavior
Magnet links should work correctly.

## Current Behavior
All Magnet links result in a nil pointer dereference in elementum/bittorrent/service.go

## Steps to Reproduce (for bugs)
1. Set up a provider that will return magnet links
2. Try to open a magnet link from that provider

## Your Environment
* Version used: 0.0.23
* Environment name and version: ARM v7 on a Raspberry Pi 3
* Operating System and version: LibreElec 8.2.2 (Kodi 17.6)
* Link to Kodi debug log: I censored the full Magnet URL from this log, which is why you'll see "XXXX" in some places - https://pastebin.com/FjaCS6pJ

**Comment by elgatito** [comment]
Full log needed, from Kodi start to that error.

**Comment by jaydeethree** [comment]
Full debug log: https://pastebin.com/BvpBZSV3

**Comment by elgatito** [comment]
You set listen address as "ListenAddr:"tun0:8890" and it fails to resolve. 
I will make changes to show that error, but anyway you should change the setting.

**Comment by jaydeethree** [comment]
Thanks! I set the listen interface and outgoing interface in Elementum to 'tun0', which is a valid network interface on my machine that has an IPv4 address. This worked in Quasar and forced it to only send traffic through tun0 and never use any other network interface, such as eth0.

It looks like Quasar is passing in the interface name to libtorrent (https://github.com/scakemyer/quasar/blob/0c92fcf3f75991be07e6b8521ef0ec2b88c8c7b4/bittorrent/service.go#L442), but Elementum is trying to pass in the interface name as the listen address (https://github.com/elgatito/elementum/blob/521e7e5b8af0ecb551202b337ff59a9ae54e6ad4/bittorrent/service.go#L386). So I think this is a bug - Elementum is passing in the interface name, but libtorrent expects an IP address (https://godoc.org/github.com/anacrolix/torrent#Client.ListenAddr).

**Comment by elgatito** [comment]
Please, try with the latest version.

**Comment by elgatito** [comment]
Addon now understands network interfaces, but torrent library now needs a dynamic ListenAddr setters.
