### ISSUE TITLE
[Bug] Play from context menu doesn't work in TV Shows library

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#310]
## The bug
In TV Shows library, when choose "Elementum Play" in the context menu, it raises an error notification with the message: "Elementum - Not Found".

## Expected Behavior
It should run the search and open the results screen as usual.

## Current Behavior
It raises an error notification with the message: "Elementum - Not Found".

## Steps to Reproduce (for bugs)
1. Go to TV Shows library in kodi
2. Stand on an episode
3. Open the context menu and choose "Elementum Play"

**Notes:**
* In the Movies library it's ok without an error.
* The library based on another addon, I'm just trying to run it with the Elementum context menu option.

## Your Environment
* Version used: 0.0.70
* Environment name and version: Kodi 17.6
* Operating System and version: Win10
* Link to Kodi debug log: https://paste.ubuntu.com/p/DdGZVNfjs6/
--- In the log there is example with an episode of the TV Show "Blindspot"
--- In the log there is example with a the movie "Truth or Dare"
--- Focus at this time stamp: 20:54:30.401 T:19152

**Comment by elgatito** [comment]
To search for movie/episode we first need to find it's TMDB id. In case shows were scraped not by TMDB and strm file not generated by Elementum - it will likely fail to find correct TMDB id.

**Comment by burekas7** [comment]
So we actually back to this old issue with TMDB, again.

Most of the the people and other addons are using TVDB or IMDB for tvshows.
But we already discussed a lot on this issue in another issue before.

I'm using The TVDB addon as my tvshows info provider.

If you could put in as a future plan to add additional support also for tvdb for TV Shows it could be nice.

**Comment by antonsoroko** [comment]
maybe it could be ported from https://github.com/scakemyer/plugin.video.quasar/blob/126b5b36982603640ad6b8d041ce208de4cdcfe4/resources/settings.xml#L8

**Comment by elgatito** [comment]
> Most of the the people and other addons are using TVDB or IMDB for tvshows.

I would be much glad if you just you your favourite addons and won't force this addon to be like any other.

**Comment by burekas7** [comment]
I don't understand why you always think I'm against you or something.
I'm not trying to force you to anything. This is not was the purpose of my words. I want to use Elementum, and I'm sure there is a reason why the others are preferring using TVDB.

It would be nice if you could explain from your side why it's a problem (Complexibility in development or something else) instead of just giving an answer like "This is what I want and that's it".
