### ISSUE TITLE
Remembering of torrent choice does not work for magnet links

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/plugin.video.elementum#311]
## Expected Behavior

allow choice caching for tv series episodes if user wants it. 
thanks.

## Current Behavior

choice caching works for movies and items founded by search but not for tv series episodes
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: 0.0.70

* Environment name and version: kodi 18

* Operating System and version: android 8

* Link to Kodi debug log:

**Comment by elgatito** [comment]
We already save selected torrent for episode. And if torrent has another episodes from same season - they will also have that torrent saved.
https://github.com/elgatito/elementum/blob/master/api/shows.go#L796

**Comment by antonsoroko** [comment]
Hmmm, then I guess I faced a bug. Caching of torrent selection works only for movies/search in my Kodi 18 and only for search in my spmc 17. Will try to collect more info and update this issue accordingly.

**Comment by elgatito** [comment]
How you start episode? From Elementum browser? From saved strm file? Any other way?

**Comment by antonsoroko** [comment]
From elementum: series->my lists->list_name->series_name->seasonN->episodeN
or series->my progress->series_name_seasonN_episodeN

проверил: по какой-то причине оно работает только с "отечественными" торент трекерами. рарбг, пиратбей, 1337х - не запоминает. ни фильмы, ни поиск, ни сериалы.

**Comment by elgatito** [comment]
Log file needed with: 
- select item to play
- select torrent
- select save item to play

**Comment by antonsoroko** [comment]
@elgatito 
done 2 times for different trackers https://paste.ubuntu.com/p/hS3GGHstQJ/

**Comment by elgatito** [comment]
Please, use v0.0.71.
Magnets were not saved at all, only torrent files. Now should save all of them.

**Comment by antonsoroko** [comment]
Works like a charm. Thanks!

(кстати рарбг и торент файлы отдаёт, без всяких хитростей. странно что магнетом сделано.)
