### ISSUE TITLE
Research for TV shows saison and not only for episode

### ISSUE THREAD

**Issue by vic1997** [elgatito/plugin.video.elementum#312]
## Expected Behavior
By right clicking on the season of a television series, it looks for the entire season and not for the first episode of the season.

## Current Behavior
For the moment, when we click on "play" in context menu on season it search a torrent for the first episode.

## Possible Solution
Change the search for whole season.

## Your Environment

* Version used: 17.6

* Environment name and version: 0.68

* Operating System and version: Windows 10 64 bits Kodi 17.6

* Link to Kodi debug log:

**Comment by elgatito** [comment]
There is already search for season.
Each provider has own keywords for season search.

Example: https://github.com/elgatito/script.elementum.burst/blob/master/burst/providers/providers.json#L1948

**Comment by vic1997** [comment]
@elgatito So, why when I search for season, it search the first episode ?
When I search for the whole season it search "South Park S18E01" instead of "South Park S18"

I use Yggtorrent precisly

**Comment by elgatito** [comment]
@vic1997 that is because Kodi is automatically adding episode number, because without it, it makes no sense to play "season". In Elementum menu we have custom handle for season, not only episode.

**Comment by vic1997** [comment]
@elgatito ok, so it's impossible. Thanks for response.

**Comment by elgatito** [comment]
From Kodi library yes, Kodi does not start any plugin for season, only for episodes.
