### ISSUE TITLE
Elementum crashes on startup after new install.

### ISSUE THREAD

**Issue by Quentin-Rouquette** [elgatito/plugin.video.elementum#313]
## Expected Behavior

Elementum should be starting.
## Current Behavior

Elementum crashes after install (popup saying "Elementum has crashed, restarting..." on a loop until it gives up).
## Steps to Reproduce (for bugs)

Install elementum on Kodi.

## Context

Install elementum on Kodi.

## Your Environment

* Version used: 0.70

* Environment name and version:  Kodi 17.6

* Operating System and version:  Android TV (7.0)

* Link to Kodi debug log: http://paste.kodi.tv/baqebamuba

**Comment by chivigoku** [comment]
Same problem here.
After installing version 70, it crashes.

Any solution?

thanks

**Comment by elgatito** [comment]
@chivigoku no log = no help.

**Comment by elgatito** [comment]
@Quentin-Rouquette log file shows it tries to start elementum multiple times. Have you updated Android or Kodi before it started to crash?

**Comment by Quentin-Rouquette** [comment]
@elgatito Everything is up-to-date and it's my first time installing Elementum.

**Comment by chivigoku** [comment]
hi @Quentin-Rouquette, you can resolve the issue adding a path in downloads in the settings as per #309

let us know if it works
that worked to me

**Comment by Quentin-Rouquette** [comment]
@chivigoku Yup that worked, didn't think it would be that since it was set to record in RAM.

**Comment by antonsoroko** [comment]
if i am not mistaken elementum still use `download directory` even if you use memory as a storage
like for some torrent related info and for downloading subtitles

maybe it should be stated more clearly in settings (or in documentation http://elementum.surge.sh/getting-started/configuration/ :-) )

**Comment by elgatito** [comment]
I would be thankful if someone could provide log file if getting the issue, described here.

**Comment by elgatito** [comment]
Cannot reproduce this issue even when I remove Elementum's settings with a clean install.

**Comment by elgatito** [comment]
Closing, this should be fixed with latest versions.
