### ISSUE TITLE
Download speed limit not working

### ISSUE THREAD

**Issue by XJIOP** [elgatito/plugin.video.elementum#315]
I tried to set download speed limit to 1024 kB/s and torrents does not start, it stay on 0/0 kB/s downloads with many seeders. Without speed limiting works fine.
Latest kodi and Ementum plugin.

**Comment by elgatito** [comment]
http://elementum.surge.sh/contribute/log/

**Comment by elgatito** [comment]
Thanks for your feedback. 
I have submitted an issue to torrent library - https://github.com/anacrolix/torrent/issues/304

**Comment by elgatito** [comment]
I am closing this issue as we migrate to another torrent engine. See #351
