### ISSUE TITLE
Синхронизация отдельных сезонов в библиотеку

### ISSUE THREAD

**Issue by Chupz0r** [elgatito/plugin.video.elementum#316]
Если я правильно понял, на данный момент с трактом синхронизируется только полностью весь сериал. У меня, например, синхронизируется в библиотеку список просматриваемые в котором есть как сериалы, так и отдельные сезоны сериалов. Сериалы добавляются в библиотеку, а отдельные сезоны других сериалов отсутствуют. Возможно ли реализовать данный момент?

**Comment by elgatito** [comment]
После того как из Trakt добавляется сериал в библиотеку - он обновляется уже по базе Trakt, целиком. 
Делать ограничения по синхронизации отдельных сезонов не вижу смысла. 
К тому же, нумерация серий/сериалов отличается у TMDB/Trakt.

**Comment by elgatito** [comment]
Закрываю. Добавлять отдельно синхронизацию сезонов не буду, сильно усложнит всё.
