### ISSUE TITLE
Проблемы с воспроизведением видео 0.0.67+

### ISSUE THREAD

**Issue by eNdiD** [elgatito/plugin.video.elementum#319]
Приветствую!

Наблюдается проблема с воспроизведением раздач. Особенно актуально для 1080p, но периодически случается и на 720p. Окружение, в котором это все запускается, описано в конце.

Что происходит:

Выбираю раздачу в 1080p около 10Гб в размере. С достаточным кол-вом сидов (50+). Начинаем просмотр. Через некоторое время воспроизведение начинает сильно тормозить. Появляются существенные тормоза с видео/звуком. При этом скорость загрузки хорошая, в районе 5000-7000 кБ/с. При этом, так же может появится сообщение Elementum, что источник слишком медленный. Наблюдается явно высокая нагрузка на ЦП, т.к. интерфейс плеера сильно тормозит. Перемотка и остановка воспроизведения осуществляется крайне медленно, а то и вовсе может привести к зависанию Kodi.

Думал про перегрев и последующий троттлинг, как самое очевидное - но нет. Температура в норме (около 70 градусов), частоты не сбрасываются.

Загрузка осуществляется в память, указано вручную 100 Мб. Та же ситуация наблюдается и с максимальным автоматическим выделением памяти. Всего в устройстве 1 Гб, из которых доступно ~750 Мб. Варианты с использованием файлов отброшены изначально, как нежизнеспособные в моей ситуации.

В остальном, настройки Elementum, напрямую касающиеся загрузки и воспроизведения, оставлены стандартные, за исключением отключенных в Elementum и Elementum Burst во всех местах прокси и DNS, т.к. в моем случае в прокси нет нужды, а гугло-DNS прописаны в маршрутизаторе.

Не могу точно сказать, когда это начало проявляться. На 0.0.63 все было точно в порядке. И, как минимум, вплоть до версии 0.0.66.

Лог прикрепляю.

## Your Environment
* Version used:
Elementum 0.0.70
ELementum Burst 0.0.33

* Environment name and version:
Raspberry Pi 3 B
OSMC 2018.10-1
Kodi 17.6

* Link to Kodi debug log:
[gdrive](https://drive.google.com/open?id=1lE_4cZsGTnvDVkxOLe1nlq1I0_Z90uEI)

**Comment by zynexiz** [comment]
Use English (or at least a translation), no one else understand what you try to say.

**Comment by elgatito** [comment]
Please, use v0.0.71.

**Comment by eNdiD** [comment]
Обновился на 0.0.71. К сожалению, проблема осталась. Новый лог записать?

**Comment by elgatito** [comment]
Да, было бы хорошо.

**Comment by eNdiD** [comment]
https://paste.ubuntu.com/p/JbGJgqhnSp/

Тут запустил фильм с момента последней остановки и остановил когда начали проявляться проблемы

По ходу дела, проверил несколько версий Elementum. С 0.0.64 по 0.0.71 проблема есть. Ниже пока не проверял. Позже попробую остальные.

Тут еще дело в том, что смотрю в основном сериалы. А они в общем-то воспроизводились без проблем, отсюда и сложно сразу выявить, когда же начались проблемы.

**Comment by eNdiD** [comment]
В общем, дело вовсе не в перегреве. Поставил малину в корпус с активным охлаждением. Температура перестала подниматься выше 60. К сожалению, это никак не помогло.

**Comment by elgatito** [comment]
Версии 0.0.* не поддерживаются. Пробуйте последние версии 0.1.*.
