### ISSUE TITLE
Добавить ссылки по настройке elementum на сайт

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/plugin.video.elementum#321]
## Possible Solution

https://www.ixbt.com/live/tv/ekspress-kurs-molodogo-boyca-po-idealnomu-proigryvaniyu-torrentov-napryamuyu-vplot-do-uhd-4k-bdremux-hot-pod-100-gbayt-na-android-boksah-s-amlogic-s912.html
http://4pda.ru/forum/index.php?showtopic=818089&st=5220#entry71708853
https://4pda.ru/forum/index.php?showtopic=772588&st=18140#entry70422583
https://4pda.ru/forum/index.php?showtopic=896840&st=0#entry72334951
https://4pda.ru/forum/index.php?showtopic=647748&st=9120#entry71785391

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

**Comment by zynexiz** [comment]
Don't spam the issue section with crap.

**Comment by antonsoroko** [comment]
@zynexiz 
I am sorry, but who are you to decide what is crap and what is not?
Calm down and behave like an adult please.

**Comment by zynexiz** [comment]
You just posted a bug issue with lots of links to Russian sites. That's defined as spam.

**Comment by antonsoroko** [comment]
I guess you are not capable to do some research before writing. A lot of users of elementum speak Russian or Ukrainian as well as the author of this app.
I don't want to be rude but you force me to. Sorry.
