### ISSUE TITLE
Unfork Elementum on Github

### ISSUE THREAD

**Issue by doko-desuka** [elgatito/plugin.video.elementum#323]
Hi.  
The code search when browsing your repo is disabled. Github doesn't let you do code searches on forked repositories when they have less "stars" (user favorites) than the parent repository.

Your fork is like tons of commits ahead of the original, so you could say it's its own project.

You can ask the Github staff to change ("detach") your repo so it becomes a normal repo and not a fork, and apparently you won't lose any issues or PRs:
https://stackoverflow.com/a/16052845

**Comment by antonsoroko** [comment]
Actually it is a quite good idea.
