### ISSUE TITLE
elementum crashes after fresh install

### ISSUE THREAD

**Issue by nickolayrusev** [elgatito/plugin.video.elementum#324]
elementum can't start after fresh install. 
can't start few times and the last time shows an error "too many crashes" and stops. here is the log file https://paste.kodi.tv/qutaxuloca
Im using latest elementum version on Android tv box (brand is mecool), kodi krypton. if you want additional resources i can give them to you. thanks!

**Comment by elgatito** [comment]
Any chance to run manually binary file: `/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/resources/bin/android_arm/elementum` ? 
Can be done from console. Just to see what errors are there. There is nothing in the log file.

**Comment by georgy-komarov** [comment]
Same for me on Android ARM64. In console it says `/sdcard/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/resources/bin/android_arm64/elementum: can't execute: Permission denied`

**Comment by elgatito** [comment]
@georgy-komarov, probably, your path does not have execute option enabled (not file, whole path). That is why it is executed with `/storage/emulated/0/Android/` instead of `/sdcard/`.

**Comment by chivigoku** [comment]
Morning @nickolayrusev and @georgy-komarov 
I have had the same issue a few days ago.
Here is what you saw #313

In order to solve this, add a patch in downloads option, into the settings

Let us know if worked
Cheers

**Comment by elgatito** [comment]
> In order to solve this, add a patch in downloads option, into the settings. 

what??

**Comment by georgy-komarov** [comment]
@chivigoku, thanks, that really helped. 

Btw, screenshot is not accessible (403 Error).

**Comment by nickolayrusev** [comment]
hi folks, @chivigoku is right-if I set manually download path to different than the default one everything works as expected. We can close the issue so we found out root cause. May be some fix will be applied for future users. thanks all for the support. big thanks to the maintainer of the project. nice job

**Comment by Mohze** [comment]
Hello, 
My Elementum started to crash from no where. I suddenly get that" Elementum crashed ,restarting" 
 and after several times i get "Elementum is still starting up..... message"

I've tried to change the Library path ,torrent files path and download path without any improvement.
I also tried to use different storage type without improvement



[kodi.log](https://github.com/elgatito/plugin.video.elementum/files/2728921/kodi.log)

I've tried to debugging and use pastebin but it does not work because elementum crashes

**Comment by maxx-bachurin** [comment]
> @georgy-komarov, probably, your path does not have execute option enabled (not file, whole path). That is why it is executed with `/storage/emulated/0/Android/` instead of `/sdcard/`.

no, the elementum binary doesn't have the execution bit set and I can't set it on my andriod device, because can't become root.

**Comment by maxx-bachurin** [comment]
> > @georgy-komarov, probably, your path does not have execute option enabled (not file, whole path). That is why it is executed with `/storage/emulated/0/Android/` instead of `/sdcard/`.
> 
> no, the elementum binary doesn't have the execution bit set and I can't set it on my andriod device, because can't become root.

I was able to capture the log from another android device (tv box). please see the log inline:

INFO  main         ▶ main             [0mStarting Elementum daemon
INFO  main         ▶ main             [0mVersion: 0.0.71 GoTorrent: cc531b8c Go: go1.11.4, Threads: 4
INFO  config       ▶ Reload           [0mReloading configuration...
INFO  config       ▶ Reload           [0mSetting remote address to 127.0.0.1:65221
INFO  config       ▶ Reload           [0mUsing download path: .
INFO  config       ▶ Reload           [0mUsing library path: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp/elementum_library
INFO  config       ▶ Reload           [0mUsing torrents path: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp/elementum_torrents
[36mDEBU  config       ▶ Reload           [0mTotal system memory: 2.0 GB
[36mDEBU  config       ▶ Reload           [0mAutomatically selected memory size: 100 MB
[36mDEBU  config       ▶ Reload           [0mUsing configuration: &config.Configuration{
  DownloadPath: ".",
  TorrentsPath: "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp/elementum_torrents",
  LibraryPath: "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp/elementum_library",
  Info: &xbmc.AddonInfo{
    Author: "elgatito",
    Changelog: "",
    Description: "Elementum is a torrent finding and streaming engine. It doesn't go on torrent websites for legal reasons. However, it calls specially crafted add-ons (called providers) that are installed separately.[CR]This project is a fork of the well known, but no longer maintained Pulsar/Quasar projects from steeve and scakemyer.",
    Disclaimer: "The author does not own or host any content found within this Addon. The author is not connected to or in any other way affiliated with Kodi, Team Kodi, or the XBMC Foundation.",
    Fanart: "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/fanart.png",
    Home: "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/",
    Icon: "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/icon.png",
    ID: "plugin.video.elementum",
    Name: "Elementum",
    Path: "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum",
    Profile: "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.elementum/",
    TempPath: "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp/elementum",
    Stars: "-1",
    Summary: "Elementum: Media streaming",
    Type: "xbmc.python.pluginsource",
    Version: "0.0.71",
    Xbmc: "/data/user/0/org.xbmc.kodi/cache/apk/assets/",
  },
  Platform: &xbmc.Platform{
    OS: "android",
    Arch: "arm",
    Version: "3.14.29",
    Kodi: 18,
    Build: "18.0 Git:20190128-d81c34c",
  },
  Language: "en",
  TemporaryPath: "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp/elementum",
  ProfilePath: "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.elementum/",
  HomePath: "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/",
  XbmcPath: "/data/user/0/org.xbmc.kodi/cache/apk/assets/",
  SpoofUserAgent: 0,
  KeepDownloading: 2,
  KeepFilesPlaying: 2,
  KeepFilesFinished: 2,
  UseFanartTv: true,
  DisableBgProgress: false,
  DisableBgProgressPlayback: true,
  ForceUseTrakt: false,
  UseCacheSelection: true,
  UseCacheSearch: true,
  CacheSearchDuration: 180,
  ResultsPerPage: 9,
  EnableOverlayStatus: true,
  SilentStreamStart: false,
  ChooseStreamAuto: false,
  ForceLinkType: false,
  UseOriginalTitle: false,
  AddSpecials: false,
  ShowUnairedSeasons: false,
  ShowUnairedEpisodes: false,
  SmartEpisodeMatch: true,
  LibraryUpdate: 0,
  StrmLanguage: "en",
  LibraryNFOMovies: true,
  LibraryNFOShows: true,
  PlaybackPercent: 85,
  DownloadStorage: 1,
  AutoMemorySize: true,
  AutoMemorySizeStrategy: 1,
  MemorySize: 100233420,
  BufferSize: 20971520,
  KodiBufferSize: 0,
  UploadRateLimit: 0,
  DownloadRateLimit: 0,
  AutoloadTorrents: true,
  LimitAfterBuffering: false,
  ConnectionsLimit: 50,
  ConnTrackerLimit: 0,
  ConnTrackerLimitAuto: true,
  SeedTimeLimit: 2,
  DisableUpload: false,
  DisableDHT: false,
  DisableTCP: false,
  DisableUTP: false,
  DisableUPNP: false,
  EncryptionPolicy: 0,
  ListenPortMin: 6881,
  ListenPortMax: 6891,
  ListenInterfaces: "",
  ListenAutoDetectIP: true,
  ListenAutoDetectPort: true,
  Scrobble: false,
  TraktUsername: "",
  TraktToken: "",
  TraktRefreshToken: "",
  TraktTokenExpiry: 0,
  TraktSyncFrequency: 2,
  TraktSyncCollections: true,
  TraktSyncWatchlist: true,
  TraktSyncUserlists: true,
  TraktSyncWatched: true,
  TraktSyncWatchedBack: true,
  TraktSyncAddedMovies: true,
  TraktSyncAddedMoviesLocation: 0,
  TraktSyncAddedMoviesList: 0,
  TraktSyncAddedShows: true,
  TraktSyncAddedShowsLocation: 0,
  TraktSyncAddedShowsList: 0,
  TraktSyncRemovedMovies: true,
  TraktSyncRemovedMoviesLocation: 0,
  TraktSyncRemovedMoviesList: 0,
  TraktSyncRemovedShows: true,
  TraktSyncRemovedShowsLocation: 0,
  TraktSyncRemovedShowsList: 0,
  TraktProgressUnaired: true,
  TraktProgressSort: 0,
  TraktProgressDateFormat: "yyyy-mm-dd",
  TraktProgressColorDate: "yellow",
  TraktProgressColorShow: "none",
  TraktProgressColorEpisode: "skyblue",
  TraktProgressColorUnaired: "deeppink",
  TraktCalendarsDateFormat: "yyyy-mm-dd",
  TraktCalendarsColorDate: "yellow",
  TraktCalendarsColorShow: "none",
  TraktCalendarsColorEpisode: "skyblue",
  TraktCalendarsColorUnaired: "deeppink",
  UpdateFrequency: 6,
  UpdateDelay: 300,
  UpdateAutoScan: true,
  PlayResume: true,
  TMDBApiKey: "",
  OSDBUser: "",
  OSDBPass: "",
  OSDBLanguage: "en",
  OSDBAutoLanguage: true,
  SortingModeMovies: 2,
  SortingModeShows: 2,
  ResolutionPreferenceMovies: 0,
  ResolutionPreferenceShows: 0,
  PercentageAdditionalSeeders: 25,
  CustomProviderTimeoutEnabled: false,
  CustomProviderTimeout: 30,
  InternalDNSEnabled: true,
  InternalProxyEnabled: true,
  InternalProxyLogging: false,
  AntizapretEnabled: false,
  ProxyURL: "",
  ProxyType: 1,
  ProxyEnabled: false,
  ProxyHost: "",
  ProxyPort: 1080,
  ProxyLogin: "",
  ProxyPassword: "",
  ProxyUseHTTP: true,
  ProxyUseTracker: true,
  ProxyUseDownload: true,
  CompletedMove: false,
  CompletedMoviesPath: "",
  CompletedShowsPath: "",
  LocalOnlyClient: false,
}
INFO  main         ▶ main             [0mAddon: plugin.video.elementum v0.0.71
[36mDEBU  database     ▶ InitSqliteDB     [0mError migrating schema: unable to open database file
[36mDEBU  database     ▶ RestoreBackup    [0mRestoring backup

**Comment by elgatito** [comment]
Closing as this is not active.
