### ISSUE TITLE
Зависания на версиях старше 0.0.46

### ISSUE THREAD

**Issue by Sheicer** [elgatito/plugin.video.elementum#325]
Приветствую.
Имеется приставка MINIX Neo U9-H. При воспроизведении Remux 1080p, через определенное время (10-20 сек) начинает притормаживать видео. В версиях 0.0.46 и младше - все идеально. Буфер в advancedsettings и в elementum - 100 мб. Буферы пробовал разные от 5 до 300мб - не помогло.
Причем если смотреть по роутеру во время воспроизведения то в 0.0.46 скорость всегда около 90-96 Мбит, в версиях старше она колеблется от 65 до 85 Мбит. Проблема только с данной приставкой, с ПК и android на смартфоне проблем нету.
[bundle_2019_1_3_8_10.log](https://github.com/elgatito/plugin.video.elementum/files/2723899/bundle_2019_1_3_8_10.log)

**Comment by elgatito** [comment]
Сделайте лог на последней версии (0.0.71), пожалуйста.

**Comment by Sheicer** [comment]
> Сделайте лог на последней версии (0.0.71), пожалуйста.
Лог который я прикрепил на ней и сделан.

**Comment by elgatito** [comment]
```
11:07:51.575 T:18446744073107667248  NOTICE: [plugin.video.elementum] INFO  main         ▶ main             [0mStarting Elementum daemon
11:07:51.581 T:18446744073107667248  NOTICE: [plugin.video.elementum] INFO  main         ▶ main             [0mVersion: 0.0.59 GoTorrent: 81e6061a Go: go1.10.3
```

Попробуйте удалить файл `/data/data/org.xbmc.kodi/files/plugin.video.elementum/bin/android_arm/elementum` и перезапустить Kodi.

У вас запускается старая версия с диска, хоть и установлена новая.

**Comment by elgatito** [comment]
Всю папка можно удалить смело 
`/data/data/org.xbmc.kodi/files/plugin.video.elementum/bin/`

**Comment by Sheicer** [comment]
Зависание осталось.
[bundle_2019_1_3_14_47.log](https://github.com/elgatito/plugin.video.elementum/files/2724162/bundle_2019_1_3_14_47.log)

**Comment by elgatito** [comment]
Версия уже правильная, но я не вижу момента старта проигрывания и вообще логов от дополнения.
Включайте режим отладки перед воспроизведением ошибки.

**Comment by Sheicer** [comment]
Подскажите как включить режим отладки?

**Comment by Sheicer** [comment]
[bundle_2019_1_3_15_10.log](https://github.com/elgatito/plugin.video.elementum/files/2724241/bundle_2019_1_3_15_10.log)
[kodi.log](https://github.com/elgatito/plugin.video.elementum/files/2724242/kodi.log)

**Comment by Sheicer** [comment]
Посмотрите пожалуйста.

**Comment by elgatito** [comment]
В логах не вижу старта дополнения и не вижу где дополнение стартует проигрывание торрента.

**Comment by elgatito** [comment]
Пробуйте версию 0.1.*. 
Версии 0.0.* не поддерживаются уже.
