### ISSUE TITLE
переименовать "лимит подключений" и "лимит одновременных подключений" или добавить описание в документацию

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/plugin.video.elementum#327]
## Current Behavior

```
лимит подключений = к пирам в рамках одного торрента
лимит одновременных подключений = в целом сетевые подключения созданные библиотекой. к dht в том числе
```
было бы круто куда нибудь описать такого плана опции, типо в http://elementum.surge.sh/getting-started/configuration/
или переименовать эти опции, аля "лимит подключений на один торрент" и "лимит всех сетевых подключений"

спасибо

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

**Comment by elgatito** [comment]
В последних версиях опции были переименованы.
