### ISSUE TITLE
Remove opensubtitles credentials from log during upload

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/plugin.video.elementum#329]
## Current Behavior
OSDBUser and OSDBPass are present in uploaded log file without any obfuscation

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: 0.0.71

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

**Comment by elgatito** [comment]
I can't see where OSDB user is in the log.

**Comment by antonsoroko** [comment]
@elgatito
https://paste.kodi.tv/gowamekaco

**Comment by elgatito** [comment]
Понял, спасибо, лог настроек из конфига. 
В следующей версии будет сокрытие всех паролей из настроек дополнения.

**Comment by antonsoroko** [comment]
Круто, спасибо!
