### ISSUE TITLE
Elementum don't work

### ISSUE THREAD

**Issue by muzena** [elgatito/plugin.video.elementum#33]
## Expected Behavior
Elementum start

## Current Behavior
Elementum simply don't work

## Steps to Reproduce (for bugs)
1. Try to start Elementum

## Your Environment

* Version used:
elementum-0.0.24
* Environment name and version:
Kodi 17.6 Krypton
* Operating System and version:
Linux Mint Cinnamon 18.3 64-bit 
* Link to Kodi debug log:
See https://pastebin.com/TQ9QxGK0

**Comment by tomtomclub** [comment]
yes i now 64 bit linux  pain in the ass , but try quasar works four mi

**Comment by elgatito** [comment]
@muzena , first go to settings and save them. Weren;t you shown the addon settings window after you get an error?

**Comment by elgatito** [comment]
Where did you find this version?

```
[0mVersion: v0.0.1 Go: go1.8.3
```

**Comment by muzena** [comment]
@elgatito 
I compile from source, from instructions in readme file:

git clone https://github.com/elgatito/plugin.video.elementum
cd plugin.video.elementum
git submodule update --init
make

> first go to settings and save them. Weren;t you shown the addon settings window after you get an error?

I try this but don't work.

**Comment by elgatito** [comment]
Documentation is old. It will not work in that way.

**Comment by elgatito** [comment]
Are you sure you do the command from the above? I have tried and it downloads latest binaries from https://github.com/elgatito/elementum-binaries . This build instructions won't build the backend, only collection everything into addon zip files.

**Comment by muzena** [comment]
@elgatito 
I try on clean install Linux Mint 18.03 and Kodi 17.6
now i can start elementum but won't play anything.
And it won't install Brust
Log file:
https://pastebin.com/hiEQSM7H

**Comment by elgatito** [comment]
I dont see your attempt to install Burst or try playing a torrent.

**Comment by muzena** [comment]
@elgatito 
I get these errors when I try playing:
Unable to find any providers.
No links were found.

Now I enabled debugging in Kodi, if this will help.
Debug log:
https://pastebin.com/ZuFS1a7D

**Comment by elgatito** [comment]
Elementum is not searching for torrents. Please, reade the welcome page.

**Comment by muzena** [comment]
After installing Burst it works!

**Comment by slayervamp** [comment]
i'm having this problem i install elementum and burst with latest build but i can get any torrent links
already back and forth to uninstall, clear data, reinstal kodi,instal elementum and burst, but nothing worked just keep get no links were found messege

any advice will be most helpfull

i'm in ATV box Amlogic s905W
