### ISSUE TITLE
Download path not set, check settings

### ISSUE THREAD

**Issue by ssarava9** [elgatito/plugin.video.elementum#330]
I tried Elementum in both windows and Android platform still getting the same error "Download path not set, check settings"

## Expected Behavior
When using Quasar it allows to specify the download path to kodi installed folder like
Android
/sdcard/android/data/org.xbmc.kodi/files

Windows
Any drive can be set as download path as long as its readable

## Current Behavior
In Windows, when i choose the download storage type as files and selected the download path to any place including the default "special://" it throws me the error as "Download path not set, check settings"
If you choose the storage type as memory , it allows to specify any drive as a storage path but the issue is nothing is getting downloaded and stored in the path, i can see the folders created for Movies and Shows
I had also made the download options to continue download and to keep the files after stopped, still the same issue

I'm facing the similar issue in Android platform as well.

## Possible Solution
Elementum is such a great addon and it will be greatly appreciated if the download option can be resolved as im going mad not able to watch movies after downloading

## Steps to Reproduce (for bugs)
1.Go to addon settings
2. Change download storage type to "files"
3. Select the default storage or kodi installation folder where Quasar normally allows to download
4. Change download option to continue and keep the files
5. Click Ok
6. Error getting as "Download path not set, check settings"

## Context
Not able to set any folder for download in both windows and android platform

## Your Environment
* Version used: Latest 0.0.71

* Environment name and version:
Kodi Leia RC 4
* Operating System and version:
Windows 10
Android 7.1

* Link to Kodi debug log:

**Comment by elgatito** [comment]
log file which shows your are trying to set and plugin throws you an error?
http://elementum.surge.sh/contribute/log/

**Comment by ssarava9** [comment]
@elgatito 
Please find below the url

[https://paste.ubuntu.com/p/zKGSb3mtjk/](url)

**Comment by antonsoroko** [comment]
Could be related to #313 and #324

**Comment by ssarava9** [comment]
@antonsoroko i tried both the options to set the download path manually in windows and Android

Windows
C;\temp\elementumdownload\    and also C:\temp\downloads\

Android

\sdcard\Android\data\org.xbmc.kodi\files\downloads\

I'm still getting error as "Download path not set, check settings"
Also tried different combinations and all my entire paths were given read write permission to everyone accessing it so permission not a problem.

Please advise how to resolve this issue as im not able to download any movies to any storage including internal

**Comment by vorkez6** [comment]
Hi,

I have always used this path with Android:

external memory / Android / data / org.xbmc.kodi / files / .Kodi / 
userdata / addon_data / plugin.video.elementum /Film 

My TV box has 64GB of ROM, and has very fast access to these SDRAMs.
This set up has always worked with Quasar, and it works even if you use ELEMENTUM by setting in the "use File" setup ...
Android allows reading / writing only within a folder of the APP / Addon .

**Comment by antonsoroko** [comment]
@ssarava9
You can investigate the issue by looking into log file.

In your log I see
```
09:35:44.782 T:11052  NOTICE: [plugin.video.elementum] INFO  config       ▶ Reload           Using download path: .
09:35:44.783 T:11052  NOTICE: [plugin.video.elementum] INFO  config       ▶ Reload           Using library path: E:\Movies
09:35:44.785 T:11052  NOTICE: [plugin.video.elementum] INFO  config       ▶ Reload           Using torrents path: E:\Movies
```
So there are 2 possibilities:
1) you have not set download path by mistake but set torrent and library path
2) changes made by author (@elgatito) in issues I linked above somehow broke download path configuration and you found a bug

**Comment by ssarava9** [comment]
@vorkez6 tried that path both internally and external drives but still showing the error
I used the same exact folder structure in Quasar and worked perfectly fine , someone pls help
Below is the kodi log 

https://paste.ubuntu.com/p/BxDHq3nynD/

**Comment by ssarava9** [comment]
@antonsoroko you are awesome and correct , download path is broken and seeing in the settings 
Only seeing library path and torrent files path

Attached screenshot 
![fdefade6-abe6-474b-96cb-99143e3c86c4](https://user-images.githubusercontent.com/23267765/50842927-bdcc7b80-1335-11e9-990e-9f47cdfeb50b.jpeg)

**Comment by antonsoroko** [comment]
Can you change "Download path"?

**Comment by vorkez6** [comment]
Exactly, the best speed is reached by using internal memories: "use memory" setup. Using this setup with Android, but for me it does not save movies seen in streaming anymore. can you rehearse and tell me how your TV box behaves? Many thanks

**Comment by antonsoroko** [comment]
@vorkez6 
Use memory means use ram. Thus nothing is saved on disk. Torrent would be downloaded by parts and these parts would be saved in ram.

**Comment by vorkez6** [comment]
hi antonsoroko, so using Elementum with the "USE MEMORY" setup is it normal that no data is saved? 
I'm sorry I'd like to be sure I understood correctly! 
From a message from Elgatito I understood the opposite: ELEMENTUM also saves when it is streaming. 
Are the files saved only by setting the "USE FILES" mode?
 Thank you for your availability and good evening

**Comment by antonsoroko** [comment]
@vorkez6 
>so using Elementum with the "USE MEMORY" setup is it normal that no data is saved?
yes, because it saves torrent pieces into **memory** (memory=RAM, not disk)
>From a message from Elgatito I understood the opposite
which message?
>Are the files saved only by setting the "USE FILES" mode?
yes

**Comment by antonsoroko** [comment]
@ssarava9 
>Another issue i found the download speed is very slow if i select use files option, will it download the entire file before playing ?

no, it will try to download "buffer size" MB (see bittorrent tab in settings).
but where are some bugs about size downloaded
https://github.com/elgatito/plugin.video.elementum/issues/301
and speed
https://github.com/elgatito/plugin.video.elementum/issues/105
https://github.com/elgatito/plugin.video.elementum/issues/199
https://github.com/elgatito/plugin.video.elementum/issues/285
ultimately it is a bug with torrent library - https://github.com/anacrolix/torrent/issues/265 (you can leave some debug info here if you want to facilitate fixing of this bug)

**Comment by antonsoroko** [comment]
@ssarava9 @vorkez6 
by the way, guys feel free to use search in this repo - you will find answers to almost all general question in open/closed issues :-)

good luck!

**Comment by elgatito** [comment]
@ssarava9 your log says plugin can't remove lockfile, due to access denied error.

```
09:12:44.477 T:11052   ERROR: [plugin.video.elementum] WindowsError(5, 'Access is denied')
09:12:44.477 T:11052 WARNING: [plugin.video.elementum] Removing library.db.lock file...
09:12:44.477 T:11052   ERROR: [plugin.video.elementum] WindowsError(2, 'The system cannot find the file specified')
```

It should be somewhere like C:\Users\SSARA\AppData\Roaming\Kodi\userdata\plugin.video.elementum\

You can try to delete it manually and then restart Kodi.

**Comment by vorkez6** [comment]
@Elgatito 
I'm sorry I misunderstood me, everything works fine!
Many thanks

**Comment by ssarava9** [comment]
we can close this issue as my original problem resolved, thanks everyone for your suggestions

**Comment by elgatito** [comment]
So what did you do?

**Comment by antonsoroko** [comment]
@elgatito
I guess some UX changes could be made (e.g. make default path visible) to avoid such kind of problems. Anyway it is up to you. Thanks.

**Comment by antonsoroko** [comment]
He thought that  "Download path" is a header for torrent and library path.
Default path '.' did not work for him (not sure what is considered as current directory).

**Comment by elgatito** [comment]
@antonsoroko 
>e.g. make default path visible

There is no hidden default path. Download Path by default is "current directory", which is determined by Kodi (in terms of unix it's `.` or `pwd`). 

If issue is caused by DownloadPath setting, not Torrents or Library path, and only on Android - then probably Kodi handles that path in a different way. 
Anyway, that path is not used when using memory storage, and there is no fatal error or panic or whatever, it looks like process was killed. 

If anyone, who have errors with default download path, could test custom binary on Android with default config (deleting settings.xml inside of plugin.video.elementum directory) - it would help.

**Comment by elgatito** [comment]
@antonsoroko 

> Default path '.' did not work for him (not sure what is considered as current directory).

Again, there is no requirement for "Download path", when using memory storage, it's not even writing warnings if using memory storage. Even if you write there non-existent path - it will even not check if it's existing, because that is memory storage.

**Comment by antonsoroko** [comment]
@elgatito
I guess you misunderstood something.
Author of the issue use files. Please see his steps to reproduce and his screenshot.

**Comment by ssarava9** [comment]
i made a mistake of not setting the download path thinking it doesnt exist, the lable "Download path" looks  like a heading and i moved to library path and torrent path, which resulted in error
Now i realised Download path line is editable and specified my storage to it
Request to add "..." next to download path label so its not confused with header or give a temp path by default
