### ISSUE TITLE
"Watched in Trakt" for folder

### ISSUE THREAD

**Issue by mohamedali-demo** [elgatito/plugin.video.elementum#334]
Hi,
I've recently installed elementum, moving over from Neptune rising. I found one key setting missing: the option to set an entire season to "watched in Trakt". When I right click, the option isn't there 

Now, I thought the workaround would be to go into the folder and set every episode to "watched in Trakt", but that doesn't automatically update the parent "season" folder.

This means I have no idea if a new episode has been released yet, I have to go into each of my shows, and check it individually to see if a new one is released. With Neptune, I could just look at the list of tv shows and I could tell, if it has a tick, it means they've all been watched.... But no such ability here.

Can you please add this small bit of functionality? It would make the world of difference.

Much appreciated.

**Comment by elgatito** [comment]
You mean when you browse shows in Elementum and enter some, you see seasons list there, so you want a context menu item to mark as completed season in Trakt?

**Comment by mohamedali-demo** [comment]
Yes exactly. A way to mark a season as watched in Trakt.

In addition, when I mark each individual episode as watched, it doesn't
roll-up automatically to mark the season as watched.

Thanks

**Comment by elgatito** [comment]
@mohamedali-demo "Set as watched" in context menu is added by Kodi and makes Kodi to change watched status internally, it's not linked to Trakt at all.

**Comment by mohamedali-demo** [comment]
So how come when I use Neptune rising the 'set as watched in trakt' works,
however with elementum it does not?

Also, why is there a 'specials' folder with 80% of my tv shows, that
contain nothing I can watch..?again this does not appear in Neptune rising.

Perhaps try testing it to verify my defect. It's a very simple test, just
connect trakt and you'll see there is absolutely no way to set a tv show as
'watched'.

I have no idea what has new episodes, what I'm up to date on, or anything.
I have to go into Neptune rising first, check what new episodes are
available, and then come back into elementum to watch it....

**Comment by elgatito** [comment]
> Perhaps try testing it to verify my defect. It's a very simple test, just connect trakt and you'll see there is absolutely no way to set a tv show as 'watched'.

There is no such functionality in Elementum. If you set something as watched in Kodi - it will set as watched in Trakt after sync is done and if you have enabled sync back watched status.

Elementum does not have explicit "set as watched in Trakt" actions.

**Comment by mohamedali-demo** [comment]
Classic.... System testing without integration testing.

Whatever it is, how do I set a tv show in the "my tv shows" part of
elementum as watched? Elementum doesn't support this functionality??

**Comment by antonsoroko** [comment]
@elgatito
Btw, I aslo use modified version of quasar that has this feature, maybe you can backport it
https://github.com/charly3pins/quasar/commit/2d9d54abd729f884faafded5e2d4ce01a519493a

Thanks.


@mohamedali-demo 
I my environment elementum marks episodes as watched in trakt as soon as i watched them. You may want to check your trakt-related settings.
Also i do not really unfetstand your issue with new episodes - i just go to "my progress" and all new episodes are there.

**Comment by mohamedali-demo** [comment]
I can't manualky set it as watched , I have to actually watch it.

I can't just "right click" and set as watched.

In Neptune rising I can set an entire season as watched by just right
clicking and selecting watched.

Not sure why this option doesn't work?

**Comment by antonsoroko** [comment]
Okay, i see. In this case as an temporary option i can offer you to do this on trakt.tv website or in some app (i use cathode android app). Also there is a new and promising app called wako - https://github.com/JumBay/wako (it has ios version if needed) that also gives you ability to control elementum fron your phone
initially i used website.
