### ISSUE TITLE
[Request] add the option "back in time"

### ISSUE THREAD

**Issue by johndoe71rus** [elgatito/plugin.video.elementum#335]
add the option "back in time" for the option "continue playback at <time>".
Subtract the number of seconds from the playback position saved.

**Comment by pavelmxx** [comment]
I am using script.xbmc.unpausejumpback addon of that. After video starts I pause then unpause playback for jump back for 10 seconds. Jump back works every time when I unpause playback. That is the best and quickest way to rewind for me.

**Comment by elgatito** [comment]
@johndoe71rus I don't understand this issue.

**Comment by pavelmxx** [comment]
Я так понял, что он хочет иметь возможность при продолжении просмотра видео, остановленном на 50:00, продолжать воспроизведение с 49:30, например. Как дополнение опции к <setting id="play_resume" value="true" /> в секундах.

**Comment by johndoe71rus** [comment]
да. Именно так. сделать настраиваемый интервал, максимум 30 секунд.

**Comment by elgatito** [comment]
Option added to 0.1.23.

**Comment by antonsoroko** [comment]
@elgatito
У меня не работает фича, проверял напрямую из списка торрентов. Опция "принудительно продолжить с..." тоже не работает или означает что-то другое.

https://paste.ubuntu.com/p/HNdrxc766n/

Спасибо.

**Comment by johndoe71rus** [comment]
у меня опция "принудительно продолжить с..." работает. Правда был случай воспользоваться только на 0.0.х ветке. Выглядит так:
если есть не просмотренный эпизод, по клику открывается меню из 2 пунктов, "продолжить с время" и "начать с начала". Пункт продолжить никак не действует, просто меню закрывается.
Начать сначала запускает закачку и воспроизведение, в самом начале стопит и проматывает на время.

**Comment by elgatito** [comment]
@antonsoroko 
> У меня не работает фича, проверял напрямую из списка торрентов. Опция "принудительно продолжить с..." тоже не работает или означает что-то другое.

Это так не работает. 
Продолжением просмотра управляет Коди. Если проигрывается что-то из библиотеки, то дополнение пытается само продолжить проигрывание. Во всех остальных ситуациях место остановки знает только Коди.

**Comment by antonsoroko** [comment]
@elgatito
Правильно ли я понимаю, что чтобы функция отмотки назад на Н минут заработала надо добавить контент из elementum в библиотеку коди? Напрямую из elementum эта функция работать не должна, так?

Спасибо.

**Comment by elgatito** [comment]
@antonsoroko 

> Правильно ли я понимаю, что чтобы функция отмотки назад на Н минут заработала надо добавить контент из elementum в библиотеку коди? 

Да, чтоб сделать поправку на возврат времени нужно узнать сколько уже прошло, а это можно узнать только по записям в библиотеке Коди.

> Напрямую из elementum эта функция работать не должна, так?

Поправку и перемотку делает или Коди (если отключено принудительная перемотка), или дополнение, если знает куда мотать.
