### ISSUE TITLE
Trakt "liked" lists - where to find them in elementum?

### ISSUE THREAD

**Issue by john3voltas** [elgatito/plugin.video.elementum#336]
Hi @elgatito .
Have been using elementum for at least an year now and it still rocks.
Quick question about trakt "liked" lists. Don't exactly know if this issue is somehow related to #303 .
I have "liked" a couple of lists from other trakt users. Mainly movie's lists.
Is there a place where I can find those lists under elementum? If so, can you please describe how/where?
BTW, I have authorized my trakt account in elementum and I can see my collection/watchlists just fine. Just don't know where to find other user's lists that I have liked in trakt website.
Thanks in advance.
Cheers

**Comment by pavelmxx** [comment]
I think, the only way to get list of another user, is to buy Trakt VIP and use CLONE function to copy into your PERSONAL LISTS. Liked lists is only for likes. I can be wrong, correct me if it so.

**Comment by john3voltas** [comment]
> 
> 
> I think, the only way to get list of another user, is to buy Trakt VIP and use CLONE function to copy into your PERSONAL LISTS. Liked lists is only for likes. I can be wrong, correct me if it so.

I'm not sure but I think you're wrong. I just opened Exodus and opened "My Movies > Lists" and there it is, my "liked" list.

**Comment by john3voltas** [comment]
Oh man... :disappointed: 
That's a bummer. You didn't implement it because you didn't find it useful? Or was it just because it was going to be a lot of work to get it done?
If implementing it doesn't represent a lot of work, could I ask you to put it on the bottom of your to-do list? You know, that kind of stuff that you're feeling bored, don't have anything else to do on a rainy/snowy day and you say "well, nothing to do here but I could add "liked" trakt lists to Elementum just to kill some time". :grin: 
Thanks mate.
Cheers

**Comment by elgatito** [comment]
@john3voltas 

> Or maybe you can add this list to the popular lists that you already feature in the addon.
> trakt link to list

Bad thing is that this only applies to english (original) torrents, not helpful for countries that wait for localized version.

**Comment by john3voltas** [comment]
> Bad thing is that this only applies to english (original) torrents, not helpful for countries that wait for localized version.

Yep, I understand.
I guess that means this is a dead-end and we will never get this kind of feature.
Thanks anyways.

**Comment by elgatito** [comment]
@john3voltas have good news for you.

1) Added "Liked" lists to "My collections", they are now added to that list.
2) Added functionality to add collections to main menu.

How to:
- Go to any collections list. "My collections" or Popular lists (list of most liked/used collections).
- Context menu -> Add to start menu.
- Go to start menu and you see that collection always there.
- To unpin collections - Context menu - Remove from start menu.

You can add as many as you like.
Works for Movies and Shows.
