### ISSUE TITLE
Set as Watched / Просмотренное

### ISSUE THREAD

**Issue by gekatvbox** [elgatito/plugin.video.elementum#337]
Здравствуй.

Суть проблемы:
1. На сайте тракта, в приложении помечаю фильмы как Просмотренные, Watched. 
2. В настройках элементума стоит полная синхронизация.
3. Захожу в библиотеку(в коди) movies/tvshows, папка история - ничего. 

Все остальные листы, watchlist, collections сразу синхронизируются и создают соответственную базу. 
То-есть 12 отмеченных фильмов в watchlist, синхронизируются сразу, и создают соответствующие файлы в библиотеке коди. А 18 отмеченных как watched - нет.

Когда я отмечаю как watched в самом Коди, уже синхронизированный фильм с trakt.tv, он переходит в раздел history в коди, и так же обратно синхронизируется с тракт и тоже помечяеться как watched. Но при этом остаеться в библиотеке Коди.

Вывод: не работает синхронизация 
trakt.tv | watched -> Kodi library.
Обратная схема работает.

Проверял на Коди 17.6 / 18
Android TV / shield tv

**Comment by elgatito** [comment]
> Sync watched states from Trakt into Kodi library

Синхронизация статуса просмотренного на библиотеку Коди. Если что-то отметить как просмотренное и оно есть в библиотеке - статус изменится.

> А возможность это сделать есть?
Возможность есть, но я не буду это делать. Смысл просмотренного в учёте статуса, а не ведения библиотеки.

**Comment by gekatvbox** [comment]
Понял. 
Спасибо, закрывай. Остальное все работает.)
