### ISSUE TITLE
Doesn't work with proxy settings enabled

### ISSUE THREAD

**Issue by hoshsadiq** [elgatito/plugin.video.elementum#34]
Logs here: https://paste.ee/p/z8syV

Edit: actually it's because of the proxy settings. When I disable it, it works fine.

**Comment by elgatito** [comment]
What proxy settings? Torrent library, used in Elementum does not support proxies.

**Comment by hoshsadiq** [comment]
Proxy settings on Kodi

**Comment by elgatito** [comment]
Proxies are not supported for network connections. Not sure, will it work or not, if you set vpn Interface in Elementum's settings.

**Comment by hoshsadiq** [comment]
Elementum has VPN settings? I've not seen these.

**Comment by elgatito** [comment]
VPN is what your system should configure, not addon. If you create VPN network on device, you can try using that interface with addon.

**Comment by hoshsadiq** [comment]
If I create a VPN connection on the system, it works fine. However, I'd like to be able to enable the proxy settings inside Kodi and have it work. This is the thing that doesn't work

**Comment by elgatito** [comment]
There is already an issue in the corresponding repository: https://github.com/anacrolix/torrent/issues/160
There is nothing I can help with.

**Comment by hoshsadiq** [comment]
Aah I see. Cool no worries.

**Comment by elgatito** [comment]
@hoshsadiq Proxy is added to Elementum in the latest versions.

**Comment by hoshsadiq** [comment]
That's awesome! Thank you so much for this!!!
