### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by riegaz** [elgatito/plugin.video.elementum#340]
While playing a 1080p movie I see the used memory increasing by 10Mb / 5 minutes. I kept all the standard settings except that I don't keep any torrent files saved locally.

Does anyone see this slow increase of memory?

**Comment by elgatito** [comment]
Log / platform / evidence / information? At least something?

**Comment by riegaz** [comment]
Sorry, I do have a amlogic s905 and therefore I'm using the arm-7 version. When watching a 1080p movie and watching the memory consumption in "top" it increases constantly until my box crashes.

How do I provide a log?

**Comment by elgatito** [comment]
This issue will not be tracked, while we are in migration to libtorrent engine. 
You can try test versions if you like. #351
