### ISSUE TITLE
 Баг с постоянной синхронизацией в history (просмотренные) trakt из kodi на android устройствах.

### ISSUE THREAD

**Issue by pavelmxx** [elgatito/plugin.video.elementum#341]
Есть профиль kodi, в котором в настройках elementum раздела trakt ВЫКЛЮЧЕНО все, кроме "синхронизировать user lists из trakt в библиотеку". На windows все отлично. Но когда этот профиль кладешь на андроид устройство, то раздел HISTORY (просмотренные) в trakt начинает наполняться по мере просмотра фильмов и сериалов. В настройках elementum все без изменений, т.е. включен только один пункт "user lists из trakt ". Проверял на двух разных андроид устройствах.
Кусочек конфига elementum с андроид устройства:
```
    <setting id="trakt_sync_userlists" value="true" />
    <setting id="trakt_sync_watched" value="false" />
    <setting id="trakt_sync_watchedback" value="false" />
    <setting id="trakt_sync_watchlist" value="false" />
```
Progress в trakt тоже наполняется сериалами.

**Comment by pavelmxx** [comment]
Никак не удается воспроизвести баг. Изменил в настройках elementum "частота синхронизации списков trakt" на 1 час. Включаю короткие 20-минутные мультсериалы. Но он, видимо, делает это в какое-то другое время. Наверняка завтра добавит в trakt. Главное заметить, и лог забрать вовремя. За прошлые 2 дня он 3 фильма добавил в просмотренные trakt, сейчас не хочет на тех же устройствах. Кнопка в настройках "обновить trakt" результатов не приносит. И как-то селективно у него это происходит, как я заметил. Добавляет в просмотренные не все фильмы, через раз, что ли. Напомню, что смысл в том, что я ВСЮ синхронизацию хочу выключить, а оставить только пользовательские списки. А он профиль trakt загаживает без моего согласия. В первый раз месяц назад нашел несколько десятков фильмов и просмотренных, удалил, на днях заметил, что снова наполняет. И судя по репертуару, исключительно с андроид устройств. Попытаюсь половить баг еще пару дней.

**Comment by elgatito** [comment]
> Напомню, что смысл в том, что я ВСЮ синхронизацию хочу выключить, а оставить только пользовательские списки. 

Лог нужен.

**Comment by pavelmxx** [comment]
Поймал баг. Воспроизводить надо видео из меню elementum, из "списка популярных", например, может и из поиска. И это видео НЕ должно быть включено в библиотеку. Если в библиотеке этого фильма нет, то после просмотра сразу же летит в trakt "просмотренное". Если есть в библиотеке, то не летит ни при каких обстоятельствах. Глюк, оказывается, не только на андроиде, но и на windows, короче - везде. На винде только библиотекой пользуюсь, а на андроиде поиском, и то иногда. Поэтому сначала ошибся в суждениях.
Добавил серию Simpsons из 23 сезона. Лог:
[https://pastebin.com/vKLkQXCb](https://pastebin.com/vKLkQXCb)

**Comment by elgatito** [comment]
@pavelmxx попробуйте с последней версией Elementum, будет ли такая же ошибка в работе.

**Comment by elgatito** [comment]
Closing without response.
