### ISSUE TITLE
[Request] Create a simple UI to see torrent's download progress

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/plugin.video.elementum#343]
## Expected Behavior

would be nice have torrent's download progress (pieces map) - it would also help with performance troubleshooting
if https://github.com/anacrolix/torrent/issues/309 will be implemented this feature could help to see if everythning works as supposed to

thanks!

## Possible Solution

![_059](https://user-images.githubusercontent.com/17964763/51620020-97682c00-1f42-11e9-9cdb-33f04059f988.png)
i guess some code could be borrowed from https://github.com/YouROK/TorrServer

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

**Comment by elgatito** [comment]
@antonsoroko http://ip:65220/info shows pieces progress.

**Comment by antonsoroko** [comment]
Did not know about this endpoint.
Looks funny but useful, thank you.
The only thing if you have hundreds of torrents it is a very big page to look at :-)
But for troubleshooting purposes should be enough.
Thank you!

**Comment by antonsoroko** [comment]
fixed by #740

**Comment by antonsoroko** [comment]
fixed by #740
