### ISSUE TITLE
Missed data in the shows->genres category. В меню Сериалы->Жанры отсутствует содержимое

### ISSUE THREAD

**Issue by vporoxnenko** [elgatito/plugin.video.elementum#344]
works until 71 release

**Comment by elgatito** [comment]
Можете очистить кеш дополнения (из настроек дополнения). Проблем с жанрами не вижу в последней версии, да и не было там никаких изменений. Могло сохраниться неправильно.

**Comment by vporoxnenko** [comment]
проверил на коме
стояла версия 0.0.55, в сериалах были жанры(именно в сериалах)
обновил до 71, пропали. У Юры такая же фигня на новой установке
кэш чистил

поигрался с разными версиями в 63 есть, в 64 пропали
проверено на линь х64, коди 17.6 и ведроид арм, коди 16.1

кусок лога
после 22:41:49.808 открыл жанры

22:41:49.021 T:139887932065536  NOTICE: [plugin.video.elementum] [GIN]
2019/02/03 - 19:41:49 | 200 |     722.931µs |       127.0.0.1 | GET
  /shows/
22:41:49.808 T:139887260976896   ERROR: Could not encode thumbnail:
special://masterprofile/Thumbnails/8/8fffe9df.png
22:41:49.808 T:139887260976896   ERROR: Failed to
CreateThumbnailFromSurface for
special://masterprofile/Thumbnails/8/8fffe9df.png
22:42:18.596 T:139887932065536  NOTICE: [plugin.video.elementum]
 [31mERRO  tmdb         ▶ func1             [0mBad status getting show
genres with map[api_key:[29a551a65eef108dd01b46e27eb0554a]
language:[en]] on https://api.themoviedb.org/3/search/movie: 422
22:42:18.596 T:139887932065536  NOTICE: [plugin.video.elementum] [GIN]
2019/02/03 - 19:42:18 | 200 |  601.023352ms |       127.0.0.1 | GET
  /shows/genres


не получилось вытащить жанры из тмдб

вот лог из 63 версии
22:59:24.541 T:139886641547008  NOTICE: [plugin.video.elementum] [GIN]
2019/02/03 - 19:59:24 | 200 |     523.314µs |       127.0.0.1 | GET
  /shows/genres
22:59:25.408 T:139887286155008   ERROR: Could not encode thumbnail:
special://masterprofile/Thumbnails/8/8fffe9df.png
22:59:25.408 T:139887286155008   ERROR: Failed to
CreateThumbnailFromSurface for
special://masterprofile/Thumbnails/8/8fffe9df.png

03.02.2019, Denis<notifications@github.com> написал(а):
> Можете очистить кеш дополнения (из настроек дополнения). Проблем с жанрами
> не вижу в последней версии, да и не было там никаких изменений. Могло
> сохраниться неправильно.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/elgatito/plugin.video.elementum/issues/344#issuecomment-460041375


-- 
Regards,
Valentin A. Poroxnenko

**Comment by vporoxnenko** [comment]
сделал полный диф по каталогам, не считая всяких ридми, отличается /resources/bin/linux_x64/elementum

**Comment by vporoxnenko** [comment]
К сожалению петон и ГО не мои языки, ИДЕ нету, а в блокноте тяжело ковыряться в чужом коде

но, полагаю, где-то здесь бага 
https://github.com/elgatito/elementum/commit/69c867c24a5469ff345b741d21b518b2ef5a97a2
https://github.com/elgatito/elementum/commit/1281d34ad132cda9318375c4412510464e192e1a

**Comment by elgatito** [comment]
@vporoxnenko Не, этот код не о том. Но упоминание о том что это только в сериалах, помогло, нашел и поправил вызов, но пока только в тестовые версии дополнения пойдут правки.

**Comment by vporoxnenko** [comment]
*thumb up* жду релиза

04.02.2019, Denis<notifications@github.com> написал(а):
> @vporoxnenko Не, этот код не о том. Но упоминание о том что это только в
> сериалах, помогло, нашел и поправил вызов, но пока только в тестовые версии
> дополнения пойдут правки.
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/elgatito/plugin.video.elementum/issues/344#issuecomment-460089069


-- 
Regards,
Valentin A. Poroxnenko

**Comment by elgatito** [comment]
Fixed in 0.1.* versions.
