### ISSUE TITLE
Better UX for torrent file opening.

### ISSUE THREAD

**Issue by vporoxnenko** [elgatito/plugin.video.elementum#345]
Add torrent by link/file is not easy to use, perhaps it would be better to separate em.

Запускать торрент по ссылке или файла не очень удобно. Мне кажется имеет смысл разделить на отдельные пункты. Сейчас чтобы открыть локальный файл необходимо вызвать "добавиь торрент", тыкнуть "файл", провалиться в корень хранилища. Если сделать меню "загрузить файл" по которому сразу открывать хранилише и запоминать крайний каталог, всё будет гораздо оперативнее. К сожалению я не питонист, иначе был бы PR ))

**Comment by antonsoroko** [comment]
Could this be a dublicate of https://github.com/elgatito/plugin.video.elementum/issues/291 ?

**Comment by elgatito** [comment]
Чем не подходит веб страница?

Питон в этом дополнении не используется почти.

**Comment by vporoxnenko** [comment]
> Could this be a dublicate of #291 ?

да, дубль

**Comment by vporoxnenko** [comment]
> Чем не подходит веб страница?
в смысле админка?
 
> Питон в этом дополнении не используется почти.
у меня жаба головного мозга, ни на чём больше не умею (
