### ISSUE TITLE
How can I donate this project?

### ISSUE THREAD

**Issue by vporoxnenko** [elgatito/plugin.video.elementum#346]
subj

**Comment by elgatito** [comment]
I have created the page - http://elementum.surge.sh/donate/

**Comment by vporoxnenko** [comment]
пайпал по польски пишет :D
боюсь не все разберутся

![image](https://user-images.githubusercontent.com/578489/51968225-72177880-2482-11e9-9f87-8f2d589a6531.png)

**Comment by vporoxnenko** [comment]
прямой перевод через ПаПал норм,а по реквизитам карты заставляет заполнять слишком много инфы, у них вроде был элемент, чтобы провести платёж без ввода домашнего адреса и группы крови

**Comment by elgatito** [comment]
@vporoxnenko А сейчас язык нормально выводит после перехода?
Спасибо за донат.

**Comment by vporoxnenko** [comment]
по-английски
