### ISSUE TITLE
Elementum crashing in Kodi in firestick

### ISSUE THREAD

**Issue by ashoktvm** [elgatito/plugin.video.elementum#347]
Elementum crashing after installing in Kodi in firestick 4k. It crashed even after restarting Kodi and even firestick. Any workaround or is it a known issue?

**Comment by elgatito** [comment]
Try to change library path in elementum settings.
Log file needed: http://elementum.surge.sh/contribute/log/

**Comment by ashoktvm** [comment]
It worked. Thanks

**Comment by ashoktvm** [comment]
The thing is the download speed is not as good as Quasar. Why is that? Is there any setting I can change to make it download faster?

**Comment by elgatito** [comment]
@ashoktvm if you want to use file for downloading - use github search.

**Comment by ashoktvm** [comment]
I meant the file fownloaded through quasar is much faster than the file downloaded using Elementum

**Comment by antonsoroko** [comment]
@ashoktvm

author meant that you can use search feature in github to find the answer to your question. this question was asked and answered several times.

btw there is new engine coming - https://github.com/elgatito/plugin.video.elementum/issues/351 and you can participate in testing.
