### ISSUE TITLE
Adding movie scraper

### ISSUE THREAD

**Issue by syneox** [elgatito/plugin.video.elementum#35]
When I search for content in Movies section of Elementum, I can see rating of a movie grabbed from themoviedb.org.

When I go to Trakt section of Elementum and find same movie, rating is grabbed from trakt.tv.

Information provider is The Movie Database add-on and imdb is set as default rating option.
Elementum setting for TV Show scraper is TheMovieDB.

It may not be Elementum related but it will be nice to override this and just use imdb.com ratings as they are still the most credible source.

This may be fixed maybe with installing Universal Movie Scraper and adding it as an option inside Elementum settings. I have tried it but it doesn't appear in scraper list.

**Comment by elgatito** [comment]
It does not work as you think it does.

When you install scraper to Kodi and add movies - they are scraped once and stored in the database, and all depends on the scraper, they can do what they want.

When you browse movies/shows in the plugin directory - we request those lists from TMDB and send request for each movie/show and can use rating, provided by TMDB.

When you choose scraper name in plugin settings - you define which title to use, so the Kodi's scraper will 100% find the movie/show correctly. 

Adding more requests to external services will make browsing slower.

**Comment by syneox** [comment]
I understand now, thanks for explanation.
