### ISSUE TITLE
Torrents are never moved in specific folders, even if they're "finished" and not playing

### ISSUE THREAD

**Issue by Qualinost1** [elgatito/plugin.video.elementum#350]
Hi, me again ;)
Would love that elementum add automatically torrents that I want to keep in my kodi library. Thought it was possible to achieve this with the option "Move downloads in distinct folders" for my films and TV shows and by adding those two folders as video source in kodi. But even if the torrents are in state finished (so not seeding) and the video is not playing the files are never moved. I tried to reboot kodi, but nothing.
Is there something I missed? What should I do to achieve what I want to do?

**Comment by Qualinost1** [comment]
I always use file storage to be able to keep files that I want to re watch later or to share with friends.
Here is a full log, I just erased all my proxy infos. (Maybe it could be usefull to don't let all the accounts infos in clear in the log?)
https://paste.ubuntu.com/p/9yS6WDCbnj/

**Comment by elgatito** [comment]
@Qualinost1 I don't see in the log where you finish watching something that is fully downloaded and it has to be moved.

**Comment by elgatito** [comment]
Please, try this in 0.1.23.

**Comment by elgatito** [comment]
Please, check the issue with the latest version, or I will have to close the issue.

**Comment by elgatito** [comment]
Closing without getting response.
Branch 0.0.* is not supported now.
