### ISSUE TITLE
Impossible to install Elementum on T95K Pro

### ISSUE THREAD

**Issue by LodocArt** [elgatito/plugin.video.elementum#352]
Hello everyone ! Since Kodi updated to Leia, my addons like Quasar or Autosub were not working anymore, crashing as I started them ! I've tried to reinstall them or remove Kodi, installed Jarvis and Krypton, resetting the android box, but I just simply cannot install any addo. When I try to install Elementum it says it installed successfully, but then tries to launch it, the app crashes, then restart, crashes, before saying to me "Crashed to many times, aborting..."
My logs are filled, so I don't have any more informations :c

### Your Environment
Used Operating system:

* [ ]  Android
* Operating system version/name:
  Android Marshmallow, Kodi Leia

PS : I've just tested it with Windows, with the latest release of Kodi and Elementum and it works without any problem, must be an Android problem D:

**Comment by elgatito** [comment]
Log file is needed if you expect some help.

**Comment by guglicap** [comment]
Hey, I had the same issue on my device, if it is a fresh install, go into the add-on settings and set the Download and Library path (Library was already set in my case). That should fix it. Also, @elgatito should I open a new issue for this or can we use this one? Steps to reproduce are simply installing the add-on from scratch on Kodi 18, on Android.

**Comment by LodocArt** [comment]
@elgatito I'm trying to get a log file, but when going to Event Log, I have the message "Elementum, Installation Failed", and when clicking it I've just the Install option, nothing more detailled :(
@guglicap I'm trying to find the Download option, where is it ? Thank you so much for your help ! :D

**Comment by elgatito** [comment]
@LodocArt go to Elementum addon settings in Kodi, first tab, Library path option.

**Comment by LodocArt** [comment]
I did set the Download Path, but it just said the addon was booting... A popup offered me to install Burst, but it failed to install..
Where is the option to have a extended log file ?

**Comment by elgatito** [comment]
@LodocArt It's not the Download path. Change the Library path. It is not empty, but change to existing directory.

**Comment by LodocArt** [comment]
I've changed the library and torrent path, and I can access Elementum, and even install Burst (after some random kodi crashes) ! 
But now Burst cannot find any links for some tv show, even adding lots of providers. In the log files i've seen some ConnectionError ! In the line 1017 it returns me 6 links, and displays it perfectly, but in 1204 it returns me lots of errors...
[kodi.log](https://github.com/elgatito/plugin.video.elementum/files/2922291/kodi.log)

**Comment by elgatito** [comment]
@LodocArt you can try to disable internal HTTP proxy in Elementum settings. There is something with websites connectivity.
