### ISSUE TITLE
TMDB invalid api key

### ISSUE THREAD

**Issue by gello0** [elgatito/plugin.video.elementum#353]
## Expected Behavior

TV shows should show episodes and seasons when clicked on a specific Show. When using search TV shows the Title should be shown
## Current Behavior

Only loading for half second and then nothing happens. Same with TV Show search and information. Same behavior in web UI
## Possible Solution

Add an alternative database  
## Steps to Reproduce (for bugs)

1.Search for tv show 

## Context

Im not able to view any TV shows using quasar.
## Your Environment

* Version used:0.0.66 to 0.1.7

* Environment name and version: 17 & 18

* Operating System and version:Android TV 5.0.1, Ubuntu 18.04

* Link to Kodi debug log:https://pastebin.com/YGz3VgAS and elemuntum log https://paste.ubuntu.com/p/4R8rfnR7xh/

**Comment by gello0** [comment]
just found out that https://developers.themoviedb.org/3 is down for me https://i.imgur.com/6JMcyjY.png
,wonder why my ISP is blocking it?

**Comment by elgatito** [comment]
> wonder why my ISP is blocking it?

Have no clue. Probably the only way is to use VPN on Kodi device.
Addons relies on TMBD database.

**Comment by gello0** [comment]
Is there an alternative to TMDB?

**Comment by gello0** [comment]
My ISP is doing DNS blocking lol, Sorry to trouble you.
