### ISSUE TITLE
Не работает обновление библиотеки

### ISSUE THREAD

**Issue by promidrol** [elgatito/plugin.video.elementum#354]
## KODI
Kodi 18 release

## Устройство: ПК
Операционная система: Windows 10 pro x64

## Проблема
При добавлении фильма/сериала в библиотеку он не появляется, в папке есть в библиотеке нет, при нажатии "обновить библиотеку" на секунду выскакивает окно с надписью "подготовка" и все!

## Версия Elementum/burst
elementum-0.0.71
elementum.burst-0.0.34

* Link to Kodi debug log:
https://paste.kodi.tv/tabiqunope.kodi

**Comment by elgatito** [comment]
Папка как источник добавлена в Kodi?

**Comment by promidrol** [comment]
Интересно получилось) На версии коди 17 папки добавлены, а в 18 нужно по новой, если переносить готовый вариант. Проблема в источниках)

**Comment by elgatito** [comment]
Судя по отзывам, у многих сбились источники после обновления.
