### ISSUE TITLE
[Request] Add language option for TMDB searches

### ISSUE THREAD

**Issue by guglicap** [elgatito/plugin.video.elementum#355]
Hello, first of all great add-on, thanks for your work! I was thinking, since there are some providers which aren't English, that it'd be helpful to have an option to choose the TMDB search language. Right now if I want to find a torrent for a movie / show in another language I have to manually search for it through the general search menu, instead of using one of the (better) specific searches. I think it'd be quite easy to implement (?), I'm willing to try and have a shot at it myself if such a feature would be implemented. Thank you.

**Comment by elgatito** [comment]
I'm not quite understanding what you want.
If you search something from main window - it will send this query 'as is' to Burst (or other searches).
If you want to search movie/episode in Burst - Elementum sends all translations, received from TMDB and Burst decides which to use for searching for each particular provider.

**Comment by guglicap** [comment]
I'll have to experiment a bit more then, I guess. But basically, I wanted to watch the Italian version of a movie, so I went to Movies -> Search and searched for the Italian title. It found the movie on TMDB, but the title was in English, and when I clicked on it to search through providers I only got Italian results. Don't know if it was supposed to search for the Italian title in Italian providers, or if it did but found no results (which would be a problem in Burst since I'm sure there are Italian torrents of the movie)

**Comment by elgatito** [comment]
> and when I clicked on it to search through providers I only got English results

You have to enable italian trackers in Burst. 
The title you see from TMDB is in the same language as your Kodi.
Italian trackers take italian title from movie/tvshow.

**Comment by guglicap** [comment]
Yeah, I forgot to mention I did enable Italian providers. Thanks, I'll look a bit into it and get back to you.

**Comment by guglicap** [comment]
Okay seems to be working fine. My bad, closing the issue.
