### ISSUE TITLE
Kodi refuses to be closed because Elementum process isn't been killed properly

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#356]
## Current Behavior
Kodi doesn't close itself, it seems that Elementum.exe process is still running and it's not killed when Kodi is trying to kill it.

When I force close it through the Task Manager, Kodi is also closed immediatly.
It happens more often with the new version 0.1.10 (I think that with the previous versions 0.0.x it was ok)

* Sometimes it does close itself but only after a few minutes.

## Expected Behavior
Elementum.exe process should be killed in the closing proccess of Kodi, so kodi will close itself more quick without delay.

* Quasar is also installed.

Kodi Log:
https://paste.ubuntu.com/p/fDNssFkCW4

## Your Environment
Elementum 0.1.10
Kodi 17.6
Windows 10,64bit

**Comment by elgatito** [comment]
Please try v0.1.11

**Comment by burekas7** [comment]
The same also with 0.1.11

Kodi Log: 
https://paste.ubuntu.com/p/tBvbpKQzrt

* quasar.exe process closed but elementum.exe still remains there and prevent from kodi to be closed.

**Comment by elgatito** [comment]
Please try version 0.1.12

**Comment by burekas7** [comment]
I checked it with 0.1.12
At the first time it was seems to be good (Kodi was closed after ~20sec), but then on the next times it seems that the problem is still exist (Kodi was closed after few minutes, it's look  like it stuck)

Updated kodi log:
https://paste.ubuntu.com/p/X6F9mc84D6

**Comment by elgatito** [comment]
Please, try 0.1.14, there are changes in 0.1.14 and 0.1.13 related to this issue.

**Comment by burekas7** [comment]
I have tried with 0.1.14, but it's still the same.
Unless I force close elementum.exe (or sometime waiting few minutes or more), kodi doesn't close itself.

Kodi Log:
https://paste.ubuntu.com/p/pYKWJH5fMQ

**Comment by burekas7** [comment]
Still the same with 0.1.16

**Comment by burekas7** [comment]
@elgatito 

Is there any progress about this issue?
There is no change with 0.1.18

**Comment by elgatito** [comment]
@burekas7 
You can try with 0.1.19.

**Comment by burekas7** [comment]
> @burekas7
> You can try with 0.1.19.

It seems to be much better now.
If the problem will be return I will update here again (Hope not)
Thanks.

(By the way, sometimes it's still stuck but now it seems that Quasar is the problem ;) )

**Comment by burekas7** [comment]
@elgatito 

By the way, I have notice an error that shown in the log on each time kodi is closing (As you can see there is the same error also with Quasar, so it's something since then).

Just to mention, it's a good error, because when it was stuck it didn't show up.

The error log:
https://paste.ubuntu.com/p/PwNk3q5k9R

**Comment by elgatito** [comment]
@burekas7 which error?

**Comment by burekas7** [comment]
@elgatito 
See in the attached log, there are some errors and exception, maybe it's not critical or relevant when it closed but it's there each time kodi is closing.
