### ISSUE TITLE
[Bug] Error notification when trying playing media from the addon

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#357]
Something happend from version 0.1.10 to 0.1.11
Any movie or episode shows an error notification when pressing on it.

Kodi Log:
https://paste.ubuntu.com/p/tTKKVhcQdG

## Your Environment
Elementum 0.1.11
Kodi 17.6
Windows 10, 64bit

**Comment by elgatito** [comment]
Please try version 0.1.12

**Comment by burekas7** [comment]
Thanks.
Checked with 0.1.12 and it's OK now.
