### ISSUE TITLE
[Request] Additional info to the episode title format

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#358]
## Current Behavior
According to version 0.1.12
The episode title format shows only the episode name as title.
For example:
"Episode Name"
(Especially inside Trakt menu lists but I think in other location also)

## Wanted Behavior
My request is to add the season and the episode number, for example:
"2x03 . Episode Name" 
or  
"2x03 | Episode Name" 
or 
"2x03 - Episode Name"

Thanks.

## Your Environment
Elementum 0.1.12
Kodi 17.6
Windows 10, 64 bit

**Comment by elgatito** [comment]
Please, try 0.1.14. Options added to Appearance settings tab.

Default skin (estuary) writes episode and season just below the episode number. So, by default, we do not add it to the title. 
So you can enable option if you like the old way.

**Comment by burekas7** [comment]
Thanks. The new setting is working well.
(0.1.14)
