### ISSUE TITLE
Elementum Crashing after install on Kodi Leia Shield

### ISSUE THREAD

**Issue by krashtestdummie** [elgatito/plugin.video.elementum#359]
Tried installing Elementum 0.71 on Nvidia Shield Leia.
Looks like Elementum successfully installed. But crashes 3 times before aborting when you try to open it up
Log File https://paste.kodi.tv/oriquyikoz

**Comment by Tydir** [comment]
@krashtestdummie 

Happened to me on the TV ( Sony Bravia - don't remember the model) and I did the following workaround:
- installed Elementum
- daemon didn't start 
- got 3 notifications that Elementum has crashed and is restarting
- accessed the add-on settings and set a path for downloads, library and torrent to: USB/android/data/org.xbmc.kodi 
- uninstalled the add-on, but I selected that i want to keep my settings
- installed it again and it worked

@elgatito - if needed I can create an issue for the TV with the logs included

**Comment by elgatito** [comment]
@Tydir  in 0.1.* branch it is fixed, but that branch is experimental so far.

**Comment by krashtestdummie** [comment]
This also worked for the Shield
Except:
-Only Library and Torrent path needed changing
-On the shield the path is:
External Storage/Android/data/org.xbmx.kodi
-No need for uninstall. Just change path, restart Kodi

**Comment by Sapphiress** [comment]
> This also worked for the Shield
> Except:
> -Only Library and Torrent path needed changing
> -On the shield the path is:
> External Storage/Android/data/org.xbmx.kodi
> -No need for uninstall. Just change path, restart Kodi

I had this same issue, Installed on my Jetstream AGT418(AndroidTV 8.1) kept getting crashes.  After changing the option from "Use Memory" to "Use Files" and setting the download directory and other paths the daemon started and everything is running great.
