### ISSUE TITLE
Creating a provider for web pages

### ISSUE THREAD

**Issue by hoshsadiq** [elgatito/plugin.video.elementum#36]
I'm not sure if elementum would support this, but it would be cool to be able to write a provider that searches non-torrent based websites (1movies, alluc etc) that can then be used with the [urlresolver addon](https://github.com/tvaddonsco/script.module.urlresolver) for kodi. This is similar how the popular addon [exodus](https://github.com/huberyhe/plugin.video.exodus) worked. A separate provider addon would need to be written to search these sites, but the core needs to be able to support these.

**Comment by elgatito** [comment]
That needs a huge amount of work, and I'm not sure it's worth spending that time.

**Comment by WilixLead** [comment]
Hi guys! @elgatito I want to help with this task becourse I already thinking about this feature.
Not sure if this feature related to Pulsar/Quasar/Elementum. But if we talking about streaming addon, I think we can apply http/rtsp/etc streaming to Elementum.
How you think about it? 

Also I think it no huge and difficult task. Becourse I looking to another addons with video streaming support and they just provide link to stream source like `plugin.play(linkToRemoteSource)`
As I see in Elementum we have something like 
`XBMC_PLAYER.play(item)`
And I think we can just send link to this without buffering by Elementum (just by using only kodi streaming features).

Only one problem I see: How to present streaming sources to Elemenum select source dialog

Also, I plain implement streaming sources as different from Brust provider for split logic. I think this feature will be cool for Elementum

**Comment by elgatito** [comment]
It's a bigger task for Burst or other plugin that would query websites and form search results. Elementum can only give queries, formed with TMDB database.

The bad thing - Elementum won't control all these website based videos.

> But if we talking about streaming addon, I think we can apply http/rtsp/etc streaming to Elementum.

You don't have to do anything with streams, you get a stream url from the search plugin (like youtube), and give it to elementum, elementum will pass it, AS IS, to Kodi, and Kodi is playing the stream, because for Kodi, it looks like a usual stream from the web (and it is it, really).

If you want to make own searcher - you can use Burst code as a start, to leave parsing incoming payload and return results back to elementum, when you have some results - I can make further changes in Elementum to properly pass the stream to Kodi.

**Comment by WilixLead** [comment]
> I can make further changes in Elementum to properly pass the stream to Kodi.  

Thats what I talking about.
I can do it. I already have code base for some resources. 

>The bad thing - Elementum won't control all these website based videos  

What you mean? Why need control?

**Comment by elgatito** [comment]
> What you mean? Why need control?

When you start a playback with a torrent file you start in internal player, which reads your playback progress, does scrobble on trakt, provides file readers to read torrent info. 
When you have an external stream url - you just pass it to Kodi and that is it, it opens a player and it's not linked to plugin anymore.

**Comment by WilixLead** [comment]
Understood. What we can do for keep tracking? Or it is super hard at this moment?

PS. Kodi also have trakt plugin for track what played in kodi itself. May be we can get code base from trakt plugin for kodi and hook all played in kodi and pass to elementum trakt? 
It is can be OverKill for elementum, but we can pass it as additional addon in elementum repo (and pass it as dependency for new provider plugin)

**Comment by elgatito** [comment]
> May be we can get code base from trakt plugin for kodi and hook all played in kodi and pass to elementum trakt?

There is no need to do all of that. 
I will try different ways to handle correctly and see how it goes, but only after there is a plugin ready for testing as a source for web streams.

**Comment by WilixLead** [comment]
Great! I notify you when make something ready for use
