### ISSUE TITLE
.part file isn't removed after the torrent is finished and removed

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#360]
## Expected Behavior
When the torrent is removed from the torrents list, the .part should be also removed.

## Current Behavior
The .part file still remains after the torrent is finished and removed from the torrents list.

## Kodi Log
https://paste.ubuntu.com/p/W2ZgMqYt2G

## Your Environment
Elementum 0.1.12
Kodi 17.6
Windows 10, 64bit

**Comment by elgatito** [comment]
Please try 0.1.14.

**Comment by burekas7** [comment]
Still the same with 0.1.14
Kodi Log: https://paste.ubuntu.com/p/gwwRx4Bn9V

For example if I stop the playback, and then it asks if to continue downloading and I choose "No", the torrent is removed from the torrents list which is ok, but the .parts file still remains.
Even if I remove it manually from the list by choosing "remove torrent and files", .parts file is still there.

Do you think it acts like that because in the settings I set it to "keep" files and both settings?

**Comment by elgatito** [comment]
> Do you think it acts like that because in the settings I set it to "keep" files and both settings?

Of course. Parts file is not a usual file, it's used for properly resuming downloads. So when you delete downloaded file - we don't need it. If you plan to resume torrent later - you will need that file.

**Comment by burekas7** [comment]
In Elementum you have two options:
- Keep files for not finished video
- Keep files for watched/downloaded video

First, what do you mean by files? only the .torrent and .parts files, or also the video file with them?

**Comment by elgatito** [comment]
Everything. Torrent file remains on disk until torrent is active.

**Comment by burekas7** [comment]
I don't know if it's another bug but when I set it like this:
* Download after playback was stopped (Ask to stop)
* Keep files for not finished video (True)
* Keep files for watched/downloaded video (Ask for delete)

And finished watching, it didn't ask me for delete, only asked me for contiune download or not.

My purpose is actually keep the video file at the end of watching, so only the .torrent & .parts files will be removed.
(By the way, where the .torrent file is created? Because I didn't find it in the pathes from the settings, even while it's downloading)

**Comment by elgatito** [comment]
.torrent file is created in Torrents directory, and they are loaded after restart.
I don't see any need in adding more options. Or you delete everything or you leave everything.

**Comment by burekas7** [comment]
@elgatito 
I don't have a problem with the .torrent file, it removes itself when the torrent is completed.
I'm talking on the .parts file, I actually don't need it anymore after the torrent is completed.
I just want to keep the video file.
The problem is when you have several torrents when some of them completed and some of them still in progress, so if I want to clean the completed .parts files I don't know which of them are related to the completed torrents. 
So if the completed .parts files can be remove themselves when their torrent are completed it could be helpful. This is what I meant.
