### ISSUE TITLE
[Bug] wrong speed units in the notification message

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#362]
## Expected Behavior
The speed rate unit should be kB/s (I guess), as it shows in the dialog

## Current Behavior
The speed rate unit shows B/s in the notification message.

## Images
Notification
![b1](https://user-images.githubusercontent.com/13424257/52899245-a2844400-31f0-11e9-9e98-a99cefe4ff81.png)

Dialog:
![b2](https://user-images.githubusercontent.com/13424257/52899246-a87a2500-31f0-11e9-87f8-dc7b20c23bbc.png)

## Your Environment
Elementum 0.1.14
Kodi 17.6
Windows 10 , 64bit

**Comment by elgatito** [comment]
B/s means Bytes per second, if there are kilobytes - it will shows it.

**Comment by burekas7** [comment]
@elgatito 

I know :)
But this is why I open the bug, why there is a difference between the notification and the dialog.
The dialog shows kB/S (Which I assume that is correct) while the notification shows it as B/s when the value is equal between them.

**Comment by scakemyer** [comment]
@elgatito You're using `humanize.Bytes` on a value that is already in kilobytes: https://github.com/elgatito/elementum/blob/master/bittorrent/service.go#L1124

**Comment by elgatito** [comment]
@scakemyer  thanks for the tip!

@burekas7 please, check 0.1.15.

**Comment by burekas7** [comment]
Yes it's ok now with 0.1.15

Thanks.
