### ISSUE TITLE
[Bug] Playing an exist torrent isn't working

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#363]
When trying to play a torrent that exists in torrents list (From Trakt lists or directly from the torrents list), it opens the dialog but doesn't play it, even when the init buffer already reached to 100%

## Expected Behavior
Pressing on an exist torrent in the torrents list, or play it from the Trakt menus should play it (When the init buffer reached to 100%)

## Current Behavior
Instead, now it's only shows the dialog without playing it.

## Steps to Reproduce (for bugs)
1. Add a new torrent for downloading.
2. While it's dowloading and the init buffer reached to 100% check this:
a. Playing it from the torrent list.
b. Playing it from the Trakt Collection list
(a & b should be act the same)

---
Also a strange issue with the percentage value, before restart kodi it shows 100%, now after restarting kodi it shows -1.00%.

![b3](https://user-images.githubusercontent.com/13424257/52899511-8d5ce480-31f3-11e9-8064-79e6a4d9aa91.png)

![b4](https://user-images.githubusercontent.com/13424257/52899514-8fbf3e80-31f3-11e9-9270-182af503c1a6.png)
---

* I think the problem starts in 0.1.14 (But I'm not sure)

## Your Environment
Kodi Log 1 (Playback issue): https://paste.ubuntu.com/p/r5YgSgmvqt
Kodi Log 2 (Percentage issue): https://paste.ubuntu.com/p/SWmkFN9Qxc
Elenetum: 0.1.14
Kodi: 17.6
OS: Windows 10, 64bit

**Comment by elgatito** [comment]
Please, try v0.1.16.

**Comment by burekas7** [comment]
Thanks, It seems that it's ok now with 0.1.16
