### ISSUE TITLE
Subtitles start to unsynchronize

### ISSUE THREAD

**Issue by sirhc78** [elgatito/plugin.video.elementum#364]
Hi, 
First, thank your awesome work !
Using 0.0.71 on libreelec kodi 17.6

Is there any known reasons that some sychronized subtitles start to create a delay regularly during all the movie ? like 1sec every 10min

Best

Chris

**Comment by elgatito** [comment]
Elementum is only giving file to Kodi. 
Everything else is done by Kodi. Probably subtitles are not suitable for that video.
