### ISSUE TITLE
weird url "d."prefix 

### ISSUE THREAD

**Issue by vporoxnenko** [elgatito/plugin.video.elementum#365]
one famous provider is allowed by ip addr
search url http://x.x.x.x/search/0/4/300/2/the%20simpsons%2030x01%7cS30/
returns some data
but files are not found 

http://d.IPADDR/parse/d.rutor.org/download/483722 : Request http://d.IPADDR/parse/d.rutor.org/download/483722 failed with code: 500

without "d." I can download the file

**Comment by elgatito** [comment]
rutor parser works fine with latest Burst. 
Check your alias settings for rutor or custom overrides.

**Comment by vporoxnenko** [comment]
try rutor alias alt domain 37.1.207.65
burst ver 34

2019-02-17 22:46 GMT+03:00, Denis <notifications@github.com>:
> rutor parser works fine with latest Burst.
> Check your alias settings for rutor or custom overrides.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/elgatito/plugin.video.elementum/issues/365#issuecomment-464500197


-- 
Regards,
Valentin A. Poroxnenko

**Comment by elgatito** [comment]
you can place another domain name in alias field, like "rutor.lib", not ip, not some text.

**Comment by vporoxnenko** [comment]
alias "www.television.st" works well

2019-02-17 23:57 GMT+03:00, Denis <notifications@github.com>:
> you can place another domain name in alias field, like "rutor.lib", not ip,
> not some text.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/elgatito/plugin.video.elementum/issues/365#issuecomment-464508035


-- 
Regards,
Valentin A. Poroxnenko

**Comment by vporoxnenko** [comment]
just check again with domain name

22:24:04.447 T:139885675542272  NOTICE: [script.elementum.burst] >                RuTor search URL: http://www.television.st/search/0/0/300/2/deadpool%202016
22:24:04.924 T:139885675542272  NOTICE: [script.elementum.burst] >>               RuTor returned 54 results in 0.5 seconds, sending 6 best ones
22:24:04.948 T:139885994252032  NOTICE: [script.elementum.burst] Providers returned 6 results in 0.51 seconds
22:24:04.990 T:139883284956928  NOTICE: [plugin.video.elementum] [GIN] 2019/02/18 - 19:24:04 | 200 |      37.262µs |       127.0.0.1 | POST     /callbacks/248132818412350724
22:24:05.781 T:139883284956928  NOTICE: [plugin.video.elementum] [33mWARN  linkssearch  ▶ 1                [0mResolve failed for http://d.www.television.st/download/609367 : Get http://d.www.television.st/download/609367: dial tcp: lookup d.www.television.st: no such host
........

d.www.television.st: no such host

**Comment by elgatito** [comment]
in rutor provider rutor domains in substituted with d.rutor domain, because torrent files are there.

**Comment by vporoxnenko** [comment]
does not work for the mirrors
хотя про рутор вряд-ли кто-то захочет читать по-английски ))

так не работает http://d.www.television.st/download/609367
так работает http://www.television.st/download/609367

думаю имеет смысл добавить оба два варианта

**Comment by elgatito** [comment]
невозможно, там прямая подмена. Пользуйтесь другими обходами для рутора.

**Comment by elgatito** [comment]
Или у себя override делайте для рутора.
```
        "parser": {
            "infohash": "",
            "name": "item(tag='td', order=2)",
            "peers": "item(tag='span', order=1, select=('class', 'red'))",
            "row": "find_once('table', order=3).find_all('tr', start=2)",
            "seeds": "item(tag='span', order=1, select=('class', 'green'))",
            "size": "item.find_all('td', ('align', 'right'))[-1].text()",
            "torrent": "'http://television.st%s' % (item(tag='a', order=1, attribute='href').split('.info', 1)[-1])"
        },
```

**Comment by vporoxnenko** [comment]
так и сделал
может рутор у себя поменял принцип работы, т.к. несколько дней назад он работал и альт доменом стоял ип адрес

**Comment by vporoxnenko** [comment]
зеркала нынче дороги ))
