### ISSUE TITLE
plugin 0.1.1+ does not work with android_arm kitkat

### ISSUE THREAD

**Issue by vporoxnenko** [elgatito/plugin.video.elementum#366]
android arm kodi 16.0, 17.1 update and completely new installation fails on start
'stderr': -2 in the logs

linux 64, kodi 17.6
 works well

[kodi.log](https://github.com/elgatito/plugin.video.elementum/files/2873448/kodi.log)
[mygica.log](https://github.com/elgatito/plugin.video.elementum/files/2873450/mygica.log)

**Comment by elgatito** [comment]
That is because you run it on android 4.4, which is api19 and currently 0.1.* branch is built with api21. 
It is planned to try api19.

**Comment by vporoxnenko** [comment]
блджад ))

2019-02-18 11:24 GMT+03:00, Denis <notifications@github.com>:
> That is because you run it on android 4.4, which is api19 and currently
> 0.1.* branch is built with api21.
> It is planned to try api19.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/elgatito/plugin.video.elementum/issues/366#issuecomment-464632659


-- 
Regards,
Valentin A. Poroxnenko

**Comment by vporoxnenko** [comment]
0.1.15 ?

**Comment by elgatito** [comment]
Please, try v0.1.16

**Comment by vporoxnenko** [comment]
огонь
