### ISSUE TITLE
Elementum isn’t using the Socks5 proxy in settings.

### ISSUE THREAD

**Issue by gaussey** [elgatito/plugin.video.elementum#367]
Kodi 18.1 Windows 10 x64

Updated to latest versions via the update interface.

Have checked my IP using torrent IP checking tools and my ISP IP is showing instead of my Socks5 Proxy IP. 
https://am.i.mullvad.net/torrent was one of IP checking tools I used.
The other is : 
http://ipmagnet.services.cbcdn.com/

Further checked using Proxycap to ensure it wasn’t the provider (privateinternetaccess) at fault.

**Comment by elgatito** [comment]
Which version of plugin you use?
What you expect to see using those websites?

**Comment by gaussey** [comment]
0.0.71 the version from this page : 
http://elementum.surge.sh/getting-started/platforms-page

I’m expecting to see an IP address from the VPN provider(PIA) and not my own ISP verifying that that Elemental is downloading the test torrent using the SOCKS5 proxy.

**Comment by elgatito** [comment]
You should provide log file. It will be visible if proxy was set to torrent engine.
http://elementum.surge.sh/contribute/log/

**Comment by gaussey** [comment]
Will do!

**Comment by ParDev** [comment]
I had` the same problem as above, but with latest release (after libtorrent) it has changed. Now when my SOCKS5 credentials are set the downloads never start. I can select a torrent, but it either is stuck in "buffering" or never downloads anything. Same settings work with Quasar currently on another box.

**Comment by elgatito** [comment]
@ParDev you should provide log file if you expect any help.

**Comment by ParDev** [comment]
I've uploaded the log here: 
https://paste.kodi.tv/todetusida.kodi

Please note I had to remove my socks5 username and password as it was output in the logs as well.

**Comment by elgatito** [comment]
I don't see any problems in the log. Proxy is set to libtorrent engine. Addon is not doing any torrent networking, it's all done by libtorrent.

**Comment by ParDev** [comment]
Are you able to download any torrent with the socks5 configuration being used? I have the same issue on two machines, trying to find the right configuration to get it working.
