### ISSUE TITLE
Elementum WindowsError (298 'T') on Kodi for XBOX One

### ISSUE THREAD

**Issue by chirson** [elgatito/plugin.video.elementum#368]
Hi, 

First I'd like to say big thanks to all the developers involved in this project, it is an amazing product.  Second, the issue I have is that after installing latest Elementum version from the site (0.0.71 for Win x64) on Kodi 18.1 for XBOX One immediately after the message Elementum addon installed i receive message WindowsError (298 'T'). Here is the link with the logs: http://paste.kodi.tv/atuhividuc

Same thing happened on previous version of Kodi 18.0 and after the update to 18.1 today.
  
Interestingly enough same version of the addon (actually the same file 0.0.71) works without any problems on Kodi UWP version 18.0 from Windows Store on Win 10. Are there any known issues with the XBOX? I thought the point of UWP was to develop one app and should work on all Microsoft platforms. After all XBOX is running slimmed down version of Win 10, isn't it.

**Comment by elgatito** [comment]
Plugin will not work on XBOX, because it has limitations in starting binaries.
