### ISSUE TITLE
Вместо одного эпизода сериала в *.parts загружается вся раздача

### ISSUE THREAD

**Issue by Pilson66** [elgatito/plugin.video.elementum#369]
## Expected Behavior
Загружается выбранный эпизод

## Current Behavior
Помимо выбранного эпизода, загружается (скорее всего) вся раздача.
Файл эпизода загружается в соответствующую директорию, а остальные части раздачи загружаются в файл *.parts, который растет

## Steps to Reproduce (for bugs)
В настройках включаем сохранять на диск, и выбираем путь к сохранению загруженных файлов. Выбираем любой сериал, любой НЕ-ПЕРВЫЙ эпизод (если выбирать первый эпизод - такого НЕ происходит), выбираем любую раздачу. После буферизации начинается воспроизведение. Нажимаем паузу, наблюдаем максимально возможную для своего интернет-соединения скорость загрузки, и очень маленький процент загруженного, который также подтверждает, что загружается например не 2 ГБ, а 2ГБ * кол-во эпизодов.

В конкретном примере - загрузка 4-го эпизода "Suits", листинг директории с эпизодами, и директории с *.parts

root@mmpc:/store/Media/Video/Torrenter# ls -lh Suits\ \(2012-2013\)\ \[S02\]\ BDRip\ 720p\ \[UKR_ENG\]\ \[Hurtom\]/
итого 2,6G
-rw-rw-r-- 1 kodi kodi 2,6G фев 25 22:34 'Suits (2012-2013) [S02E04] BDRip 720p [UKR_ENG] [Hurtom].mkv'
root@mmpc:/store/Media/Video/Torrenter# ls -lh .*.parts
-rw-rw-r-- 1 kodi kodi 22G фев 25 22:43 .c135ea152cc5a96eacd4d2a6a9cecd8859587c51.parts

через некоторое время, когда процент загрузки на экране стал равен 100%

root@mmpc:/store/Media/Video/Torrenter# ls -lh Suits\ \(2012-2013\)\ \[S02\]\ BDRip\ 720p\ \[UKR_ENG\]\ \[Hurtom\]/
итого 2,6G
-rw-rw-r-- 1 kodi kodi 2,6G фев 25 22:34 'Suits (2012-2013) [S02E04] BDRip 720p [UKR_ENG] [Hurtom].mkv'
root@mmpc:/store/Media/Video/Torrenter# ls -lh .*.parts
-rw-rw-r-- 1 kodi kodi 36G фев 25 22:53 .c135ea152cc5a96eacd4d2a6a9cecd8859587c51.parts

Счетчик принятых байт сетевого интерфейса (через ifconfig) также подтверждает то, что загружено было не 2.6 ГБ, а 36+ ГБ

Данное поведение проверено дважды, на двух разных сериалах с двух разных трекеров.

## Your Environment
* Version used: kodi 18.1
* Environment name and version: 0.1.16 linux x64
* Operating System and version:  Ubuntu 19.04 amd64

**Comment by elgatito** [comment]
http://elementum.surge.sh/contribute/log/
Нужно лог смотреть.

**Comment by Pilson66** [comment]
Лог:
http://paste.ubuntu.com/p/Rp6PncSrKs/

**Comment by Pilson66** [comment]
Помог лог? Удалось найти багу?

**Comment by elgatito** [comment]
Пока не смотрел.

**Comment by elgatito** [comment]
Не вижу ничего необычного в логе.
Записью parts файлов занимается библиотека, мы можем только удалить этот файл после удаления торрента.

**Comment by Pilson66** [comment]
Получается, более невозможно скачать для просмотра только одну серию? Всегда будет прицепом качаться весь сезон?

**Comment by elgatito** [comment]
Качается всегда только выбранный файл. В parts хранятся куски соседних с выбранным файлом.

**Comment by Pilson66** [comment]
Почему тогда размер .parts примерно равен размеру всего торрента? Согласно тому, что я вижу - качается весь торрент. Если потом выбрать следующую серию - она не начинает скачиваться, а просто копируется целиком из .parts.

**Comment by elgatito** [comment]
Можете создать issue в репозитории торрент-движка: https://github.com/arvidn/libtorrent/ .
Дополнение только удаляет parts файл после удаления скачанных файлов. Если файлы не удаляются то и parts не удаляется. 
Если запускать кучу скачиваний и не удалять parts - то вполне может быть в файле содержатся куски из разных файлов.

**Comment by Pilson66** [comment]
Давайте вернемся к заголовку данного, так сказать, уже топика. Речь не идет об удалении или не-удалении .parts файла. Речь идет о том, что при закачке и воспроизведении одной серии, качаются все серии, что есть в раздаче. И это воспроизводится на каждой закачке, если выбирается вторая и выше серия. Я это подробно описал в "Steps to Reproduce (for bugs)".
Денис, Вы сами пробовали это воспроизвести, или только лог посмотрели?

**Comment by elgatito** [comment]
Еще раз пишу. Дополнение только говорит качалке какую директорию использовать для скачивания, и, если удалять торрент со всеми файлами через дополнение (не вручную из диска), то дополнение зачистит parts файл, если нужно.

Всё что касается записи этих файлов - это делает качалка.

**Comment by Pilson66** [comment]
Тоесть дополнение не говорит качалке, что нужно скачать только один файл из раздачи? Вот в этом-то и проблема. В тригинальном quasar скачивался только выбранный файл. Разве libtorrent не умеет качать выборочно файлы? Это же базовый функционал.

**Comment by elgatito** [comment]
> Тоесть дополнение не говорит качалке, что нужно скачать только один файл из раздачи? 

Говорит.

> Разве libtorrent не умеет качать выборочно файлы?

Так и делает.
Parts файл используется для хранения кусков НЕВЫБРАННЫХ файлов. Которые соседствуют с выбранным. 
Можете читать в документации libtorrent зачем и почему создаются parts файлы.
Вот пример обсуждения: https://github.com/arvidn/libtorrent/issues/3397

Со стороны дополнения parts файлы не контролируются.

**Comment by Pilson66** [comment]
Тогда получается, что либо дополнение неправильно говорит, что нужно скачать только выбранный файл, либо libtorrent "кладет" на это, и качает все целиком. Как этот момент можно отдебажить?

**Comment by Pilson66** [comment]
Например qBittorrent, которым я пользуюсь, также тспользует libtorrent, но он не имеет проблем с выбором отдельных файлов.

**Comment by elgatito** [comment]
Please, try v0.1.18. Download parts file, then use as usual.

**Comment by Pilson66** [comment]
Unfortunately, the same behavior... I started to download the second episode (3 GB) out of 7 (22 GB in total), and I received a separate 3 GB episode, and 19.8 GB .parts file.

**Comment by elgatito** [comment]
До старта скачивания был на диске parts файл?

**Comment by elgatito** [comment]
https://github.com/arvidn/libtorrent/issues/3243

```
ls does not show you how much space has been allocated for files, it shows the size of the file.

instead, use stat -f "%b" <file-name>
```

**Comment by Pilson66** [comment]
До закачки:
`root@mmpc:/store/Media/Video/Torrenter# ls -lh .*.parts                 
ls: невозможно получить доступ к '.*.parts': Нет такого файла или каталога`

После закачки второго эпизода:
`root@mmpc:/store/Media/Video/Torrenter# ls -lh GOT\ \(Season\ 07\)\ LOST\ 1080/*
-rw-rw-r-- 1 kodi kodi 3,7G мар  6 12:04 'GOT (Season 07) LOST 1080/GOT.(S07E02).HD1080.LostFilm.(qqss44).mkv'
root@mmpc:/store/Media/Video/Torrenter# stat -c "%b" GOT\ \(Season\ 07\)\ LOST\ 1080/GOT.\(S07E02\).HD1080.LostFilm.\(qqss44\).mkv
7711880
root@mmpc:/store/Media/Video/Torrenter# ls -lh .*.parts
-rw-rw-r-- 1 kodi kodi 25G мар  6 12:07 .c43059ddf11773e3bc0e832f8390ed609b854383.parts
root@mmpc:/store/Media/Video/Torrenter# stat -c "%b" .c43059ddf11773e3bc0e832f8390ed609b854383.parts
50915136`

**Comment by elgatito** [comment]
А диск, на который пишется parts файл поддерживает sparse файлы? Какая там файловая система?

Вот у меня например:
```
elgato@HP:~/Develop/elementum$ ls -la ~/Downloads/Elementum/downloads/.4c54c8f46785e59954d5c35170dc703d50fb2e04.parts 
-rw-r--r-- 1 elgato elgato 251973632 бер  4 18:10 /home/elgato/Downloads/Elementum/downloads/.4c54c8f46785e59954d5c35170dc703d50fb2e04.parts
elgato@HP:~/Develop/elementum$ du ~/Downloads/Elementum/downloads/.4c54c8f46785e59954d5c35170dc703d50fb2e04.parts
217800	/home/elgato/Downloads/Elementum/downloads/.4c54c8f46785e59954d5c35170dc703d50fb2e04.parts
elgato@HP:~/Develop/elementum$ 
```

du пишет реальный размер, ls - пишут выделенное место.

**Comment by Pilson66** [comment]
Файловая система ext4
```
root@mmpc:/store/Media/Video/Torrenter# mount | grep /store
/dev/sdb1 on /store type ext4 (rw,noatime,nodiratime)
```
ls и du показывают одинаковый размер.
```
root@mmpc:/store/Media/Video/Torrenter# ls -lh .c43059ddf11773e3bc0e832f8390ed609b854383.parts
-rw-rw-r-- 1 kodi kodi 25G мар  6 20:37 .c43059ddf11773e3bc0e832f8390ed609b854383.parts
root@mmpc:/store/Media/Video/Torrenter# du -sh .c43059ddf11773e3bc0e832f8390ed609b854383.parts
25G     .c43059ddf11773e3bc0e832f8390ed609b854383.parts
```
Также, кол-во полученых данных на сетевом интерфейсе увеличивается на размер закачки, что также подтверждает то, что происходит скачивание всего торрента, а не только выбранного эпизода плюс несколько кусков. Об этом я также писал в самом начале.

До закачки (строка "RX"):
```
root@mmpc:/store/Media/Video/Torrenter# ifconfig eth0
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.0.22  netmask 255.255.255.0  broadcast 192.168.0.255
        inet6 fe80::2e0:4cff:fe04:60  prefixlen 64  scopeid 0x20<link>
        ether 00:e0:4c:04:00:60  txqueuelen 1000  (Ethernet)
        RX packets 76496788  bytes 65525966553 (65.5 GB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 90820962  bytes 93926354224 (93.9 GB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```
После:
```
root@mmpc:/store/Media/Video/Torrenter# ifconfig eth0
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.0.22  netmask 255.255.255.0  broadcast 192.168.0.255
        inet6 fe80::2e0:4cff:fe04:60  prefixlen 64  scopeid 0x20<link>
        ether 00:e0:4c:04:00:60  txqueuelen 1000  (Ethernet)
        RX packets 99330774  bytes 97366948982 (97.3 GB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 99427218  bytes 96495242896 (96.4 GB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by elgatito** [comment]
Скорее всего нужно создавать ишью в libtorrent.
Показать что файла нету, стартовать торрент, показать содержимое выкачанное, и du/ls/stat.
