### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by NeoCro44** [elgatito/plugin.video.elementum#37]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

**Comment by NeoCro44** [comment]
Im not sure is this issue but i cant get more then 2500 kB/s even i got 500 mbit speed. I tried for test movies that got over 1k seeders still same results. I didnt change settings to limit speed.
And i need wait till 100% download if file is bigger then around 700 mb to be able to watch whitout loading popup all the time

**Comment by heartlogic** [comment]
I have the same issue. Quasar is using all available bandwidth while elementum's torrent engine is using half of it.

**Comment by tomtomclub** [comment]
Quasar is using all available bandwidth  yes true i haves the same issue

**Comment by elgatito** [comment]
Elementum is not doing Download itself. Downloading is done by the library. You can can raise an issue there (anacrolix/torrent) if you are using default file storage and it's working slow.

**Comment by NeoCro44** [comment]
ok tnx
