### ISSUE TITLE
Torrents restart downloading from 0% even when fully downloaded

### ISSUE THREAD

**Issue by royeiror** [elgatito/plugin.video.elementum#370]
I'm using the latest Elementum on LibreELEC 9.0 x86. I normally load a bunch of torrents and tick them off whenever I can. But since changing from Quasar to Elementum I've been having to download the torrents over a few times, upon reboot and sometimes with nothing special going on at the time. The latest I was actually watching a 100% downloaded torrent and it froze and started downloading from 0% and so did all the other torrents that were already at 100%

## Expected Behavior
Downloaded torrents should remain in place

## Current Behavior
Torrents restart from 0% upon reboot. Sometimes randomly.

## Your Environment

* Version used: .0.0.71
* Environment name and version: LibreELEC 9.0 Leia
* Operating System and version: LibreELEC 9.0
* Link to Kodi debug log:
https://drive.google.com/a/taucontrol.com/file/d/1oHERLm0aJQE4MyS7p7x9F2L8i8kA90VJ/view?usp=drivesdk

**Comment by elgatito** [comment]
The 0.0.* branch is not supported, for the moment.
You can try 0.1.* (manually download from https://github.com/elgatito/plugin.video.elementum/releases ).
It has same torrent engine as Quasar does.

**Comment by royeiror** [comment]
Wow. I didn't know I was so out of date.

**Comment by elgatito** [comment]
It's not, yet, released to the masses, so not in repository, for the moment.

**Comment by royeiror** [comment]
I don't know how I came about it then. IIRC through the official page.
