### ISSUE TITLE
Download speed real slow

### ISSUE THREAD

**Issue by ashoktvm** [elgatito/plugin.video.elementum#373]
Download speed is really low. Its not the problem my connection. SInce quasar is getting full download speed. Definitely a Elementum problem

**Comment by Goga777** [comment]
didn't you limit your upload speed?

**Comment by ashoktvm** [comment]
no. There is no upload limit. In quasar its utilizing my full bandwidth. But in elementum i am getting only 1/6th of the bandwidth

**Comment by elgatito** [comment]
You should read welcome message and provide all the required information.
