### ISSUE TITLE
Active connections and Download speed are dropping when resuming

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#375]
It seems that when resuming for playback when the torrent is still downloading, it lose the connections with the seeds and reconnecting to them, and the speed is fall and then start to increase again.
(It's more problematic when we are talking on weak torrents)

## Steps to Reproduce (for bugs)
1. Start downloading a torrent (Pay attention to the seeds/peers and the active connections and the speed)
2. Stop it and choose continure downloading in the background.
3. Choose the torrent in order to resume it while it's still downloading.
4. Pay attention again to the speed and the active connections.
It seems that it reconnecting them, and the speed is dropping for a period until it recover in a good case or not at all and stuck on 0 active connections.

Kodi Log:
https://paste.ubuntu.com/p/kx2NyygHMp

## Your Environment
* Version used: 0.1.16
* Environment name and version: Kodi 17.6
* Operating System and version: Win 10, 64bit

**Comment by elgatito** [comment]
Should be better with 0.0.17.

**Comment by zorge88** [comment]
When a press pause, torrent stop downloading.
After 10 second, torrent is continue downloading.

**Comment by burekas7** [comment]
@elgatito 
> Should be better with 0.0.17.
Checked with 0.0.18

Basically it seems to be solved but I think there is another issue now.
The speed looks like fake value because it shows for example avarage of 500kb/s,
But when I checking the actual file progress it doesn't progress according to this speed, 600MB file was should be finished more quick with that speed.

Kodi Log:
https://paste.ubuntu.com/p/q5P8NWVJsb

**Comment by elgatito** [comment]
@burekas7 try to remove upload limit and see how it goes.

**Comment by burekas7** [comment]
> @burekas7 try to remove upload limit and see how it goes.

remove or reduce?
I will check and update.

**Comment by elgatito** [comment]
@burekas7 Remove 500kb upload or increase to few thousands, for example.

**Comment by burekas7** [comment]
Strange.
I have changed the upload to "0", restart kodi.
When I go to the torrent list I see that the torrent is 100% (Before the ristart it was ~20% was increasing very slowly while the speed was ~500kb/s

Kodi Log after the restart.
https://paste.ubuntu.com/p/MksBT2mbYY

**Comment by burekas7** [comment]
In addition to the previous comment, another strange thing:
I'm checking the video file in my drive, and the details and the video itself shows that the file is finished, but elementum still shows that the download is in progress (~35% and increasing with download speed of 2M), how is it possible?

(Upload is on "0" now)

Kodi Log:
https://paste.ubuntu.com/p/TydCBN6xYX

**Comment by elgatito** [comment]
> And another issue, even that I set the upload to 0, it's still uploading (~25kb/s)

0 means - not limited. 
_Libtorrent does not support disabling upload._ When you limit it to, for example, 1 byte - it cannot communicate with peers and you can't even download.

**Comment by elgatito** [comment]
> I'm checking the video file in my drive, and the details and the video itself shows that the file is finished, but elementum still shows that the download is in progress (~35% and increasing with download speed of 2M), how is it possible?

Percents of "done" we get from libtorrent. Probably, it does not know what files do we need. When you start "playback", you select file and then it calculates new percents and continue downloading.

I will review adding torrents on plugin start.

**Comment by burekas7** [comment]
> 0 means - not limited.
> _Libtorrent does not support disabling upload._ When you limit it to, for example, 1 byte - it cannot communicate with peers and you can't even download.
Ok. And general question. The download speed (or active connections) is affected by the upload limit or there is no connection between them?

> Percents of "done" we get from libtorrent. Probably, it does not know what files do we need. When you start "playback", you select file and then it calculates new percents and continue downloading.
> 
> I will review adding torrents on plugin start.

Ok Thanks.
This problem hasn't happened since then, maybe it was specific operation that I did that made this situation.

**Comment by elgatito** [comment]
> Ok. And general question. The download speed (or active connections) is affected by the upload limit or there is no connection between them?

Yes. Limit is including messages between libtorrent and peers, so if it can't send messages - you can't ask for downloads from peers.

> This problem hasn't happened since then, maybe it was specific operation that I did that made this situation.

It was probably a non-finished torrent, with file-based storage, when you restart Kodi, it automatically adds previous torrent but shows it's finished.

**Comment by burekas7** [comment]
> Yes. Limit is including messages between libtorrent and peers, so if it can't send messages - you can't ask for downloads from peers.

Understood, you must set the limit in order to able the connect and download.
But what I actually meant is if I set the upload limit to 500kb/s or 2000kb/s for example, is the download speed will be the same or it will be act difference? The download speed is affect by the upload limit value?

**Comment by elgatito** [comment]
> But what I actually meant is if I set the upload limit to 500kb/s or 2000kb/s for example, is the download speed will be the same or it will be act different? Is the download speed affected by the upload limit value?

Download/Upload bandwidth includes messages between libtorrent and peers. When you limit download/upload, it limits bandwidth in general, including messages. So yes, when you set a little download - you will limit upload speed, if you limit upload - you will limit download speed.

**Comment by zorge88** [comment]
If it's not a problem for you to see how he has arranged the scakemye on Quasar
everything works perfectly

**Comment by burekas7** [comment]
@elgatito 
It seems that the issue is back again in 0.1.31.

When resuming the speed is falling to zero and start again the connections.

* Another question, what could be the reason that peers aren't connect to me and download? (My upload sometimes remain on zero for a long time, sometimes the entire download)
