### ISSUE TITLE
Elementum 1.17 crashing not working anymore

### ISSUE THREAD

**Issue by KillerJoeBR** [elgatito/plugin.video.elementum#376]
Sorry I am using my phone right now. But new version is crashing when I try to play any content. It seems to be trying to load a previous torrent but there isn't one and it crashes. 

https://www.dropbox.com/s/thvd1vtgfhlyppx/kodi.old.log?dl=0

**Comment by elgatito** [comment]
Please, try v0.1.18.

**Comment by KillerJoeBR** [comment]
New version is working great. Thanks.
Good work!
