### ISSUE TITLE
0.1.17 "internal server error" при попытке воспроизвести эпизод.

### ISSUE THREAD

**Issue by Pilson66** [elgatito/plugin.video.elementum#377]
## Steps to Reproduce (for bugs)
Открываем любой сериал, любой сезон. Выбираем любой эпизод. После поиска торрентов, вываливается "Internal server error".  Далее, в верхнем правом углу выводится статус "Elementum: 100% Проверяем торрент-файлы...", и бесконечно крутится спинер.

## Your Environment
* Version used:
0.1.17
* Environment name and version:
18.1
* Operating System and version:
Ubuntu Linux 19.04 amd64
* Link to Kodi debug log:
Лог из консоли:
https://paste.ubuntu.com/p/489psXdYJg/

**Comment by Sheicer** [comment]
Такая же ошибка при любом поиске любого фильма.

**Comment by elgatito** [comment]
Да, я исправил ошибку.

**Comment by Pilson66** [comment]
Что-то коммитов пока не видно...

**Comment by burekas7** [comment]
Yes I have this problem too:
https://paste.ubuntu.com/p/kHsNGFBWQh
(Since 0.1.17 or since the last burst update)

**Comment by elgatito** [comment]
@burekas7 it comes from Elementum 0.1.17 update. Added more DHT nodes and that caused the bug. Now preparing new version.

**Comment by elgatito** [comment]
Please, try v0.1.18.

**Comment by Pilson66** [comment]
This issue looks like a fixed one.

**Comment by burekas7** [comment]
> @burekas7 it comes from Elementum 0.1.17 update. Added more DHT nodes and that caused the bug. Now preparing new version.

Thanks, it's ok now with 0.1.18
