### ISSUE TITLE
Trakt lists

### ISSUE THREAD

**Issue by burrodesancho** [elgatito/plugin.video.elementum#38]
I have several trakt lists (shows that I watch on Netflix and shows that I watch on Kodi) and watchlist for shows that I am considering.
Adding of a trakt list to the library works correctly. But during trakt syncing tv shows from my watchlist and other trakt lists are added to the library as well.

## Expected Behavior

Adding and syncing tv shows to the library just from selected trakt list.
## Current Behavior

On the first selection and adding of a trakt list to the library shows are scanned and imported correctly.
Elementum trakt sync imports shows from other trakt lists into the library as well.
All unwanted shows can one by one be removed from the library from Elementum (context menu and remove from library). After that removed shows will not be imported again into the library. But after adding a new show in any of my trakt lists this show will be added as well.
## Steps to Reproduce (for bugs)

1. Add a list to library.
2. Wait for trakt sync on do it manually from Elementum settings.
3. Shows from other lists start to populate library.
## Your Environment

* Version used: 0.0.25

* Environment name and version: Kodi 17.6 

* Operating System and version: Arch Linux 64bit

* Link to Kodi debug log: [Kodi.log](https://paste.ubuntu.com/26339424/)

**Comment by elgatito** [comment]
That is pretty expected. We are not managing Trakt from Elementum, but rather using some features to import items from Collections and Lists. 
If we'd add controlling mechanisms to set which list you want to import and which is not - then it becomes really complicated and that is not what we want. 

I can see the option to add settings for different sync parameters. 
For example: allow sync of userlists, allow sync of collection, allow sync of watchlist, allow sync of watched items, allow cross-sync of watched items from kodi to trakt.

Will that be better?

**Comment by burrodesancho** [comment]
That would be great!

Any way to stop shows from other trakt lists to populate the library is good for me.

Thanks!

**Comment by elgatito** [comment]
Forgot to mention that this is implemented in latest versions. You can browse Elementum Settings -> Trakt and select what you want to sync and what you don't.

**Comment by burrodesancho** [comment]
Thanks a lot!
