### ISSUE TITLE
Shows being added to library, without being in Trakt account

### ISSUE THREAD

**Issue by shalevmo** [elgatito/plugin.video.elementum#380]
## Expected Behavior
I've added my Trakt account, so my library would sync with my collection. So only the series that are in my collection should appear in my library. 

## Current Behavior
When I clear the library, and then sync trakt manually, everything happens as it should, and only the shows that should be in my library are in my library. But when I leave Kodi open for a few hours, it probably syncs automatically, and when this happens, I have two new kinds of shows being added to my library:
1. Shows that are in my trakt history, but not in my collection. 
2. Shows that I dont even know are being added to my library (I checked on trakt, never watched them and they're not in any of my lists or in my collection). 

## Possible Solution
Maybe for some reason the automatic sync ignores my settings, and therefore doing something wrong? (it does explain shows from my history being added, but does not explain the weird shows that being added). 

## Steps to Reproduce (for bugs)
I'm not sure how the issue can be reproduced, since I have no idea where those unfamiliar shows are coming from. 
Maybe this steps will help reproduce the issue with my trakt settings being ignored (or that's AR least what I think):
1. Enable trakt + scrobble. 
2. Enable sync items from collections into kodi library. 
3. Disable sync items from watch list into library, and sync items from user lists into library. 
4. You need to have some shows in your trakt history, that are not in your collection. 
5. Update trakt on elementum settings. 
6. Check that library only has shows from your collection. 
7. Leave kodi open for a few hours so auto sync will be triggered. 
8. Check your library to see if shows that aren't in your collection were added. 

## Your Environment
Elementum 0.1.19
Kodi 18.1
Nvidia shield 2017 (Android TV 8.0) 

Thank you!

**Comment by elgatito** [comment]
Have you deleted the show from the Kodi library? (the one that shows up after sync)

Elementum syncs Collections, User lists, Watchlist from Trakt. 
"Watched" are not synced.

But if show was previously in added through Elementum - it will be re-added to the library until it was not deleted from Elementum (like find the show, in context menu "Remove from library").

**Comment by elgatito** [comment]
Closing without getting the response.
