### ISSUE TITLE
Torrents status

### ISSUE THREAD

**Issue by jorgecardoso220** [elgatito/plugin.video.elementum#381]
Hi 

Is there any way to get the torrent download information, we get when pause a vídeo, with the vídeo still playing?

Thanks in advance

**Comment by elgatito** [comment]
> Is there any way to get the torrent download information, we get when pause a vídeo, with the vídeo still playing?

What does that mean?

**Comment by antonsoroko** [comment]
I think he meant OSD with download speed and status that is shown during the pause. And he wants to see this info during playback.

**Comment by jorgecardoso220** [comment]
I will try to explain better. 
When you pause a vídeo you get the information of the download speed and percentage. It is possible to present that information with the vídeo still playing?

**Comment by jorgecardoso220** [comment]
> I think he meant OSD with download speed and status that is shown during the pause. And he wants to see this info during playback

Exactly that 😀

**Comment by elgatito** [comment]
You want to see downloading stats while watching something?

**Comment by antonsoroko** [comment]
I guess it could be convenient for tuning purposes. Like bind a key to show this osd.

**Comment by jorgecardoso220** [comment]
The ideial solution would be, when you press “i” to get the vídeo information window the osd would be shown

**Comment by antonsoroko** [comment]
https://github.com/elgatito/plugin.video.elementum/issues/326

**Comment by zorge88** [comment]
Everything works perfectly on the new version.
I looked at the film and it stands on seeding.
When I enter element settings, and change any settings, all movies are deleted from Elementun - torrents
They all stay on my hard drive, they do not get deleted from the hard disk, but there are no more in Elementum torrents.

**Comment by elgatito** [comment]
@zorge88 

> When I enter element settings, and change any settings, all movies are deleted from Elementun - torrents
> They all stay on my hard drive, they do not get deleted from the hard disk, but there are no more in Elementum torrents.

You mean when you change settings and elementum is reloaded - there are no torrents in the list of torrents?

**Comment by zorge88** [comment]
Yes, no torrents
But it has them on the hard disk

**Comment by zorge88** [comment]
I set in the Elemental settings Bittorrents "load torrent from torrents folder on start up" and everything works well,
When run up Kodi ,all torrents autimatic downloading , even if I left them on pause.

**Comment by antonsoroko** [comment]
If i am not mistaken, this option is enabled by default. If not - it is a bug.

**Comment by zorge88** [comment]
Yes, this option is enabled by default.
I left 5 torrents on pause, when I reboot KODI, all 5 torrents start automatically downloading.
On Quasar , it stands for a pause until I personally re-launch it every time I respond.

**Comment by antonsoroko** [comment]
@elgatito
What is expected behavior in this case?
(Pause torrent, restart elementum, torrent is in X state)

**Comment by zorge88** [comment]
Do you know what the problem was?
I use Exodus Redux + Elementum context due to the IMDB library.
when I play a movie over Elementum, when I press the pause and exit from KODI and restart it, the movies that are released from ELEMENTUM do not continue to download. That's it.
But when I open the EXODUS and play the movie through Elementum contex he continues to download the movie from where the download was stopped.

**Comment by elgatito** [comment]
In libtorrent torrents are always added in Paused state. 
In Elementum, currently, it's Resumed after being added. 
I don't know of a way to save pause/resume state for torrents. So we can either resume all automatically loaded torrents or leave paused.

**Comment by elgatito** [comment]
Added option to define if auto-loaded torrents should start paused or resumed.
