### ISSUE TITLE
[Bug] "Disable background progress dialog on plaback" isn't working well

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#382]
I set the "Disable background progress dialog on plaback" but the dialog still shown on playback (even after restart kodi)
![image](https://user-images.githubusercontent.com/13424257/54165171-44055b00-4468-11e9-86cb-b39383bf9f10.png)

![image](https://user-images.githubusercontent.com/13424257/54165256-99416c80-4468-11e9-9c1f-10f63a2dffb8.png)

Kodi Log:
https://paste.ubuntu.com/p/G5kTkjN7Nk

## Your Environment
Elementum: 0.1.20
Kodi: 17.6
OS: Win10, 64bit

**Comment by elgatito** [comment]
It's not that dialog, it's about the one that shows on top on the window (with a spinner).

That one, on the screenshot, should be hidden if you resume playback. Is the data changed on that dialog or it's static?

**Comment by burekas7** [comment]
Oh my mistake, the relevant setting is "Enable overlay status" and not what I did.
But why it's located under "Kodi Library" tab? (In Quasar it's under "General" settings)

**Comment by elgatito** [comment]
Yes, that's a mistake, it should be in Appearance tab.

So you see this dialog only when paused? Or even when playing video? If yes - then it's a bug somewhere there. It should show on pause and hide on playback.

**Comment by burekas7** [comment]
Yes it's ok, it's shown on pause and hidden on playback.
Thanks.
