### ISSUE TITLE
Why existing torrent isn't recognized when choosing it again from menus

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#383]
I have a torrent that is finished (100%) in the Torrents list.
But when I go to the Trakt menus and play the same episode, it isn't recognize that there is already a torrent for this episode, and start new search for it.
Usually it works, just on this specific case.
(Maybe it isn't finding the files regarding this torrent or something, or relate to the fact that there is no more .parts or .torrents files in the download folder as it was as I have noticed lately)

Kodi Log:
https://paste.ubuntu.com/p/G5kTkjN7Nk

Elementum: 0.1.20
Kodi: 17.6
OS: Win10, 64 bit

**Comment by elgatito** [comment]
You play episode 1, find season pack, watch episode, leave torrent in active list.
Then want to play episode 2 and expect to use existing torrent, that is in active list.
Right?

**Comment by burekas7** [comment]
No.

On this specific case there was a torrent in the Torrents active list, but when I press on the episode in Trakt Progress or Trakt Collection, it didn't recognize it was there and run the burst search again.
(As I said, basically it works well, it asked if to run an existing torrent etc, but just on this case it happend, it's not something that happens frequently)

**Comment by elgatito** [comment]
Please try with 0.1.25.
It should work fine.

**Comment by burekas7** [comment]
Basically it's ok already since 0.1.24 (Also in 0.1.25)
It was a specific case.

If it will happen again I will reopen it.

Thanks.

**Comment by elgatito** [comment]
No, no. Before 0.1.25 plugin was not able to lookup episode in existing torrents. Only if you were watching it before.
Now it looks for same show in your torrents and look if it can find desired episode.

**Comment by burekas7** [comment]
> No, no. Before 0.1.25 plugin was not able to lookup episode in existing torrents. Only if you were watching it before.
> Now it looks for same show in your torrents and look if it can find desired episode.

Oh, understood now.
Thanks.
