### ISSUE TITLE
Download multiple episodes within same torrent

### ISSUE THREAD

**Issue by tupc10** [elgatito/plugin.video.elementum#384]
Hello guys, first of all I would like to thank you for your great work with Elementum, on my opinion it is the best torrent player available for kodi!

I am running:
Elementum v0.1.16
LibreELEC with Kodi v18.1
Raspberry Pi 3 B
and it works like a charm! It gives me an option to download all the episodes within the same torrent at once, but this option is gone after the latest updates, so I had to go back to v0.1.16.

It would be great if this option could be brought back into the newest releases and also if it could be made explicit available, like an popup option.

The steps that I am current following to download multiple episodes within same torrent on v0.1.16 are:
1) Setup Elementum to download torrents using files, and not the memory option;
2) Open Elementum and search for torrent using Elementum Burst;
3) Choose the torrent to downlod from the list generated;
4) Wait for the popup screen shows up and list all the files or episodes available within the torrent chosed;
5) Since I want to download all of them, I press the back button and do not choose any of the listed episodes within the torrent;
6) Elementum then starts the download of all the files or episodes inside the torrent.

Thanks again for your work and patience!

Best Regards

**Comment by elgatito** [comment]
@tupc10 actually, that was a bug, because not choosing anything means nothing should be downloaded.

Kodi does not allow adding simple button to that dialog or choosing file. 
But I will look on other options.

**Comment by tupc10** [comment]
Hello @elgatito, thanks for your quick reply! I see, it really makes sense that was a bug and not meant to happen..

I would be very pleased if you really could take a look at this, it is nothing pleasant to download all the episodes within a torrent clicking one by one kkk...

I know very little about Kodi interface, specially after Leia update, but some ideas that come to my mind and seem simpler to implement are:

-> Add an item named for example "All content" into the list of episodes, for downloading all of them (maybe need to be done at Elementum Burst side);

-> Enable Kodi Context Menu over the list of torrent generated by Elementum Burst, with an option for "Download all content" of the chosen torrent;

-> Return the "bug" and its original funcionality to Elementum, allowing to download all content of torrent when no item is chosen from the episodes list.

I hope to have helped and not created a big problem for you by asking this.

Anyway, thanks again for understanding and for your consideration!

Best Regards

**Comment by burekas7** [comment]
Regarding for a Season torrent, In quasar you could chose the specific episode and download, then it was changed so instead selecting the specific episdoe it was donw automatically for you according to the episode you press on.

1. Is there any option for downloading the whole season?
2. Is there a setting for disable/enable this option of automatically selection of episode for downloading?

**Comment by Pilson66** [comment]
I think, the best behavior for this - auto-download the next one episode, when the current episode began to play, and fully downloaded. This behavior was implemented in the "torrenter" kodi plugin, and it was very convenient.

**Comment by tupc10** [comment]
Hello again,

Any news about this topic? For me it really doesn't matter to have an user-friendly option for this funcionality or to have it enhanced. Just having it back as it was on v0.1.16 would be really great. Then I could update my addon to the last version that has better torrent pause/resume perfomance and won't be stuck on this old version anymore.

Please, if it is not asking too much and it is not a big deal, rollback this funcionality as it was on v0.1.16! Thanks again and best regards!

**Comment by elgatito** [comment]
There are few options for this issue.

If you add torrent with multiple files (and you use files for downloading, not memory), then you can go to list of torrents, and in context menu check "Download all" to start downloading all files.

Another option. If you go to list of episodes and in context menu check "Play from ... " (which adds all episodes in the playlist), and check torrent with multiple files, then torrent will start downloading at the end of current episode, and torrent will not be closed until you stop the playlist. 
This is so-called auto-play for next episode.

**Comment by burekas7** [comment]
Regarding the first option, when I press on "Download all", will it add all the episodes to the Torrents list and download them separatly or it still remains as one torrent so after the current episode will be done it will start to download all the others?

Additional option I think about is to open a dialog with all the contained episodes in the Season torrent, mark only the episode you want from the list, so it will download only the marked episodes. Is it possible?

**Comment by elgatito** [comment]
> Regarding the first option, when I press on "Download all", will it add all the episodes to the Torrents list and download them separatly or it still remains as one torrent so after the current episode will be done it will start to download all the others?

No. You can't add same torrent twice. Download starts when you are almost done with current episode.

> Additional option I think about is to open a dialog with all the contained episodes in the Season torrent, mark only the episode you want from the list, so it will download only the marked episodes. Is it possible?

Not possible with Kodi.

**Comment by tupc10** [comment]
Hello, I never had the opportunity to thank you! I tested the "Download ALL" option that you created and it works as expected, thank you for your great work, @elgatito! I just had some difficulties to use this option when the torrent comes from elementum Burst search, because it starts downloading before I could check the option to "Download ALL". Anyway, I believe to have found a way to use it with Burst, I just need to go to torrents section and pause or restart the download after choosing the "Download ALL" option. Thanks again! Best regards
