### ISSUE TITLE
[Request] Modify Trakt Scrobble to use watched progress percentage properly

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/plugin.video.elementum#385]
## Current Behavior

In elementum settings i have 95% to mark video as completed
I watched episode for 81% (43/53mins) then pressed stop button and episode was marked as watched and removed from "my progress". 

## Steps to Reproduce (for bugs)

1. 
2. 
3.
4.

## Your Environment

* Version used: 0.1.20

* Environment name and version: spmc 17

* Operating System and version: android TV 8

* Link to Kodi debug log:

**Comment by elgatito** [comment]
Log file needed. It shows why and when watched has been set.

**Comment by antonsoroko** [comment]
@elgatito
https://paste.ubuntu.com/p/2nsnx8FhHf/

Thanks!

**Comment by elgatito** [comment]
I don't see an error. 
We don't  set as watched in Kodi, and we only save progress on Trakt in percents. Looks like they marked as watched automatically when progress is more than 80%.

**Comment by antonsoroko** [comment]
What is the meaning of setting in elementum then? (Процент просмотра для пометки просмотренным в trakt -  как-то так называется)

**Comment by elgatito** [comment]
To mark as watched in Kodi and in Trakt.

**Comment by antonsoroko** [comment]
https://trakt.docs.apiary.io/

Не смог найти ни в нете ни в апи что-то про захардкодженные проценты.

**Comment by elgatito** [comment]
Все вопросы к тракту. Запрос на отметку watched не отправляется, значит они сами.

**Comment by antonsoroko** [comment]
Проверю на разных процентах в настройках. Кажется когда я поставил 100, то не было бага.

**Comment by elgatito** [comment]
https://trakt.docs.apiary.io/#reference/scrobble/stop/stop-or-finish-watching-in-a-media-center

```
Use this method when the video is stopped or finishes playing on its own. If the progress is above 80%, the video will be scrobbled and the action will be set to scrobble. A unique history id (64-bit integer) will be returned and can be used to reference this scrobble directly.
If the progress is less than 80%, it will be treated as a pause and the action will be set to pause. The playback progress will be saved and /sync/playback can be used to resume the video from this exact position.
Note: If you prefer to use a threshold higher than 80%, you should use /scrobble/pause yourself so it doesn't create duplicate scrobbles.
```

**Comment by antonsoroko** [comment]
спасибо, что-то я с телефона пропустил это.
может есть смысл юзать pause тогда ?

**Comment by elgatito** [comment]
Не уверен что там можно несколько scrobble делать, но надо пробовать.

**Comment by antonsoroko** [comment]
Баг ещё актуален. Не критично , но изредка напрягает :-)
Спасибо.

**Comment by elgatito** [comment]
@antonsoroko уже выяснили что это не баг, а специфика работы Trakt. Они сами остановку проигрывания трактуют как просмотренное.
