### ISSUE TITLE
Sorting in torrent list does not work

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/plugin.video.elementum#386]
## Expected Behavior

Would be nice to see new torrents on top of the list. Sorting could provide this functionality.

## Current Behavior

Сортировка в списке торентов не работает.
Т.е. они выстроены по времени добавления, но сделать обратную сортировку не получается.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: 0.1.20

* Environment name and version: spmc 17

* Operating System and version: android tv 8

* Link to Kodi debug log:

https://paste.ubuntu.com/p/2nsnx8FhHf/

**Comment by elgatito** [comment]
Стандартный скин не даёт никакого выбора сортировки, как и в меню обычных (не там где фильмы).
Я добавил дату в торренты, но так же сортировки у меня не появилось.

**Comment by antonsoroko** [comment]
У меня нестандартный скин. Очень жаль что так выходит.

**Comment by antonsoroko** [comment]
Сортировка что-то сломалась совсем
Последние торренты стали в середине. (Может связано с жестким выходом из коди.)
https://paste.ubuntu.com/p/kN9SR6FRJH/

**Comment by elgatito** [comment]
In 0.1.26 I removed dates from torrents to keep strict sorting.
The only option I see is to make strict sorting from context menu on torrents.

**Comment by antonsoroko** [comment]
In general it somehow sorted, but there are many let's say misplaced items. Changing direction of sorting  (still) does not work.

https://paste.ubuntu.com/p/xfKQtgZTt8/

**Comment by elgatito** [comment]
Sorting torrents by means of skin should not work, because torrents list is not a list of movies/episodes, and your skin cannot properly treat it. 
When I added date to each item - if was not able even use default sorting and was breaking it.

**Comment by antonsoroko** [comment]
>Sorting torrents by means of skin should not work, because torrents list is not a list of movies/episodes, and your skin cannot properly treat it.

Ok, i see.

>In general it somehow sorted, but there are many let's say misplaced items. 

For example if you close elementum while it downloads a torrent (that is in the botton of the list at that exact moment - correct sirring) and start elementum again, then this torrent could appear somewhere in the middle of list.

**Comment by elgatito** [comment]
@antonsoroko you can open http://127.0.0.1:65220/torrents/ and see real order of torrents.
If it differs from what you see in Kodi - then it's your skin.

**Comment by antonsoroko** [comment]
Checked - order is the same as in kodi.
But this list changes fron time to time. Looks like after restart elementum do some kind of checking of torrents and thus some torrents become "fresher" than they were.

**Comment by elgatito** [comment]
@antonsoroko on load, torrents are sorted by modification date. You can open directory with torrent files and sort by modification time, to see the order there.
I have tried many times, it always sorts by modtime, which is changed only on torrent creation.

**Comment by antonsoroko** [comment]
I will try.
But if I am not mistaken modification time is also changed when you change attributes of file (and file content), not only on creation - there is a different attribute for that - creation time.
Also I use NTFS (because of Android restrictions), not sure, but it also might add something to the picture.

**Comment by elgatito** [comment]
> But if I am not mistaken modification time is also changed when you change attributes of file 

Elementum is not touching torrent files after they are created.

**Comment by antonsoroko** [comment]
I tried standard skin and even English locale and regional settings for date - same result.
Ordering in elementum does not match ordering in File Manager (i mean real files). And after every restart it slightly changes in elementum, but not in FM.

Is ordering is based on *.torrent file or on "real" file/folder? (i have photos to proof what i said above, but for real files and not for *.torrent files - i can make photos of these as well)
And as I can see after restart elementum starts to recheck some torrents and exactly these torrents become out of order.

**Comment by antonsoroko** [comment]
*. torrent files are definitely changed on every elementum start. But i don't see correlation with sorting in torrents list in elementum/kodi.

@elgatito
Could you please clarify for me what info elementum uses for sorting?

Thanks.

**Comment by antonsoroko** [comment]
For history:

![IMG_20190422_144440](https://user-images.githubusercontent.com/17964763/56621425-b7d08100-662c-11e9-932f-9f6bf225c31d.jpg)
![IMG_20190422_142534](https://user-images.githubusercontent.com/17964763/56621426-b7d08100-662c-11e9-9d2d-c56e711a424d.jpg)
![IMG_20190422_143003](https://user-images.githubusercontent.com/17964763/56621427-b8691780-662c-11e9-903a-c650da125115.jpg)
![IMG_20190422_143141](https://user-images.githubusercontent.com/17964763/56621428-b8691780-662c-11e9-80ee-1b42773e8c11.jpg)
![IMG_20190422_143936](https://user-images.githubusercontent.com/17964763/56621429-b8691780-662c-11e9-8bd9-e3bb5a3c5cf9.jpg)
![IMG_20190422_141732](https://user-images.githubusercontent.com/17964763/56621430-b8691780-662c-11e9-923b-3e94215cc9a2.jpg)

**Comment by elgatito** [comment]
> Could you please clarify for me what info elementum uses for sorting?

https://github.com/elgatito/elementum/blob/v0.1.29/bittorrent/service.go#L944
Elementum is using only *.torrent files, stored in "Torrents" directory inside of downloads directory.
Maybe your system changes modification time on any access to them. We can try with using creation date.

**Comment by antonsoroko** [comment]
>Elementum is using only *.torrent files, stored in "Torrents" directory inside of downloads directory.

I guess you meant "torrent directory" in settings (which is inside of kodi's `temp` directory be default).
Anyway, as i said above
>*. torrent files are definitely changed on every elementum start. But i don't see correlation with sorting in torrents list in elementum/kodi.

So this is kind of strange. Maybe something related to Android or NTFS.


About
>We can try with using creation date.

I guess this could be more "native" - sorting by torrent adding date.

Thank you in advance!

**Comment by elgatito** [comment]
Looks I have found the problem. 
Each time torrent metadata is resolved by libtorrent, *.torrent file was re-written to the disk, so modification time was changed on every Elementum restart. 
I will fix this, but modification time will still be used, because not all filesystems store creation time, so Golang does not have api for getting it.

So new torrents will be in the end of the list, while old ones will stay 'as is'.

**Comment by antonsoroko** [comment]
Great, thank you !

>Golang does not have api for getting it.

Yeah, i also noticed that.

**Comment by elgatito** [comment]
Please, try v0.1.30.
Modification date should not change after you start elementum (kodi).

**Comment by antonsoroko** [comment]
Seems to be good now.
Thank you very much!
