### ISSUE TITLE
remove open subtitles integration

### ISSUE THREAD

**Issue by hoshsadiq** [elgatito/plugin.video.elementum#387]
Sorry to be a bother, but could you please remove open subtitles integration? It doesn't work without logging in (at least for me) and using the official open subtitles addon works perfectly fine with anything loaded from elementum.

I mentioned this a while ago on another thread but nothing was done so figure I'd open a new ticket so it's separately tracked.

**Comment by elgatito** [comment]
If you don't want to use it, just don't. 
Why removing it?

**Comment by antonsoroko** [comment]
Elementum/quasar implementation of opensubtitles search has better filtering as i can see (official plugin sometimes gives you irrelevant results).
I don't see a point to remove it. Maybe it could be switchable (on/off in settings) as an option.

**Comment by hoshsadiq** [comment]
My reasons for raising this issue are as follows:

- For some reason, Elementum is top in the subtitle selection list, which doesn't work without logging in
  - As far as I know there is no way to change that order
- Logging in allows for open subtitles to track you
  - Considering their site and addon is usable without logging in, this is a better option to me.
- Elementum's focus is on streaming torrents, not subtitles. Following the single responsibility principle in software, I think the option for subtitles should be left to addons that manage subtitles. This gives users the option to choose their preferred website too ([there's a whole host of addons](https://kodi.tv/addons/subtitles)).

@antonsoroko Can't say I've tried the one supplied by Elementum since I don't really want to register on open subtitles, however, I've never had much of an issue with the official plugin. The only thing that happens every now and then is that I accidentally pick a subtitle that's out of sync, but usually the second one I pick is correct.

Alternatives to removing, I'd be happy to use the Elementum subtitle provider instead providing I don't have to log in. Failing that, as @antonsoroko said, having an option to enable/disable it would be great.

**Comment by elgatito** [comment]
OSDB cannot be disabled, it is defined in `addon.xml`.
