### ISSUE TITLE
Остановка загрузки LibTorrent, связанная с частыми постановками на паузу видео и малым количеством сидеров.

### ISSUE THREAD

**Issue by pavelmxx** [elgatito/plugin.video.elementum#389]
За последний месяц, видимо в связи с переходом на LibTorrent, если я правильно все понял, стал замечать, что видео с малым количеством сидеров (до 10, но возможно дело не в этом) начинает с какого-то момента прекращать загрузку данных. После остановки видео и запуска той же раздачи с того же момента, продолжает играть нормально, что исключает такую причину, как отсутствие сидеров. Возможно, это связано с частыми постановками на паузу, а именно около 5 раз на ~5 минут каждая на полуторачасовой фильм. По крайней мере, я уже 3 раза ловил такую закономерность в остановке, как частые паузы и малое количество сидеров. За 9 лет эксплуатации всяких quazar и torrenter, явно как и elementum, на разных p2p плеерах подобного не встречал. Это к тому, что опыт эксплуатации разных версий libtorrent на том же torrenter – большой.

Прикладываю кусок лога у удалением, на мой взгляд, ненужных дубликатов строк:
[https://pastebin.com/sxss0ymc](https://pastebin.com/sxss0ymc)

В 03:25:32.625 T:5396 проигрывание замерло. На экране паузы показывает "download rate = 0". После этого остановил вручную и стартовал видео заново. Все пошло с максимальной скоростью загрузки.

**Comment by Goga777** [comment]
когда вы пишете, остановил вручную - вы имеете ввиду - на паузу поставил?

**Comment by pavelmxx** [comment]
Останавливаю кнопкой "стоп". Пауза проблемы не решает, загрузка останавливается совсем. Пауза помогает, если источник медленный, чтобы буфер заполнить. Там по логу все видно.

**Comment by elgatito** [comment]
Можете пробовать версию 0.1.22, больше я не знаю что можно делать. Дополнение никаких ограничений не ставит и не управляет отключениями пиров, а настроек по этому поводу я не вижу у libtorrent.

**Comment by elgatito** [comment]
@pavelmxx каой результат с 0.1.22?

**Comment by elgatito** [comment]
Closing without getting response.
