### ISSUE TITLE
service.watchedlist addon

### ISSUE THREAD

**Issue by pavelmxx** [elgatito/plugin.video.elementum#390]
Посоветуйте, пожалуйста, решение для синхронизации и бэкапа watchedlist (просмотренных) библиотеки коди. Раньше пользовался "service.watchedlist" addon, но он отказывается работать позицией в библиотеке, если рядом с *.strm файлом от elementum лежит *.nfo файл такого вида: 
```
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<movie>
	<uniqueid type="unknown" default="false">375183</uniqueid>
	<uniqueid type="elementum" default="false">375183</uniqueid>
	<uniqueid type="tmdb" default="true">375183</uniqueid>
	<uniqueid type="imdb" default="false">tt1718924</uniqueid>
	<uniqueid type="tvdb" default="false"><nil></uniqueid>
</movie>
https://www.themoviedb.org/movie/375183
https://www.imdb.com/title/tt1718924/
```
, который автоматически создает trakt, интегрированный в elementum. В такой ситуации service.watchedlist просто игнорирует фильм без всяких записей в логах. Встроенный в elementum trakt не имеет возможности пакетной выгрузки и загрузки watchedlist. Официальный addon trakt делает все коряво, портит списки и не имеет достаточной функциональности. Сейчас пользуюсь временным решением: убиваю скриптом *.nfo рядом с *.strm и не использую списки trakt, т.к. они тоже создают *.nfo файлы, как и добавление фильма в библиотеку через интерфейс elementum. Очень бы хотелось иметь недостающий грамм функциональности внутри elementum для решения задач по пакетному бэкапу и синхронизации watchedlist, пусть даже в рамках самого trakt, что, тем не менее, сомнительно верно. В идеале хотелось бы иметь внутри elementum свой "service.watchedlist.elementum" с блэкджеком и прочим, чтобы создавал свой watchedlist.db, готовый для импорта и экспорта в любой момет на любой машине, и без всякий лишних привязок ко всяким id elementum и trakt.

**Comment by elgatito** [comment]
> Посоветуйте, пожалуйста, решение для синхронизации и бэкапа watchedlist (просмотренных) библиотеки коди.

Никогда таким не интересовался, синхронизация просмотренного и так работает в Elementum.

> Встроенный в elementum trakt не имеет возможности пакетной выгрузки и загрузки watchedlist.

Не понимаю зачем это делать? Дополнение синхронизирует просмотренное из Тракта. Проставляет просмотренное тоже сразу.

**Comment by elgatito** [comment]
Not sure this is needed in this plugin. There are many other plugins to sync Trakt items.
