### ISSUE TITLE
Не работает на OrangePi

### ISSUE THREAD

**Issue by Delvish** [elgatito/plugin.video.elementum#392]
Доброго времени суток.
На OrangePi (установлен образ RetrOrangePi, в составе идет Kodi 17.4) устойчиво работает только версия 0.0.71. Пробовал несколько версий 0.1.х - все они падают с примерно одинаковым текстом в логах. Пробовал полностью удалять директорию с плагином и ставить заново - толку нет. Что можно предпринять?

 
> 
> 19:40:15.513 T:3027894272   DEBUG: ------ Window Init (DialogBusy.xml) ------
> 19:40:15.513 T:3027894272   DEBUG: Window DialogBusy.xml was already loaded
> 19:40:15.513 T:3027894272   DEBUG: Alloc resources: 0.09ms
> 19:40:15.932 T:3027894272   DEBUG: ------ Window Deinit (DialogNotification.xml) ------
> 19:40:16.301 T:2633954224  NOTICE: [plugin.video.elementum] Python version: ['2.7.9 (default, Aug 13 2016, 18:15:29) ', '[GCC 4.9.2]']
>                                                 dist: ('debian', '8.9', '')
>                                                 linux_distribution: ('debian', '8.9', '')
>                                                 system: Linux
>                                                 machine: armv7l
>                                                 platform: Linux-3.4.113-sun8i-armv7l-with-debian-8.9
>                                                 uname: ('Linux', 'RetrOrangePi', '3.4.113-sun8i', '#110 SMP PREEMPT Sun Nov 26 01:48:10 GMT 2017', 'armv7l', '')
>                                                 version: #110 SMP PREEMPT Sun Nov 26 01:48:10 GMT 2017
>                                                 mac_ver: ('', ('', '', ''), '')
> 19:40:16.688 T:2633954224   DEBUG: [plugin.video.elementum] Requesting http://127.0.0.1:65220/ from ['plugin://plugin.video.elementum/', '10', '']
> 19:40:16.696 T:2633954224    INFO: CPythonInvoker(12, /home/pi/.kodi/addons/plugin.video.elementum/navigation.py): script successfully run
> 19:40:16.699 T:3027894272   DEBUG: ------ Window Init (DialogNotification.xml) ------
> 19:40:16.700 T:3027894272   DEBUG: Window DialogNotification.xml was already loaded
> 19:40:16.700 T:3027894272   DEBUG: Alloc resources: 0.01ms
> 19:40:16.776 T:2633954224    INFO: Python script stopped
> 19:40:16.777 T:2633954224   DEBUG: Thread LanguageInvoker 2633954224 terminating
> 19:40:16.820 T:3027894272   ERROR: GetDirectory - Error getting plugin://plugin.video.elementum/
> 19:40:16.822 T:3027894272   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.elementum/) failed
> 19:40:16.822 T:3027894272   DEBUG: CGUIMediaWindow::GetDirectory (addons://sources/video)
> 19:40:16.822 T:3027894272   DEBUG:   ParentPath = []
> 19:40:16.855 T:2633954224   DEBUG: Thread BackgroundLoader start, auto delete: false
> 19:40:16.865 T:3027894272   DEBUG: Keyboard: scancode: 0x24, sym: 0x000d, unicode: 0x0000, modifier: 0x0
> 19:40:16.877 T:2633954224   DEBUG: Thread BackgroundLoader 2633954224 terminating
> 19:40:17.121 T:3027894272   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
>

**Comment by elgatito** [comment]
Полный лог нужен.

**Comment by Delvish** [comment]
[kodi.log](https://github.com/elgatito/plugin.video.elementum/files/2980158/kodi.log)

**Comment by elgatito** [comment]
У вас старое ядро, не запускается бинарник. Если последняя версия тоже не стартует, то придется оставаться на ветке 0.0.* пока.

**Comment by Delvish** [comment]
спасибо за информацию. что ж, попробую обновиться. я так понимаю, до мажорной 4й версии нужно обновить ядро?

**Comment by elgatito** [comment]
@Delvish честно, без понятия. На том же libreelec, ядро 3.14 и работает, а на Убунте 14-ой не работает.

**Comment by Delvish** [comment]
да уж. ну, попробую strace и все такое, может получится понять чего не хватает

**Comment by elgatito** [comment]
Nothing to do with current build environment. 
The only option I see is to try make build environment (libtorrent-go) with usa of musl library, not default libc.

**Comment by elgatito** [comment]
Please try 0.1.32, it is built with Musl, without use of Libc.

**Comment by elgatito** [comment]
@Delvish
