### ISSUE TITLE
Why is there no option to force a certain initial buffer?

### ISSUE THREAD

**Issue by Ianmu** [elgatito/plugin.video.elementum#393]
When downloading a torrent made up of multiple files elementum calculates a certain initial buffer based on the total torrent size. I only care about one file so I really don't need to buffer that much, but I can't force it to use less initial buffer using the normal settings. The initial buffer of the 102gb torrent takes so long that I am able to write this whole post during it. While the episode that I want to watch is only 1.5gb.

I am using the latest version of elementum on the latest version of libreelec, but that doesn't really matter I guess.

Edit: I love the add-on BTW. Keep up the good work :).

**Comment by elgatito** [comment]
By default, automatic buffer selection option is enabled, it does not count file size or torrent size, but, instead, looks for piece size, which, for big torrents is 8/16mb.
You can disable this option in Bittorrent tab.
And there you can change buffer size, which is 20mb, by default.
