### ISSUE TITLE
Problem with running a torrent

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#395]
Since version 0.1.22 when I choosing the torrent from the results screen, the dialog isn't show up, instead the waiting/loading spinner stuck on the screen until I press the backspace key. And when I press the backspace key I get the "Playback failed" dialog and then the torrent progress dialog show up.
(Currently I playing it from the Trakt Progess page, but I don't think it's the reason or relevant)

Kodi Log:
https://paste.ubuntu.com/p/dDYpSK2zxV/

* Also I'm checking the same torrent also with Quasar, and there I'm getting , more seeds and more active connection and it's start downloading with great speed while with Elementum is stuck on 0kb/s, especially after I change some settings and it restart the torrent process.
Log: https://paste.ubuntu.com/p/zDPctYX5vx

## Your Environment
Elementum 0.1.22
Kodi 17.6
Win 10 , 64bit

**Comment by elgatito** [comment]
I don't see anything wrong in the log. Torrent is added and started to download.

**Comment by burekas7** [comment]
Although sometimes there is still a little delay since I'm choosing the torrent from the burst results windows and until the init buffering dialog is show up, it seems to be better now with 0.1.23, because before there wasn't delay, it was just stuck with the loading icon.

If the problem return I will open it again.

Thanks.
