### ISSUE TITLE
Optimize libtorrent work

### ISSUE THREAD

**Issue by elgatito** [elgatito/plugin.video.elementum#398]
This is a task for testing different settings for libtorrent.

Please, do not try to download and run the binary. 
I place binaries and ask specific people to try test version, to see if it makes any difference.

**Comment by elgatito** [comment]
[elementum.zip](https://github.com/elgatito/plugin.video.elementum/files/3000623/elementum.zip)
Test binary for armv7.

**Comment by burekas7** [comment]
Is it relevant for windows?

**Comment by elgatito** [comment]
@burekas7 

> Is it relevant for windows?

No. 
This issue will be used for posting some test versions, related to different issues. That one is for testing download speed on armv7 memory storage.

**Comment by KillerJoeBR** [comment]
@elgatito

I had really slow speeds using elementum in the early versions but since the change after 0.1.x i get very good speeds. (using memory) So why do you think you need to test a different version?

**Comment by elgatito** [comment]
@KillerJoeBR it works good for you, for me, but some people report of having problems with speeds, so I test different approaches, make binary and ask them to try.

There are still some places to fix and make speeds better, so trying to cover maximum amount of user cases.

**Comment by elgatito** [comment]
[linux_armv7.zip](https://github.com/elgatito/plugin.video.elementum/files/3030181/linux_armv7.zip)
[linux_arm64.zip](https://github.com/elgatito/plugin.video.elementum/files/3030182/linux_arm64.zip)

Guys, here is the binary for Linux_armv7 and Linux_arm64. 
I would ask to enable deadlines in Bittorrent section of Elementum and try this binary.

What to test: seek video, change audio tracks.

**Comment by burkostya** [comment]
I am trying to replace binary in elementum v0.1.29 with this one on my RPi3 model B. But getting error about settings not saved. Is it because of different versions? If so could you provide fresh binary?

**Comment by elgatito** [comment]
@burkostya use latest release, no need to use binaries uploaded here.
