### ISSUE TITLE
Support IOS/tvOS

### ISSUE THREAD

**Issue by elgatito** [elgatito/plugin.video.elementum#4]
General issue tracker for IOS/tvOS support in Elementum.

**Comment by elgatito** [comment]
scakemyer/plugin.video.quasar#452

**Comment by elgatito** [comment]
@mrdest , i have pushed a new version of Elementum, there is a dump of system information coming to the log.
It would be awesome if you run plugin.video.elementum on ios/tvos to see how the system definition looks like. (even if it does not start properly)

**Comment by mrdest** [comment]
**iOS (iPad Pro)**

> 10:42:00.166 T:6179827712  NOTICE: ES: Starting UDP Event server on port 9777
10:42:00.166 T:6179827712  NOTICE: UDP: Listening on port 9777 (ipv6 : false)
10:42:00.356 T:6167883776  NOTICE: [plugin.video.elementum] Python version: ['2.7.13 (default, Nov 14 2017, 15:00:49) ', '[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]']
                                                dist: ('', '', '')
                                                linux_distribution: ('', '', '')
                                                system: Darwin
                                                machine: iPad6,3
                                                platform: Darwin-17.2.0-iPad6,3-64bit
                                                uname: ('Darwin', 'Mrdest-iPad', '17.2.0', 'Darwin Kernel Version 17.2.0: Fri Sep 29 18:14:51 PDT 2017; root:xnu-4570.20.62\~4/RELEASE_ARM64_S8000', 'iPad6,3', '')
                                                version: Darwin Kernel Version 17.2.0: Fri Sep 29 18:14:51 PDT 2017; root:xnu-4570.20.62\~4/RELEASE_ARM64_S8000
                                                mac_ver: ('11.1.2', ('', '', ''), 'iPad6,3')
10:42:00.411 T:6191181824  NOTICE: [plugin.video.elementum] elementumd: starting elementumd
10:42:00.413 T:6186938368  NOTICE: [plugin.video.elementum] elementum: starting jsonrpc service

[Full kodi.log](http://bit.ly/2jN7f1K)
<hr>

**tvOS (Apple TV 4)**

> 10:59:29.990 T:6208090112  NOTICE: [plugin.video.elementum] OS type: Darwin
10:59:29.990 T:6208090112  NOTICE: [plugin.video.elementum] uname: ('Darwin', 'Apple-TV', '17.2.0', 'Darwin Kernel Version 17.2.0: Fri Sep 29 17:54:22 PDT 2017; root:xnu-4570.20.62\~1/RELEASE_ARM64_T7000', 'AppleTV5,3', '')
10:59:29.990 T:6208090112  NOTICE: [plugin.video.elementum] Binary dir: False, item: False
10:59:29.990 T:6208090112  NOTICE: [plugin.video.elementum] elementumd: proc is empty
10:59:30.136 T:6199603200  NOTICE: [plugin.video.elementum] Python version: ['2.7.12 (default, Oct 24 2017, 14:18:23) ', '[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]']
                                                dist: ('', '', '')
                                                linux_distribution: ('', '', '')
                                                system: Darwin
                                                machine: AppleTV5,3
                                                platform: Darwin-17.2.0-AppleTV5,3-64bit
                                                uname: ('Darwin', 'Apple-TV', '17.2.0', 'Darwin Kernel Version 17.2.0: Fri Sep 29 17:54:22 PDT 2017; root:xnu-4570.20.62\~1/RELEASE_ARM64_T7000', 'AppleTV5,3', '')
                                                version: Darwin Kernel Version 17.2.0: Fri Sep 29 17:54:22 PDT 2017; root:xnu-4570.20.62\~1/RELEASE_ARM64_T7000
                                                mac_ver: ('11.1', ('', '', ''), 'AppleTV5,3')


[Full kodi.log](http://bit.ly/2zs2KAZ)

**Comment by elgatito** [comment]
Great. Now, at least, we can properly detect ios/tvos.
I have put some changes, so you can try the next (probably v0.0.6) version with proper OS detection.

**Comment by mrdest** [comment]
Hi, I want to help more. I have python knowledge and some experience with go and Addons development.
If I clone the project, what should I do to help and proceed with the development?

**Comment by elgatito** [comment]
Binary is compiled by xgo (https://github.com/karalabe/xgo with docker images for go 1.9 https://hub.docker.com/r/elgatito/xgo-1.9.2/ ).
That docker image is my fork of original xgo image, but with newer golang. There is also an iOS/OSX SDK's. As I understand, we need to add there SDK for tvos to be able to build against that OS type.
Python side is only detecting platform and trying to run the binary.

**Comment by mrdest** [comment]
OK, so the steps should be as follows?

1. docker pull elgatito/xgo-1.9.2 #from [here](https://hub.docker.com/r/elgatito/xgo-1.9.2/)
2. go get github.com/elgatito/cross-compiler #And compile with adjustments & support for iOS & tvOS
3. go get github.com/elgatito/elementum.git #and compile
4. go get github.com/elgatito/plugin.video.elementum #And package with new resources/bin

Is that correct?

**Comment by elgatito** [comment]
You can look into travis configuration for both daemon and plugin repositories. 
https://github.com/elgatito/elementum/blob/master/.travis.yml
https://github.com/elgatito/plugin.video.elementum/blob/master/.travis.yml

To build the daemon:
1) docker pull elgatito/xgo-1.9.2
2) go get https://github.com/elgatito/elementum.git
3) make linux/amd64 # inside of elementum directory

That probably would be enough.
Cross-compiler project/image is not used now, only Xgo needed.
Documentation is not yet updated for newer makefiles. 

For plugin:
1) git clone https://github.com/elgatito/plugin.video.elementum.git
2) cd plugin.video.elementum
3) rm -rf plugin.video.elementum # inside of cloned repo, this folder is generated by "make"
4) git clone https://github.com/elgatito/elementum-binaries.git resources/bin/ # or copy generated binaries 
5) make && make zipfiles

**Comment by mrdest** [comment]
Thanks!
I tried:
`$ cd $GOPATH/src/github.com/elgatito/elementum ; make darwin-10.6/386`

> Makefile:73: warning: overriding commands for target `build'
Makefile:43: warning: ignoring old commands for target `build'
/Applications/Xcode.app/Contents/Developer/usr/bin/make build TARGET_OS=darwin-10.6 TARGET_ARCH=386
Makefile:73: warning: overriding commands for target `build'
Makefile:43: warning: ignoring old commands for target `build'
xgo -go 1.9.2 -image=elgatito/xgo-1.9.2 -targets=darwin-10.6/386 -dest build/ -ldflags='-w -X github.com/elgatito/elementum/util.Version="v0.0.5-6-g0bf89de" -extldflags ""' github.com/elgatito/elementum
make[1]: xgo: No such file or directory
make[1]: *** [build] Error 1
make: *** [darwin-10.6/386] Error 2

BTW, xgo was downloaded successfully:
> ...
Digest: sha256:fc1aeee70c19d9726fb5b213c6c26f897d0222273081a56e94720f9382a68fc2
Status: Downloaded newer image for elgatito/xgo-1.9.2:latest

Probably something I'm missing with Docker & containers.

I'm here to try to build with iPhone, iPad & ATV :)

**Comment by elgatito** [comment]
You miss the xgo utility:
```go get github.com/karalabe/xgo``` (which calls custom docker image, which is elgatito/xgo-1.9.2)

**Comment by elgatito** [comment]
You can join the gitter chat for elementum, if you want to https://gitter.im/ElementumApp/Lobby

**Comment by mrdest** [comment]
Here is the reason it won't work on iOS: https://github.com/xbmc/xbmc/blob/master/tools/depends/target/python27/make-fork-optional.patch#L8

**Comment by elgatito** [comment]
It came out that fork is disabled in IOS globally, not only in python or kodi. 
The workaround is to use pthreads, but not sure it is suitable for our application, that needs investigation.

**Comment by Lojs** [comment]
V.0.0.20
https://paste.ubuntu.com/26257617/

https://imgur.com/a/DlnmE

**Comment by elgatito** [comment]
Can you try uninstall and reinstall from zip?

**Comment by Lojs** [comment]
Can you please till me which zip file?
This one:
plugin.video.elementum-0.0.20.darwin_x64.zip
Or:
plugin.video.elementum-0.0.20.zip

I’m on APPLE-TV

**Comment by elgatito** [comment]
Second one is always preffered.

**Comment by Lojs** [comment]
https://paste.ubuntu.com/26258407/

**Comment by elgatito** [comment]
Oh yes... Which ATV is that? Its the same issue as stated above. Not yet fixed for the moment.

**Comment by Lojs** [comment]
It’s ATV4

**Comment by elgatito** [comment]
@Lojs @mrdest  please, try to download and install the plugin v0.0.50. 

There is a test fix for Xbox/iOS problem, so testing would be much appreciated!

**Comment by elgatito** [comment]
@rmonst3r  can you show the kodi.log?

**Comment by rmonst3r** [comment]
Yep, trying to figure out how to get it off the box.


On July 9, 2018 at 12:33:11 AM, Denis (notifications@github.com) wrote:

@rmonst3r <https://github.com/rmonst3r> can you show the kodi.log?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/elgatito/plugin.video.elementum/issues/4#issuecomment-403357027>,
or mute the thread

**Comment by rmonst3r** [comment]
Here it is: https://paste.kodi.tv/uxajifumom

**Comment by rmonst3r** [comment]
Yep the latest available on the site.

I just found out about Elementum so i would not have had an old install.

If you need me to test anything let me know, I'll help .

**Comment by elgatito** [comment]
@rmonst3r thanks, I will make another fix in the next version of plugin.

**Comment by elgatito** [comment]
Please, try the 0.0.53

**Comment by elgatito** [comment]
@rmonst3r @mrdest @Lojs Can somebody try to reinstall version to 0.0.55 and start on iOS?

**Comment by rmonst3r** [comment]
Hi Denis,

Same error: https://paste.kodi.tv/papilaluli

Ver 0.56

**Comment by elgatito** [comment]
@rmonst3r  thanks.
Thas is sad, it proves we can't run the binary on iOS, surely. The only way is to run with headless config, binary on non-iOS device and plugin without binary on iOS.

**Comment by elgatito** [comment]
I will make few changes to cleanup everything and, probably, try to make a proper document, describing how to configure it.

**Comment by rmonst3r** [comment]
K no problem.

Thanks for your work.
