### ISSUE TITLE
OpenSubtitles language support

### ISSUE THREAD

**Issue by elgatito** [elgatito/plugin.video.elementum#40]
OpenSubtitles always use english language and not taking in mind Kodi or system language.

**Comment by dankec2000** [comment]
Auto download default subtitle on start in desired language (as in Covenant?)

**Comment by hoshsadiq** [comment]
Why does elementum need opensubtitles support? Kodi already has opensubtitles support by simply installing another plugin. Works fine with any plugin playing.

**Comment by elgatito** [comment]
@hoshsadiq Elementum already includes OpenSubtitles support. It's looking for subtitles, depending on the current playing file. I'm not sure how separate addon will treat torrent files and will it find correct subtitles or not.

**Comment by hoshsadiq** [comment]
Current builtin Kodi support works 100% with Elementum as long as the torrents are named properly. Even if the torrents aren't named correctly, you can specify your own search string, however, by default, no subtitle providers are installed on Kodi. I've installed `service.subtitles.opensubtitles`, set it as default (Settings > Player > Language > Default TV show/movie service), then when you play a show/movie using Elementum, you can go to Subtitles > Enable then Download (similar as if you'd be using Elementum). Hence why I feel like it's better to leave this functionality to a separate addon and actually remove this completely from Elementum. That way Elementum can focus on it's the streaming and everything else it's good at, and other plugins can manage the subtitles. Additionally, plenty of other providers exist, so language is not an issue either.

**Comment by elgatito** [comment]
Looking into the code and can't see how OSDB is used at all. Looks like it's not active. So closing this for now.

**Comment by elgatito** [comment]
Okay. I have investigated this a little bit. Kodi is making requests on their own. And sends list of languages it wants to get.
To change the language for subtitles search, Kodi setting should be changed at Settings -> Player -> Languages -> Service Downloads -> Languages

**Comment by dankec2000** [comment]
Any Chance to implement auto download default (first) subtitle when starting video in desired language (as in Covenant, Exodus...?) Actually, it could be an option in settings (download subtitle on start - on/off)
