### ISSUE TITLE
[Request] A new setting for: Info language

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#400]
I have a request, if you could add an option for setting and selecting the info language for Movies and TV Shows (Titles, Descriptions info etc)
Also, it would be nice iff you can add a seperate selection for each content type, I mean for example, if you want to keep the Title with the original language but the description with the selected language etc.

Current Environment:
Elementum 0.1.24

**Comment by elgatito** [comment]
After reviewing the issue, I can say I would not do this. 
It will make a big mess and I don't think this is a good idea.
