### ISSUE TITLE
Burst doesn't find any result since 0.1.24

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#401]
It seems that since 0.1.24, Burst doesn't find any result while checking with Quasar (and Quasar burst) it does find results.

I'm testing it from Trakt My Progress.

Kodi Log:
https://paste.ubuntu.com/p/6xdn6V7fVv

## Your Environment
Elementum 0.1.24
Elementum Burst 0.0.35
Kodi 17.6
Windows 10, 64 bit

**Comment by zorge88** [comment]
Restart pc or Android box

**Comment by burekas7** [comment]
Thanks it's ok now.
Usually I just restart kodi.
