### ISSUE TITLE
Trakt sync not working properly

### ISSUE THREAD

**Issue by acsterf** [elgatito/plugin.video.elementum#402]
## Expected Behavior

- Remove a media from My Collection list if it is deleted from Kodi library - "Remove from Trakt (...)" checked;
- A Movie/Show/Episode marked as Unwatched should be synced back to Trakt - "Sync back Kodi watched (...)" checked;

## Current Behavior

- A media deleted in Kodi isn't removed from "My Collection" list in Trakt, and is re-added to library after a sync if "Sync from collections" is checked;
- Watched episodes marked as "Unwatched" in Kodi isn't updated in Trakt, and will be marked as "Watched" after a sync if "Sync watched states from Trakt into Kodi library" is checked;

Kodi 18.1 - Android TV 7.0.0
Elementum 1.24
Log https://paste.kodi.tv/uruqebuhay / https://paste.kodi.tv/p/P7K9vSDjXF

**Comment by homemdasneves** [comment]
Same here.

**Comment by elgatito** [comment]
@acsterf @homemdasneves  please, re-test with v0.1.38 and provide a fresh log. 
Thanks

**Comment by elgatito** [comment]
Closing without reply.

**Comment by acsterf** [comment]
After updating Elementum and doing a full wipe in Trakt list and in Kodi's library I can list embedded Trakt's elements that aren't working properly:

- Delete a Movie / TV Show from Library won't remove it from Trakt collection; "Remove from Trakt (...)" "My Collection" checked;
- Movies / TV Shows deleted from Library reappears after sometime;
- Deleted Movies / TV Shows DB count is zero even after several removals;
- Libray update with recent episodes and new shows added to Trakt list not working stand alone, a DB cache clearing and manual sync start necessary;

Kodi 18.4 - Android TV 7.0
Elementum 0.1.41
Log: https://paste.kodi.tv/deciselama
