### ISSUE TITLE
enabling authenticated socks5 prevents connectivity 0.1.24

### ISSUE THREAD

**Issue by xhiddle** [elgatito/plugin.video.elementum#403]
This ix x64 windows 10 pro using x64 elementum with burst 0.34

Enable socks5 proxy in elementum settings.  My provider requires username and password.  The debug log shows the correct spelling of both.  The host (ip address) is correct.  UNchecking "Use proxy for downloading torrent files" allows for burst results.  So (?) settings are not ignored, but socks5 not authenticating?

socks5 proxy DISabled in elementum returns full functionality.

setup socks
exit kodi
restart kodi

## Expected Behavior
on restart kodi after socks5 configuration expect internet not-blocked

## Current Behavior
Elementum only complains on screen when starting with a tmdb error. 

## Possible Solution
an option to show on screen or in popup the result of authentication attempts, or store to debug log.  Is it not connecting?  Is it not authenticating?  is there a server error?  is there a field syntax error?

## Steps to Reproduce (for bugs)

1.  uninstall kodi
2. wipe %appdata%\Kodi
3. install kodi
4. install elementum universal
5. install burst
6. my addons ..  video .. elementum .. information .. configuration .. proxy
7. add socks5 host, username, password,  server accepts port 1090
8. ressultant use behaves as if there is no internets

## Your Environment

* Version used:

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

Windows 10 Pro 64bit
Elementum 0.1.24 burst 0.34
Kodi kryton 17.6

debug log
https://pastebin.com/rESYn6B5

**Comment by ParDev** [comment]
This is the same issue I still have. Trying to use Socks5 authentication with username and password. Once enabling Socks5, I can see burst results and select torrent for downloading, however it just hangs after that. The downloads never begin and I don't see any error messages.

**Comment by shanusmcshan** [comment]
Same here using socks5 host, username, password - burst results (which do use proxy) are fine - but on selecting torrent it does not connect to peers and times out.

Elementum 0.1.24 burst 0.34
Linux 4.15.0-47-generic 
Kodi 18.1

**Comment by elgatito** [comment]
There is an error with setting proxy settings in libtorrent, when having user/password. 
Will be fixed in the next version.

**Comment by elgatito** [comment]
Please try with 0.1.25.

**Comment by ParDev** [comment]
Confirmed able to download now with 0.1.25 and Socks5 proxy authenticated and working! Thanks so much for the fix.

**Comment by elgatito** [comment]
Good. Closing the issue.
