### ISSUE TITLE
Несуществующий эпизод в "мой прогресс"

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/plugin.video.elementum#404]
## Current Behavior

![IMG_20190329_004639](https://user-images.githubusercontent.com/17964763/55200021-9a8acd00-51bc-11e9-9b14-c2db300bbadf.jpg)
В тракте его нет, вероятно он был добавлен по ошибке и потом удалён. Но из elementum  он не удаляется и сам не пропадает.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: 0.1.24

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

 https://paste.ubuntu.com/p/dTDPbW9fjk/

**Comment by antonsoroko** [comment]
И еще один
![1553979315728225127624208543765](https://user-images.githubusercontent.com/17964763/55281566-a13d4f80-5336-11e9-88c2-4fa8bb7aae35.jpg)

**Comment by antonsoroko** [comment]
держалось долго, но пропало само. может что-то есть смыл подкрутить в кэше, на будущее.

**Comment by elgatito** [comment]
@antonsoroko should be fixed with 0.1.41, watched show progress now checks changes with Trakt.

**Comment by antonsoroko** [comment]
Can't really check since it's not user controlled situation. But I hope it will be okay in future.

Thank you!
