### ISSUE TITLE
Download/playback stops when switching media position

### ISSUE THREAD

**Issue by kalika303** [elgatito/plugin.video.elementum#405]
Once a media correctly buffers and **starts** the playback, it seems to be impossible to switch from a time position to another (using the time bar, fast forward, changing chapter or whatever).

Even if a lot of connections **are active**, they suddenly drop to zero, the media execution stops and Kodi returns to the Elementum addon home screen, making impossible to resume a playback to a specific point.

## Expected Behavior
It should be possible to "move around", change chapter, or fast forward to a position of a media. **Not being able to resume a playback**, makes actually hard to watch a movie.

## Current Behavior
Connections **drop to zero**. It seems that somehow the download isn't able to continue again from another media position and disconnect from sources. 

## Steps to Reproduce (for bugs)
1. Get a torrent via a magnet
2. Use torrent URL and paste the torrent there
3. Wait buffering and let the playback starts
4. Try to switch to another position (e.g. change chapter). Do something extreme, like moving to the middle of the media
5. Wait for the playback to resume
6. If it starts (sometimes it does), wait to be sure connections are not lost and continue download

## Context / Env

* RaspberryPI 3B+, 
* Librelec 8.2.5,
* Kodi 17.6, 
* Elementun v0.1.24 (via all-in-one install)
* Using memory (default configuration) for dl/streaming
* Using a torrent URL: this doesn't track the position when the playback stops and makes even harder to resume a playback

**Comment by elgatito** [comment]
> Connections drop to zero. It seems that somehow the download isn't able to continue again from another media position and disconnect from sources.

What connections?
You should provide a proper log file (with enabled debugging), which shows your problem.

**Comment by kalika303** [comment]
You mean Kodi logs? Or is there some other log you need? Specific Elementum or torrent log?

**Comment by kalika303** [comment]
Have you been able to recreate the issue?

**Comment by elgatito** [comment]
> Have you been able to recreate the issue?

No.

> You mean Kodi logs? Or is there some other log you need? Specific Elementum or torrent log?

http://elementum.surge.sh/contribute/log/

**Comment by elgatito** [comment]
Please try with 0.1.25.

**Comment by elgatito** [comment]
There are changes in 0.1.27 to faster switch positions.
Closing as this is not really a bug, still have to find better settings for libtorrent.

**Comment by kalika303** [comment]
Ok, will test it and give feedback. Thanks.
