### ISSUE TITLE
Не работает на OrangePi LibreELEC 9.0.1 KODI 18.1

### ISSUE THREAD

**Issue by kuchka506** [elgatito/plugin.video.elementum#406]
Перестает запускаться после обновления на 9.0.1.
[NEW 01_KODI.log](https://github.com/elgatito/plugin.video.elementum/files/3026595/NEW.01_KODI.log)

**Comment by elgatito** [comment]
@kuchka506 побился файл базы данных. Удаляйте файлы `cache.db`, `-cache-backup.db`.
