### ISSUE TITLE
Медленная буферизация в самом конце буферизации

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/plugin.video.elementum#408]
## Current Behavior

С файловым бэкендом и более менее большим файлом буферизация сначала идет плавно, а после 99% очень медленно. Чем больше файл - тем заметнее.
![IMG_20190402_235128](https://user-images.githubusercontent.com/17964763/55438964-62f89800-55a3-11e9-8c2e-ff9aef7044a0.jpg)
![IMG_20190402_235138](https://user-images.githubusercontent.com/17964763/55438980-70ae1d80-55a3-11e9-8887-da97ee4c24af.jpg)
![IMG_20190402_235144](https://user-images.githubusercontent.com/17964763/55439001-7dcb0c80-55a3-11e9-90a0-8f17f630e1ef.jpg)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: 0.1.24

* Environment name and version: spmc 17.4

* Operating System and version:

* Link to Kodi debug log: https://paste.ubuntu.com/p/rWFqnNncs7/

**Comment by elgatito** [comment]
Можно пробовать включить deadlines в настройках, закладка bittorrent.
Дополнение только ставит приоритеты кускам файла.

**Comment by antonsoroko** [comment]
Включил. Пока только на одном торенте поверил, но вроде стало лучше. Погоняю еще и отпишусь. Спасибо!

**Comment by elgatito** [comment]
Please try with 0.1.25.

**Comment by antonsoroko** [comment]
С включёнными или выключенными deadlines?
На 0.1.24 с включенными я вроде больше проблемы не наблюдал.

**Comment by elgatito** [comment]
> С включёнными или выключенными deadlines?

С версии 0.1.25 по-умолчанию с deadlines.

**Comment by antonsoroko** [comment]
Вроде все ок, спасибо!
