### ISSUE TITLE
4k content stops playing after some seconds playing

### ISSUE THREAD

**Issue by riegaz** [elgatito/plugin.video.elementum#411]
I just got the new odroid n2 and wanted to test your plugin and found it fails playing 4k content. I'm wondering if it is a kodi related or addon related issue.

The log file is here:
http://s000.tinyupload.com/?file_id=10548599236031949848

**Comment by elgatito** [comment]
@riegaz nothing special in the log. Can you try to increase buffer to at least 50mb? And maybe increate memory size, as big films need more memory for keeping good speed.
I will ask then to try next version, will be available soon.

**Comment by riegaz** [comment]
I set the buffer to 100mb and the memory size to maximum. Nothing changed, it also didn't play any longer than before. Further ideas are welcome.

**Comment by elgatito** [comment]
For 65GB files you need at least 150Mb internet channel. 
You can manually set memory size for torrent. For this size of torrent it should be at least 200mb.

**Comment by riegaz** [comment]
I just set both, the torrent file and the buffer to 400mb and it seems to work now. Is this something which could work by auto detection as well or should I leave the settings like this?

**Comment by riegaz** [comment]
BTW. Loading bigger 4k movies sometimes gives me a timeout while buffering. The buffering keeps running but then the movie just doesn't start to play. I think this is not wanted right?

I would say if there is a timeout, it should stop the buffering?!

**Comment by elgatito** [comment]
> I would say if there is a timeout, it should stop the buffering?! 

There is a setting for buffering timeout (the dialog window that comes before starting playback).

> Would it make sense to set the torrent buffer to around this size automatically depending on each individual movie?

There is automatic buffer/memory size adjustment, but it checks for free memory on the device and does not do the adjustment if you don't have a lot of memory, so if you need heavy torrents - you have to manually increase memory to some bigger values.

> Sometimes I get the "content was not able to play message" even though I just leave the available torrent window and never tried to play anything. 

I don't understand this. Where you get the error? Logs, that list the error, are always welcome.

**Comment by riegaz** [comment]
> There is a setting for buffering timeout (the dialog window that comes before starting playback).

I know that I can increase the timeout there. However, its behaviour is not correct, at least to me. If there is a timeout message telling me that it took too long to buffer a file it should either interrupt the file buffering or not show up at all. Right now the timeout is shown, the file keeps buffering to 100% but then the content doesn't start playing. It is by far not a serious thing. I was just wondering.

> There is automatic buffer/memory size adjustment, but it checks for free memory on the device and does not do the adjustment if you don't have a lot of memory, so if you need heavy torrents - you have to manually increase memory to some bigger values.

I do have 4gb of memory, this should be by far enough, shouldn't it? I can leave it set manually, no problem here.

> I don't understand this. Where you get the error? Logs, that list the error, are always welcome.

I'm not sure now about the wording but elementum displays a popup telling that it was able to play the file. It is a standard popup which was there always. I will make a quick video that shows what I mean.

**Comment by elgatito** [comment]
Please try with 0.1.25.

**Comment by elgatito** [comment]
Please, check v0.1.27.

**Comment by riegaz** [comment]
I just tried, did you change something about the buffering of 4k movies? I didn't reset the values yet.

Concerning the popup: it is still showing up for no reason. Here is the video:

https://send.firefox.com/download/e4f30e6463fe8934/#UqqxJnKN_fADUyXrba88UQ

The password is "ele"

**Comment by elgatito** [comment]
Oh. The link is already expired. Can you re-upload it? 
And also, please, try 0.1.28.

**Comment by riegaz** [comment]
I just installed 0.1.28. I reset my settings and when the buffer size is set to the default 20mb a 4k torrent only plays for some seconds before it start to stutter. Setting it to 200mb still stops after some more seconds. 

I see that an increased buffer is needed for the playback of bigger content. However setting the buffer to 400mb is annoying when playing 720p or 1080p content since it still wants to buffer 400mb of it before it starts to play.

Any ideas for this? Something like a variable buffer depending on the file size? Or individual settings for different resolutions?

Do you still need the kodi debug log? I think it is easy to reproduce now?!

**Comment by elgatito** [comment]
> Do you still need the kodi debug log? 

Yes.

> I think it is easy to reproduce now?!

Reproduce what? I don't have any problems with playback. It does not mapper its' 4K or 240p.

**Comment by riegaz** [comment]
1. Buffer set to 200 and 50mb. I receive the message that the read rate is too low for continuous playback
https://send.firefox.com/download/9ce90e7aa475d374/#etz2JtPDoajE_JKsKyL0xg

It seems it doesn't stop playing anymore, there are only long freezes.

**Comment by elgatito** [comment]
Your download speed is too low for streaming 80Gb files. You need 200Mbit internet channel for such speeds.
You can try to increase memory size, but I'm not sure it will be enough.
There is nothing to bug with this issue.

**Comment by riegaz** [comment]
I do have a 1Gbit internet, so I guess it is by far sufficient?!

**Comment by elgatito** [comment]
There is nothing to help with. You device cannot make good speeds to stream so big files.
