### ISSUE TITLE
Video doesn't play after buffer

### ISSUE THREAD

**Issue by tehnards** [elgatito/plugin.video.elementum#413]
Video buffers from tracker, then returns to selection screen. Log is attached. Thanks in advance.
[kodi.log](https://github.com/elgatito/plugin.video.elementum/files/3075809/kodi.log)

Elementum 0.1.24
Kodi 18.1
Windows 10 Home

**Comment by tehnards** [comment]
There was an issue with that particular file.

**Comment by elgatito** [comment]
You log does not have any information.
You should follow instructions for providing proper log file - http://elementum.surge.sh/contribute/log/

**Comment by elgatito** [comment]
Please, make a proper log file, not piece of log.

**Comment by elgatito** [comment]
@tehnards 
I will close the issue if there is no response.

**Comment by elgatito** [comment]
Closing without no response.
