### ISSUE TITLE
Subtitles folders

### ISSUE THREAD

**Issue by marcoscamurati** [elgatito/plugin.video.elementum#417]
I can not access the folders on my system when I want to put a caption that I downloaded, only the "plugin" folders appear! Does anyone know how to access the system folder?

Version 0.1.26
Kodi 18.1 Leia
Android TV 8.0

**Comment by elgatito** [comment]
I do not understand what you mean.

**Comment by marcoscamurati** [comment]
Sorry if I could not be clear, I'll send some frames I think will help explain.
But I meant that I can not access the root folders of my Android TV when it is on screen by selecting a subtitles.
I'll soon send frames to stay clearer.

Thank you

**Comment by elgatito** [comment]
Would be cool if you could make a photo/screenshot of what you talk about.

**Comment by marcoscamurati** [comment]
Frames that they think will explain better.
But the summary is how much in the selection of subtitles I can not access the subtitles that I downloaded on my android tv! I do not have access to system folders.

![IMG_9807](https://user-images.githubusercontent.com/49660327/56240910-eff32500-606a-11e9-94f1-a695cda1acc0.JPG)
![IMG_9809](https://user-images.githubusercontent.com/49660327/56240934-00a39b00-606b-11e9-9a28-4af6de536258.JPG)
![IMG_9810](https://user-images.githubusercontent.com/49660327/56240960-0bf6c680-606b-11e9-99dd-8a73c4e67530.JPG)

**Comment by elgatito** [comment]
When you select "Choose subtitles" - Kodi is starting file selector window. It's not from Elementum. 
Local subtitles will not work with Elementum.

You should use "Download subtitles" (next option), to use subtitles addons to find subtitles for Kodi.
