### ISSUE TITLE
Movie Stops When I Resume playback 

### ISSUE THREAD

**Issue by Tarek-Depp** [elgatito/plugin.video.elementum#418]
Hi ,

Every time I resume playback the movie stops by it self .
And one more thing , also I always receive a message " Not Found"  why?
Thanks.

**Comment by elgatito** [comment]
You should provide log file and give more information about your issue.
http://elementum.surge.sh/contribute/log/

**Comment by elgatito** [comment]
@Tarek-Depp I will close the issue if there is no response.

**Comment by elgatito** [comment]
Closing without no response.
