### ISSUE TITLE
"resume N seconds earlier" does not work (without library integration)

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/plugin.video.elementum#419]
## Current Behavior

Now elementum keeps state in internal database (if I am not mistaken) but "resume N seconds earlier" does not work from "movies->my watchlist" for example.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:

0.1.27
* Environment name and version:

Smpc 17.4
* Operating System and version:

Android tv 8
* Link to Kodi debug log:

https://paste.ubuntu.com/p/WN2Jydjg3f/

**Comment by elgatito** [comment]
You have set store resume action to "0". There was wrong label for that setting. 
Correct should be: No - Ask - Yes. 
Your setting is "No" which disabled storing resumes.

**Comment by antonsoroko** [comment]
I tried all 3 options (оставить, удалить, спросить) - nothing chanded.

**Comment by elgatito** [comment]
Please, try 0.1.28, it now forces seek regardless, what Kodi wants, to seek or not.

**Comment by antonsoroko** [comment]
Now it works as you said (but only if I tick the option to force resume) - thank you.
but this is kind of ambiguous because it is not correlate with user input - i choose to start from the beginning but elementum force "seek" (that kind of make sense since i tick "force" option, but what i am trying to say is that this is not really logical/convenient). this could be "fixed" by using "ask for resume" option in elementum but this is also not really convenient because you have to confirm your choice twice.
Also one time I saw different resume time data in kodi and elementum.

If it is even possible, would be nice to make this feature more, let's say, "native".

Thank you.

**Comment by elgatito** [comment]
> If it is even possible, would be nice to make this feature more, let's say, "native".

No. 
Kodi not always asking for resuming playback, even when it shows that item is in watch progress. And so is settings "resume=false" to playback request. That is why there is a force resume option. You cannot disable default Kodi dialog to resume.
