### ISSUE TITLE
Ошибка после установки и при запуске на Android TV

### ISSUE THREAD

**Issue by myststudio** [elgatito/plugin.video.elementum#420]
TV TCL S6500. Android TV 8. 
Kodi 18.1 (пробовал так же 17), Elementum 0.1.25.
После установки (и при каждом запуске) плагина выходит ошибка. При этом плагин открывается, настройки меняются, но не работает (как будто не видит сеть). На другом устройстве все работает.
Лог:
https://paste.kodi.tv/uwucojuhak

**Comment by elgatito** [comment]
Попробуйте версию 0.1.28.

**Comment by myststudio** [comment]
Также установка и запуск с ошибкой
https://paste.kodi.tv/eweyucekew

**Comment by elgatito** [comment]
Попробуйте еще раз с версией 0.1.29, пожалуйста.

**Comment by myststudio** [comment]
Добрый день!
По прежнему ошибка Elementum. Может выгрузить какую-то дополнительную информацию?

Лог:
https://paste.kodi.tv/zipeqamomu

**Comment by elgatito** [comment]
А откуда Коди ставили? Он выглядит каким-то необычным (что не может встроенный в себя код запустить).

**Comment by myststudio** [comment]
Ставил с PlayMarket. 
Возможно проблема с данным ТВ (AIDA показывает что процессор 64  бита, но работает в режиме 32 бит).
Попросил других владельцев попробовать запустить KODI + Elementum у себя.

**Comment by elgatito** [comment]
@myststudio 
Please, try v0.1.30.

**Comment by myststudio** [comment]
Теперь устанавливается без ошибки. Но при запуске выдает "OsError 8 Exec format error.
Если повторно запустить, запускается с уведомлением "Похоже Elementum еще стартует. Подождите".  

ЛОГ: https://paste.kodi.tv/forofameqo

Пробовал ставить SPMC все тоже самое.
У других пользователей данной модели аналогичная проблема.

**Comment by elgatito** [comment]
Please, try v0.1.31.

**Comment by myststudio** [comment]
Теперь все работает отлично!
Спасибо за ваш труд!
