### ISSUE TITLE
Runaway memory usage with memory caching

### ISSUE THREAD

**Issue by soulnull** [elgatito/plugin.video.elementum#423]
## Expected Behavior

Nothing works after updating... Just kidding.. A smooth stream of win and happiness.
## Current Behavior

A stream that plays for a while, but eventually gets choppy and locks up the entire box
## Possible Solution

I believe the issue may be related to my "zero cache" (I run a zero cache buffering to a 500gb HDD because I like smooth seekability). However, I specify a maximum amount of memory in the addon for it to cache, disabled "use advanced settings" in the torrent settings, and I set the buffer size lower as well.. It blows right past any limit I set until it locks up the box. This wasn't an issue until the latest update, since I cached to filesystem on the earlier version, but that's not working for me currently (see /issues/421)

## Steps to Reproduce (for bugs)

1. Open Kodi
2. Open Elementum, select an excellent and completely public domain torrent
3. Watch video, smile, think of the wonders of how awesome technology is for all the cool things it can bring us
4. Frown when it gets choppy and stops responding to remote commands or ssh

## Context

I started with Elementum a few days ago, and love the hell out of it. Best addon ever, in my opinion. But a few times it's frozen my boxes (Sunvell T95Z Max, Amazon FireTV 2nd gen). Finally had an SSH session into it running top, and until the torrent starts on the Sunvell, Elementum consumes 1.3% of my RAM. As soon as I open, it starts gobbling up RAM like a vampire looking for blood, or a zombie looking for brains. When I end the stream, RAM usage stays inflated until I disable the addon and reenable it. If I start another, it continues to climb, unless I reset between plays. I had similar issues, though not as severe, when disk caching was working.. But I think it's because I left my event log turned on... I can't confirm if this was the original issue with disk caching and memory leaking, but it seems like I'm getting leaks regardless of what I do with my FireTV/Sunvell T95Z Max (coreelec) boxes.

## Your Environment

* Version used: 0.1.28

* Environment name and version: Uhh.. 0.1.28?

* Operating System and version: OpenELEC 9.01, FireTV 2nd gen

* Link to Kodi debug log: I apologize, it's late and I will totally send one as soon as I get more time if you'd like, but I wanted to get this on the radar since it may be a known issue/log may not be necessary. Otherwise, could you please let me know where in the memory filling process to save it? Because if I just let it go until it fills up, the box is unresponsive, so I need to save it at some point before it fills up the memory... Which may not be useful.. I'm not sure. Please let me know.

**Comment by elgatito** [comment]
Log file is needed.

What is your problem in less words? Device Out of memory? Playback stops? Or what?

**Comment by soulnull** [comment]
Sorry, im wordy. Playback gets choppy and freezes within a few minutes of starting when in memory caching playback mode. RAM usage of elementum climbs until box freezes despite settings/limits to buffer/cache sizes.

When in the process should I pull in the log file? The entire os goes unresponsive, forcing a hard reboot, so should I let it get to about 50% system ram usage or so (750mb used by elementum) and then download the log? Less? More? Please let me know.

**Comment by soulnull** [comment]
It appears this is a duplicate of issues/412. Will close. Suggest maybe disable "high speed" as a "libtorrent settings profile" in the meantime, as it appears to ignore the memory cache settings.

**Comment by soulnull** [comment]
@elgatito I closed this because it's a duplicate, but the issue still exists when I set "high speed" in "BitTorrent settings" (obviously the workaround is to use "normal" for now). Memory limits are ignored if playing from memory cache, caching to disk makes no difference, and even stopping playback/cancelling the download/deleting the file does not bring memory usage back down, which requires disabling/reenabling the plugin to restart the elementum process. This very well may be a libtorrent issue, but here's a log anyways in case it's not. [log file here](https://paste.ubuntu.com/p/RF9pHc7wbx/)

I let it go until memory usage of the elementum process was at ~50% RAM usage, then stopped playback, cancelled download, and deleted file (using elementum dialog boxes set to "ask"). Memory usage, as I type, still sits at 53.6% fior the elementum process, and it is not currently doing anything. Worth noting: It never goes above 10% when not using "high speed", even if using memory cache.

**Comment by elgatito** [comment]
1) libtorrent profiles are settled up by libtorrent.
2) Users reported about memory usage on highspeed profile.
3) I would not recommend changing from default profile.
4) When you select memory size - you select size for storing torrent data, not memory used by application. Release of virtual memory is done by garbage collectors, application is not controlling memory release.

**Comment by soulnull** [comment]
Alright, thanks for the info... And for picking up this project.
