### ISSUE TITLE
Completion percentages jumping around in file cache mode

### ISSUE THREAD

**Issue by soulnull** [elgatito/plugin.video.elementum#424]
## Expected Behavior
Percentages showing how much of the download is completed. 

## Current Behavior

Percentages do not reflect the status of the download when caching to disk, as noted in /issues/421

## Steps to Reproduce (for bugs)

1. Enable file cache mode
2. download something
3. Pause to see wildly inaccurate and constantly changing number, or view on /web, or in the "torrents" entry in the main menu
4.

## Context

Have no clue what the download is actually doing...

## Your Environment

* Version used: 0.1.29

* Environment name and version: firetv, coreelec 9.01, Kodi 18.1, 18.2 rc

* Operating System and version:

* Link to Kodi debug log:

https://paste.ubuntu.com/p/j9FQpfztR7/

**Comment by antonsoroko** [comment]
btw, in old (and new) versions i sometimes had a similar issue during buffering stage.

**Comment by MichaelAndoid** [comment]
Same problem.
Sometimes says 100% but if I close Kodi and open again it's only 20%.

Downgrade to 0.1.27 is ok.

**Comment by luispabon** [comment]
I thought it had got fixed in 0.1.29 but it hadn't. Whatever changed did improve, but not fix it, downloads would pause at 99%. Upon downgrading to 27 these downloads were in fact around 80%.

Kodi 18.1, Ubuntu 19.04

**Comment by elgatito** [comment]
I'm working on fixing this in the next version.

**Comment by luispabon** [comment]
Superb, thank you :+1:

**Comment by elgatito** [comment]
Please, try v0.1.30.

**Comment by soulnull** [comment]
Same issue. I'll try to describe a behavior that may help in diagnosing. The percentages do still jump around, but if i pause it and even restart Kodi, then play back from the "torrent history" menu, the percentage reads correctly until it starts downloading again, and then the percentages start jumping around again.

Not sure if that helps to narrow it down, but if there is anything i can do to help on my end, please let me know.

**Comment by elgatito** [comment]
Log is needed.

**Comment by soulnull** [comment]
I'm on it. Here are two logs: first is just starting the torrent. Second is after restarting Kodi and trying to resume the same torrent from history. Hopefully this difference helps.

http://953fm.cc/log1.log
http://953fm.cc/log2.log

Anything else needed? Let me know, will do what i can to help.

**Comment by elgatito** [comment]
Please, try v0.1.31.

**Comment by MichaelAndoid** [comment]
[bug 1] % initial loading from 99.0 to 100 takes 2 minutes.
FIXED

[bug 2] stop downloading shows 100% and I can't resume, after restart Kodi shows 10% and I can resume.
FIXED

**Comment by soulnull** [comment]
Rozwiązany. Dziękuję Ci.
