### ISSUE TITLE
Downloading is stopping after buffer is 100%

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#425]
I have a strange behavoiur:
The downloading starts, the speed also starts to increase, it reaches to the buffer (~38M), the playback started, it continue the downloading a little more, then stopped suddenly (after 67.7M), in the torrents list it shows 100%, when I open the context menu it shows the option of "Resume torrent" (And I never stop the downloading), and the downloading isn't contiune. seems to be stuck or something.
* I checked it twice, still the same.

(The watching is through the Trakt Progress: Black Mirror S03E06)

Kodi Log:
https://paste.ubuntu.com/p/8RZxsFFH39

Elementum 0.1.29
Kodi 17.6
Win 10 , 64bit

**Comment by MichaelAndoid** [comment]
Same problem.
Says 100% and don't let me to resume but if I close Kodi and open again it's only 20% and I can resume now.

Downgrade to 0.1.27 is ok.

**Comment by susobaco** [comment]
Same problem, when the playback stops in the search and download of subtitles, the download also stops.

**Comment by burekas7** [comment]
> Same problem.
> Says 100% and don't let me to resume but if I close Kodi and open again it's only 20% and I can resume now.
> 
> Downgrade to 0.1.27 is ok.

Yes, I have noticed that too later, when closing and opening kodi and resume, it seems that the downloading is back to the original percentage and continue.

**Comment by elgatito** [comment]
I'm working on fixing this in the next version.

**Comment by elgatito** [comment]
Please, try v0.1.30.

**Comment by MichaelAndoid** [comment]
Same problem one 0.1.30
Says 100% and don't let me to resume but if I close Kodi and open again it's only 10% and I can resume now.

Downgrade to 0.1.27 is ok.

**Comment by elgatito** [comment]
@MichaelAndoid I can't reproduce it. I choose an episode - it starts buffering, then playback starts. I restart Kodi. Go to torrents list. Start playback and it starts fine.
What do you do?

**Comment by burekas7** [comment]
Me too.
Still the same as I described with 0.1.30.

1. The download starts ok.
2. When the buffer is almost react to its 100% ( =38MB), another problem is that the buffer percentage start to "slow down" on ~99% (while the download speed still the same) - It's another issue.
3. But after it reach to 100% the playback starts.
4. I pause the playback, press the "Tab" key in order to see the backgroind progress notification, it still shows strange percentage value which not indicate the actual total torrent progress when finally it reach to 100%, I don't know which progress it actual follows, 
5. I stop the playback and confirm the dialog for continue the downloading.
6. I check the torrents list, and it shows that the torrent is 100%.
7. In my files system the file usage is stuck on 67.7MB.
8. Restarting kodi, the progress notification and the torrents list shows the correct value, and it seems the download is continue (also the file usage start to increase)

I check it for example with Black Mirror S03E06
![image](https://user-images.githubusercontent.com/13424257/56849640-b7bbd400-68ff-11e9-92b0-2848c8b390c6.png)

Kodi Log (with debug mode):
https://paste.ubuntu.com/p/zt56TK7Zmf

**Comment by MichaelAndoid** [comment]
I have the same bug mentioned in point 2, but this bug is old I can reproduce on 0.1.27, and 2 versions before.
From 0 to 99.0% 6 secounds, but from 99.0 to 100% takes 2 minutes and the speed don't decrease.
Sometimes the slow starts ate 96%.

**Comment by elgatito** [comment]
Please, try v0.1.31.

**Comment by burekas7** [comment]
Now with 0.1.31 it's much better and finally works as should be. Thanks.

Sometimes when the buffer close to its 100% it seems that the download speed start to decrease, but then when I pause the playback to see the download speed, it usually back to normal speed. Is it normal?

**Comment by elgatito** [comment]
> Is it normal?

Yes. Which piece and when to download - decides libtorrent. 
Before 0.1.31 not all pieces of a file were marked for download.

**Comment by MichaelAndoid** [comment]
[bug 1] % initial loading from 99.0 to 100 takes 2 minutes.
FIXED

[bug 2] stop downloading shows 100% and I can't resume, after restart Kodi shows 10% and I can resume.
FIXED
