### ISSUE TITLE
solution for croatian translation

### ISSUE THREAD

**Issue by adiadi2** [elgatito/plugin.video.elementum#427]
Hi, solution for closed and not fixed issues #270 and #372 is to add (%s) into translated string at msgctxt "#30415" of the elementum croatian language strings.po file.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

**Comment by elgatito** [comment]
It really helps?
I will add this to the next version.

**Comment by elgatito** [comment]
I have added this fix for 0.1.30

**Comment by elgatito** [comment]
Closing. Change was added to 0.1.30.
