### ISSUE TITLE
Does not exclude unwanted resolutions

### ISSUE THREAD

**Issue by hp-je513l** [elgatito/plugin.video.elementum#432]
I have my settings to exclude 720p and 480p but it still retrieves them. I'm using a Fire TV 4K (3rd gen)

**Comment by elgatito** [comment]
Where did you exclude resolutions? 
Elementum does not filter results, received from search plugins (like Burst).

**Comment by hp-je513l** [comment]
Under Program Add-ons => Elementum Burst => Resolution.

**Comment by elgatito** [comment]
Burst can filter results. Elementum is not removing anything.
