### ISSUE TITLE
Option to auto download subtitles only if there are no embedded subtitles in video container

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/plugin.video.elementum#433]
## Expected Behavior

Часто в видео файле уже есть субтитры, правильно синхронизированные под видео. Иногда елементум скачивает неподходящие (не синхронизированные под конкретное видео) субтитры. Но так как сейчас елемент качает субтитры всегда, то часто скачанные субтитры оказываются выше по списку чем встроенные. Что в случае несинхронизированных субтитров - проблема. Короче говоря было бы здорово не качать субтитры если они уже есть в видео файле (mkv контейнер как пример), если возможно конечно. Спасибо.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

**Comment by elgatito** [comment]
Option has been added to 0.1.35. 
Alongside, previously subtitles were added before video initialization, not it is done after video container has been read and we know if there are any existing subtitles' streams added to the player.

**Comment by antonsoroko** [comment]
Works like a charm. Thank you!
