### ISSUE TITLE
Lost of download progress of 1st episode in season pack when start to download 2nd episode 

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/plugin.video.elementum#435]
## Current Behavior

Dowbloaf 1st episode in season pack completely theen start to download 2nd episode , then try to start 1st episode - downloading is starting again from 20% with strange buffer size (150mb instead og usual 60mb). After unexpected crash/reboot looks like 1st episode again is 100% downloaded.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

spmc.log (after unexpected reboot) 
https://paste.ubuntu.com/p/sKVpkNfVKv/
spmc.old.log (before reboot , issue should be hete)
https://paste.ubuntu.com/p/ghhcv56c4Z/

**Comment by antonsoroko** [comment]
it's still an actual problem.
in general work with season pack with file storage is unstable.

**Comment by elgatito** [comment]
Log is already not available.
It is probably better to totally remove file storage in plugin.

**Comment by elgatito** [comment]
@antonsoroko 
I'd ask you to make new log, but, keep in mind, that in 0.1.38 database was changed and it will probably lost which file you were trying to download once torrent was added.
So you will need to add some new torrent, select the file and so on.

**Comment by elgatito** [comment]
Please, re-test with 0.1.41.

**Comment by antonsoroko** [comment]
Will do. Thanks.

Btw
>It is probably better to totally remove file storage in plugin.

please don't :-) file storage is only option when you have to use VPN and your device is not powerful enough to provide good net speed with VPN, or when you simply have a slow internet connection, or even when number of seeds are low and inconsistent (very often case for old videos).
Thank you.

**Comment by burekas7** [comment]
@antonsoroko 
I'm agree.
This is the only option I'm using since I have used Quasar/Elementum.
Don't remove it.
Usually it works well.

**Comment by antonsoroko** [comment]
By the way i was not able to reproduce this bug.
I guess it was torrent file specific and since log file is lost and i don't remember which torrent it was i am going to close this issue.
Thanks.
