### ISSUE TITLE
Occasional reboots on android TV during download

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/plugin.video.elementum#436]
## Current Behavior

I guess i already faced this issue 10 times. Usually during download of one torrent and watching another. Started recently, maybe several weeks ago.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:

* Environment name and version: spmc 17

* Operating System and version: android TV 8 , xiaomi mi box 3

* Link to Kodi debug log:

Log before unexpected reboot
https://paste.ubuntu.com/p/ghhcv56c4Z/

**Comment by antonsoroko** [comment]
To be honest it reproduces very often. Loke every time i download something big (more than 20-30 minutes of download)

**Comment by elgatito** [comment]
Plugin does not interact with a system/OS. 
I have no ideas what is the reason for reboots and what can cause them. You can try to debug or something like that.

**Comment by elgatito** [comment]
In version 0.1.35 linux binaries are built statically with use of Musl, instead of dynamically linking to libc.
I'm not sure how android works in that field. 
Can you try to run manually linux arm64/admv7 binaries on your android? Will it run or not?

**Comment by elgatito** [comment]
@antonsoroko do reboots still happen with 0.1.38 and later?

**Comment by antonsoroko** [comment]
can not say for 0.1.38. need more time. with pre-0.1.38 reboots happen from time to time. Usually when several torrent are downloading at the same time (looks like "big" I/O issue, not sure if it is OS, HW or app issue).

**Comment by elgatito** [comment]
@antonsoroko you don't use memory storage and you use android, which does not use musl for builds. So you should not have Out-of-memory errors.
Maybe worth trying to use latest Android NDK to prepare binaries.

**Comment by antonsoroko** [comment]
looks like this issue is gone. closing. thanks.
