### ISSUE TITLE
Question about working with web interface

### ISSUE THREAD

**Issue by MasterSoft24** [elgatito/plugin.video.elementum#438]
Hi! I have a question about torrent adding with The WebUI. If I send a request like `http://KODI_IP:65220/torrents/add` with a magnet in `uri` parameter then torrent will be added but downloading doesn't start while I don't press the play button. How I can download the whole torrent without play it? By other words, can I use Elementum like a torrent client?

**Comment by elgatito** [comment]
In latest version, when you add torrent via Web - you have new button for downloading all files. It will start to download, without starting playback.
