### ISSUE TITLE
Issue with video cache buffer

### ISSUE THREAD

**Issue by peter099** [elgatito/plugin.video.elementum#439]
I am using Elementum with its default settings, with torrent download to RAM memory. When the pre-buffer is downloaded Elementum starts playing the video, but if i check the video cache buffer (Ctrl+Shift+O) it does not go more than 7.50 mb. I tried to set fixed RAM usage and disabled 'Choose memory size automatically' using the default memory size of 100 mb, but the video cache still won't go more than 7.50 mb.
Why is this limit of 7.50 mb and how can i increase it? The default Kodi buffer size is 20 mb and when i stream from remote server video cache goes over 7.50 mb, so i think the problem must be with Elementum. I am using Kodi Krypton and Elementum 0.1.31 on Windows 7 x64 and the RAM memory of my laptop is 4GB. I don't use also advanced settings file.

**Comment by elgatito** [comment]
@peter099 what is "video cache buffer"? 
Elementum is not filling any caches in Kodi. It's all managed by Kodi itself.

**Comment by peter099** [comment]
Yes, it seems that i have to use advanced settings file to modify the video cache size, though i don't understand why the cache does not filling up to 20 mb, which is the default Kodi settings, but stops at 7.50 mb.

Also, i don't understand what is the purpose of the option 'Choose memory size automatically' in Elementum since Kodi do not use more than 7.50 mb of the RAM memory. 

"@peter099 what is "video cache buffer"?" - I mean video cache size: https://kodi.wiki/view/HOW-TO:Modify_the_video_cache

**Comment by elgatito** [comment]
@peter099 if you select to use Memory for downloading torrent, then you have to define amount of memory, that can be used for that. Elementum is not interacting with Kodi about buffers and their sizes.  That is all controlled by Kodi.

**Comment by elgatito** [comment]
When you select to download with memory storage - you need some memory size, to be able to flawlessly stream the file to Kodi, when Kodi asks for another piece of that file. 
More memory you give to Elementum - bigger speed have.
