### ISSUE TITLE
Buffer size 

### ISSUE THREAD

**Issue by tipitao** [elgatito/plugin.video.elementum#440]
Hi

I have Kodi 18.2 x64 with 8 GB RAM. When i start a torrent with 2 Gb i see  buffer is 650 MB aprox. (for torrent with 700 mb buffer size is same  650 mb aprox. ) and i delay many time to start view movie. In Elementum is posible modify buffer size parameter?

Regards

PD Sorry for my english......

**Comment by elgatito** [comment]
@tipitao 
You can disable automatic memory size, in Elementum settings and set any size manually.

**Comment by tipitao** [comment]
Ok thanks. What is relation between memory size  and buffer 1 to 10?
example, if i have 6'5gb ram free, buffer amount will 650 mb aorox?

Many thanks and sorry my english level

**Comment by elgatito** [comment]
There is no relation between buffer size and memory size. 300 mb should be enough for any video file, but your internet speed should be also able to download that video bitrate.

**Comment by tipitao** [comment]
Ok.... thanks
