### ISSUE TITLE
Reloading Configuration Error LOOP process

### ISSUE THREAD

**Issue by pitkevich80** [elgatito/plugin.video.elementum#442]
When launch plugin, got error 
[http://prntscr.com/nwmst6](url)
Elementum Error.. 
And Loop process Reloading Configuration.. Possible fix somehow?

**Comment by elgatito** [comment]
Log file is needed.

**Comment by pitkevich80** [comment]
> Log file is needed.

okay, one moment.

**Comment by pitkevich80** [comment]
[kodi.log](https://github.com/elgatito/plugin.video.elementum/files/3244960/kodi.log)
here is the log file

**Comment by elgatito** [comment]
Error from python that it could niot bind to a socket. Have you tried to reboot whole pc?

**Comment by pitkevich80** [comment]
Yeah it help  ! Thanks a lot!

**Comment by elgatito** [comment]
Huh. Great, it helped you.
Sadly, Windows not always releasing the network port promptly and needs a "good" restart.

**Comment by pitkevich80** [comment]
> Huh. Great, it helped you.
> Sadly, Windows not always releasing the network port promptly and needs a "good" restart.

Yeah i think so.. Now i know what to do if error will happened again ;) 
Thank you!
