### ISSUE TITLE
Empty Movie List

### ISSUE THREAD

**Issue by kavuraki** [elgatito/plugin.video.elementum#444]
Whenever I click movies from main menu of Elementum it is all empty. Tv Shows work normal. All sub lists exist. but Movies is completely empty. I reinstalled Elementum but didn’t work.

**Comment by elgatito** [comment]
You can try to clear cache from plugin settings menu. (last tab)

**Comment by kavuraki** [comment]
unfortunately didn’t work after clearing cache. I also reinstalled it with deleting all user data.
