### ISSUE TITLE
Anime in elementum

### ISSUE THREAD

**Issue by Asunix666** [elgatito/plugin.video.elementum#445]
Please remove anime's in recent episodes/ recent tv shows since ti'll this day they don't work!

**Comment by elgatito** [comment]
I don't understand what you want.

**Comment by Asunix666** [comment]
Well, elementum shows episodes from an anime i select but it can't find the right torrent from that episode i choose. It gives me different results from tv shows not even related to anime's.

**Comment by elgatito** [comment]
Searching is done by other plugins, Elementum is only sending request for a search.

**Comment by antonsoroko** [comment]
@Asunix666 this means that probably you need to configure search plugins (like Burst) first to enable anime related torrent tracker.
