### ISSUE TITLE
No link found when start a video from the search tool

### ISSUE THREAD

**Issue by lexcyr** [elgatito/plugin.video.elementum#449]
## Expected Behavior

After searching a video and got a result i should be able to start the video.
## Current Behavior

When i launch the video from the result i always have error: "no link found"
I might do something wrong, as i am a complete newbies on this. But it's weird that when i go to the website of the provider and copy the link i am able to add it in elemtum and start the movie without issue.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

It would be really good to be able to search the videos, directly from elementum, or from the web interface and start it from that result. Instead of actually go to the torrent website and copy the torrent link everytime in Elementum.

## Your Environment

* Version used: 

* Environment name and version: elementum burst 0.0.36 by elgatito /Elementum 0.1.35 by elgatito
 Kodi 18.2 on Raspbery Pi 3 B+
* Operating System and version:

* Link to Kodi debug log: http://paste.kodi.tv/yikeqofuke

**Comment by elgatito** [comment]
@lexcyr  in your log you search for a movie and it is not found within selected providers.
What did you expect if something is not found?

**Comment by lexcyr** [comment]
i am using the menu already in elementum (eg: TV shows ->Most Played -> and i am just choosing one video there). I thought those folder are searching regarding the selected provider (actually i have just 2 selected in Elementum Burst).
May be it's me who don't understand well how it's working.
But i am not able to have a result when i am searching a movie from Elementum (even if i am trying to look for the letter "a" i have no result) but i can find it in the provider website. Is it a configuration issue of the provider? if yes, how can i fix it.
I hope you would be able to see in the log here that i was able to watch a movie by adding the magnet that i got from that provider website, but i can't find the same movie by searching in Elementum.

Link to Kodi debug log: http://paste.ubuntu.com/p/KCdCTkXv4f/
http://paste.kodi.tv/ikumebilax

Thanks in advance

**Comment by elgatito** [comment]
Looks like a bug with cloudflare scraper, should be fixed in the next version.

**Comment by elgatito** [comment]
@lexcyr  Can you try the latest version of Elementum?

**Comment by elgatito** [comment]
Closing without getting response.
