### ISSUE TITLE
[Bug] Issue when opening a show through Calendar > My Shows

### ISSUE THREAD

**Issue by hoshsadiq** [elgatito/plugin.video.elementum#45]
Playing a show by going to calendar > my shows, plays the show, shows an error, then stops playing. When selecting a show to play from the results, it loads and plays the show, then the video screen gets overlayed with a "Playback failed" error. Clicking "OK" (only option), forces Kodi to stop playing the show.

## Expected Behavior
No error should come up when it plays the show, and it should not stop the video

## Current Behavior
Error shows up. Click OK on the error, stops the video to play.

## Possible Solution
Can't give you a possible solution, but the workaround is to go into the show through any other means (search, watchlist etc) and then finding the same episode, and playing it from there.

## Steps to Reproduce (for bugs)
1. In Elementum go to TV Shows > Trakt > Calendar > My Shows
2. Select a show that aired today (need to find a show with results)
3. Select one of the results, and wait for it to buffer
4. Once buffered, the show will play, but as soon as it starts playing, error message pops up.

## Your Environment
* Version used: latest
* Environment name and version: Kodi 17.6, armv7l
* Operating System and version: Android 7.0
* Link to Kodi debug log: https://paste.ee/p/Ktwkf

**Comment by elgatito** [comment]
I don't understand this issue and what is wrong.

**Comment by hoshsadiq** [comment]
I will try and record a video later today.

**Comment by elgatito** [comment]
What about this one? Video is not required, but re-check with the latest version (and the log, of course) is much appreciated.

**Comment by hoshsadiq** [comment]
Sorry, I haven't had the time for the video. I will try checking it when I can as currently nothing is showing up that I can reproduce it with. Give me a few days :)

**Comment by elgatito** [comment]
@hoshsadiq  It is still relevant?

**Comment by hoshsadiq** [comment]
This is an annoying one. When I go back to the list, there's nothing that has aired on that day, so I'm unable to reproduce it, and on the days I do have stuff airing, I forget to check! I have stuff in my list that airs today, so I'll set a reminder to check it out as soon as I'm home!

**Comment by hoshsadiq** [comment]
Okay, I was able to upload a video: https://drive.google.com/file/d/1NnD-DV6Hbh156KRPBQzdtnzuftO_hGTT/view?usp=drivesdk

**Comment by elgatito** [comment]
Ouch. Log is already non-available (expired). If you have this issue, can you resend a log file? (i have watched the video, thanks)

**Comment by elgatito** [comment]
@hoshsadiq can you try to reproduce the bug with 0.0.55 ?

**Comment by elgatito** [comment]
@hoshsadiq Calendars were changed in 0.0.56. Can you check the issue?

**Comment by hoshsadiq** [comment]
Sorry dude, I got your message, but haven't been able to check. I will do my best to check over the next few days!.

**Comment by elgatito** [comment]
Should I close this issue? Is it relevant with the latest version?

**Comment by hoshsadiq** [comment]
Can't reproduce it anymore, so must have been fixed! Thanks for all the hard work @elgatito!

**Comment by i-me-mine** [comment]
I may be entirely mistaken, but I believe the error occurs when a provider times out or returns an error.  In that case, an error message pops up after a source is selected, and as the original poster noted the error message is overlayed by the connection and buffering information.  

Some work arounds are to wait until the selection screen times out and make your source selection after the error code pops up.  You can also make a selection, immediately cancel the connection process, then click the episode again in the calendar and click yes when asked if you want to use the previously selected source.  Lastly, you can allow the show to buffer and start playing, immediately click the error "ok" button and immediately restart the episode, clicking yes for the same source--this will allow you to immediately begin playback if done fast enough.

Frankly, though the error can be a little bit of a pain in the neck, the software was provided free and as is, so I've got no complaints if there is a mild inconvenience once in a while.
