### ISSUE TITLE
Source code elementum binaries?

### ISSUE THREAD

**Issue by frevib** [elgatito/plugin.video.elementum#456]
## Expected Behavior
Source code of the `elementum` binaries are available for download.

## Current Behavior
Cannot find the source code of the `elementum` binaries.

## Possible Solution
Put source code on Github.

## Context
I would like to make improvements to the binaries.

**Comment by elgatito** [comment]
Please, read the welcome page first.

> elementum - The Elementum daemon itself, built on top of the cross-compiled libtorrent-go

https://github.com/elgatito/elementum/
