### ISSUE TITLE
Resume point

### ISSUE THREAD

**Issue by RH1CK** [elgatito/plugin.video.elementum#459]
This is not a insue, but i didnt know how to contact you, i just wanted to know how you handle the resume point in the addon once strm files in kodi dont have that natively. Been looking on google for some hours and couldnt find any documentating regardles how an addon handle resume points in kodi, thanks in advance, also thanks for the amazing addon you have, been using for some time

**Comment by elgatito** [comment]
Kodi saves resume points itself. You can't influence it. 
Elementum is storing on it's side as well, and forcing Kodi to rewind playback if needed.
