### ISSUE TITLE
Season pack file selection

### ISSUE THREAD

**Issue by pedrochiuaua** [elgatito/plugin.video.elementum#460]
I want to suggest an improovement for tv shows. I am using elementum since a few months and i found that in mostly cases the best way for found healty tv show torrents is with a season pack. So, now i have to:
1. Open context menu on the season and choice the select torrent option. Then elementum search for the full season.
2. Select the file i want to play.
3. Manually search for subtitles for the episode that i select, because by default it search for the season pack subtitle instead the file i choose.

I think it can be improoved adding an option in addon settings for search for a season pack and/or for the single episode, or adding a context menu option for that.
Then, when you select a tv show, a season and an episode, elementum can search for a full season torrents. And, when you select the season pack torrent, elementum automaticly select the correct file in the season pack an play it. Implement the automatic detection using the file name that fit whit the required episode should not be hard.

Sorry for my english, hope you can understandme. Thanks for your great work!

**Comment by elgatito** [comment]
You understand everything in a wrong way. 
When you ask to play an episode Elementum is starting a Burst (or any other search plugin) search for episode. 
Burst has definitions how to search for episodes, for each provider. Some search for Episode+Season, some search only for Episode, some search only for Season. That all depends on provider settings.

When you select episode to play and then select season torrent in search results - Elementum will automatically select needed file and is there are more episodes in that torrent - it will save torrent file for them, so allow re-use of torrent without need of searches.

**Comment by elgatito** [comment]
Closing without getting response.
