### ISSUE TITLE
choppy/out-of-sync playback Elementum 0.1.35

### ISSUE THREAD

**Issue by riiiic** [elgatito/plugin.video.elementum#462]
Hello and thanks for reading.

I am experiencing a problem with Elementum (it happens with this last versions 0.1.35, default settings, but it also happened before).

The download speed and buffering are fine, elementum finds the file, starts downloading and plays. After few minutes (depending on the size of the file, the bigger the sooner), audio and video start being slightly out of sync which cause the playback to be chopped in order to re sync.
I have noticed this happen when the download speed is "very" high 9-13000kb/sec.
My first reaction was to instruct Elementum to phisically save the file first, wait until 100% (full downloaded) and start the playbyck then.
Since a couple of days it happens also with stored files.
Reset the android box didn't serve any good, it was fine for a couple of days a now is behaving all of the same again.

I am running Kodi on a Skystream III plus:
CPU: AMLogic S905X2 quad core ARM Cortex-A53 @ up to 2.0 GHz 
GPU: Mali-G31 - A55 ARM Cortex  650 MHz delivering 1.3 Gpix/s 
DRAM: 4GB DDR4
Flash Memory: 64GB
Bluetooth: Yes - 4.1
Software
Operating System: Android 8.1 Oreo
Platform: SkyStreamTV

Will I find a description of this kind of error in the log file ?

Thanks a lot for your help.

**Comment by elgatito** [comment]
> Will I find a description of this kind of error in the log file ?

Maybe, but it's not linked with Elementum. Elementum is giving a simple "file" to Kodi, how Kodi plays it - is not controlled by Elementum.

**Comment by riiiic** [comment]
Hello Elgatito,
thanks a lot for your reply. 
Meanwhile I also mailed skystream, apparently many users reported issues linked to Leia 18.3 last update, as you commented is really linked to kodi. I will install an older version and check. Many thanks again.
