### ISSUE TITLE
Elementum Refuses to create a Subtitle Folder on External HDD

### ISSUE THREAD

**Issue by Kristijan1001** [elgatito/plugin.video.elementum#465]
## Context
So i have an Android Sony TV, i am well aware that the write permissions to an external HDD are forbidden. But if you select a folder in Android/data/org.kodi../ (This folder should have write and read permissions). I have a custom folder selected in Kodi settings for the subtitles to download, when i use any other addons like titlovi, open-subtitles and podnapisi all work perfectly fine and download the subtitles in the specified folder on the external HDD. But when i select the download directory in Elementum subtitles refuse to download anymore, before selecting the download directory they work fine.  Why i select the download directory to my external is because i want the movies to be downloaded there, because the TV only has 8GBs of internal storage which is not enough for a 4K Movie for example to be fully downloaded. Now i am not even sure if the movies are even being downloaded to the external HDD since the subtitles can't be downloaded either.

Another thing what does the "Download Directory" mean in the Elementum Settings ? 

Download for the movies ? for the Subtitles ?

Also the Library location what is this one for ? Metadata ?

The Torrent Files location ? is this only for the .torrent files or for the actual downloadable movies.

## Expected Behavior
For Elementum not to create any folders and just download the subtitles in the specified folder. This might be why the issue is happening.

## Current Behavior
Elementum refuses to create a folder on a External HDD

## Possible Solution
Just download the subtitle instead of creating a folder.

## Steps to Reproduce (for bugs)
1. Select a Folder on External HDD
2. Try to download a Subtitle
3. Can't Create Folder Error.

## Your Environment
* Version used: Latest KODI Version from Google Play Store.
* Environment name and version: Latest Elementum version from the official REPO.
* Operating System and version: Android Sony TV Oreo 8, Latest Kodi Leia

**Comment by elgatito** [comment]
Elementum does not know anything about your settings to download subtitles somewhere.
Subtitles - provided in torrent file are part of it and is downloaded to usual download directory.
Subtitles found on OSDB are downloaded to temporary Kodi directory.

**Comment by Kristijan1001** [comment]
> Elementum does not know anything about your settings to download subtitles somewhere.
> Subtitles - provided in torrent file are part of it and is downloaded to usual download directory.
> Subtitles found on OSDB are downloaded to temporary Kodi directory.

As soon as i change the download directory to my external drive the subtitles stop working. If i reinstall and don't touch the download directory path in the settings the subtitles work fine. So there has to be something that is getting messed up, because it is defiantly changing the directory as soon as you touch the "Download Path" . I am talking about OpenSubtitles. As soon as you click on a subtitle to download it says. Elementum Can't Download subtitle. Subtitle folder cannot be created.

**Comment by elgatito** [comment]
No log = no help.

**Comment by Kristijan1001** [comment]
> No log = no help.

@elgatito can you tell me the process on how to acquire it, i will be happy to do it.

**Comment by Kristijan1001** [comment]
Alright, i will try to figure it out, will get back to this.

**Comment by elgatito** [comment]
http://elementum.surge.sh/contribute/log/

**Comment by djnotis** [comment]
@elgatito Hi i have a problem with elementum i choose download path with external hdd and the movie doesn't begin or download but when i choose internal storage the download begin. i use kodi with android tv sony and android 8 oreo please help me

**Comment by antonsoroko** [comment]
@djnotis

possibility to write to external storage depends on Android TV version. 
I also have 8. When I had 6 - I was able to write to external storage (but only to Android/data/org.kodi../ directory because of limitation of Android)

With 8 my only solution was to format external HDD as internal storage (in settings) and also move app data to it (it will ask after format, without this step it does not work).
So you will have one "merged' storage (i.e. one big).
After these manipulations I was able to use Android/data/org.kodi../ directory as download path in elementum.

**Comment by Kristijan1001** [comment]
Only way to go around this is to have your HDD formated as internal storage. Then go settings> storage > your hdd> move data to it. This will make the hdd appear in the filemanager. You can now setup custom folders for everthing and all works perfectly.

**Comment by elgatito** [comment]
Closing, cause of missing log.
