### ISSUE TITLE
Problem streaming bigger torrent files

### ISSUE THREAD

**Issue by peter099** [elgatito/plugin.video.elementum#467]
I have problem streaming some big torrent files - over 2GB. This is the problem:
The pre-buffer is downloading with good speed, i am connecting to good amount of seeders. When the stream starts i see the video cache is full, but then it starts emptying gradually until it reach zero and the stream freezes. If i hit pause i see that the download speed is good, so i don't know why the video cache is not filling. 
Elementum is set to download the torrent to ram memory, and my upload and download speed is set to unlimited. I am using Kodi 17 on Windows 7. Elementum version is 0.1.37.

**Comment by elgatito** [comment]
No log = no help.

**Comment by elgatito** [comment]
Closing without getting response.
