### ISSUE TITLE
No buffering no peers no seeds

### ISSUE THREAD

**Issue by Talixme** [elgatito/plugin.video.elementum#471]
Hello, first thanks a lot for your work is amazing what are you doing with this proyect.

Here is my problem.

Some torrents that i try to stream are no working. Everything is ok until the buffer window, that give me 0 peers and 0 seeds.The i try with quasar or torrenter and works fine.

Hardware : Mi Box S 
OS : Android Tv 8.1
Kodi 18.3

Movier Working log Elementum & Torrent 1
https://pastebin.com/N0k25fJZ

Movie Not Working Log Elementum &  Torrent 2
https://pastebin.com/cGPBBEdu

Thanks a lot.

**Comment by Talixme** [comment]
I have done some more test, if the torrent has more than like a week everything works fine.

Not Working Log Elementum & Torrent with less than a week
https://pastebin.com/mEiBuwr8

Working Log Quasar & Same Torrent
https://pastebin.com/a4WJCuN1

Maybe is something wrong with some trakers?

Thanks.

**Comment by Talixme** [comment]
O i did some more test.

From version 0.0.1.android_arm to 0.1.19.android_arm every torrent works fine

From version 0.1.20.android_arm to last release doesnt work sames torrents

Thanks

**Comment by elgatito** [comment]
I don't see the problem since you provide only part of log file where you only add a torrent.

**Comment by avssport** [comment]
I have the same problem, i add the full log to check it. Thank and great job!!

[https://paste.kodi.tv/uquzotumaw](url)

**Comment by elgatito** [comment]
@avssport I see there are no peers and no seeds.
I'd suggest:
1) Enable libtorrents logs, in Elementum settings, Bittorrent tab. Then re-run your test.
2) Provide any torrent file, that tried to download in Elementum. (You can find the path to it from Kodi log file, for example: `Adding torrent from /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.alfa/videolibrary/temp_torrents_Alfa/cliente_torrent_Alfa.torrent`

Strange it cannot find peers even with enabled DHT. 
It happens with all torrents from Alfa plugin? 
Or only some of them?

**Comment by avssport** [comment]
It only happens with torrents of Newpct1 channel the other channels works well, i go to try to re-run test as you explain and add the log. Thanks!

**Comment by avssport** [comment]
@elgatito i tried again from Windows with the same result, i add the log this time with libtorrents log, I hope that help you to fix the problem. Thanks!

https://drive.google.com/open?id=1i1jRqkTS7ziW1Gw9PE8DEczil6XF6f_I

**Comment by elgatito** [comment]
@avssport actually does not see anything wrong in the log. DHT is working and libtorrent is trying to find any peers and it can't. 
Does not know what to advise you, maybe it is a better question for libtorrent's maintainers...

**Comment by avssport** [comment]
@elgatito but with other torrent clients works well

**Comment by elgatito** [comment]
@avssport I'm not a developer of libtorrent library. Elementum is using libtorrent 'as is'.

**Comment by elgatito** [comment]
Closing as libtorrent is doing all the downloading. 
To resolve magnets - DHT should be enabled and working, and should not be blocked by firewalls.
