### ISSUE TITLE
[Request] Sort seasons of series in ascending order

### ISSUE THREAD

**Issue by pitsi** [elgatito/plugin.video.elementum#472]
As usual, I was showcasing elementum to a friend of mine and this time he noticed that seasons of series are sorted in descending order, as shown here.

![screenshot000](https://user-images.githubusercontent.com/5880037/64195636-a628a100-ce8a-11e9-8a14-93660c645199.png)

So, I was wondering if it is possible to somehow sort them in an ascending one, i.e season 1 on the top, then season 2 and so on,

## Expected Behavior
Elementum should sort seasons like so: season 1, season 2, season 3 etc.

## Current Behavior
Elementum sorts seasons like so: season 5, season 4, season 3, season 2, season 1 and then the specials/extras.

## Possible Solution
No idea.

## Steps to Reproduce (for bugs)
1. Launch elementum and go to tv shows
2. Select one from the lists, e.g. breaking bad from the "most popular" list. 
3. Notice what I mention above

## Context
I think that ordering the seasons in ascending order offers a more straigh forward way to search through the episodes.

## Your Environment
* Version used: 0.1.37
* Environment name and version: Kodi 18.4 on amd64 linux
* Operating System and version: Debian testing x64
* Link to Kodi debug log: not needed

**Comment by elgatito** [comment]
Setting to sort seasons was added to v0.1.38. 
Also "All seasons" was added, to look like Kodi library.
Please, try.

**Comment by antonsoroko** [comment]
Works for me.
The only thing is that if you want to change ordering you need to do it for every TV series separately (not sure if it is Kodi or elementum thing) 
Thank you

**Comment by pitsi** [comment]
It works for every tv show for me. Screenshots for the first 4 from the "most popular" section.

![screenshot000](https://user-images.githubusercontent.com/5880037/65658066-d51bd800-e02e-11e9-97f5-e19876c54cf3.png)
![screenshot001](https://user-images.githubusercontent.com/5880037/65658067-d51bd800-e02e-11e9-93ba-a10d7b2b2570.png)
![screenshot002](https://user-images.githubusercontent.com/5880037/65658069-d51bd800-e02e-11e9-9062-f57b08349435.png)
![screenshot003](https://user-images.githubusercontent.com/5880037/65658070-d5b46e80-e02e-11e9-95e4-b3808bf2473e.png)

**Comment by elgatito** [comment]
@antonsoroko there is no caching for list of episodes/seasons. Maybe your skin is doing caching, or some other addon.
