### ISSUE TITLE
[Bug/Request (?)] - Merge to Library option looks broken

### ISSUE THREAD

**Issue by Tsadilas** [elgatito/plugin.video.elementum#473]
Elementum 0.1.37, Win7 64bit, Kodi 18.4, latest java, Quasar 0.9.78, TMM 3.0.4

This is relevant to TV shows.  All downloaded media and folders are renamed and NFOed with TMM properly. E.g. G:\TV Series\American Gods (2017)\Season 1\ American Gods - S01E01 - The Bone Orchard.mkv.  Quasar comparison is offered as this is a fork.  Tests were conducted on a fresh Kodi installation only with helly repo, xconfuence skin, quasar and elementum installed.

“merge library option” from search looks broken, assuming Quasar sets the expected behavior. When I choose it, it creates strm files in the library for ALL the episodes, regardless if a media file is present in the library thus resulting into everything being listed twice in the Kodi TV show view.  Quasar, when using merge option only creates, and thus lists in Kodi, the strm files of the episodes missing.

What I am trying to achieve is have a ‘TV SHOWS” view in Kodi where episodes inside shows/seasons are listed only once, either displaying/pointing to the actual media file in my HDD or to the strm file. Point is to be able to easily download missing episodes and future released ones.

Essentially, what is need assuming its broken or missing is a command along the lines of “IF episode is listed in the library THEN skip creation or delete strm file”.

Tested both with Elementum and Quasar to compare. Kodi, Quasar and elementum library being fully expunged before each attempt.  

Some notes on Quasar behavior which may come handy. On this front it works better albeit with some failings in some episodes of some series – but always the same failures for reasons I cannot explain as naming looks right. Problem persists with certain episodes, e.g “American Gods” as depicted in the pics but not others like “Cobra Kai”. Weird thing is that unneeded strms seem to point to the right episode which looks like adhering to the same naming convention as other episode which are correctly skipped from being created. More weird the fact that for Battlestar Galactica, for example, Elementum seems to create a second “entry” in the Kodi TV shows view despite both folders with strm and mkv files have the exact same name. Quasar on the other hand creates in the library path a folder with 0 strms – correctly – and no second entry in the tv show view. This contrary to “American Gods” behavior were even double entries are viewed on the same listing.

Hope these help and that there is an obvious and easy solution. 

To reproduce:
Add local files to Kodi library (G:/TV Show) and update. TV Shows list populates
Search TV show with Elementum and Quasar, right click and chose “merge to Library”

Pic 1: Kodi view after adding local files
Pic2-4: After merging to library with Quasar 
Pic5-7: After merging to library with Elementum 
Pic8-9: How thing should/want them to look

![pic1](https://user-images.githubusercontent.com/54939683/64352870-6df99d80-d005-11e9-88eb-0ead604f8f76.jpg)
![pic2](https://user-images.githubusercontent.com/54939683/64352871-6df99d80-d005-11e9-8b39-341b95934fc1.jpg)
![pic3](https://user-images.githubusercontent.com/54939683/64352872-6df99d80-d005-11e9-9682-7412063a372f.jpg)
![pic4](https://user-images.githubusercontent.com/54939683/64352873-6df99d80-d005-11e9-9ad3-95e119c8f7e0.jpg)
![pic5](https://user-images.githubusercontent.com/54939683/64352874-6e923400-d005-11e9-886c-3f17e5189aff.jpg)
![pic6](https://user-images.githubusercontent.com/54939683/64352875-6e923400-d005-11e9-8732-ba4003f08039.jpg)
![pic7](https://user-images.githubusercontent.com/54939683/64352878-6e923400-d005-11e9-94ae-297cf808ba09.jpg)
![pic8](https://user-images.githubusercontent.com/54939683/64352879-6f2aca80-d005-11e9-9c06-a556c9522f82.jpg)
![pic9](https://user-images.githubusercontent.com/54939683/64352883-6fc36100-d005-11e9-9651-c418870bb04e.jpg)

**Comment by Tsadilas** [comment]
Mhhh. Apparently there was something screwy with my settings and/or the metadata scrappers. Problem solved albeit with a suspiciously length process.

**Comment by Rmdhn1** [comment]
Tell us
