### ISSUE TITLE
[Request] Shortcut to go to the end of tv episode name when adding .torrent file

### ISSUE THREAD

**Issue by peter099** [elgatito/plugin.video.elementum#474]
When the metadata for the torrent file name and tv episode names are too long it is not possible to see which tv episode you are selecting when opening .torrent file for season packs. A shortcut to go to the end of the tv episode name will be very useful.

**Comment by peter099** [comment]
When you manually add torrent file for season pack it opens a window with a list of the episodes, and if you have long names for the torrent metadata - like torrent name, tv show name - you can see only the beginning of the selection. But to see which episode you have actually selected, you have to wait the carousel to reach the end of the selection which is a very slow thing. 

example: https://i.imgur.com/UnK3vTv.png

**Comment by elgatito** [comment]
That dialog is managed and showed by Kodi. 
Elementum can only give list of options to display (what it actually does). 
I don't know of any way to control that window.
