### ISSUE TITLE
Problem with alfa torrents

### ISSUE THREAD

**Issue by Expolio** [elgatito/plugin.video.elementum#475]
Hi, the problem is  this :when i download something from elementum itself it works fine,but when i tried to download  some movie from other magnet link add-on (like alfa) the seed/peers ,download and upload is 0 and it stays buffering forever.(Tried in librelec 9.1 in rpi3 and a windows with kryton 17.4)

**Comment by elgatito** [comment]
Provide proper log file, which shows the problem.
https://elementum.surge.sh/contribute/log/

**Comment by elgatito** [comment]
@Expolio I will close the issue if you don't give a proper log file.

**Comment by elgatito** [comment]
Duplicated of #471
