### ISSUE TITLE
slow network speed when elementum is running

### ISSUE THREAD

**Issue by fuligjimmy** [elgatito/plugin.video.elementum#476]
hi, 

I'm using the latest elementum with OSMC and even when i'm not streaming the osmc vero's network speed is much slower (using speedtest-cli for testing).

When I uninstall elementum everything goes back to normal.

Is there any fix for this?

Thanks a lot!

**Comment by elgatito** [comment]
Elementum is not influencing the network. If you use file storage for downloading torrents  and have a lot of them active within Elementum - they can use upload bandwidth of course.
Also, if you have shitty router, DHT can be a problem for you.
Any way, if you have problems - you should remove the plugin.
