### ISSUE TITLE
Matching episodes of series with the library

### ISSUE THREAD

**Issue by Nosperatos** [elgatito/plugin.video.elementum#477]
When watching series, the following problem often began to arise: if there are separate subtitle files in the torrent, then when watching, you have to choose a series each time, although they have the correct names. The idea is to ignore non-video files in files.
example: e1s01.avi, e1s02.avi ext is correct
example2: e1s01.avi, e1s01.srt ext is problem

in my other project I solved a similar problem like this:
EXT_CORRECT = ['.avi', '.flv', '.mp4', '.mkv', '.wmv', '.ts']
def extension_check(path):
    correct = False
    extension = os.path.splitext(path)[1].lower()
    for item in EXT_CORRECT:
        if extension == item:
            correct = True
            break
    return correct

It will be good if you implement something similar in your project.
I apologize for English; I know it badly.

**Comment by elgatito** [comment]
Small files are filtered by Elementum, it can be controlled in the settings. By default - anything less then 100mb is filtered.
That is done to filter all surrounding files, like audio, subtitles, texts and so on.

@Nosperatos  Maybe you have modified that setting? I don't know how you can see small files in other way.

**Comment by Nosperatos** [comment]
Thank you I’ll study the settings more closely.

**Comment by Nosperatos** [comment]
Напишу так без переводчика. Действительно в настройках стояло значени 0 мб на минуту сериала. Поставил 2 мб и проблема исчезла. Спасибо за замечательный проект, успехов!
