### ISSUE TITLE
Can't remove TV shows from Library.

### ISSUE THREAD

**Issue by zukove** [elgatito/plugin.video.elementum#481]
Keeps coming back to library. 
Please advise.

**Comment by elgatito** [comment]
@zukove you should find show in Elementum and in context menu remove from the library, then Elementum will know not to create strm files for that show.

**Comment by zukove** [comment]
Thanks for the response. This is what I am doing (remove from library via Elementum and not via kodi library. STRM files keep coming back upon next library update by Elementum. the show is being added to Kodi Library again. I believe this is a bug. Please advise.

**Comment by elgatito** [comment]
@zukove then, log is needed. 
Enable debug logging.
Restart Kodi, go to Elementum, find that show, do "Delete from library", go to Elementum settings, launch Library update.
And then show the log.
http://elementum.surge.sh/contribute/log/

**Comment by elgatito** [comment]
In 0.1.43 Show, deleted from Kodi library, is marked as deleted in Elementum to avoid re-creating the files.

**Comment by dmitrymikhnevich** [comment]
I'm running Kodi on Android TV.

In v 0.1.43 I still have the issue that TV shows removed from the Kodi library reappear there after some time. I tried both ways to remove TV shows: in Kodi library itself and in Elementum (via a context menu "Remove from Kodi Library").

**Comment by zukove** [comment]
> I'm running Kodi on Android TV.
> 
> In v 0.1.43 I still have the issue that TV shows removed from the Kodi library reappear there after some time. I tried both ways to remove TV shows: in Kodi library itself and in Elementum (via a context menu "Remove from Kodi Library").


That’s right. I found a workaround:
From Elementum
1. Remove show from library
2. Merge show to library
3. Remove again

From Kodi Library:
Remove the show manually. 

Let me know if it works for you.

**Comment by dmitrymikhnevich** [comment]
> That’s right. I found a workaround:
From Elementum
Remove show from library
Merge show to library
Remove again

That worked. So far so good, thanks.
