### ISSUE TITLE
Torrent history is in reverse sort order

### ISSUE THREAD

**Issue by peter099** [elgatito/plugin.video.elementum#483]
Last used torrents in torrent history used to appear at the top of the list and now they appear at the bottom. I don't know if this is intentional but when they appeared at the top it was more convenient.

**Comment by elgatito** [comment]
@peter099 you are right. Will be fixed in 0.1.41.

**Comment by elgatito** [comment]
@peter099 should be fixed in 0.1.41.

**Comment by peter099** [comment]
Yes, the last used torrents are appearing now at the top. Thanks!
