### ISSUE TITLE
Delaying with the Trakt Watched status sync update

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#484]
After Elementum is starting, I go into the Elementum -> Trakt -> My TV Collection 
But it seems that Elementum still has not synced with Trakt Watched status, even that my Trakt addon ran a synchronization after Elementum has started.
Just ~5 minutes later, when my Trakt addon run a refresh process and resync, the watched status in elementum is updated.

I don't think there was such a delay in the past, the watched status was update pretty immedietly after Elementum has started.

Is there any way to make a synchronization right after elementum is starting or fix this issue so there is no be a delay in updating the watched status when open Elementum Trakt menus after Elementum started?

Kodi log:
https://paste.ubuntu.com/p/MPHw55n3wb/

Times:
14:15 Elementum started
14:15 First trakt sync (on kodi start)
14:20: Refresh Trakt - Running Trakt sync (After this sync, the watched status is updated)

Elementum 0.1.40
Kodi 17.6
Windows 10, 64bit

**Comment by elgatito** [comment]
@burekas7 should be fixed with 0.1.41.

**Comment by burekas7** [comment]
Thanks, it seems to be better now.

**Comment by antonsoroko** [comment]
@burekas7 
just out of curiosity - what value you have for "Synchronize frequency of Trakt (minutes)" in elementum settings?
(https://github.com/elgatito/plugin.video.elementum/blob/master/resources/language/messages.pot#L1997)

**Comment by burekas7** [comment]
It set on 5 minutes, it actuall explains the times I mentioned.
But @elgatito fix it even with this value, so the watched status are sync pretty fast right after Elementum is starting (or it remembers the last sync. I don't know)

**Comment by elgatito** [comment]
@burekas7 
> or it remembers the last sync. I don't know

First Elementum gets Kodi library, then gets everything from Trakt, so it's always the real data.
