### ISSUE TITLE
"Remember torrent choice" work wrongly in torrent search

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/plugin.video.elementum#486]
## Current Behavior

"Remember torrent choice" work wrongly in torrent search - torrent from last search is proposed for new search (and for every old searches).

## Steps to Reproduce (for bugs)

1. search for torrent, choose torrent
2. search for another torrent - elementum will propose you a torrent from last search
3.
4.

## Your Environment

* Version used:
0.1.40

* Environment name and version: spmc 17,4

* Operating System and version: android tv 8

* Link to Kodi debug log:

https://paste.ubuntu.com/p/V8Bjmqzfj7/

**Comment by elgatito** [comment]
@antonsoroko 
I cannot reproduce this issue. I go to Elementum -> Search -> New search , search something - and select torrent. Then starting previous query - get correct torrent from history.

**Comment by antonsoroko** [comment]
Hm, strange. Anything useful from the log file? (2 searches, second uses result of first - this issue)

**Comment by elgatito** [comment]
@antonsoroko can you write reproduction steps, one-by-one. Maybe there is some specific case for getting a bug.

**Comment by antonsoroko** [comment]
@elgatito
Честно , нету ничего специфичного, захожу в поиск, ищу серию, выбираю торент, потом делаю другой поиск, выбираю торент, потом выбираю предыдущий элемент истории , а оно предлагает торент от последнего поиска. Может у меня что-то в базе сломалось при обновлении или ещё как?

**Comment by elgatito** [comment]
@antonsoroko try with 0.1.43.

**Comment by elgatito** [comment]
Try with default skin (Estuary)

**Comment by antonsoroko** [comment]
@elgatito 
тоже самое с Estuary. (0.1.44)
интересно то, что раньше работало, скин и версия коди не менялись.
началось после переезда базы болт ( github.com/asdine/storm )

попробую почистить может QueryHistory в storm.db или еще что

спасибо.

**Comment by antonsoroko** [comment]
fixed in 0.1.48
thank you!
