### ISSUE TITLE
looks like elementum is still starting up

### ISSUE THREAD

**Issue by evripidesk** [elgatito/plugin.video.elementum#487]
Hello I installed kodi on Apple TV and try to install the elementum, the installation goes fine but when I tried to open the elementum addon I get this message looks like elementum is still starting up and cannot open

**Comment by elgatito** [comment]
Elementum cannot run on iOS (tvOS).
See #4

**Comment by BTopbas** [comment]
@elgatito Elementum can not run on Apple TV without binary (only client) mode? I want to use elementum with client mode on kodi matrix with Apple TV. 

I have coreelec kodi box and apple tv. Coreelec stable kodi on Linux. And apple tv running kodi matrix alpha. But I cant install elementum client version in apple tv kodi. So I change addon.xml python version to 3.0.0 addon installed. I changed remote host ip to coreelec kodi ip and not run binary option to true. But when I run elementum on matrix gives error and can't run.

**Comment by elgatito** [comment]
@BTopbas client-only mode is buggy and not everything works.
I don't know how elementum runs on Kodi 19. You can fix and push a PR.

**Comment by remusici** [comment]
Hello. Any updates on elementum for Apple TvOS? I have installed Kodi with TrollStore on Appletv OS 16.6 but when i try to open Elementum "looks like elementum is still starting"

**Comment by antonsoroko** [comment]
Ios is not supported. But if you have other supported device, then you can use ios device as client (see advanced settings of elementum).

**Comment by antonsoroko** [comment]
@aicynide jacktorr is a wrapper on TorrServer, and TorrServer can run on macOS, but not iOS or tvOS. So you anyway end up with the same "separate client and separate server" approach as with elementum. What is your point then?

**Comment by antonsoroko** [comment]
@antonsoroko this is different situation. i am talking about addons for kodi, not about standalone apps.
In ios or tvos - kodi can't run binaries - this is limitation of platform itself (as far as i know) so it can't start elementum. that's why i proposed client-server mode. the same limitation has Xbox.
standalone apps work, but not kodi addons that need to run binaries.

**Comment by antonsoroko** [comment]
@aicynide restriction of the Operation System itself, like for security reasons i guess. at least this is what i understood after reading https://github.com/elgatito/plugin.video.elementum/issues/4 .
