### ISSUE TITLE
Keep Downloading dialog disappearing before selecting

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#488]
1. Go to Trakt -> MyProgress (Maybe from other place too)
2. Choose a torrent and play it.
3. Stop the playback (Make sure in the setting for asking 'Keep Downloading')
* The stop process also have a little bug, it doesn't stop immediatly.
4. The "Keep Downloading?" dialog show up with the 'busy' circle on it, so I can't press on any button there.
5. After the 'busy' circle disappear, the dialog gone too, and the torrent also gone from the torrent list.

Kodi Log:
https://paste.ubuntu.com/p/JF7vbbS4k4

Image:
![image](https://user-images.githubusercontent.com/13424257/66275916-42810180-e896-11e9-9753-c6c824fecf08.png)

Also the buffer downloaded fast but the torrent is still big, and probably the download decrease so the playback start laggy.

## Your Environment
Elementum 0.1.41
Kodi 17.6
Windows 10, 64 bit

**Comment by elgatito** [comment]
@burekas7 in Elementum v0.1.41 there is a new option to autoclose confirm dialogs after timeout. You can disable it or increase the timeout in plugin settings.

**Comment by burekas7** [comment]
The setting is actually called:
"Automatically answer Yes after timeout"
But here it chose the "No" option, and there wass no timeout, I just stop the playback as usual.

**Comment by elgatito** [comment]
>  there wass no timeout

Timeout for answering the dialog.

> the setting is actually called

Description is not corrent. If "yes" is predefined - treats as "yes". If "no" is predefined - treats as "no".

**Comment by burekas7** [comment]
What do you mean by 'predefined', according to my skin setting?
In my skin settings there is a setting of:
"Set default focus to NO button in confirmation dialog" (which is false in my case, which means that the predefined should be "YES" and it still check it as "NO" and remove it from the torrent list)

But the big question is why there is a timeout when stopping the playback at the first place?
Why there is this 'busy' circle when stopping?
All the time I was stopping the playback and immedietly the 'Keep Downloading?' dialog was show up.
Currently when I stop, there is kind of a little 'stuck' (black screen), then it returns to the menu screen with the dialog and the 'busy' status, so I can't press on any button, and then it was disappearing (probably due to this new setting that you talk about)

**Comment by elgatito** [comment]
@burekas7 is this still an issue?

**Comment by burekas7** [comment]
No.
A long time pass and now with 0.1.62 it's ok (Even before I think)

Thanks.
Closing it.
