### ISSUE TITLE
[Bug] Resume playback reset the active connections and download speed

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#489]
1. Start a new torrent.
2. Stop the torrent and leave it running and downloading in the torrent list
3. After a while, resume and play it from the torrent list.
4. The bug: All the connection and the download speed are reset to zero and restart the connections.

* I think I already open an issue on it in the past.

Images:
![image](https://user-images.githubusercontent.com/13424257/66312243-f6c36c00-e918-11e9-8340-c7ae51447cef.png)

After resume:
![image](https://user-images.githubusercontent.com/13424257/66312270-0773e200-e919-11e9-9089-984ebb865fb0.png)
![image](https://user-images.githubusercontent.com/13424257/66312294-165a9480-e919-11e9-8f14-5240f68e79c7.png)

Kodi Log:
https://paste.ubuntu.com/p/c2FCNFtwjv
(You can focus after ~15:30, I also enabled the debug mode)

## Your Environment
Elementum 0.1.41
Kodi 17.6
Windows 10, 64bit

**Comment by burekas7** [comment]
@elgatito 
This issue is still exist in Elementum 0.1.52

Kodi debug log:
https://paste.ubuntu.com/p/mqWRkq7Hzt

Before:
![image](https://user-images.githubusercontent.com/13424257/82142387-b16b0380-9844-11ea-9b2a-82457fc59328.png)

After resuming from the torrent list:
![image](https://user-images.githubusercontent.com/13424257/82142399-c34ca680-9844-11ea-8264-92044e4c29e5.png)
![image](https://user-images.githubusercontent.com/13424257/82142417-dcedee00-9844-11ea-9c64-bd991edf3996.png)

**Comment by elgatito** [comment]
@burekas7 seeds/speed was reset after you stop watching or when you re-open player?
You can see through the web page.

**Comment by burekas7** [comment]
@elgatito 
Reset when re-open player.
(When I stop the playback the speed is still stable)

What do you mean by "through web page"?

**Comment by elgatito** [comment]
@burekas7 I mean the web part of Elementum.

http://127.0.0.1:65220/web/

**Comment by burekas7** [comment]
After stopping the torrent:
(Remain the same - OK)
![image](https://user-images.githubusercontent.com/13424257/82258148-fb95d700-9961-11ea-9901-796ff03f9d72.png)

Right after resuming from the torrent list:
(Drop - Fail. Btw, if the torrent is a popular one, it back to the normal speed pretty fast, but with weak torrents it can be more problematic)
![image](https://user-images.githubusercontent.com/13424257/82258246-2849ee80-9962-11ea-9390-4565ed2f7ef0.png)

* Another issue: Why upload is remain on zero all the time, even when the max upload is set in the BitTorrent settings?

**Comment by elgatito** [comment]
> Another issue: Why does the upload remain on zero all the time, even when the max upload is set in the BitTorrent settings? (As you can see in the first image)

Elementum is taking numbers from what libtorrent gives. And upload cannot be disabled, only limited, if you set rate limits in Elementum configuration.

> (Drop - Fail. Btw, if the torrent is a popular one, it back to the normal speed pretty fast, but with weak torrents it can be more problematic)


Thanks for clarification. Have to see where if gets paused.

**Comment by burekas7** [comment]
> > Another issue: Why does the upload remain on zero all the time, even when the max upload is set in the BitTorrent settings? (As you can see in the first image)
> 
> Elementum is taking numbers from what libtorrent gives. And upload cannot be disabled, only limited, if you set rate limits in Elementum configuration.

Yes, as I said. I set it to value of 1000kb/s, but it was still remain on zero.
I will check it later with another torrent.

**Comment by burekas7** [comment]
@elgatito 
Ignore my last comment regarding the upload, with another torrent it seems to be ok
![image](https://user-images.githubusercontent.com/13424257/82379320-5f3a0600-9a2f-11ea-9487-420f8a1dc592.png)

**Comment by elgatito** [comment]
There was a bug with pausing torrent when starting a playback. 
It was there only if enable pause/resume trick for libtorrent (which is disabled by default).
In 0.1.53 it was fixed.

**Comment by burekas7** [comment]
Thanks @elgatito 
It seems to be ok now with 0.1.53
