### ISSUE TITLE
elementum query in tmdb Portuguese (pt-br)

### ISSUE THREAD

**Issue by videofree** [elgatito/plugin.video.elementum#491]
Good evening I would like to know if you can modify the elementum query in tmdb in Portuguese (pt) to Portuguese (pt-br) because the queries are coming wrong because the releases here in Brazil has not yet come out that the names here are different.

in the tmdb addon has the settings en I wish they could help me would be very grateful.

**Comment by elgatito** [comment]
@videofree sorry, not quite understanding your problem. Can you show an example of what we have and what you would like to have.

**Comment by videofree** [comment]
Good Morning.

On Brazilian Torrents sites they published several files, but the files are only placed supports being officially released in Brazil (Dubbed) tmdb does the same.

So when you click on release in Portuguese (pt) comes information that there are no files in Brazil yet.

But tmdb has Portuguese (pt-br) which has information equivalent to what exists in files.

**Comment by videofree** [comment]
Then it becomes more interactive with existing information.

**Comment by videofree** [comment]
sorry for the translation, i'm using google it may not translate properly.

**Comment by elgatito** [comment]
@videofree sorry, I still don't understand what you mean. You talk about browsing folders in plugin, or you talk about searching on torrent websites, or anything else? Give an example of situation.

**Comment by videofree** [comment]
Good Morning. When you use the elementum addon. You select the movie option in my initial, several options appears. The information that appears comes in the language selected in kodi but the selected language is Portuguese Brazil, plus the information that appears is from Portuguese from Portugal. I checked that you have the Portuguese Brazil option on tmdb site. On the site the information is the same as the content that is available on the torrent dubbed sites.

**Comment by videofree** [comment]
that's right I'm wanting to say

**Comment by elgatito** [comment]
I would be thankful for a log file with portugal/Brazil language, selected in Kodi, and trying to search something with Burst.

**Comment by warlosbr** [comment]
I have the same problem

**Comment by elgatito** [comment]
Closing because no log file provided.
