### ISSUE TITLE
Проблемы с разделом "В библиотеке Kodi"

### ISSUE THREAD

**Issue by Chupz0r** [elgatito/plugin.video.elementum#493]
1. Данный раздел работает, только если в настройках Elementum активировано создание NFO файлов для фильмов/сериалов. Не понятно для чего тогда в настройках нужны данные пункты, если из-за них перестает работать данный раздел.
2. При удалении из библиотеки элементов в данном разделе, они нормально удаляются физически и из обычной библиотеки Kodi, но почему-то все равно остаются в данном разделе.

**Comment by elgatito** [comment]
В раздел "В библиотеке" покадают только фильмы/сериалы, которые отдаёт Коди, и у которых есть отметка о дополнении. 
Без отметки нормально работать и отмечать фильмы/сериалы не является возможным.
