### ISSUE TITLE
auto-scrape

### ISSUE THREAD

**Issue by kovacicjanez** [elgatito/plugin.video.elementum#494]
Hi,

can someone explain settings for auto-scrape?
My setup is listed below.. and no movies are added to my library, what am I missing? 
My settings:
enabled: on
add to library: on
strategy: find 1080p resolution
number of results to find: 5

**Comment by elgatito** [comment]
@kovacicjanez I would not now suggest to use auto-scrape, as it creates a lot of requests to trackers, which is not good for them.
