### ISSUE TITLE
Падает скорость после буферизации

### ISSUE THREAD

**Issue by hyperpuncher** [elgatito/plugin.video.elementum#496]
После буферизации скорость падает практически в ноль и когда проигрывание из буфера доходит до конца загрузка крашится. Такое происходит в 90% случаев, в логе получилось ещё словить нормальную загрузку. С ноутбука с теми же настройками в Kodi и Elementum проблем нет.

* Elementum 0.1.41
* Kodi 18.4
* Android TV 8.1 на Mi Box S

http://paste.kodi.tv/peqomaviwa

**Comment by elgatito** [comment]
Можете пробовать уменьшать количество одновременных соединений. Может роутер умирает при большой нагрузке. Проблем в логе не вижу. Пиров много, всё в процессе работы, а не качает.

**Comment by hyperpuncher** [comment]
Количество соединений не помогло, но когда поставил буфер с 20 на 0, всё стало работать идеально. Неделю всё тестил, ничего не помогало. Спасибо за аддон!
