### ISSUE TITLE
[Request] Link the torrent selected for the season to all episodes of the season

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/plugin.video.elementum#497]
## Current Behavior

если выбрать торрент через "выбрать стрим" для сезона , а потом открыть сезон и выбрать серию , то начинается поиск торрентов заново , а не открывается торрент для сезона.

Ну и в тракт соответственно ничего не синкается
(я про просмотр напрямую из "выбрать стрим" сезона)

В общем, было бы круто ассоциировать все серии в сезоне с торентом выбранным из меню для сезона

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: 0.1.41

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

**Comment by elgatito** [comment]
From 0.1.43, torrent, selected for a season, is linked to all the episodes, found in it.

**Comment by elgatito** [comment]
Closing. Proper season handling was added in 0.1.43.
