### ISSUE TITLE
Can we get an option to find TV Shows Episodes that are Packed in one Torrent, without needing to manual search for it every-time.

### ISSUE THREAD

**Issue by Kristijan1001** [elgatito/plugin.video.elementum#498]
*Full Season = Torrent that includes all of the Episodes, because some of them are only available as a Pack and not as Separate Download.

## Expected Behavior
When selecting a TV Show have the option to find torrents that include "Full Season" without doing a manual search.

## Current Behavior
Only way to get to "Full Season" torrents is to manual search as far as i am aware. 

## Possible Solution
When selecting "All Seasons*" on a TV Show, it could search the Full Seasons torrents too. Instead just the separate episodes. 

Or we can have a check mark in settings that we can enable, that will allow us to search the "Full Season" torrent whenever we click an individual episode too. I don't know if it is capable for it to check what episodes are included in the torrent, but having it just Season separated would be perfectly fine. Example. If i click on Season 1 Episodes it shows "Season 1" Pack torrents too, if i click on Season 2 Episodes it shows "Season 2" Pack Torrents etc.

## Steps to Reproduce (for bugs)
NA

## Context
I tried this with few TV Shows.

## Your Environment
* Version used:
Latest Version
* Environment name and version:
Latest Kodi
* Operating System and version:
Android TV Oreo

**Comment by antonsoroko** [comment]
@Kristijan1001 
try to invoke menu on particular season (e.g. "Season 1") and choose "Select stream" - it will search for "season pack".
(if i understood you correctly)

**Comment by elgatito** [comment]
Saving of season's torrent for episodes will be fixed in the next version.
To trigger selection of torrent for a season, need to go to list of seasons for a show, then select context menu and "Select stream", then when you choose a torrent - it will be saved for episodes of a season.

**Comment by elgatito** [comment]
Try with v0.1.43.

**Comment by antonsoroko** [comment]
This feature works fine for me, thank you.
I guess this issue can be closed.
