### ISSUE TITLE
[Request] Please add a "settings" button to the main menu of elementum

### ISSUE THREAD

**Issue by pitsi** [elgatito/plugin.video.elementum#499]
## Expected Behavior
Add one more button that would open elementum's settings menu.

## Current Behavior
In order to get to elementum's settings now you have to either press "i", bring up the info page of elementum and select settings from there, or right click on it and select settings from that right click menu. This is ok for systems that have a keyboard or a mouse, but it is a no go for systems with a simple remote control, e.g. a rpi on a tv, because not all remote controls have that option button (the equivalent of right click) or an info button that works as it should on kodi.

## Possible Solution
No idea.

## Steps to Reproduce (for bugs)
1. Highlight elementum from kodi's video addons screen.
2. Press "i" on the keyboard or right click with the mouse, provided that your device has these peripherals
3. Select settings from the menu that just appeared
4. Edit elementum's settings as usual

## Context
I think one more button in this menu is enough. The button would lead to elementum's settings directly
![screenshot001](https://user-images.githubusercontent.com/5880037/67508027-d7f30280-f698-11e9-92b7-2a4e1d0f2f1c.png)

## Your Environment
* Version used: 0.1.41
* Environment name and version: Kodi 18.4 and 18.2 respectively
* Operating System and version: Debian testing x64 and libreelec 9.0.2 on rpi 3b+
* Link to Kodi debug log: Not needed

**Comment by elgatito** [comment]
@pitsi added in 0.1.43.
