### ISSUE TITLE
Support for Burst

### ISSUE THREAD

**Issue by unster** [elgatito/plugin.video.elementum#5]
Hi,

is Elementum going to support Burst provider(s)?

**Comment by elgatito** [comment]
Hi.
Elementum has own Burst (forked it, to be able to update it). It is available from Elementum repository.

**Comment by unster** [comment]
Hi @elgatito, can you please provide details to Elementum repository so I could add it to my local repo on Kodi on LibreElec?

**Comment by elgatito** [comment]
Repository works same as it was in Quasar, it's a virtual repository and Kodi is querying the elementum daemon for listing addons and their versions.
If you only need addon.xml for each module, you can try this:
http://elementum.surge.sh/packages/elgatito/plugin.video.elementum/addon.xml
http://elementum.surge.sh/packages/elgatito/script.elementum.burst/addon.xml

These urls are updated automatically with the latest addon.xml

**Comment by tomtomclub** [comment]
thank you men greet job
