### ISSUE TITLE
Torrent from ygg isn't downloading

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#500]
## Steps to Reproduce:
I put here one of the torrent files I have checked, a season pack (One of few I have tried)
* The torrent file: https://f2h.io/n99xs2g14yb4
* The torrent info from the site: https://bit.ly/2JrmI1o

When I try to download one of the episodes there (E02 for example) the download doesn't start.

Is it a problem with elementum (Torrent engine) or problem with ygg torrents?
* With Quasar it is the same by the way (There the P and S shows -1)
* With other providers by the way there is no such a problem.

![image](https://user-images.githubusercontent.com/13424257/67643938-71364900-f925-11e9-8205-f877c1ce7870.png)

Kodi Log:
https://paste.ubuntu.com/p/FgyCWRs6WS

===
Elementum 0.1.41
Kodi 17.6
Windows 10, 64bit

**Comment by elgatito** [comment]
Downloading is not what ELementum does. It is done by libtorrent. No seeds, no peers are found for that torrent. 
Maybe tracker is blocked for you and it's private, so not available via DHT.
