### ISSUE TITLE
[Bug] Resume playabck from torrents list isn't working for torrents that add through "Search Torrent"

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#501]
## Steps to Reproduce (for bugs)
1. Search a torrent in the general Torrents search in the main menu in Elementum
2. The torrent start downloading and play as usual.
3. I stop the playback, the torrent still downloading in the background
4. Going to the Torrents list, try to resume playback from there (Play / resume torrent), and nothing happen, doesn't play.
Usually the little 'busy' icon is shown and disappeared immediately, sometime the "Playback failed" dialog is shown instead. So I can watch it only from the File Manager and not from Elementum.
Even after restart kodi, it's still the same.

Kodi Log:
https://paste.ubuntu.com/p/t4CRHWhCd9

Focus on "Money Heist S03E02" (Money.Heist.S03E02.1080p.WEB.X264-EDHD.mkv)

* By the way, it's a little strange, because I opened a bug on the same version that also talk about this, but there it was working but there was another problem:
https://github.com/elgatito/plugin.video.elementum/issues/489

* EDIT: Probably the reason is that the torrent here was added through the "Search Torrent" option and not from the Trakt Menus for example, as mentioned here in other issue with similar problem (Issue #434 )

## Your Environment
Elementum, 0.1.41
Kodi 17.6
Windows 10, 64 bit

**Comment by burekas7** [comment]
@antonsoroko 
So now I understand why the same version act differently by playing from the Torrents list, as you said, in this issue I added the torrent through the "Search" option and not from Elementum/Trakt menus for example. I don't know for sure if this is the reason by probably.

**Comment by burekas7** [comment]
Now I can confirm, I have 2 torrents in the list, one was add through the Search Torrent option and the other was add through the Trakt -> My Collection menu. The one from Trakt is resume and play ok while the other one doesn't do anything when pressing on it (the "busy" icon shown for a second and gone, sometimes the "Playback Failed" dialog is shown, but most of the times just doesn't do anything)

What could be the reason?
What is the difference?

@elgatito

**Comment by elgatito** [comment]
Please, try with v0.1.43.

**Comment by burekas7** [comment]
@elgatito 
Still the same with v0.1.43

Kodi Log: https://paste.ubuntu.com/p/Vk7p9vRfMW
Focus on "Money Heist S03E02"

**Comment by elgatito** [comment]
I cannot reproduce the issue. 
Try with default Estuary skin.

**Comment by burekas7** [comment]
@elgatito 
Currently I have another bug with the "Search" section (before I would be able to check this issue)
https://github.com/elgatito/plugin.video.elementum/issues/524

@antonsoroko 
Which skin are you using?
Can you check this issue also?

**Comment by burekas7** [comment]
> Please, try with v0.1.43.

Still the same with 0.1.44
Trying to play a torrent from the torrent list that was added by the main Search torrents doesn't work.

Kodi Debug Log:
https://paste.ubuntu.com/p/NtHcRK5cj8

**Comment by elgatito** [comment]
I cannot reproduce your issue on default skin.

**Comment by burekas7** [comment]
I reproduced it also with the default skin: Estuary

Kodi debug log:
https://paste.ubuntu.com/p/WBH3D2sqpS

**Comment by antonsoroko** [comment]
i use fuse neue skin
but it is not a skin specific issue
same issue with estuary - https://github.com/elgatito/plugin.video.elementum/issues/434#issuecomment-571205521

**Comment by elgatito** [comment]
Should work with 0.1.49.

**Comment by burekas7** [comment]
I can't test it for now becuase this open issue: https://github.com/elgatito/plugin.video.elementum/issues/524

**Comment by burekas7** [comment]
Thanks, it's ok.
Checked with 0.1.50
