### ISSUE TITLE
1.41 segfaults on libreelec 9.80 on s905x

### ISSUE THREAD

**Issue by phlmm** [elgatito/plugin.video.elementum#502]
Perhaps is not really an issue, since I use mainly unofficial software, but still want to share. 

My issue is duplicates whats described in https://webcache.googleusercontent.com/search?q=cache:Basb8vqpfQ0J:https://github.com/elgatito/plugin.video.elementum/issues/485

1. All-in-one installation installs armv7 which segfaults without any useful info
2. running arm64 instance segfaults after starting torrent related tasks

## Expected Behavior
Elementum starts

## Current Behavior
Elementum segfaults

##  Solution 
1. workaround is to manually install arm64 and create symlink as shown below:
```sh
LibreELEC:~/.kodi/addons/plugin.video.elementum/resources/bin # ls -la
total 3
drwxr-xr-x    3 root     root          1024 Oct 30 22:40 .
drwxr-xr-x    9 root     root          1024 Oct 30 22:40 ..
drwxr-xr-x    2 root     root          1024 Oct 30 22:40 linux_arm64
lrwxrwxrwx    1 root     root            12 Oct 30 22:40 linux_armv7 -> linux_arm64/
```
2. Disable DHT in elementum config

## Steps to Reproduce (for bugs)
Install https://yadi.sk/d/DHePyyRcterLf on sd-card on a s905 based amlogic device
Install any version of elementum > 1.27
Expect elementum starts
Elementum crashes on kodi

## Context
Run elementum

## Your Environment

* Version used:1.41 (but any > 1.27 segfaults) 

* Environment name and version:
Kodi (19.0-ALPHA1 Git:e31d257e4b6a9c5a622bb280d4abc4e44dc9eca5). Platform: Linux ARM 32-bit
* Operating System and version:
Running on Amlogic Meson GXL (S905W) Amlogic Meson GXL (S905W) P281 Development Board with LibreELEC (community): devel-20191024145508-6e9040d 9.80, kernel: Linux ARM 64-bit version 5.4.0-rc3

* Link to Kodi debug log:

http://ix.io/20qy   -> kodi log
https://pastebin.com/EgvQr314 -> segfault strace
http://paste.kodi.tv/oxitaresij -> elementum works

**Comment by elgatito** [comment]
@phlmm  
> Install any version of elementum > 1.27

Anything below this version works fine?

**Comment by phlmm** [comment]
Yes, I've tried various version around 1.2 and they seemed to work. Anything I can do to help?

**Comment by elgatito** [comment]
Please, try v01.43 and later.

**Comment by elgatito** [comment]
Closing. Libc usage was restored in 0.1.43 and later.

**Comment by phlmm** [comment]
Thanks for fixing the issue! It works as expected now.
