### ISSUE TITLE
Music plugin?

### ISSUE THREAD

**Issue by rockofclay** [elgatito/plugin.video.elementum#503]
I couldn't find feature requests anywhere, so I submitted this as an issue. Sorry if I've put this in the wrong spot.

Is it possible to use the elementum addon to build a music library? Or does a whole new kodi addon need to be built?

**Comment by elgatito** [comment]
You can search some torrent directly and probably pass it to Kodi. 
But it looks pretty hard from my side. I assume there are existing plugins for that.
