### ISSUE TITLE
[Request] Solid background addon icon

### ISSUE THREAD

**Issue by queeup** [elgatito/plugin.video.elementum#505]
Transparent background addon icon is not looking good on kodi addon browser or on the widgets. Please consider to change 100% solid background.

Example:
![icon](https://user-images.githubusercontent.com/87835/68849953-1c941b80-06e4-11ea-9231-283529835b50.png)

**Comment by elgatito** [comment]
Changing to static background will make it look good in one skin, and bad in others.
Anyway, I'm not a designer, feel free to make a change and make a PR for it.

**Comment by queeup** [comment]
All add-ons are solid(static) backgrounds on the official repo. It's their design rules I guess. https://kodi.wiki/view/Add-on_structure#icon.png

It's up to you to follow their rules. If you are OK with transparent background I am fine with It.
