### ISSUE TITLE
[Feature] 401 error from Trakt should be properly treated and shown

### ISSUE THREAD

**Issue by ThurahT** [elgatito/plugin.video.elementum#506]
Elementum can't display my Trakt lists anymore. I can briefly see the error from line 408 in the kodi.log in Kodi notification popup. 

TV-show Progress, Watchlist, Collection, every Trakt list I try come up as bad request. This is also not an isolated incident. Confirmed on another box running Devuan (Debian old stable) with Kodi 17.1. This happened the first time almost a week ago I believe.

[kodi.log](https://github.com/elgatito/plugin.video.elementum/files/3849271/kodi.log)

**Comment by elgatito** [comment]
You should try to re-authorize Trakt in Elementum. 
Settings -> Trakt

**Comment by ThurahT** [comment]
Okay, That fixed it, but I don't understand why it broke in the first place? I didn't try to reauthorize since my Trakt account was visible in Elementum and in the kodi.log so I assumed smthng else was wrong. Also it broke on another box with another Trakt account which got Elementum installed at a much later date which furthermore added to my assumption about a something else broke. I'll go ahead and reauthorize that box as well. Thanks for a great addon!

**Comment by elgatito** [comment]
@ThurahT Trakt does authorization of a session, so maybe they have invalidated it. It seems they can do it if token was not used for some time. That happens sometimes.

**Comment by elgatito** [comment]
Trakt errors regarding authorization now show with an alert in Kodi.
