### ISSUE TITLE
Elementum крашится

### ISSUE THREAD

**Issue by hyperpuncher** [elgatito/plugin.video.elementum#507]
При выборе аниме крашится сразу же и перезагружается. Всё работало отлично, ничего не трогал и где-то день-два назад начал крашиться каждый раз на компе и на Mi Box.
## Your Environment

* Version used: Elementum 0.1.41

* Environment name and version: Kodi 18.4

* Operating System and version: Android TV 8.1, macOS 10.15.1

* Link to Kodi debug log: http://paste.kodi.tv/mojexomiwi

**Comment by elgatito** [comment]
Связано с неработающим Tvdb, и отсутствием проверок на это в приложении.
Спасибо за репорт.

**Comment by hyperpuncher** [comment]
Понял, буду ждать когда TVDB поднимется.

**Comment by hyperpuncher** [comment]
Всё работает.
