### ISSUE TITLE
[Bug] Sorting option for 'Trakt -> Progress' isn't saved

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#508]
## Steps to Reproduce (for bugs)
1. Go to Settings -> Trakt -> Progress
2. Currently my option is "By air date (older)", so I try to change it to "By air date (newer)
3. OK for saving the settings.
4. Go back and check if the option was saved, but it still show "By air date (older)" instead of "By air date (newer) as I want.

* Note: It happens with each of the options there, non of them is saved after press the OK button.
It still show that the sorting is "By air date (older)"

* Link to Kodi debug log: https://paste.ubuntu.com/p/Kmz8v9yxjh

## Your Environment
* Version used: Elementum 0.1.41
* Environment name and version: Kodi 17.6
* Operating System and version: Win 10, 64bit

**Comment by elgatito** [comment]
It works as expected. Make sure sorting in Kodi is set to "Default", then it will give sorting to Elementum. Otherwise Kodi will sort same list in the same way.

**Comment by burekas7** [comment]
You right, when kodi sorting is 'Default' the Elementum Trakt Progress sorting is saved and change the order as selected.
Thanks.
