### ISSUE TITLE
[Bug] Unicode chars in file names

### ISSUE THREAD

**Issue by hyperpuncher** [elgatito/plugin.video.elementum#511]
Я так понял, что проблема где-то тут, но понятия не имею как пофиксить.
```
ERROR: [plugin.video.elementum] (elementum.rpc) In Handler method ElementumRPCServer.Player_SetSubtitles([u'http://127.0.0.1:65220/files/Boku ...)
ERROR: [plugin.video.elementum] Unhandled error: UnicodeEncodeError: 'ascii' codec can't encode characters in position 51-58: ordinal not in range(128)
```
## Your Environment

* Version used: Elementum 0.1.41

* Environment name and version: Kodi 18.5

* Operating System and version: Android TV 8.1, macOS 10.15.1

* Link to Kodi debug log: http://paste.kodi.tv/kicuxilavi

**Comment by elgatito** [comment]
@hyperpuncher 
Проявляется не всегда?

**Comment by hyperpuncher** [comment]
Заметил, что иногда подтягивает, но если их выбрать, то сразу же перекидывает на вшитые.

**Comment by elgatito** [comment]
@hyperpuncher С последней версией ошибка тоже есть?

**Comment by hyperpuncher** [comment]
Перестал пользоваться элементумом, закрывать?
