### ISSUE TITLE
Removed from library tv shows are added again on next library sync

### ISSUE THREAD

**Issue by peter099** [elgatito/plugin.video.elementum#514]
If i remove any of the added to my library tv shows their are added again on the next library sync. I am removing them from Kodi, i tried also deleting the .strm files of the show and cleaning the library, but the shows are added again on the next sync. Any idea why this is happening? 

Using Kodi 17 on Windows 7 with elementum 0.1.41. 

This is the log: https://pastebin.com/VuJFdF8P

**Comment by peter099** [comment]
It seems that the issue is with storm.db database file. If i remove tv show from the library and then delete storm.db file, the tv show is not added again on the next library sync. But if i remove the tv show and don't delete storm.db file, the tv show is added to the library again on the next library sync.

**Comment by elgatito** [comment]
You should find the show in Elementum and delete it from context menu there.
Otherwise, Elementum is re-adding strm files and Kodi is re-importing them as well.

**Comment by peter099** [comment]
Deleting the show from context menu doesn't work. Only deleting storm.db file worked.
