### ISSUE TITLE
Elementum data folder big size

### ISSUE THREAD

**Issue by peter099** [elgatito/plugin.video.elementum#517]
The size of elementum data folder plugin.video.elementum has become 1.25GB. Why is that? The files with bigger size are: 

app.db - 385MB
app-backup.db - 384MB
cache.db - 245MB
cache-backup.db - 193MB

**Comment by elgatito** [comment]
Cache becomes bigger. 
History of played torrents is also stored. 
You can remove databases any time.

**Comment by peter099** [comment]
I deleted all four databases and after starting Kodi the cache.db and cache-backup.db databases were recreated, but app.db was not. What information app.db database contain?
