### ISSUE TITLE
Add to trakt collection context menu from widget.

### ISSUE THREAD

**Issue by pompe84** [elgatito/plugin.video.elementum#518]
Some skins offer a way to display content via widgets (Aura) on the main screen. When opening the context menu on selected media when on a widget there aren't options to add to watchlist or collection. I guess that is somewhat a Kodi issue, but I believe it can still be enabled. For instance the standalone trakt and Add to watchlist addon https://kodi.wiki/view/Add-on:Trakt_-_Add_to_watchlist_button will display the option in the context menu on a widget, but it just doesn't work. Maybe 2 separate add-ons that connect to Trakt can't work together in Kodi. Anyway, examining the Add to watchlist add-on code I find it to be really simple, just calling a function from the Trakt add-on. Is there a way to do the same for Elementum?

**Comment by elgatito** [comment]
@pompe84 I don't understand this. What exactly is needed?

**Comment by elgatito** [comment]
Closing without getting response.
