### ISSUE TITLE
[Question] Can't find "Language code for subtitles (example: en, it, es)" option

### ISSUE THREAD

**Issue by Nukles** [elgatito/plugin.video.elementum#519]
I can't find anymore the option in the Menu that searched for subtitles in a specific language. It's called "Language code for subtitles (example: en, it, es)" and it is somewhere in the Elementum Options but I can't find it anymore. I just found this github code that translates this option but I can't find the option in the Elementum Menu. https://github.com/elgatito/plugin.video.elementum/blob/master/resources/language/French/strings.po

**Comment by elgatito** [comment]
@Nukles 
Subtitles language is about OpenSubtitles. It is located in a separate settings tab.
