### ISSUE TITLE
Низкая скорость

### ISSUE THREAD

**Issue by Dmitry55** [elgatito/plugin.video.elementum#520]
[settings.zip](https://github.com/elgatito/plugin.video.elementum/files/3965191/settings.zip)

Добрый день. 
18.2 Git:20190428-a94ccc8ba5 Media Center Kodi
Paspberry pi 3B
На версии 0.1.41 скорость скачивания от 300 до 900 КБ/ceк, при этом через некоторое время после начала просмотра видео начинает тормозить
Если сделать откат до 0.0.71 скорость возрастает до 3000-4000КБ/сек.
Может что в настройках можно поменять. Не хотелось бы оставаться на старом релизе.

**Comment by elgatito** [comment]
Нету лога что происходит, нету информации о выбранных настройках.
Но хотите советы что менять?

**Comment by Dmitry55** [comment]
Добрый день. 
Лог прикладываю. Настройки я уже выкладывал, но на всякий случай продублирую
[kodi.zip](https://github.com/elgatito/plugin.video.elementum/files/3979316/kodi.zip)
[settings.zip](https://github.com/elgatito/plugin.video.elementum/files/3979322/settings.zip)

**Comment by elgatito** [comment]
@Dmitry55 В архивах settings.xml тот что идёт с дополнением, где список всех доступных настроек, а не выбранные значения.

**Comment by elgatito** [comment]
Лог Kodi тоже бесполезный и сделан неправильно.
http://elementum.surge.sh/contribute/log/

**Comment by elgatito** [comment]
Закрываю тикет ввиду отсутствия информации.
