### ISSUE TITLE
[Request] Please offer a way to disable the elementum subtitles "provider"

### ISSUE THREAD

**Issue by pitsi** [elgatito/plugin.video.elementum#521]
## Preface
A few years ago, I was using the opensubtitles addon for my subtitle needs. Since the site owners demanded an account to let the addon download any subtitles, I removed it and started using the opensubtitles by opensubtitles one from [here](https://github.com/opensubtitles/service.subtitles.opensubtitles_by_opensubtitles).  I consider the above to be a stupid rule, because it applies only to kodi users. Other apps that use their api, e.g  almost all media players like vlc, smplayer etc, do not demand the usage of an account. And that is why I totally hate that approach, because they somehow want to track kodi users.

## Expected Behavior
Those credentials can also be used in elementum too (settings > subtitles > opensubtitles > 2 fields for username and password), for automatic or manual downloading of subtitles. I have not and can not test it because I will never make an account for them.

## Current Behavior
So, I was thinking if you can give us the option to disable the elementum "provider" from the download subtitles window, either via a simple "use elementum subtitles" selection box in elementum's settings, or via a small if-else check, e.g. "if those fields are blank, do not offer elementum subtitles as an option".

Keep in mind that without credentials, an error pops up as seen here
![screenshot000](https://user-images.githubusercontent.com/5880037/71151776-45f11b80-223d-11ea-897f-04878a963c59.png)

## Possible Solution
No idea.

## Steps to Reproduce (for bugs)
Although it is not needed.
1. Start a video.
2. Press m or move the mouse to get the on screen menu.
3. Go to subtitle settings > download subtitle.
4. Select elementum as the provider and notice what I post on the above screenshot

## Context
Please read above

## Your Environment
* Version used: 0.1.41
* Environment name and version: Kodi 18.5
* Operating System and version: Debian testing x64
* Link to Kodi debug log: Not needed

**Comment by elgatito** [comment]
https://github.com/elgatito/plugin.video.elementum/blob/master/addon.xml#L13

I believe it is a static value, if addon provider subtitles or not. 
If you find any way to control it - I will take a look.

**Comment by pitsi** [comment]
I have literally 0 experience in coding, sorry :(
If it is not doable, feel free to close the issue report here.

**Comment by burekas7** [comment]
@elgatito 
Why not just remove it at all?
For each subtitles provider usually has their own addon.
Elementum shouldn't need to provide any support for subtitles, I think.

**Comment by KillerJoeBR** [comment]
I like elementum having its own subtitle provider because it can automatically download subtitle. That's a great feature. I also like the ability to set the provider to search a specific language in the settings. So I use the elementum subtitle to only search in Brazilian Portuguese while I can also use the official opensubtitle addon to search also  English subtitles in case I need.

And I don't know why sometimes the elementum provider find results and the official one doesn't work. And sometimes it's the opposite. But it's good to have a fallback option

**Comment by pitsi** [comment]
@KillerJoeBR 
Fyi, you can set any subtitle addon to search for more than one language from kodi's settings

![screenshot000](https://user-images.githubusercontent.com/5880037/71554424-8283fa80-2a27-11ea-8e53-153363aba2f7.png)

Obviously, the addon/providing site has to support those languages. which means that even if you set e.g. the langiage to Portuguese and use a greek subtitle addon, you will get no results.

**Comment by elgatito** [comment]
Closing. As there is no way to optionally disable subtitles, and subtitles removal will not be here.
