### ISSUE TITLE
elementum crash loop after kodi update

### ISSUE THREAD

**Issue by 4lphac** [elgatito/plugin.video.elementum#523]
Elementum stuck in a crash loop in ubuntu latest, .kodi/temp/kodi.log doesn't show anything useful, how can I send you more detailed info?

**Comment by elgatito** [comment]
Next time send log files.
That information is available when you open the issue on Github.

Wait 30 minutes before 0.1.43 is available. 0.1.42 is broken for Linux systems.

**Comment by elgatito** [comment]
@4lphac please, try v0.1.43 and later.

**Comment by elgatito** [comment]
Closing without getting a response.
