### ISSUE TITLE
Can't remove TV shows from Library

### ISSUE THREAD

**Issue by dmitrymikhnevich** [elgatito/plugin.video.elementum#525]
The same issue as described there: #481 

I'm running Kodi 18.5 on Android TV 9.

In v 0.1.43 I still have the issue that TV shows removed from the Kodi library reappear there after some time. I tried both ways to remove TV shows: in Kodi library itself and in Elementum (via a context menu "Remove from Kodi Library"). Please advise.

**Comment by dmitrymikhnevich** [comment]
Here is my log: https://paste.kodi.tv/ehowogowek

**Comment by dmitrymikhnevich** [comment]
There is a workaround in #481 suggested by the other user, which worked for me:
>From Elementum
Remove show from library
Merge show to library
Remove again

**Comment by elgatito** [comment]
Please, try with 0.1.44. Removal should be done again, but it should remove files on the disk and not re-add it later.

**Comment by zukove** [comment]
dmitrymikhnevich - does it work for you now?

**Comment by dmitrymikhnevich** [comment]
Works well now.
