### ISSUE TITLE
Delay at the start of download when selecting season pack

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#527]
## Steps to Reproduce (for bugs)
1. Search for The WItcher S01E02 (I'm search from Trakt....)
2. Select the episode from Season pack:
The.Witcher.US.S01.COMPLETE.1080p.WEB.x264-STRiFR[TGx]
3. The downloading start.
4. After a while when the percentage in the notification message rising, the buffer download in the dialog actually start downloding and when the percentage reached to 100% the playback start as normal. 
When I'm back to the main screen, the percentage in the notification shows the total progress, as normal.

So I have two questions:
1) Why it takes so long until the episode buffer start downloading when choosing a torrent which exist in Season pack?
2) What does the percantge in the notification mean before the buffer start downloading? What is the progress there? Because the download is on 0kb/s and there is no percentage value in the dialog, only in the notification.
(I have attached also video)

* Just to mention that it happened also with another tv show.
* I have attached also video files for illustration.

* Example1: (Elementum 0.1.43)
Video file to download: https://f2h.io/vkyfpmgccz7r
Kodi Log: https://paste.ubuntu.com/p/tFq5yq2NQp
(Focus on The Witcher S01E02 as shown in the video and described above)

* Example2: (Elementum 0.1.42)
Here it takes much longer until the buffer start downloading (The percentage in the notification reached to ~80% until the buffer start)
Video files: 
Part1 - https://f2h.io/lcck3qxmpvtp
Part2 - https://f2h.io/0holeijasw93
Kodi Log: https://paste.ubuntu.com/p/mHXmYsNCJC
(Focus on 13 Reasons Why as shown in the video)

Elementum: 0.1.43
Burst: 0.0.40
Kodi: 17.6
Windows 10, 64bit

**Comment by elgatito** [comment]
```
00:51:01.394 T:16172  NOTICE: [plugin.video.elementum] INFO  bittorrent   в–¶ AddTorrent       Waiting for information fetched for torrent: c340297ea1486bc634a25d0c0584047c9cb8b691
00:51:06.257 T:16172  NOTICE: [plugin.video.elementum] INFO  bittorrent   в–¶ AddTorrent       Information fetched for torrent: c340297ea1486bc634a25d0c0584047c9cb8b691
```

You have selected torrent, provided by magnet link.
To get list of files we need to resolve the magnet, that can take some time (made by libtorrent). 
There is no way to speed it up.

**Comment by burekas7** [comment]
Ok, so it's normal. Thanks.

So there is no meaning to the percentage value itself which shown before the buffer start in the notification?
Because the buffer start downloading in different value, one time it was after ~30% one time after ~80%

**Comment by elgatito** [comment]
I have added a notification to 0.1.44 when magnet resolving is in progress.
