### ISSUE TITLE
[Bug] Selecting "No" in Delete Torrent dialog still delete the torrent

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#529]
## Steps to Reproduce (for bugs)
1. Focus on a torrent in the torrents list
2. Open the context menu for it.
3. Select "Delete Torrent"
4. In the dialog press on "No"
5. The torrent is removed instead of cancel it.

Kodi Debug Log:
https://paste.ubuntu.com/p/9bmtfKqvTM

Video:
https://f2h.io/c64unxzfd8zb

* Elementum: 0.1.44 (It was also with 0.1.43)
* Kodi 17.6
* Skin: Titan 3.7.x
* Windows 10, 64bit

**Comment by elgatito** [comment]
> Select "Delete Torrent"
> The torrent is removed instead of cancel it.

What is a "Cancel" that you expect when you choose to "Delete"?

**Comment by burekas7** [comment]
> > Select "Delete Torrent"
> > The torrent is removed instead of cancel it.
> 
> What is a "Cancel" that you expect when you choose to "Delete"?

Sorry, By selecting "NO" I meant cancel the dialog without remove the torrent from the list.
Actually, "NO" is acting like "YES" here.

**Comment by burekas7** [comment]
I reproduced it also with the default skin: Estuary

Kodi debug log:
https://paste.ubuntu.com/p/xzsswnyS38

**Comment by antonsoroko** [comment]
@burekas7 
i might be mistaken but in your video it is looks like that new "auto choose yes after N seconds" feature was executed before you managed to click "no".

**Comment by burekas7** [comment]
@antonsoroko 
1. This feature is disabled for me.
Btw, I think this feature is shouldn't be exist, who said that "Yes" (or "No") should be the correct choice for all the dialogs. But this is for another discussion.

2. In the video you can see that I clearly click on the "No" choice, there is no timeout or something that was done automatically. By the way I increased the timeout value, and for the video I waited a while to illustrate the click event, but it occurs also when I click immediately when the dialog appears.

**Comment by burekas7** [comment]
Btw, I have the same issue with the dialog of "Keep Downloading" which popup when I stop a playback, and choose "Yes", the torrent probably still exist in the background because when I play  it again, it recognize it and play, but the torrent itself is removed from the torrents list in "Torrents" menu.
It's like no matter what I choose in these dialogs it remove it from the list (While it seems to be still in the background, or not)

Elementum 0.1.47
Kodi 17.6
Skin Titan
Win 10, 64 bit

**Comment by burekas7** [comment]
With 0.1.51 there is no dialog at all, selecting "Delete Torrent" from the side menu remove it from the torrent list without asking if I'm sure as before. Is it normal?

**Comment by elgatito** [comment]
@burekas7 In 0.1.51 if you don't select any file - torrent is forced to remove. You can't add torrent without selecting files.

**Comment by burekas7** [comment]
There are 2 issues with this "Delete Torrent":
*Delete Torrent*
![image](https://user-images.githubusercontent.com/13424257/80312009-94b25180-87eb-11ea-9898-5a5904933da4.png)

1) With the default skin in kodi 18.6 (Clean Kodi)
When I choose here "No" in this dialog:
*The Dialog*
![image](https://user-images.githubusercontent.com/13424257/80312130-45205580-87ec-11ea-9556-27c70dd0e4d0.png)
It ignores my selection and still remove it from the torrents list, like there is no meaning if I choose "Yes" or "No" it still removes it from the "Torrents list".

Kodi Log: https://paste.ubuntu.com/p/2dcrws6KkN

2) In my current build (kodi 17.6, Titan skin) this dialog isn't shown at all.
The setting of "Automatically answer Yes after timeout" is OFF.
I'm still testing my build and see what may make it happens, bacause with clean Kodi with Titan the dialog is shown.

**Comment by elgatito** [comment]
The dialog, that you show, is asking to delete torrent FILES. Torrent itself will be deleted from elementum, that is the purpose of 'delete torrent'.

**Comment by burekas7** [comment]
The problem is not with what it does, the problem is with the dialog itself. 
What is the purpose of answering 'yes' or 'no' while both of them make the same and remove the torrent from the list?
I expecting when I choose "No" nothing would happen so the torrent remain in the list, and when I choose yes, it will remove the torrent from the list and the torrent file itself (Without touching the video file)
(While 'Delete Torrent and Files' will remove also the video file with the torrent file)

**Comment by elgatito** [comment]
> The problem is with the purpose of dialog.

There is no problem with it. 

> I'm expecting when choosing "Delete Torrent" The dialog should relate only to "Delete Torrent file" and not to "Delete Torrent Video Files".

It is about deleting files IN THIS TORRENT, and not about any `.torrent` file.

When you choose "Delete torrent" - it will, surprise, DELETE THE TORRENT.

There are no options to remove or leave `.torrent` file, you should not care about it.

I'm closing this issue, because it is not an issue. The logic will not change, unless you change it youself.
