### ISSUE TITLE
Playback stop suddenly and disapper

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#532]
## Steps to Reproduce (for bugs)
1. I search and play this episode from Trakt -> MyProgress (Westworld S02E03)
2. After 10-20 seconds the playback suddenly stopped, and the torrent download also stopped and disapper also from the torrents list
3. After restarting Kodi, the torrent show up and continue the downloading
4. Go again to MyProgress and press on the same episode, it doesn't recognize that there is a torrent that already download and ask for new search.
5. Also when I try to play it from the torrents list, it doesn't do anything, just continue the download without an option to play it from the addon.

I don't have debug log because I didn't test anything so I didn't active the debug logging.
Since the last versions there is instability with Elementum and I don't know why.
It wasn't like this before, strange failures.

Kodi Log:
https://paste.ubuntu.com/p/sHwDpCwKmf
After restart: https://paste.ubuntu.com/p/VnTVhbd6NH

## Your Environment
Elementum 0.1.44
Kodi 17.6
Skin: Titan
Windows 10, 64 bit

**Comment by elgatito** [comment]
@burekas7 is there still an issue with the latest version?

**Comment by burekas7** [comment]
I forgot it :)
It seems good for me with 0.1.62

Closing it.
Thanks.
