### ISSUE TITLE
elementum 0.1.47 crashes upon launch on Android 4.4.2 , kodi 16.1

### ISSUE THREAD

**Issue by std781** [elgatito/plugin.video.elementum#542]
Hi,
Recently elementum crashes on my android tv box 
I have reinstalled but still doesn't work.
Suspecting updated addon which conflicts with elementum.

OS  Android 4.4.2, Amlogic S812
Kodi version 16.1
elementum  0.1.47

attaching kodi log:

[kodi.zip](https://github.com/elgatito/plugin.video.elementum/files/4085403/kodi.zip)

Thanks

**Comment by elgatito** [comment]
Latest version does not work on old Kodi due to old python version.

**Comment by std781** [comment]
Thanks :) elementum 0.1.41 is working fine
