### ISSUE TITLE
HELP ME 

### ISSUE THREAD

**Issue by auguzsto** [elgatito/plugin.video.elementum#543]
Sorry for the bad English.

I have an android box, and I'm not able to install Elementum. In downloads there is no compatible version with my box type, an android armv7. It only has arm64, x86. None of these works in my box! Could someone help me, please?

**Comment by AlekseyS2877** [comment]
Hi! Try ALL platforms version "plugin.video.elementum-0.1.47.zip" size 159Mb.

**Comment by antonsoroko** [comment]
@auguzsto 
https://github.com/elgatito/plugin.video.elementum/releases

Your box probably need plugin.video.elementum-0.1.47.android_arm.zip

But as it was stated above, first time it is better to use "full bundle" (you can determine it by size).
So I also suggest you to use plugin.video.elementum-0.1.47.zip
