### ISSUE TITLE
Latest update brough a really annoying bug, the torrent list doesn't populate anymore when downloading a torrent, unless you Restart.

### ISSUE THREAD

**Issue by Kristijan1001** [elgatito/plugin.video.elementum#545]
I know he killed the development, but latest update brought a bug where if you download something, it won't show under the torrents category anymore. You have to completely restart Kodi for it to show.

This eliminates the ability to pause, delete or play from The Torrent Category in Elementum, unless you restart kodi. I did a whole wipe with Kodi problem still persists.

**Comment by antonsoroko** [comment]
Yeah, I have the same issue :-( but since development was stopped I decided not to file a bug.
But I guess this bug could be useful for "next generations" :-)

**Comment by Kristijan1001** [comment]
> Yeah, I have the same issue :-( but since development was stopped I decided not to file a bug.
> But I guess this bug could be useful for "next generations" :-)

I really wish he just fixes, it probably is something minor (speculation have no idea). Kinda sucks how the latest version is the most broken one :(

**Comment by Kristijan1001** [comment]
> Yeah, I have the same issue :-( but since development was stopped I decided not to file a bug.
> But I guess this bug could be useful for "next generations" :-)

This is even more broken than i realized. Even after restart if you try to play the movies from the downloaded torrents section it doesnt do anything.... Only way to play the movies is to find the movie again and play it from there.

**Comment by antonsoroko** [comment]
Yeah :-(
Another workaround is to open torrent from "torrents history" (item in main menu).

**Comment by burekas7** [comment]
Yes me too.
But as @antonsoroko said, there is no point to open bugs since the development stopped.
And there are still open bugs to fix.

**Comment by elgatito** [comment]
Should be fixed in 0.1.48, but only for newly added torrents.

**Comment by antonsoroko** [comment]
works fine for me, thanks!

**Comment by burekas7** [comment]
Works for me too. Thanks!

**Comment by Kristijan1001** [comment]
@elgatito or someone, you mentioned only newly added torrents will work. But i have downgraded to v0.1.4.5. Will updating to 0.1.48 make the old torrents work too , because right now everything is working perfectly fine for me on 0.1.4.5. Just wondering if i should update, because i don't want to lose all of the old torrents and make them unclickable.

**Comment by elgatito** [comment]
@Kristijan1001 information about played content was deleted on playback stop. And that also removed torrent from the list of torrents. So if you have that information in the database - it will continue to work, if not - only re-addition of torrent will help to save information again.

**Comment by Kristijan1001** [comment]
@elgatito Just updated . Works Perfectly. Thank you!
