### ISSUE TITLE
Daemon notification on startup

### ISSUE THREAD

**Issue by mkaflowski** [elgatito/plugin.video.elementum#547]
Is it possible to disable daemon notification on startup or start daemon when launching the addon by user? What daemon do when I dont use Elementum?

**Comment by tomaskazragis** [comment]
I’ve been interested in this as well. Unfortunatelly the answer is no. There is a work around - to comment few lines in golang code, rebuild elementum and then rebuild kodi addon. To be honest it’s pretty easy, but you’ll either lose your changes upon update or updates in case they will be released ;)


T.K.

**Comment by mkaflowski** [comment]
Thats a shame :( It could be the option in preferences. Does it download or upload some data when I d not stem videos or it is in idle?

> Wiadomość napisana przez tomaskazragis <notifications@github.com> w dniu 31.01.2020, o godz. 10:17:
> 
> I’ve been interested in this as well. Unfortunatelly the answer is no. There is a work around - to comment few lines in golang code, rebuild elementum and then rebuild kodi addon. To be honest it’s pretty easy, but you’ll either lose your changes upon update or updates in case they will be released ;)
> 
> 
> T.K.
>

**Comment by pitsi** [comment]
Afaik, the only thing that uploads and downloads data when elementum is idle is the automatic scrape function. If you keep it disabled, nothing is downloaded or uploaded.

**Comment by elgatito** [comment]
You cannot disable startup notification. Plugin is waiting for requests, torrent service is running and waiting for torrents.
