### ISSUE TITLE
Yggtorrent don't work anymore

### ISSUE THREAD

**Issue by Ilysia52** [elgatito/plugin.video.elementum#548]
Hello, I know that the development has stopped (and thanks to elgatito for this great work), but I would like to know if anyone knows how to add Yggtorrent again? they have changed their address to .se and now there are no more results on the search.
In domain alias I tried to add .se or yggtorrent.se but it didn't work, I'm not sure to do the right manipulation ? Or there is nothing to do? :(

Thank you!

**Comment by antonsoroko** [comment]
Hi.
This is actually burst issue - github.com/elgatito/script.elementum.burst/

And it has a method to solve it by yourself.

Use overrides - https://github.com/elgatito/script.elementum.burst#adding--editing-providers
So in you case you probably just need to override `base_url ` for `yggtorrent`, see original definition here https://github.com/elgatito/script.elementum.burst/blob/96821f3ea36186398a669884db5e3d069d2ceba9/burst/providers/providers.json#L2424
Or you can even copy-paste the whole provider to new `.json` file and fix other issues with this provider if they exist (like new search query pattern, for example).


P.S. As a dirty hack you can try to use aliases, e.g. in linux you can use `/etc/hosts` file and if you know new ip address of yggtorrent you can specify it for old domain. But it is better to use the method I described above.

**Comment by elgatito** [comment]
Providers are not linked to this plugin.
