### ISSUE TITLE
Сhange the color of the resolution

### ISSUE THREAD

**Issue by PostnikovArtem** [elgatito/plugin.video.elementum#549]
Hello! Tell me, please, how to change the color of the resolution in the search for torrents in your plugin?
![Z4zQW8E_ELo](https://user-images.githubusercontent.com/27950783/74487234-ff800c00-4ecf-11ea-8899-4b9e398b888a.jpg)

**Comment by elgatito** [comment]
https://github.com/elgatito/elementum/blob/master/bittorrent/torrent_file.go#L105
Colors are static values.
