### ISSUE TITLE
Any way to seed after finish diwnloading? 

### ISSUE THREAD

**Issue by arlekyn2** [elgatito/plugin.video.elementum#550]
Hi, 

Just wondering if there are any settings to keep seeding the downloaded torrent. 
I use "save to drive"  specifically for this purpose (to seed after downloading), but connection to the tracker is closed as soon as the download is finished. 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

**Comment by antonsoroko** [comment]
I have set "seeding time" and "seed ration" in torrent section of settings to large values and I can see in web ui that seeding works even for very old torrents.
Give this a try.

**Comment by elgatito** [comment]
Seeding is controlled in Bittorrent tab of Elementum Settings.
