### ISSUE TITLE
bad status

### ISSUE THREAD

**Issue by PostnikovArtem** [elgatito/plugin.video.elementum#552]
Hello! On all my devices, when I open the “in trend” tab, I get bad status getting trending Trakt shows: 503. Please tell me what you can do about it. Thanks!

**Comment by elgatito** [comment]
You should update to the latest version or create custom Trakt API keys and use them.

**Comment by antonsoroko** [comment]
@PostnikovArtem 
i would recommend to update *and* create a custom API key. guide - https://github.com/elgatito/plugin.video.elementum/issues/534#issuecomment-571752668
