### ISSUE TITLE
Not starting any torrent

### ISSUE THREAD

**Issue by Cyroq** [elgatito/plugin.video.elementum#553]
Since a few weeks, Elementum doesn't start any torrent. I can search, see the list of trackers, but when I choose one Kodi is loading for a second and then returns to the main menu. When I add a torrent by magnet URL the same thing happens: it does not start buffering.

I checked the logs and found this:
`ERROR: GetDirectory - Error getting plugin://plugin.video.elementum/playtorrent`

I tried downgrading to version 0.1.44 and 0.1.41 (copying manually to /home/osmc/.kodi/addons/plugin.video.elementum) but it doesn't seem to make any difference. I know support has ended but maybe somebody else experiences the same problem and knows how to solve it?
Thanks in advance.

**Comment by elgatito** [comment]
@Cyroq  no one can help you without log files.

**Comment by filippeof** [comment]
I have the same issue. Here it is the logfile:
paste.kodi.tv/siquzoleku

**Comment by elgatito** [comment]
@filippeof what you have in the log is that you select a magnet and it cannot be resolved for some reason. Maybe DHT is not working for you.

```
2020-04-09 12:39:19.578 T:1521992576  NOTICE: [plugin.video.elementum] INFO  bittorrent   ▶ AddTorrent       [0mWaiting for information fetched for torrent: ee5240d6a3376b2733430b30f7889b11f6eeb033
```

**Comment by elgatito** [comment]
@Cyroq you can try with 0.1.51, maybe it will solve your problem.

**Comment by Cyroq** [comment]
Thank you @elgatito. I tried 0.1.51 but that did not fix the problem. This is the log: https://paste.kodi.tv/yovinuzuza.kodi

**Comment by elgatito** [comment]
@Cyroq your Elementum starts twice. Try to uninstall and re-install the addon.

**Comment by Cyroq** [comment]
I uninstalled the addon, rebooted and installed in again. Unfortunately, the problem persists. The log from re-install to error: https://paste.kodi.tv/qiwupokife.kodi

**Comment by elgatito** [comment]
@Cyroq there is no information what is going on with the addon.

**Comment by Cyroq** [comment]
When I insert a magnet url, a loading icon shows up for a few seconds and Elementum goes back to the main menu. I have no other information about the addon. How can I retrieve more information that is useful to you?

**Comment by elgatito** [comment]
@Cyroq you should enable debugging mode. http://elementum.surge.sh/contribute/log/

**Comment by Cyroq** [comment]
Thank you. This is the log with debugging and event logging: https://www.dropbox.com/s/x71c3trkabyzb17/kodi.log?dl=0 (it's too big for paste.kodi.tv)

**Comment by elgatito** [comment]
@Cyroq I see you have a dialog to select file or enter torrent url and that is the last message there. What you do there?

**Comment by Cyroq** [comment]
I insert the magnet url and press OK, after which Elementum closes the dialog, shows the loading icon for a few seconds and then stops.
On previous attempts the 'Trending' and 'Popular' lists etc were empty, I am now able to start a torrent from there. Playing a torrent by url still doesn't seem to work.

**Comment by elgatito** [comment]
> On previous attempts the 'Trending' and 'Popular' lists etc were empty, I am now able to start a torrent from there. Playing a torrent by url still doesn't seem to work.

It is not normal, I don't know what happens with your installation. 
Maybe someone ever will help you.

**Comment by elgatito** [comment]
@Cyroq Please try with 0.1.52 and post a new log file after testing.

**Comment by namelivia** [comment]
I was facing a similar issue and updating fixed it for me. Thank you for the update! You rule!

**Comment by Cyroq** [comment]
Unfortunately the update did not make any difference for me. Log: https://paste.kodi.tv/ovuqitaduv.kodi

**Comment by elgatito** [comment]
```
ERROR: [plugin.video.elementum] Failed to wait till window has finished loading
```

You have a "busy" dialog, probably a running wheel, so playback does not start.
Not having a solution for that.

**Comment by Cyroq** [comment]
Strange, I did not see any dialog or running wheel. I pasted my magnet link, hit OK and the dialog window closed and nothing happened. 
Maybe I'll try a complete reinstall of Kodi some day. Nevertheless, thank you for your help.

**Comment by damionx7** [comment]
try changing your skin . i had aura and the same issue. changing theme fixed this for me.

**Comment by elgatito** [comment]
@Cyroq Please, try with Elementum 0.1.56.

**Comment by elgatito** [comment]
@Cyroq Should I close this?

**Comment by Cyroq** [comment]
Yes, you can close it. I ended up using a different approach by hitting the share button on magnet links and share it with Yatse.
