### ISSUE TITLE
Crash during update lead to re-checking of random torrent

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/plugin.video.elementum#555]
## Expected Behavior

maybe some graceful hadling of exit if possible

## Current Behavior

minor bug - Crash during update lead to re-checking of random torrent

## Steps to Reproduce (for bugs)

1. start kodi with old version of elementum and a lot of torrents (>100)
2. elementum takes time to load all torrents (~30s)
3. if update happens during this time - elementum crashes (see log)
4. after start it starts to re-check some torrent

## Your Environment

* Version used:
0.1.49

* Environment name and version:
spmc 17.6

* Operating System and version:

android tv 8
* Link to Kodi debug log:

https://paste.ubuntu.com/p/gvPXKDhKsc/

**Comment by elgatito** [comment]
@antonsoroko please, check with 0.1.50.
There is a check for closing libtorrent state.

**Comment by antonsoroko** [comment]
В идеале было бы проверить так же как коди останавливает плагин (там же сигналом) т как раз во время проверки торент файлов. Но на андроид ТВ это сделать сложно, так что я проверил как смог:
запуск коди, до того как елементум сказал что стартанул - выход
запуск коди, до того как елементум сказал что стартанул - стоп приложения через андроид меню
запуск коди, до сразу после того как елементум сказал что стартанул (по идее в этот моент идет проверка как я понимаю) - выход
запуск коди, до сразу после того как елементум сказал что стартанул - стоп приложения через андроид меню

вроде с такими тестами все ок. но опять же в идеале было бы "правильно" проверить на linux коробке.

Спасибо!

**Comment by antonsoroko** [comment]
снова словил эту ситуацию при обновлении
```
23:10:42.153 T:18446744072510957936  NOTICE: [plugin.video.elementum] terminating with uncaught exception of type libtorrent::libtorrent_exception: session is closing
23:10:42.154 T:18446744072510957936  NOTICE: [plugin.video.elementum] /buildbot/src/googleplex-android/ndk-release-r20/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:73: abort_message: assertion "terminating with uncaught exception of type libtorrent::libtorrent_exception: session is closing" failed
23:10:42.155 T:18446744072510957936  NOTICE: [plugin.video.elementum] SIGABRT: abort
23:10:42.156 T:18446744072510957936  NOTICE: [plugin.video.elementum] PC=0xe824dbf4 m=8 sigcode=4294967290
```
https://paste.ubuntu.com/p/zn9QTSqJVQ/

**Comment by elgatito** [comment]
@antonsoroko не отпрывается лог, там нужно видеть что было вокруг ошибки.

**Comment by antonsoroko** [comment]
@elgatito 
похоже удалили
перезалил https://paste.ubuntu.com/p/JFHK8Q7HDS/

спасибо

**Comment by elgatito** [comment]
@antonsoroko thx

```
23:10:14.698 T:18446744072510957936  NOTICE: [plugin.video.elementum] INFO  main         ГўВ–В¶ main             [0mVersion: 0.1.52 LibTorrent: 1.1.14.0 Go: go1.14.2, Threads: 4
```

С версии 0.1.53 уже ловятся ошибки С++, избегая падений.
По идее не должно такого быть после апдейта. 
Но надо следить. Обернуть абсолютно всё в перехваты надо слишком много времени.

**Comment by antonsoroko** [comment]
>С версии 0.1.53 уже ловятся ошибки С++, избегая падений.
Понял. У меня апдейт был с 0.1.52 до 0.1.55, так что буду надеятся что больше такого не словлю :-)
Спасибо.
