### ISSUE TITLE
"Download with elementum" does not work in tv progress and does not do background download

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/plugin.video.elementum#556]
## Current Behavior

i put it here since i am not sure how much this bug of context menu and how much of elementum plugin itself

in tv series "progress" context menu "download" start search without 0 in episode number e.g. s1e8
works fine in other sections but:
1) it does not download in background - acts like "play" (play after buffering)
2) wrongs text - still says "playing in elementum"

## Steps to Reproduce (for bugs)

1. open in tv series "progress" 
2. choose episode with 0 - e.g. s01e08
3. in context menu select "download with elementum" - you will get "nothing found"
4. check search history - it will show s1e8

## Your Environment

* Version used:
0.1.49
0.0.3

* Environment name and version:
spmc 17.6

* Operating System and version:

android tv 8
* Link to Kodi debug log:

https://paste.ubuntu.com/p/kQdXH6wfPG/

**Comment by elgatito** [comment]
@antonsoroko please, check with 0.1.50.

context.elementum is taking information from Player's labels, if item is not played from Kodi library.

**Comment by antonsoroko** [comment]
>in tv series "progress" context menu "download" start search without 0 in episode number e.g. s1e8

fixed, thank you

i created separate bugs for context plugin:
https://github.com/elgatito/context.elementum/issues/6
https://github.com/elgatito/context.elementum/issues/5

thanks
