### ISSUE TITLE
No buffering window in 0.1.49

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/plugin.video.elementum#557]
## Expected Behavior

to see buffering window to understand if torrent is alive/slow and maybe you need to stop and choose other one

## Current Behavior

No buffering window in 0.1.49 

## Steps to Reproduce (for bugs)

1. start download in any trakt section - buffering window is not showing, kodi shows "waiting" and then start play (in web ui i can see buffering)
2. but if open the same torrent in torrents list - you will see buffering window

## Your Environment

* Version used:
0.1.49

* Environment name and version:
spmc 17.6

* Operating System and version:

android tv 8
* Link to Kodi debug log:

https://paste.ubuntu.com/p/gGKP4x8ZFk/

**Comment by frkos** [comment]
I have similar issues...
I understand the development is stopped,  so does anyone know how I can downgrade to previous version?
It was really stable for me

**Comment by elgatito** [comment]
@antonsoroko please, check with 0.1.50.

**Comment by frkos** [comment]
As for me, it fixed my issues. 
Thank you!

**Comment by antonsoroko** [comment]
Works good in trakt and in search.
Thank you!
