### ISSUE TITLE
Can't open season pack (added via search or trakt) in torrents list. "select file to play" does not work properly

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/plugin.video.elementum#558]
## Expected Behavior

season packs should open

## Current Behavior

can't open season pack (added via search or trakt)
"select file to play" does not work properly - starts to download random file in season

## Steps to Reproduce (for bugs)

1. try to open season pack in torrents list - you will see windows with files list but if you choose one - nothing happens
2. try to use "select file to play" - if i choose e01 it starts to download s08
3. then if i open (in usual way) torrent again - window with list appears , i choose e01 - but elementum starts e08
4. after that if i try to open again torrent - same behaviour like in step 1
5. then if in step 2 i choose different episode then different wrong episode starts to download and play
6. and so on

## Your Environment

* Version used:
0.1.49

* Environment name and version:
spmc 17.6

* Operating System and version:

android tv 8
* Link to Kodi debug log:

https://yadi.sk/d/vqMNb3yW2AsP1g

**Comment by elgatito** [comment]
@antonsoroko please, check with 0.1.50.

**Comment by antonsoroko** [comment]
>try to open season pack in torrents list - you will see windows with files list but if you choose one - nothing happens

this is fixed - thank you!

for issue with "select file to play" i created a separate issue - #560 
thanks
