### ISSUE TITLE
open season pack from torrent list open last played episode instead of list of files

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/plugin.video.elementum#559]
## Expected Behavior

not sure if this is a big or feature but i guess season packs should open list of files anyway (for convenience)
if it is not possible or hard to fix - then it is better to have #498 in place without fixing this bug.

btw "select file to play" works fine only for completely downloaded torrents, so can't be used as a workaround for all cases at the moment - #560 

## Current Behavior

open season pack from torrent list open last played episode instead of list of files

## Possible Solution

probably connected to change made here - https://github.com/elgatito/plugin.video.elementum/issues/498#issuecomment-567633466

## Steps to Reproduce (for bugs)

1. associate a torrent with a season via "select stream"
2. watch some episode (not the first)
3. open season pack in torrents list - it will open the same episode you watched instead of list of files
4. watch some other episode via trakt menus
5. open season pack in torrents list - it will open the same episode you watched in the previous step instead of list of files

## Your Environment

* Version used:
0.1.50

* Environment name and version:
spmc 17.6

* Operating System and version:

android tv 8
* Link to Kodi debug log:

https://paste.ubuntu.com/p/VN387Df5nv/

**Comment by elgatito** [comment]
It is not a bug. Every torrent is linked with movie/episode.
When you start playback from torrents' list - elementum tries to find file linked with the movie/episode.
The only way to avoid auto-selecting file is to select it manually from context menu, if that is not working - then it is a bug.

**Comment by antonsoroko** [comment]
>When you start playback from torrents' list - elementum tries to find file linked with the movie/episode.

that's why i thought...

i will close this issue.

>The only way to avoid auto-selecting file is to select it manually from context menu, if that is not working - then it is a bug.
yeah, there is small bug with this https://github.com/elgatito/plugin.video.elementum/issues/560

Thank you!
