### ISSUE TITLE
[Request] Force 'Add to library' operation

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#56]
Regarding to 'Add to library' operation:
Can you add an option for enable overwrite when items status returned as 'already in library'?
(For entire lists and also for single items)

The reason for that is because my library currently built by Quasar (but it could be also another addon), so for testing (for example) or just to make a parallel library folders, when I want to add an item or entire list in Elementum to his Library folders, some of them are recognized as 'already in library' (Because it was added before to kodi library by the other addon), and doesn't add them to the Elementum library folder.
A Force Add To Library option (Or just do not check if already in library) and overwrite folders if needed, could be helpful here.

Thanks.

**Comment by elgatito** [comment]
Context menu rewritten.
When item is added to the library - option "Merge in library" is shown. It is forcing to re-add the item.
