### ISSUE TITLE
"select file to play" does not work properly for not fully downloaded season pack - starts to download random file in season

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/plugin.video.elementum#560]
## Expected Behavior

season packs should open

## Current Behavior

"select file to play" does not work properly for not fully downloaded season pack - starts to download random file in season
## Steps to Reproduce (for bugs)

1.  try to open not fully downloaded season pack in torrents list via "select file to play" - if i choose e01 it starts to open/download e16 (in first log; in second log for different torrent e01 opens e08)

## Your Environment

* Version used:
0.1.50

* Environment name and version:
spmc 17.6

* Operating System and version:

android tv 8
* Link to Kodi debug log:

https://paste.ubuntu.com/p/jcnk8JVHHj/
https://yadi.sk/d/vqMNb3yW2AsP1g

**Comment by elgatito** [comment]
@antonsoroko please, try with 0.1.51.

**Comment by antonsoroko** [comment]
Seems to be fixed. Thank you!
