### ISSUE TITLE
Elementum crashes on startup on older Mac's with pre-AVX chips

### ISSUE THREAD

**Issue by hellobe2121** [elgatito/plugin.video.elementum#562]
## Current Behavior
Elementum crashes on startup ("Elementum has crashed") and after a few times it stops trying to start. Elementum is thus not usable.

In the logs, you can see the following lines:
`2020-03-24 16:21:59.942 T:123145351823360  NOTICE: [plugin.video.elementum] SIGILL: illegal instruction`

`2020-03-24 16:21:59.943 T:123145351823360  NOTICE: [plugin.video.elementum] PC=0x406a560 m=0 sigcode=1`

I have tried reinstalling, removing settings, but that does not help. Latest version that does work: version 0.1.47

## Possible Solution
According to me, this happens because the Elementum daemon is compiled using Go. Go has a bug in version 1.14 that causes errors on darwin64 systems with pre-AVX chips, see https://github.com/golang/go/issues/37459 and https://github.com/golang/go/issues/37478

This has been solved in Go version 1.14.1

I think the problem will be solved if recompiled with latest Go version.

## Your Environment

* Version used:
Elementum 0.1.48, 0.1.49 & 0.1.50

* Environment name and version:
Kodi 18.6 on iMac 11,3

* Operating System and version:
Mac OS X 10.13.6
* Link to Kodi debug log:
http://paste.kodi.tv/xagodiqaxi.kodi

**Comment by elgatito** [comment]
@hellobe2121 you can try 0.1.51, it uses golang 1.14.2
