### ISSUE TITLE
An offer to complete elementum's translation to greek

### ISSUE THREAD

**Issue by pitsi** [elgatito/plugin.video.elementum#563]
## Expected Behavior
It would be nice if all of elementum's menus etc were in the same language...

## Current Behavior
... but they are not. Although I am not one of those users who expect everything to be translated in their own language, I get some sort of ocd when I see things that are half greek and half english :D 

## Possible Solution
I offer to translate what is not in greek. Just point me to the right file.

## Steps to Reproduce (for bugs)
Do NOT do the following steps if you can't read greek! I won't help you switch back to your locale :P 
1. Change your kodi's locale to greek. Settings > interface > regional > language > greek.
2. Exit to main menu and then go to the video addons and launch elementum.
3. Notice that some of its menu entries are in greek, e.g. for movies, series etc, while some others remain in english, e.g. torrents history.
4. Go to elementum's setting to see more inconsistency.

## Context
Hmm... I think it will also help other greek users who are bad at english.

## Your Environment
* Version used: 0.1.50
* Environment name and version: Kodi 18.6
* Operating System and version: Debian testing x64, libreelec 9.2.1 x64 and libreelec 9.2.1 armv7 (rpi3b+)
* Link to Kodi debug log: Not needed.

**Comment by elgatito** [comment]
@pitsi you can make the change and create a pull request to include it in the next version.
Example can be found here: https://github.com/elgatito/plugin.video.elementum/pull/541
That is the preferred way.

But you can even open translation and fill in empty/wrong translations and attach it to this issue.
https://github.com/elgatito/plugin.video.elementum/blob/master/resources/language/Greek/strings.po

**Comment by pitsi** [comment]
Because all of these seem... ~~greek~~ difficult to me, will you mind if I upload everything I do on pastebin and then have someone else do the commits etc?

**Comment by elgatito** [comment]
@pitsi that is also fine.

**Comment by pitsi** [comment]
Please help.
What does the option "Limit rates after initial buffering only" actually do? I do not use it on my system and I understand it as "use all the available bandwidth until buffer fills up, then switch to the limits for down/up speeds". Am I right?

More will follow :(

**Comment by elgatito** [comment]
> I do not use it on my system and I understand it as "use all the available bandwidth until buffer fills up, then switch to the limits for down/up speeds". Am I right?

Yes, when buffering is done - speed limiter gets enabled.

> The same for ""Get updates for pre-releases". Does it mean pre-releases of movies/series or of elementum?

Yes.

> The word "libary" is translated as "movie library" sometimes and as "book library" a couple of times. I wanted to translate it to "collection". What shall I choose?

Up to you. I'd stick with the name that comes in Kodi for your language. Elementum library is the same meaning as Kodi library.

**Comment by pitsi** [comment]
So, after checking how kodi uses the word library in the greek translation... I am even more confused.
Here is a screenshot of settings > media > library with the locale set to english
![screenshot001](https://user-images.githubusercontent.com/5880037/77736053-54a55680-7014-11ea-9d9f-624b0e91c3c5.png)

And here is the same thing with the locale set to greek
![screenshot000](https://user-images.githubusercontent.com/5880037/77736094-6f77cb00-7014-11ea-8ead-1a463c81c3d2.png)

Kodi translates "library" to "συλλογή" (= collection) for the options seen on the text in grey letters, but it translates it to "βιβλιοθήκη" (= book library) as seen on the text with orange letters.
And the word "ταινιοθήκη" (= movie library) is not present anywhere :/
I think I will stick with "συλλογή", if you are ok with it.

**Comment by elgatito** [comment]
All the translations are made by people, so it call depends on you and other people.

As far as I see, the only translator for Greek language was @Filosofos in Quasar. So maybe he/she can help here.

**Comment by Filosofos** [comment]
I also think that you should use "συλλογή" on order to be more consistent.
If you need any help with the translations don't hesitate to contact me.

**Comment by pitsi** [comment]
Questiosn, questions :(

1) The word "binary" on line 431 remains untranstaled to greek. I suggest the usage of "εκτελεσιμο" (= executable), if you are ok with it.

2) On the same line, there is this bit "[CR] Required platform" and I do not know what cr means. Is it supposed to show the platform elementum's executable must be? If so, I will translate it to "απαιτουμενη πλατφορμα", which is the exact translation of "required platform", but what about [CR]? 

3) The options under the proxy settings (socks4, socks5, etc) will remain untranslated. But how do I translate the ones for username, password etc below them? Which lines are for those?

4) The same applies to the options for user agent spoofing (libtorrent, bittorrent, utorrent, deluge etc), they will remain unchanged.

5) Line 318  "Spoof user agent (highly inadvisable)" is translated to "μασκάρεμα του user agent (δεν προτεινεται)", which means "spoof user agent (not recommended)". 
The same applies to line 322 "Default advisable (acceptable)" is translated to "προεπιλογή (προτεινεται)", which means "default (suggested". Poor translations I know, thus I ask for some help here.

6) "Max upload rate" on line 49 has been changed from "μέγιστος ρυθμός μεταφόρτωσης (Upload)" to "μέγιστος ρυθμός αποστολής", which imho is the exact translation of "max upload rate". Are you ok with it?

7) What does "Enable tuned storage settings" do?

**Comment by elgatito** [comment]
> On the same line, there is this bit "[CR] Required platform" and I do not know what cr means. Is it supposed to show the platform elementum's executable must be? If so, I will translate it to "απαιτουμενη πλατφορμα", which is the exact translation of "required platform", but what about [CR]?

`[CR]` - means new line, Kodi does not wrap long sentences, you have to do it youself.

> The options under the proxy settings (socks4, socks5, etc) will remain untranslated. But how do I translate the ones for username, password etc below them? Which lines are for those?

When you enable option, you see the ones that are below. Technical words are better to leave "as is".

> What does "Enable tuned storage settings" do?

It is setting specific options for bittorrent client for maximizing disk write speed.

**Comment by pitsi** [comment]
> It is setting specific options for bittorrent client for maximizing disk write speed.

Is this the same as "pre-allocate the disk space" that regular torrent clients have?

**Comment by elgatito** [comment]
> Is this the same as "pre-allocate the disk space" that regular torrent clients have?


No, it's usually called "disk cache". In this case it is enabled and set to custom value, which is not configurable.

**Comment by antonsoroko** [comment]
@pitsi 
I think you you can paraphrase this to something like "Enable settings optimised for storage performance"

**Comment by pitsi** [comment]
Here I go again :(
1) Can someone simplify this for me "Initial buffering timeout (seconds)"?
2) The word "updates" in "Automatically re-scan Kodi library after updates" means the elementum's updates?
3) Where are the options for "Listen interfaces" and "Outgoing interfaces" inside elementum's settings?

**Comment by elgatito** [comment]
> Can someone simplify this for me: "Initial buffering timeout (seconds)"? Line 374.

It's the buffering which starts when you open something for playback.

> The word "updates" in "Automatically re-scan Kodi library after updates" means the elementum's updates?

Updates = changes to the library (something added or removed).

> Where are the options for "Listen interfaces" and "Outgoing interfaces" inside elementum's settings?
If you disable automatic selection - you can define options.

> The "Disable background progress dialog" option disables that overlay thing on the video that shows upload/download rate etc when pressing pause?

No. If you pause video and return to Kodi - you see progress in the upper corner, that is it.

**Comment by pitsi** [comment]
> If you disable automatic selection - you can define options.
Under which menu is that? I can't find it :(

**Comment by pitsi** [comment]
My list of non tranlated and poorly translated lines has started to pile up again, so please help me if you can.
1) Lines 353 (listen interfaces) and 387 (outgoing interfaces). 
I have no idea how to translate them, although I know what they mean. They refer to the network interface to be used for incoming and outgoing connections, right? But how do I explain all that in greek? Any ideas @Filosofos ?
2) Line 793 (reset clearences). 
What does this do?
3) Line 853 (watchlist added to library). 
I have no idea how to translate "watchlist"... Is it the list of stuff that was already watched?
4) Line 857 (collection added to library). 
"Library" translates to "συλλογη", for the reasons discussed above, and "collection" translates to "συλλογη" too, because that it its literal translation. So the greek translation is as bad as "collection added to collection"! 
5) Line 952 (error creating output pipe for 'unrar' command).
I know what it does, yet I fail to translate it to something that makes sense.
6) Line 1032 (force stream auto-selection from settings).
I assume it is used to auto-select the video stream from the torrent, so I translated it to "auto-select video file" and totally lost the "from settings" part.
7) Line 1060 (mmap file).
Is that something like the rest of the tech terms (proxy, socks, etc) that remain untranslated?

Thank you in advance.

**Comment by pitsi** [comment]
I just noticed that the language files were updated or changed for 0.1.51.
How can I keep the stuff I have already translated in the file and also "insert" the new, untranslated lines?

**Comment by elgatito** [comment]
@pitsi new items are added in the end as new additions.
You can finish what you have, I will update it.

**Comment by pitsi** [comment]
This is all I could do, translated up to line 1721. I do not know when and if I will be able to complete it in the future, so I post everything I have done until today. Sorry :(
[strings.txt](https://github.com/elgatito/plugin.video.elementum/files/4605390/strings.txt)

Rename strings.txt to strings.po.

**Comment by elgatito** [comment]
@pitsi I have included your changes in version 0.1.52. Thanks for you work.

**Comment by pitsi** [comment]
Thank you :)
I made the update a few minutes ago and I noticed that I have missed the entries in the main menu completely, so what I say on the 3rd step is still there :/ 
I promise to continue it when I have time and I will reopen the issue once I have made significant progress.

**Comment by pitsi** [comment]
Sorry for bringing this back up, but I want an urgent fix for a couple of bad translations I found yesterday

a) Line 1694 should say
`msgstr "Καταγραφη των αιτημάτων του εσωτερικού proxy"`
instead of that nonsense it says now. I forgot to switch the keyboard to the greek layout in the mid of the sentence.

b) Line 969 should say
`msgstr "Μετακίνηση ολοκληρωμένων"`
This is just bad translation, because I did not know where the message was used inside elementum, so I improvised... poorly.

Thank you in advance.

**Comment by pitsi** [comment]
Sorry for bringing this to the surface after 4+ years, but my eyes hurt when I see some on the translations I did, like the ones I mention above. What do I have to do? I will probably not complete the translation to 100%.

**Comment by antonsoroko** [comment]
@pitsi 
This is easy, you can do everything from your browser:
1. open https://github.com/elgatito/plugin.video.elementum/blob/master/resources/language/Greek/strings.po
2. Click edit (pencil icon)
3. Make changes
4. Click "Commit changes"  and it will create "pull request" than can be reviewed and merged by elgatito 


There is official guide https://docs.github.com/en/repositories/working-with-files/managing-files/editing-files#editing-files-in-another-users-repository

**Comment by pitsi** [comment]
It says I need to for the repo first :(

**Comment by antonsoroko** [comment]
@pitsi 
I guess you meant that it says that "fork"  must be created first, so do it. It is free :-)

**Comment by pitsi** [comment]
You have no idea how many times I pressed "fork" as a github noob and how many forked repos I deleted when I realised what I had done :D 

If I edit the file myself and upload it here like I did last time, will you do the dirty work for me?

**Comment by antonsoroko** [comment]
@pitsi it would make much more sense if you will do this by yourself. Then if you will notice that you need to change something else (like you noticed above) you can do this again without asking anybody.

Just click edit, agree to create fork (you must create fork, fork is kind of shallow copy of repository), make changes, click commit.

**Comment by antonsoroko** [comment]
@pitsi i tried to find a video guide for you, but there is no guide because this process is very simple and easy and straightforward. 

as i wrote above:
1. Open https://github.com/elgatito/plugin.video.elementum/blob/master/resources/language/Greek/strings.po
2. Click edit (pencil icon)
3. Agree to create fork (**it is a must**)
4. Make changes in file
4. Click "Commit changes" and it will create "pull request" than can be reviewed and merged by elgatito

**Comment by pitsi** [comment]
No offence, but I do not need a video or a guide to help me. I understand what you are saying and I did the steps up to the one which asked me to fork the repo. I hope I will do it in the weekend.

**Comment by pitsi** [comment]
I just completed my first attempt. I hope I did everything good enough :)

**Comment by antonsoroko** [comment]
@pitsi you still need to create a pull request (important: from your fork to this repo, not "local"  pull request).

**Comment by pitsi** [comment]
I hope I got it right.

**Comment by antonsoroko** [comment]
It looks ok. 

https://github.com/elgatito/plugin.video.elementum/pulls

**Comment by pitsi** [comment]
Now that my commit is merged to elementum, can I delete the cloned repo from my account? 
Sorry for sounding stupid, I am a complete noob with such stuff.

**Comment by elgatito** [comment]
> Now that my commit is merged to elementum, can I delete the cloned repo from my account? 
> Sorry for sounding stupid, I am a complete noob with such stuff.

Yes, you can remove the forked repository after your change is merged.
