### ISSUE TITLE
Elementum on Xiaomi Mi Box S does not show video after buffer.

### ISSUE THREAD

**Issue by daweasel27** [elgatito/plugin.video.elementum#564]
Hello

I have a Xiaomi Mi Box S with Kodi.

I can select the torrent, and then it buffers, but no video appears.

When I click again it displays resume from x time.

What it's wrong with this?

Log - http://paste.ubuntu.com/p/WvvHPYZR6Y/

If you need another log please ask

Thank you

**Comment by elgatito** [comment]
@daweasel27 this plugin is not supported.
I can only see that your Kodi have started elementum twice, don't know how and why.

**Comment by daweasel27** [comment]
> @daweasel27 this plugin is not supported.
> I can only see that your Kodi have started elementum twice, don't know how and why.

How can I provide better logs?

**Comment by elgatito** [comment]
@daweasel27 you already have the best log you could have.

**Comment by m4xc4v413r4** [comment]
Works fine here on the same device, so that part isn't part of the issue. If you can't find why elementum is starting twice (which is probably the same reason that's causing your problem) do a clean install.
