### ISSUE TITLE
Searching for subtitles provide wrong title

### ISSUE THREAD

**Issue by arthurvaverko-kaltura** [elgatito/plugin.video.elementum#568]
on AndroidTv X64

after choosing to play something (like a tv series episode) then openning the subtitles download dialog the filename provided to the search is `Siriesname%20s01e01`
the encoded space charecter is causing the subtitles to not be found and only a manual search will find them.

I have some python skills but never kodi related..
If you can help out and point me to the place that defines the file name for the player I could take a look and maybe provide a pull request myself...

**Comment by elgatito** [comment]
Hello.

What you see as a tile in subtitles window is not what is used for search by Elementum.
It is detected by Kodi based on url, that is played.
Elementum is using own logic for searching.
https://github.com/elgatito/elementum/blob/master/api/subtitles.go

**Comment by arthurvaverko** [comment]
Thanks understood .. but sometimes the built-int subtitles are not found and i want to search other providers .. 
the built-in subtitle search in kodi is using the player file name to search for subtitles using the installed providers (using add-ons) i was wondering what could change that file name ..

**Comment by elgatito** [comment]
@arthurvaverko Elementum is already changing the file name. More information is here: #196, #282, #318.

**Comment by elgatito** [comment]
Closing. Issues mentioned above - describe the same.
