### ISSUE TITLE
[BUG/Request] Background progress notification comes and goes

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#57]
## Expected Behavior
In Quasar the Background progress notification (dialog) shows each torrent progress and after all it shows the Total progress, and then cyclic back to show the torrent progress and so on.
(Notification shows up, torrent1 progress, torrent 2 progress, total progress, torrent1 progress, torrent 2 progress, total progress... and so on)
While all this time the notification is stay on screen.

## Current Behavior
In Elementum it behaves like this:
Notification shows up, torrent1 progress, torrent 2 progress, total progress, Notification goes away, Notification comes in again. It's annoying the notification comes and goes from the screen on each cycle. It should be stay on screen all the time.

## Your Environment
* Version used: 0.0.30
* Environment name and version: Kodi 17.6
* Skin: Titan
* Operating System and version: Windows 10 , 64 bit

**Comment by elgatito** [comment]
Should be better with 0.0.32

**Comment by burekas7** [comment]
I've checked, and it seems that you have fixed it. Thanks.
