### ISSUE TITLE
v1.50 - file storage mode no longer working, with latest release

### ISSUE THREAD

**Issue by splaquet** [elgatito/plugin.video.elementum#570]
## Expected Behavior
Program opens as usual

## Current Behavior
Continuous crashing, until limit reached. 

## Possible Solution
I tried to reset my download paths, but no change  

I switched to memory mode, but I can only watch <720dpi (under 1gb, for the most part)

## Steps to Reproduce (for bugs)
1. Upgrade to Elementum v1.5
2. Open Elementum
3. Continue to see “Elementum has crashed. Restarting”
4. After several of those, it stops trying

## Context
Since the upgrade, app simply continues to crash. Seems unrelated, but I can no longer pull large torrents using memory storage

## Your Environment
v1.50
Kodi v17 [Krypton]) 
Nvidia Shield w/ Android tvOS 

* Link to Kodi debug log:
I did not think to generate (or look into) my log. I’m out walking at the moment. I’ll submit tonight.

**Comment by elgatito** [comment]
@splaquet noone can help you without log file.

**Comment by splaquet** [comment]
so... i was using tail on the log (not sure why i hadn't thought about that at first), and saw a few items that looked interesting.  

most interestingly, it looked as though elementum was calling the skin helper plugin, but didnt have the plugin location set. i might be incorrect there... but either way, i disabled them all and removed what i could.

i uninstalled all of the Elementum components (video, context, burst, repo), also removed all settings, and reinstalled.  

when i installed everything (elementum) again, it worked.  i probably didnt have to remove elementum, but i wanted to wipe any of my configs.

attached is the error log.
[kodi.log](https://github.com/elgatito/plugin.video.elementum/files/4498227/kodi.log)

**Comment by elgatito** [comment]
@splaquet when you create an issue, there is information how to get log file properly.
http://elementum.surge.sh/contribute/log/#easy-one

**Comment by splaquet** [comment]
My apologies. I’m honestly not even sure if this sums up the error still... but I haven’t turned on the error log since, so hopefully this has the content. 

http://paste.kodi.tv/orajuberek

**Comment by elgatito** [comment]
@splaquet have you opened the link? it does not contain log.

**Comment by splaquet** [comment]
I clicked on upload Elementum log to pastebin. That was the URL I received back. Embarrassingly, I’m an experienced user... just distracted lately. 

So, I ended up finding my real problem. I had installed a wizard that modified my advanced_settings. The cache buffer was set incorrectly. After erasing the custom content, everything is working as expected. 

After seeing your .51 update, it looks as though you can play with this from within Elementum now.  Awesome!

Thank you for your patience, and my apologies for my noob moves.
