### ISSUE TITLE
[Request] Option for "Clear Search History"

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#575]
Hi,

'Search' Torrent:
Currently there is only one option of "Remove from history" when you open the context menu on an item in the History list.

Can you please add a new option in the search history list also for "Clear All Search History"? 
So it will be possible to remove all the history items at once instead of doing it one by one.
* I think it will be better to put this as additinal item and not in the context menu.
--- New Search
--- Clear search history

Thanks.

**Comment by elgatito** [comment]
@burekas7 option added in 0.1.52.

**Comment by burekas7** [comment]
Thanks.
I'm getting "Internal Server Error" when pressing on the "Clean All"

Kodi debug log: 
https://paste.ubuntu.com/p/KYXqMRmvbb

Elementum 0.1.52

**Comment by elgatito** [comment]
@burekas7 were queries removed? or have an error and they remain in the list?

**Comment by burekas7** [comment]
Error + Still remain in the list, nothing happen after that.

**Comment by elgatito** [comment]
That is a bug in database library. You can try with 0.1.53, maybe it will help.

**Comment by burekas7** [comment]
Thanks @elgatito 
It's working with 0.1.53
