### ISSUE TITLE
looks like elementum is still starting up

### ISSUE THREAD

**Issue by Ghaleb-alnakhlani** [elgatito/plugin.video.elementum#577]
## Expected Behavior

It should open the Elementum addon 
## Current Behavior

When i click on the addon i get this message "looks like elementum is still starting up" 
## Possible Solution

I have tried almost all possible solutions.
Reinstalled Kodi twice.
Installed the previous version of Elementum and the latest one.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

I have tried almost everything reinstalling Kodi but still unable to start Kodi I get this message whenever i try to open it.
## Your Environment

* Version used: Ubuntu 20.04

* Environment name and version: 0.1.51
 
* Operating System and version: Ubuntu 20.04 Kodi leia 18.6

* Link to Kodi debug log: Unable to provide log because whenever i try to get the log i get the same message

**Comment by elgatito** [comment]
Read the page and get the log file manually.
http://elementum.surge.sh/contribute/log/

**Comment by Ghaleb-alnakhlani** [comment]
I don`t know what happened it is working now. I was able to install it without any problem.
I guess I am going to close this now.
