### ISSUE TITLE
[Issue] Liked list from Trakt showing up as Empty List in "My Lists"

### ISSUE THREAD

**Issue by JacopoV** [elgatito/plugin.video.elementum#578]
## Expected Behavior
Opening a list from "My List", if previously liked on Trakt, should show the content.
Feature i'm referring to : https://github.com/elgatito/plugin.video.elementum/issues/336 

## Current Behavior
By liking a list in Trakt, it normally shows up in "My List", but by clicking on it, it shows an empty list.

## Steps to Reproduce (for bugs)

1. Like a list in Trakt
2. Check that correctly shows up in "My List"
3. Click on the list you liked
4. Check the list is empty (but it's not on Trakt website)

## Your Environment

* Version used: last one 

* Environment name and version: Kodi 18 

* Operating System and version: Android TV 9

* Link to Kodi debug log:

Thanks :)

**Comment by JacopoV** [comment]
Update : so the list i m trying to get into is this one : https://trakt.tv/users/aclo_networks/lists/tv-shows-netflix-heart-heart-heart

I noticed that 's actually listen in the popular one, but it results empty.
So i tried with another one with way less entries and it's working (https://trakt.tv/users/movistapp/lists/walt-disney-animated-feature-films?sort=rank,asc).

So i think that's due the amount of entries :( even trakt seems taking it's own time to list it.

**Comment by elgatito** [comment]
@JacopoV you should add a log file, showing what happened there.

**Comment by JacopoV** [comment]
@elgatito can you please guide me how to retrieve the log for you? I m running on Android TV. If you can't, just maybe a Elementum menu section i can look into and see where it saves the log :) many thanks !

**Comment by elgatito** [comment]
@JacopoV http://elementum.surge.sh/contribute/log/#easy-one

**Comment by JacopoV** [comment]
@elgatito Thanks a lot for the quick support. Here's the log : http://paste.kodi.tv/onahadojit
