### ISSUE TITLE
Searches randomly yielding no results, unicode error

### ISSUE THREAD

**Issue by hitmancho** [elgatito/plugin.video.elementum#579]
I know there isn't any support for this anymore, but I have been getting this error recently, running Kodi 18.6 and latest Elementum. Basically, very random word searches or show / movie searches using their respective categories give me an ASCII error and display no results. If I decide to do a manual search, all is good BUT only if I remove some letters (have not found any pattern). It does not work if I search for "show s01" or anything like that, for example.

I attached a full log, notice the very bottom and the errors there. It seems to be happening because of some of the .py files and it has to do with not being able to encode some characters. I cannot recall this happening before, months ago. My Kodi is in English using the Default character set. I am only using Cyrillic for my Player, so I can get subtitles for some shows in my language on occasion. Anyone encounter such and error?

[bundle_2020_5_10_11_0.log.txt](https://github.com/elgatito/plugin.video.elementum/files/4605539/bundle_2020_5_10_11_0.log.txt)

**Comment by elgatito** [comment]
@hitmancho this is a bug in Burst. Will be fixed in the next version of it.

**Comment by qaron84** [comment]
for for me.. disable limetorrents and it works fine!!

**Comment by RobP-git** [comment]
I am still getting this error, any chance of getting a fix soon?

**Comment by elgatito** [comment]
@RobP-git @qaron84 @hitmancho still an issue with the latest Burst/Elementum?

**Comment by hitmancho** [comment]
> 
> 
> @RobP-git @qaron84 @hitmancho still an issue with the latest Burst/Elementum?

Seems to be working fine for me. Tested it again by searching for "rome s01" in Search and it finds torrents no problems. Not had a chance to test if other names and strings could be a problem, but I do no think so.

Only text-related issues I have been seeing is shows with special characters (e.g. 90 day fiance with a diacritic on "e") being scraped from the Shows tab with that letter and getting zero results. Otherwise, searching manually from the Search tab is yielding all relevant torrents. Let me know if you need any further files from my side.

**Comment by elgatito** [comment]
@hitmancho in case you meet this bug again - feel free to raise an issue.

> Only text-related issues I have been seeing is shows with special characters (e.g. 90 day fiance with a diacritic on "e") being scraped from the Shows tab with that letter and getting zero results.

Sadly, that is how trackers search such cases, some treat "ę", "é" and "e" as same chars. Some need to have specific "e" char, some just don't find other than simple "e".

**Comment by RobP-git** [comment]
Yes also working for me now, thanks!

**Comment by RobP-git** [comment]
> @RobP-git @qaron84 @hitmancho still an issue with the latest Burst/Elementum?

Yes also working for me, thanks!
