### ISSUE TITLE
[BUG/MALFUNCTION] Shows added to library are not listed in library

### ISSUE THREAD

**Issue by unster** [elgatito/plugin.video.elementum#58]
Hi,
this is my second try with elementum - I started with version .24 and same issue, right now I've tested with .31 and problem still occurs.

I am not attaching logs as I don't know what logs does developer needs - I will of course add them later as I get more requirements.

**Brief description:** I've added 2 shows to the library, both times I was asked by elementum to rescan my library and it did so. No new shows discovered and they weren't added to library. I have set up rescanning library every time I restart my Kodi and it was already restarted several times last few weeks. Shows are still not "discovered". What is interesting, there was a folder created for each show in my elementum's library folder and in each folder there are strm files in correct number (newest episodes included). 

**Repro steps: (not fancy really)**
1. Open elementum plugin
2. Go to search & search for any show
3. Open context menu on found show and click on "Add to library"
4. Elementum is asking to rescan library - agree on that
5. Wait for elementum to finish scanning
6. Go to library - new show isn't present (FIRST ATTEMPT)
7. Restart Kodi & let it rescan library again
8. Go to library - new show still insn't present (SECOND ATTEMPT)

## Your Environment
* Version used: .24 & .31
* Environment name and version: linux_arm64
* Operating System and version: LibreELEC (Krypton) 8.2.2
* Device: Odroid-C2
* Additional info: I have last Quasar & Quasar-Burst still installed as I am using them till I solve this issue (working for already added shows - months ago)
* Link to Kodi debug log: to be uploaded if requested

**Comment by elgatito** [comment]
> No new shows discovered and they weren't added to library. I have set up rescanning library every time I restart my Kodi and it was already restarted several times last few weeks. Shows are still not "discovered". What is interesting, there was a folder created for each show in my elementum's library folder and in each folder there are strm files in correct number (newest episodes included).

You select a directory for Library, then Elementum is creating there directories for each show/movie, and episodes/movies inside each directory. 
So basically you will have two directories: %LIBRARY/Movies and %LIBRARY/Shows, then you have to find them in Kodi and set up scraper for each of them (I'd advise TheMovieDB or Universal scrapers, they both available from Kodi default repository).
Only after that Kodi will try to import created directories.

**Comment by unster** [comment]
Silly me! You are right, working like charm! :) We can close it.
