### ISSUE TITLE
Proxy request from Elementum to Jackett and just return result to Elementum ?

### ISSUE THREAD

**Issue by chicungunya** [elgatito/plugin.video.elementum#580]
Hello @elgatito , @hoshsadiq
I want to proxy request from Elementum to Jackett and just return result to Elementum.
I need Jackett as indexers of Elementum, is that possible ?

What do I have to put in Elementum here : https://imgur.com/a/C4qw9G4 (http://192.168.1.3:65220/web/)
And here in Jackett : https://imgur.com/rbC1FDb (http://192.168.1.12:9117/UI/Dashboard)

Do I have to put same information in Burst too ? 

Thanks a lot !

**Comment by elgatito** [comment]
@chicungunya  I was talking about proxy as a development design, not as http proxy in some application.
You need a separate addon which will receive request from Elementum and send it to Jackett. There is nothing to do from Elementum.

**Comment by chicungunya** [comment]
Maybe there is a way to add Jackett as a custom provider in Burst?

**Comment by elgatito** [comment]
@chicungunya there is no such way. There is nothing to do for Burst.
