### ISSUE TITLE
play specific torrent item

### ISSUE THREAD

**Issue by thomasgm** [elgatito/plugin.video.elementum#582]
hello, it would be cool if there is a way to play a specific item when torrent has many files
like
plugin://elementum/magnet=uri&item=2

so this will play item 2 on magnet link automatically instead of wait for user to choose from the pullup menu that is showed.

**Comment by elgatito** [comment]
@thomasgm 
`&index=N` is already available.

**Comment by elgatito** [comment]
https://github.com/elgatito/elementum/blob/master/api/play.go#L31

**Comment by elgatito** [comment]
@thomasgm 
In 0.1.52 and later you can use `oindex=N` parameter to use file index, as it is in the torrent file.
