### ISSUE TITLE
magnet does not show all episodies

### ISSUE THREAD

**Issue by thomasgm** [elgatito/plugin.video.elementum#584]
any reason why torrents like this does not show all episodies?
magnet:?xt=urn:btih:9385f6a8f4f5f129f36ea7f2c28485c8abebb294

**Comment by elgatito** [comment]
@thomasgm 
I have no idea. Files are filtered by size only.

**Comment by antonsoroko** [comment]
if my search is right then this torrent is `http://www.torlock.cc/ixitch/9385f6a8f4f5f129f36ea7f2c28485c8abebb294` 
so i can see than files names are not following any name convention (e.g. s01e01 or 1x1)

**Comment by elgatito** [comment]
I will close this issue. 
No log, no description, nothing.

**Comment by antonsoroko** [comment]
i think the problem was because of the torrent. It has files like `06 - VIATORRENTS.COM .avi`, not sure if elementum has `NN` pattern for searching episodes. And IMHO it is bad naming convention.
