### ISSUE TITLE
[Request] Web page should show total size of selected files, not full torrent size

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#585]
The bug:
Torrent keeps the downloading even when a specific episode was already finished (When it was chosen from a season torrent).

1. Search for an episdoe (For example: Vikings S03E04)
2. Select a Season torrent result (For example:  Vikings.S03.1080p.AMZN.WEBRip.DDP5.1.x265-SiGMA[rartv])
3. Check for time to time the actuall size to verify when the episode is finised its download.
4. Check the web page / notification / torrent list to see the progress and downloading status.

Some images:
3.
![image](https://user-images.githubusercontent.com/13424257/82382476-b42c4b00-9a34-11ea-9354-7b42b55f7241.png)

4) It seems that the percentage is calculate by the size of entire season (29GB) and not by the episode size, and also still downloading even when the specific episode was already downloaded.

![image](https://user-images.githubusercontent.com/13424257/82381725-5fd49b80-9a33-11ea-99f9-a42453577b47.png)

![image](https://user-images.githubusercontent.com/13424257/82381799-7975e300-9a33-11ea-91aa-dee2b95d1e08.png)

Kodi Log:
https://paste.ubuntu.com/p/zZZqyPSZHB

Question:
* Does it download the entire season torrent even if it choose only a specific episode from it?

Request:
* In the web page: Show the details (Name, Size, Progress) regarding the specific episode progress and not the entire season as shown in the image.

---
Elementum 0.1.51
Kodi 17.6
Win 10 / 64bit

**Comment by antonsoroko** [comment]
yeah, i have the same from time to time.

**Comment by burekas7** [comment]
When I stop the playback and tried to play it again I got the "Internal Server Error" notification.
After restarting Kodi it suddenly show it as 100% . Seems that maybe something goes wrong on this case.

**Comment by elgatito** [comment]
If you open a season torrent, by default Elementum is starting download of next episode when download of current file is complete. 
You can disable it in the settings.

**Comment by antonsoroko** [comment]
I have this option disabled in settings, but anyway sometimes i get this behaviour.
When i check directory with files - no new files in it.
It looks like elementum downloads something extra into nowhere.

**Comment by burekas7** [comment]
@elgatito 
As @antonsoroko said, the setting of "Automatically start downloading next episode" is off.
And there is no other files that were downloaded, there is only the wanted episode.
And it never start a new episode, this behaviour happens with a episode from season torrent.

**Comment by elgatito** [comment]
Download progress is returned by libtorrent, without any modifications, for file storage.

**Comment by elgatito** [comment]
@burekas7 Please, try with Elementum 0.1.56. 
@antonsoroko 

There were lot of places with wrong file/piece management. I have reorganized that. But, probably, it will need to re-add the torrent to start counting properly.

**Comment by elgatito** [comment]
@burekas7 
Please, try with v0.1.63.
Web page now showing selected files' size.

**Comment by burekas7** [comment]
Yes, the web page shows the episode size and not the season.

BTW, Is it possible to show the relevant episode size from a season torrent also in the results window?
Now it shows the season torrent size.

**Comment by elgatito** [comment]
@burekas7 you mean the window when you select the torrent?
There we don't even know the real size of a torrent, if that is a magnet, we show what we get from websites. 
And we don't have list of files if that is a magnet.

**Comment by burekas7** [comment]
Yes.
Understood.

Thanks.
