### ISSUE TITLE
does not work on kodi 16

### ISSUE THREAD

**Issue by veniciusgp** [elgatito/plugin.video.elementum#586]
It stopped working on kodi 16.1 since version 0.1.46

**Comment by elgatito** [comment]
@veniciusgp you give no description. you give no information, you give no log.

**Comment by veniciusgp** [comment]
I will attach the logs.

But the problem is that elementum simply does not start on kodi 16 in version 0.1.46 or higher. Log error occurs.

This happens on kodi 16 + elementum android_arm

The test was done on android 5.1 I don't know if it occurs with other OS

**Comment by antonsoroko** [comment]
@veniciusgp Hi. You can imagine that author use different environment than you, and this is not an enterprise product to have a QA team with different HW and OS'es, so author expect that community will provide not only description of a bug, but also a tech info like logs. I hope you understand. Thanks.

**Comment by veniciusgp** [comment]
@elgatito 
The Log that was missing

Kodi.log 
paste.ubuntu.com/p/dnrQk6sJ3j/

**Comment by elgatito** [comment]
@veniciusgp try with 0.1.55. 
Kodi 16 have very old python which causes errors.

**Comment by veniciusgp** [comment]
@elgatito 
The problem persists even in version 0.1.55

https://pastebin.ubuntu.com/p/knYC4zpJ2p/

The kodi 16 python is really old but my tv box uses kodi 16 with a custom PVR and therefore I cannot update.

I don't think it's worth it to spend energy to fix this problem. I will go back to version 0.1.45 which already works very well.

Thank you very much for your attention

**Comment by elgatito** [comment]
@veniciusgp maybe it is not the big issue, but I don't have Kodi16 to test it, so it's not so easy.

**Comment by veniciusgp** [comment]
@elgatito 

Wouldn't it be possible to install kodi 16.1 in your test environment? I think the problem is reproducible on any version of kodi 16.1 (Android or Windows)

Regards

**Comment by elgatito** [comment]
To install old Kodi on Linux you need to remove all existing Kodis. 
Portable version works only on Windows.

**Comment by veniciusgp** [comment]
@elgatito 

Too bad it is not possible to install kodi 16.1 in your development environment. I will continue to use version 0.1.45 which is serving me very well.

thank you

**Comment by elgatito** [comment]
@veniciusgp I could not reproduce the issue with Kodi16.0 on windows. v0.1.55 launched well.

**Comment by veniciusgp** [comment]
@elgatito 

So it probably has something to do with the OS. In my example I use a tvbox android 5.1 + kodi 16.1.

Could this problem be happening due to a possible lack of dependence?

**Comment by elgatito** [comment]
@veniciusgp exactly that error was caused by Python syntax error. But to check possible fixes it is needed to run on problematic Kodi. So I cannot reproduce even with Kodi 16.0.

**Comment by veniciusgp** [comment]
@elgatito 
Could there be a difference between kodi 16.1 for android compared to kodi 16.1 for windows? Aren't they supposed to have the same version of Python?

**Comment by elgatito** [comment]
@veniciusgp it can, probably.

**Comment by elgatito** [comment]
@veniciusgp Please, try with Elementum 0.1.56.

**Comment by veniciusgp** [comment]
Hi @elgatito 

Python syntax error still occurs

https://paste.ubuntu.com/p/XYNVSjR23V/

**Comment by antonsoroko** [comment]
looks like this kodi uses python 2.6
so
https://stackoverflow.com/questions/21069668/alternative-to-dict-comprehension-prior-to-python-2-7

**Comment by veniciusgp** [comment]
@elgatito 

Yes. This version of kodi uses python 2.6

**Comment by antonsoroko** [comment]
and looks lie it is already fixed here https://github.com/elgatito/plugin.video.elementum/commit/44f7470725c27d7fd76433e675a1d1960a827d24

but no luck

**Comment by elgatito** [comment]
@antonsoroko it was not properly coded there. I will make another try. Thanks for helpful link.

**Comment by antonsoroko** [comment]
and iteritems does not exist in python3
so i think code that will work in all 3 pythons will be:
```mod_kwargs = dict((key, py2_encode(value))
                    for key, value in kwargs.items())```

**Comment by antonsoroko** [comment]
and iteritems does not exist in python3
so i think code that will work in all 3 pythons will be:
```
mod_kwargs = dict((key, py2_encode(value))
                    for key, value in kwargs.items())
```
works for python27 and python3 on my machine

@veniciusgp 
could you please edit 
`/storage/sdcard/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/resources/site-packages/kodi_six/utils.py` (line 60) and check?

**Comment by veniciusgp** [comment]
@antonsoroko 

I will make the modification according to your suggestion and post the results

**Comment by elgatito** [comment]
@veniciusgp 

Change in utils.py the whole function to this:
```
def encode_decode(func):
    """
    A decorator that encodes all unicode function arguments to UTF-8-encoded
    byte strings and decodes function str return value to unicode.

    This decorator is no-op in Python 3.

    :param func: wrapped function or a method
    :type func: types.FunctionType or types.MethodType
    :return: function wrapper
    :rtype: types.FunctionType
    """
    if PY2:
        def wrapper(*args, **kwargs):
            mod_args = tuple(py2_encode(item) for item in args)
            if PY2:
                mod_kwargs = dict((key, py2_encode(value))
                    for key, value in kwargs.iteritems())
            else:
                mod_kwargs = {key: py2_encode(value) for key, value
                          in kwargs.iteritems()}

            return py2_decode(func(*mod_args, **mod_kwargs),
                              errors='replace')
        wrapper.__name__ = 'wrapped_func_{0}'.format(func.__name__)
        return wrapper
    return func
```

**Comment by veniciusgp** [comment]
@elgatito 

I made the change to the utils.py file as suggested but there is still a syntax error

https://paste.ubuntu.com/p/mZCvdq2C9K/

**Comment by elgatito** [comment]
@veniciusgp It does not look like you have changed it.

Can you just replace the file (but change .txt to .py)?


[utils.txt](https://github.com/elgatito/plugin.video.elementum/files/4706142/utils.txt)

**Comment by veniciusgp** [comment]
@elgatito 

The utils.py file replaced but the error is the same

https://paste.ubuntu.com/p/Q2QgGJ63BK/

https://paste.ubuntu.com/p/h63Mzk2dJ4/

**Comment by elgatito** [comment]
@veniciusgp one more attempts then

[utils.txt](https://github.com/elgatito/plugin.video.elementum/files/4706187/utils.txt)

**Comment by veniciusgp** [comment]
@elgatito 
The file extension was changed from .txt to .py and was placed inside the \ Android \ data \ org.xbmc.kodi \ files \ .kodi \ addons \ plugin.video.elementum \ resources \ site-packages \ kodi_six folder

![image](https://user-images.githubusercontent.com/35663151/83335961-b4bfaf80-a286-11ea-94a8-3cc32f2146d4.png)

**Comment by elgatito** [comment]
@veniciusgp I mean I have uploaded new version of "utils.txt", there is a change in there.

**Comment by veniciusgp** [comment]
@elgatito 

Perfect
Now elementum has been activated in a wonderful way

https://paste.ubuntu.com/p/tcpq3jMVS6/

**Comment by elgatito** [comment]
@veniciusgp please, try to browse the plugin, launch something, so act different things to verify everything is fine.

**Comment by veniciusgp** [comment]
@elgatito 
I have browsed all the menus, changed settings, played movies and series and there was no problem. Everything went perfectly

**Comment by elgatito** [comment]
@antonsoroko can you check if this change works on Kodi19?

**Comment by antonsoroko** [comment]
@elgatito unfortunately i still use kodi 17.
but i guess we can ask people here #495
