### ISSUE TITLE
Elementum crash when video start

### ISSUE THREAD

**Issue by csmathon** [elgatito/plugin.video.elementum#587]
Hi Everyone,
Since last week Elementum is caching the video but then when it tries to start, it crashed.
Today I reinstalled from scratch (openelec on raspberry pi 3 b 1.2) but same issue.

The logs are https://paste.kodi.tv/elufafokan

Any idea?

**Comment by elgatito** [comment]
@csmathon 
Should be fixed with 0.1.55.
