### ISSUE TITLE
Increase magnet timeout maximum

### ISSUE THREAD

**Issue by chicungunya** [elgatito/plugin.video.elementum#591]
Hello @elgatito ,
Is that possible to increase the maximum of magnet time out please ? 180 is not enough if I use a SOCKS5 Proxy.
I tried to do it in settings.xml but when I reupload it in my sd card, Elementum put it automatically at 15s.
Thanks a lot !

**Comment by elgatito** [comment]
@chicungunya you need more than 180 seconds?

**Comment by chicungunya** [comment]
Yes :/

**Comment by chicungunya** [comment]
@
