### ISSUE TITLE
Playback resume doesn't work

### ISSUE THREAD

**Issue by iz8mbw** [elgatito/plugin.video.elementum#592]
If I put in play a movie torrent (for example a mkv file) and if I stop playback after a while, if I go in Torrent history and I put in play the same torrent, Elementum asks me to resume playback or start from begging but in any case the playback starts always from the beginning.
May be some my wrong config?
Where to enable again playback resume? 
Thank you @elgatito

**Comment by elgatito** [comment]
@iz8mbw without a log file noone can help you.

**Comment by iz8mbw** [comment]
Sure, will provide. So I expect you don't have this issue :-)

**Comment by iz8mbw** [comment]
Hi @elgatito Denis.
Here the Kodi log: https://privatebin.net/?84139ec5ebce7344#33HdZ86yZiWTGkgmuzZz96ggRTgjsyK4GUdgmRRrDqGS

What I did:

Opened Kodi
Opened Elementum
Went in Torrent History
Putted in Play a Torrent from history
Elementum asked me to Resume from 0:13:38
I selected Yes
Torrent starts to buffer but when in Play it started from beginning.

Than you.

**Comment by elgatito** [comment]
@iz8mbw you have disabled play resume setting in Elementum, so it is not forcing a seek.

**Comment by iz8mbw** [comment]
i'm being crazy, cannot find in Elementum where to set it....

**Comment by iz8mbw** [comment]
I found this in settings.xml `<setting` id="play_resume">false</setting>` and now I put it to"true". But cannot understand where this settings sis in the GUI.
