### ISSUE TITLE
Libraries info - Libtorrent and OpenSSL

### ISSUE THREAD

**Issue by iz8mbw** [elgatito/plugin.video.elementum#593]
Hi @elgatito Denis.
I don't know which libraries version for Libtorrent and OpenSSL Elementum is currently using.
It will be nice if Elementum will go to use Libtorrent version 1.2.7 and OpenSSL version 1.1.1g.
For example the latest version 1.2.7 of Libtorrent introduces enhancement for the UPnP and port forwarding for both local router/gateway and a VPN environment.
Thank you Denis if a Libraries upgrade can be implemented for Elementum.

Thanks.

**Comment by elgatito** [comment]
@iz8mbw Elementum is compiled on libtorrent-go docker images.
They are configured here: https://github.com/ElementumOrg/libtorrent-go

Each version change should compile fine on all existing platforms, on not the latest compilers (to be able to run on old systems).

I have no plans on migrating to libtorrent 1.2, it needs a lot of time.
Feel free to make changes and submit a PR.
