### ISSUE TITLE
Resume question

### ISSUE THREAD

**Issue by john3voltas** [elgatito/plugin.video.elementum#595]
Hi.
I'm watching a movie and I stop playing after 30 minutes into the movie.
Next day I pick the same movie and press play. Elementum asks me if I want to resume from 00h30m and I say yes.
So, Elementum starts caching the movie and when it starts playing it is showing 00h00m00s and it stands there (paused) for some good 30 seconds or so (caching again?) and only then it goes directly to 00h30m00s and starts playing from where I left.
Is this to be expected? Why does it need to work this way? Not ranting, just curious.
Thanks a lot.
Cheers

**Comment by elgatito** [comment]
@john3voltas yes, previously we were asking Kodi to seek to N minute right after player is started, but it was working only from time to time. Now we wait until player has duration of a video file, then seek is working 100%.

**Comment by john3voltas** [comment]
@elgatito 
Thanks a bunch for clearing that out for me.
Moving to closed.
