### ISSUE TITLE
Interact with elementum

### ISSUE THREAD

**Issue by SecT0uch** [elgatito/plugin.video.elementum#598]
Hi @elgatito,

Thanks for your work. I know Elementum is not maintained anymore, but I want to ask you how to interact programmatically with Elementum.

I want to create an issue or PR on [Kore](https://github.com/xbmc/Kore/). I would like to be able to use "Play with Kodi" for magnet links or `.torrent` http(s) links.

I would like to know how to "Add torrent" with:
* magnet links
* http(s) .torrent links

I checked the code but I can't find how to use `playuri` or `playtorrent`.
Is there any other way than a http POST form-data request (like the web UI) ?

For example for soundcloud you can use `plugin://plugin.audio.soundcloud/play/?url=`. See [PR](https://github.com/xbmc/Kore/pull/671/commits/1c2135647b6a102e8711423c7d57926486d9f9aa)

**Comment by elgatito** [comment]
Hello,

Elementum endpoints: https://github.com/elgatito/elementum/blob/master/api/routes.go#L26
Play endpoint: https://github.com/elgatito/elementum/blob/master/api/play.go#L29

**Comment by fuligjimmy** [comment]
where/how can i run these commands?

**Comment by elgatito** [comment]
@fuligjimmy make http requests to elementum http server.

**Comment by SecT0uch** [comment]
Thanks @elgatito `plugin://plugin.video.elementum/play?uri=` is what was looking for.

For reference: [Kore PR](https://github.com/xbmc/Kore/pull/752)
