### ISSUE TITLE
"Timed out" when i open my movie collection

### ISSUE THREAD

**Issue by Dustman71** [elgatito/plugin.video.elementum#599]
## Expected Behavior
When i go in movies -> my collection i hope a list of my added movies appears. In series it works perfectly for me

## Current Behavior
The screen stops and after a while I receive the elementum message telling me Timed out

## Possible Solution
Could it be something related to the requests made to the server?

## Steps to Reproduce (for bugs)
 i go in movies -> my collection 

* Version used:
0.1.58

* Environment name and version:
LibreELEC 9.2 Kodi 18.7.1

* Operating System and version:
LibreELEC 9.2

* Link to Kodi debug log:
https://pastebin.com/N7cSRRxi

**Comment by elgatito** [comment]
@Dustman71 you should upload full log and with debug mode enabled.
http://elementum.surge.sh/contribute/log/

**Comment by elgatito** [comment]
Closing without getting response.
