### ISSUE TITLE
Install?

### ISSUE THREAD

**Issue by markcwee** [elgatito/plugin.video.elementum#6]
Hello there, 
I would like to install this addon on Kodi 17.6, but addon crashes upon installing in Kodi, after 3 restarts installation aborts.
Looks like deamon doesn't start...

I'm using Kodi 17.6 on Minix neo x64 (Windows 10 x86). 
Any help would be appreciated. Cheers.

**Comment by elgatito** [comment]
Can you post the kodi.log?

**Comment by markcwee** [comment]
How to?
