### ISSUE TITLE
elementum 0.1.58 refuse to load after viewing home screen. Gives the "elementum is starting give it some time"

### ISSUE THREAD

**Issue by ThurahT** [elgatito/plugin.video.elementum#602]
Hi! First of all I want to give my thanks for still kind of maintaining elementum. It is the best kodi addon. And the only I use tbth. So, issue is pretty much covered in the title. Kodi starts normal and elementum loads. I can view every section normally. But as soon as I "back" all the way out to home screen and then tries to enter elementum again it gives the "elementum is starting up give it time". Waiting does not help. Restarting Kodi works. So, it is not a big deal in that sense.
Kodi is Krypton 17.1 on Linux dist. Devuan 2.1. That thumbnail it tries to load in the log does not exist.
[kodi.log](https://github.com/elgatito/plugin.video.elementum/files/4775687/kodi.log)

**Comment by abugamel** [comment]
Hi everyone
 same issue here 

Anyone can help? 
[kodi.log](https://github.com/elgatito/plugin.video.elementum/files/4777375/kodi.log)

**Comment by elgatito** [comment]
@ThurahT you still have this issue? You can try to re-install plugin from zip file.

**Comment by elgatito** [comment]
Closing without getting response.

**Comment by ThurahT** [comment]
Nope, you fixed it some releases back! Thanks for all your hard work!
