### ISSUE TITLE
Not opening correct movie

### ISSUE THREAD

**Issue by yakirp88** [elgatito/plugin.video.elementum#61]
When trying to play a movie, for example: "Dunkirk", or any other movie, it opens a list of torrents for other movies, lke "pirates of the caribean", "spiderman" etc.

I am using windows 10 with kodi 17.6, elementum version 0.0.32 burst version 0.0.10

**Comment by elgatito** [comment]
You should provide a kodi.log if you want any assistance.
http://kodi.wiki/view/Log_file/Easy

**Comment by yakirp88** [comment]
[http://paste.ubuntu.com/26425322/](url)

**Comment by yakirp88** [comment]
look at line 2219, I selected Dunkirk 374720 and I got on results pirates of the Caribbean and many else results none of them is Dunkirk.

**Comment by elgatito** [comment]
it's s bug with burst and specific provider, not the Elementum itself.

**Comment by yakirp88** [comment]
I am using quasar choosing the same movie with quasar burst, same providers and in quasar I get results and in elementum gets wrong results. so there is problem.
