### ISSUE TITLE
Internal server error trying to open Trakt list (with and without custom APIs)

### ISSUE THREAD

**Issue by dairefagan** [elgatito/plugin.video.elementum#614]
## Expected Behavior
_Elementum >> Shows >> Trakt >> My Lists should display my custom TV Show lists but instead I receive:

## Current Behavior

`Elemental Internal Server Error`

Note that Settings >> Trakt does display my username and the name of my userlists if I want to configure them for adding or removing.

## Steps to Reproduce (for bugs)
1. Input custom Trakt API client and secret, recheck and save
2. Authorise Trakt and save
3. Try to open a custom Trakt list through Elemental
4. Uninstall and repeat without custom Trakt API client and secret.

## Context
I am unable to browse my preferred content.

## Your Environment
* Version used: 0.1.58
* Environment name and version: Kodi 18.7
* Operating System and version: Ubuntu 18.04
* Link to Kodi debug [https://paste.kodi.tv/uvusenujiq](https://paste.kodi.tv/uvusenujiq)

**Comment by dairefagan** [comment]
@antonsoroko pointed out the following error which looks like a bug:

`runtime error: invalid memory address or nil pointer dereference`

**Comment by i6jm** [comment]
have same problem today .. any help or fix

**Comment by ShlomiD83** [comment]
I believe that the API was revoked.
got mine fixed using a private Trakt API.

**Comment by elgatito** [comment]
@dairefagan is there still a bug with 0.1.61?

**Comment by elgatito** [comment]
Closing without getting response.
