### ISSUE TITLE
[Request] Adjust episode matcher to match something-mores1e01

### ISSUE THREAD

**Issue by dairefagan** [elgatito/plugin.video.elementum#615]
## Expected Behaviour
I select an episode I want to watch, the best torrent available happens to be a pack, and Elementum automatically streams that episode.

## Current Behavior
I select an episode I want to watch, the best torrent available happens to be a pack, and Elementum prompts me to confirm the same episode again in the Files window.

## Possible Solution
I do not know why someone would want to be given the choice to play any episode when they have already selected a specific one but there is most likely a reason for this functionality, so to not break that perhaps there could be an option to 'automatically select file from pack'.

## Steps to Reproduce (for bugs)

As expected Behaviour.

## Context
Seamless streaming, reducing redundant selections.

## Your Environment

* Version used:
Elementum 0.1.58
* Environment name and version:
Leia 18.7
* Operating System and version:
Ubuntu 18.04.
* Link to Kodi debug log:
N/A.

**Comment by elgatito** [comment]
@dairefagan Elementum has automatic episode matching, but it works only if it can definitely select episode file.
https://github.com/elgatito/elementum/blob/master/bittorrent/player.go#L38

**Comment by dairefagan** [comment]
> @dairefagan Elementum has automatic episode matching, but it works only if it can definitely select episode file.
> https://github.com/elgatito/elementum/blob/master/bittorrent/player.go#L38

I have only been testing with Elementum for two days but I have been testing extensively with manual scraping and all packs I have selected prompt for confirmation of the file name. Is manually selection from a a pack something users should only have to do only very rarely?

Can you please explain what prevents automatic episode matching and if there is anything I can do to help Elementum get around this?

I should mention in case relevant I was initially trying to use Elementum through Gaia but as Elementum is my only source, it seems Elementum offers access to more sources, and as I have experienced a lot of issues with Gaia starting to play stream but then starting to download another torrent or prompting me repeatedly to select a file from another pack, I am moving towards just using Elementum.

**Comment by elgatito** [comment]
@dairefagan as I've said before, Elementum can match episode only when it knows which episode should be matched. 
If you search streams manually or from external plugins which do not send episode+season number - how Elementum can match anything?

**Comment by dairefagan** [comment]
> @dairefagan as I've said before, Elementum can match episode only when it knows which episode should be matched.
> If you search streams manually or from external plugins which do not send episode+season number - how Elementum can match anything?

I clean installed Kodi and the only external plugin I have installed now is TheMovieDB Helper. I have just tested a particular show with Elementum - not using TMDBHelper - and despite selecting the episode I am prompted to then choose the file from the pack. I thought perhaps I needed to add episode number to title but that has made no difference.

When generating the log when the Files window prompt appeared I just pressed backspace several times to exit out of Elementum and get back to my list of video addons.

Please see log here: [](http://paste.kodi.tv/umuzujapow)

**Comment by antonsoroko** [comment]
@dairefagan can you describe again how (step by step in menu) you choose torrent?
and also give example of files names in the torrent file.

**Comment by dairefagan** [comment]
> @dairefagan can you describe again how (step by step in menu) you choose torrent?
> and also give example of files names in the torrent file.

Sure. I cleared the torrent history in Elementum settings before doing this.

_Kodi >> Addons >> Video Addons >> Elementum >> TV Shows >> Search >> New Search >> <american horror story> >> American Horror Story >> Murder House >> 1x01 Pilot >> American.Horror.Story.S01.1080p.BluRay.x264-CLASSiC >>_ 

After selecting the torrent file the _Files S1E1_ window appear prompting me to choose a file from list like _cls-ahs01e01.mkv_

**Comment by elgatito** [comment]
`cls-ahs01e01.mkv`

This specific file will not match, because `s01` is not coming after non-alphanumeric char.

**Comment by dairefagan** [comment]
I understand. Unless it would cause other problems, could you please
implement matching for files in packs where the sXXeXX comes after an
alphanumeric character?

**Comment by elgatito** [comment]
@dairefagan matching modified to find the ones listed above.
Please, try with 0.1.63.
