### ISSUE TITLE
Memory and use files

### ISSUE THREAD

**Issue by nikos17m** [elgatito/plugin.video.elementum#616]
Hello 

This is the only way to get an answer about my concern

I looked online but I couldn’t find the answer 

I run Kodi from my android tv box,I transferred it to the sd card because I don’t want to ruin my emmc storage with all these write and read,if I choose memory it will write and read from the sd card?

I am asking because with the memory option I have smoother playback compared to use files that I know for sure that the files are being downloaded goes directly to my sd card and for that I am not sure if the memory option uses the sd card 

So what I am asking is if memory option is safe and uses the sd card.

Sorry for my bad English 

Let me know plz 
Stay safe 
Regards 
Nick

**Comment by elgatito** [comment]
@nikos17m Memory storage is using only RAM memory, internal memory or sd-card or any other storage **is not used**.

**Comment by nikos17m** [comment]
Thank you very much for the super fast answer 

Is safe for long term use?
Thanks again

**Comment by elgatito** [comment]
@nikos17m yes, it does not hurt you hardware or storages.
