### ISSUE TITLE
[BUG] Раздел Torrents не работает - сбой

### ISSUE THREAD

**Issue by Lontron** [elgatito/plugin.video.elementum#617]
Раздел Torrents не работает, когда я добавляю торрент из ip/web и открываю его, elementum дает автоматический сбой, независимо от выбранного торрента.

Log: http://paste.kodi.tv/opigipamic

**Comment by elgatito** [comment]
Нужен лог в режиме отладки. В логе ошибки нету.

**Comment by Lontron** [comment]
> Нужен лог в режиме отладки. В логе ошибки нету.

Эта проблема также есть в kodi 18/19, платформа не имеет значения, я тестировал ее на corelec и проблема тоже есть.

http://paste.kodi.tv/gupowuraci with kodi.log
http://paste.kodi.tv/jegekevefi debug only

**Comment by elgatito** [comment]
Надо вручную запустить 
C:\\Users\\IONCB~1\\AppData\\Roaming\\Kodi\\userdata\\ADDON_~1\\PLUGIN~1.ELE\\bin\\WINDOW~1\\ELEMEN~1.EXE
и сделать те же действия, потом показать что во время вылета пишет.

**Comment by Lontron** [comment]
> Надо вручную запустить
> `C:\\Users\\IONCB~1\\AppData\\Roaming\\Kodi\\userdata\\ADDON_~1\\PLUGIN~1.ELE\\bin\\WINDOW~1\\ELEMEN~1.EXE`
> и сделать те же действия, потом показать что во время вылета пишет.

сделал 

http://paste.kodi.tv/efamoxiyim

**Comment by elgatito** [comment]
@Lontron Это не то. 
Я имел ввиду:
- запустить коди
- убить в процессах `elementum.exe` (раза 3, он будет сам перезапускаться несколько раз)
- запустить вручную в консольке (`cmd`)  - `C:\\Users\\IONCB~1\\AppData\\Roaming\\Kodi\\userdata\\ADDON_~1\\PLUGIN~1.ELE\\bin\\WINDOW~1\\ELEMEN~1.EXE`
- Открыть то, что не открывалось.
- Скопировать что последнее было на экране в консоли перед вылетом.

Встроенный лог этого не показывает, потому что туда сообщения эти не доходят, потому надо из консоли запускать чтоб увидеть их.

**Comment by Lontron** [comment]
> @Lontron Это не то.
> Я имел ввиду:
> 
> * запустить коди
> * убить в процессах `elementum.exe` (раза 3, он будет сам перезапускаться несколько раз)
> * запустить вручную в консольке (`cmd`)  - `C:\\Users\\IONCB~1\\AppData\\Roaming\\Kodi\\userdata\\ADDON_~1\\PLUGIN~1.ELE\\bin\\WINDOW~1\\ELEMEN~1.EXE`
> * Открыть то, что не открывалось.
> * Скопировать что последнее было на экране в консоли перед вылетом.
> 
> Встроенный лог этого не показывает, потому что туда сообщения эти не доходят, потому надо из консоли запускать чтоб увидеть их.


https://paste.kodi.tv/tijujecete.kodi ?

**Comment by elgatito** [comment]
@Lontron Похоже на то, но судя по логу проигрывание запустилось и Коди начал показ.

**Comment by Lontron** [comment]
> @Lontron Похоже на то, но судя по логу проигрывание запустилось и Коди начал показ.

Включил фильм и автоматически элементум сбои, и в Kodi 18 то же самое.

**Comment by Lontron** [comment]
@elgatito
`NOTI  bittorrent   тЦ╢ logAlerts        state_changed_alert: Strelok.2019.1080p.AMZN.WEB-DL.ELEKTRI4KA.UNIONGANG.mkv: state changed to: downloading`

**Comment by elgatito** [comment]
@Lontron В логе я вижу что добавляется магнит, он находится, потом буфферизируется, потом включается проигрывание в Коди, оно включилось, и сразу лог заканчивается.

Закрывается проигрывание? Закрывается Elementum.exe? Что происходит после старта проигрывания?

**Comment by Lontron** [comment]
> @Lontron В логе я вижу что добавляется магнит, он находится, потом буфферизируется, потом включается проигрывание в Коди, оно включилось, и сразу лог заканчивается.
> 
> Закрывается проигрывание? Закрывается Elementum.exe? Что происходит после старта проигрывания?

Elementum.exe останавливается, и фильм останавливается после того как буфер заканчивается.

**Comment by elgatito** [comment]
@Lontron 
> Elementum.exe дает автоматический сбой останавливается

Закрывается в консоли приложение и самая последняя строка там эта?
> NOTI bittorrent тЦ╢ logAlerts state_changed_alert: Strelok.2019.1080p.AMZN.WEB-DL.ELEKTRI4KA.UNIONGANG.mkv: state changed to: downloading

Совсем ничего нету после?

**Comment by Lontron** [comment]
> @Lontron
> 
> > Elementum.exe дает автоматический сбой останавливается
> 
> Закрывается в консоли приложение и самая последняя строка там эта?
> 
> > NOTI bittorrent тЦ╢ logAlerts state_changed_alert: Strelok.2019.1080p.AMZN.WEB-DL.ELEKTRI4KA.UNIONGANG.mkv: state changed to: downloading
> 
> Совсем ничего нету после?


Я протестировал его еще несколько раз, последняя строка остается такой каждый раз.

**Comment by elgatito** [comment]
У себя тоже повторил. Там именно в таком порядке: добавить без проигрывания через веб, запустить просмотр - получаешь вылет из библиотеки торрента.

**Comment by Lontron** [comment]
> У себя тоже повторил. Там именно в таком порядке: добавить без проигрывания через веб, запустить просмотр - получаешь вылет из библиотеки торрента.

Да

**Comment by elgatito** [comment]
@Lontron Должно работать с версии 0.1.62.

**Comment by Lontron** [comment]
> @Lontron Должно работать с версии 0.1.62.

работает
