### ISSUE TITLE
Иногда Elementum Daemon не запускается.

### ISSUE THREAD

**Issue by Lontron** [elgatito/plugin.video.elementum#618]
Даже после того как я открою его и подожду 5 секунд пока он восстановится, он не запустится, 
или я остановлю службу и запускаю службу снова или после нескольких перезапусков Elementum восстанавливается.  

Я давно сталкиваюсь с проблемой, но после нескольких чистых переустановок, я понял что эта проблема не от меня.

Log: https://paste.kodi.tv/zipufepeje

**Comment by elgatito** [comment]
@Lontron ваши логи без режима отладки не несут никакой информации.

**Comment by Lontron** [comment]
@elgatito Я не могу сделать kodi.log из настроек elementum, если elementum не запускается.

**Comment by Lontron** [comment]
@elgatito показывает мне что через 5 секунд Elementum запускается и не запускается, как я уже говорил выше.

**Comment by elgatito** [comment]
@Lontron Режим отладки никак не связан с дополнением. При создании issue здесь указана инструкция как делать логи.

**Comment by Lontron** [comment]
@elgatito Да, я знаю, я делал это раньше, но ничего, я не могу создать log, потому что elementum dameon не работает, он говорит мне ждать 5 секунд чтобы начать, и ничего.  Только если я остановлю службу и запускаю службу снова или после нескольких перезапусков Elementum восстанавливается.

**Comment by elgatito** [comment]
@Lontron Режим отладки никак не связан с дополнением.

https://elementumorg.github.io/screenshots/log5.png

**Comment by Lontron** [comment]
> @Lontron Режим отладки никак не связан с дополнением.
> 
> https://elementumorg.github.io/screenshots/log5.png
http://ix.io/2teS Все в порядке?
Я не могу создать log из настроек elementum.

**Comment by Lontron** [comment]
> @Lontron Режим отладки никак не связан с дополнением.
> 
> https://elementumorg.github.io/screenshots/log5.png

http://paste.kodi.tv/unajuloral нормально?

**Comment by Lontron** [comment]
Не знаю как у других с автозагрузкой, но этот скрипт помог /storage/userdata/autoexec.py 👍:
Закрою эту тему по причине нахождения решения, может у кого-то все нормально запускается, но для тех у кого проблемы, этот скрипт решает эту проблему.

import xbmc
import time

time.sleep(10)

# disable and enable addon
jsonCmd = '{"jsonrpc":"2.0","id":1,"method":"Addons.SetAddonEnabled","params":{"addonid":"plugin.video.elementum","enabled":false}}'
jsonRv = xbmc.executeJSONRPC(jsonCmd)

time.sleep(1)

jsonCmd = '{"jsonrpc":"2.0","id":1,"method":"Addons.SetAddonEnabled","params":{"addonid":"plugin.video.elementum","enabled":true}}'
jsonRv = xbmc.executeJSONRPC(jsonCmd)
