### ISSUE TITLE
[Request] Option to assign local torrent file to Season, TV Show or a Movie

### ISSUE THREAD

**Issue by bibic123** [elgatito/plugin.video.elementum#619]
Hello,

I know @elgatito has stopped working on it. But maybe if someone knows how to code, and see this request...

It would be nice to have the ability to atribute a local torrent file to a TV show Season or a Movie.
I'm sure it would be quite easy to implement, we can already attribute one torrent file from fetched with burst to an entire season, and autosync to the episodes. And we can already of course add local torrents in general section, or via the web interface.

Sometimes burst don't find the correct torrent file, for the correct provider, with enough seed etc.. Especially with yggtorrent.

I'm currently using Torrent History to fetch my torrent file, but it's not very intuitive and pleasant. And it doesn't sync with Trakt.

Thanks.

**Comment by kavuraki** [comment]
Would be wonderful

**Comment by daviddia5** [comment]
I join the request

**Comment by bibic123** [comment]
@elgatito thanks :)

**Comment by daviddia5** [comment]
Thanks, but I can't get it to work for me. When I select "Assign torrent" It appears busy for a long time and shows "Not found".
Then it gives me the option to manually select from external storage and it gives me the error "could not ver torrent info"

I am doing something wrong?

**Comment by antonsoroko** [comment]
this is 2 parts feature: new version of context.elementum was released but new version of elementum also must be released (code of the elementum plugin already has this feature but was not released yet).

**Comment by antonsoroko** [comment]
also please note how it works: https://github.com/elgatito/context.elementum/pull/13#issue-615408894

**Comment by antonsoroko** [comment]
@daviddia5 try with 0.1.77
