### ISSUE TITLE
[BUG] Problem with providers timeout and the available streams dialog

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#62]
## Expected Behavior
When some providers got timeout, the available streams dialog should still appear and show the rest providers that is responding. On the first try and not on the second try (As described in the 'current behavior)

## Current Behavior
On the first try when some providers get timeout, it shows the 'playback fail' message.
Then on the second try, it also get timeout for the same providers but this time it continue (resolving & scrapping), and show the available stream dialog.

## Steps to Reproduce (for bugs)
1. Make sure you have a provider that si not responding so you be able to get Timeout for it.
2. Choose a Movie or something to try.
3. On the first time you should get the 'Playback fail' message and the 'available streams' dialog won't show up.
4. On the second, it will show up.

## Your Environment
* Version used: 0.0.32
* Environment name and version: Kodi 17.6
* Operating System and version: Win 10, 64bit
* Link to Kodi debug log:
https://pastebin.com/QdRvVPLk
https://pastebin.com/c0XbfmXD

**Comment by elgatito** [comment]
Should be better with 0.0.33

**Comment by burekas7** [comment]
@elgatito 

You fix the stuck in 0.0.34
But the original problem is still exist.
Only the second try it shows the available streams dialog, on the first time it show that there was timeout with 2 providers, show playback fails and return to the list without show the results dialog.

Log: https://pastebin.com/BCwUZ3ES

**Comment by burekas7** [comment]
Additional kodi log: https://paste.ubuntu.com/26530760
(idope timeout failed showing the results dialog for all the rest)

**Comment by elgatito** [comment]
This is a duplicate for #119 probably. Please, try with 0.0.46.

**Comment by elgatito** [comment]
Should be fixed. According to reports.
