### ISSUE TITLE
Elementum/Burst - Keeps crashing on Android TV

### ISSUE THREAD

**Issue by JacopoV** [elgatito/plugin.video.elementum#620]
Hi, 

since last night (Sept 5th) when i run Elementum + Burst on Android TV 9 on Philips TV TPM191E, Elementum keeps saying that's crashing on boot, and Burst says error 111 " URL Error Connection Refused" .

Force closing Kodi and rebooting the TV seems not sorting any effect. 
From the Log, it seems that all the refused connections are connected to Mulan, which is the first movie in the first widget. Don't know why it seems to crate a problem.

## Expected Behavior
Running normally as it used to.

## Current Behavior
Elementum crashes, maybe due Burst error 111 with Connection Refused.

## Steps to Reproduce (for bugs)

1. Lunch Kodi on Android TV 18.7 Leia
2. Let Elementum start loading
3. See the issue in the notification and content not really loaded 

## Context
I m using Aura with widgets, filled from tracktv. The issue prevents to load correctly the content.

## Your Environment
Android TV 9
* Version used:
0.1.57/0.1.58
* Environment name and version:
Kodi 18.7 Leia
* Operating System and version:
Android TV 9
* Link to Kodi debug log:
http://paste.kodi.tv/cizuxunuhu

**Comment by elgatito** [comment]
@JacopoV you need to make log with debug mode enabled in Kodi.

**Comment by JacopoV** [comment]
@elgatito oh, I apologize for it. I can't reproduce the bug anymore. In elementum > advanced I clear all databases and cache and it seems fine now. If I ll get this issue again, I ll be sure to send the correct log. =)

**Comment by elgatito** [comment]
Closing. As the issue looks fixed.
