### ISSUE TITLE
Browse for subtitle not working

### ISSUE THREAD

**Issue by Dimitris-Arch** [elgatito/plugin.video.elementum#622]
When the torrent file is from url or local file,browse for subtitle is working ok and the path starts at "var/media/driver"
But when using the burst provider the starting path is not a real path, it starting at plugin menu as" plugin://" and it is not browsable
At burst settings there is not subtitle section

**Comment by elgatito** [comment]
Burst/Elementum is not controlling subtitles search by other plugins.
This addon is not maintained.
