### ISSUE TITLE
Elementum is still starting up

### ISSUE THREAD

**Issue by john3voltas** [elgatito/plugin.video.elementum#623]
Kodi 18.8 (LibreELEC on RPi 3B+) with Elementum/Elementum Burst here.
This setup has been working fine for months.
Suddenly, yesterday I noticed Kodi was frozen. Couldn't do anything in it's UI.
Rebooted the Pi and noticed that the Addons' icons were taking a lot of time to show up although the UI had already started. Trying to use the UI I noticed it was frozen once again.
After some minutes I noticed a message rolling on the top/right corner of the screen stating that Elementum still hadn't started and that's when Kodi's UI became available once again and the addons' icons showed up and I could once again browse the UI.
Tried to open Elementum but it keeps saying "Elementum is still starting up".

It was working just fine the previous day. Any ideas?

**Comment by elgatito** [comment]
Nobody can help you without kodi log.

**Comment by john3voltas** [comment]
> Nobody can help you without kodi log.

Hi @elgatito .
Yes, I just couldn't attach a Kodi.log because I'm not at home at the moment.
I'll grab a log and paste it here (pastebin) as soon as I get home. I was just trying to understand if this was something that was happening on a wide scale or if it's only happening to me.
I'll drop by later this evening to paste the log.
Thanks in advance.
Cheers

**Comment by john3voltas** [comment]
Hi there.
Sorry that didn't make it home on time to paste the log yesterday...
Here it is a link: http://ix.io/2zxZ
Hope you can give me a hand with it because right now it seems to be hanging my Pi. And worse than that, I can't watch my favorite TV shows :-D
Thanks in advance.
Cheers

**Comment by elgatito** [comment]
Looks like the binary is broken on the disk. You can try to reinstall from zip file.

**Comment by john3voltas** [comment]
Jeez, I don't know how I didn't think of reinstalling it...
Even took the sd-card out and ran an fscheck on it because it sounded like it needed it from looking at the log.
Found a bad cluster on a vfat partition /dev/mmcblk0p7 "Cluster 4581 is unreadable.". But was it.
I'll reinstall and will let you know.
Cheers

**Comment by john3voltas** [comment]
@elgatito 
Nope, it didn't work.
- I removed all 4 addons (elementum, elementum-burst, elementum-helper and elementum repo)
- restarted my kodi box
- uploaded elementum all-in-one (https://github.com/elgatito/plugin.video.elementum/releases/download/v0.1.58/plugin.video.elementum-0.1.58.zip) from my computer to the kodi box
- installed the zip file with no apparent issues and left it there for ~5 minutes without doing anything else
- tried to run elementum but it said there was an i/o problem
- rebooted the box
- retried after ~10 minutes of having restarted but still says elementum is still starting.
I'll post a kodi.log as soon as possible because the box is not unresponsive (due to this issue) and it will stay like that for 10 minutes and I have to leave the house.
Will post a log as soon as I get home later today.
TIA
Cheers

**Comment by john3voltas** [comment]
@elgatito 
Okay, it recovered faster than I antecipated.
Here's the log after uninstalling, reinstalling and still experiencing the issue: [http://ix.io/2zAN](url) .
Cheers

**Comment by elgatito** [comment]
You can try to manually run the binary - /storage/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_armv7/elementum

**Comment by john3voltas** [comment]
> You can try to manually run the binary - /storage/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_armv7/elementum

You mean, running the binary from an ssh session? Because this box doesn't have a console where I would run such a cli command.

**Comment by elgatito** [comment]
```
pi3sala:~ # /storage/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_armv7/elementum
Bus error
```

What about running this one? - `/storage/.kodi/addons/plugin.video.elementum/resources/bin/linux_armv7/elementum`

You can also try to remove on the disk this file `/storage/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_armv7/elementum` and then restart the box.

It probably looks like a hardware error.

**Comment by john3voltas** [comment]
> ```
> pi3sala:~ # /storage/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_armv7/elementum
> Bus error
> ```
> 
> What about running this one? - `/storage/.kodi/addons/plugin.video.elementum/resources/bin/linux_armv7/elementum`
> 
I tried and got this back:
`pi3sala:~ # /storage/.kodi/addons/plugin.video.elementum/resources/bin/linux_armv7/elementum`
`-sh: /storage/.kodi/addons/plugin.video.elementum/resources/bin/linux_armv7/elementum: Permission denied`

> You can also try to remove on the disk this file `/storage/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_armv7/elementum` and then restart the box.
> 
This did it! This worked, after removing the file and restarting Kodi, the Pi came back up in less than 2 minutes and now Elementum is working just fine. It didn't even loose any settings even though I removed and reinstalled the addon.

Thanks a bunch for your help, @elgatito . :-D

> It probably looks like a hardware error.
>
Just to clarify, by hardware error, did you mean an sd-card hardware error? Or did you mean an raspberry pi hardware error? Because there seems to be some suspicious "unreadable cluster" thing going on in my box, right?

**Comment by elgatito** [comment]
> Just to clarify, by hardware error, did you mean an sd-card hardware error? Or did you mean an raspberry pi hardware error? Because there seems to be some suspicious "unreadable cluster" thing going on in my box, right?

Probably binary file was broken, maybe bad sector on sd-card, or something like that.

**Comment by john3voltas** [comment]
Thanks a lot, @elgatito 
You always help us even though you're no longer actively developing Elementum.
Stay cool and take care.
Cheers
