### ISSUE TITLE
Elementum Fanart not showing movie posters

### ISSUE THREAD

**Issue by JacopoV** [elgatito/plugin.video.elementum#628]
Hello,

i'm not entirely sure is an Elementum issue, but if i m not wrong in the settings it handles fan art for movies and shows.
Since 2 days it seems not able to download the art.

## Expected Behavior
Loading art from fanart successfully 

## Current Behavior
Not many are being loaded

## Steps to Reproduce (for bugs)
1. Load some movie pages
2. Notice art posters missing here and there

## Context
Not very user friendly without images.

## Your Environment

* Version used:
Lastest
* Environment name and version:
Kodi 18.7 Android TV
* Operating System and version:
Android TV, 9
* Link to Kodi debug log:
http://paste.kodi.tv/dafavicofi

Many thanks!

**Comment by elgatito** [comment]
@JacopoV It's not related to Elementum. https://www.themoviedb.org/talk/5f8807a3a806730037404cbb

**Comment by JacopoV** [comment]
Oh sorry about it. As mentioned i wasn't really sure! thanks again for your work 👍

**Comment by host505** [comment]
@elgatito tmdb admin identified the root cause of the problem on the thread you linked.
It seems a simple TLS transition would suffice, no?

**Comment by JacopoV** [comment]
I had to update Kodi to 18.9 to have the issue fixed
