### ISSUE TITLE
Adding items to library references plugin.video.quasar

### ISSUE THREAD

**Issue by strummerj** [elgatito/plugin.video.elementum#63]
I'm running 0.0.32. When I add a show to my Kodi Library all of the .strm files reference quasar as we see below. If I manually go in and replace quasar with elementum they work in Kodi. If not they fail to find quasar and won't open on kodi. Does elementum handle creating these files?

Contents of a .strm file:
plugin://plugin.video.quasar/library/show/play/1418/11/13

Thank you!

**Comment by strummerj** [comment]
Upon further investigation it seems like when I add something to my library from elementum it doesn't create folders or .strm files in my library folder at all. It just has the old files that were there from Quasar. Any ideas? Thanks!

**Comment by elgatito** [comment]
Of source Elementum is not overwriting any existing file!
You have two options: run Migrate from Elementum settings, or Disable quasar and delete strm files created by Quasar. Or just set another library path for Elementum. Otherwise Quasar will create strm files there.

**Comment by strummerj** [comment]
Thanks. I also just figured out that I needed to reboot Kodi to get Elementum to pickup the library path I set it settings. After doing that it seems better now.

**Comment by elgatito** [comment]
Make sure you have disabled Quasar syncronization, or better user another path for library, or you will have problems in future when both plugins will want to write same locations.

**Comment by strummerj** [comment]
I'll do that. Thanks again.
