### ISSUE TITLE
Trakt Not working anymore. No movies are being displayed. To fix it use private key to authorize.

### ISSUE THREAD

**Issue by Kristijan1001** [elgatito/plugin.video.elementum#630]
I don't know if this is going to get updated. But going to settings and trakt you can set your own trakt to fix it.

**Comment by Jezze83** [comment]
Does anyone know how to fix this or how to setup trakt api to kodi? Cant use elementum because trakt not working

**Comment by elgatito** [comment]
Google takes 1 minute to show how to "trakt api key create".

**Comment by antonsoroko** [comment]
https://github.com/elgatito/plugin.video.elementum/issues/534#issuecomment-571752668

**Comment by rudf0rd** [comment]
The reason we bounced the API key is because it was destroying Trakt profiles with duplicates.  If you care about your Trakt history at all, be careful with this plugin.

See: https://github.com/elgatito/plugin.video.elementum/issues/633

**Comment by elgatito** [comment]
Closing this issue.
Please, read the announcement at https://github.com/elgatito/plugin.video.elementum/issues/636
