### ISSUE TITLE
Is it possible to not showing the repeated part before clip title in video collections?

### ISSUE THREAD

**Issue by igorgidea** [elgatito/plugin.video.elementum#631]
Version used:
0.1.59
Environment name and version:
Kodi 18.9
Operating System and version:
Windows 10

**1.** When opened torrent that represents collection of videos is it possible to change settings or something, to not showing repeating part, but show only clip titles? Because current behavior makes hard to read titles.
![изображение](https://user-images.githubusercontent.com/20354531/97501853-b0eda180-197a-11eb-8e7f-25996b1d278a.png)

In this case title doesnt fit into window width and need to wait to see it (more than 30 seconds), that makes elementum unusable  for this video collection.
![изображение](https://user-images.githubusercontent.com/20354531/97551182-533d7180-19db-11eb-8fcb-c00a992266ae.png)

**2.** And second question: how to make autoplay next clip in the list?

**Comment by elgatito** [comment]
1. Directory name is removed when there is one directory and you can suppress it's name and leave only file names.
File names are not modified.

2. "Plays" are launched by Kodi, not Elementum.

**Comment by igorgidea** [comment]
Thank you for replying me and for Elementum, but im not sure what directory did you mean? There is no directories at all, im just open torrent. For example if i open the same torrent, from second attached screenshot with Ultra Music Hits. Часть 21 in mTorrent i see this:
![изображение](https://user-images.githubusercontent.com/20354531/97809411-64a1aa80-1c75-11eb-9bbf-57bfcdbe662e.png)
Seems like torrent name is the repeated part that should be removed to see only clip titles.

_"Plays" are launched by Kodi, not Elementum._
Is this means there is no way to start play all video clips in collection? Only run one by one?

**Comment by elgatito** [comment]
@igorgidea If you provide specific torrent - I will say why directory name is not removed.

If you want to modify file names - it will not happen. Elementum is removing directory name if there is only one directory in the torrent, and no files outside of it.

> Is this means there is no way to start play all video clips in collection? Only run manually one by one?

Yes. Kodi is requesting playback and expects one file to play.

**Comment by igorgidea** [comment]
_**If you provide specific torrent - I will say why directory name is not removed.**_
please try open this torrent [http://d.rutor.info/download/741466](url)
_**If you want to modify file names - it will not happen.**_ 
Nope, im just wanna to see it.

**Comment by elgatito** [comment]
@igorgidea how you add that torrent to Elementum? When I add it from torrent file - I do not see any directory name, I see only names of files.

**Comment by igorgidea** [comment]
**First approach**
![изображение](https://user-images.githubusercontent.com/20354531/97978197-e6a8e500-1dd5-11eb-8ed3-43892376b733.png)
![изображение](https://user-images.githubusercontent.com/20354531/97978254-faece200-1dd5-11eb-8e18-00b5c62e70b6.png)
![изображение](https://user-images.githubusercontent.com/20354531/97978316-13f59300-1dd6-11eb-81d2-5137a100f449.png)
![изображение](https://user-images.githubusercontent.com/20354531/97978361-2374dc00-1dd6-11eb-9002-4ebbe4b2baa1.png)
![изображение](https://user-images.githubusercontent.com/20354531/97978551-60d96980-1dd6-11eb-9a3b-33a1c2da4a92.png)
**Second approach**
![изображение](https://user-images.githubusercontent.com/20354531/97978197-e6a8e500-1dd5-11eb-8ed3-43892376b733.png)
![изображение](https://user-images.githubusercontent.com/20354531/97978641-85354600-1dd6-11eb-9eca-17f32c1cd587.png)
![изображение](https://user-images.githubusercontent.com/20354531/97978748-ad24a980-1dd6-11eb-9491-ef2f8ad91a10.png)
![изображение](https://user-images.githubusercontent.com/20354531/97978819-ce859580-1dd6-11eb-92fb-cc66caaf74e1.png)

**Comment by elgatito** [comment]
@igorgidea If you wait and the name in "Files" window is scrolling, you see after directory name "/" or "\" (before file name)?

**Comment by igorgidea** [comment]
Yes i see "\" before file name
![изображение](https://user-images.githubusercontent.com/20354531/97989061-a736c480-1de6-11eb-956f-6997516d591a.png)

**Comment by elgatito** [comment]
@igorgidea try with v0.1.61.

**Comment by igorgidea** [comment]
With 0.1.61 works fine. Thanks a lot!

**Comment by elgatito** [comment]
Good!
