### ISSUE TITLE
[Bug] Torrent isn't resolving from Results window

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#632]
1. Searching torrent for example: Blindspot S05E07
2. Selecting this result :
Blindspot S05E07 1080p WEB H264-METCON[rarbg]
Provider: torrentdownloads
(By the way, sometimes this result shows up and sometimes it doesn't, I don't know why, it seems that also other results from this provider according to the search results on their site doesn't show up)
3. It shows "Playback is failed", the torrent isn't resolved.
4. Add this torrent manually by "Add torrent" (The file: https://f2h.io/1r3kpn3227a3)
5. The torrent is working and resolved. The buffer dialog is show up.

Kodi Log for 1 to 3:
https://paste.ubuntu.com/p/FSSsxcxzVb

Kodi Log for 4 to 5:
https://paste.ubuntu.com/p/vVZcmQxNxG

Why there is a difference between loading the torrent through the Results window and add torrent manually?

## Environment
Elementum 0.1.59
Kodi 17.6
Windows 10, 64bit

**Comment by ShlomiD83** [comment]
did you check how many seeders the torrent has?
it's seems it has only 4 seeders and can't connect to them.

**Comment by burekas7** [comment]
@ShlomiD83 

When I add it manually it connected to them and start downloading (Not so fast because it has low seeders but it started)
But when I click on it from the results the playback failed at the start.

**Comment by JacopoV** [comment]
+1 

Last night was able to resolve and play from the result window, but as we speak, it can't anymore.

Kodi 17.9 (latest Leia with fixes for Clourflare) on Android TV 9. 
No recent updates on Kodi or anything else in the last 36hours. 

Log : http://paste.kodi.tv/garucanude

Thanks

**Comment by ShlomiD83** [comment]
@burekas7 

i was able to reproduce your problem, it throws an error.

regarding results not showing up it's because of an API limitation form torrentapi, this problem occurred also with Magnetic Providers. it's a limit of number of requests per 1 or 2 seconds.

**Comment by JacopoV** [comment]
@ShlomiD83 on my end it can't start any stream at all. Sometimes in the Kodi UI notification seems to throw an error. I ll try to reproduce it

**Comment by JacopoV** [comment]
Sorry i do apologise. It turned out my ISP updated the router and reboot my network.  By doing so the firewall settings i had, somehow and for the first time, have been altered. It's now all working. Cheers.

**Comment by elgatito** [comment]
@burekas7 

> Kodi Log for 1 to 3:

Here you add magnet. Which means you need to connect to real people to get information about the torrent. 
Libtorrent failed with that. You can increase the timeout for maget resolve.

> Kodi Log for 4 to 5:

Here you add torrent file. Which means you already have information about the torrent, so download starts instantly.

**Comment by burekas7** [comment]
Understood.

Thanks @elgatito
