### ISSUE TITLE
Trakt sync is adding plays in a loop

### ISSUE THREAD

**Issue by jovalbo** [elgatito/plugin.video.elementum#633]
Several months ago, I notice all my plays in trakt had been disappeared. I contacted the team and apparently elementum was sending plays in a loop and they deleted my history.

I disabled trakt sync in elementum, and today I wanted to set it up again, so I created a new API key, I put it in elementum and I enable again trakt sync.
Apparently, elementum is adding plays in a loop, I don't know why.
I thought tha enabling "Remove multiple plays from history, leave 1" would work but I have the same problem, the plays were deleted from my trakt account and added just after that.

Do you have any idea why this is happening? Any possible solution?

Thanks in advance .

https://paste.kodi.tv/kojurelehe.kodi

**Comment by elgatito** [comment]
Closing this issue.
Please, read the announcement at #636
