### ISSUE TITLE
Elementum daemon: TypeErrore('argument 1 must be string withoute null bytes, not str',)

### ISSUE THREAD

**Issue by kuchka506** [elgatito/plugin.video.elementum#634]
Падает Элементум при включённом Рутрекере в burst.
Elementum daemon: TypeErrore('argument 1 must be string withoute null bytes, not str',)
http://paste.kodi.tv/izomuvutix.kodi

**Comment by elgatito** [comment]
@kuchka506 отключайте отладку встроенного прокси в Elementum. Скорее всего ошибка пропадёт.

**Comment by kuchka506** [comment]
Отключил. Пропала.

**Comment by elgatito** [comment]
version 0.1.60 has a fix for this.
