### ISSUE TITLE
Elementum keeps crashing. Reloading configuration loop

### ISSUE THREAD

**Issue by Firestorm7893** [elgatito/plugin.video.elementum#635]
## Expected Behavior
Elementum starting up
## Current Behavior
Right now elementum keeps crashing on loop, i watched the logs and nothing really stood out to me, only some kind of socket error?

## Steps to Reproduce (for bugs)
Unfortunately I can't say a method to reproduce the bug. I just open kodi

## Context
Never used elementum before, just installed it for the first time today. I tried clearing the cache and everything from elementum settings but nothing helped

## Your Environment

* Version used:
1.59
* Environment name and version:
Kodi 18.9 leia
* Operating System and version:
Windows 10 pro 20H2
* Link to Kodi debug log:
[https://pastebin.com/k6XRsxdf](url)

I tried running elementum.exe by itself, here's what is displayed:
![Cattura](https://user-images.githubusercontent.com/12925730/98483944-49521480-220c-11eb-8511-8719f5cf344e.PNG)

**Comment by elgatito** [comment]
@Firestorm7893 your log says it cannot start on the port, like something is already there.
Maybe try to remove and re-install the addon from zip file.

**Comment by elgatito** [comment]
Closing without getting response.
