### ISSUE TITLE
not seeding and reboot fill problems 

### ISSUE THREAD

**Issue by tomtomclub** [elgatito/plugin.video.elementum#64]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

nr 1:the addon is not seeding ( this is important for the entire torrent community}
nr 2 ;after reboot the movie is still gone? 
systeem linux 64 bit  ***0032 **elementum

**Comment by elgatito** [comment]
Where is the log?

**Comment by tomtomclub** [comment]
https://paste.ubuntu.com/26425794/

sorry mate

**Comment by elgatito** [comment]
Maybe, after UPNP/NAT will be added to the torrent library - it will seed better. There is nothing to do with it in Elementum.

About restarts - it's not yet working fine and controlling old torrents.

**Comment by tomtomclub** [comment]
oke no problems , i hoop you can fix it ,

**Comment by elgatito** [comment]
You can try 0.0.35 with upnp support (it's in testing mode)

**Comment by elgatito** [comment]
@tomtomclub , you can try 0.0.36, torrent are re-added after client restart, so you won't loose them.
Cheers.

**Comment by ziiky** [comment]
I tryed 0.0.36 
speed is little better but oscilating too much. Is not constant like in quasar.
Elementum still do not upload/seed! Quasar seed nicely with good speed
After last update ... video play stucking all the time

[kodi.log](https://github.com/elgatito/plugin.video.elementum/files/1671229/kodi.log)

**Comment by elgatito** [comment]
> video play stucking all the time

You should be more descriptive. 

> speed is little better but oscilating too much. Is not constant like in quasar.
Plugin is not doing any downloads, it's done by torrent engine. If Quasar works for you - it's great if you can use it further.

**Comment by elgatito** [comment]
Regarding the reported issue:
Torrents' queue is now reloading after restarts (applicable only to non-memory storages).
Upload/seed is not controlled/done by this plugin.
