### ISSUE TITLE
Cant select local subtitles

### ISSUE THREAD

**Issue by najibrajak** [elgatito/plugin.video.elementum#640]
When i want to select subtitle from local by selecting "browse subtitle", theres no option to select local directories instead of plug in directories.

**Comment by elgatito** [comment]
@najibrajak When you open subtitles menu - it is controlled by Kodi, that shows all available subtitles addons.

**Comment by elgatito** [comment]
Closing without getting response.

**Comment by froggz19** [comment]
I have the same problem, I cannot select a local subtitle file, Kodi 18.9 x64 and Elementum 0.1.68.

https://user-images.githubusercontent.com/8935954/108638746-094c3000-7491-11eb-93cb-8b207a2ad4af.mp4
