### ISSUE TITLE
[Request] Обновление кода для Kodi 19

### ISSUE THREAD

**Issue by Lontron** [elgatito/plugin.video.elementum#645]
https://forum.kodi.tv/showthread.php?tid=344263&pid=2975581#pid2975581
01 September 2020 - xbmc.translatePath() was moved to the xbmcvfs module (xbmcvfs.translatePath()) 

Log: http://paste.kodi.tv/nirovomenu `2020-11-12 13:08:34.183 T:9824  WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.`

**Comment by elgatito** [comment]
@vlmaksime want to pick this up?)

**Comment by vlmaksime** [comment]
Этот метод удалят аж в 20й версии. Я надеюсь, что совместимость реализуют в kodi-six.

**Comment by elgatito** [comment]
@vlmaksime @Lontron перемотка теперь работает в последней версии с Коди 19?

**Comment by vlmaksime** [comment]
у меня заработала

**Comment by Lontron** [comment]
> @vlmaksime @Lontron перемотка теперь работает в последней версии с Коди 19?
Да

**Comment by vlmaksime** [comment]
**Roman_V_M** объяснил, что kodi-six не отвечает за обратную совместимость модулей ([ответ](https://forum.kodi.tv/showthread.php?tid=327883&pid=2989430#pid2989430)). Поэтому придется добавлять совместимость в коде. На выходных постараюсь поправить.

**Comment by elgatito** [comment]
@vlmaksime @Lontron в версии 0.1.63 много изменений. Проверьте на Kodi19, работают ли диалоги всплывающие. И вообще.

**Comment by Lontron** [comment]
> @vlmaksime @Lontron в версии 0.1.63 много изменений. Проверьте на Kodi19, работают ли диалоги всплывающие. И вообще.

работает
