### ISSUE TITLE
Kodi 19 beta1, 0.1.62: not solve the CloudFlare challenge

### ISSUE THREAD

**Issue by Gregsr** [elgatito/plugin.video.elementum#648]
Impossible to download the torrent 
`WARNING <general>: [plugin.video.elementum] [33mWARN  proxy        ▶ handleResponse   [0mCould not solve the CloudFlare challenge: jschl_vc is missing from challenge form`

**Comment by elgatito** [comment]
@Gregsr Cloudflare protection is not solved by Elementum. It will be removed from Elementum totally, probably, in future versions.
