### ISSUE TITLE
Plugin not working in kodi 18.9 on xbox series S

### ISSUE THREAD

**Issue by daguix** [elgatito/plugin.video.elementum#649]
Hi,

  I tried to install the latest release of the plugin 0.1.62 in kodi on xbox series S. There is an error WindowsError(3,'L') after install. The plugin does not launch. I tested the same plugin on Android mobile and TV and it works fine.

**Comment by elgatito** [comment]
@daguix there are many issues about xbox. It does not allow to run the binary, nothing to do with it.

**Comment by daguix** [comment]
Thanks for the quick answer and for all your work.

**Comment by elgatito** [comment]
@daguix Can you please try this one - https://github.com/elgatito/plugin.video.elementum/issues/669#issuecomment-1369529351
