### ISSUE TITLE
[Request] Activate Extra Fanart

### ISSUE THREAD

**Issue by daviddia5** [elgatito/plugin.video.elementum#650]
I know it is not a vitally important thing but many users love this feature.
I leave it as a suggestion, and thank you very much for years of fantastic work.

**Comment by elgatito** [comment]
@daviddia5 what is an "Extra Fanart"? What do you mean?

**Comment by daviddia5** [comment]
> @daviddia5 what is an "Extra Fanart"? What do you mean?
When you are in a movie tab, the background image changes every 4 or 5 seconds.
This is done through fanart.tv

**Comment by daviddia5** [comment]
![VID-20201125-WA0004](https://user-images.githubusercontent.com/74454397/100230389-f83d6280-2f25-11eb-9d36-b52f60854971.gif)

**Comment by elgatito** [comment]
@daviddia5 Please, try with v0.1.63.

I have found only the possibility to set `setAvailableFanarts`, but can't say it is what you want. Please, try it and say what you have.

**Comment by daviddia5** [comment]
It does not do what I said, that is, Get multiple fanarts from fanart.tv and the skin is responsible for displaying them cyclically.
I have seen this option in the tmdb helper addon.

But it has improved obtaining the best fanart and clearlogo (which in my language, Spanish, sometimes failed)
Thanks for the job!

**Comment by elgatito** [comment]
> It does not do what I said, that is, Get multiple fanarts from fanart.tv and the skin is responsible for displaying them cyclically.
> I have seen this option in the tmdb helper addon.

@daviddia5 Okay, then if you find what is needed - you can write. Because I see no other way to set multiple fanarts to skins.

**Comment by elgatito** [comment]
@daviddia5 what skin you use, so that you see background changes in tmdbhelper? I've tried Arctic Zephyr and Aura and Arctic Horizon and background are never changed.

**Comment by daviddia5** [comment]
> @daviddia5 what skin you use, so that you see background changes in tmdbhelper? I've tried Arctic Zephyr and Aura and Arctic Horizon and background are never changed.

I use AuraMod

**Comment by elgatito** [comment]
@daviddia5 Okay. I have installed AuraMOD, entered TMDBHelper listings and still can't see changing backgrounds. Maybe have to enable it somehow in TMDBHelper or the skin?

**Comment by daviddia5** [comment]
I think it is enabled by default. 
Test on skin settings, Background, Set timer per image: 4 seconds
In library views use Showcase view, and Extra fanart: On
I hope this helps.
![16086564557743352175065347697577](https://user-images.githubusercontent.com/74454397/102914060-08425680-4480-11eb-972b-c29e8dea4514.jpg)
I have taken the photo just at the moment the fanart is changing.

**Comment by daviddia5** [comment]
TheMovieDB Helper settings:
![1608658192192475422135637006161](https://user-images.githubusercontent.com/74454397/102916390-bf8c9c80-4483-11eb-8f51-dcba5c58d226.jpg)

**Comment by elgatito** [comment]
@daviddia5 Oh! I have missed that option in the list to enable fanart. Now it works and the next version will show fanarts.

**Comment by elgatito** [comment]
@daviddia5 Please, try with 0.1.64.

**Comment by daviddia5** [comment]
Hello! Should multiple fanart be enabled? Only one appears to me.

I have detected that, for example, in the "Trending" category the synopsis is now not shown in my language (Spanish), in previous versions it is.

**Comment by elgatito** [comment]
> Hello! Should multiple fanart be enabled? Only one appears to me.

You only have to enable fanart.tv in Elementum settings.
And of course it should be enabled in your skin settings.

> I have detected that, for example, in the "Trending" category the synopsis is now not shown in my language (Spanish), in previous versions it is.

Your language should be used, if possible.

**Comment by daviddia5** [comment]
Ok, I have already discovered the problem.
Movies, most popular (tmdb): multiple fanart working! Thanks!! And language ok.

Movies, all Trakt categories (Trending, my wishlist, etc) only one fanart and language in english (the synopsis, the poster is displayed in my language)

The same happens in TV Shows

**Comment by daviddia5** [comment]
ok forget the above, everything works fine !!
I had "get Trakt info for lists" enabled and that was the problem

**Comment by elgatito** [comment]
@daviddia5 I was thinking of advising to check that setting, because Trakt is not sharing images information now.

**Comment by elgatito** [comment]
@daviddia5 glad to hear. Closing the issue.
