### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters

### ISSUE THREAD

**Issue by pekindenis** [elgatito/plugin.video.elementum#651]
Kodi version: 18.7
Elementum: elgatito 0.1.62
OS: raspbian

 -->End of Python script error report<--
UnicodeEncodeError: 'ascii' codec can't encode characters in position 29-35: ordinal not in range(128)
log.debug('{0}.onNotification({1}, {2}, {3})'.format(self, sender, method, py2_decode(data)))
File "/root/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/monitor.py", line 52, in onNotification
Traceback (most recent call last):
Error Contents: 'ascii' codec can't encode characters in position 29-35: ordinal not in range(128)
Error Type: <type 'exceptions.UnicodeEncodeError'>
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!

**Comment by elgatito** [comment]
@pekindenis Please, try with v0.1.63.
