### ISSUE TITLE
[Bug] 'Download' from context menu still act as "use memory"

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#653]
In version 0.1.57 you first added this option as was mentioned there:
- Added functionality to allow using both memory and file storages. Running 'Download' from context menu will download with file storage.

But it's not working as it should be.

Steps:
1) Set Download methid "use Memory".
2) Set Download path.
3) Stand on an item to play, open the context menu.
4) Select the option of "Elementum Download".

Result:
What actually happend is that the file isn't downloaded to the path as "File Storage" option,
It still playing it as Memory type.

Kodi debug log:
https://paste.ubuntu.com/p/4SqBF5frcY

## Your Environment
Elementum 0.1.62
Kodi 17.6
Windows 10, 64bit

**Comment by burekas7** [comment]
Hi @elgatito ,
Have you checked this feature?
Do I understand it right, this is how it should work?

Thanks.

**Comment by elgatito** [comment]
@burekas7 "Elementum Download" from context menu should always use files, whatever is selected as active storage.

**Comment by burekas7** [comment]
Ok, so as I described above there is a bug with that when Elementum is set "Use memory".

**Comment by elgatito** [comment]
@burekas7 
Please, try with v0.1.63.
There was a bug with passing background download job from non-Elementum Kodi entries.

**Comment by burekas7** [comment]
Yes, it's work.

But can you add a new option in the context menu of : "Elementum Download **& Play**"
Currently there is "Elementum Download" so it's just download it in the background.
So with the new request in addition of the download it also will start play it from storage (Exactly like it was if I was set it as "use Files" method)

"Elementum Play" running it as it set, "use memory" or "use files" type.
So even if I select "Elementum Download" and then "Elementum Play", it will start play it as "use memory" and not from the storage.
---

btw another issue is this dialog, since 0.1.63 there is a number of seconds in the buttons (Here is on the Yes, but sometimes it's on the No), I guess it's the fallback choose after a timeout, but is it shuold be like this?
![image](https://user-images.githubusercontent.com/13424257/102899941-53566c80-4474-11eb-9d65-eaead2eb327f.png)

**Comment by elgatito** [comment]
@burekas7 currently there are "Play" and "Download" options. One for playing, another for downloading. 
Adding auto-play to downloaded will make a mess, since you don't know when it is completed. In the latest version there is a notification that download is completed.

**Comment by burekas7** [comment]
@elgatito 
So the only option in this case is to donwload and then go to the Torrents list and play it from there?
There is no other way to do this from the context-menu of downloading and playing?

**Comment by elgatito** [comment]
@burekas7 that is the only way. To do what you want - need to change both context plugin and elementum.

**Comment by elgatito** [comment]
Closing this issue.
