### ISSUE TITLE
[Question] Init buffer size

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#654]
Hi,

I have a question about the init buffer size settings:
It always take the "Beginnig of file buffer size" value and add 10MB-20MB to this value as init buffer size when starting playing a torrent (or to the value from AdvancedSettings)

What is the meaning of the "End of file buffer size"?

![image](https://user-images.githubusercontent.com/13424257/101286139-8a304f80-37f1-11eb-8cd9-1b931e1fc402.png)

**Comment by antonsoroko** [comment]
you can find the answer here https://github.com/elgatito/plugin.video.elementum/issues/455

**Comment by elgatito** [comment]
@burekas7 when you open file in Kodi - it takes bytes from the beginning and bytes from the end of file. It is always rounded to actual piece size of that torrent. 
If Piece size is 16MB, so even for 1 Kb you need to download the whole 16MB. But we make sure to have the size, we setup in the settings.

**Comment by burekas7** [comment]
Thanks @antonsoroko 
@elgatito 

So what is the actuall need of having this "End of file" in the setting?
How does changing this impact on the playing/download progress?
(The using of "Begin of the file" I pretty understand)

**Comment by elgatito** [comment]
@burekas7 who knows what you want. It's just a possibility to change how much you want to pre-download before starting the playback.

**Comment by burekas7** [comment]
Ok, thanks.
