### ISSUE TITLE
Inconsistent results during 4k streams

### ISSUE THREAD

**Issue by samjuels** [elgatito/plugin.video.elementum#655]
## Current Behavior
When streaming 4k files from sources (above 10Mb/s) I get repeated crashes of either elementum or kodi during streams.
If I repeatedly attempt to play the same file eventually it will work.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
1.62
* Environment name and version:
Kodi 18.9
* Operating System and version:
Android TV Shield TV 2019
* Link to Kodi debug log:
https://pastebin.com/hFq8n1bp

**Comment by elgatito** [comment]
@samjuels what should I see in that log? You just opened something and then log is finished. 
If you have crashes, then you need to show what happens then.

**Comment by samjuels** [comment]
> @samjuels what should I see in that log? You just opened something and then log is finished.
> If you have crashes, then you need to show what happens then.
How is that possible if kodi is crashing? is there another log file I need to enable?

**Comment by elgatito** [comment]
Check for kodi.old.log file, near the usual kodi.log file.

**Comment by samjuels** [comment]
https://pastebin.com/YXBq29Vh

this is a section of the complete log. let me know if you need more.

**Comment by samjuels** [comment]
heres a more complete log, i recreated the error with a different file.

https://pastebin.com/ffMQT0xM

**Comment by elgatito** [comment]
Disable libtorrent alerts in Elementum settings. And try again.

**Comment by samjuels** [comment]
oddly enough i just did that...
https://pastebin.com/ffMQT0xM

**Comment by samjuels** [comment]
here is another attempt...
https://pastebin.com/JE996aeT

**Comment by samjuels** [comment]
one more ...
https://pastebin.com/4X7cuj4j

**Comment by elgatito** [comment]
@samjuels I don't see any problem there.
Maybe you have out-of-memory issue, of something like that, if you Kodi is killed.

**Comment by samjuels** [comment]
You are absolutely correct!!! I tried running my old 2017 shield tv (3gb) and it works perfectly!!! That extra gig of ram makes all the difference. Thank you for being awesome!!!!.
