### ISSUE TITLE
[Bug] Kodi language not properly used.

### ISSUE THREAD

**Issue by an0nimo** [elgatito/plugin.video.elementum#656]
I have installed only official KODI scraper TMDb addon as "info provider" and it is working fine pulling the text of synopsis, or of summary, in portuguese language on EXODUS addon but don't work on ELEMENTUM addon pulling the text only on english language.
The TMDb addon is all set for portuguese language.
So, I didn't find a way to set ELEMENTUM addon to get the text of TV Shows/Movies synopsis in different language of english.

**Comment by elgatito** [comment]
@an0nimo Sorry, I don't understand what you talk about.
Elementum is not using any scrapers, it takes information directly from TMDB.

**Comment by elgatito** [comment]
This issue describes a bug, or you request something?

**Comment by an0nimo** [comment]
Thank you for quickly reply.
Well... this is a **request**, I think, unless there is a way to configure the elementum addon to change the language of the synopsis text of TV programs and movies to Portuguese, or other, that I have not seen.
If the Elementum addon pulls the text of synopisis directly from TMDB in english as a default, so the request is a way to pulls the text of TV Shows/Movies synopsis in others language.

**Comment by elgatito** [comment]
@an0nimo let me guess what you are talking about.

Your Kodi language is set to Portuguese/Brazil in Kodi.
You go to Elementum, browsing movies/shows, you see titles in proper language, but description is english? Or you see everything in english?

**Comment by an0nimo** [comment]
> Your Kodi language is set to Portuguese/Brazil in Kodi.

Yes... and pt-br language is set in TMDb addon too.

> You go to Elementum, browsing movies/shows, you see titles in proper language, but description is english? Or you see everything in english?

Everything is in english.
Like example, below are 2 links of print screen that I took. See the text inside of red retangule.
This link is the TV Show description (episode resume or synopsis) in portuguese language viewed on EXODUS addon:
https://ibb.co/cY7sNtv
And this link is the TV Show description (episode resume or synopsis) in portuguese language viewed on ELEMENTUM addon:
https://ibb.co/9whWd2R

**Comment by elgatito** [comment]
@an0nimo I would ask you to provider a Kodi log. You can just start Kodi and make a log file, without doing anything else.
http://elementum.surge.sh/contribute/log/

**Comment by an0nimo** [comment]
Okay... but which option I choose to upload log: **/debug/bundle** or **/debug/all** ?

**Comment by elgatito** [comment]
Any, I need to see what configuration is collected on your Kodi. Bundle is fine.

**Comment by an0nimo** [comment]
Okay.
Is here:
http://paste.kodi.tv/ahoyehorat

**Comment by elgatito** [comment]
@an0nimo thanks for that log. It made the bug clear.
Please, try with v0.1.63.
Should be better.

**Comment by an0nimo** [comment]
Thanks for your quick support but something is not right.
After install **v0.1.63**, in the page of the search result, the text of description is correct in portuguese...
https://ibb.co/7VknBHW
... but in page of the episodes, the description for each episode is not is shown.
https://ibb.co/bgKhPfz

**Comment by elgatito** [comment]
@an0nimo provide new log where you went to episodes list and you see everything in english.
Also try to restart Kodi, and go to Elementum settings and click "Clear TMDB cache".

I have changed language to Portuguese (Brazil), so to tv shows, select one, and I see names in Portuguese, description as well in portuguese.

**Comment by an0nimo** [comment]
> provide new log where you went to episodes list and you see everything in english.

Below is the log link. I don't see any description in english, only in portuguese or none. 
http://paste.kodi.tv/ehucezojiq

> Also try to restart Kodi, and go to Elementum settings and click "Clear TMDB cache".

I did it already before write my previous message. I cleanned all options in "Database" and in "Cache" but it didn't resolve. I changed too some settings in "Kodi Libary" and "Automatic Scape" but nothing.

**Comment by elgatito** [comment]
@an0nimo that is not the right log format. 

I don't understand what is the problem now. You see english names of episodes everywhere? Or for some shows only?
You see descriptions in english? Everywhere?

**Comment by KillerJoeBR** [comment]
Hi @elgatito. I'm also Brazilian and I thank you for trying to fix this issue. With the latest release 0.63 now I see the movies and series description in Portuguese (I'm not sure if it's Brazilian Portuguese or Portugal) anyway thats already a huge improvement. Some episodes description are blank. But the majority have. So I guess there isn't one avaliable in Portuguese in the tmdb database for those that don't appear anything.

Perhaps elementum could use the English description as a fallback, second option when there isn't a description in the language selected. 

Anyway I think right now it's already a huge improvement. Thank you!

**Comment by KillerJoeBR** [comment]
Ok let me give you more info.

The problem seems to happen only in episode titles/ descriptions. 

Movie and series  plots are in Portuguese and some are in English (newer ones mostly). So I guess when there isn't a Portuguese description it already shows the English default one.

But in episodes this doesn't happen. When there isn't a Portuguese description it doesn't show anything. So it's blank.

**Comment by an0nimo** [comment]
> @an0nimo that is not the right log format.

This time I chose **/debug/all** option instead **/debug/bundle**. 

> I don't understand what is the problem now. You see english names of episodes everywhere? Or for some shows only?
You see descriptions in english? Everywhere?

Sorry for delay but I was making a video to explain better, comparing Seasons and Episodes descriptions of TV Shows inside of ELEMENTUM and EXODUS addons:
https://streamable.com/vddnw7

**Comment by elgatito** [comment]
@KillerJoeBR @an0nimo Thanks for giving more information. This is more clear now.

> I'm not sure if it's Brazilian Portuguese or Portugal

Here you can see languages, supported by TMDB - https://developers.themoviedb.org/3/configuration/get-languages (api key: 8cf43ad9c085135b9479ad5cf6bbcbda ). 
As you can see, there is only Portuguese, nothing for Brazil.

> So I guess there isn't one avaliable in Portuguese in the tmdb database for those that don't appear anything.

Yes, sometimes we get no localized description, so we get blank entries.

This is pretty complicated. 
I have added default getters for movies/shows/seasons/episodes, will be available in the next version.

**Comment by elgatito** [comment]
@KillerJoeBR @an0nimo Please, try with 0.1.64.

**Comment by an0nimo** [comment]
> @KillerJoeBR @an0nimo Please, try with 0.1.64.

After installed the v0.1.64, I cleaned all options of the "Database" and "Cache".
I made a video to show how is now:
https://streamable.com/mf0lqf
1- The Some descriptions of the TV Shows is in Portuguese and others in English, when not find in Portuguese, but it's Okay. No have problem;
2- The description on the Seasons list page is not displayed;
3- The Episodes description came back display in English, when should be in Portuguese.

**Comment by elgatito** [comment]
@an0nimo yes, when your local translation is not found - we take it from english, if english not found, we take from the original language. This is made to show you at least some information and not leaving empty fields there.

@KillerJoeBR  @an0nimo  Should I close this issue now?

**Comment by an0nimo** [comment]
> @an0nimo yes, when your local translation is not found - we take it from english, if english not found, we take from the original language. This is made to show you at least some information and not leaving empty fields there.

Well... anyway thank you very much for always quickly reply and for tried to help.
My suggestion is add an option in settings to choose which scraper addon we want set to obtain the TV Shows/Movie descriptions because inside of them we can choose the language preferred to be showed and if will be obtain in TMDb, IMDB, TVDB or other.
In EXODUS addons, the descriptions are obtained from IMDB. I see that in the description address:
https://streamable.com/kcxhd7
**What is the file of Elementum addon that can I try to change TMDB for IMDB ?**

**Comment by elgatito** [comment]
@an0nimo As I've said in the first reply:
> Elementum is not using any scrapers, it takes information directly from TMDB.

We take what we can from TMDB. IMDB does not have API, TVDB makes API non-free.

**Comment by KillerJoeBR** [comment]
@elgatito

OK so I tested the the 0.1.64 and it seems to be working fine for everything. Every movie, series, season and episode that I saw had a description. Most ones in Portuguese, just some in English but that's expected.

And now it shows artwork for banners and actors! That's a great improvement! 

I think this version is great! Thanks
