### ISSUE TITLE
[Bug] "Trakt -> My Progress" isn't working

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#657]
Hi,

Since updating to 0.1.63 I get an error while trying to enter into Trakt->My Progress
* Just to mention that Trakt is responding, Trakt -> My Collection is worikng.

Kodi Debug Log:
https://paste.ubuntu.com/p/Gpf3DZZ5QP

Thanks.

**Comment by elgatito** [comment]
[navigation.py.zip](https://github.com/elgatito/plugin.video.elementum/files/5730932/navigation.py.zip)

Can you replace your `navigation.py` script, that is inside of `plugin.video.elementum/resources/site-packages/elementum` directory.
Then set logging level of Elementum to `DEBUG` (in Elementum settings).
And make another log file.

**Comment by burekas7** [comment]
@elgatito 
With this file it's working.

Kodi debug log:
https://paste.ubuntu.com/p/wvghnXM3rQ

* btw I see this file also exist in the main directory.

**Comment by elgatito** [comment]
@burekas7 please, try now this version. Trying to understand the cause of an error.
There is a global `navigation.py`, but it has few lines and calls the bigger one.

[navigation.py.zip](https://github.com/elgatito/plugin.video.elementum/files/5731162/navigation.py.zip)

**Comment by burekas7** [comment]
It's working also with this file.

Kodi debug log:
https://paste.ubuntu.com/p/nwsBKfjkjC

**Comment by elgatito** [comment]
@burekas7 okay, thanks, now I get the problem. WIll be fixed in the next version.

**Comment by elgatito** [comment]
@burekas7 Please, try with 0.1.64.

**Comment by burekas7** [comment]
It's ok now.
Thanks.

**Comment by burekas7** [comment]
Hi, @elgatito 

There is a problem again with Trakt->My Progress.
I'm getting errors of 502 (or 500 that I saw once)

Just to mention that Trakt is working.
Movies & TV Shows collections are working.

Kodi debug log:
https://paste.ubuntu.com/p/S4bP2mHhy5

**Comment by burekas7** [comment]
It's ok now.
Maybe it was a problem with Trakt or something that was stuck with Elementum, I don't know.

**Comment by elgatito** [comment]
@burekas7 Yesterday Trakt had a maintenance. So API was not working for few hours.
