### ISSUE TITLE
Strange value on the dialog buttons

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#658]
Hi,
Since 0.1.63 there is a number of seconds in the buttons (Here is on the Yes, but sometimes it's on the No), I guess it's the fallback choose after a timeout, but is it shuold be like this?
![image](https://user-images.githubusercontent.com/13424257/102899941-53566c80-4474-11eb-9d65-eaead2eb327f.png)

In the settings btw there is only one option regarding this:
And the timeout there is 10, so where does the 1200 value come from?
(Not to mention that the option is disabled in my settings)
![image](https://user-images.githubusercontent.com/13424257/102901480-5f432e00-4476-11eb-9aef-37c0820a004a.png)

**Comment by elgatito** [comment]
@burekas7 good catch. Will fix that.

**Comment by elgatito** [comment]
@burekas7 Please, try with 0.1.64.

**Comment by burekas7** [comment]
Ok now.
Thanks.
