### ISSUE TITLE
Elementum crashing after 0.1.63 update on Kodi 16

### ISSUE THREAD

**Issue by gloga** [elgatito/plugin.video.elementum#659]
Elementum updated from 0.1.62 do 0.1.63 in the middle of video playback. After that it reported constant crashing.
I have tried reverting back to 0.1.62 and installing Elementum on fresh Kodi install.
Installation goes through fine, but after I open Elementum I ,again, get a crash notice.

* Environment name and version:
* Kodi 16.1 Jarvis
* Android 4.4.2

**Comment by elgatito** [comment]
@gloga Don't you want to give any information about your issue? Log file is required.

**Comment by gloga** [comment]
Sure. I'll provide you with the log ASAP.

**Comment by elgatito** [comment]
@gloga Please, try with 0.1.64.

**Comment by gloga** [comment]
[kodi.log](https://github.com/elgatito/plugin.video.elementum/files/5735665/kodi.log)

Here is the log.
Version 0.1.64 is only available as a source code and I don't know how to build it.

**Comment by elgatito** [comment]
```
CANNOT LINK EXECUTABLE: cannot locate symbol "sigfillset" referenced by "/data/data/org.xbmc.kodi/files/plugin.video.elementum/bin/android_arm/elementum"...
```

```
15:19:57 T:1790226936  NOTICE: Running on MBX B.S805.5 with Android 4.4.2 API level 19, kernel: Linux ARM 32-bit version 3.10.33

```

It will not work with Androdi 4.4.2: #576

**Comment by gloga** [comment]
Strange, because i think version 0.1.62 worked fine.
What's the latest version that will work with Android 4.4.2?

**Comment by elgatito** [comment]
Copying from the issue link, I've posted:

```
1.51 wouldn't work on android 4.4 as it actually built for android api
version 21(mean android 5)
1.41 works well on android 4.4, 1.42 and later doesn't work
I would suggest to install 1.41 on yours kitkat device and turn update off.
It's required to downgrade project dependencies versions to support android
4.4. I'm not sure it's reasonable to do
```

**Comment by elgatito** [comment]
You can try to compile it on yourself. There is nothing I can do.
