### ISSUE TITLE
[Bug] The resume dialog doesn't work properly

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#660]
Hi,

I found a bug with the resume operation. (I don't know for sure if it's kodi or elementum issue)

1) Play a media that you have stopped (Image1 - Aquaman for example)
2) First a kodi options pops up with options of: "Start from begining" or "Resume from ..." (Image2)
3) Select "Start from begining".
4) Then Elementum also pops up its resume dialog options: "Continue playback from ..."  (Image3)
* BTW, I don't know why there is a need also for this dialog if Kodi already pops up its own.
This is just unnecessary duplication I think.
5) Select "No".
6) Wait until the playback will start, at first it shows that it's on time 00:00 (Image4)
but then you can see the playback start from the resume point instead from the begining (image5)
It seems that it ignores 1-Kodi selection and 2-Elementum selection.

Kodi debug log:
https://paste.ubuntu.com/p/yv7YF2Rhmg

Image1:
![image](https://user-images.githubusercontent.com/13424257/103027424-7eb58600-455e-11eb-9050-268179a7dcd8.png)

Image2:
![image](https://user-images.githubusercontent.com/13424257/103027511-aefd2480-455e-11eb-9e60-2189abd84261.png)

Image3:
![image](https://user-images.githubusercontent.com/13424257/103027552-c2a88b00-455e-11eb-91f8-24297fef0fed.png)

Image 4:
![image](https://user-images.githubusercontent.com/13424257/103027642-ea97ee80-455e-11eb-967d-b654dec3dd50.png)

Image5:
![image](https://user-images.githubusercontent.com/13424257/103027706-09968080-455f-11eb-9ba8-b62e43d4aaf2.png)

---

Elementum 0.1.64
Kodi 17.6
Win10

**Comment by elgatito** [comment]
@burekas7 
There are several problems with resume function in Kodi:
1) It does not always ask to resume, even when it has stored resome position and after playback started it resumes without asking.
2) You don't know what user answers, to resume or not.
3) Kodi's logic differs from version to version, from OS to OS.

So there is no way to rely on Kodi resume functionality. For me it works in a random way. And you cannot disable it for Elementum playbacks (at least I don't know of any way to do that).

**Comment by elgatito** [comment]
btw, you can disable resume from Elementum in settings.

**Comment by burekas7** [comment]
@elgatito 
Do you mean to "Force resume playback" setting in the "Kodi Library"->General?
Why is it there? Is it relevant only for kodi library or also inside the addon?

Anyway I checked it when this setting is disabled, and now it seems that Kodi popup wins no matter what you choose in the Elementum dialog.
But how can I disable the Elementum dialog if so? Because it doesn't change anything in this case.

**Comment by elgatito** [comment]
There are 2 options:
Store Resume position for downloaded files
Ask to use stored Resume position

If you disable them - you will not be asked to resume from elementum, and elementum will not force Kodi to resume.

**Comment by burekas7** [comment]
> There are 2 options:
> Store Resume position for downloaded files
> Ask to use stored Resume position
> 
> If you disable them - you will not be asked to resume from elementum, and elementum will not force Kodi to resume.

Isn't it a conflict of these two settings of "Force" And "Ask".
Because if you enable the "Force" option, the "Ask" setting isn't relevant.
So if I understand it right, the "Ask" setting should be visible only when the "Force" is disabled.

btw, regarding the "Ask" setting, why one of the choices is "Ask to delete"? I think it should be another text there.

**Comment by burekas7** [comment]
@elgatito 

So I did some QA on this feature, and I cover all the options and those are my findings:

Elementum -> Settings -> Kodi library -> General
![image](https://user-images.githubusercontent.com/13424257/106472489-64e75700-64ab-11eb-9be2-91c1873dafa7.png)

## Current Behaviour ##
According to **"Ask to use store Resume position"** setting:
1. **No** - **Without** Elementum dialog, the "Force Resume" setting **doesn't** affect here.
The meaning is: Kodi dialog is the one that decideds here.

2. **Yes** - **Without** Elementum dialog, the "Force Resume" setting **does** affect here. 
The meaning is: Elementum is the one that decideds here according to "Force Resume".
Actually, "Yes" + "Force Resume" enabled = "No".

3. **Ask to delete** - **With** Elementum dialog, and the "Force Resume" setting **does** affect here:
* Force Resume: **Disable** - Kodi dialog is the one that decideds here no matter what you select in Elementum dialog.
The meaning is the the Elementum dialog is redundant here
* Force Resume: **Enable** : 
When one of the dialogs (Kodi or Elementum) are selected by resume option, the playback is resume.
When both dialogs are selected by playing from the begining, the playback will start from the begining.

      **Note1:**
      Elementum resume dialog is shown only if you choose to play the same last/previously torrent.
      If not, the new search process for new torrents will begin and this dialog doesn't show up when selecting a new torrent from 
      the results.

       **Note2:**
       I don't know why the text is "delete" here.



## My Suggestion ##
As you can see all the combination of these settings is confusing.
So I make a new suggestion that replace these settings of "Ask to use" + "Force Resume".

1. **Remove** the "Force Resume" setting.
2. **Change** the **"Ask to use"** setting to **"Force Resume options"**.
3. The options inside **"Force Resume options"** will be:
   a. **By Kodi**: 
   (Without the Elmentum dialog)
   Which is currently equale to:
   --- Ask to use: No 
   --- Ask to use: Yes + Force Resume: Disable
   --- Ask to use: Ask + Force Resume: Disable

   b. **By Elementum - Ask**: 
   (With the Elmentum dialog)
   Which is currently equale to:
   --- Ask to use: Ask + Force Resume: Enable

   c. **By Elementum - Force Resume**: 
   (Without the Elmentum dialog)
   Which is currently equale to:
   --- Ask to use: Yes + Force Resume: Enable 
   (Except when both dialogs were selected to play from begining)

---
I hope this is clear enough.
It's relates to Elementum 0.1.66.

Thanks you.

**Comment by elgatito** [comment]
@burekas7 Do you mean to leave option to store resume position, and make another setting with options:
1) By Kodi = to let Kodi do what it wants
2) By Elementum - Ask = to Ask in a dialog if we know Kodi was not asking.
3) By Elementum - Force = to not ask anything but force resume.

I think if Kodi was asking and we know the answer - we can automatically follow the answer, without asking?

**Comment by burekas7** [comment]
@elgatito 

I don't know how actually doing it because you said that there is a problem with resume function in Kodi.

But as I see there is no need for Elementum dialog at all or even the Force Refresh (But you can leave the Force option if someone want it)
Because when I tested it, all the time when I didn't use Elementum resume dialog, the kodi resume dialog worked fine (According to what I wrote).

**Comment by burekas7** [comment]
By the way, what is the purpose of the "Store resume position for downloaded files"?
Why does it have a specific setting for this case?

**Comment by elgatito** [comment]
@burekas7 We can get resume position from Kodi, only when item is stored in library, then we can get it.
In all other cases, we can get what user answered, but we don't know where Kodi wants to seek the video.

Then the next issue is that Kodi does not always seek the video, it differs for platforms/Kodi versions/video format/etc.

That is why Elementum is asking to resume and then force the resume, meaning it checks that Kodi really seek the video, if not, then initiating seek again.

For getting proper resume position Elementum stores playback progress locally, for items, played with Elementum.

**Comment by burekas7** [comment]
@elgatito 
Now I'm get what you meant for.
So the reason it probablt worked for me with the Kodi dialog selection is because I tested it with Trakt lists and the content their is also exist in my Kodi Library.

So to summarize there are two issues:
1 - Resume position depends on the source (Kodi Library vs all the others)
2 - Kodi is not consistant in resuming, it differs for platforms/Kodi versions/video format/etc

I understand the logic, but the settings are very confusing as I discribed all the combinations.
I think it will be better if you change it according to my suggestion and as you wrote in this comment: https://github.com/elgatito/plugin.video.elementum/issues/660#issuecomment-771176691

The goal is to avoid double dialogs (The Elementum dialog) if there is no need (Of course if we verify that Kodi do its job - resume and seek).

For example, if the most using is for Kodi Library content / Trakt Lists that most of their content is similar to kodi library, so I will probably choose "By Kodi".
Other will might choose "By Elementum - Ask" or "By Elementum - Force"

The issue with "Force" option by the way that it may confusing when Kodi dialog shows up, because it won't have any meaning to the selection there, but here we can't do anything. So who that will select that should be aware of that.

**Comment by elgatito** [comment]
@burekas7 Please, try with v0.1.67.

**Comment by burekas7** [comment]
@elgatito 
Thanks. I tested it on 0.1.67

* **by Kodi** - Works well.
* **by Elementum - Force** - Works well.
* **by Elementum - Ask** : There was no Elementum dialog at all. I played it from Trakt lists, and no matter of the content is exist in my Kodi Library or not. Does it suppose to behave like this? If so, what is the difference between "by Kodi" and "by Elementum - Ask"? Or you are actually checking before if kodi can handle the resume?

**Comment by elgatito** [comment]
> by Elementum - Ask : There was no Elementum dialog at all. I played it from Trakt lists, and no matter of the content is exist in my Kodi Library or not. Does it suppose to behave like this? If so, what is the difference between "by Kodi" and "by Elementum - Ask"? Or you are actually checking before if kodi can handle the resume?

Yes, when we are sure we get answer from Kodi resume dialog - we skip asking.
We cannot disable resume dialog from Kodi, so we can only expect to get an answer.

**Comment by burekas7** [comment]
> > by Elementum - Ask : There was no Elementum dialog at all. I played it from Trakt lists, and no matter of the content is exist in my Kodi Library or not. Does it suppose to behave like this? If so, what is the difference between "by Kodi" and "by Elementum - Ask"? Or you are actually checking before if kodi can handle the resume?
> 
> Yes, when we are sure we get answer from Kodi resume dialog - we skip asking.
> We cannot disable resume dialog from Kodi, so we can only expect to get an answer.

Understood, It's ok, it's good as it now that Kodi dialog is the one that show up instead of Elementum dialog.
Also the resume and seek is ok also with the "Ask" option.
So now basically I can't test the "by Elementum - Ask" option with the dialog :)
* I checked that with kodi 17.6 in windows.

By the way in addition as I wrote in one of the notes, there was addtional issue with the Elementum resume dialog that wasn't show up if you choose not to play the previous torrent from history and start a new search. But I can't test it now according to this new change.

**Comment by elgatito** [comment]
@burekas7 I have changed it in v0.1.68. As I said, Kodi does not ask to resume for strm items, but was giving 'resume:false' without questions. So Elementum is now asking if Kodi sent that.

**Comment by burekas7** [comment]
@elgatito 

According to version 0.1.68:
* by Kodi - Works well.
* by Elementum - Force - Works well.

* The open issue is still with "by Elementum - Ask".
Now on 0.1.68 I do get the Elementum dialog
Currently it acts like this:
(Assuming "K"=kodi resume dialog, "E"=Elementum resume dialog, "P"=Playback)

K=resume, E=begining => P=resume
K=begining, E=resume => P=resume
K=begining, E=begining => P=begining
K=resume, E=resume => P=resume

So what is the purpose of Elementum Dialog here?
On one case Kodi wins and on other case Elementum wins.

I understand it that it should work so Elementum is the one who force the playback by its dialog selection.
But it doesn't work like this.

Just to mention, the tests was done from Trakt My Collection list.

**Comment by elgatito** [comment]
@burekas7 Writing last time here.

We never know if Kodi was really asking user to resume. But we ALWAYS get "resume:false" from it. Even when it did not ask at all.
That is why Elementum is always asking to resume if Kodi sent "resume:false".
I will not change that logic. 

If your Kodi works fine with resuming - just disable it in Elementum.

**Comment by burekas7** [comment]
OK, Thanks.

So just to summarize if someone else will asks:
The feature of "by Elementum - Ask" works only if you choose the same option in both dialogs (Kodi & Elementum), 
otherwise it will set it as "Resume" if there was different selection between them.

* And a small open bug regarding: (Not so crucial)
When there is previously torrent that is saved in Elementum, and you choose "No" in this dialog, and choose another torrent from the results, the Resume dialog doesn't show up if you choose a different torrent.
