### ISSUE TITLE
MPAA not showing

### ISSUE THREAD

**Issue by matke-84** [elgatito/plugin.video.elementum#662]
@elgatito There is definitely something wrong with MPAA. I tried some other skins not only titan bingie mod (Aeon nox Silvio, Amber, both kodi official) and it doesn't work. Installed kodi from scratch, reinstalled everything and nothing. I also asked some friends to try it, same situation. Maybe this will help you. When I turn on the option in the elementum "Use Trakt Information in Trakt lists" MPAA displays without any problems, of course everything else is lost (fanarts). But look at how you set up the MPAA for the trakt so maybe that's the solution for the problem. MPAA is the basic information, as well as the duration, realise date... it should not cause so many problems. I would be very grateful if you could solve this problem. Thanks in advance.
P.S. Sorry please I don't know if you see messages on closed posts.

**Comment by elgatito** [comment]
@matke-84 

First, there are lists of Movies/Shows that come from Trakt, and when you enable setting "Use Trakt Information in Trakt lists" - you will see only information, provided by Trakt. In TMDB lists, or without enabled setting, you will see only information from TMDB. You cannot mix Trakt and TMDB information. 

If you believe there is information on TMDB, that you don't see in Elementum you need to provide:
1) Link to Movie/Show on TMDB, which has MPAA, for your Kodi region, you expect to see in Kodi.
2) Proper Kodi log.

I will not search anything, or try to guess what you talk about.

**Comment by matke-84** [comment]
@elgatito I did not change the region. It remained the default, no mpaa. I try to change regions and it doesn't work with any of them. With tmdb helper I get mpaa, with local scraper I get, with elementum no. Not for a single movie or tv show, in a few skins, I only get in aura mode skin. It’s the only skin I’ve tried and it works. It is impossible that he is valid and the others are not. I noticed something, I don't know if it has an impact. I don't understand very well all this, so I'm sorry if I'm wrong.
Part of your trakt code says the following:
`MPAA:          movie.Certification`
https://github.com/elgatito/elementum/blob/0d8f17ff9f54ab7024e1dad2c381343f8d20e2d6/tmdb/movie.go#L447
And the tmdb code you changed a couple of days ago stands:
`MPAA:          movie.mpaa()`
https://github.com/elgatito/elementum/blob/0d8f17ff9f54ab7024e1dad2c381343f8d20e2d6/trakt/movies.go#L672
I’m just saying that something isn’t right and I believe I’m not the only one who isn’t being shown this but maybe no one has noticed so far. I similarly tried to explain to you about fanarts and until someone else reported the problem you didn't react. Maybe is problem with me is that I don't know how to explain. Please don't get me wrong I'm just trying to draw your attention to things that aren't working properly. I also want like you to make the elementum work as well as possible for everyone. Sorry if I offended you in any way.

**Comment by elgatito** [comment]
You have spent time for writing things you dont understand, instead of doing what I asked.

**Comment by matke-84** [comment]
https://www.themoviedb.org/movie/464052-wonder-woman-1984

https://www43.zippyshare.com/v/00jnteDQ/file.html

Is this ok?

**Comment by matke-84** [comment]
@elgatito This is kodi log from my computer. The previous one is from Android Box.

https://easyupload.io/2ymaqa

**Comment by elgatito** [comment]
@matke-84 both logs are fine. You have chosen "en_gb" region in Kodi? I see the language, but I do not see the region in the log file.

**Comment by matke-84** [comment]
@elgatito Are we talking about these settings?

![language](https://user-images.githubusercontent.com/74268331/103213863-39eb6f80-490f-11eb-9499-45c8dc299b14.jpg)

I love English even though it’s not my language. I change the date format, temperature data... but I always leave the region and language English. But I tried my region and language as well but I still don't get mpaa. I clear tmdb, trakt cache several times. Nothing.
Tried on multiple computers and android devices.

**Comment by elgatito** [comment]
@matke-84 Yes, this region. So you use en_GB for you Kodi's. I have enough information for the moment.

**Comment by matke-84** [comment]
@elgatito Also I uses en_us. So you can add too, I would be grateful.

**Comment by matke-84** [comment]
@elgatito Happy new year my friend. I wish you all the best. To keep doing such good things as elementum and even better. Just one short question. Is there any progress in my request for mpaa? Thanks in advance and one more all the best in 2021. :-)

**Comment by elgatito** [comment]
@matke-84 Nothing was done and I have no estimations if it would be fixed, or when.

**Comment by matke-84** [comment]
@elgatito OK. I still hope you find some time to sort this out. Thank you in advance.

**Comment by elgatito** [comment]
@matke-84 
Please, try with 0.1.65.

**Comment by matke-84** [comment]
@elgatito It works. And it's great that mpaa came out at the beginning of the movie. Thanks.
