### ISSUE TITLE
Error in source selection found

### ISSUE THREAD

**Issue by veniciusgp** [elgatito/plugin.video.elementum#663]
![1](https://user-images.githubusercontent.com/35663151/103173061-05a48000-4837-11eb-8541-d70601351eee.png)

![2](https://user-images.githubusercontent.com/35663151/103173064-0c32f780-4837-11eb-9ecf-4d92523e8ba5.png)

When selecting a source, the following error is occurring.

'wrapped_class_ListItem' object has no attribute 'setCast'

Test environment

Elementum 0.1.64
kodi 16.1
Android 5.1.1
Brazilian Portuguese language

https://paste.kodi.tv/ehovoxobaf.kodi

Note: This problem did not occur in version 0.1.62

Regards

**Comment by elgatito** [comment]
@veniciusgp Please, try with 0.1.65.

**Comment by veniciusgp** [comment]
> @veniciusgp Please, try with 0.1.65.


Hi @elgatito 

In version 0.1.65 no source is found

![WhatsApp Image 2021-01-09 at 10 58 17](https://user-images.githubusercontent.com/35663151/104093537-d98ef300-5269-11eb-98a9-4ef741e26110.jpeg)

Note: I did not update version 0.1.64 to version 0.1.65. I uninstalled version 0.1.64 and installed version 0.1.65

Elementum Burst update to version 0.0.55

https://paste.kodi.tv/pecisajise.kodi

Regards

**Comment by elgatito** [comment]
@veniciusgp your burst configuration cannot find any results for requested item. There is no error with Elementum.

**Comment by veniciusgp** [comment]
> @veniciusgp your burst configuration cannot find any results for requested item. There is no error with Elementum.

Hi @elgatito 

Why doesn't this problem happen with version 0.1.62 without changing any settings in Burst?

**Comment by elgatito** [comment]
@veniciusgp It can be because in last versions language detection was fixed, so previously, Burst probably used english names, now it uses spanish/portuguese names. 
Enable setting to use original names for searching.

**Comment by veniciusgp** [comment]
> @veniciusgp It can be because in last versions language detection was fixed, so previously, Burst probably used english names, now it uses spanish/portuguese names.
> Enable setting to use original names for searching.

Hi @elgatito 

I changed the setting in elementum to use the original names in the search according to your tip

Now several sources are being found but when selecting one the following error is occurring

Failed to convert to input type to either a std::string or a std::vector<(XBMCAddon::xbmcgui::InfoLabelStringOrTuple)>

https://paste.kodi.tv/puqevecafi.kodi

Regards
