### ISSUE TITLE
[Bug] Torrent is gone after restarting Kodi (Using Context Menu: Download)

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#666]
This bug regarding to the "Elementum Download" option in the Context menu.
After restarting Kodi, the torrent that was downloading is gone.

## Steps to Reproduce (for bugs)
1. Set Elementum for "Use Memory".
2. Choose an item to play (Here for example it's "Alita")
3. Open Context menu and select "Elementum Download".
4. Wait for a whille (You can see torrent is downloading), then close kodi by "S"->quit.
5. Restart Kodi.
6. Check Elementum Torrents list, the torrent is gone (Thought that the file is still exist in storage)

On the other hand, When I'm using the "Use files" and playing a torrent (Not from the context menu), when I'm closing and restart kodi, the torrent is continue from the point it stopped.
That is what I'm expecting it to behave also here.
It seems that even I select the "Download" option from the context menu, it's still act as "Use memory" regarding closing/restarting kodi.

Kodi debug log:
- Before closing kodi:
Part1: https://paste.ubuntu.com/p/XxMzdFkn9T
Part2: https://paste.ubuntu.com/p/cjHWN6QKv7
- After restarting kodi:
https://paste.ubuntu.com/p/Y7XQbZ62vB

## Your Environment
Elementum 0.1.64
Kodi 17.6

**Comment by burekas7** [comment]
EDIT:

Changing back from "Use Memory" to "Use files" suddenly make the torrents to show again from nowhere. Strange

Kodi log:
https://paste.ubuntu.com/p/2kjb3tBKjt

**Comment by elgatito** [comment]
When you run with memory storage, your torrents are not loaded on startup, because Elementum does not know what storage was used to download it. 
To resume file-based torrents, when running memory storage, Elementum first need to store that information somewhere.

**Comment by antonsoroko** [comment]
@elgatito just curious, would it be possible to load torrents from elementum_torrents directory even when you use memory storage?
theoretically (and as i can see with a quick test) this directory should only has *.torrent files only from "download" action, "play" action creates only *.fastresume file, and then deletes it. 
but there are couple of issues:
1. if you "play" previously "downloaded" torrent - "play" will also delete *.torrent file, so it will be lost (but real data will remain).
2. when you try to start downloaded torrent it actually starts to download it again, but to memory.

so probably it is possible but will require some amount of checks to be added.

maybe you can add more of anticipated issues with this approach?

**Comment by elgatito** [comment]
@antonsoroko we do not have saving of which storage is used for each torrent. When you add torrent - you can choose how to store it. On restart you only have torrent files, that you load into libtorrent, and you don't know if some should not be added automatically.

**Comment by antonsoroko** [comment]
@elgatito 
i meant, considering that this dir will be always empty if you use only mem storage (only play) and non-empty when you do download with mem storage (b/c internally elementum will use file storage for this case) - i guess it it safe to load torrents from this dir (and again use file storage even if you have mem storage selected).

alternatively - some kind of mixed storage might be introduced (to make code's logic simplier).

**Comment by elgatito** [comment]
@antonsoroko check latest commit in elementum repository. It should save which storage is used and re-add file based torrents even if memory storage is selected.

**Comment by antonsoroko** [comment]
@elgatito 
interesting approach.

but look like we still would need fixes for:

1. if you "play" previously "downloaded" torrent - "play" will also delete *.torrent file after close, so it will be lost (but real data will remain).
2. when you try to start "downloaded" torrent it actually starts to download it again, but into memory.

also after changing from file storage to mem it deleted all my .fastresume files :-(

also i see that 1 torrent can has `.mem` and `.file` files which also can lead to some errors.
also when i add torrent file via web ui - it creates .mem while in reality it uses file storage. so it not loaded after restart. but adding via context adds it as .file.
i guess /download vs /torrents/add:
1st force usage of file storage  at some point
https://github.com/elgatito/elementum/blob/309f7e43a705767fa78c1e9260dbaf19e698469f/bittorrent/player.go#L189 
2nd explicitly uses storage from settings
https://github.com/elgatito/elementum/blob/309f7e43a705767fa78c1e9260dbaf19e698469f/api/torrents.go#L438

probably this feature will not be a "low-hanging fruit".

**Comment by antonsoroko** [comment]
[panic_add_torrent_mem_after_file.log](https://github.com/elgatito/plugin.video.elementum/files/6511855/panic_add_torrent_mem_after_file.log)

**Comment by antonsoroko** [comment]
[panic_add_torrent_mem_after_file.log](https://github.com/elgatito/plugin.video.elementum/files/6511881/panic_add_torrent_mem_after_file.log)

**Comment by antonsoroko** [comment]
@burekas7 
could you please try this dev build?
[elementum.zip](https://github.com/elgatito/plugin.video.elementum/files/6527238/elementum.zip)

you need to unpack it and replace old elementum binary (with stopped kodi).
i guess the path in windows will be:
`C:\Users\YOU\AppData\Roaming\Kodi\addons\plugin.video.elementum\resources\bin\windows_x64\elementum.exe`

thanks.

**Comment by slavatyn** [comment]
Have same ussue, i try dev build, now torrents don't deletes and works good after restart, but button "elementum download" gives error "coud not find TMDB entry for requested kodi item 'some numbers' of type"

**Comment by antonsoroko** [comment]
@slavatyn log file plz
also which version of context.elementum you use? should be not less than 0.0.6

**Comment by burekas7** [comment]
> @burekas7
> could you please try this dev build?
> [elementum.zip](https://github.com/elgatito/plugin.video.elementum/files/6527271/elementum.zip)
> 
> you need to unpack it and replace old elementum binary (with stopped kodi).
> i guess the path in windows will be:
> `C:\Users\YOU\AppData\Roaming\Kodi\addons\plugin.video.elementum\resources\bin\windows_x64\elementum.exe`
> 
> thanks.

Yes, it's working :)
On step 6, torrent is restore from where it has stopped and continue the downloading and it also show up in torrents list.

**Comment by slavatyn** [comment]
@antonsoroko 
"@slavatyn log file plz
also which version of context.elementum you use? should be not less than 0.0.6"
I use 0.0.6
Yesterday I returned the old elementum file, today I wanted to get the logs, installed dev elementum again, and there are no more errors, everything works as it should! It's strange, yesterday I reloaded kodi, elementum, changed the file-osu settings in elementum, the error did not disappear, moreover, changing to the file mode, the download button did not give an error, as soon as the memory mode was turned on, the error appeared. The only thing I did was restart my computer after 10 days of continuous work. Anyway, everything works now! =)

**Comment by antonsoroko** [comment]
>also after changing from file storage to mem it deleted all my .fastresume files :-(

this is the only thing left to check, i guess.

**Comment by antonsoroko** [comment]
okay, that was fixed by https://github.com/elgatito/elementum/pull/48

so i guess we can close this issue right after new release.

**Comment by antonsoroko** [comment]
@burekas7 could you please close this issue?

**Comment by antonsoroko** [comment]
@burekas7 could you please close this issue?

**Comment by burekas7** [comment]
@elgatito @antonsoroko 
Why I don't see the "Elementum Download" option in the context menu?
Has it changed?

**Comment by antonsoroko** [comment]
@burekas7 install "context.elementum" addon.

**Comment by burekas7** [comment]
@antonsoroko 
Oh I see, it was merges into "Elementum menu..."
In the past it wasn't like that.

And what do you meant "file storage"?
The bug was related to the mode of "use memory" and using the "Download" feature.

**Comment by antonsoroko** [comment]
>And what do you meant "file storage"?

"Use files" maybe. i do not remember the name but logic is obvious. file vs memory.

>The bug was related to the mode of "use memory" and using the "Download" feature.

and i fixed it 2 years ago.
and you confirmed that it worked - https://github.com/elgatito/plugin.video.elementum/issues/666#issuecomment-846582868

**Comment by antonsoroko** [comment]
@burekas7 

>And what do you meant "file storage"?

"Use files" maybe. i do not remember the name but logic is obvious. file vs memory.

>The bug was related to the mode of "use memory" and using the "Download" feature.

and i fixed it 2 years ago.
and you confirmed that it worked - https://github.com/elgatito/plugin.video.elementum/issues/666#issuecomment-846582868

**Comment by burekas7** [comment]
@antonsoroko 
1. You can use the "Download" option on both modes (Use Files, Use Memory)
2. The bug that was mentioned here is fixed.
3. There is **another/new issue** with the "Download" option.
When I choose "Download" it shows the "Playback failed" dialog which should not be shown.

**Comment by antonsoroko** [comment]
@burekas7 

>When I choose "Download" it shows the "Playback failed" dialog which should not be shown.

to be honest, i do not remember we can fix it, but please create a new issue and close this one.

**Comment by burekas7** [comment]
A new issue has been opened
