### ISSUE TITLE
Elementum crashes on startup

### ISSUE THREAD

**Issue by mirkorm** [elgatito/plugin.video.elementum#667]
Hello,
It's a couple of months Elementum is crashing on startup for no apparent reason, during the time since it first happened I've usually bypassed the problem by updating the elem. addon through the elem. repo (even if the version was the same one I already had installed on kodi). Lately though not even updating helped and it just keeps crashing.

elem vers: 0.1.64
kodi vers: 18.9 leia
sys: windows 10

log: https://paste.kodi.tv/umutetitog.kodi

**Comment by elgatito** [comment]
```
2021-01-01 18:10:39.473 T:371984  NOTICE: [plugin.video.elementum] Binary dir: C:\Users\Mirko\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.elementum\bin\windows_x64, item: C:\Users\Mirko\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.elementum\bin\windows_x64\elementum.exe
2021-01-01 18:10:39.754 T:371984   ERROR: [plugin.video.elementum] WindowsError(2, 'The system cannot find the file specified')
```

Have no idea why addon cannot find binary. Maybe your system removes it.

**Comment by mirkorm** [comment]
Thank you so much, I suck at reading kodi logs. I added the elementum exe on the windows security exceptions and now it works even after various reboots, so I guess win defender was blocking it (strange that it never showed on defender's reports, I'll double check).

**Comment by mirkorm** [comment]
I'm sorry to reopen it but the error reappeared and while I was using it: the audio track of the video I was reproducing started crackling, then I rebooted kodi and got the same error and noticed that the bin folder is completely gone. I don't know if it's a bug or something that has to do with a windows update but I never had this kind of problems with elementum and neither with quasar before that so I'm reporting it to you. I'l try to reinstall elementum and add the whole folder in windows security exception and I'll let you know if it solves the problem. Anyway if anybody has any idea why this happens or if anybody has this problem too they can join in the conversation

**Comment by elgatito** [comment]
@mirkorm If there is no binary here `C:\Users\Mirko\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.elementum\bin\windows_x64\elementum.exe`, then it's still your system, that removes it, or any other program. Elementum is not deleting it.

**Comment by mirkorm** [comment]
Yes, but I'm trying to figure out what's causing it, It's odd that windows defender is doing it because it usually warns me when it blocks or moves something to quarantine so that I can confirm the action or restore the files. It's strange nobody else is experience the issue. Now I'll try to add the whole elementum folder to the exceptions and see if it fixes the problem.

**Comment by iz8mbw** [comment]
An Antivirus?

**Comment by mirkorm** [comment]
Even after adding the whole folder to win defender exceptions, the folder is gone after windows reboot. I checked the protection history of ms def and there's no sign of any threat removed or moved to quarantine and the latest scan report performed on the system reported no threats. I don't have any other third party antivirus so I really have no clue what's deleting it. I'm starting to suspect kodi itself or a bug of some sort, I don't have any other software that automatically deletes stuff.

**Comment by elgatito** [comment]
```
2021-01-01 18:10:53.216 T:386876   ERROR: kod[filetools.rename:311]:  ######## ERROR #########
2021-01-01 18:10:53.216 T:386876   ERROR: kod[filetools.rename:311]:  ERROR when renaming the file: C:\Users\Mirko\AppData\Roaming\Kodi\addons\addon-stable
2021-01-01 18:10:53.217 T:386876  NOTICE: kod[updater.updateFromZip:307]:  Cancellando il file zip...
```

What is that?

> 2021-01-01 18:10:39.473 T:371984  NOTICE: [plugin.video.elementum] Binary detection: [ Source: C:\Users\Mirko\AppData\Roaming\Kodi\addons\plugin.video.elementum\resources\bin\windows_x64\elementum.exe, Destination: C:\Users\Mirko\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.elementum\bin\windows_x64\elementum.exe ]

When Kodi is starting, Elementum is taking the binary, which comes with zip file, copies it to `userdata` directory and then runs it. 
So in your case, it takes file from: 
`C:\Users\Mirko\AppData\Roaming\Kodi\addons\plugin.video.elementum\resources\bin\windows_x64\`
And copies it to:
`C:\Users\Mirko\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.elementum\bin\windows_x64\`

**Comment by elgatito** [comment]
Also try to start Kodi and run elementum binary manually, to see if it dies somehow, or killed by any program.

**Comment by mirkorm** [comment]
kod[updater.updateFromZip:307]:  Cancellando il file zip...
means "deleting zip file" in italian

yes under "C:\Users\Mirko\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.elementum\bin\windows_x64\" I found the elemenutum.exe

Another thing I noticed that might mean nothing but it's odd is that every time I install elementum, and I accept to install bursts it gives me an error so I have to install elementum from the zip file again (without uninstalling the elementum I've just installed) and only then it manages to install burst automatically when it asks me

Thank I'm trying to run the exe manually and see what happens, I'll report back

**Comment by mirkorm** [comment]
If I try to run it manually from the folder with kodi running it still doesn't appear on the task manager and it still tells me that elementum has crashed.

I've tried with an older version too I still had but the error still persists (ver 0.1.62)

**Comment by mirkorm** [comment]
This is the error it gives me when I try to let it automatically install burst on first elementum install https://i.imgur.com/JILzxCP.png
And I notice that on the first install the elementum repository is disabled by default, but when I bypass it by redoing the install from the zip it enable the repository and manages to install burst

**Comment by mirkorm** [comment]
And regarding `ERROR: kod[filetools.rename:311]:  ERROR when renaming the file: C:\Users\Mirko\AppData\Roaming\Kodi\addons\addon-stable`
 I'm check but I don't have an addon-stable folder under C:\Users\Mirko\AppData\Roaming\Kodi\addons\ (and yes I have show hidden files enabled) so that's another odd thing I'm going to check

**Comment by elgatito** [comment]
> If I try to run it manually from the "C:\Users\Mirko\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.elementum\bin\windows_x64" folder with kodi running it still doesn't appear on the task manager and it still tells me that elementum has crashed.

Just open console (cmd) and start the binary after you started Kodi.

**Comment by mirkorm** [comment]
I've uploaded a log where I've installed elementum (after having uninstalled elem, burst, the repo and having restarted kodi).
This time around burst installed on the first attempt with no error (don't know why) but still no bin folder under C:\Users\Mirko\AppData\Roaming\Kodi\addons\plugin.video.elementum\ and no process on task manager.
So maybe we can see where it is installing elementum and what is happening during the installation process

https://paste.kodi.tv/ulumivupir.kodi

**Comment by mirkorm** [comment]
Ok, I'm going to try to run it from cmd (anyway I've noticed that when I start it from the exe file the prompt quickly opens does something and closes in a metter of a second but nothing happens

**Comment by mirkorm** [comment]
I'm unable to test more because with the last installation I did to show you the log is working after reboot, but from previous recent attempt I think tomorrow, if not this evening I'll get the error back and be able to see if it works if I launch from the command prompt

**Comment by mirkorm** [comment]
Yes, as expected it already stopped working.
I tried launching elementum from the prompt and this is what it said: https://paste.kodi.tv/epuvuleleh.kodi

**Comment by elgatito** [comment]
@mirkorm that is different, it cannot stop the process from the lockfile. You can remove the lockfile manually and restart Kodi: 
`C:\\Users\\Mirko\\AppData\\Roaming\\Kodi\\addons\\plugin.video.elementum\\.lockfile`

**Comment by elgatito** [comment]
@mirkorm let me know if it again starts to give errors about that. There were changes in the last version about lockfile, so if new lockfile will throw you errors again - let me know.

**Comment by mirkorm** [comment]
Yes, I've started kodi a few minutes ago and elementum crashed again on startup, so I closed kodi, deleted the lockfile and started kodi again and so now elementum is back working.

**Comment by elgatito** [comment]
@mirkorm Please, try with 0.1.65.

**Comment by mirkorm** [comment]
I wanted to inform you that these days it's working with 0.1.64 too without having to delete the lockfile! I'm updating elementum and let you know if anything goes wrong.

**Comment by mirkorm** [comment]
It's several days that it's working without issues so I guess it's safe to say that the problem is solved, thank you so much
