### ISSUE TITLE
First of all i want to thank the developper of this fantastic addon , for me it's the best kodi addon ever. I have a problem with Yggtorrent provider for me it's very important to get it working daily cause i depend on French language content, this provider work for me like one day and the day after it goes down and it finds no links for several days or weeks, for no reason, it come back to work suddenly and then goes off again, when i use the website with my account it works on the browser i don't know what is the problem and what can i do to fix it .

### ISSUE THREAD

**Issue by Fodoli** [elgatito/plugin.video.elementum#668]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

**Comment by elgatito** [comment]
Please, do not use issue title for describing the issue.

Questions, related to providers, should be placed into Burst repository, not Elementum.

Yggtorrent is using coudflare defense, which is not passing Burst, there is nothing to do with it, at the moment.
