### ISSUE TITLE
Low speed torrent

### ISSUE THREAD

**Issue by veniciusgp** [elgatito/plugin.video.elementum#67]
Dear Friend

I am facing low speed torrent problem. It oscillates between 100 and 300 kbps. When I use the quasar with the same file I get the maximum speed of my connection in a few seconds. Does not the elementum use the same torrent client in relation to the quasar? I tested NMAP and Memory download and in both I got the same problem of slow download speed.

The problem occurs on both windows and android and elementum 0.0.32

**Comment by elgatito** [comment]
No, Elementum is using another torrent engine.

**Comment by veniciusgp** [comment]
And can you tell why the download speed when I use elementum is very unstable relative to the quasar? Is it a known problem?

Best regards

**Comment by elgatito** [comment]
As a welcome message says, you should provide kodi.log.

**Comment by veniciusgp** [comment]
[geostorm.2017.elementum.txt](https://github.com/elgatito/plugin.video.elementum/files/1649990/geostorm.2017.elementum.txt)
[geostorm.2017.quasar.txt](https://github.com/elgatito/plugin.video.elementum/files/1649991/geostorm.2017.quasar.txt)

As requested follows the logs

With the quasar in a few seconds I got the most out of my connection at download speed (4000 to 5000kbps). With the elementum the download speed was between 100 and 400kbps.

**Comment by veniciusgp** [comment]
Debug level logs
[geostorm.2017.elementum.txt](https://github.com/elgatito/plugin.video.elementum/files/1650018/geostorm.2017.elementum.txt)
[Uploading geostorm.2017.quasar.txt…]()

**Comment by elgatito** [comment]
Also can you do the following:
1) Try to disable Upnp/NAT in Quasar and try that torrent. To see if get a difference.
2) Open download in Elementum and go to http://IP_KODI:65220/info , it will print torrent engine status, can you copy it somewhere? (ok if you paste it here). 

With memory storage you also get a very low speed?

**Comment by IkenHuub** [comment]
I have the same issue. #following

**Comment by elgatito** [comment]
@IkenHuub so you can also do what I asked for.

**Comment by IkenHuub** [comment]
I will certainly do that later today when I'm at home. :)

**Comment by Bloodhunter4rc** [comment]
I had the same issue when using file storage, somehow i think the memory storage option "Use x mb" is related to how fast it downloads, i set the storage to memory changed memory size to use to 9999999999999 and then changed back to file storage,  and now its incredible fast after doing this , normally this shouldnt effect it at all i guess.

**Comment by susobaco** [comment]
I also experienced the same thing yesterday, with the update to the latest version, the speed dropped a lot. As soon as I can, I'll run the tests you comment on.

**Comment by elgatito** [comment]
It's related to torrent library update. You can revert to 0.0.34, while fix comes in place.
I'll make a new version as soon as it's fixed in the library.

**Comment by ziiky** [comment]
Hello
I have the sam problem like these guy.
My quasar works fantastic ... I get full DL speed after few seconds, also quasar upload files what I can see when I hit pause.
But on other hand, Elementum throttling on 10% of my full speed and I cant get elementum to upload!!!
I tryed to manually open ports on router and portforward them but that didnt help.
I thing that upnp dont work and eementum cant comunicate with router... 
I can see on my router (fritzbox) when quasar open ports, but ehen I start elementum ports do not open.
I use libreelec on nexbox a95x

**Comment by ziiky** [comment]
I will upload short video in a min!

**Comment by elgatito** [comment]
Are you reading before writing?

```
It's related to torrent library update. You can revert to 0.0.34, while fix comes in place.
I'll make a new version as soon as it's fixed in the library.
```

**Comment by ziiky** [comment]
Yea I read! Do U? :)
I said that I have this problem with old versions too ;)

**Comment by NeoCro44** [comment]
I'm having same issues and like 100 more people on my facebook page
This issue is present from day one
Try use same torrent in utorrent and ull get full speed while in elementum max up to 3000 kbps

**Comment by syneox** [comment]
@elgatito 

I was writing about this low speeds since your first versions of Elementum but you told me it is Android specific. Now I see that people on another systems are also having this problem. Elementum download speeds can't compare with Quasars.

Is it possible to build Elementum with Quasar libtorrent-go library instead of the one you are using in Elementum and can you tell us some resons behind using anacrolix libraries?

**Comment by elgatito** [comment]
@syneox you can fork this project and make what you want. 
I would not migrate to any other torrent library. If you like Quasar then you should use it.

**Comment by elgatito** [comment]
@NeoCro44 , can you try the latest 0.0.36? Few issues were fixed in torrent engine.

**Comment by NeoCro44** [comment]
Im seeing now some improvments about speed
Now is around 4000 kB/s
But now im having issue about wrong sources
When u try browse vikings, shameless or blindspot u get results for uk voice and some random tv shows from eztv

**Comment by NeoCro44** [comment]
I just tried black list and so.e other tv shows
It keeps random sources from eztv with no proper sources

**Comment by elgatito** [comment]
Would be good if you send any log. But it is probably because of Burst, probably you have non-English language in Kodi?

**Comment by NeoCro44** [comment]
Yep Croatian

**Comment by NeoCro44** [comment]
It seems very buggy
I just watched 2 tv shows (the one i could searc for) and now elementum keeps loading them
I deleted them manualy but now they are still loading at 0%
And i cose to delete files after i finish watching but they allways stay undeleted
I was deleting them manualy

**Comment by elgatito** [comment]
No log = no help.

**Comment by NeoCro44** [comment]
https://paste.ubuntu.com/26477134/

**Comment by ziiky** [comment]
Why closed?
Speed is still poor, its not constant like in quasar, jumping up and down.
Elementum still do not upload/seed. 
After last update to verz.0,0,36 video play stucking non-stop.

[kodi.log](https://github.com/elgatito/plugin.video.elementum/files/1671220/kodi.log)

**Comment by elgatito** [comment]
Closed because:
- Issue is about low download speed, which was fixed in 0.0.36, comparing to 0.0.35.
- Download is done with torrent engine, this plugin does not influence it.
- If you find any problems - you should create an issue, if there is none for your problem.

**Comment by ziiky** [comment]
hmmm did u try to compare dl speed with quasars? 
With quasar I get 100% of my bandthwidth every time but with elementum I get max 30%...  if I have luck

**Comment by ziiky** [comment]
I do not see that elementum conects to peer hive; maybe that affect in achiving max speed?!

**Comment by elgatito** [comment]
> Download is done with torrent engine, this plugin does not influence it.

**Comment by NeoCro44** [comment]
Every time i upload log file u close thread
U done that and in other thread

**Comment by elgatito** [comment]
> Issue is about low download speed

You should use proper issue for each problem.

**Comment by NeoCro44** [comment]
Poteto potato same thing

**Comment by susobaco** [comment]
Hi, it looks like you've improved a bit since the upgrade to 0.036. Even so, the velocity drops too much suddenly, and goes back up again, it's not constant. Attachment log.
[info_elementum.txt](https://github.com/elgatito/plugin.video.elementum/files/1671442/info_elementum.txt)

**Comment by elgatito** [comment]
For memory storage or file?
