### ISSUE TITLE
[Request] Up Next :  load next episode from Trakt Progress

### ISSUE THREAD

**Issue by JacopoV** [elgatito/plugin.video.elementum#671]
Hi @elgatito ,

since i've updated to 0.1.64, i noticed from the changelog, you made the initial integration for Up Next, which works great if i play a specific episode within the season view ( basically, you have the list of all episodes, i guess as playlist).

However ( not sure if it's possible at all ), if i play an episode from the Progress section of Trakt ( basically, you're next episode  to be watched), Up Next is not connecting to the next episode, by saying the playlist is empty. 

Do you think it's possible and easy to implement/fix ? If not, really don't bother. :)

Thanks again for your time and happy new year.
PS : is the donation link still connected to you right? 

Many thanks

**Comment by elgatito** [comment]
@JacopoV Please, post the log file with log level DEBUG for Elementum and DEBUG for UpNext. (Where you start something from progress and scroll to the end).

> PS : is the donation link still connected to you right?

Yes.

**Comment by JacopoV** [comment]
Here's the log : http://paste.kodi.tv/paveroxogu

Let me know if there's everything to pin point the issue. I quickly look inside the log for the error prompted from Aura "can't find the next item to play" but i can't  find that. I wonder where is printed...

Thanks again

**Comment by elgatito** [comment]
@JacopoV In the log I see playback of Vikings 11th episode, then Upnext auto-selected next episode, then after 12th episode Upnext failed to switch to 13th episode?

**Comment by JacopoV** [comment]
Well, yeah. 

This is the scenario : 

- playing Vikings e11
- about the ending, Next Up asks about e12
- confirm e12
- error and back to home ( no visible sign of e13 except log file)

This happens if you have,  or not, the file for episode 12. Not only Vikings, i see this behaviour with all shows if played from Trakt Progress.

As mentioned, the scenario works great from the season view :) 

Thanks

**Comment by JacopoV** [comment]
Well it's kinda correct.

Elementum was finishing playing Vikings s06

**Comment by JacopoV** [comment]
@elgatito i think it's all about  the playlist, and it might not be even possible to implement/fix it. 

If I run an episode from the season list, the playlist is  generated with all the episodes. 
So Up Next can move to the next episode without any trouble.

If I run an  episode from the progress Trakt, the playlist only has one element in the list,  the current episode selected. 
Then Up Next tries to look for the next in the list, but it's not there. 

I don't think there's an easy way to have it working, unless creating a temp playlist having the current episode, that's about to finish, and dynamically adding the next one. 
But then, I'm not sure how could be handled if the file is not downloaded yet from Elementum. 

That could might explain why, still playing from progress Trakt, it seems that Elementum is not downloading the next episode automatically (with the flagged option active), compared to have it played from the season list ( so i guess it does have the full playlist) in which is actually buffering the next episode  while watching the one you want.

**Comment by elgatito** [comment]
@JacopoV Could not reproduce. But I ran it with beta version of Upnext, so maybe it differs from release version. You can try it: https://github.com/MoojMidge/service.upnext

**Comment by JacopoV** [comment]
@elgatito Mmm interesting .. I m using  1.1.4 (release).
Just to  show you the issue (at this point, it might not be Elementum to be honest) : https://gofile.io/d/f1tOPP

Don't know how to install a beta version, unless is a zip file as dependency. 

:) thanks for looking into.

**Comment by elgatito** [comment]
@JacopoV you can probably try to download the zip and install directly to Kodi - https://github.com/MoojMidge/service.upnext/archive/master.zip

I've seen these playlist errors, but I'm not sure I see them with this new version.
Try and test it.

**Comment by JacopoV** [comment]
@elgatito i tried the zip  you linked, but it didn't work. It could be due the skin maybe? how's handling playlists ?

**Comment by JacopoV** [comment]
@elgatito oddly, with a new fresh install ( starting from a backup i've without anything more than elementum ) i installed Up Next, and in the season view, with all episodes, it's not showing at all. I guess something in off in general with Up Next at this point. Not sure. Both release version and the beta zip. 

For now you can drop looking into till i figure out why isn't showing in the way that used to work. 
I ll poke you if i can resume  the old working behaviour

Thanks :)

**Comment by JacopoV** [comment]
@elgatito so I managed to get it working in the episode list from the season. I had to turn on the options in Next Up "available on playlists" (default is off, dunno why).

Sadly still doesn't work if the episode is played from the trakt progress widget from the home. =(

**Comment by elgatito** [comment]
@JacopoV It does not matter from where you started playback. If you play specific episode and there is next episode, then Elementum is sending information about it to UpNext.
Current UpNext version does not always correctly process active player information, that is why it does not show notification and does not switch to the next episode.

It would be good if you could make a log file with Debug levels in UpNext and Elementum, to see if UpNext just aborts notification or they are not sent to Upnext.

**Comment by JacopoV** [comment]
@elgatito Sure, i ll try later today :) thanks

**Comment by JacopoV** [comment]
@elgatito got a change to give it a go again. Both Kodi log, Next Up debug, Elementum debug : http://paste.kodi.tv/qecuyamena

Thanks

**Comment by elgatito** [comment]
@JacopoV Hard to say. No errors in the log. UpNext tried to notify you about next episode. I guess you pressed confirmation before episode finished, but still just got to the list of episodes?

Is there any setting in UpNext to define way to work with playlists? It probably should not append the playlist, just trigger a new playback.

**Comment by JacopoV** [comment]
@elgatito in every test I press the confirmation to move to the next episode, before the time expires.

From a Trakt progress widget : goes back to home with the error 
From the list of episodes from season : moves to the next one correctly as Elememtum would do by itself (like skipping to the end will start immediately the next episode). So it's not going back to the episode list per se.

In Up Next the only reasonable options I could think about are : 
- default action when nothing selected (set as play next) 
- enable on playlists (set as ON, even tho by default is off, so I'm not sure about this)
- include already watched episodes (set as ON)

These are only the ones that are behavior oriented. 

I assume it's on them more than Elementum, so I would say to ignore this and leave it. Must be something else. 

Thanks for the patience and time.

**Comment by JacopoV** [comment]
Hi @elgatito , i ll paste here the two logs in case you have time/want to do a comparison (if there's any difference at all at this point):
- log from Home > Trakt progress widget > http://paste.kodi.tv/iqasoyobim (it didn't work, back home with playlist error)
- log from episode list > http://paste.kodi.tv/coqesasaso (it worked, stayed in the player, elementum buffer UI came up and proceed to the next episode flawlessly)

Extra info :
- using Aura Mod skin (maybe something is off there)
- using Up Next master beta (the one you sent me and seems working for you)

It might be just an issue with Up Next to be fair. It seems not working all the time even from the episodes list (not appearing at all).
It's not the end of the world tho, so if you can't spot anything or similar, feel free to close this ticket. 

Cheers and thanks again.

**Comment by elgatito** [comment]
@JacopoV All Elementum can do is to send information about next episode. And that is done, but somehow it cannot switch to play next episode.

**Comment by JacopoV** [comment]
@elgatito It's okay, must be something else.  Thanks for looking  into!  Really appreciated :)
