### ISSUE TITLE
[Bug] Wrong fanarts for the seasons in TV shows

### ISSUE THREAD

**Issue by matke-84** [elgatito/plugin.video.elementum#672]
@elgatito I found one very annoying bug. When we enter into tv shows and then into the seasons the wrong fanarts appear. It's about the following. If there is no poster for a season or much more often a season thumb fanart usually randomly takes a poster or season thumb from another season, usually the first.
Example for season posters
![Screenshot_20210110-101059](https://user-images.githubusercontent.com/74268331/104119003-06f0a500-532d-11eb-92ed-b5392ab03ead.png)
Here you can see that the last two posters for season 32 and for specials are shown as the first season.
Example for season thumbs
![Screenshot_20210110-101207](https://user-images.githubusercontent.com/74268331/104119049-5636d580-532d-11eb-9b25-41c915f4f297.png)
There is a much bigger problem here. Unlike the posters where it appears somewhere, this appears in almost every tv shows. The Vikings tv show has only one season done on fanart.tv (second season) and on the example you can see that it shows all seasons as the second.
The problem here is that season thumbs are rarely made for TV shows on fanart.tv. Posters made more often and that's why we have a problem in some places, unlike season thumbs. This appears in all skins, titan bingie mode skin is just an example.
Is there a possibility that where it does not find a season poster or season thumb, it displays a tv poster or tv thumb? I think it's much better to show it that way than to show season 1 for season 32 and specialas or for all seasons to be seasaon 2 like on example.

**Comment by elgatito** [comment]
@matke-84 Try with 0.1.65.

**Comment by matke-84** [comment]
@elgatito That's it. It looks much better. But you only did it for the posters, i think you forgot the landscape images that made me write this post. Can you do same fix for landscape images as well? Thank you in advance.
![Screenshot_20210115-182656](https://user-images.githubusercontent.com/74268331/104758907-63095e00-575f-11eb-827f-12f2638f8cbb.png)

**Comment by matke-84** [comment]
@elgatito Hi. I see a new update has come out but there is still the same problem with landscape images. Can this be sorted out?

**Comment by elgatito** [comment]
@matke-84 I have no plans of changing it. And I don't see any problem there.
First you complained that there are no arts for specific items. 
Now you complain that we select Non-seasoned items from TVShow for seasons where we have no arts.

Code is open, you can make changes and propose them.

**Comment by matke-84** [comment]
@elgatito No, no. You didn't understand me. Everything is ok. That's what I asked for and I don't complain about it. I just pointed out that it show instead of where there is no landscape image for the season it throws out specials, instead of non season image. With the posters everything is ok. Just do the same with landscape pictures as well. I said that in the previous post for the tv show The Walking Dead, but you didn't understand what I wanted to say. Thanks in advance.
![specials](https://user-images.githubusercontent.com/74268331/106766094-ce956b80-6639-11eb-8906-8645d5da7778.png)
![333](https://user-images.githubusercontent.com/74268331/106768170-f554a180-663b-11eb-8223-471882d0ed21.png)
![333](https://user-images.githubusercontent.com/74268331/106768065-d9e99680-663b-11eb-8a1e-5417679c5fff.png)

**Comment by matke-84** [comment]
> Code is open, you can make changes and propose them.

OK. Tell me if this is the solution for the problem.
https://github.com/elgatito/elementum/blob/2e8e6ecfdb8e72c1a0f7e23071203420b5b6a495/fanart/fanart.go#L411
https://github.com/elgatito/elementum/blob/2e8e6ecfdb8e72c1a0f7e23071203420b5b6a495/fanart/fanart.go#L428
`Landscape:    GetBestShowImage("", old.Landscape, fa.SeasonThumb, fa.TVThumb)`
I saw that you made this changes for posters in version 0.1.66 (with some other changes). Posters with this modification work, would this fix landscape images as well?
Sorry in advance, I'm not an expert for kodi addons programing, I'm just trying to find a solution for this bug.

**Comment by elgatito** [comment]
@matke-84 Fanart does NOT have separate lists for Show and Season items. They all come in same list.
Specials have "season=0" same as Show arts. There is no way to divide them.

**Comment by elgatito** [comment]
@matke-84 I will not spend time on this. So you can close it or wait when someone will try to do what you want.

**Comment by matke-84** [comment]
@elgatito Please sorry. Just one more question. Why if you set the season=0 and if you set it to display non season images, it shows images of specials, that are part of the season? Why does it work with posters and not with landscape images?

**Comment by matke-84** [comment]
@elgatito What can I tell you, except one thing, thank you so much. :-)
