### ISSUE TITLE
[Request] Mark watched - Sync Also With Trakt

### ISSUE THREAD

**Issue by JacopoV** [elgatito/plugin.video.elementum#673]
Hi @elgatito ,

at this point you will most likely hate me and i get that :) . 
I'm trying to setup the dev env to work on Elementum so i can start trying with some code changes etc, also because i want to learn something new. 

But back on the request (don't like this word.. i'm not really requesting.. i m not in that position. More like a wish if possible).
Currently Elementum syncs perfectly with Trakt.tv for :
- mark as watched (toward the end of the movie/show)
- add/remove to watchlist
- add/remove to collection

As far i seen, by looking and browsing, the mark as watched is only flagged as that in Kody library, but  it's not sending the information to Trakt. And I guess it's all connected to an ID from the DB handling the lists, so..

Would be possible to use the same API and content (movie/show) ID from the above current working scenarios, to send the flag to Trakt.tv when marking "as watched" ? 

Thanks again :)

**Comment by elgatito** [comment]
> As far i seen, by looking and browsing, the mark as watched is only flagged as that in Kody library, but it's not sending the information to Trakt. And I guess it's all connected to an ID from the DB handling the lists, so..

> Would be possible to use the same API and content (movie/show) ID from the above current working scenarios, to send the flag to Trakt.tv when marking "as watched" ?

I don't understand this.

Elementum is syncing watched state of Kodi items to Trakt and from Trakt to Kodi library.
If something is not working for you - you can try to reproduce it, show proper log and wait if someone will try to fix it (if there is anything to fix).

**Comment by JacopoV** [comment]
Oh, i see, i thought the Elementum was handling some communications with Trakt.

Basically, if you open the context menu on a movie or show, and click "Mark as watched" it actually flags it as watched in the UI ( and Kodi library, so when you close and reopen Kodi itself, it shows the correct state), but not on Trakt. 
You have to manually do it on Trakt (via website or app). 

I was mainly asking because watchlist and collections they do work ( so the changes are performed on Trakt too), so i thought  it could work too for marking as watched a single movie/show.

Steps :
- Open the context menu on a movie/episode
- Click "Mark as watched"
- Notice the flag UI appearing
- Check your Trakt account
- Notice that's not marked as watched

Log : http://paste.kodi.tv/ilanupotuy

thanks again, sorry for the confusion

**Comment by elgatito** [comment]
> Basically, if you open the context menu on a movie or show, and click "Mark as watched" it actually flags it as watched in the UI ( and Kodi library, so when you close and reopen Kodi itself, it shows the correct state), but not on Trakt.
You have to manually do it on Trakt (via website or app).

Mark as watched, is a Kodi action. If you change watched state of library item - Elementum will sync it. If any other item - Elementum is not able to sync anything.

**Comment by JacopoV** [comment]
Ok, now i do see the limitation. Thanks for the explanation! Nothing than can be done then :) I ll close the issue. Thanks
