### ISSUE TITLE
[Bug] Crash - Deleting Torrent and Files

### ISSUE THREAD

**Issue by JacopoV** [elgatito/plugin.video.elementum#674]
## Expected Behavior
Elementum should let you delete old torrents and file without crashing as 0.1.64.

## Current Behavior
Since 0.1.65, Elementum crashes if trying to delete torrents and file from the add on itself on kodi or using the web interface.

## Possible Solution
n/a

## Steps to Reproduce (for bugs)
Install Elemetum 0.1.65
1. Download few torrents
2. Try to delete multiple torrents + files at once
3. Observe the issue

## Context
Trying to delete old torrents + files. 

## Your Environment

* Version used: 0.1.65

* Environment name and version: 0.1.65

* Operating System and version: Kodi 18.8, Android TV, OS version 9

* Link to Kodi debug log:http://paste.kodi.tv/aciyogepek

Note : the log might now show much due the crash. 
So i can take the log only at restart of Elementum Itself.
I started having this errors since the last update to 0.1.65. Never had any trouble on 0.1.64.

Edit : the UI notifies an error related to Burst, with a connection issue.

**Comment by JacopoV** [comment]
After crashes and crashes, i managed to delete the torrents using Elementum by clearing all the database and cache. Not it seems letting you deleting torrents and file.
I ll report back @elgatito if it happens again.

**Comment by okrisz** [comment]
Same issue here. It is happening since 0.1.65
I cleared the cache but that didnt solve the crashing. I dont want to clear the complete database.

**Comment by elgatito** [comment]
This issue will not be fixed by removing anything.

**Comment by JacopoV** [comment]
@elgatito so far i wasn't able to reproduce the issue. I'll keep using elementum and see if i can spot the "how to" :)

**Comment by JacopoV** [comment]
@elgatito i got the crash again. Instead using Elementum log upload ( maybe due crash cannot do much), i uploaded with another addon : https://ares-project.uk/logupload/log.php?id=279086

I was initially trying to delete the second entry and started crashing every single time. 
Then tried with both 2nd and 3rd entry but nothing. 

<img width="1442" alt="Screenshot 2021-01-14 at 09 40 54" src="https://user-images.githubusercontent.com/1202954/104565475-9effce80-564c-11eb-9139-1070e16a7dba.png">

I hope you can spot something in there.
Many thanks

**Comment by MichaelAndoid** [comment]
Same problem 0.1.65 last update now i cant "Delete Torrent and files",  Elementum has crasched...restarting.

Kodi: 18.9
Android: 7.0

**Comment by JacopoV** [comment]
Maybe this could help to reproduce the bug ( so fai i successfully managed to gain 5 torrents which i can't delete):

- select a source to play
- let the buffer to reach 100% and start playing the source
- click stop
- popup about continue downloading shows up : i click no but it seems not registering the input, to it takes default YES after the 5 sec timeout
- second popup about deleting is not showing up
- try to delete the torrent and files from Elementum addon or WebUI
- if you're "lucky" you can see the bug
- Elementum crashes, often pointing to Burst as URL wrong connectio
- After several failures, Elementum notifies too many crashes  and fully reboot

After i reinstall 0.1.64 (disabling auto update on add ons) and i can successfully delete the torrents and files.

**Comment by MichaelAndoid** [comment]
I cant reproduce the bug on new downloads, ONLY on the 3 olds downloads download with the 0.1.64 version.
Maybe the solution is go to the kodi directory and delete the files .torrent

**Comment by JacopoV** [comment]
Well from a clean slate with 0.1.65 i got 5 torrents i wasn't able to delete. So i don't think is related with torrents coming from 0.1.64.

**Comment by MichaelAndoid** [comment]
> Well from a clean slate with 0.1.65 i got 5 torrents i wasn't able to delete. So i don't think is related with torrents coming from 0.1.64.

Maybe but i cant reproduce yet on new downloads, more 3 or 4 days i have tested more downloads to be sure.

**Comment by elgatito** [comment]
@JacopoV Try with 0.1.65.

**Comment by JacopoV** [comment]
@elgatito well, i 've reported the bug with 0.1.65. On 0.1.64 it actually works perfectly :)

**Comment by elgatito** [comment]
@JacopoV ouch, you are right. Wrong git tag. New version is building.

**Comment by JacopoV** [comment]
@elgatito no problem :) thanks

**Comment by elgatito** [comment]
@JacopoV now available, v0.1.66.

**Comment by JacopoV** [comment]
lemme check, i ve like 9 torrent locked with 0.1.65 :) i ll be back to you soon

**Comment by JacopoV** [comment]
@elgatito it seems working great :) it managed to remove the torrents and files which 0.1.65 wasn't able to 👍  Thanks a lot as usual :)

**Comment by MichaelAndoid** [comment]
> @JacopoV now available, v0.1.66.

Works ok, now i can delete 3 old torrents.
Thanks.

**Comment by JacopoV** [comment]
Well after testing a lot on my end, everything works as it should. And it seems for the other users who reported this issue too.
So thanks again for the fast fix. 

Closing the ticket
