### ISSUE TITLE
failed playback when orion has 0 results

### ISSUE THREAD

**Issue by georgew21** [elgatito/plugin.video.elementum#675]
Hello, there is the following problem.

I am on kodei 18.9 (latest elementu version) and I have installed orion addon for elementum burst. When orion has 0 results for a torrent, then even if the others providers have results, I get an error of failed playback without diplasing the window with results.

Maybe the problem due to the kodi timeout that producing a "playback failed" instead wait more for the results. I have set orion timeout to 20 seconds, burst timeout to 25 secs and elementum video timeout to 30 secs. The notification by orion that has no results coming after 2-3 secs, but i see the notifcation that elementum burst waits more to recieve the results. 

This is a debug kodi log: http://paste.kodi.tv/gupiqoboji
in line 8244 we see that The Pirate Bay returned  3 results in 2.9 seconds, but always there is this problem.

Thanks for any help.

**Comment by elgatito** [comment]
@georgew21 your Elementum is configured to abort waiting after 30 seconds, and Burst waits for 60 seconds. Elementum timeout should be bigger than Burst.

**Comment by georgew21** [comment]
oops! well, I can't find where I have set burst to 60 secs. On burst
settings I had set search timeout to 25 secs and on elementum video
settings I had set custom provider timeout to 30 secs.

Now, I have disabled the custom provider timeout on elementum video
settings and I have also on burst settings enable the auto timeout setting
according to elementum.

But I have exactly same problem.

So could you please explain me how can I change the burst timeout?

Στις Τετάρτη, 13 Ιανουαρίου 2021, ο χρήστης Denis <notifications@github.com>
έγραψε:

**Comment by elgatito** [comment]
> So could you please explain me how can I change the burst timeout?

Change timeout in Elementum to 60 seconds. Set Burst to use Elementum timeout settings.

**Comment by georgew21** [comment]
Thank you. I made the settings as you told me and now it works. 

Although , before i had the setting of burst to 25 secs (and elementum to 30 secs), as it looks from debug the burst for some reason was 60 secs and i had the above problem.

I think this is identical problem with this https://github.com/elgatito/plugin.video.elementum/issues/644 of @burekas7, so maybe there is really a bug. Otherwise, you should close this issue. 

Have a nice day.

**Comment by elgatito** [comment]
Closing, as this is related to Burst, not Elementum.

**Comment by georgew21** [comment]
I just note that I reported this to Orion développer and he fixed with a new update, so now the Orion addon "communicates" properly to burst when there aren't results and we don't need to run timeout.
