### ISSUE TITLE
(bug) elementum crashes after selecting episode from trakt

### ISSUE THREAD

**Issue by georgew21** [elgatito/plugin.video.elementum#678]
I am on kodi Leia and I have latest elementum video addon. 

When I select an episode from a widget on my homescreen (the widget shows trakt progression of TV shows ) elementum starts search, but soon video elementum addon crashes and restarts.

the same happens if try to play an episode from elementum menu - shows - my progress and I think that problem there is for all episodes from trakt (I confirm for episodes for my history) 

If I try again, then whole kodi crashes. 

This is debug log:
http://paste.kodi.tv/lagujaxezu

**Comment by georgew21** [comment]
I note that I have the same problem when searching for all TV shows in my library, too. this is weird.

I tried to clear kodi and elementum cache hut

**Comment by georgew21** [comment]
*I closed accidentally

**Comment by KillerJoeBR** [comment]
I noticed constant crashes while I try playing some videos lately. It was mostly old series so I thought it had something to do with old encode or something.

Anyway I revert elementum to 0.1.65 and so far no crashes

**Comment by georgew21** [comment]
I tried with various older versions (both elementum and burst), but unfortunately no fix.

**Comment by georgew21** [comment]
@elgatito i tried in burst with older settings and the problem is resolved. the changes that i have done recently were about the filter section, i had disable all filters (resolution, keywords etc). 

for some reason disabling all filters have as result the crashing.

**Comment by elgatito** [comment]
Please, try with v0.1.67.

**Comment by georgew21** [comment]
I disabled all filters on burst settings and now works nice without crashing (in previous versions the disabling was causing the crash).

 

Thank you!
