### ISSUE TITLE
[Feature] Burst results indicate the matching file if already started/downloaded

### ISSUE THREAD

**Issue by JacopoV** [elgatito/plugin.video.elementum#682]
First i'd like to kick off saying thanks, and how much i do appreciate the support and further help from @elgatito. 
I'm aware development is stopped, but the constant help and improvements is very nice to see.

As usual i won't mention the word Request, so i put at tag Feature. Feel free, as usual, to rename, add a flair, or close the ticket directly.

Second, i ve notice the great recent changes in Burst, now collecting the same result from different trackers under the same umbrella. It's insane how you can aggregate so many sources with the same file. I didn't know that. It boosts a ton the distribution ratio (especially for bigger files such as 4k).

That, brought me here to mention a possible improvement in the result page from Burst (assuming the UI is handled by Elementum).

The improvement would be :
- Indicate in the result page (list of entries), with a coloured dot or a coloured box around the entry, the local file (the one you are already downloading and you have downloaded) which is matching , by size && name, the entry if self.

Current scenario :
-  Elememtum has a database cleared or lost the .torrent file, so it has no .torrent file connected but it has the file partially or fully downloaded.
- So by clicking the same result (if you remember which one, if not the suggested highlight would be the improvement) would trigger the usual "checking" / "buffering" on the  file itself, before resuming downloading.

Below some mock of what i mean, in case i failed at explaining what i mean :)

![Concept - Highlight Dot](https://user-images.githubusercontent.com/1202954/105007254-07c5bd00-5a38-11eb-8437-f8a7f29bda38.jpg)
![Concept - Highlight Box](https://user-images.githubusercontent.com/1202954/105007258-098f8080-5a38-11eb-8b02-cbe381b560e6.jpg)

In the mock above, the first entry is matching the same filename and size from the file in your local storage, but it has no torrent file. By clicking on that, i will start the "checking" phase before resuming.

## Your Environment

* Version used: Kodi 18.9

* Environment name and version: 0.1.66

* Operating System and version: Android TV, OS 9

Thanks for you time and patience.

**Comment by elgatito** [comment]
@JacopoV 
Around half of items in that list of found torrents are only having a magnet, which means we don't know list of files and their sizes.

**Comment by JacopoV** [comment]
Oh i see. i thought because they're displayed in there, with name and size, they could have been compared to the files folder. (the list in the mockup image is a random one i too from internet and edited). 

Well thanks anyways :)

**Comment by elgatito** [comment]
@JacopoV Sizes, names, seed/leech amounts - everything comes from provider's pages, they are usually not accurate.

**Comment by JacopoV** [comment]
Well if they're not accurate, nothing that can be done :) thanks for the explanation :)

**Comment by antonsoroko** [comment]
@elgatito 
>Indicate in the result page (list of entries), with a coloured dot or a coloured box around the entry,

btw, the same idea but for downloaded and existing torrents might be handy: 
1. e.g. when you found and downloaded torrent via search and then found it via trakt (because sometimes new episodes appears in elementum's trakt some time after they available in internet)
2. when you added torrent manually via web page and then used trakt

i mean generally cases when torrent and trakt entity is not mapped atm and then you map them.
