### ISSUE TITLE
[BUG] Failed to play video

### ISSUE THREAD

**Issue by WuYRV** [elgatito/plugin.video.elementum#685]
Hi, need help.
Elementum starts, I can find movie or something, it scraps the torrents, I choose one from the list and get an error message: "can't set attribute" after pop-ups window: Playback failed: "One or more items failed to play" and that's all, nothing else happens. Same thing when load torrent file directly.

## Expected Behavior

Torrent should start buffering and then play video

## Current Behavior

get an error message "can't set attribute" then pop-ups window: Playback failed: "One or more items failed to play" and nothing else happens

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
0.1.66  
* Environment name and version:
Kodi 19 [Matrix] 19.0-0.8.20201207 git8cc9e80 fc33 x86_64  
* Operating System and version:
Fedora 33 x64 (KDE Plasma) (kernel: Linux 5.10.10-200.fc33.x86_64) 
* Link to Kodi debug log:
https://paste.kodi.tv/feqofehoya

**Comment by elgatito** [comment]
@WuYRV Please, change logging level of Elementum to Debug. (addon settings, last tab). And make a new log.

**Comment by WuYRV** [comment]
https://paste.kodi.tv/afenavekal

**Comment by WuYRV** [comment]
Found some python updates in Kodi 19 I think it may be concerned to my problem:
https://github.com/xbmc/xbmc/pull/18345

**Comment by elgatito** [comment]
@WuYRV I can't see any error in the log file. Try also enabling debugging in Kodi itself - http://elementum.surge.sh/contribute/log/#preparation

**Comment by WuYRV** [comment]
I already did :-(

https://paste.kodi.tv/falitijodo

ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.elementum/movie/464052/links/Wonder%20Woman%201984%20%282020%29]

**Comment by elgatito** [comment]
@WuYRV It is not an error, it is a fact.

Try to remove and re-install Elementum and enable DEBUG log level in Elementum settings and enable debugging in Kodi.

**Comment by WuYRV** [comment]
completely removed .kodi folder from users, installed only elementum and enabled both debugs
https://paste.kodi.tv/acocuvenoy

**Comment by elgatito** [comment]
@WuYRV 
```
021-01-28 13:01:49.234 T:15247   ERROR <general>: /home/yrv/.kodi/addons/script.elementum.burst/burst/parser/ehp.py:158: SyntaxWarning: "is" with a literal. Did you mean "=="?
                                                     if attribute is 'text':
```
This can be a problem.

Can you open web page http://192.168.1.3:65220/web/ (replace  IP with the one that run Kodi/Elementum), and add any torrent/magnet there, and see it playback works there.

**Comment by WuYRV** [comment]
It started buffering, but in the end the same :-(
https://paste.kodi.tv/uhenimokuv

**Comment by elgatito** [comment]
```
2021-01-28 13:36:43.238 T:15080   ERROR <general>: CYUVShaderGLSL::CYUVShaderGLSL - failed to open file gl_shader_frag_texture_lim.glsl
```

Still strange output and nothing specific.
You should try Kodi18 then.

**Comment by WuYRV** [comment]
Kodi 18 works great!, I have it on my other computer (fedora 32), but fedora 33 repository has only Kodi 19... so sad. Thank you very much anyway! Maybe with further updates it will be solved.

**Comment by r3dnck** [comment]
@elgatito https://github.com/elgatito/plugin.video.elementum/commit/99aa21fcbb2e9f2afa88d2b289658e0ed2f3823b
This commit should fix the problem

**Comment by WuYRV** [comment]
Yes it WORKS!!! Thank you very-very-very much!
