### ISSUE TITLE
[Small bug] Wrong duplicat "Movies -> Most Popular" category

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#687]
Hi,

There is duplicate of "Most Popular" category in "Movies" category,
When the second one is seems to be wrong and show empty list.

![image](https://user-images.githubusercontent.com/13424257/106766253-5ed7ae80-6642-11eb-9921-61320367ae76.png)

----
Elementum 0.1.67

**Comment by elgatito** [comment]
@burekas7 First one gets from Trakt, second from TMDB. They were always there.

**Comment by ShlomiD83** [comment]
Maybe different them in the title? "TMDB Most Popular" & "Trakt Most Popular"?

**Comment by burekas7** [comment]
> Maybe different them in the title? "TMDB Most Popular" & "Trakt Most Popular"?

@elgatito 

Also with the other categories, mark them which relates to Trakt and which relates TMDB

**Comment by burekas7** [comment]
> @burekas7 First one gets from Trakt, second from TMDB. They were always there.

So why does one of them returns empty list? (I guess is the one of TMDB)

**Comment by ShlomiD83** [comment]
> > @burekas7 First one gets from Trakt, second from TMDB. They were always there.
> 
> So why does one of them returns empty list? (I guess is the one of TMDB)

they both work fine, maybe try clearing your cache.

**Comment by burekas7** [comment]
> they both work fine, maybe try clearing your cache.

Correcrt.
Cleaning the TMDB cache fixed it and it has a content now.

**Comment by burekas7** [comment]
Thanks @elgatito 
Looks great in 0.1.68.

Close.
