### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Azat868** [elgatito/plugin.video.elementum#69]
Thank you for continuing work on the Quasar.

I have some questions:
1. What class of microsd you recommend? To watch movies 1080p  8-15gb?
2. Quasar had problems with external carriers (flash usb). How are things here if you specify the boot path of the external drive? (quasar stopped when buffering to an external drive)

Thank

**Comment by elgatito** [comment]
1. You should not use SD cards at all. They are not engineered for small random writes and will get damaged sooner or later. That is why there is a memory storage. Memory is fine with that usage.
2. If you set a path and you get a message that plugin has started - then it should be fine and plugin can use that path. But you can have small speed or something like that. That is too much individual.

**Comment by Azat868** [comment]
Sorry, but on raspberries, I have nothing but microsd and usb 2.0. You say microcd can not be used. And you do not know how to react elementum with usb 2.0 flash external device . Do you use elementum  yourself? Where do you use your supplement?

**Comment by elgatito** [comment]
I'm not saying you *can't* use SD cards. You can use whatever you want. But it will not work too long and become broken too soon. If you don't have other options - use memory storage with 70Mb. Should be enough for usual cases.

**Comment by Azat868** [comment]
What file system format do you recommend for external storage? (ntfs, ext ...?)

**Comment by elgatito** [comment]
Probably any non-FAT32. People use on android, windows, linux, osmc without problems.

**Comment by Azat868** [comment]
https://github.com/scakemyer/plugin.video.quasar/issues/862
https://github.com/scakemyer/plugin.video.quasar/issues/90
It turns out in elementum you solved the problem with external drives?

**Comment by elgatito** [comment]
You can test to see if it works. I had no reports that external storage has problems. But it can be that nobody tried it.

**Comment by Azat868** [comment]
- How to change the list on the wall in films? I write number 4, and films does not on the wall

**Comment by elgatito** [comment]
Sorry, I don't understand your question. You want to change number of items in listings within Elementum?

**Comment by burekas7** [comment]
I have micro-sd port in my device and usb 2.0 port.
What is more recommended for using with this addon if I want to set the Download path to be on external memory?

**Comment by elgatito** [comment]
It's all individual. You should use what better serves your needs.

**Comment by burekas7** [comment]
But what could be broken first, the sd card or the USB flash drive?
And regarding the write/read speed, which one is better for torrents use?

**Comment by elgatito** [comment]
> But what could be broken first, the sd card or the USB flash drive?

USB *FLASH* drive is almost the same as sd-card, generally. 
USB HDD drive is much better.

**Comment by burekas7** [comment]
Ok, but all of them are supported in Elementum as Download path, right?
In Quasar are they supported too?

**Comment by elgatito** [comment]
> Ok, but all of them are supported in Elementum as Download path, right?

Elementum is not limiting anything, it's all about your operating system. Some (like android) are limiting external storages, so if it work - you get it.

**Comment by burekas7** [comment]
So it's more recommended to format it as NTFS and set it as expand to the internal storage? (Android)

I have also understood that FAT32 limits the file size of torrents you can use, right?

**Comment by Azat868** [comment]
How to change the list on the wall in films? I write number 4, and films does not on the wall
![photo_2018-01-24_20-38-45](https://user-images.githubusercontent.com/29046741/35347600-aa1688e4-0146-11e8-90da-5d096b7b3bc2.jpg)
![photo_2018-01-24_20-38-46](https://user-images.githubusercontent.com/29046741/35347601-aa3632ca-0146-11e8-9c53-a9fdfd147382.jpg)

**Comment by Azat868** [comment]
How to make that vnc show an elementum? Now if you run vnc it shows the desktop
![vnc show decstop](https://user-images.githubusercontent.com/29046741/35348124-29b66b4a-0148-11e8-9048-b0772cd70918.JPG)
![vnc](https://user-images.githubusercontent.com/29046741/35348125-29d59902-0148-11e8-9a7e-5ecbade499b7.jpg)

**Comment by Azat868** [comment]
![version viewer](https://user-images.githubusercontent.com/29046741/35348167-46e6cac0-0148-11e8-904a-52217e3efb28.JPG)

**Comment by Azat868** [comment]
> Please note that for legal reasons, I won't discuss, develop nor distribute any providers connecting to illegal sources. So there is no need to ask me. While I can partake in general discussions regarding provider development, I won't do so for illegal sources specific problems.


I'll try to ask all the same. How can I use the proxy for providers in the settings? So that the download does not go through a proxy? Search - through a proxy, download - without a proxy.

**Comment by elgatito** [comment]
> Views

https://forum.kodi.tv/showthread.php?tid=133342
```
<views>500,51,50,550,551,560,501,508,504,503,505,511,720,722,723,724,725,737</views>
```

> Proxy

Proxies are not working in Elementum (yet).

**Comment by elgatito** [comment]
> So it's more recommended to format it as NTFS and set it as expand to the internal storage? (Android)
> I have also understood that FAT32 limits the file size of torrents you can use, right?

There is no "right" answer, you should try on your device. 
FAT32 - yes, size limit of files and poor speed sometimes.

**Comment by Azat868** [comment]
I just noticed problems with usb. I insert different yusb, the message leaves: "You do not have rights of record on this yusb". Checked with three usb drives, everywhere the same. The Kodi is 17.6 for the raspbian
![you have do not permission](https://user-images.githubusercontent.com/29046741/35349940-6c99666a-014d-11e8-9d51-d7af5fe0f052.jpg)

**Comment by Azat868** [comment]
Drive Format NTFS

**Comment by Azat868** [comment]
> Proxies are not working in Elementum (yet).
And if you register a proxy in the settings of the Kodi? This proxy does not apply to elementum?

**Comment by Azat868** [comment]
By default, where does the log write elementum? /root/.kodi/temp/kodi.log? Need that the settings include that the log elementum was written ?

**Comment by Azat868** [comment]
https://pastebin.com/YyLh6PeL

**Comment by elgatito** [comment]
What should I look for in that log?

**Comment by Azat868** [comment]
16:40:11.884 T:1489691392    INFO: initializing python engine.
16:40:11.884 T:1489691392   DEBUG: CPythonInvoker(4, /root/.kodi/addons/plugin.video.elementum/navigation.py): start pro$
16:40:11.917 T:1489691392   DEBUG: -->Python Interpreter Initialized<--
16:40:11.917 T:1489691392   DEBUG: CPythonInvoker(4, /root/.kodi/addons/plugin.video.elementum/navigation.py): the sourc$
16:40:11.918 T:1489691392   DEBUG: CPythonInvoker(4, /root/.kodi/addons/plugin.video.elementum/navigation.py): setting t$
16:40:11.918 T:1489691392   DEBUG: CPythonInvoker(4, /root/.kodi/addons/plugin.video.elementum/navigation.py): entering $
16:40:11.918 T:1489691392   DEBUG: CPythonInvoker(4, /root/.kodi/addons/plugin.video.elementum/navigation.py): instantia$
16:40:12.369 T:1911189504   DEBUG: ------ Window Init (DialogBusy.xml) ------
16:40:12.477 T:1489691392  NOTICE: [plugin.video.elementum] Python version: ['2.7.13 (default, Nov 24 2017, 17:33:09) ',$
                                                dist: ('debian', '9.3', '')
                                                linux_distribution: ('debian', '9.3', '')
                                                system: Linux
                                                machine: armv7l
                                                platform: Linux-4.9.59-v7+-armv7l-with-debian-9.3
                                                uname: ('Linux', 'r', '4.9.59-v7+', '#1047 SMP Sun Oct 29 12:19:23 GMT 2$
                                                version: #1047 SMP Sun Oct 29 12:19:23 GMT 2017
                                                mac_ver: ('', ('', '', ''), '')
16:40:12.549 T:1489691392   DEBUG: [plugin.video.elementum] Requesting http://localhost:65220/ from ['plugin://plugin.vi$
16:40:12.808 T:1489691392   ERROR: [plugin.video.elementum] Traceback (most recent call last):
16:40:12.808 T:1489691392   ERROR: [plugin.video.elementum]   File "/root/.kodi/addons/plugin.video.elementum/resources/$
16:40:12.809 T:1489691392   ERROR: [plugin.video.elementum]     data = _json(url)
16:40:12.809 T:1489691392   ERROR: [plugin.video.elementum]   File "/root/.kodi/addons/plugin.video.elementum/resources/$
16:40:12.809 T:1489691392   ERROR: [plugin.video.elementum]     with closing(urllib2.urlopen(url)) as response:
16:40:12.809 T:1489691392   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
16:40:12.809 T:1489691392   ERROR: [plugin.video.elementum]     return opener.open(url, data, timeout)
16:40:12.810 T:1489691392   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/urllib2.py", line 435, in open
16:40:12.810 T:1489691392   ERROR: [plugin.video.elementum]     response = meth(req, response)
16:40:12.810 T:1489691392   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/urllib2.py", line 548, in http_re$
16:40:12.810 T:1489691392   ERROR: [plugin.video.elementum]     'http', request, response, code, msg, hdrs)
16:40:12.810 T:1489691392   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/urllib2.py", line 473, in error
16:40:12.811 T:1489691392   ERROR: [plugin.video.elementum]     return self._call_chain(*args)
16:40:12.811 T:1489691392   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_c$
16:40:12.811 T:1489691392   ERROR: [plugin.video.elementum]     result = func(*args)
16:40:12.811 T:1489691392   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/urllib2.py", line 556, in http_er$
16:40:12.811 T:1489691392   ERROR: [plugin.video.elementum]     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
16:40:12.812 T:1489691392   ERROR: [plugin.video.elementum] HTTPError: HTTP Error 503: Service Unavailable

**Comment by Azat868** [comment]
Constant errors. Please do normally, and then lay out. Or do not even lay out. My nervous system will be fine.

**Comment by elgatito** [comment]
I don't know why your python can't communicate with the daemon. You can delete settings.xml for plugin.video.elementum to restore default settings.

**Comment by Azat868** [comment]
Thank you. How, do you recommend starting the kodi 17.6? kodi or kodi-standalone?

**Comment by Azat868** [comment]
Unfortunately, I ran and so kodi and so kodi-standalone. I did not have enough nerves at elementum. Very very very buggy application. To understand how it is buggy, you need to set: raspabian, kodi 17.6, then elementum. I opened elementum 10 times, and 9 times he gave an error. I wrote these errors here, but the author waved his hands. I am tired of this. I'd better look at something else from the add-ons. Not this elementum.  Successful to you torment, dear users, but I have enough.
