### ISSUE TITLE
No subtitles found for video started via "Torrent History"

### ISSUE THREAD

**Issue by hejman** [elgatito/plugin.video.elementum#692]
Starting a movie through the "Torrent history" category causes the movie name "History" to be passed on the the Kodi subtitle search instead of the filename/hash. This applies to any subtitle provider i have tested (Open subtitles and Subscene).

I assume this is a bug?

**Comment by elgatito** [comment]
@hejman When you open something from torrent history - you open a torrent file, that has no information about it's content, only filenames.
I don't know of any method of instructing Kodi about name for subtitles search.

**Comment by naamapps** [comment]
@elgatito maybe add an option to link an existing torrent in the torrent history to a movie or TV show episode.
For example, episode of a random TV show - right click on the episode - in the menu click attach torrent from history - show a list of all the torrent history - choose a torrent - play the torrent with the right details. 

Hope that make sense, 
Thanks.

**Comment by elgatito** [comment]
When you open a stream with Elementum Kodi treats it as a file, and when you open Browse dialog - it just tried to get root of this file store, which is a main page of Elementum.
I have no ideas how to change it.

**Comment by naamapps** [comment]
Sorry but I don't really understand what you mean.
The file of the stream can't be modified to contain the relevant information about the episode or movie you attach? 
Then how when you choose a stream from Burst, it contains all of the information?
I just throw things out there and hope it works out for you.. I don't have the experience in kodi development.

**Comment by elgatito** [comment]
> Then how when you choose a stream from Burst, it contains all of the information?

Because when you search something - you know what you search.
If you run something from torrent history - you have only torrent, you don't know who added it.

**Comment by naamapps** [comment]
Yes I understood that.
Why can't the user choose a specific movie from the catalog and attach it to a torrent from the torrent history?
It's the user responsibility to choose the right movie but it is a solution. 
That way you have the information about the movie and you have the torrent from the history.

**Comment by elgatito** [comment]
> Why can't the user choose a specific movie from the catalog and attach it to a torrent from the torrent history?

Because it is not implemented. Source code is open and you can submit a Pull Request to fill that gap.

**Comment by naamapps** [comment]
I was asking this hypotheticaly.
As I said, I don't have the experience to do something like this. 
It's just a suggestion for you.

**Comment by antonsoroko** [comment]
should be available in next elementum release.
also please note how it works: https://github.com/elgatito/context.elementum/pull/13#issue-615408894
