### ISSUE TITLE
(BUG) elementum crashes after playing file using storage

### ISSUE THREAD

**Issue by spiyderz** [elgatito/plugin.video.elementum#698]
OS=libreelec 9.2.6
RPi4
Kodi=18.9
Latest elementum/burst

I'm using elementum with file storage settings. I have a NAS share mounted on boot (NFS). On the share I have three folders (downloads, movies, shows) elementum saves downloads to the downloads folder and then is set up to separately move movies to movies and shows to shows. When a file is done playing I get the pop-up would you like to continue to download I select no. I then get two more pop-ups asking if I would like to delete the files, I click no both times as soon as I click no the second time I get a notification elementum crashed. It does this every single time. 

If anybody can give me an idea of why I keep crashing after playback is done it would be greatly appreciated.

Log: http://paste.kodi.tv/ajuyekuxes
Log: http://ix.io/2PMM

Edit: so if I send it to download to storage but not move files everything works great no crash but as soon as I turn move to folders back on I get a crash every time I'm done playing.tge torrent.

**Comment by elgatito** [comment]
```
2021-02-17 13:22:55.726 T:2382795632  NOTICE: [plugin.video.elementum] free(): double free detected in tcache 2
2021-02-17 13:22:55.728 T:2382795632  NOTICE: [plugin.video.elementum] SIGABRT: abort
2021-02-17 13:22:55.729 T:2382795632  NOTICE: [plugin.video.elementum] PC=0xb6b9a2d8 m=0 sigcode=4294967290
```

Looks you have some problem with C++ code. 
I have no idea what is that about.

**Comment by spiyderz** [comment]
> ```
> 2021-02-17 13:22:55.726 T:2382795632  NOTICE: [plugin.video.elementum] free(): double free detected in tcache 2
> 2021-02-17 13:22:55.728 T:2382795632  NOTICE: [plugin.video.elementum] SIGABRT: abort
> 2021-02-17 13:22:55.729 T:2382795632  NOTICE: [plugin.video.elementum] PC=0xb6b9a2d8 m=0 sigcode=4294967290
> ```
> 
> Looks you have some problem with C++ code.
> I have no idea what is that about.

I appreciate you looking. I'll start researching.

**Comment by elgatito** [comment]
@spiyderz Please, try with 0.1.70.

**Comment by spiyderz** [comment]
> @spiyderz Please, try with 0.1.70.

Thanks I'll give it a shot this afternoon when I get home. Is the donate button still working? I'd like to mash on that thing a couple of times.

**Comment by elgatito** [comment]
@spiyderz Yes, button should be working.

**Comment by spiyderz** [comment]
Working in 1.71
