### ISSUE TITLE
impossible install to vero4k

### ISSUE THREAD

**Issue by inah72** [elgatito/plugin.video.elementum#7]
19:44:36.221 T:3456099312   ERROR: [plugin.video.elementum] Traceback (most recent call last):
19:44:36.233 T:3860067312   DEBUG: CCurlFile::Open - effective URL: <https://raw.githubusercontent.com/dvor85/kodi.repo/master/addons.xml.md5>
19:44:36.280 T:3383751664   DEBUG: Thread FileCache start, auto delete: false
19:44:36.281 T:3383751664    INFO: CFileCache::Process - Source read didn't return any data! Hit eof(?)
19:44:36.293 T:4093637616   DEBUG: CRepositoryUpdateJob[repository.meta] checksum not changed.
19:44:36.293 T:4093637616   DEBUG: CRepositoryUpdateJob[repository.supremacy] checking for updates.
19:44:36.296 T:4093637616   DEBUG: CFileCache::Open - opening <Colossal1/repository.colossus.common/master/addons.xml.md5> using cache
19:44:36.296 T:4093637616   DEBUG: CurlFile::Open(0xd3a52920) https://raw.githubusercontent.com/Colossal1/repository.colossus.common/master/addons.xml.md5
19:44:36.306 T:3456099312   ERROR: [plugin.video.elementum]   File "/home/osmc/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/daemon.py", line 221, in elementumd_thread
19:44:36.306 T:3456099312   ERROR: [plugin.video.elementum]     proc = start_elementumd(stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
19:44:36.307 T:3456099312   ERROR: [plugin.video.elementum]   File "/home/osmc/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/daemon.py", line 199, in start_elementumd
19:44:36.307 T:3456099312   ERROR: [plugin.video.elementum]     return subprocess.Popen(args, **kwargs)
19:44:36.307 T:3456099312   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
19:44:36.308 T:3456099312   ERROR: [plugin.video.elementum]     errread, errwrite)
19:44:36.308 T:3456099312   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
19:44:36.308 T:3456099312   ERROR: [plugin.video.elementum]     raise child_exception
19:44:36.310 T:3456099312   ERROR: [plugin.video.elementum] OSError: [Errno 2] No such file or directory
19:44:36.311 T:3456099312   ERROR: [plugin.video.elementum]
19:44:36.312 T:4093637616   ERROR: CCurlFile::Open failed with code 404 for https://raw.githubusercontent.com/Colossal1/repository.colossus.common/master/addons.xml.md5
19:44:36.312 T:4093637616   ERROR: Open - failed to open source <https://raw.githubusercontent.com/Colossal1/repository.colossus.common/master/addons.xml.md5>
19:44:36.312 T:4093637616   ERROR: CRepository: failed read 'https://raw.githubusercontent.com/Colossal1/repository.colossus.common/master/addons.xml.md5'
19:44:36.331 T:3383751664   DEBUG: Thread FileCache 3383751664 terminating
19:44:36.331 T:3860067312   DEBUG: CFileCache::Open - opening <1.0/repositories/DiMartino/myshows.me-kodi-repo/raw/default/addons.xml.md5> using cache
19:44:36.331 T:3860067312   DEBUG: CurlFile::Open(0xd7780838) http://api.bitbucket.org/1.0/repositories/DiMartino/myshows.me-kodi-repo/raw/default/addons.xml.md5
19:44:36.333 T:4114235392   DEBUG: ------ Window Init (DialogNotification.xml) ------
19:44:36.393 T:4093637616   DEBUG: CRepositoryUpdateJob[repository.smash] checking for updates.
19:44:36.396 T:4093637616   DEBUG: CFileCache::Open - opening <Colossal1/repository.colossus.common/master/addons.xml.md5> using cache
19:44:36.396 T:4093637616   DEBUG: CurlFile::Open(0xd3a52920) https://raw.githubusercontent.com/Colossal1/repository.colossus.common/master/addons.xml.md5
19:44:36.411 T:3456099312   ERROR: Exception in thread Thread-2:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
                                                self.run()
                                              File "/usr/lib/python2.7/threading.py", line 763, in run
                                                self.__target(*self.__args, **self.__kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/daemon.py", line 221, in elementumd_thread
                                                proc = start_elementumd(stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
                                              File "/home/osmc/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/daemon.py", line 199, in start_elementumd
                                                return subprocess.Popen(args, **kwargs)
                                              File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
                                                errread, errwrite)
                                              File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
                                                raise child_exception
                                            OSError: [Errno 2] No such file or directory

## Your Environment

* Version used:

* Environment name and version:
Kodi 17 [Krypton]) and  OSMC, 
* Operating System and version:

* Link to Kodi debug log: http://paste.osmc.tv/urigifumoz

**Comment by elgatito** [comment]
Can you try enabling debug mode in kodi? Log will have more information.

**Comment by inah72** [comment]
update link to log

**Comment by inah72** [comment]
http://paste.osmc.tv/urigifumoz

**Comment by inah72** [comment]
i think same problem https://github.com/scakemyer/plugin.video.quasar/issues/810

**Comment by elgatito** [comment]
Have you tried to install universal zip? (the biggest one) 
Plugin tries to load linux_arm-6 binary and did not find it (according to your log).

**Comment by elgatito** [comment]
Can you try with the version v0.0.15 and post the log if not working?

**Comment by inah72** [comment]
same  error   OSError: [Errno 2] No such file or directory
http://paste.osmc.tv/kaxamukiqi

**Comment by elgatito** [comment]
Uninstall the plugin, download the biggest zip and reinstall.

**Comment by inah72** [comment]
Does not matter
http://paste.osmc.tv/enujasujag

**Comment by elgatito** [comment]
there was a typo in the code. Please, try v0.0.16.

**Comment by inah72** [comment]
same story after 16 install
http://paste.osmc.tv/oribizapuz

**Comment by elgatito** [comment]
Your system says binary cannot be run from path: /home/osmc/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_arm64/elementum

can you try to run binary from 
/home/osmc/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_arm64/elementum
/home/osmc/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_arm-6/elementum

**Comment by inah72** [comment]
Vero 4K can run armhf and arm64 packages side by side, e.g. I installed `sudo apt-get install gcc:arm64`after this i have different error:
http://paste.osmc.tv/ehavujifap

**Comment by elgatito** [comment]
I ask you to run binaries from shell. There are binaries for different platforms when you install the biggest zip.

**Comment by inah72** [comment]
osmc@osmc4k:~/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_arm64$                     sudo ./elementum
./elementum: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory

arm7 version loading binary 
arm6 unable to execute

**Comment by elgatito** [comment]
Can you show the log from running arm7 binary?

**Comment by inah72** [comment]
http://paste.osmc.tv/ixejusetey

**Comment by elgatito** [comment]
Please, try version 0.0.17. Reinstall plugin from the biggest zip file.

**Comment by inah72** [comment]
Littlebit better but lot of errors log:https://www.dropbox.com/s/adk2xx9axbpr3j4/kodi.log?dl=0

**Comment by elgatito** [comment]
I can't see that log. 
Can you reboot, and try to open something and then paste log somewhere?

**Comment by elgatito** [comment]
The daemon loads fine, then it looks like system limitation (you can try to change it by using "ulimit").
Try setting download storage as Memory.

**Comment by inah72** [comment]
After change plugin settings download storage as memory it's working

**Comment by strummerj** [comment]
Hello. I am running into similar issues with the latest version on my Vero 4K. It looks like elementum installs and trys to run the arm6 binary when it actually needs to do arm7 or arm64. If I replace the arm6 binary with either of those it works.

I have to do this to make it work:

rm ~/.kodi/addons/plugin.video.elementum/resources/bin/linux_arm-6/elementum

cp ~/.kodi/addons/plugin.video.elementum/resources/bin/linux_arm64/elementum ~/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_arm-6/elementum

Thanks!

**Comment by elgatito** [comment]
If you have troubles with 0.0.33, try to uninstall and install plugin from biggest zip.

**Comment by elgatito** [comment]
Log is empty for that link.

**Comment by elgatito** [comment]
Do not download platform specific zip file. Download the one with the biggest size, without platform specification. And install it.

**Comment by inah72** [comment]
Yes  i downloaded bigger zip file http://paste.osmc.tv/walufeyuve

**Comment by inah72** [comment]
10:03:53.118 T:3622286080   DEBUG: CPVRTimers - Update - updating timers
10:03:53.508 T:3502084864  NOTICE: [plugin.video.elementum] Updating elementum daemon...
10:03:53.715 T:3811832576  NOTICE: [plugin.video.elementum] Python version: ['2.7.13 (default, Nov 24 2017, 17:33:09) ', '[GCC 6.3.0 20170516]']
                                                dist: ('debian', '9.3', '')
                                                linux_distribution: ('debian', '9.3', '')
                                                system: Linux
                                                machine: arm
                                                platform: Linux-3.14.29-51-osmc-arm-with-debian-9.3
                                                uname: ('Linux', 'osmc', '3.14.29-51-osmc', '#1 SMP Tue Jan 2 09:35:33 UTC 2018', 'arm', '')
                                                version: #1 SMP Tue Jan 2 09:35:33 UTC 2018
                                                mac_ver: ('', ('', '', ''), '')
10:03:53.716 T:3811832576  NOTICE: [plugin.video.elementum] CPU: proc0={'CPU implementer': '0x41', 'Features': 'fp asimd evtstrm aes pmull sha1 sha2 crc32 wp half thumb fastmult vfp edsp neon vfpv3 tlsi vfpv4 idiva idivt', 'CPU architecture': '8', 'processor': '3', 'Hardware': 'Vero4K', 'CPU revision': '4', 'CPU part': '0xd03', 'Serial': '210a82005db8868bdf5322b0dc0a3898', 'Processor': 'AArch64 Processor rev 4 (aarch64)', 'CPU variant': '0x0'}
10:03:53.717 T:3811832576  NOTICE: [plugin.video.elementum] Exploring model: aarch64 processor rev 4 (aarch64)
10:03:53.717 T:3811832576  NOTICE: [plugin.video.elementum] Using CPU info arch: arm64
10:03:53.849 T:3491754752   ERROR: [plugin.video.elementum] Traceback (most recent call last):
10:03:53.850 T:3491754752   ERROR: [plugin.video.elementum]   File "/home/osmc/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/rpc.py", line 359, in server_thread
10:03:53.850 T:3491754752   ERROR: [plugin.video.elementum]     s = bjsonrpc.createserver(port=JSONRPC_EXT_PORT, handler_factory=ElementumRPCServer)
10:03:53.850 T:3491754752   ERROR: [plugin.video.elementum]   File "/home/osmc/.kodi/addons/plugin.video.elementum/resources/site-packages/bjsonrpc/main.py", line 55, in createserver
10:03:53.850 T:3491754752   ERROR: [plugin.video.elementum]     sck.bind((host, port))
10:03:53.851 T:3491754752   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/socket.py", line 228, in meth
10:03:53.851 T:3491754752   ERROR: [plugin.video.elementum]     return getattr(self._sock,name)(*args)
10:03:53.851 T:3491754752   ERROR: [plugin.video.elementum] error: [Errno 98] Address already in use
10:03:53.852 T:3491754752   ERROR: [plugin.video.elementum]
10:03:53.854 T:3483366144  NOTICE: [plugin.video.elementum] elementumd: starting elementumd
10:03:53.854 T:3710644992   DEBUG: JSONRPC Server: New connection detected
10:03:53.854 T:3710644992    INFO: JSONRPC Server: New connection added
10:03:53.854 T:3710644992    INFO: JSONRPC Server: Disconnection detected
10:03:53.855 T:3483366144  NOTICE: [plugin.video.elementum] Kodi's JSON-RPC service is available, starting up...
10:03:53.855 T:3483366144  NOTICE: [plugin.video.elementum] Binary detection. Source: /home/osmc/.kodi/addons/plugin.video.elementum/resources/bin/linux_arm64/elementum, Destination: /home/osmc/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_arm64/elementum
10:03:53.858 T:3483366144  NOTICE: [plugin.video.elementum] Updating elementum daemon...
10:03:53.858 T:3491754752   ERROR: Exception in thread Thread-1:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                                self.run()
                                              File "/usr/lib/python2.7/threading.py", line 754, in run
                                                self.__target(*self.__args, **self.__kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/rpc.py", line 359, in server_thread
                                                s = bjsonrpc.createserver(port=JSONRPC_EXT_PORT, handler_factory=ElementumRPCServer)
                                              File "/home/osmc/.kodi/addons/plugin.video.elementum/resources/site-packages/bjsonrpc/main.py", line 55, in createserver
                                                sck.bind((host, port))
                                              File "/usr/lib/python2.7/socket.py", line 228, in meth
                                                return getattr(self._sock,name)(*args)
                                            error: [Errno 98] Address already in use
10:03:53.980 T:3502084864  NOTICE: [plugin.video.elementum] Deleting stale files set([])
10:03:53.980 T:3502084864  NOTICE: [plugin.video.elementum] Binary detection: [ Source: /home/osmc/.kodi/addons/plugin.video.elementum/resources/bin/linux_arm64/elementum, Destination: /home/osmc/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_arm64/elementum ]
10:03:53.981 T:3502084864  NOTICE: [plugin.video.elementum] Binary dir: /home/osmc/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_arm64, item: /home/osmc/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_arm64/elementum
10:03:53.982 T:3502084864   DEBUG: [plugin.video.elementum] Checking for visible
10:03:53.991 T:3502084864  NOTICE: [plugin.video.elementum] elementumd: start args: [u'/home/osmc/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_arm64/elementum'], kw: {'close_fds': True, 'env': {'USERNAME': 'osmc', 'SUDO_COMMAND': '/usr/lib/kodi/kodi.bin --standalone -fs --lircdev /var/run/lirc/lircd', 'TERM': 'linux', 'SHELL': '/bin/bash', 'TZ': ':Europe/Tallinn', 'HOME': '/home/osmc', 'SUDO_UID': '0', 'SUDO_GID': '0', 'LD_LIBRARY_PATH': u'/home/osmc/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_arm64:', 'KODI_BIN_HOME': '/usr/lib/kodi', 'LOGNAME': 'osmc', 'USER': 'osmc', 'KODI_HOME': '/usr/share/kodi', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'MAIL': '/var/mail/osmc', 'SUDO_USER': 'root', 'OS': 'Linux', 'PYTHONOPTIMIZE': '1'}, 'cwd': u'/home/osmc/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_arm64', 'stderr': -2, 'stdout': -1}
10:03:54.009 T:3483366144  NOTICE: [plugin.video.elementum] Deleting stale files set([])
10:03:54.010 T:3483366144  NOTICE: [plugin.video.elementum] Binary detection: [ Source: /home/osmc/.kodi/addons/plugin.video.elementum/resources/bin/linux_arm64/elementum, Destination: /home/osmc/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_arm64/elementum ]
10:03:54.011 T:3483366144  NOTICE: [plugin.video.elementum] Binary dir: /home/osmc/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_arm64, item: /home/osmc/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_arm64/elementum
10:03:54.012 T:3483366144   DEBUG: [plugin.video.elementum] Checking for visible
10:03:54.021 T:3483366144  NOTICE: [plugin.video.elementum] elementumd: start args: [u'/home/osmc/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_arm64/elementum'], kw: {'close_fds': True, 'env': {'USERNAME': 'osmc', 'SUDO_COMMAND': '/usr/lib/kodi/kodi.bin --standalone -fs --lircdev /var/run/lirc/lircd', 'TERM': 'linux', 'SHELL': '/bin/bash', 'TZ': ':Europe/Tallinn', 'HOME': '/home/osmc', 'SUDO_UID': '0', 'SUDO_GID': '0', 'LD_LIBRARY_PATH': u'/home/osmc/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_arm64:', 'KODI_BIN_HOME': '/usr/lib/kodi', 'LOGNAME': 'osmc', 'USER': 'osmc', 'KODI_HOME': '/usr/share/kodi', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'MAIL': '/var/mail/osmc', 'SUDO_USER': 'root', 'OS': 'Linux', 'PYTHONOPTIMIZE': '1'}, 'cwd': u'/home/osmc/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_arm64', 'stderr': -2, 'stdout': -1}
10:03:54.111 T:3502084864   ERROR: [plugin.video.elementum] Traceback (most recent call last):
10:03:54.111 T:3502084864   ERROR: [plugin.video.elementum]   File "/home/osmc/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/daemon.py", line 252, in elementumd_thread
10:03:54.112 T:3502084864   ERROR: [plugin.video.elementum]     proc = start_elementumd(stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
10:03:54.112 T:3502084864   ERROR: [plugin.video.elementum]   File "/home/osmc/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/daemon.py", line 230, in start_elementumd
10:03:54.112 T:3502084864   ERROR: [plugin.video.elementum]     return subprocess.Popen(args, **kwargs)
10:03:54.113 T:3502084864   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
10:03:54.113 T:3502084864   ERROR: [plugin.video.elementum]     errread, errwrite)
10:03:54.113 T:3502084864   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
10:03:54.113 T:3502084864   ERROR: [plugin.video.elementum]     raise child_exception
10:03:54.114 T:3502084864   ERROR: [plugin.video.elementum] OSError: [Errno 13] Permission denied
10:03:54.114 T:3502084864   ERROR: [plugin.video.elementum]
10:03:54.118 T:3483366144   ERROR: [plugin.video.elementum] Traceback (most recent call last):
10:03:54.118 T:3483366144   ERROR: [plugin.video.elementum]   File "/home/osmc/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/daemon.py", line 252, in elementumd_thread
10:03:54.118 T:3483366144   ERROR: [plugin.video.elementum]     proc = start_elementumd(stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
10:03:54.119 T:3483366144   ERROR: [plugin.video.elementum]   File "/home/osmc/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/daemon.py", line 230, in start_elementumd
10:03:54.119 T:3483366144   ERROR: [plugin.video.elementum]     return subprocess.Popen(args, **kwargs)
10:03:54.120 T:3483366144   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
10:03:54.120 T:3483366144   ERROR: [plugin.video.elementum]     errread, errwrite)
10:03:54.120 T:3483366144   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
10:03:54.121 T:3483366144   ERROR: [plugin.video.elementum]     raise child_exception
10:03:54.121 T:3483366144   ERROR: [plugin.video.elementum] OSError: [Errno 2] No such file or directory
10:03:54.122 T:3483366144   ERROR: [plugin.video.elementum]
10:03:54.125 T:3483366144   ERROR: Exception in thread Thread-2:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                                self.run()
                                              File "/usr/lib/python2.7/threading.py", line 754, in run
                                                self.__target(*self.__args, **self.__kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/daemon.py", line 252, in elementumd_thread
                                                proc = start_elementumd(stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
                                              File "/home/osmc/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/daemon.py", line 230, in start_elementumd
                                                return subprocess.Popen(args, **kwargs)
                                              File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
                                                errread, errwrite)
                                              File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
                                                raise child_exception
                                            OSError: [Errno 2] No such file or directory
10:03:54.126 T:3502084864   ERROR: Exception in thread Thread-2:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                                self.run()
                                              File "/usr/lib/python2.7/threading.py", line 754, in run
                                                self.__target(*self.__args, **self.__kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/daemon.py", line 252, in elementumd_thread
                                                proc = start_elementumd(stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
                                              File "/home/osmc/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/daemon.py", line 230, in start_elementumd
                                                return subprocess.Popen(args, **kwargs)
                                              File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
                                                errread, errwrite)
                                              File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
                                                raise child_exception
                                            OSError: [Errno 13] Permission denied

**Comment by inah72** [comment]
i see everything strange

**Comment by elgatito** [comment]
Now I also see the contents, strange.

Can you look on your device if you have this file and it can be ran:
/home/osmc/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_arm64/elementum

Also if you have this directory: /home/osmc/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_arm64/
and this /home/osmc/.kodi/addons/plugin.video.elementum/resources/bin/linux_arm64/

Because if can't copy from one directory to another one. You can also delete this one - /home/osmc/.kodi/userdata/addon_data/plugin.video.elementum/bin/ and restart kodi .

**Comment by elgatito** [comment]
Any update here?

**Comment by strummerj** [comment]
Just an idea, but if they continue having trouble they might try:

sudo apt-get install gcc:arm64

**Comment by inah72** [comment]
after sudo apt-get install gcc:arm64 install was also elementum install successful .

**Comment by elgatito** [comment]
@DuzAwe @inah72  @strummerj  can anyone with OSMC post Kodi log file with debug enabled?

http://elementum.surge.sh/contribute/log/

Probably if we select armv7 and not arm64, it will not require installing gcc library.

**Comment by DuzAwe** [comment]
@elgatito Soonest I can post the logs would be Tuesday night. Vero 4k is arm64 but OSMC armhf is installed by default and I belive its the Amlogic S905X chipset. Hope thats of some help until then.

**Comment by elgatito** [comment]
@DuzAwe according to some docs, basic system for Vero is armv7, while it can run armhf and arm64 after installing of gcc:arm64. That is why I want to try to change detection to set it to armv7, so it won't need any packages. 
That is a theory, so I will need a log to see how it gets through detection, then I will ask someone with Vero, to try dev version to make sure it works fine.
