### ISSUE TITLE
Error on Android 7 and Kodi Leia 18

### ISSUE THREAD

**Issue by atomizasser** [elgatito/plugin.video.elementum#70]
Hello.
Thanks for the add-on. I find a problema with add-on an Kodi Leia 18.
I've tested add-on in Kodi Leia 18 on android 7 (last nightly build) and it doesn't work. If you try to start Elementum appears and error and said "Restart Kodi before start". But after restart and try it again, same error appears.

I've attached the log. Kinds regards

[kodi.log](https://github.com/elgatito/plugin.video.elementum/files/1653844/kodi.log)

**Comment by elgatito** [comment]
Plugin can't copy own files to the userdata directory, where it usually keeps files:

```
ERROR: [plugin.video.elementum] Unable to copy to destination path for update: [Errno 13] Permission denied: '/data/data/org.xbmc.kodi'
```

**Comment by atomizasser** [comment]
Thanks.
Is there a solution? Android version is Android TV 7.0 for SonyTV. I don't have root acces, but data/data folder is writable because kodi is installed there. It is possible move Elementum data to an usb folder to write? Thanks.

**Comment by elgatito** [comment]
Please, try 0.0.34 and post new log file here.

**Comment by atomizasser** [comment]
Thanks . I will test it when I come back at home.

**Comment by elgatito** [comment]
It depends an many things. 
You can try the memory storage to see if it's a problem with a storage. 
But that is not in the scope of this issue.
