### ISSUE TITLE
[Request] Do not display text in background images

### ISSUE THREAD

**Issue by daviddia5** [elgatito/plugin.video.elementum#700]
In some backgrounds the title is shown and in my opinion it is not very aesthetic. I remember that in artwork beef there was an option for them not to appear.

![PXL_20210220_111002154 PORTRAIT](https://user-images.githubusercontent.com/74454397/108593584-d6ad1500-7374-11eb-9603-48e3c5766b17.jpg)
![PXL_20210220_111137852 PORTRAIT](https://user-images.githubusercontent.com/74454397/108593586-d876d880-7374-11eb-8ee9-49ee2f0452fe.jpg)

I have tried turning fanart.tv on or off with no changes.
For if it helps, in tmdb helper those images do not appear.
Thanks!

**Comment by matke-84** [comment]
@daviddia5 This is not up to the elementum. If I am not wrong, this is auramod skin. There is an option in the auramode not to use skinhelper for fanarts. I don't have this problem for both titles you mentioned but I use titan bingie mode skin.

**Comment by elgatito** [comment]
@daviddia5 There 3 types of images, you see:
1) Landscape with title on it.
2) Landscape without title.
3) Title itself.

TMDB has only 1).
Fanart has 1, 2, 3.

Elementum is giving all found images to Kodi, which gives them to active skin and skin decides how and what to show.
In my understanding you need to disable what you need in skin, not each addon separately. That does not make sense.

**Comment by daviddia5** [comment]
> @daviddia5 There 3 types of images, you see:
> 
> 1. Landscape with title on it.
> 2. Landscape without title.
> 3. Title itself.
> 
> TMDB has only 1).
> Fanart has 1, 2, 3.
> 
> Elementum is giving all found images to Kodi, which gives them to active skin and skin decides how and what to show.
> In my understanding you need to disable what you need in skin, not each addon separately. That does not make sense.

Yes, I have noticed that when I use fanart.tv they appear less.
The option "use fanart by default" in the "Appearance" menu, what does it do exactly?

**Comment by elgatito** [comment]
> The option "use fanart by default" in the "Appearance" menu, what does it do exactly?

Getting images from fanart.tv.

**Comment by daviddia5** [comment]
> > The option "use fanart by default" in the "Appearance" menu, what does it do exactly?
> 
> Getting images from fanart.tv.

I mean "Use default fanart". What exactly does this do?
![PXL_20210223_020119226 MP](https://user-images.githubusercontent.com/74454397/108789693-0cbbe600-757b-11eb-84e5-40a5cf5a20e2.jpg)

**Comment by elgatito** [comment]
Place default icons if needed, if I remember correctly.

**Comment by antonsoroko** [comment]
"Use default fanart" will be renamed to "Use fallback fanart if fanart wasn't found"
it means to use https://github.com/elgatito/plugin.video.elementum/blob/master/fanart.jpg when item does not have its own fanart.

@daviddia5 is this issue still relevant? if not - could you please close it.
