### ISSUE TITLE
I contacted trakt support regarding 423 error and they responded

### ISSUE THREAD

**Issue by ArsalanAlli** [elgatito/plugin.video.elementum#701]
Hi elgatito,
First of all thanks man for this wonderful adon and its sad that we aren't getting any future updates. Anyhow good luck for your future man.
Coming back to the topic, i contacted trakt support regarding my API being blocked and they responded by saying that elementum has created some 395k history items along with duplicates.
They have deduplicated the records and unblocked the access to api.
Now the question: i just wanted to ask you if that will ever happen again as asked by support ?? If yes then pleas let me know so that i dont authorize ele with trakt and keep using both of them without any issue.
Waiting for the kind response man.

**Comment by elgatito** [comment]
There are no reported issues with the latest version of Elementum.

**Comment by ArsalanAlli** [comment]
Thank you very much for the reply man.. appreciate it.

**Comment by spiyderz** [comment]
> There are no reported issues with the latest version of Elementum.



> There are no reported issues with the latest version of Elementum.
Have you had a chance to look at #698? Thanks!
