### ISSUE TITLE
A lot of UPnP ports - possible leftovers from anacrolix/torrent

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/plugin.video.elementum#703]
## Expected Behavior

only port from settings in UPnP (like in the bottom of the screenshot)

## Current Behavior

![elementun_upnp_many_ports](https://user-images.githubusercontent.com/17964763/109201650-25aedc00-77b3-11eb-8698-d2940fce5460.png)

## Steps to Reproduce (for bugs)

1. configure some port in elementum torrent settings
2. start elementum
3. open UPnP settings of your router
4.

## Your Environment

* Version used: 0.1.69

* Environment name and version: spmc 17.6

* Operating System and version: android tv 9

* Link to Kodi debug log: https://paste.ubuntu.com/p/rC3Tt5mQ5s/

**Comment by elgatito** [comment]
@antonsoroko What is the problem? I see two Upnp entries from Elementum. For TCP and UDP. That is expected.

**Comment by antonsoroko** [comment]
a lot of ports from anacrolix/torrent, which i guess is no longer used in elementum but probably somehow remains in elementum and creates ports (and does not delete them).

**Comment by elgatito** [comment]
@antonsoroko Elementum is not using anacrolix/torrent library in any way. Torrserve and other software can use it.

**Comment by antonsoroko** [comment]
sorry, my bad, i was really confident that i disabled all other addons.
everything is good now. thank you.
