### ISSUE TITLE
Season pack buffering issue

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/plugin.video.elementum#704]
## Expected Behavior

no buffering (or buffering check) for completed episodes in pack

## Current Behavior

you cant open completed episode (because of the buffering) if you started to download next one

## Possible Solution

maybe stop buffering and switch to download mode for season pack when you open completed episode or continue buffering but skip check for buffering for completed episode

## Steps to Reproduce (for bugs)

1. choose torrent for season and start download 1st episode
2. after it was downloaded, play 2nd episode - it will start buffering, dont wait and cancel 
3. try to open 1st episode - despite the fact that it was downloaded you still need to wait for 2nd episode to complete buffering
4. try step 2 with 3rd episode - it will increase buffering even more

## Your Environment

* Version used: 0.1.69

* Environment name and version: spmc 17.6

* Operating System and version: android tv 9

* Link to Kodi debug log: https://paste.ubuntu.com/p/Qt5R4wJCfY/

**Comment by elgatito** [comment]
@antonsoroko Please try with v0.1.70.

**Comment by antonsoroko** [comment]
looks good.
thank you!
