### ISSUE TITLE
Some Help please 

### ISSUE THREAD

**Issue by jrod10133** [elgatito/plugin.video.elementum#71]
im having issues installing elementum on the nvidia shield tv i get a error saying could not find binary for architecture 'android_arm64'! i try uninstall and re installing and i downloaded the big zip file also but im still getting a error message i cannot use the addon on the nvidia because of this error

**Comment by elgatito** [comment]
If you want to get any help - provide the kodi.log.

**Comment by elgatito** [comment]
@jrod10133  should I close this issue?

**Comment by compyy** [comment]
worked fine on my Nvidia shield today.

**Comment by elgatito** [comment]
@compyy  but it was not working? Or it was working fine earlier?

**Comment by compyy** [comment]
I installed it first time and it worked with full zip file.

**Comment by elgatito** [comment]
@jrod10133 do you have any updates on this issue?
