### ISSUE TITLE
How to remove season number on shows with only one season

### ISSUE THREAD

**Issue by deniscerri** [elgatito/plugin.video.elementum#713]
## Current Behavior
Example. Boruto is a one season show and it gets searched always as Boruto ... S01E....
Since the show doesnt work like that, i get zero search results using those keywords. 

## Possible Solution
If i simply search the name of the show and just the episode number on the sites supported, i get a good amount of results
So if i remove the s01 at the beginning
Most anime just have this format:
'Name of the Anime' - 'Episode Number' [video quality]

* Version used:
 Latest
* Environment name and version:
Kodi Matrix
* Operating System and version:
Windows 10

**Comment by antonsoroko** [comment]
i guess

https://github.com/elgatito/script.elementum.burst#adding--editing-providers

find your provider here https://github.com/elgatito/script.elementum.burst/blob/master/burst/providers/providers.json

and make override for its `anime_keywords` like in example `"anime_keywords": "{title} {episode}",`.

**Comment by elgatito** [comment]
@deniscerri Elementum is giving all information to searcher addons, they do the search.

**Comment by deniscerri** [comment]
> i guess
> 
> https://github.com/elgatito/script.elementum.burst#adding--editing-providers
> 
> find your provider here https://github.com/elgatito/script.elementum.burst/blob/master/burst/providers/providers.json
> 
> and make override for its `anime_keywords` like in example `"anime_keywords": "{title} {episode}",`.
> 
> also it is script.elementum.burst question, so ideally should go to its repo.

Your Answer fixed my problem. Thank you
