### ISSUE TITLE
tenho um aparelho Mecool km3 

### ISSUE THREAD

**Issue by dranimboy** [elgatito/plugin.video.elementum#723]
quando eu instalo o Elementum dá erro de permissão.fica faltando o repositório do Elementum. Já tentei muitas maneiras.

**Comment by codingnoob233** [comment]
tente instalar, com kodi 18.9 ao invés.

**Comment by elgatito** [comment]
In english, please.

**Comment by codingnoob233** [comment]
> In english, please.

He's getting a permission error installing elementum, on his mecool km3 android box.

Was telling him to try installing with kodi 18.9 instead

**Comment by antonsoroko** [comment]
looks like it can have Android TV 10 - so yes 18.9
https://github.com/elgatito/plugin.video.elementum/issues/669

**Comment by elgatito** [comment]
@dranimboy Closing because of missing information.
