### ISSUE TITLE
Update reference values for messages in messages.pot

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/plugin.video.elementum#725]
## Current Behavior

some example of messages that might be inaccurate:
```
msgctxt "#30549"
msgid "Number of results to find"
```

```
msgctxt "#30388"
msgid "Cache selected streams"
```

```
msgctxt "#30117"
msgid "Resolving torrent files..."
```

## Possible Solution

After #717 will be merged we should try to update reference values for messages in messages.pot accordingly.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

**Comment by elgatito** [comment]
@antonsoroko Not quite understand this issue. Can you give more information.

**Comment by antonsoroko** [comment]
в процессе перевода вроде как стало ясно, что некоторые англ строки не совсем точно отражают то что в реальности делает код.
например `"Resolving torrent files..."` - там вроде файл за раз, а не файлы
`"Cache selected streams"` - тут наверно было бы точнее `cache torrent/stream selection`
`"Number of results to find"` - там как я понял кол-во результатов чтобы считать поиск удачным, аля `Number of results to consider search successful` (надо конечно короче как-то)

может ещё что-то, я думал после мержа 717 посмотреть ещё раз.

**Comment by elgatito** [comment]
`"Resolving torrent files..."` - именно множественное. процесс скачивания и распознания торрентов от поиска.
