### ISSUE TITLE
[Bug] TV Show still marked as Unwatched

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#727]
Hi,
@elgatito 

Regarding the Trakt Lists (TV Shows - My Collection for example)

Even if all the seasons & episodes have been watched the TV Shows still presented without the "Watched" tag and actually act as unwatched TV Show.

First I thought there is relation to these items:
- Special season
- All Seasons

But even when I disable them (Appearance -> List) the TV Show still shown as unwatched.

But maybe even when disabling them they are still "there" actually and this makes the problem with this issue.
From my checking I guess that the hidden item of "special seasons" is the problem and not the "All Seasons" item.

My suggestions is:
If you choose to ignore the "special" seasons in Trakt Lists, so don't take them into account when setting the "watched" status for a TV Show.

Please tell me if you need any additional information.

Thanks.

---
Elementum 0.1.74
Kodi 17.6

---

Images:

![image](https://user-images.githubusercontent.com/13424257/112544687-014d1c00-8dc0-11eb-950d-45d9ab06bc2a.png)
![image](https://user-images.githubusercontent.com/13424257/112545096-7882b000-8dc0-11eb-81f6-45e18f712f81.png)

![image](https://user-images.githubusercontent.com/13424257/112544784-1b86fa00-8dc0-11eb-96d8-0be81d5f8c9d.png)

**Comment by elgatito** [comment]
@burekas7 Please, try with the latest version.

**Comment by burekas7** [comment]
Thanks @elgatito 

The version 0.1.75 fixed the problem.

Closed.
