### ISSUE TITLE
Elementum 0.1.74 identified as a trojan by Windows Defender

### ISSUE THREAD

**Issue by fastleo63** [elgatito/plugin.video.elementum#728]
## Expected Behavior

Elementum running.
## Current Behavior

Elementum not starting anymore (access denied). Cause: Windows Defender blocked it because it was identified as a trojan.
Some other antimalwares recognizes it as a malware:
https://www.virustotal.com/gui/file/c3b6ce44eae5f58b0e7ea0ad37b07bff51635ad294ab2c1fef6724c831e0d122/detection
## Possible Solution

Add Kodi appdata folders in Windows Defender exclusion rules?
## Steps to Reproduce (for bugs)

1. Run Kodi as usual;
2. Let Elementum update itself to 0.1.74;
3. Wait a few seconds, access denied error notice appears.
4. Even the elementum.exe contained in All-in-one package zip file is identified and blocked.

## Your Environment

* Version used: 0.1.74

* Environment name and version: Kodi 18.9 [Leia]

* Operating System and version: Windows 10 Pro v20H2 (64-bit)

* Link to Kodi debug log:

**Comment by SubEdict** [comment]
Wow I just got the same thing. Needed to turn off Defender and re-install 0.1.7.4. Also Kodi 19 won't install the Repo and Faild to install Brust so I download from the git here as nothing else work.

**Comment by elgatito** [comment]
@fastleo63 Interesting how they decide that.
Don't know how we can deal with this.

**Comment by dineshalphaque** [comment]
This is due to one of two things,

1. There really is a trojan embedded in elementum.exe, probably from the machine it was originally compiled from. In this case, it would be best to compile v0.1.75 from a different (clean !) machine, while the first is scanned and cleaned with a virus/malware scanner.

2. There isnt a trojan embedded in elementum.exe, but by sheer coincidence it exhibits a signature of the trojan and thus gets flagged by the anti-virus software. This can usually be fixed trivially by just modifying something inconsequential (like adding a new text/info box/string or perhaps just bringing a new feature forward into 0.1.75 and releasing that, instead. 

Either way, i think we should flag elementum unusable (or revert to 0.1.73) until this is cleared up. malware triggers aren't something which we'd want to have a fine piece of software generating.

just my 2 cents.

**Comment by elgatito** [comment]
@dineshalphaque Elementum is compiled on Linux, inside docker image. So there is no trojan in the system. 
There was an update of Golang version and Swig version for the last release.

**Comment by elgatito** [comment]
Yes, that is caused by a Golang version update:
https://github.com/golang/go/issues/44323

**Comment by matke-84** [comment]
> Wow I just got the same thing. Needed to turn off Defender and re-install 0.1.7.4. Also Kodi 19 won't install the Repo and Failed to install Brust so I download from the git here as nothing else work.

@elgatito Exactly the same thing with 0.1.74. There is no repo and automatically no burst. I have to install it manually.

**Comment by SubEdict** [comment]
Update All-in-one 0.1.75. No trojan! wee.   But still no Repo or Burst (so no option to update).
If it's help here's the log when updating to 1.75 (I think it's somewhere in line 1150 ..?)
[https://paste.kodi.tv/etagegihop.kodi](https://paste.kodi.tv/etagegihop.kodi)

**Comment by elgatito** [comment]
@SubEdict I don't see any errors related to repository. Check if it is installed, maybe it is disabled in Kodi.

**Comment by SubEdict** [comment]
> maybe it is disabled in Kodi.

Were? How? The only thing that is new in v19 when install from zip is this message:
> Warning! Note that add-ons installed from zip(excluding served repositories) will not auto-update and must be manually updated. Would you like to proceed?
 
There's no setting that I know for it ..Am I missing something? 
* I changed: "Update official add-ons from" to "Any repositories" but I don't think is related and did nothing.
Btw, happened on all 3 PC Win -7/10. No Repo, No update, No Burst, Only manually from the git here.

**Comment by elgatito** [comment]
@SubEdict The bug was caused by remove "fanart.png" file from plugin.video.elementum.
Please, install v0.1.76, repisitory should get installed.

**Comment by SubEdict** [comment]
Perfect job @elgatito, Repo El'+ Burst works great now. 
Thanks you so much for your time and effort keeping it alive.

**Comment by SubEdict** [comment]
aah about #728, Defender now call it Low risk Potentially Unwanted Program (PUP). Not sure if this message came a second before the 1.76 update. Anyway, I ignore it.

**Comment by burekas7** [comment]
@elgatito 
0.1.76 fixed my issue in https://github.com/elgatito/plugin.video.elementum/issues/734
Thanks.
