### ISSUE TITLE
Redownload of relocated files

### ISSUE THREAD

**Issue by sfjuocekr** [elgatito/plugin.video.elementum#73]
If you use the move to separate folders option and open the same torrent as you previously watched, the download is reinitiated.

Maybe a file check in the competed destination folder could be made beforehand, so the already downloaded file is used instead.

**Comment by elgatito** [comment]
Completed folder is another unique path, which is not involved into actual downloading. 
Making such a change needs too many changes in the code. 
Sorry, but I would not add this.

**Comment by sfjuocekr** [comment]
Also a file check should be made when the files already exist in the download directory.

The old Quasar backend handled that correctly.
