### ISSUE TITLE
option "Add retrackers" for "Magnet trackers" does not do anything

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/plugin.video.elementum#733]
## Current Behavior

option "Add retrackers" for "Magnet trackers" does not do anything https://github.com/elgatito/elementum/blob/c26b1346a773650bc9328bf49eec146c1913a8c1/bittorrent/torrent_file.go#L373

## Possible Solution

собственно вопрос - что она должна была бы делать? Учитывая что есть еще extraTrackers.
если что-то полезное - то можно попробовать добавить это, иначе может есть смысл просто удалить этот вариант.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

**Comment by elgatito** [comment]
@antonsoroko  it is not used now, and will be removed.

**Comment by elgatito** [comment]
@antonsoroko
https://github.com/elgatito/elementum/blob/c26b1346a773650bc9328bf49eec146c1913a8c1/bittorrent/torrent_file.go#L373
That is the first part, second has moved here:
https://github.com/elgatito/elementum/commit/bc6a26a8e6e693201f235dcd5fb4269b13f9c697
