### ISSUE TITLE
Security Alert (Windows)

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#734]
Hi, @elgatito 

Since updating to version 0.1.75, when I starting a new torrent I got this warning alert from Windows Security:

Program:Win32/Wacapew.C!ml
Alert Level: Low
Process: ...\Kodi\userdata\addon_data\plugin.video.elementum\bin\windows_x64\elementum.exe

* I don't know if it's something from the browser (Since Elemetum web page was run there) or the process in kodi.

Why did this happen? Is it normal?

---
Kodi 17.6
Windows 10, 64bit

**Comment by burekas7** [comment]
@elgatito 

0.1.76 fixed the issue.
Thanks.

**Comment by burekas7** [comment]
After a few hours without any problem,
Suddenly the warning alert popup again:

Program:Win32/Wacapew.C!ml

**Comment by elgatito** [comment]
@burekas7 
https://golang.org/doc/faq#virus

**Comment by burekas7** [comment]
Thanks. 

For now I added the Elementum exe file to the exceptional list of the Windows Defender and it works.
