### ISSUE TITLE
0.1.76 identified as having a virus   - Trojan:Win32/Zpevdo.B

### ISSUE THREAD

**Issue by kidkjbiker** [elgatito/plugin.video.elementum#739]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

**Comment by kidkj77070** [comment]
Went back and loaded 1.69. Seems ok.

**Comment by elgatito** [comment]
There is no virus.
Duplicate of #728
