### ISSUE TITLE
Torrents not downloading when pausing video stream / exiting with "Continue Downloading"

### ISSUE THREAD

**Issue by Bloodhunter4rc** [elgatito/plugin.video.elementum#74]
## Expected Behavior
Keep Downloading when the video is paused or video is exited should keep downloading

## Current Behavior
Downloading stops but Uploading continues after pausing the video, stays on state "queued" if video is resumed it downloads again normally.

Also happens when exiting and Choosing "Keep Downloading" Torrent is stuck at same percentage but uploading continues.

## Steps to Reproduce (for bugs)

1. Start Streaming
2. Pause
3. Check State on gui or torrent info web , peers connected but Downloadpercentage does not increase
4. Resume -> Starts Downloading again

## Your Environment
Kodi 17 , Elementum V0.0.34
Android, Storage system : File Storage

Exit the Stream and "Keep Downloading" selected.

[kodi.log](https://github.com/elgatito/plugin.video.elementum/files/1661702/kodi.log)

different file but same effect (Stuck with 80 active peers and in kodi log "Queued"):
[torrentinfo.txt](https://github.com/elgatito/plugin.video.elementum/files/1661706/torrentinfo.txt)

**Comment by Bloodhunter4rc** [comment]
Looks like the memory storage buffer is used for file storage , after that it doesnt download anymore if paused.

**Comment by elgatito** [comment]
> Looks like the memory storage buffer is used for file storage , after that it doesnt download anymore if paused.

For memory storage that is expected behavior, because we should not block memory for non-active torrents. Otherwise we can kill the device. 
Elementum can play multiple videos at a time, but they should be active.

**Comment by Bloodhunter4rc** [comment]
Yes but i use file storage option, so this should not happen also when changing the memory storage option to use x megabyte of memory storage to 9999999 and then switching to file storage, downloading is lot faster when using file storage.

**Comment by elgatito** [comment]
Any change to storage settings (download path, memory size, type of storage) needs torrent client restart, which currently does not save previous list of torrents.

List will be reloaded, for non-memory storage, in future versions, there is a ticker for that already.

**Comment by Bloodhunter4rc** [comment]
true thats the reason , after kodi restart its downloading in the background
