### ISSUE TITLE
Next Page (2) is showing at the beginning of Trakt.tv trending movies  (see attached picture)

### ISSUE THREAD

**Issue by ShlomiD83** [elgatito/plugin.video.elementum#745]
tried several skins and always the "next page" is at the beginning instead at the end of the movie list..
is this a bug?

![image](https://user-images.githubusercontent.com/17053215/116594738-3999ca00-a92b-11eb-8ee3-ac0d2af99fc7.png)

**Comment by antonsoroko** [comment]
i guess you changed "sort by" from "default" to any other type. (b/c it works for default for me but not for others types)
probably a bug, but might a limitation as well. i have not checked the code yet.

**Comment by elgatito** [comment]
Change sort for that list to Default.

**Comment by ShlomiD83** [comment]
I've already tried that, didn't help.

**Comment by antonsoroko** [comment]
did you change sort and then went back and forward again? it will not update screen unless you do that.

**Comment by ShlomiD83** [comment]
I'll try again..

**Comment by antonsoroko** [comment]
@elgatito just out of curiosity - is it fixable or it is well known limitation?

**Comment by ShlomiD83** [comment]
> did you change sort and then went back and forward again? it will not update screen unless you do that.

I changed it to default and re-entered the category and now it's ok.

**Comment by antonsoroko** [comment]
@elgatito 
i mean, i just noticed that changing sort order does not affect the position of this item - it is always on top.
even for "name" which I expected to work. (other things like date probably also could work, genre might be tricky).

**Comment by elgatito** [comment]
"Previous" or ".." is not what we insert, it is inserted by Kodi when you go to any page from current page.

**Comment by antonsoroko** [comment]
I meant `Next Page (2)` item
