### ISSUE TITLE
[Question] returning seeds/peers

### ISSUE THREAD

**Issue by D4anielCB** [elgatito/plugin.video.elementum#747]
Hi, Im wondering if this is possible to integrate elementum to another addon, i have a list of magnet urls and i'd like to return its seeds/peer, or if not is there any api that i could use to do so?
Thanks

**Comment by D4anielCB** [comment]
Found this one: https://checker.openwebtorrent.com/check?magnet=

**Comment by elgatito** [comment]
@D4anielCB No, Elementum does not have that.

**Comment by antonsoroko** [comment]
@D4anielCB maybe close this one?

**Comment by D4anielCB** [comment]
> @D4anielCB maybe close this one?

Yes, thank you both

**Comment by antonsoroko** [comment]
@D4anielCB close the issue please :-)
