### ISSUE TITLE
[Request] Add button to reset Library/Torrent path in Kodi settings

### ISSUE THREAD

**Issue by dankec2000** [elgatito/plugin.video.elementum#76]
In settings: When choosing download path to device which you cannot use, f.i., some folder on non-mapped NAS you cannot go back to f.i. folder on internal memory.

The only solution is to load default settigs and set it all over again.

Maybe to implement "load default settings" for each tab, not for the whole settings?

**Comment by ziiky** [comment]
I noticed that too!

**Comment by elgatito** [comment]
I don't know what you talk about.

If you select click library/download path and that does not work well for you - you can raise a ticket in Kodi issue tracker. Plugin is not doing anything with it.

**Comment by dankec2000** [comment]
No, after choosing inaproriate device Elementum (as Quasar) tells that you cannot use f.i. network drive. Ok. But now you cannot set it back to f.i. /system/downloads (it won't let you for some reason)

**Comment by elgatito** [comment]
If would be helpful if anyone read the rules and include kodi.log or provide any information/screenshot when creating an issue.

**Comment by dankec2000** [comment]
Only a video could help. No use of screenshot or kodi logs in this case (You should try it for yourself)

**Comment by ziiky** [comment]
I will upload short video in few mins...

**Comment by dankec2000** [comment]
Exactly!

**Comment by elgatito** [comment]
> https://youtu.be/AWvXL1XR3Eo

As I have said before, this selection is done by Kodi. Plugin only checks selected path if it's writable and shows a warning if not.

**Comment by dankec2000** [comment]
In Quasar you COULD choose another path (if warning message appears).
In Elementum not.
So, how it's done by Kodi?

**Comment by elgatito** [comment]
Elementum is checking selected in settings path when you save settings. If not writable - you are returned to settings window to change that.

How do you expect it to be?

**Comment by dankec2000** [comment]
Yes, you are returned to settings window to change that, **but you cannot choose another device anymore (you cannot revert back as it was before)**

That was said from the beginning...

**Comment by elgatito** [comment]
Plugin is not setting any settings (we can, but we don't), user does that in Settings windows, controlled by Kodi. Plugin is only checking *saved* settings. 
Changing, reverting, and other things that you do with settings - is not under control of a plugin.

When you open settings - Kodi is controlling it.
When you click the path to change it - Kodi is controlling and showing you the file browser.
When you click "Save/OK" - Kodi is saving settings and sending plugin notification about saved settings.

**Comment by dankec2000** [comment]
Then Quasar is communicating with outher space in this segment because it's working fine there.
But never mind, thanks for your effort, Elementum is great addon and I already migrated to it (from Quasar).

Good luck in future!

**Comment by elgatito** [comment]
Button added to latest versions.
