### ISSUE TITLE
After restart, torrents are not pulled up in the "use memory" mode

### ISSUE THREAD

**Issue by slavatyn** [elgatito/plugin.video.elementum#765]
I use  elementum 0.77 "memory mod" on android tv.
When i choose "download torrent" in Elementum context helper, its works good, i can watch downloaded film in library, and see downloaded torrent in elementum menu.
But after restarting kodi, all downloaded movies and torrents remain in place, but elementum no longer sees previously downloaded torrents.  Because of this, the previously downloaded file is ignored and memory is used again.  As far as I understand, this is due to the fact that in the "use memory" mode, the bittorrent setting is ignored> add torrents from the torrents folder at startup

**Comment by antonsoroko** [comment]
@slavatyn 
you could use search.
https://github.com/elgatito/plugin.video.elementum/issues/666

please close this issue and join conversation in aforementioned issue.

btw, we have a dev build, so you know your platform (e.g. windows_x64, or provide a log file), we can give you a dev buuild to test.
