### ISSUE TITLE
Andriod tv low download speed, crash/lags on online

### ISSUE THREAD

**Issue by slavatyn** [elgatito/plugin.video.elementum#772]
Добрый!
на Windows всё хорошо, а в android tv постоянно что-то не так( 
Использую sony bravia - там вроде чистый android 9
Подключён зарегистрированный usb hdd 1tb (лежал всё время без дела, всего ему ~2 года)
В настройках elementum торренты\файлы\библиотека загружаться туда
Использую режим памяти

1. При попытке в режиме онлайн посмотреть фильм 4к ~60гб
Либо периодически сильно тормозит, 
(могу выцепить лог)
Но чаще kodi или elementum крашиться спустя 1-2 мин просмотра
https://drive.google.com/file/d/1iFpvB8ejdBjOTVPdl-O48lFxOXo9tkSf/view?usp=sharing

2. При Cotex menu elementum - Скачать фильм тот-же торрент
Либо скачивается 1-20% затем происходит краш elementum, при этом можно перегрузить коди и скачается дополнительно ~20%
(могу выцепить лог)
Но чаще скорость около нулевая 300б\сек-20кб\сек и при попытке закрыть kodi, он крашиться
https://drive.google.com/file/d/11_TUE21c2L2LUKasGghzlUSRfho-HSXN/view?usp=sharing
Следом я перегружаю android, захожу в коди, скачка начинает разгоняться, но через пару сек опять падает до около нулевых
https://drive.google.com/file/d/1LpCaawEOTkwHGXy1_9Xo4nJVDXO491Ee/view?usp=sharing

На всякий случай напишу, если фильм удалось полностью скачать на hdd, всё работает отлично
И вроде с меньшим объёмом и разрешением, проблема случается реже (но это не точно)
Тестировал тот-же самый фильм на windows, там всё работает

**Comment by antonsoroko** [comment]
panic не видно в логах, и только в 'kodi (онлайн просмотр).log' есть 2 рестарта, но без причины.
может оперативная память заканчивается и андроид просто убивает процесс.
было бы интересно посмотреть вывод `dmesg` в консоли, сразу после перезапуска елементума.
https://www.xda-developers.com/how-to-take-logs-in-android/

без него не сказать точно.


если заморачиваться не хочется, то можно попробовать уменьшить потребление памяти элементумом в его настройках - может быть поможет. но это я наугад. лог файлы супер большие, я их не читал, а только искал по ключевым словам.

**Comment by slavatyn** [comment]
Думал уже рутить но сильно повезло, похоже нашёл проблему, смогу протестировать на следующей недели
Вроде сходиться, даже в простое fps при скачке торрента на 12мб\сек прыгает и рандомно крашиться
Источник: https://4pda.to/forum/index.php?showtopic=684033&st=60#entry80734090

Что бы на наших телевизорах смотреть 4K HDR фильмы с высоким битрейтом (торренты размером более 40Гб) нужно следующее:
1. HD VideoBox Pro версия (цена ~150 рублей)
Это каталог с фильмами в котором реализован удобный поиск торрент фильмов.
2. ViMu Media Player for TV (цена ~125 рублей).
Это плеер который имеет отличную буферизацию что сглаживает косяки интернета/локальной сети. В плеере нужно выставить размер буфера 80мб.
3. TorrServe (Бесплатно).
Это непосредственно программа которая качает торренты и сразу же отдаёт видеопоток вашему плееру.
Приложение состоит из двух частей (Клиент и Сервер).

Многие сталкиваются с тем, что "тяжелые" фильмы тормозят и глючат.
Причина проста:
Общая нагрузка на процессор устройства высокая (телевизор не осиливает одновременно закачку торрента и воспроизведение 4К фильма). И это можно решить перенеся функции сервера на стороннее устройство.


Если у вас нет стороннего устройства (NAS/Компьютер/Смартфон с 5Ггц Wi-Fi/Шустрая приставка на Android) на которое можно перенести сервер, то для вас есть только одно решение:
Смотрите BD-Rip или купите телевизор модельного года 2019+


Если стороннее устройство есть, то:
Клиент устанавливаете на Телевизор, а Сервер на внешнее устройство под которое есть Сервер тут: https://github.com/YouROK/TorrServer/releases
О том, как устанавливать сервер на ваше устройство лучше уточнять в профильной ветке TorrServe

Так же Сервер можно установить на смартфон. Устанавливает так же как на телевизор (сначала ставите Android клиент, потом закидываете в папку Download сервер, после во вкладке Обновления в TorrServe устанавливаете из папки Download сервер).

Что бы клиент работал с сервером, который установлен на другое устройство нужно в Клиенте на телевизоре указать IP адрес вашего устройства куда установили Сервер (В главном меню слева сверху, там по умолчанию у вас стоит http://localhost:8090).
Настройки подбираете согласно мощности процессора вашего устройства. Например у меня на NAS QNAP TS-269L стоят следующие настройки:
Размер кэша: 600
Размер буфера предзагрузки: 100
Отключить UTP
Отключить Отдачу
Количество соединений: 40

Как определить какой максимальный размер торрента вы сможете смотреть со своей скоростью интернета?
Берёте скорость своего интернета и делим на 8. Например 100мбит/с делим на 8 и получаем 12,5 мегабайт в секунду вы сможете скачивать. Средний фильм длится ~90 минут. 90 умножаем на 60 = 5400 секунд. Теперь умножаем 12,5 мегабайт (ваша скорость) на 5400 секунд (длительность фильма). = 67 500 мегабайт. Делим на 1024 и получаем ~66Гб. Вот с интернетом 100мбит/с потолок это примерно 66Гб файлы.

**Comment by slavatyn** [comment]
Настроил NFS сервер на windows, попробовал подключить папку хранения файлов elementum на него, но высветилась ошибка, что сетевые ресурсы не поддерживаться(

**Comment by antonsoroko** [comment]
@slavatyn 
nfs сервер это не тоже самое, что торрент сервер. (но если сможете сделать nfs подключение не через коди - будет работать и на nfs, но вряд ли это что-то даст).
они предлагают поставить TorrServe на отдельную машину, а на телевизор только клиент TorrServe.

вообще, тоже самое можно сделать и с elementum, но там есть нюансы так как elementum бинарь зависит от kodi.
по факту надо настроить elementum на запуска как клиент, и "Удаленный хост" выставить ip сервера на котором будете запускать elementum. (последняя вкладка)
потом на сервере запустить бинарь елементума:
`путь/к/elementum -localHost=0.0.0.0 -remoteHost=IP_OF_CLIENT_WITH_KODI`

ещё надо создать download path как настроено на клиенте (в настройках елементума) и на сервере (надо узнать полный путь к папке на клиенте и создать такую же папку на сервере - с связкой андроид и винда не уверен что выйдет, из-за разницы в концепции путей, android+linux работает, я когда то делал).

но возможно, будут какие-то мелкие косяки в плане юзабилити. данный функционал давно не развивался.

больше инфы тут
https://github.com/elgatito/plugin.video.elementum/issues/2

**Comment by antonsoroko** [comment]
попробуйте всё таки снять dmesg и подкрутить настройки памяти елементума, убивается процесс я думаю именно из-за нехватки памяти.
а вот если есть тормоза - то да, это уже к процу (или диску, но наверно не в вашем случае) и тут или смотреть менее "пафосные" рипы :-) или использовать отдельный сервер.

**Comment by slavatyn** [comment]
По 1 проблеме.
Очень помог этот гайд - "Улучшаем производительность ваших телевизоров отключая рекламные приложения"
https://4pda.to/forum/index.php?showtopic=684033&st=60#entry80380007
С 30 fps на некоторых кадрах в стабильные 60... магия, весь андройд гораздо живее теперь чувствует.
Также очистил кэш kodi через настройки android и проверял на основном профиле (2ой заруинился(с него тестировал раньше) после того как elementum попросил через nfs работать и убил процесс kodi) может что-то из из этого повлияло на всякий пишу, может поможет кому.
До этого пробовал память менять, вроде не помогало, в характеристиках тв 2.5 гб пишется.

2ую проблему хочу заново зафиксировать.
Нажимая просто смотреть фильм, всё хорошо скорость сразу поднимается до высокой.

> От сюда стартанул лог: 

Но через - Cotex menu elementum - Скачать фильм
скорость долго держится 300б\сек-20кб\сек

> Это основная проблема, дальше просто доп. инфо

выбираю выход из kodi
kodi зависает
убиваю процесс kodi через меню android

> Тут лог наверно закончен
[kodi (медленная скачка, краш после закрытия коди).log](https://github.com/elgatito/plugin.video.elementum/files/6605099/kodi.log)

Андройд начинает дико тормозить, до полной перезагрузки, при этом процесса kodi уже нет

**Comment by antonsoroko** [comment]
@slavatyn 

>скорость долго держится 300б\сек-20кб\сек

судя по логу у вас стоит использовать память, хотя у вас есть внешний hdd.
когда вы делаете download - используется hdd, соотв надо время на создание файла. 
как только запустите скачивание - посмотрите в папку с загрузками, я думаю увидите, что он потихоньку создаётся и соотв в это время скорость низкая. по крайней мере так у меня.

в логе краша нету. но если файл ещё не создался, а вы выходите - он скорее всего не выйдет пока не создаст файл до конца.

ещё на скорость выхода влияет кол-во трекеров.
если "Добавлять доп. трекеры" стоит в "Все известные трекеры" и торрентов много, то будет долго выходить, до нескольких минут.
можно выбрать меньшую опцию, или отключить вообще.
из старых торрентов автоматом добавленные трекеры не удалятся уже, но можно поставить "Модифицировать трекеры в торренте"="Каждый раз" и тогда они перезапишутся, а потом можно или вернуть в "В момент добавлении" если хочется.

**Comment by slavatyn** [comment]
Я сегодня немного психанул и сбросил на заводские всё и вся, судя по всему не зря)
Вероятно причина в следующем:
Вместо "Очистить и форматировать как память устройства" я выбрал "Зарегистрировать HDD", на него в папку kodi всё записывалось, но похоже что неэффективно.

> в логе краша нету. но если файл ещё не создался, а вы выходите - он скорее всего не выйдет пока не создаст файл до конца.

Да, очень похоже на то

> когда вы делаете download - используется hdd, соотв надо время на создание файла.
ещё на скорость выхода влияет кол-во трекеров.
если "Добавлять доп. трекеры" стоит в "Все известные трекеры" и торрентов много, то будет долго выходить, до нескольких минут.
можно выбрать меньшую опцию, или отключить вообще.
из старых торрентов автоматом добавленные трекеры не удалятся уже, но можно поставить "Модифицировать трекеры в торренте"="Каждый раз" и тогда они перезапишутся, а потом можно или вернуть в "В момент добавления" если хочется.

Перед всем этим я специально удалил все торренты, кэш чтобы оставить только 1 этот торрент, но перед тем как выйти из около нулевой скорости проходило 5-10 минут, собственно по этой причине я перешёл на "использовать память".
После этого скорость держалась максимум на 17мб

В итоге после сброса, этот-же фильм, практически сразу разгоняется до 27мб

Что-то из этого или всё вместе помогло
1. Вместо "Зарегистрировать HDD" > "Очистить и форматировать как память устройства"
2. Само приложение kodi с elementum переехало с внутренней памяти устройства на HDD
3. Сброс настроек elementum до заводских с минимальными изменениями
4. Сброс Kodi до заводских (это врядли)

Спасибо за помощь!

**Comment by antonsoroko** [comment]
>Вместо "Зарегистрировать HDD" > "Очистить и форматировать как память устройства"

интересно, что оно работало вообще. у меня 9й андроид не позволял писать на винт когда он просто подключён как переносной, а не отформатирован системой. и даже при форматировании писать может только в папку kodi, аля `Android/data/org.xbmc.kodi/files/downloads`.

кстати, раз у вас hdd - есть смысл поставить "использовать файлы" вместо памяти, и делать доброе дело - сидировать.
с памятью - только короткая отдача во время просмотра, что не оч хорошо.

**Comment by antonsoroko** [comment]
хотя я вот сейчас заметил у вас тоже `/storage/XXX/Android/data/org.xbmc.kodi/files/`. 

а во что был отформатирован hdd? не fat32 же? там макс размер файла 4гб.

но мой андроид например не поддерживал ntfs и ext4, поэтому только фоматироание помогло.

**Comment by slavatyn** [comment]
> а во что был отформатирован hdd? не fat32 же? там макс размер файла 4гб.

В ntfs

> но мой андроид например не поддерживал ntfs и ext4, поэтому только форматирование во внутренний помогло.

Оно к лучшему как раз) Похоже форматирование во внутреннюю память для android более френдли

**Comment by antonsoroko** [comment]
пора все эти вещи в FAQ добавить уже наверное.
аля https://github.com/elgatito/elementum-surge/pull/2
