### ISSUE TITLE
Elementum crashing on mi box s 

### ISSUE THREAD

**Issue by FKOV** [elgatito/plugin.video.elementum#775]
Elementum is crashing every time , I open it on mi box s
Here is the kodi log: 
https://paste.kodi.tv/loqoxayahe

**Comment by elgatito** [comment]
@FKOV There is no error in the log. You can try to run manually elementum from ssh (when Kodi is running).
Run this binary file: `/data/data/org.xbmc.kodi/files/plugin.video.elementum/bin/android_arm/elementum`

**Comment by FKOV** [comment]
I will try it tomorrow and let you know, thanks

**Comment by antonsoroko** [comment]
also, could you please set log level in elementum to debug? at least for future logs.

**Comment by elgatito** [comment]
Closing due to no response.
