### ISSUE TITLE
Playback suddenly interrupts

### ISSUE THREAD

**Issue by avoidik** [elgatito/plugin.video.elementum#78]
## Expected Behavior
Playback whole file from start to end

## Current Behavior
Playback suddenly interrupts in the middle

## Possible Solution
None

## Steps to Reproduce (for bugs)
Usual playback from magnet link

## Context
None

## Your Environment
* Version used: 0.0.34, 0.0.35, 0.0.36
* Environment name and version: Kodi 16.1
* Operating System and version: Android 4
* Link to Kodi debug log: (issue at the end of the log) http://rgho.st/8pG8snpcl
```
23:15:24 T:1929507320  NOTICE: [plugin.video.elementum] INFO  bittorrent   ▶ UpdateWatched    [0mCurrently at 56.186532%, KodiID: 0
23:15:24 T:1929507320  NOTICE: [plugin.video.elementum] INFO  main         ▶ Notification     [0mStopped at 56.186532%
```
I didn't stopped it myself.

## Additional info
I've tried to change the memory buffer sizes without any luck. Right now configuration is following:
- cache memory buffer in advancessettings.xml is set to 50MB
- ram memory buffer in Elementum is set to 200MB
- cache in Bittorrent settings in Elementum is set to 50MB

**Comment by elgatito** [comment]
Can you do the following.

When Kodi player get paused (before it stops the playback), open http://127.0.0.1:65220/info (insert Kodi IP if Kodi not on local host), and save the output of a page somewhere. That is needed to see the status of a torrent engine.

**Comment by avoidik** [comment]
I'll try to catch this moment, but the problem is that sometimes it works, and sometime interrupts, so it's hard to predict which playback will interrupt.

**Comment by jorgecardoso220** [comment]
Any solution for this problem? its happening with me too.

**Comment by avoidik** [comment]
Here is the info right before interrupt
https://pastebin.com/9ngsrASX

**Comment by avoidik** [comment]
Btw it is the torrent with multiple files

**Comment by avoidik** [comment]
And I've updated plugins versions

**Comment by elgatito** [comment]
Have you tried with default memory size of 100mb? 
In the log everything is fine. That is a known issue, and nobody knows why that happen.

**Comment by elgatito** [comment]
@avoidik Any  updates? Should we close the issue?

**Comment by elgatito** [comment]
Closing without response.
