### ISSUE TITLE
Try to set IDs for ListItems generated by elementum to easily use them in context menu

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/plugin.video.elementum#783]
## Expected Behavior

if we can store IDs (e.g. tmdb id) then we can use them in context menu plugin w/o any hacks.

## Current Behavior

currently in context menu plugin in order to support  ListItems generated by elementum we have to parse `path` and then we have to convert acquired information to real tmdb id (since path does not have id for episode and season, only for show and movie). this is very hacky and incovenient.

## Possible Solution

`count | integer (12) - can be used to store an id for later, or for sorting purposes`
https://codedocs.xyz/AlwinEsch/kodi/group__python__xbmcgui__listitem.html#ga0b71166869bda87ad744942888fb5f14

`Function: setUniqueIDs(values, defaultrating)`
`Sets the listitem's uniqueID`
https://codedocs.xyz/AlwinEsch/kodi/group__python__xbmcgui__listitem.html#ga7fc2ecd77b8d0032cc68eee6b4c9d6a2

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

**Comment by elgatito** [comment]
@antonsoroko make sure to target API for Kodi16. It is used by SPMC, so is pretty popular.

**Comment by antonsoroko** [comment]
i also used to use spmc, but beta version - 17.6
in case of 16 - it is sad since `setUniqueIDs`/`getUniqueID` were introduced only in 17

https://github.com/xbmc/xbmc/commit/f438970acb9bfc8646e91f298c62e8a786e72551

**Comment by elgatito** [comment]
@antonsoroko that is why where are checks for Kodi version in `navigation.py` that remove fields that cause Python Errors in old Kodi.

**Comment by antonsoroko** [comment]
I mean, we still can use it, but I also wanted to remove all hacks for elementum items in context plugin and context.go. But I guess we have to keep them untill Kodi 16 is completely gone.

Would be nice if we had some statistics about about Kodi versions and OSes that use elementum :-)
