### ISSUE TITLE
Make repository.elementum independent from elementum

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/plugin.video.elementum#788]
## Expected Behavior

Repo should be independent from elementum. Now if elementum is down because of some issue - repo also is down, so there is no way to install a new version with a fix for that issue.

## Current Behavior

сейчас при установке дополнение устанавливает repository.elementum, который ведет на сам elementum, который запрашивает xml готовый с гитхаба.
Но если elementum не работает то и репо не работает.
вот здесь https://github.com/elgatito/elementum-surge/blob/master/generate.sh просто берется последний релиз и пишется в гитхаб, чтоб его потом можно было скачать.

## Possible Solution

лучше было бы просто сразу делать из всего этого готовый архив-репозиторий и при установке просто ссылку на него давать.
https://github.com/ElementumOrg/elementumorg.github.io/tree/master/packages/elgatito
Можно оставить всё как есть для старых версий, и добавить сборку репозитория и хранение его в готовом виде.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

**Comment by elgatito** [comment]
@antonsoroko I cannot see the way to say Kodi link for each addon in repository, it expects to find addon in `datadir`.
I think it is possible to move the addon proxy code to python, in that way python part is always running, even without binary, so repository will work properly.

**Comment by elgatito** [comment]
@antonsoroko In latest version of plugin.video.elementum we download binary directly from github, if it is missing locally, so we can include "client" version of Elementum (without any binary) is a regular repository.
It will update in a usual way and then download new binary file automatically for that platform.

**Comment by antonsoroko** [comment]
very nice! (i have seen new code, but have not really dig into how it works yet)

**Comment by antonsoroko** [comment]
seems to be fixed.
