### ISSUE TITLE
v0.1.79 ERROR : TypeError: Failed to convert to input type to either a std::string or a std::vector

### ISSUE THREAD

**Issue by SubEdict** [elgatito/plugin.video.elementum#793]
After v0.1.79 update **All** the links will failed with message:
ERROR <general>: TypeError: Failed to convert to input type to either a std::string or a std::vector

* Link to Kodi debug log:

[el0.1.79_kodi19.log](https://github.com/elgatito/plugin.video.elementum/files/6683161/el0.1.79_kodi19.log)
![failedtoconvert](https://user-images.githubusercontent.com/36477829/122689759-c6774a80-d22d-11eb-9473-d4b83b383bb4.gif)

**Comment by slavatyn** [comment]
Same problem-android tv
[kodi (2).log](https://github.com/elgatito/plugin.video.elementum/files/6683182/kodi.2.log)

**Comment by SubEdict** [comment]
Downgraded and Re-install v0.1.78 for now (Auto update off), works perfect.

**Comment by MichaelAndoid** [comment]
Same problem here Android TV 7.
How can i downgrade?

**Comment by antonsoroko** [comment]
as an intermediate fix (while waiting for new release) - you can replace local file with https://raw.githubusercontent.com/elgatito/plugin.video.elementum/ac90c292bcde6cb8ff6ff00a71db6183381d8c2c/resources/site-packages/elementum/navigation.py

**Comment by SubEdict** [comment]
> as an intermediate fix (while waiting for new release) - you can replace local file with https://raw.githubusercontent.com/elgatito/plugin.video.elementum/ac90c292bcde6cb8ff6ff00a71db6183381d8c2c/resources/site-packages/elementum/navigation.py (with the same path of course)

Thanks guys for the quick fix.  Did a copy-paste to navigation.py, restart Kodi and all good now.

**Comment by antonsoroko** [comment]
new elementum release is live. please test.

**Comment by antonsoroko** [comment]
sorry guys. 0.1.80 has new issue. my fault.
intermediate fix - https://raw.githubusercontent.com/elgatito/plugin.video.elementum/79679c5c6533c1da9d5b4a10e5103d3492b8cb41/resources/site-packages/elementum/navigation.py

**Comment by antonsoroko** [comment]
0.1.81 should be ok.
please try.

**Comment by SubEdict** [comment]
3 hours on 0.1.81, works great. Thanks again for the lightning speed of updates.

*Some issue when playing seasons pack and using Up Next ...But I won't open or post an issue yet, not today :)
Future test: Continuous playing Season pack: Second episode always freeze and stopped after 10 minutes (even when cache is 100% full and ready).

**Comment by slavatyn** [comment]
> 3 hours on 0.1.81, works great. Thanks again for the lightning speed of updates.

Join here!

**Comment by antonsoroko** [comment]
Thank you for testing.

>Some issue when playing seasons pack and using Up Next

i do not use this feature, but some latest changes might have affected it. feel free to post an issue (with debug enabled bot in kodi and elementum).

>Future test: Continuous playing Season pack: Second episode always freeze and stopped after 10 minutes (even when cache is 100% full and ready).

hm. nothing changed in terms of downloading. so it maybe some old issue that came out now. and i guess you use memory (since you said cache) - i am not familiar with that part of the code since i use files. maybe author will be able to help.
