### ISSUE TITLE
failed to convert input type error when playing any video 0.1.79

### ISSUE THREAD

**Issue by ShlomiD83** [elgatito/plugin.video.elementum#797]
Hi All,
since updating to 0.1.79 on windows x64 I can't play any video (movie or tv show).
this doesn't happen on 0.1.78.

kodi 18.9 on windows 10 x64

https://zerobin.net/?26c11ba06bebf6c6#eEr8VKVs9822eJAu7u0pCX2cgDXmwUWhQtQB3h2jZBo=

please advise.

**Comment by dzervas** [comment]
I too have this and it was fixed with a downgrade to 1.0.78

**Comment by antonsoroko** [comment]
Please see https://github.com/elgatito/plugin.video.elementum/issues/793

New release will fix it, proper intermediate fix described in that issue.

**Comment by ShlomiD83** [comment]
thank @antonsoroko
