### ISSUE TITLE
Library does not update

### ISSUE THREAD

**Issue by torbvea** [elgatito/plugin.video.elementum#8]
## Expected Behavior
Library should update with new episodes when they air.

## Current Behavior
Library does not add new episodes.

## Context

I have added a few tvshows to the library, but when new episodes are released the library will not update to add the new episodes

## Your Environment

* Version used: Windows x64 0.0.12

* Environment name and version: Kodi 17.6

* Operating System and version: Windows 10

* Link to Kodi debug log: http://paste.ubuntu.com/26112212/

**Comment by elgatito** [comment]
What is your TV Shows scrapper, selected in Elementum settings?

**Comment by torbvea** [comment]
The TVDB, but it seems like it is working now. It was only with one tvshow(the walking dead) but it is now syncing after I re-added the show to the library

**Comment by elgatito** [comment]
Plugin takes information about new episodes from TMDB database, so expect people filled in information about TVDB id, your log says there is no ID yet. That should probably be the problem.
