### ISSUE TITLE
Seems the readme is outdated, not working on kodi kodi 17 and Android 4.4.2

### ISSUE THREAD

**Issue by leozanelato** [elgatito/plugin.video.elementum#806]
Tried lastest versions with no luck, always give me the popup "elementum is starting"

I am using a tv Box with Android 4.4.2 and official kodi 16 and 17.1 mygica, but elementum seems to not work anymore. 

Tried because the readme says It works with Android 4.4+ and kodi 16... 

Even with a clean install with only the elementum and Burst addon It dont start... Always give the "elementum is starting" popup.

Is there anything i can do to make this work? I dont wanna buy a newer device because this have a satelite receiver built in.

**Comment by elgatito** [comment]
@leozanelato android 4.4 is too old. You can try earlier releases.
Read this thread - https://github.com/elgatito/plugin.video.elementum/issues/576
