### ISSUE TITLE
No download on android device

### ISSUE THREAD

**Issue by atomizasser** [elgatito/plugin.video.elementum#81]
Hello.
I've tested last version, 0.0.37 on Android device 7.0 with Kodi Leia 18 (nightly version).
Elementum is set in file mode (stored in usb) but torrent doesn't start. Load peers and seeds but not buffering. After this is not possible to stop torrent loading and if you try to delete manually from Kodi's file explorer, Kodi crashes.

Attached, log from kodi and info from torrent engine.

[info.txt](https://github.com/elgatito/plugin.video.elementum/files/1675421/info.txt)
[kodi.log](https://github.com/elgatito/plugin.video.elementum/files/1675422/kodi.log)

**Comment by elgatito** [comment]
It looks like the issue with the storage.
Can you try the memory storage? Or you have issue only with files?

**Comment by atomizasser** [comment]
Hello.
I only have issue with file storage, memory mode works perfectly (and it is very very fast, but my hardware is not enough to play bluray remux in memory mode).

**Comment by elgatito** [comment]
Not sure I can help with that. 

Downloading/reading is done by torrent engine and there is nothing special with files processing, can be some limitations with android in general.

**Comment by syneox** [comment]
Did you created a folder structure on usb flash before adding it as a storage? Does it work when you use Internal Storage? You may have problem with file/folder permissions.

**Comment by atomizasser** [comment]
The files are stored on:
/storage/(usb-id)/Android/data/org.xbmc.kodi/files

**Comment by atomizasser** [comment]
Files are stored at:
/storage/(usb-id)/Android/data/org.kodi.com/files

Maybe i have to create another structre?

**Comment by syneox** [comment]
mine is /storage/(usb-id)/Android/data/org.kodi.com/files/Elementum but I don't think adding Elementum will solve it for you since you are already writing inside Kodi data folder.

If Internal Storage is working for you I guess your device usb subsytem is not working correctly, maybe try different usb flash or just use Memory option

**Comment by atomizasser** [comment]
I've tested internal storage and it works.
However in USB flash drive and USB-HDD, one format in ExFat and other in NTFS it did'nt work.
I will try to format usb drive as internal memory and store there torrent

**Comment by compyy** [comment]
It is a known issue, its android limitation, actually downloading does start but after quite sometime, somehow full dump file has to be created before downloading starts, and if file is bigger and USB is slow it takes ages, Quasar had a fix for it but it is still not perfect.

Perfect solution is to have very fast SSD in USB 3.1 GEN 2 adapter which i am using and you wont have this issue.

**Comment by syneox** [comment]
Which android device you are using with usb 3.1 support?

**Comment by atomizasser** [comment]
I think there's a workaround for the problem. If formated a dedicated USB as "internal storage". Now the USB memory and internal android memory is fusioned and i cannot see my USB. If I select /storage/0/Android/Downlad as path to store files, Elementum start to download cache and it is possible to play a movie. I've tested with large file like 4K movies, that is bigger than internal SonyTV memory and Elementum don't warm any missatge about "limted filesize of storage". I don't know if Android can recognize the filesize of the file and make the cache on USB, maybe during playback of a 4K movie when the cache is over, the playback will end.

I have to continue testing.

**Comment by syneox** [comment]
@atomizasser 

yes, that seems to do the trick, I remember trying this before on some earlier versions of Elementum but it was not working.

Now I get speeds up to 4000kB/s with healthy torrents, however, upload is stil at 0kB/s. Maybe it's worth saying that for me upload never worked.

**Comment by elgatito** [comment]
@syneox, enable upnp and set seed time to be not 0 and it will work, I have checked it yesterday

**Comment by syneox** [comment]
@elgatito 

I never touched upnp, always using those default settings but I have set seed time to 1 and upload started! Thank you, Elementum is getting better day by day!

Also, I have formatted USB drive as internal storage inside Android and I had to move files to USB drive after that, only now, files are being downloaded to USB drive. I will test more and post any findings...

**Comment by elgatito** [comment]
@syneox , upload got better with latest versions, especially the torrent engine, we use.

Android is much permissioned OS, so some basic things are faulty there, that is why, probably the best and the fastest storage there will be memory. And it is doing upload now. No so good as it is with files, but at least something.

Are we closing this issue?

**Comment by syneox** [comment]
Sorry for late comment, I am absolutely satisfied with Memory Storage performance on my Android TV box, Xiaomi MIBOX3.

I don't even need file storage option anymore, so if you ask me, issues are resolved.

**Comment by acsterf** [comment]
@atomizasser how did you manage to  mount a USB external storage as internal?

@elgatito as long saving to an external storage suffers from low speed download (AFTV 2nd), saving to memory works great! Wonder if it is possible to dump and save the files from memory to an external storage.

**Comment by elgatito** [comment]
I'm closing this issue. 
File storage is done by Torrent library (which is located at https://github.com/anacrolix/torrent ). 
And there is an issue for Android slow download - https://github.com/anacrolix/torrent/issues/234
