### ISSUE TITLE
[Question] Why advancedsettings.xml act diffrently in Elementum than on other addons?

### ISSUE THREAD

**Issue by SubEdict** [elgatito/plugin.video.elementum#811]
## Expected Behavior
*First of all I would like to apologize up ahead for this confusing "for dummies" subject. :)

In Kodi I'm using this advancedsettings.xml for all addons and it works great, all video start and keep caching in 10 seconds 30%-40% forward, so there's never a buffering issue.
`<advancedsettings>
  <cache>
    <memorysize>278921216</memorysize>
    <readfactor>12</readfactor>
  </cache>
</advancedsettings>`

But on Elementum all I get from this is: Load at start 300MB to RAM before playing and when playing only keep loading forward the same very small 8-9MB. (Why?)

All setting in El' are on default with only a little change on the start 50MB instead of 20MB. **I see it doesn't really matter when using advancedsettings anyway.

So.. My question: Is there a way to keep loading/caching to RAM more (in my case 300MB forward) while playing like I see on my other regular addons?

*Edit: BTW, I know about the option to disable advancedsettings in the setting.

PC Win7/10 x64, 4GB RAM, 1GB Fiber Lan.

UPDATE: Added [image link](https://imgur.com/gallery/Who6GAv)
Thanks

**Comment by elgatito** [comment]
@SubEdict `advancedsettings.xml` is a customization for Kodi player, it has nothing to do with addons.
You are setting buffer for loading stream data.

Amount of memory in Elementum is used to store upcoming bytes. When piece of data is given to Kodi - we remove it from Elementum memory and request next piece. Elementum tries to use all possible memory for upcoming data. That is why if you seek back then Kodi will wait till we re-download deleted pieces of data and give it to Kodi.

**Comment by SubEdict** [comment]
> ..Kodi player, it has nothing to do with addons. ...You are setting buffer for loading stream data.

Yes, thanks for the replay. Ok, for the player not the addons but still, the upcoming data to buffer ahead is the amount that I write in advancedsettings.xml so the player show on all addons the right amount of buffer (almost 300MB upcoming data).

> Elementum tries to use all possible memory for upcoming data

Interesting. So when I see on the player timeline little to none upcoming data buffer (in grey) that load only the next 10-20 seconds that's actually all I got left to store from my 4GB RAM?

*All of these questions are just because all the hottest most trending new 4K  with 1000+/3000+ seeders/lechers start to buffer and I just trying to give the buffer ahead a little more upcoming data. Everything else work great.

**Comment by elgatito** [comment]
@SubEdict 
> so the player show on all addons the right amount of buffer (almost 300MB upcoming data).

No, player does not expose those values to anyone. Elementum is reading `advancessettings.xml` directly from disk.

>  So when I see on the player timeline little to none upcoming data buffer (in grey) that load only the next 10-20 seconds that's actually all I got left to store from my 4GB RAM?

Bigger buffer size in Kodi should load more butes in memory and help when bitrate is changing often or your internet is not constant. 
If you use memory storage - you should increase memory size in Elementum if you target big file sizes. More torrent pieces you can store - more speed you can gain.

**Comment by SubEdict** [comment]
I'm not using storage just the default setting RAM (Auto). Do I need  to config and use storage now with those big files?

I can see the starting load go up to 15MB with no problem so looks like the 1GB internet bandwidth works good, It's just later on the buffer suddenly start showing drops to let's say 500k/b and after 8-10 seconds back to full 8-15MB download.
So.. With the default setting of El' I can't "help" the buffer with advancedsettings.xml?

**Comment by elgatito** [comment]
@SubEdict 

>  It's just later on the buffer suddenly start showing drops to let's say 500k/b and after 8-10 seconds back to full 8-15MB download.

You need to watch percent of completion. When all the memory is used - you are not downloading anything and waiting for player to get data from elementum. When data is given - you download next pieces. More pieces you can store - more contant playback you will have.

**Comment by SubEdict** [comment]
I do look.
Avg total usage when playing 4k (O key): 66-75%
Task Manager: Elementum 1.3GB, Kodi 700MB, System 1.2GB.
Doesn't look so drastic like "out of memory" issue. Is there anything else I can do maybe in the setting?

**Comment by elgatito** [comment]
@SubEdict I'm talking about Elementum overlay status, that you see when you pause playback in Kodi.
It shows amount of memory used in total and percentage of downloaded. In a perfect world you would see almost 100% all the time, that means you always have pretty much ready-to-read pieces of torrent and won't see lags.

**Comment by SubEdict** [comment]
When I pause (because frame freeze) that's where I see the drop to 500Kb with 5%-10% cache buffer and after a few seconds back to 4-6-10MB.. to full 99%.

So to sum it up, Elementum already using the max RAM it can get to cache more up ahead pieces.
Setting more cache to the memory in advancessettings.xml for the player won't help because El' already handle the max RAM he can get. ..ya?

**Comment by SubEdict** [comment]
Hmm.. Saw a couple of discussions about some 4k Dolby Atmos freeze and drop bandwidth because some issue with Kodi 19.1 and will be fix in 19.2 so maybe it's not Elementum fault at all.

Decided to turn off advancedsettings.xml as it's looks like El' already doing the best memory/cache calculation ..I think?
_"I'm giving it all she's got, captain!"_

Downloaded the latest Kodi nightly build. Looks like the first well seeded 4k, 40min' file was ok_'ish_ (one little buffering at the first 3 minutes and smooth play after that).

@elgatito Really appreciate the time and effort you took trying to explain it to me this embarrassing subject.
