### ISSUE TITLE
panic: Success

### ISSUE THREAD

**Issue by axelsimon** [elgatito/plugin.video.elementum#817]
Hello,

Elementum appears not to be working anymore on CoreELEC 19.2-Matrix_rc2.

It was working fine until not long ago (i know, don't we all say that).

I've enabled debug logging, and all i can see in the logs that looks relevant is this:

> 
> 2021-07-30 00:01:25.379 T:28212 WARNING <general>: [plugin.video.elementum] INFO  bittorrent   ▶ AddTorrent       .[0mSetting sequential download to: true
> 2021-07-30 00:01:25.379 T:28212 WARNING <general>: [plugin.video.elementum] INFO  bittorrent   ▶ AddTorrent       .[0mAdding new torrent item with url: /storage/.kodi/temp/elementum_torrents/7bec122ce4dd8b6d9540
> e80e8f26fe542ee44893.torrent
> 2021-07-30 00:01:25.379 T:28212 WARNING <general>: [plugin.video.elementum] INFO  bittorrent   ▶ NewTorrent       .[0mAdding torrent with storage: File
> 2021-07-30 00:01:25.379 T:28212 WARNING <general>: [plugin.video.elementum] INFO  bittorrent   ▶ loadTorrentFiles  .[0mLoading torrent file f52012e3d76c81b6ecf505cc04dfee6b76b0f6bc.torrent
> 2021-07-30 00:01:25.380 T:28212 WARNING <general>: [plugin.video.elementum] INFO  bittorrent   ▶ AddTorrent       .[0mAdding torrent from /storage/.kodi/temp/elementum_torrents/f52012e3d76c81b6ecf505cc04dfee6b76
> b0f6bc.torrent
> **2021-07-30 00:01:25.380 T:28212 WARNING <general>: [plugin.video.elementum] panic: Success**
> 2021-07-30 00:01:25.383 T:28140   ERROR <general>: CCurlFile::FillBuffer - Failed: Server returned nothing (no headers, no data)(52)
> 2021-07-30 00:01:25.383 T:28140   ERROR <general>: CCurlFile::Open failed with code 0 for http://127.0.0.1:65220/repository/elgatito/plugin.video.elementum/addons.xml.md5:
>                                                    
> 2021-07-30 00:01:25.383 T:28140   ERROR <general>: CFileCache::Open - <http://127.0.0.1:65220/repository/elgatito/plugin.video.elementum/addons.xml.md5> failed to open
> 2021-07-30 00:01:25.383 T:28140   ERROR <general>: CRepository: failed read 'http://127.0.0.1:65220/repository/elgatito/plugin.video.elementum/addons.xml.md5'
> 2021-07-30 00:01:25.383 T:28212 WARNING <general>: [plugin.video.elementum] 
> 2021-07-30 00:01:25.384 T:28212 WARNING <general>: [plugin.video.elementum] System information: linux_armv7 
> 2021-07-30 00:01:25.385 T:28212 WARNING <general>: [plugin.video.elementum] Kodi build version: 19.1 (19.1.0) Git:fb3ff50005b8afdec70f9e53a4d87504a4850d55
> 2021-07-30 00:01:25.385 T:28212 WARNING <general>: [plugin.video.elementum] OS type: Linux
> 2021-07-30 00:01:25.386 T:28212 WARNING <general>: [plugin.video.elementum] uname: uname_result(system='Linux', node='kodisambard', release='4.9.113', version='#1 SMP PREEMPT Sun Jun 6 11:49:21 CEST 2021', machine
> ='armv7l', processor='')
> 2021-07-30 00:01:25.602 T:28143   ERROR <general>: CCurlFile::Open failed with code 404 for https://raw.githubusercontent.com/kodinerds/repo/master/addons.xml.md5:
>                                                    
> 2021-07-30 00:01:25.602 T:28143   ERROR <general>: CFileCache::Open - <https://raw.githubusercontent.com/kodinerds/repo/master/addons.xml.md5> failed to open
> 2021-07-30 00:01:25.602 T:28143   ERROR <general>: CRepository: failed read 'https://raw.githubusercontent.com/kodinerds/repo/master/addons.xml.md5'
> 2021-07-30 00:01:26.128 T:28140 WARNING <general>: Repository add-on repository.elementum uses plain HTTP for add-on downloads in path http://127.0.0.1:65220/repository/elgatito/ - this is insecure and will make y
> our Kodi installation vulnerable to attacks if enabled!
> 2021-07-30 00:01:27.328 T:28546    INFO <general>: Skipped 2 duplicate messages..
> 2021-07-30 00:01:27.328 T:28546    INFO <general>: initializing python engine.
> 2021-07-30 00:01:29.351 T:28546    INFO <general>: CPythonInvoker(21, /storage/.kodi/addons/script.embuary.info/default.py): script successfully run
> 2021-07-30 00:01:30.476 T:28212 WARNING <general>: [plugin.video.elementum] elementumd: starting elementumd
> 2021-07-30 00:01:30.478 T:28181    INFO <general>: JSONRPC Server: New connection added
> 2021-07-30 00:01:30.479 T:28181    INFO <general>: JSONRPC Server: Disconnection detected
> 2021-07-30 00:01:30.479 T:28212 WARNING <general>: [plugin.video.elementum] Kodi's JSON-RPC service is available, starting up...
> 2021-07-30 00:01:30.526 T:28546    INFO <general>: Python interpreter stopped
> 2021-07-30 00:01:30.530 T:28212 WARNING <general>: [plugin.video.elementum] Binary detection. Source: /storage/.kodi/addons/plugin.video.elementum/resources/bin/linux_armv7/elementum, Destination: /storage/.kodi/u
> serdata/addon_data/plugin.video.elementum/bin/linux_armv7/elementum
> 2021-07-30 00:01:30.531 T:28212 WARNING <general>: [plugin.video.elementum] Deleting stale files set()
> 2021-07-30 00:01:30.532 T:28212 WARNING <general>: [plugin.video.elementum] Binary detection: [ Source: /storage/.kodi/addons/plugin.video.elementum/resources/bin/linux_armv7/elementum, Destination: /storage/.kodi
> /userdata/addon_data/plugin.video.elementum/bin/linux_armv7/elementum ]
> 2021-07-30 00:01:30.532 T:28212 WARNING <general>: [plugin.video.elementum] Binary dir: /storage/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_armv7, item: /storage/.kodi/userdata/addon_data/plugin.vi
> deo.elementum/bin/linux_armv7/elementum 
> 2021-07-30 00:01:30.532 T:28212   ERROR <general>: [plugin.video.elementum] Existing process found from lockfile, killing...
> 

Eventually, we reach something ilke
> 2021-07-30 00:38:33.546 T:32054   DEBUG <general>: [plugin.video.elementum] elementumd: no attempts left

So it looks like it loads, goes through most of startup, then dies (panic: Success), then tries to load a few more times until giving up.

This, earlier in the log, may also be useful:
> 2021-07-30 00:38:04.183 T:31993   DEBUG <CAddonSettings[plugin.video.elementum]>: trying to load setting definitions from old format...

I realised that debug logging is only enabled for Kodi, not Elementum. I will get a log with that enabled too, tomorrow.

## Steps to Reproduce (for bugs)
Honestly, no idea. I wish i could say.

## Context
I believe Elementum was recently updated to 0.1.83. (the files in .kodi/addons/plugin.video.elementum are dated from the 18th of July)

## Your Environment

* Version used: 0.1.83

* Environment name and version: 19.1.0

* Operating System and version: CoreELEC 19.2-Matrix_rc2 on arm v7 (ODROID N2)

* Link to Kodi debug log: i can share a full debug log if necessary

**Comment by elgatito** [comment]
@axelsimon That is probably an error from libtorrent. Elementum Debug log needed to see the problem.

**Comment by elgatito** [comment]
@axelsimon Closing because of a missing log.

**Comment by axelsimon** [comment]
Hi @elgatito, sorry for not providing the log in time. I completely understand you closing the issue.
Here's a quick summary of what happened in the past month.

- I eventually moved `.kodi/userdata/addon_data/plugin.video.elementum/` to a backup directory and restarted Kodi: Elementum came back up fine.
- Then my Kodi system (CoreELEC 19.2-Matrix_rc2, rc3 after August 5 or so) crashed, and the same problem happened: Elementum tries to start multiple times and eventually gives up.
- I've hade multiple crashes since, and each time Elemetum fails to start after. I've moved the corrupted elemenum add-on directory out of the way each time, and i now have a collection of 5 crashed Elementum add-on directories (and multiple `.parts` files in my download path).

I currently have debug logs enabled but right now, as Elementum is working, the log shows nothing helpful. I will restore the original corrupted dir and get the Kodi debug log, so this can be investigated.

**Comment by axelsimon** [comment]
Here is a log that contains the dreaded `elementumd: no attempts left`:
https://paste.kodi.tv/sosodoseka.kodi

**Comment by elgatito** [comment]
@axelsimon You binary is killed by something or has some kind of an error.
You can try to run the binary manually from ssh.
`/storage/.kodi/addons/plugin.video.elementum/resources/bin/linux_armv7/elementum`

**Comment by antonsoroko** [comment]
will turning on libtorrent logs give more info? elementum log messages mystically end.

**Comment by elgatito** [comment]
They end because most probably process will killed.

**Comment by axelsimon** [comment]
I was able to look into this again tonight.
After a `chmod +x` on the elementum binary, I was able to start it manually and discovered that it crashes with the `Panic Success` message after trying (and failing) to load a torrent from `.kodi/temp/elementum_torrents/` (or maybe `.kodi/temp/elementum/` wasn't able to capture the log.

I've removed the file that was causing elementum to `panic: Success` and it started fine after. If this happens again, i'll check if it's the same problem. What is strange is that while i removed the `.kodi/userdata/addon_data/plugin.video.elementum` directory after Elementum/Kodi crashes (which would make Elementum start again), until today i'd never removed any saved torrent file. So something in the plugin settings would change and prevent Elementum from starting.

@elgatito Does this help? Could you reopen the issue?
