### ISSUE TITLE
Torrent resolving issue

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#819]
Hi,

Some of the torrents doesn't play.
I took a one case, for example: Money Heist S03E01

Kodi Debug Log:
https://paste.ubuntu.com/p/Mbk6WvXwmM

Thanks.

---
Elementum version: 0.1.83
Kodi 17.6

**Comment by antonsoroko** [comment]
>22:39:07.061 T:14012  NOTICE: [plugin.video.elementum] ERRO  bittorrent   ▶ WaitForMetadata  Expired timeout for resolving magnet link for 40 seconds

this magnet does not work for me in even in qbittorrent from 2 different locations in europe (vpn), so this is looks like not an elementum issue - probably no real seed (tracker website can show anything) or traffic to them are blocked.

**Comment by ShlomiD83** [comment]
@burekas7 maybe it's an issue on your end, I can play Money Heist S03E01 just fine.
![image](https://user-images.githubusercontent.com/17053215/132130601-4ec91edd-8432-4ade-9890-b37c00dabb07.png)

**Comment by burekas7** [comment]
@ShlomiD83 
I know I could choose another torrent from the list,
I was curious why this one for example didn't work, because it happens more lately then before.

**Comment by ShlomiD83** [comment]
@burekas7 the magnet to tried to play indeed doesn't work, not in Elementum or qBittorrent.
It's not an Elementum issue, it's a specific torrent issue.

**Comment by burekas7** [comment]
Yes, it seems that sometime the tracker's website return false data as anton said.
