### ISSUE TITLE
Looks like Elementum is still Starting up

### ISSUE THREAD

**Issue by RafaelGodoyEbert** [elgatito/plugin.video.elementum#821]
daemon error: b "filenotfounderror"(2, 'no such file or directory') elementum

KODI 19.1 Matrix (Batocera on RaspBerry Pi 3 Model B+)
I tested the versions installed on zip:  
Elementum  -	0.1.83;
			0.1.82;
			0.1.81;
			0.1.80;
			0.1.76;
And still with the same error

I deleted the .kodi\userdata\addon_data\plugin.video.elementum\bin\linux_armv7\elementum
and nothing happens

Can someone help me?

LOG
`

> 2021-09-07 14:34:01.116 T:1903  WARNING <general>: [plugin.video.elementum] elementumd: starting elementumd
> 2021-09-07 14:34:01.117 T:1662    DEBUG <general>: JSONRPC Server: New connection detected
> 2021-09-07 14:34:01.117 T:1662     INFO <general>: JSONRPC Server: New connection added
> 2021-09-07 14:34:01.117 T:1902  WARNING <general>: [plugin.video.elementum] elementum: starting jsonrpc service
> 2021-09-07 14:34:01.118 T:1662     INFO <general>: JSONRPC Server: Disconnection detected
> 2021-09-07 14:34:01.119 T:1903  WARNING <general>: [plugin.video.elementum] Kodi's JSON-RPC service is available, starting up...
> 2021-09-07 14:34:01.129 T:1903  WARNING <general>: [plugin.video.elementum] Binary detection. Source: /userdata/system/.kodi/addons/plugin.video.elementum/resources/bin/linux_armv7/elementum, Destination: /userdata/system/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_armv7/elementum
> 2021-09-07 14:34:01.131 T:1903  WARNING <general>: [plugin.video.elementum] Updating elementum daemon...
> 2021-09-07 14:34:01.315 T:1903  WARNING <general>: [plugin.video.elementum] Deleting stale files set()
> 2021-09-07 14:34:01.316 T:1903  WARNING <general>: [plugin.video.elementum] Binary detection: [ Source: /userdata/system/.kodi/addons/plugin.video.elementum/resources/bin/linux_armv7/elementum, Destination: /userdata/system/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_armv7/elementum ]
> 2021-09-07 14:34:01.317 T:1903  WARNING <general>: [plugin.video.elementum] Binary dir: /userdata/system/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_armv7, item: /userdata/system/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_armv7/elementum 
> 2021-09-07 14:34:01.320 T:1903    DEBUG <general>: [plugin.video.elementum] Checking for visible
> 2021-09-07 14:34:01.364 T:1903  WARNING <general>: [plugin.video.elementum] elementumd: start args: ['/userdata/system/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_armv7/elementum'], kw: {'stdout': -1, 'stderr': -2, 'cwd': '/userdata/system/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_armv7', 'env': {'LD_LIBRARY_PATH': '/userdata/system/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_armv7:/usr/lib/mysql', 'SHELL': '/bin/sh', 'RUNLEVEL': 'S', 'LANGUAGE': '', 'PWD': '/userdata', 'dev': 'LABEL=BATOCERA', 'HOME': '/userdata/system', 'LANG': 'en_US.UTF-8', 'SDL_NOMOUSE': '1', 'TERM': 'linux', 'INIT_VERSION': 'sysvinit-', 'SHLVL': '2', 'XDG_RUNTIME_DIR': '/var/run', 'LC_ALL': 'en_US.UTF-8', 'CONSOLE': '/dev/console', 'PREVLEVEL': 'N', 'PATH': '/sbin:/usr/sbin:/bin:/usr/bin', 'DBUS_SESSION_BUS_ADDRESS': 'unix:path=/run/dbus/system_bus_socket', 'OLDPWD': '/', '_': '/usr/lib/kodi/kodi.bin', 'KODI_BIN_HOME': '/usr/lib/kodi', 'KODI_HOME': '/usr/share/kodi', 'OS': 'Linux', 'TZ': ':America/Sao_Paulo', 'LIRC_SOCKET_PATH': '/var/run/lirc/lircd', 'PYTHONOPTIMIZE': '1', 'GODEBUG': 'madvdontneed=1'}, 'close_fds': True}
> 2021-09-07 14:34:01.430 T:1903    ERROR <general>: Exception in thread 
> 2021-09-07 14:34:01.430 T:1903    ERROR <general>: Thread-2
> 2021-09-07 14:34:01.430 T:1903    ERROR <general>: :
>                                                    
> 2021-09-07 14:34:01.430 T:1903    ERROR <general>: Traceback (most recent call last):
>                                                    
> 2021-09-07 14:34:01.430 T:1903    ERROR <general>:   File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
>                                                    
> 2021-09-07 14:34:01.433 T:1903    ERROR <general>:     
> 2021-09-07 14:34:01.433 T:1903    ERROR <general>: self.run()
> 2021-09-07 14:34:01.433 T:1903    ERROR <general>: 
>                                                    
> 2021-09-07 14:34:01.433 T:1903    ERROR <general>:   File "/usr/lib/python3.9/threading.py", line 892, in run
>                                                    
> 2021-09-07 14:34:01.436 T:1903    ERROR <general>:     
> 2021-09-07 14:34:01.436 T:1903    ERROR <general>: self._target(*self._args, **self._kwargs)
> 2021-09-07 14:34:01.436 T:1903    ERROR <general>: 
>                                                    
> 2021-09-07 14:34:01.436 T:1903    ERROR <general>:   File "/userdata/system/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/daemon.py", line 298, in elementumd_thread
>                                                    
> 2021-09-07 14:34:01.438 T:1903    ERROR <general>:     
> 2021-09-07 14:34:01.438 T:1903    ERROR <general>: proc = start_elementumd(stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
> 2021-09-07 14:34:01.438 T:1903    ERROR <general>: 
>                                                    
> 2021-09-07 14:34:01.438 T:1903    ERROR <general>:   File "/userdata/system/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/daemon.py", line 255, in start_elementumd
>                                                    
> 2021-09-07 14:34:01.439 T:1903    ERROR <general>:     
> 2021-09-07 14:34:01.440 T:1903    ERROR <general>: return subprocess.Popen(args, **kwargs)
> 2021-09-07 14:34:01.440 T:1903    ERROR <general>: 
>                                                    
> 2021-09-07 14:34:01.440 T:1903    ERROR <general>:   File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
>                                                    
> 2021-09-07 14:34:01.443 T:1903    ERROR <general>:     
> 2021-09-07 14:34:01.444 T:1903    ERROR <general>: self._execute_child(args, executable, preexec_fn, close_fds,
> 2021-09-07 14:34:01.444 T:1903    ERROR <general>: 
>                                                    
> 2021-09-07 14:34:01.444 T:1903    ERROR <general>:   File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
>                                                    
> 2021-09-07 14:34:01.448 T:1903    ERROR <general>:     
> 2021-09-07 14:34:01.449 T:1903    ERROR <general>: raise child_exception_type(errno_num, err_msg, err_filename)
> 2021-09-07 14:34:01.449 T:1903    ERROR <general>: 
>                                                    
> 2021-09-07 14:34:01.449 T:1903    ERROR <general>: FileNotFoundError
> 2021-09-07 14:34:01.449 T:1903    ERROR <general>: : 
> 2021-09-07 14:34:01.449 T:1903    ERROR <general>: [Errno 2] No such file or directory: '/userdata/system/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_armv7/elementum'
> 2021-09-07 14:34:01.449 T:1903    ERROR <general>: 

`

**Comment by antonsoroko** [comment]
did you use plugin.video.elementum-0.1.83.zip or plugin.video.elementum-0.1.83.linux_armv7.zip ? if 2nd - try 1st.

also please provide output of
`tree /userdata/system/.kodi/userdata/addon_data/plugin.video.elementum/`
and
`tree /userdata/system/.kodi/addons/plugin.video.elementum/resources/bin/`
(if `tree` is not installed - install it)

also **full** log file would be useful: http://elementum.surge.sh/contribute/log/

**Comment by RafaelGodoyEbert** [comment]
I tested plugin.video.elementum-0.1.83.zip and plugin.video.elementum-0.1.83.linux_armv7.zip, but same error.

log
[kodi.log](https://github.com/elgatito/plugin.video.elementum/files/7124974/kodi.log)
how i provide output of the tree?

**Comment by antonsoroko** [comment]
via terminal (if you have direct access, e.g. keyboard is connected) or ssh (if no direct access).

i am not familiar with Batocera but they have wiki pages, e.g.
https://wiki.batocera.org/access_the_batocera_via_ssh

in addition, please also run commands below **after** you run kodi with elementum:
```
uname -a
chmod +x /userdata/system/.kodi/addons/plugin.video.elementum/resources/bin/linux_armv7/elementum
/userdata/system/.kodi/addons/plugin.video.elementum/resources/bin/linux_armv7/elementum
chmod +x /userdata/system/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_armv7/elementum
/userdata/system/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_armv7/elementum
```

**Comment by RafaelGodoyEbert** [comment]
I managed to open it by SSH

Did not work!

[kodi.log](https://github.com/elgatito/plugin.video.elementum/files/7130810/kodi.log)
![image](https://user-images.githubusercontent.com/78083427/132557745-6141d42a-acc1-46e5-882c-d1dfdee5fc77.png)

**Comment by RafaelGodoyEbert** [comment]
I solved the problem by downgrade the BATOCERA system from 32 to 30. BATOCERA 31 does not have KODI and 32 KODI still has problems.

**Comment by nabeko2146** [comment]
In case anyone else runs into this problem, it is likely caused by incorrect architecture.

Installing the All-in-one Elementum on RPi4 w/ 64-bit Manjaro results in the same error.
Attempting to install the arm64 package doesn't work; it insists on armv7.
What does work very simply is installing All-in-one, and replacing armv7 with arm64:

    $ cp .kodi/addons/plugin.video.elementum/resources/bin/linux_arm64/elementum \
         .kodi/addons/plugin.video.elementum/resources/bin/linux_armv7/elementum
    $ rm .kodi/userdata/addon_data/plugin.video.elementum/bin/linux_armv7/elementum

Start or restart Kodi and Elementum will work!

---

I am not sure if this is wrong for all arm64 systems or if the addon performs some unique Raspberry Pi detection that doesn't support 64-bit. Working 64-bit support for RPi4 (including hardware acceleration) is very new, and its under this context my issue occurred. The OP may have also been using a 64-bit OS (Pi3B is 64-bit capable also).

**Comment by borzaka** [comment]
Thank you @nabeko2146, it worked on my ODROID N2+ with Ubuntu 22.04 as well!
