### ISSUE TITLE
Elementum showing wrong Seeds number?

### ISSUE THREAD

**Issue by GitujMe** [elgatito/plugin.video.elementum#822]
I search for an Movie, or TV Show, most of torrents are 300+ seeds, yes there are also lower ones like 20, 5, even 1.

I choose the 300+ Seeds torrent and while Elementum is buffering it in reality the Torrent actually has only couple Seeders like 2 or 3. How and why?

Have I accidentally set an limit or? Pretty much whatever I choose I have only up to 5 Seeders, it's really difficult to watch anything. I choose the currently most popular movie from trending, it shows 5000+ Seeders, I open the file I get below 10 Seeders. :(

**Comment by antonsoroko** [comment]
Do you mean you connect to 5 seeds or you see 5 seeds in total?
There are limit settings, for connections for example, these can affect how to how many seeds you will connect.
Also you might disabled some protocols.

Also try via VPN - maybe your ISP block something. Or via different bittorrent client but on same device.

**Comment by GitujMe** [comment]
> Do you mean you connect to 5 seeds or you see 5 seeds in total?
> There are limit settings, for connections for example, these can affect how to how many seeds you will connect.
> Also you might disabled some protocols.
> 
> Also try via VPN - maybe your ISP block something. Or via different bittorrent client but on same device.

Both actually. After I choose a torrent from the list I usually see up to 5 seeds and I usually connect to the same number. But, when Elementum shows the list of torrents after it scrappes them from my selected sources they are full of seeders. Let's say you pick a movie with 1080p ######## (5355/1340), after I select the file when buffering it shows like S:4/P:2 and download is so slow. How it can find so low number of seeds?

I checked the settings, I am not sure what setting refers for connection limit. Maybe I accidentally set the limit? I want to unlock it fully, if an file has 5000+ seeds I want to be open to all seeds, it's like Elementum picks randomly up to 5 of them and sometimes it works while sometimes those 3-5 seeds are not enough even for 5GB movie. And this happens to every single Movie or TV Shows, nonetheless is it 1990s movie or movie which released yesterday and currently is TOP trending with #### of Seeders.

Maybe I should just reset Elementum settings but still, would like to know what exactly I messed up here.

It's Kodi Matrix btw, it's still fresh, all I remember I set up in Elementum is Trakt, I don't think I've set any limit for seeds.

**Comment by antonsoroko** [comment]
If you don't want to re-configure from scratch - you can try reset settings only on bittorent tab. And maybe other torrent/connections related settings in other tabs if they are there by some legacy reasons (I do not remember thb).

But to be honest it looks more like ISP issue.

1. try via VPN - maybe your ISP blocks something. 
2. try via different bittorrent client but on same device.

**Comment by elgatito** [comment]
@GitujMe Elementum shows you number of seeds, you are connected to, and total number of seeds. That is a real information, gathered from trackers/DHT.

What sites show about torrent - is not always true, they can show any numbers.
