### ISSUE TITLE
Question regarding the Kodi Library integration

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#823]
Hi,

In the old Quasar addon I set the Quasar addon data folders to be as a video source, and set Kodi Library for that.
So when I want to add an item from my Trakt Collection inside Quasar. I selected it and chose from the context menu the option of add them to the library (or Remove).
But here with Elementum it seems that the entire Trakt Collections content are added automatically to the Elementum addon data folders on each startup (What I don't want to)
I don't want that all the Collection will be in my Kodi Library, only some of them as it worked in Quasar, when I select them manually from the Trakt Lists .

How should I set that in the settings?

Thanks.

**Comment by elgatito** [comment]
@burekas7 

> I don't want that all the Collection will be in my Kodi Library, only some of them as it worked in Quasar, when I select them manually from the Trakt Lists .

It is not possible, and that is a proper behavior. Everything from collection is added to Kodi library, unless Trakt sync is disabled.

**Comment by burekas7** [comment]
@elgatito 

I think the meaning of the "My Collection" as its name, to collect them, it doesn'e mean that your are actually watching them or going to. If I want to watch them I will add them to Kodi Library.
In addition, Kodi has a built-in option in their context menu of "Add to library / Remove from library", so it's there for a purpose.

Why is it not possible to make an option of selecting an item in the collection, choose "Add to library" from the context menu and it will create and add a folder with an strm file in it in the Elementum Library path? (Instead of sync the entire Collection)

There is additional option I can think of which is less preferred:
Add an multiple selection option so the user can choose the source of Elementum sync: By Collection / By List, and if choosing a list so a new option will be visible for selection the specific list, so the filtering will be actually by Trakt? 
(And if so, in addition add an option in the context menu of "Add/Remove from a list)

**Comment by elgatito** [comment]
> In addition, Kodi has a built-in option in their context menu of "Add to library / Remove from library", so it's there for a purpose.

There is no built in option to add something to the library.

When you add something to the library FROM Elementum, it adds that item to either Collection or Userlist or Watchlist on Trakt, if that is enabled in settings.

**Comment by burekas7** [comment]
@elgatito 

So I think you're pretty nuch changed the meaning of "Kodi Library".
On every other Video Addon, the option of "Add to Library" means "Add to **Kodi** Library" and not "Trakt List".
And the actuall action is add to the path you have set as a Movie/Shows Kodi library paths, an item (Folder + Subfolder(For TVShows) + strm file/s) according to the selection (It could be from any Trakt list in the addon etc...)

Then setting these paths as a video sources and set their contents as "Movies/Shows" and define their scrappers.
So when you "Add to Library" and choose "Scan for new content" it adds it to Kodi Library.
Without any connection to Trakt list. Kodi Library should be independent and rely only by the path you set for him to create the kodi library items.
If you want to add an item to any Trakt List (Collection, Watchlist, Customlist etc..) so add options for "Add to Trakt Collection / List ... " (I can show you how it done by one of the addons I have for example)

If I flow with your thought, so why do I need the "Kodi Library" if you define that all the collection content will be synced to my local userdata in order to set it as a kodi library? I can just go to "Trakt -> My Collection" inside Elementum.

**Comment by antonsoroko** [comment]
I think there is some kind of miscommunication.

There is "Add to Library" menu item and it adds item from Trakt to Kodi's library. At least as far as i remember. Please correct me if i am wrong.

About collection - you can simply turn off sync of collection to kodi in settings (trakt tab). And if i stated above is correct - then you can do what you wanted - add items to kodi from collection manually.

Did you explore sync related settings? I think what you want can be simply configured.

**Comment by burekas7** [comment]
@antonsoroko 
Thanks now it's ok.

But I have a question:
What is the difference between:
(1) Kodi Library -> Maintenance -> Enable Kodi Synchronization
- and - 
(2) Trakt -> Synchronization - > sync items from collections / watchlist / userlist into Kodi Library?

When I set all the three options of **(2)** to **False** and **(1)** is **True**, I still get content from somewhere,
When I set **(1)** to **False** and all the three options of **(2)** to True, I still get content from somewhere,
Only when I set **(1)** to **False** and all the three options of **(2)** to False, It's ok.

And by the way:
What does "Trakt -> Sync hidden items" means?

**Comment by antonsoroko** [comment]
iirc
1. in general write .strm files to specified directory (then you add this directory to kodi's library in kodi's settings)
2. sync specific lists (they all basically are lists) to directory specified above

>I still get content from somewhere

iirc, that's because elementum will not delete .strm files if you simply disable these options. you need to delete content  (generated .strm files) in  "specified directory" manually. these options will simply stop add new .strm files (no sync basically).

>What does "Trakt -> Sync hidden items" means?

search is useful :-)
https://github.com/elgatito/plugin.video.elementum/issues/290


>Can I sync my Kodi Library path with a specific Trakt List that I created?
>In Elementum there is an option to add an item to a specific Trakt List?

i do not remember. take a look into the settings.
there are settings to choose custom lists for sync.
then you can manually add to this list i think via menu.
and if "sync items from userlist" is enabled it also will be automatically synced (but not sync might be not bidirectional, i read a code at some point but i do not really remember and since i do not use kodi library - i can't say for sure).
but in general - there are a lot of settings - try them first.

**Comment by burekas7** [comment]
@antonsoroko 
> iirc, that's because elementum will not delete .strm files if you simply disable these options. you need to delete content (generated .strm files) in "specified directory" manually. these options will simply stop add new .strm files (no sync basically).
I know, I deleted the content before each trying, so I didn't know why I still get content in the first two tryings, and when both option are disabled it was ok.

Regarding the rest, thanks, I will check and update.

**Comment by antonsoroko** [comment]
>when both option are disabled it was ok

Then I remember wrong. We need to check the code for how these options are used to know the answer for sure.

**Comment by burekas7** [comment]
@antonsoroko 

1) Regarding the manual addition to Kodi Library:
After selecting the "Add to Library" in the context menu, the item is add to the library folder, 
But when selecting the same item again and checking the context menu, it doesn't change to "Remove from Library", it still shows the option as "Add to Library". (I know there is an option of removing the the item from Kodi Library (And its files from the folder) by Kodi context menu inside the Library by "Managed...". But I guess there should be also the option of "Remove from Library" as I said)

2. Regarding the automatic sync option of a **Trakt specific list -> Kodi Library**:
It seems that there is no such an option.
There is only a plural option of "Trakt -> Synchronization - > sync items from **userlists** into Kodi Library"
You can't select a specific list, it probably sync with all of them.

The options of selecting a specific list that are exist are for sync is for the reverse direction of Add/Remove items for Kodi Library -> Trakt List.

**Comment by antonsoroko** [comment]
"Remove from Library" should work. at least it worked for me. but for it to work - integration with kodi library should be enabled first.

But your initial question was about "In Elementum there is an option to add an item to a specific Trakt List?" as i can see.

there are menu items to add to collection and to watchlist, but i guess not to userlist.

**Comment by burekas7** [comment]
@antonsoroko 

1) Regarding the **"Remove from Library"**, I see what is the problem:
- If I want it to be able to know if an item is already exists, I need to enable the setting of "Enable Kodi library synchronization", but as I said, when I enable that I get all my collection (+old items that I have already added & removed from it in the past, I don't know why) inside Elementum library path, a behavior that I don't want to. So when doing that I loss the ability of add items manually.
- What I want is the ability to add an item manually to Elementum library path + The ability of the Kodi library synchronization so I will be able to see the "Add/Remove from library" option correctly.

Currently, in order to get what I want, this is what I need to do:
- Kodi Library -> Maintenance -> Enable Kodi Synchronization - **False**
- Trakt -> Synchronization - > sync items from collections / watchlist / userlist into Kodi Library - **False**
- Add to library - **Elementum context menu**
- Remove from library - **Kodi context menu: "Manage... -> Remove from library"** * (Need to enable the option of delete files in Kodi Settings)
(Because it always shows "Add" in Elementum context menu)

2) Regarding the second issue of option to sync a specific user list / lists:
Can you considere it as a request? (Or should I make it as a seperate request/issue for that?)
The request is:
Add an option for selecting a single Trakt User List or multiple selection of lists option (For Shows and Movies) for sync them from Trakt to Kodi Library.

3) Maybe it's a bug or something else that I still don't understand, as I said,
Why when selecting only this option of "sync items from user lists into Kodi library" to be enabled,
I get all the shows that I have ever added to the Collection (Shows that I added in the pase and have already removed them)

**Comment by antonsoroko** [comment]
>If I want it to be able to know if an item is already exists, I need to enable the setting of "Enable Kodi library synchronization", but as I said, when I enable that I get all my collection

this is strange. if you enabled library synchronization but did not enable sync of collection - collection should not be synced.

>Can you considere it as a request? (Or should I make it as a seperate request/issue for that?)

i would suggest to create a separate issue, since here we already started to discuss many different things.

>Shows that I added in the pase and have already removed them

i do not really understand what you mean. all item from trakt Collection will be added when you are enable sync. So if you added item year ago, then removed, then enabled sync - item will not be in collection at the time of sync, thus will not be in kodi.
although i must mention that i do not remember if we delete item from kodi if you deleted it from trakt. as i mentioned there was some nuances. but this only affect library after you enabled sync and lived with this option enabled for some time. if we do not delete - then clean of path and elementum cache probably would remove old items completely.

**Comment by burekas7** [comment]
@antonsoroko 

`this is strange. if you enabled library synchronization but did not enable sync of collection - collection should not be synced.`

Exactly, I already mentiond this case in this comment:
https://github.com/elgatito/plugin.video.elementum/issues/823#issuecomment-918648895

`i would suggest to create a separate issue, since here we already started to discuss many different things.`

OK.

```
i do not really understand what you mean. all item from trakt Collection will be added when you are enable sync. So if you added item year ago, then removed, then enabled sync - item will not be in collection at the time of sync, thus will not be in kodi.
although i must mention that i do not remember if we delete item from kodi if you deleted it from trakt. as i mentioned there was some nuances. but this only affect library after you enabled sync and lived with this option enabled for some time. if we do not delete - then clean of path and elementum cache probably would remove old items completely.
```

I will give you a numeric exmaple.
My TV Shows Trakt Collection has only 52 items,
When I enable the "Enable Kodi library synchronization" and: 
sync items from collections into Kodi Library - Disabled - I'm getting 54 items.
sync items from collections into Kodi Library - Enabled - I'm getting 57 items.
These extra items are TV Shows that I added in the past and in some point removed them from the collection.
So I don't why and how Elementum still gets them?
I did "Clear Trakt cache" but still the same.

**Comment by antonsoroko** [comment]
>Exactly

create a separate issue for that maybe. with info only about that issue.

>So I don't why and how Elementum still gets them

no idea. maybe check https://trakt.tv/settings/hidden and other pages in trakt. maybe you will find something strange that could explain this.

another guess would be: elementum will not sync episodes and seasons from collection since there are no such separate types in kodi. only shows and movies. so if you go to https://trakt.tv/users/USER/collection and filter out seasons/episodes - how many movies and shows you get? how many movies and shows you get in kodi after sync?

**Comment by antonsoroko** [comment]
@burekas7 any new info with what I described above?

**Comment by burekas7** [comment]
@antonsoroko
Hi, I hope to check the Trakt issue soon. I will update when I have some findings.

**Comment by burekas7** [comment]
@antonsoroko 

The shows that exist in the "hidden" section are not including in the external shows that fetched from Trakt to Kodi.
But this is regarding to the option when "Sync Trakt Collection" is enabled.
Regarding to the case when all trakt options are disabled I opened a bug.

And the numbers are the same as described above.

**Comment by antonsoroko** [comment]
@burekas7 i think this issue also can be closed.
as you recently learned in #825 your items were still syncing because they were in elemenum library. you need to remove items from elementum library as elgatito said.
