### ISSUE TITLE
Files .ts don't appear

### ISSUE THREAD

**Issue by RafaelGodoyEbert** [elgatito/plugin.video.elementum#824]
Files .ts don't appear, only .mp4, how i to do for appear .ts on elementum?

On qbittorrent appear 35 folders and +100 files .mp4 and .ts 
![image](https://user-images.githubusercontent.com/78083427/133124666-f22dc8ab-dbcf-45fb-beb2-6ff841e98e7c.png)

On Elementum KODI appear only 27 itens
![image](https://user-images.githubusercontent.com/78083427/133124783-a79d794b-ebce-4df8-ae93-6f1965f08a2d.png)

**Comment by elgatito** [comment]
@RafaelGodoyEbert Elementum filters files, based on size.

**Comment by antonsoroko** [comment]
so you can try to adjust that size in settings.

**Comment by antonsoroko** [comment]
@RafaelGodoyEbert did it help?

**Comment by RafaelGodoyEbert** [comment]
I had found it, just didn't know how to delete my question. Thanks for commenting anyway!
