### ISSUE TITLE
Cashe still warming up notice, plus crashing 

### ISSUE THREAD

**Issue by codingnoob233** [elgatito/plugin.video.elementum#829]
elementum latest update running  on Android.Adding torrents possible but searching for shows or movies result in infinite loading/ search does it also.

Backing out of Kodi or trying to access elementum or burst settings result in crash.

Sorry even more issues appeared I'll follow the guide and try to do it right

**Comment by antonsoroko** [comment]
When you create an issue - there is a template. And it is there for a reason :-) It has a link to "how to create a debug log", for example, also info about versions, environment and etc.

**Comment by elgatito** [comment]
Closing due to no log provided.
