### ISSUE TITLE
[Bug] Library/Trakt synchronization causes intermittent crash in Kodi 19.1

### ISSUE THREAD

**Issue by dineshalphaque** [elgatito/plugin.video.elementum#838]
Hi folks,

Have been seeing intermittent crashes of Kodi (not just elementum) triggered by Elementum's Trakt synchronization (it's set to 30 minutes, in my config). Not sure if this is due to Elementum or if it's Kodi which needs a fix here. The relevant log lines when this happens are below. To note, it doesn't happen at every synchronization, but it does happen 4-5 times over any given 24 hour period.

Any ideass ?

I'm running Kodi and Elementum on:-
> Linux osmc 4.9.113-45-osmc #1 SMP PREEMPT Sun Aug 8 03:43:54 UTC 2021 aarch64 GNU/Linux

These are literally the last lines in the log, as Kodi restarted after the last line below. 
> 2021-10-18 18:58:44.907 T:9678     INFO <general>: JSONRPC Server: Disconnection detected
> 2021-10-18 18:58:44.911 T:9678     INFO <general>: JSONRPC Server: New connection added
> 2021-10-18 18:58:44.930 T:9678     INFO <general>: UpdateDetailsForMovie: Starting updates for movie 51
> 2021-10-18 18:58:44.954 T:9678     INFO <general>: UpdateDetailsForMovie: Finished updates for movie 51
> 2021-10-18 18:58:44.981 T:9692  WARNING <general>: [plugin.video.elementum] DEBU  main         ▶ Notification     Got notification from xbmc/VideoLibrary.OnUpdate: {"item":{"id":111,"type":"movie"},"playcount":399}
> 2021-10-18 18:58:44.982 T:9678     INFO <general>: JSONRPC Server: Disconnection detected
> 2021-10-18 18:58:44.984 T:9678     INFO <general>: JSONRPC Server: New connection added
> 2021-10-18 18:58:45.039 T:9678     INFO <general>: UpdateDetailsForMovie: Starting updates for movie 144
> 2021-10-18 18:58:45.062 T:9678     INFO <general>: UpdateDetailsForMovie: Finished updates for movie 144
> 2021-10-18 18:58:45.085 T:9692  WARNING <general>: [plugin.video.elementum] DEBU  main         ▶ Notification     Got notification from xbmc/VideoLibrary.OnUpdate: {"item":{"id":51,"type":"movie"},"playcount":399}
> 2021-10-18 18:58:45.091 T:9678     INFO <general>: JSONRPC Server: Disconnection detected
> 2021-10-18 18:58:45.091 T:9678     INFO <general>: JSONRPC Server: New connection added
> 2021-10-18 18:58:45.106 T:9692  WARNING <general>: [plugin.video.elementum] DEBU  main         ▶ Notification     Got notification from xbmc/VideoLibrary.OnUpdate: {"item":{"id":144,"type":"movie"},"playcount":399}
> 2021-10-18 18:58:45.127 T:9678     INFO <general>: UpdateDetailsForMovie: Starting updates for movie 99
> 2021-10-18 18:58:45.167 T:9678     INFO <general>: UpdateDetailsForMovie: Finished updates for movie 99
> 2021-10-18 18:58:45.199 T:9678     INFO <general>: JSONRPC Server: Disconnection detected
> 2021-10-18 18:58:45.199 T:9678     INFO <general>: JSONRPC Server: New connection added
> 2021-10-18 18:58:45.227 T:9678     INFO <general>: UpdateDetailsForMovie: Starting updates for movie 112
> 2021-10-18 18:58:45.227 T:9692  WARNING <general>: [plugin.video.elementum] DEBU  main         ▶ Notification     Got notification from xbmc/VideoLibrary.OnUpdate: {"item":{"id":99,"type":"movie"},"playcount":399}
> 2021-10-18 18:58:45.251 T:9678     INFO <general>: UpdateDetailsForMovie: Finished updates for movie 112
> 2021-10-18 18:58:45.284 T:9678     INFO <general>: JSONRPC Server: Disconnection detected

**Comment by dineshalphaque** [comment]
It literally happened again, 30 minutes after the last one described above as Elementum was synchronizing. The log lines are,

> 2021-10-18 19:10:06.706 T:13630    INFO <general>: UpdateDetailsForMovie: Starting updates for movie 83
> 2021-10-18 19:10:06.733 T:13630    INFO <general>: UpdateDetailsForMovie: Finished updates for movie 83
> 2021-10-18 19:10:06.760 T:13644 WARNING <general>: [plugin.video.elementum] DEBU  main         ▶ Notification     Got notification from xbmc/VideoLibrary.OnUpdate: {"item":{"id":63,"type":"movie"},"playcount":372}
> 2021-10-18 19:10:06.765 T:13630    INFO <general>: JSONRPC Server: Disconnection detected
> 2021-10-18 19:10:06.766 T:13630    INFO <general>: JSONRPC Server: New connection added
> 2021-10-18 19:10:06.771 T:13644 WARNING <general>: [plugin.video.elementum] DEBU  main         ▶ Notification     Got notification from xbmc/VideoLibrary.OnUpdate: {"item":{"id":83,"type":"movie"},"playcount":372}
> 2021-10-18 19:10:06.785 T:13630    INFO <general>: UpdateDetailsForMovie: Starting updates for movie 142
> 2021-10-18 19:10:06.807 T:13630    INFO <general>: UpdateDetailsForMovie: Finished updates for movie 142
> 2021-10-18 19:10:06.836 T:13630    INFO <general>: JSONRPC Server: Disconnection detected
> 2021-10-18 19:10:06.837 T:13630    INFO <general>: JSONRPC Server: New connection added

**Comment by antonsoroko** [comment]
try with enabled debug logging in elementum and upload full log file. link to the guide was in issue template (also template has fields for other useful info that should be provided).

**Comment by dineshalphaque** [comment]
Just thinking out aloud, but as a temporary mitigation for this issue, would it be possible to disable automated synchronization by setting the Trakt synchronization frequency to 0 minutes ? When 0, elementum never updates Trakt periodically.

Ad hoc Trakt updates can still be done by manually triggering it through Settings->Trakt->Update Trakt in Elementum.

Would this be possible, @elgatito ?

**Comment by elgatito** [comment]
@dineshalphaque It will not fix the issue, just make it happen more rare.
Even if Elementum would intentionally spam with Jsonrpc calls - it should not crash Kodi.

**Comment by dineshalphaque** [comment]
@elgatito 
An update.

The intermittent crashes do not happen on Windows 10 21H1 with Kodi 19.3 and Elementum 0.1.83. This installation has been running without a crash for 35 hours, with the same library movies/shows from the above referenced OSMC boxen. All Elementum settings are default with Trakt synchronization turned on. 

It's possible that these intermittent crashes on happen on Linux.

**Comment by dineshalphaque** [comment]
Update.

Since upgrading Elementum to 0.1.86, Kodi 19.3 has been running for over 96 hours without a crashed caused by JSONRPC calls. This is definitely a Good Thing !

Am wondering if this is just fortunate luck or has something changed in 0.1.86 which either intentionally or unintentionally fixed this issue.

@elgatito

**Comment by dineshalphaque** [comment]
It's been months, and i've not seen a crash caused by Elementum 0.1.86 and Kodi 19.4. Am closing this issue as solved.
