### ISSUE TITLE
Download continuous but stops buffering with large files. 

### ISSUE THREAD

**Issue by jaapie1989** [elgatito/plugin.video.elementum#84]
First of all I have installed elementum on a Nvidia Shield and use a external usb 3.0 as storage. When selecting a movie with a larger file size like 10GB. The download starts and continues but the buffering stops halfway, around 78%.  

Smaller movie files around 2GB works just fine. Could you help me with this?

**Comment by elgatito** [comment]
You should read welcome message and post your kodi.log.
