### ISSUE TITLE
Elementum doesn't open torrents or fetch them from the search, probably after Kodi update to Matrix

### ISSUE THREAD

**Issue by mirkorm** [elgatito/plugin.video.elementum#840]
Hello,
I'm not sure it's closely related to the kodi update but after the update to matrix it's behaving strangely, I opened kodi and performed some of those tasks with the debug logging activated:

-* I searched for a file and found little to no results (e.g. on the log i read it went for this page https://www.1337x.to/search/rocky+balboa/1/ and found no results, but if i open that page on a browser there are plenty of results, probably some kind of fetching issues?)

-* Tried to open a result but elementum didn't load it

-* I tried to open a torrent file that i had locally with elementum but an error appears saying "internal server error" and doesn't load it.

Log file: https://paste.kodi.tv/ihedosenax.kodi

elementum 0.1.83 on kodi 19.3 on wIndows 10

I'm available for any testing 
Thanks a lot

**Comment by dineshalphaque** [comment]
@elgatito 1337x also works for me, with or without a VPN. Am based in Malaysia, if that helps as it could be a geolocation block on IP addresses.

> 2021-11-01 02:07:44.887 T:12404 WARNING <general>: [script.elementum.burst] Burstin' with 1337x, ETTV, EZTV, KickAss, LimeTorrents, MagnetDL, RARBG, Sky torrents, The Pirate Bay, TorrentDownloads, YTS, Zooqle
> 2021-11-01 02:07:44.995 T:12407 WARNING <general>: [script.elementum.burst] [1337x] >                1337x search URL: https://www.1337x.to/search/reservation+dogs+s01e01/1/
> 2021-11-01 02:07:56.115 T:12407 WARNING <general>: [script.elementum.burst] [1337x] >>               1337x returned  4 results in 11.2 seconds
> 2021-11-01 16:16:03.525 T:29868 WARNING <general>: [script.elementum.burst] Burstin' with 1337x, ETTV, EZTV, KickAss, LimeTorrents, MagnetDL, RARBG, Sky torrents, The Pirate Bay, TorrentDownloads, YTS, Zooqle
> 2021-11-01 16:16:03.647 T:29871 WARNING <general>: [script.elementum.burst] [1337x] >                1337x search URL: https://www.1337x.to/search/reservation+dogs+s01e02/1/
> 2021-11-01 16:16:12.140 T:29871 WARNING <general>: [script.elementum.burst] [1337x] >>               1337x returned  3 results in 8.6 seconds
