### ISSUE TITLE
Not work on Xbox Series S.

### ISSUE THREAD

**Issue by v-hct** [elgatito/plugin.video.elementum#844]
Kodi is not working on xbox series s. Not run. Pls help. I installed Kodi on Xbox, Elementum does not start, before that, everything was fine to use on a PC.  I am an ordinary user who is glad that there is such an application, tell me how to solve the problem.  all I can send is a screenshot of the error (log not working) after installation and when trying to run it.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: 0.183

* Environment name and version: 19.3 Matrix

* Operating System and version:  Xbox Series S

* Link to Kodi debug log:

**Comment by v-hct** [comment]
![IMG_20211102_185730](https://user-images.githubusercontent.com/76693839/139875275-cce01630-f0ec-4ba0-a41d-f894b2e9e3c4.jpg)
![IMG_20211102_185733](https://user-images.githubusercontent.com/76693839/139875287-fa1f8f4f-77e8-47d7-90e8-3479ad0e54de.jpg)

**Comment by antonsoroko** [comment]
https://github.com/elgatito/plugin.video.elementum/search?q=Xbox

**Comment by elgatito** [comment]
@v-hct 
Xbox cannot run Elementum (that is not a limitation from Elementum). You can run only python based Kodi addons.

**Comment by elgatito** [comment]
@v-hct  Can you try this one - https://github.com/elgatito/plugin.video.elementum/issues/669#issuecomment-1369529351
