### ISSUE TITLE
Don't STOP torrent on Kodi seek timeout or other errors

### ISSUE THREAD

**Issue by notgood** [elgatito/plugin.video.elementum#845]
Running Elementum on Arch and latest Kodi, downloading to memory, large enough memory limit for every torrent.
Mobile internet connection with a very fluctuating speed, depending on weather, time of the day, phase of the moon... from zero to hero basically.

Elementum is set to continue downloading after play was stopped, keep files for videos, etc etc etc.

Yet given any Kodi seek error due to download timeout, Elementum simply stops and removes torrent, wasting all the downloaded in-memory content.

Any way to force Elementum to KEEP downloading and ignore Kodi playback errors? I mean I can restart Kodi playback of particular video manually, but don't want to waste time re-downloading it all again on every connection timeout.

Attaching the log of such dropout:
[kodi.log](https://github.com/elgatito/plugin.video.elementum/files/7473810/kodi.log)

**Comment by notgood** [comment]
Stopping playback manually also removes torrent.

But doing some futher testing, it seems to be a bug/feature of Elementum memory backend. Switching to file storage (while still downloading to memory using tmpfs filesystem) seems to solve this issue, torrent keeps running even after stopping playback.

**Comment by antonsoroko** [comment]
the thing is that memory storage is not a real "storage". it is not like file system where elementum puts whole file.
it is just big chunk of memory where elementum puts small chunks of torrent and then replace old chunks with new.
so basically memory storage is ephemeral and looks more like pile of chunks, as i can see it.

https://github.com/ElementumOrg/libtorrent-go/blob/master/memory_storage.hpp

**Comment by antonsoroko** [comment]
>Elementum is more tested and feature-full when downloading to files.

I would not say that. I think author did a lot to make memory storage the main feature of elementum.
And i guess majority of users use memory  storage unfortunately (hence no long-term seeding).

Although, file storage is more straightforward and simple thus it is more stable.

**Comment by notgood** [comment]
Now that I've played with it for a few hours, OS in-memory filesystem gives me the best of two worlds: flexibility of  a real FS, no extensive weardown of flash storage or HDD noise, no preallocation of RAM until actually required.

But its something Kodi or Elementum can't setup on its own, no plug-and-play here, requires some knowledge and manual labour to setup, at least on Linux. Perhaps similar on Windows, and probably next to impossible on Android without root.
