### ISSUE TITLE
Not able to run on Google TV (Android 10)

### ISSUE THREAD

**Issue by GHenry21** [elgatito/plugin.video.elementum#847]
I download the all in one pack and install it but when try to open an error shows up saying: 
Deamon error, permission error (13, permission denied)

**Comment by antonsoroko** [comment]
When you created this issue you probably saw that there are several "Pinned issues" - look at them again. Solution described there.

**Comment by StefanIlchev** [comment]
@GHenry21 I solved this issue by putting the daemon in a separate service app:
https://github.com/elgatito/plugin.video.elementum/issues/669#issuecomment-942653472

This is the behavioral change in Android 10 that is causing the problem:
https://developer.android.com/about/versions/10/behavior-changes-10#execute-permission
