### ISSUE TITLE
Elementum not working in Manjaro arm RPI4 [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by ra77767** [elgatito/plugin.video.elementum#849]
## Steps to Reproduce (for bugs)
1.Install manjaro for raspberry pi 4 8gb
2.install kodi
3.install elementum All-in-one

* Version used: 0.1.8.3  All-in-one
* Environment name and version:  KDE Plasma 5.23
* Operating System and version: Kodi 19.3 (matrix),Manjaro 21.10
* Link to Kodi debug log: [link](https://drive.google.com/file/d/1vCVYLabFL1Yjh-lgY71-OItT_uddg1fW/view?usp=sharingl)

**Comment by antonsoroko** [comment]
found same issue and some solution by searching in issues
see
https://github.com/elgatito/plugin.video.elementum/issues/821#issuecomment-976088790

you can try manually specify arch in setting (`linux_armv7` i guess) - more permanent solution. or manually copy binary for correct arch - temporary solution.

**Comment by ra77767** [comment]
Problem solved
