### ISSUE TITLE
[Bug] Playing watched items removes their 'watched' status

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#85]
## Current Behavior
When playing a watched item it removes the watched mark and doesn't keep their 'watched' status. Also it doesn't mark it again as watched according to Trakt after sync (Even when going in again, or trying to refresh it), while in Trakt site and in Kodi library and other addons it's still showing it as 'watched'.

## Expected Behavior
The 'watched' status should be kept even if replaying it.
(No matter how much percentage of the video was watched)
Because in Trakt it knows that you already played it in the past, and still considered it as watched.
So if the addon makes a sync with Trakt, even if the addon itself removed the 'watched' status, after the sync is should set it again as 'watched' according to Trakt.

## Steps to Reproduce (for bugs)
1. Go to your collection list for example (Movies -> Trakt -> Collection)
2. Choose a movie that already marked as watched (Synced by Trakt)
3. Stop it somewhere in the start.
4. The movie is now marked as unwatched, while it should be still marked as watched.
(In Trakt and Kodi library it's still marked as watched)
It seems that it doesn't resync the status after this case.

## Your Environment
* Version used: 0.0.39
* Environment name and version: Kodi 17.6
* Operating System and version: Win 10, 64 bit
* Link to Kodi debug log: https://paste.ubuntu.com/26497934/
-- I enabled the Debug mode right before I went into the "Trakt -> Collection" category
-- Focus on these movies: Inside Out (2015) and The Incredibles  (2004) -> They should be marked as watched, but in Elementum they shown as 'unwatched' according to my description above.

**Comment by burekas7** [comment]
Now it seems that the sync with Trakt doesn't work at all, I watched a movie last week and when I'm going into Trakt Collection, it is still shown as 'unwatched'.
(Version 0.0.41)

**Comment by elgatito** [comment]
In 0.0.53 playcount is not influenced by playback progress, so if you want to re-watch movie/episode - it will stay watched, but with a progress, being saved.
