### ISSUE TITLE
Xbox One, Kodi 19.3.0 - erro no serviço: b'attributeError("module\'_winapi\' has no attribute \'CreateProcess\'")'

### ISSUE THREAD

**Issue by jonathansf** [elgatito/plugin.video.elementum#852]
Xbox one
  Kodi 19.3.0
After doing the initial installation, when restarting kodi, the elementum performs the initialization process, but displays the message " service error: b'attributeError("module\'_winapi\' has no attribute \'CreateProcess\'") '" and does not start.

**Comment by antonsoroko** [comment]
@jonathansf 

search can be used to find the answer - https://github.com/elgatito/plugin.video.elementum/issues?q=is%3Aissue+Xbox

**Comment by jonathansf** [comment]
Thank

**Comment by jonathansf** [comment]
Thanks @antonsoroko, my scenario is the same as ticket #844  open for  @v-hct, but it's still unresolved.

**Comment by elgatito** [comment]
@jonathansf Xbox cannot run Elementum (that is not a limitation from Elementum). You can run only python based Kodi addons.
