### ISSUE TITLE
[Request] Separate menu view from movies/tv shows view 

### ISSUE THREAD

**Issue by matke-84** [elgatito/plugin.video.elementum#853]
As the title suggests, these two views need to be separated. If I change the movies view, the movie/tv show menu also changes and vice versa. Tried with multiple skins, same thing.
Main menu
![111](https://user-images.githubusercontent.com/74268331/148433792-f7d3dc95-1221-4fc8-b497-867f3a5071e2.png)
Movie menu (it should share view with the main menu not with movies view)
![222](https://user-images.githubusercontent.com/74268331/148433873-2a7eca67-e443-417b-8033-d0768515e552.png)
Movies view
![333](https://user-images.githubusercontent.com/74268331/148433929-6cfd2e73-d604-4614-8d31-4db7ebe05227.png)

**Comment by elgatito** [comment]
There is no bug.
There are separate settings for content view for menu and list of movies/shows/series/episodes.
Even if it is showing in the context menu that you save view for movies, it saves view for menu lists.

Go to the menu. Select view that you want. In context menu save this view.
Go to list of movies/shows. Select view that you want. In context menu save this view.

**Comment by matke-84** [comment]
@elgatito I know I have the ability to force a view for movies, tv shows, etc. Only this doesn't work very smoothly. Sometimes another view appears for a second and then the view I forced. Other addons, such as tmdb helper, have just been set up as I wrote. Isn't it logical that the main menu and submenus have the same view while the list of movies / tv shows is different? There is no logic if I set my movies list view to be a poster, to set my submenu in the poster. As you can see in the picture, it looks ugly.

**Comment by antonsoroko** [comment]
>Isn't it logical that the main menu and submenus have the same view while the list of movies / tv shows is different?

I think it makes sense.
I also would prefer navigation menus to be simple like small icons, but for movies/episodes something like banners.
In my skin i use "small icons" for everything and it looks fine, but i guess for more "rich" skins it might not be the case.

**Comment by elgatito** [comment]
I do not understand this issue.
By default Elementum is not setting any specific view, unless user sets something manually.
There is no way to predefine views, because each skin has own IDs for view modes.

**Comment by matke-84** [comment]
@elgatito You don't need to set a view. It just needs to be set that when I change the view in skin for the list of movies/tv shows, it doesn't change for the submenu. That needs to be separated. If you want, download for example tmdb helper and you will see that the main menu, submenus and movie lists are separated so that when I change for one view it does not change for the rest.

**Comment by elgatito** [comment]
@matke-84 Do you read what I write?

There are separate settings for content view for menu and list of movies/shows/series/episodes.

If you have any issues - do a PR and propose changes.

**Comment by matke-84** [comment]
@elgatito Yes I read it. But something is definitely wrong. If other similar addons do not have this problem, it means that something needs to be fixed in the elementum. Also @antonsoroko agreed with this. I would sort this out but unfortunately I am not an expert for go. No need to get angry and close the issue, I'm just trying to suggest some changes to make this addon as good as possible.

**Comment by antonsoroko** [comment]
@matke-84 
btw, have you tried to change these views directly in settings? (not via context menu)

there are 
https://github.com/elgatito/plugin.video.elementum/blob/2f7355ae0da5d183dd05c9d211ac3a1d5e413699/resources/settings.xml#L148-L155

in "Appearance" tab.
I can't test it now, but as i can see you set separate views for menus and videos.
(it uses view number iirc, but after you save some views via context menu - you will be able to map those numbers to particular views)

**Comment by matke-84** [comment]
@antonsoroko It's works. When I wrote that the view can be forced, I thought of that option. But I also wrote that this doesn’t work so smoothly. Very often the native view appears for a half second or second and then switches to the view I set in the elementum appearance option. It looks like a glitch. This is especially visible on android devices. I understand that Denis says that the settings are separate, but it simply doesn't happen in any other similar addon that if I change the view for movie/tv show lists in the skin, it changes menu as well. There is something that the skins recognize is the same in these settings and then change them at the same time. Here is an example how it looks like in tmdb helper.
Main menu
![1a](https://user-images.githubusercontent.com/74268331/148565112-109feada-59dc-479a-88af-b3dcddfb1dc9.png)
Movie submenu
![1b](https://user-images.githubusercontent.com/74268331/148565845-2f9978c3-ee56-44d4-a9d0-ed2bc886d199.png)
Movies list
![1c](https://user-images.githubusercontent.com/74268331/148565232-ccc9f20c-eecf-4f14-9d40-973b9f350ea0.png)

**Comment by antonsoroko** [comment]
@matke-84 
>Very often the native view appears for a half second or second and then switches to the view I set in the elementum appearance option

if i understood your correctly that was fixed by https://github.com/elgatito/plugin.video.elementum/pull/836

with new release - should be fixed.

if not - then i dunno.
