### ISSUE TITLE
[Features Request] Regarding the 'TV Shows -> Progress'

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#86]
I decided to make a new issue so it will be easier to follow.
Regarding 0.0.42

1. Add the aired date info also next to each episode name in the start of the line.
Because the air dates are one of the thing here, and some of the View Modes in the skin doesn't show it.
2. In addition to (1), add an option (In the Settings) for setting the date format, for example %d-%m-%y or %y-%m-%d etc. (Text input by user)

3. Add an options (In the Settings) for sorting this progress list:
• By Air Date / Previously aired
• By Title (Name)
• Recently collected
In SALTS it is done by the addon and selected in its Settings and not by kodi.
Kodi has only two option 'Date' and 'Genre' and this is no what I meant.
And by the way, kodi built-in sorting by 'Date' doesn't work or affect the list order.

Here are the Trakt sort filters, if you can implement those it will be nice: (Blue - Required. Green - Optional)
![progressfilters](https://user-images.githubusercontent.com/13424257/35870380-718c6a9e-0b59-11e8-83d0-667cab7382db.png)

4. Change the name. Instead of 'Progress' ,change it to "My Next Episodes" (Not critical)

5. I have already understood that you don't like it, but maybe one day in the future:
To colorize the air date and the aired/not aired episode title in different color for distinction and nice look (Like in the example below)
No one has ever complained about it or had a skin issues about it.

**Examples (According to SALTS addon):**
* Settings:
![salts](https://user-images.githubusercontent.com/13424257/35654686-fecaea84-06e5-11e8-96dc-7ccb29fa9b14.png)
![222](https://user-images.githubusercontent.com/13424257/35654826-d0aa3d5c-06e6-11e8-86e7-b73174220a38.png)

* 'Progress' list (My Next Episode)
![progresssalts](https://user-images.githubusercontent.com/13424257/35654708-21a2dba2-06e6-11e8-8a13-1334fc857123.png)

**Currently implementation in Elementum 0.0.39:**
![progresselementum](https://user-images.githubusercontent.com/13424257/35654724-34659fb8-06e6-11e8-8af1-3c0bc84f1a1c.png)

**Comment by burekas7** [comment]
6. Regarding the future episodes - Thumbnail image:
For regular exist episodes, the fanart that is shown is the episode image, and also the thumbnail (which  based on this episode's fanart image)
But, because you are using the TVDB, for future unaired episodes, these episodes doesn't have an episode image, so thumbnail is shown as blank, but the fanart image shows the TV Show fanart which is good. 
So my request here is to do a check, so if there is no episode/thumbnail image, use the TV Show fanart image as the thumbnail image instead of the episode image.

This is how it's look today:
https://s18.postimg.org/c0hpr8iax/screenshot015.png

**Comment by elgatito** [comment]
> This is how it's look today:
> https://s18.postimg.org/c0hpr8iax/screenshot015.png

That is only on progress page?

**Comment by burekas7** [comment]
From what I have checked so yes. As I said only in 'progress' you can see future episodes and future episodes still haven't image yet in TVDB. This is why you show it as blank. But they do have their TV-Show fanart instead so you can use it as thumbnail instead on this case.

**Comment by burekas7** [comment]
7. Please add these new options in the Settings for the 'Progress' section:
- Show unaired/future episodes in 'Progress' - Enable/Disable (Default=Enable/On)
- Exclude Completed/Ended shows from 'Progress' - Enable/Disable (Defualt=Disable/Off) 
(Similar to the SALTS settings example)

@hoshsadiq
According to this: https://github.com/elgatito/plugin.video.elementum/issues/46#issuecomment-363451251

**Comment by burekas7** [comment]
> > This is how it's look today:
> > https://s18.postimg.org/c0hpr8iax/screenshot015.png
> 
> That is only on progress page?

**Comment by burekas7** [comment]
@elgatito 

> > This is how it's look today:
> > https://s18.postimg.org/c0hpr8iax/screenshot015.png
> 
> That is only on progress page?

In addition to that I have now new episodes that don't get their thumbnail/fanart image.
I see why it happens, you are using TMDB for TV Shows and here for the 'Progress' section, instead of taking the images from TVDB or Trakt. TMDB is basically for Movies and not for TV Shows.

This is the reason why I still think it better to implement this request of selecting the main info source (Trakt/TVDB/TMDB)
https://github.com/elgatito/plugin.video.elementum/issues/87

**Comment by burekas7** [comment]
@elgatito 

Hi, This request is from old days, is there any chance that something would be done here according to all sections that mentioned?

**Comment by elgatito** [comment]
Changes in v0.0.54:
- Added settings for: colorize items, date format, sort of items in the list, allowing non-aired episodes.

Closing this issue. Future requests can be made in a separate issue.
