### ISSUE TITLE
Strange message on update 0.1.85

### ISSUE THREAD

**Issue by matke-84** [elgatito/plugin.video.elementum#861]
Someone mentioned that a strange message appears in the notification during the first installation 0.1.85. Here's what it looks like. I see that this message was inserted with a new update, but it is obviously not displayed properly.
![elementum](https://user-images.githubusercontent.com/74268331/149006281-0c6b92bc-752d-4099-bcc7-bd3de0972c20.png)

**Comment by antonsoroko** [comment]
looks like this is already fixed in 86 - https://github.com/elgatito/plugin.video.elementum/commits/master
https://github.com/elgatito/plugin.video.elementum/commit/d9261554a6f7d4bbdf3cacb304af221609c032ea

**Comment by dineshalphaque** [comment]
Wait, there's already an 0.1.86 ? Has this been pushed out?

I'm on 0.1.83 with auto updates turned on but haven't yet got it through auto update. Fyi, all other add ons seem to auto update correctly, including from non Kodi official repos.

Had to manually update to 0.1.86 just now. Any ideas what I'm doing wrong ?

**Comment by SubEdict** [comment]
> Had to manually update to 0.1.86 just now. Any ideas what I'm doing wrong ?
Yeah lol, this is the most confusing part because after Kodi 19 zip files won't update automatically. I found that even when Elementum is installed successfully from a zip you still need to look inside the repo - video and install (check version), only then the auto-update will work. 

No Idea why or even if it suppose to do that, but it works.

**Comment by dineshalphaque** [comment]
> even when Elementum is installed successfully from a zip you still need to look inside the repo - video and install (check version), only then the auto-update will work.

That's exactly what I did manually to upgrade to 0.1.86. let's see if it auto updates after this.

**Comment by matke-84** [comment]
It's fixed.
