### ISSUE TITLE
[Bug] Problem with resume playback with Kodi library

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#865]
Hi,

On Elementum it's ok:
1. Stop playback in some point
2. Play it again
3. You have an option to resume it from where it has been stopped.

But - when I'm doing the same when playing it from Kodi library (Which based on Elementum of course)
When playing it again, it starts from the beginning without and dialog or something to resume.

Kodi debug log:
For playing it from library, watched status is on 71% (Vikings S05E04)
https://paste.ubuntu.com/p/R3xRBYXYQH

![image](https://user-images.githubusercontent.com/13424257/151261769-ec480dd3-e6e2-45dc-8c9a-26f9536ae3c9.png)

---
Elementum 0.1.86
Kodi 19.3
Skin: Titan
Windows 10

**Comment by antonsoroko** [comment]
from log
>2022-01-27 01:01:01.743 T:5596  WARNING <general>: [plugin.video.elementum]   LibrarySyncEnabled: false,

if you enable it
https://github.com/elgatito/plugin.video.elementum/blob/a3e1bed8489344518de32421ba373c6956bfa8db/resources/language/messages.pot#L1841

does it work?

iirc it should be enabled in order to "resume from kodi" to work, but i might be mistaken.

**Comment by burekas7** [comment]
This is a little problematic since this unsolved issues that I opened:
https://github.com/elgatito/plugin.video.elementum/issues/823
https://github.com/elgatito/plugin.video.elementum/issues/825

If I will change one of the condition it would make sync issues again.
But I will test in order to verify this.
I thought at first that it maybe kind of a Kodi issue, but I don't know actually, so I start thinking maybe it something with Elementum (In my case it remember the season torrent, so it pops up a dialog to use this torrent, so I was thinking maybe it has an impact maybe)
