### ISSUE TITLE
[Feature Request] Selecting the default information source

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#87]
Add an option for selecting the default information source scrapper.
(For titles, names, descriptions, episodes, airdates, images etc...)

**For TV Shows**
* TVDB
* Trakt

**For Movies**
* TMDB
* Trakt

**Comment by elgatito** [comment]
To be able to do this - all items in TMDB, TVDB, Trakt need to be linked, and they are not. 
And even if there was all the information - this is a huge piece of work, which I don't want to make.

Elementum is using TMDB as base database and there is not other option.

**Comment by burekas7** [comment]
Can you at least for now force TV Shows to use TVDB?
Because in 'Trakt -> Progress' for example it using TMDB.

So I got for example this corrupt image:
http://image.tmdb.org/t/p/w1280/rDrgPUcPGJX2Wr515GzTU6NJGcP.jpg
Or new episodes don't get their thumbnail/image because it still not updated in tmdb.

TMDB is for movies and not for TV Shows.

By the way I still think Trakt is better for both Movies and TV Shows.
But if you can add an option for selecting is the best.

**Comment by elgatito** [comment]
Finally. 
We use TMDB for listing items and can use Trakt when listing comes from Trakt. 
Images come from TMDB only, because Trakt is not giving them now (disable in the API). 

I would not add TVDB at this point, to avoid more mess.
