### ISSUE TITLE
Library on net share

### ISSUE THREAD

**Issue by megavenik** [elgatito/plugin.video.elementum#878]
Hi! Today I've tryed to configure a network-shared library for Elementum, but faced an issue:

![image](https://user-images.githubusercontent.com/815281/164052694-a9bc259e-560b-44a7-b10d-be943b2ed470.png)

I'm getting this error on Win 10, Kodi 19.4, Elementum 0.1.86

As I can see from the [code](https://github.com/elgatito/elementum/blob/b7fdd9fcd18b6b097d61b7489385b7032a072211/config/config.go#L877), it is the dedfault behavior, plugin doesn't even try to check whether path is really writable or not. But I'm not very good in Golang and don't know plugin's codebase, maybe I'm mistaken here.

On the other hand, I've seen people on the internet showing screens with smb:/ paths and saying that everything works for them.

Can you please help understand, how the make Elementum library shareable between different machines over local network?

Thanks!

**Comment by elgatito** [comment]
Elementum is supporting only local paths. To support network based paths it needs to be supported by Golang. 
You can make a system mount and then use it is Elementum as a local folder.
