### ISSUE TITLE
Elementum fails to start on kodi 20 (20 alpha1 as of today)

### ISSUE THREAD

**Issue by pitsi** [elgatito/plugin.video.elementum#883]
## Expected Behavior
Elementum should start and all its "parts" (= the repo and burst) should be available.

## Current Behavior
Elementum does not start, so its repo is not available and burst can not be installed as well. The relevant part in the log file is
```
2022-05-28 07:19:51.441 T:787     ERROR <general>: Repository add-on repository.elementum uses old schema definition for the repository extension point! This is no longer supported, please update your addon to use <dir> definitions.
2022-05-28 07:19:51.441 T:787     ERROR <general>: Repository add-on repository.elementum does not have any directory and won't be able to update/serve addons! Please fix the addon.xml definition
2022-05-28 07:20:00.205 T:793     ERROR <general>: GetDirectory - Error getting plugin://plugin.video.elementum/
```

## Possible Solution
No idea, but I am willing to try anything on its addon.xml if someone shows me how the new "addon.xml definition".

## Steps to Reproduce (for bugs)
1. Install kodi 20. Right now, it is available on debian's experimental repo (alpha1), on teamxbmc's nigtly builds ppa for ubuntu and on libreelec 11 nightly.
2. Download elementum for the the applicable architecture and install it from zip.
3. Restart kodi.
4. Launch elementum and notice the above in the log.

## Context
I have been using elementum since its very first days, so now that an alpha version of kodi 20 is released, I want to check which addons still work on it. And because I am not willing to sacrifice the kodi installation on my main pc, I installed it via libreelec 11 nightly on my rpi3b+. 
It was on libreelec 9.2.8, but because libreelec 10 for the rpi3 was delayed until 10.0.2, I rarely used it for 6+ months now. I would install libreelec 10 from scratch anyway one day, so I thought why not try the nightly to check on kodi 20? 
Sadly, I get filesystem corruption notifications a lot, although the card and the rpi3b+ are not "worn out" at all, so I do not know for how much longer I will use it. They (= the rpi3b+ and the sd card) must have like 1-1.5 months of total usage time since April 2019 that I got them.

## Your Environment
* Version used: 0.1.86
* Environment name and version: Kodi 20 alpha 1
* Operating System and version: Libreelec nightly for rpi2 (armv7l)
* Link to Kodi debug log: (see above)

**Comment by pitsi** [comment]
I made a bit of progress. I added the `<dir>` part on repository.elementum/addon.xml so it now looks like so
```
<addon id="repository.elementum" name="Elementum Repository" version="0.1.86" provider-name="elgatito">
	<requires></requires>
	<extension point="xbmc.addon.repository" name="Elementum Repository">
		<dir>
		<info compressed="false">http://127.0.0.1:65220/repository/elgatito/plugin.video.elementum/addons.xml</info>
		<checksum>http://127.0.0.1:65220/repository/elgatito/plugin.video.elementum/addons.xml.md5</checksum>
		<datadir zip="true">http://127.0.0.1:65220/repository/elgatito/</datadir>
		</dir>
	</extension>
	<extension point="xbmc.addon.metadata">
		<platform>all</platform>
		<summary lang="en">GitHub repository for Elementum updates</summary>
	</extension>
</addon>
```
and now elementum can launch as usual, works as usual and burst can be installed too.

p.s. Don't be mad at me for splitting the one-line text of addon.xml into multiple lines. It was the only way I had to make it human-readable.

**Comment by burekas7** [comment]
Yes, they updated the repo structure, so any repo that wouldn't update it their repo won't work:
https://kodi.wiki/view/Add-on_repositories#Repository_Add-on

**Comment by elgatito** [comment]
@pitsi Please, try v0.1.87.

**Comment by pitsi** [comment]
I stoppped using kodi 20 alpha/beta (I can't recall what version was it) in early September because the nightlies of libreelec 11 had serious connectivity issues on my devices and I was fed up troubleshooting them.

On my system though, which runs kodi 19.5, the file `~/.kodi/addons/repository.elementum/addon.xml` seems unchanged and still on v0.1.86
```
$ cat .kodi/addons/repository.elementum/addon.xml 
<addon id="repository.elementum" name="Elementum Repository" version="0.1.86" provider-name="elgatito">
	<requires></requires>
	<extension point="xbmc.addon.repository" name="Elementum Repository">
		<info compressed="false">http://127.0.0.1:65220/repository/elgatito/plugin.video.elementum/addons.xml</info>
		<checksum>http://127.0.0.1:65220/repository/elgatito/plugin.video.elementum/addons.xml.md5</checksum>
		<datadir zip="true">http://127.0.0.1:65220/repository/elgatito/</datadir>
	</extension>
	<extension point="xbmc.addon.metadata">
		<platform>all</platform>
		<summary lang="en">GitHub repository for Elementum updates</summary>
	</extension>
</addon>
```
Spaces and indentation was added to make it human readable. Elementum was updated a few minutes ago to 0.1.87 and kodi was restarted as well.

**Comment by pitsi** [comment]
Now that kodi 20 was released as stable, I am waiting for to reach my distro's repo and apt to "force-update" it to the new version, so I will definitely report back for its behavior.
Tbh, I would grab it from the unstable part of the repo since it has been there since yesterday, but I have one binary addon (inputstream adaptive) that is not packaged for the new version yet and I do not want apt to remove it.

**Comment by pitsi** [comment]
Sadly, you will wait a lot more for me to check if the repo is compatible.
I got the update to kodi 20 yesterday afternoon and kodi no longer starts on my system. In fact, it segfaults at launch and exits.
I am troubleshooting it and I hope it will finally work, because there are other repos I have to check as well.

**Comment by elgatito** [comment]
@pitsi Almost sure it is related to Elementum :) 

@StefanIlchev What is the correct way of getting a log from a remote device, like  I did with `logcat` on emulator, that was showing segfault description as well?

**Comment by pitsi** [comment]
It is definitely NOT related to elementum or any other addon. I completely deleted ~./kodi and it still fails to launch.
It is probably some opengl library that is not loaded from my gpu's driver. The problem is which one and why.

**Comment by StefanIlchev** [comment]
@elgatito it should work the same way with a device, assuming you've enabled debugging on the device and authorized the ADB connection. The second column of the output of `adb devices` should be `device`.

If you're using the logcat window in the IDE make sure you're not looking at an old `DEAD` connection as it doesn't always switch to a new one automatically.

**Comment by pitsi** [comment]
Fresh and temporary installation of le 11 beta1 on rpi3b+ (armv7 architecture), because I REALLY had to check it!
```
# cat .kodi/addons/repository.elementum/addon.xml
<addon id="repository.elementum" name="Elementum Repository" version="0.1.87" provider-name="elgatito">
	<requires></requires>
	<extension point="xbmc.addon.repository" name="Elementum Repository">
	<dir>
		<info compressed="false">http://127.0.0.1:65220/repository/elgatito/plugin.video.elementum/addons.xml</info>
		<checksum>http://127.0.0.1:65220/repository/elgatito/plugin.video.elementum/addons.xml.md5</checksum>
		<datadir zip="true">http://127.0.0.1:65220/repository/elgatito/</datadir>
	</dir>
	</extension>
	<extension point="xbmc.addon.metadata">
		<platform>all</platform>
		<summary lang="en">GitHub repository for Elementum updates</summary>
	</extension>
</addon>
```
The repo's structure is compatible with kodi 20 and there is no error in kodi's log. But why is my other system (le 9.2.6 x64, kodi 18.9) still on 0.1.86? Any ideas are welcome, excluding the one to reinstall elementum.
I gave up troubleshooting kodi 20 on my main system and sadly I removed it after like 10 years of... devotion to it :p 
I even deleted my ~/.kodi folder so as to start fresh once my issue is fixed.

If there is nothing else to add, feel free to close the issue.

**Comment by elgatito** [comment]
@pitsi `repository.elementum` is a separate addon, and it is installed when you run `plugin.video.elementum` for the first time. 
Even if you update `plugin.video.elementum` - repository addon will stay the same. So you can uninstall `repository.elementum` and restart Elementum - it will install `repository.elementum` again.

I wanted to review that process and let repository update itself.

**Comment by pitsi** [comment]
I did what you suggested and elementum did reinstall repository.elementum and it works now.
But what about the update process? A friend who was on kodi 19, got the upgrade of the repo to 0.1.87 and when he got the kodi's upgrade to 20, he said it just kept working.

**Comment by pitsi** [comment]
Due to an issue with kodi 20 on nvidia 340, I have decided to stop using it (or maybe use it rarely) on my pc.
However, I did test elementum and I can say its repo works as it should with kodi 20, so I am closing the issue.
