### ISSUE TITLE
[ Question ] Only download torrents for play later

### ISSUE THREAD

**Issue by serhumanos** [elgatito/plugin.video.elementum#887]
Hi, I like to know if is there any option to set in Elementum that alow to download selected torrent instead playing/streaming it.
I will like to select it to watch it later, but keep downloading (there are many torrents with small amount of peers/seeds that can not be played in real time)
thank you very much!

**Comment by antonsoroko** [comment]
@serhumanos 2 way to do this:
prerequisites:
1. set storage to files (memory will not work obviously, it is temporary storage).
2. set "keep files" option
3. optionally, set in settings to download all files of torrent, if you want to download whole seasons

ways:
1. start torrent, then cancel.
2. use http://elementum.surge.sh/context/

**Comment by serhumanos** [comment]
> @serhumanos 2 way to do this: prerequisites:
> 
>     1. set storage to files (memory will not work obviously, it is temporary storage).
> 
>     2. set "keep files" option
> 
>     3. optionally, set in settings to download all files of torrent, if you want to download whole seasons
> 
> 
> ways:
> 
>     1. start torrent, then cancel.
> 
>     2. use http://elementum.surge.sh/context/

Thank you very much! I was doing the first option, but the context plugin is very cool!
