### ISSUE TITLE
Anime Category alongside Movies and TV shows 

### ISSUE THREAD

**Issue by iMithrellas** [elgatito/plugin.video.elementum#890]
Is there a way to create a category that would work the same way as TV shows but would only include Anime? 

If so can anyone guide how I would achieve such a result?

Thanks in Advance, 
Mithrellas. 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

**Comment by elgatito** [comment]
Elementum is using TMDB as a catalog base. And anime is part of TV Shows  there, I guess. 
Adding another service is possible, but only as a contribution from anyone else.
