### ISSUE TITLE
Can't install it on Android Kodi 19.4

### ISSUE THREAD

**Issue by Barabba11** [elgatito/plugin.video.elementum#892]
Hi, Elementum 0.1.86 in past was installed, I don't remember when, and it was working, then I start to receive an error at kodi startup, as elementum doesn't have permissions and so on, starting it manually didn't help, so I decidet to uninstall it and reinsall it from zero. 
I've tries all sigle packages fgor android with all versions, i'm getting installation error, why?
May someone please help me? Thank you a lot

**Comment by Barabba11** [comment]
I was able to install it by Kodi on Demand, but I have error 13, probably because of Android 10>?

**Comment by antonsoroko** [comment]
If you have android 10+ - then see #669
This issue is also pinned to "main page" of issues.
