### ISSUE TITLE
Can I automatically add movies and shows that I have watched to the library? And if so , how?

### ISSUE THREAD

**Issue by dhr-uvin** [elgatito/plugin.video.elementum#893]
Whenever I watch a movie or show and i want to add it to library , I always have to manual open context menu and add it. This is a little bit annoying as I have to do it every single time. Is there a way for it to automatically be added after I watch even a bit of the episode / movie?

**Comment by antonsoroko** [comment]
I guess - no, see https://github.com/elgatito/plugin.video.elementum/blob/a3e1bed8489344518de32421ba373c6956bfa8db/resources/language/messages.pot#L981-L997
for currently available syncs.

**Comment by dhr-uvin** [comment]
Ah , how unfortunate.

**Comment by elgatito** [comment]
You can add manually something, but we don't have automatic addition.
