### ISSUE TITLE
Trackt issues again

### ISSUE THREAD

**Issue by Crsarmv7l** [elgatito/plugin.video.elementum#895]
Looks like trackt is not working again. Did they change the api key?

**Comment by elgatito** [comment]
@Crsarmv7l  they have mesages saying there are problems with the database: https://twitter.com/trakt , so I can't login to check the API status.

**Comment by matke-84** [comment]
@elgatito
OMG. I am so glad to see that you have replied to any message which means you are ok. I hope we will see sometime another update of the best kodi addon ever. Greetings.

**Comment by Crsarmv7l** [comment]
Closing. Looks like it was just due to trakt crapping the bed
