### ISSUE TITLE
[Compatibility?] Kodi v20 Repo blocked. Could not connect.

### ISSUE THREAD

**Issue by SubEdict** [elgatito/plugin.video.elementum#897]
## Issue briefly:
Just FYI. Tested Kodi v20 + latest Elementum zip (All-in-one).
Elementum updated successfully but **without the repo** so..  No updates and no Burst (Needed to downloaded manually from git).
Tried to click on the old repo and got a "Could not connect to repository" message.

** Other PCs with Kodi 19.5 works fine (Auto-update and all).

## Your Environment
Elementum 0.1.87. Kodi version 20 (Nexus official release).
Windows 7/8/10

**Comment by elgatito** [comment]
@SubEdict Version 0.1.87 is compatible with Kodi20, but repository is not re-installed with Elementum updates, so you need to uninstall `repository.elementum` addon and then restart Elementum, it will reinstall repository with the latest version.

**Comment by SubEdict** [comment]
Thanks @elgatito, that did the trick. 
Good to see you live & kick'n. :)
