### ISSUE TITLE
Is the elementum binary installed twice?

### ISSUE THREAD

**Issue by pitsi** [elgatito/plugin.video.elementum#9]
This is a duplicate of an issue I opened under quasar's github repo a few days ago, here
https://github.com/scakemyer/plugin.video.quasar/issues/909

I noticed that the exact same thing happens in elementum too, so the questions remain, since elementum is a fork of quasar. The system configuration is also the same as in the other issue, but quasar was removed completely in order to test elementum's capabilities.

Here are the sums for elementum proving that the binary file is indeed the same.
```
$ md5sum .kodi/userdata/addon_data/plugin.video.elementum/bin/linux_x64/elementum 
25537b623ed28cc882d08832dbebd2b8  .kodi/userdata/addon_data/plugin.video.elementum/bin/linux_x64/elementum
$ md5sum .kodi/addons/plugin.video.elementum/resources/bin/linux_x64/elementum 
25537b623ed28cc882d08832dbebd2b8  .kodi/addons/plugin.video.elementum/resources/bin/linux_x64/elementum
```

Thank you in advance

**Comment by elgatito** [comment]
Quasar/Elementum copy binary to allow self-update, it's normal behavior.

**Comment by pitsi** [comment]
Sorry for bringing this back to the surface ~5 years later, but I am having an argument with a so called "kodi expert" and the lack of platforms for testing the following claim, forces me to ask as the dev.

Assuming there are 2 versions of the addon under `/addons/plugin.video.elementum/resources/bin/`, the one for android arm64 and the one for windows x64, and but of them under `/userdata/addon_data/plugin.video.elementum/bin/`, the one for windows x64. 

On a system that is not on any of the 2 forementioned architectures, e.g. on linux x64, elementum won't even launch, let alone install the correct version by itself from its repo, as he claims.
What will happen a system that is either android arm or windows x64? I assume that in this case, the addon will work as it should only on windows x64 and fail on android arm64. Am i right?
