### ISSUE TITLE
Choose stream automatically and "Resume from" 

### ISSUE THREAD

**Issue by denisNic** [elgatito/plugin.video.elementum#90]
## Current Behavior
1. <s>[Library] The TV shows library is not loaded the thumbnails in the player</s>
2. <s>[Library] In log - errors on request "uniqueid"</s>
3. [Choose stream auto]If you select "choose stream automatically" in the settings, this only works after restarting kodi.
4. [Choose stream auto] If you select from the context menu, a list of links appears.
5. [Library] "resume from" not working

## Possible Solution
1. <s>[Library] Do a check on the version of Kodi and call the corresponding requests</s>
2. [Choose stream auto] A separate link by analogy "/play", "/search", "/links"
## Steps to Reproduce (for bugs)
1. [Library] Resume tv show/movie from the library
2. [Choose stream auto] Disable "choose stream automatically", restart Kodi, Enable "choose stream automatically" and run a movie or TV series in library
3. [Choose stream auto] Disable "choose stream automatically", restart Kodi, click "choose stream automatically" in context menu

## Context
1.<s> [Library] Thumbnails in the player when playing from the library TV Shows</s>
2. <s>[Library] Lack of query errors in the logs</s>
3. [Choose stream auto]Automatic selection without restarting
## Your Environment
* Version used: Elementum 0.0.41, Burst 0.0.14
* Environment name and version: Kodi 16.1 [Jarvis]
* Operating System and version: Windows 8.1 x86
* Link to Kodi debug log:
[Library](https://paste.ubuntu.com/26509186/)
[Choose stream auto]
[Before restart Kodi](https://paste.ubuntu.com/26509227/)
[After restart Kodi](https://paste.ubuntu.com/26509229/)

**Comment by elgatito** [comment]
There is no way to check if Kodi supports `uniqueid` and `year`, and no other way to get it. 
That error does not influence much on identifying movie/episode.

```
00:15:23 T:3244  NOTICE: [plugin.video.elementum] INFO  btplayer     ▶ playerLoop       Stopped playback
00:15:23 T:3244  NOTICE: [plugin.video.elementum] DEBU  btplayer     ▶ UpdateWatched    Updating Watched state: &bittorrent.PlayerParams{Playing:true, Paused:false, Seeked:false, WasPlaying:false, FromLibrary:true, WatchedTime:27.1700019836, VideoDuration:1325.65905762, URI:"C:\\Users\\nic\\AppData\\Roaming\\Kodi\\cache\\elementum\\696548c7eacf140aee15481a8b5d5745c6690875.torrent", FileIndex:-1, ResumeIndex:-1, ContentType:"episode", KodiID:29, TMDBId:1345591, ShowID:60625, Season:3, Episode:8}
00:15:23 T:3244  NOTICE: [plugin.video.elementum] INFO  bittorrent   ▶ UpdateWatched    Currently at 2.049547%, KodiID: 29
```

If playback is less than 180 seconds - watched status is not saved. `KodiID: 29` says item is resolved.

**Comment by denisNic** [comment]
The progress of the browsing works very well in 0.0.41 !!! Thank you! I'm more interested in the thumbnail in the player when playing a series from the library

**Comment by elgatito** [comment]
Can you show screenshot when thumbnail is good and when not? To see what you mean.

**Comment by denisNic** [comment]
[In library](http://dropmefiles.com/OL4By) - Bad
[In elementum](http://dropmefiles.com/a1gZT) - Good

**Comment by denisNic** [comment]
"Resume from" does not work from the library. Playback starts from the beginning
[LOG "Resume from"](https://paste.ubuntu.com/26514798/)

**Comment by elgatito** [comment]
> [Choose stream auto]

Can be tested with 0.0.42.

> [Thumbnail] 

Can be tested too.

**Comment by denisNic** [comment]
Elementum 0.0.42 
1. [thumbnail] working! Thank you!
2. [choose stream auto] Everything is still, without restarting it does not work. [Log](https://paste.ubuntu.com/26524946/)
3. [resume from] not working - [New log](https://paste.ubuntu.com/26524965/)

**Comment by elgatito** [comment]
> [resume from] not working 

Can you do the following (and post the log):
- Open movie/episode from Kodi library
- Wait at least 200 seconds or seek somewhere more than 3 minutes.
- Close, wait about 10 seconds.
- Open same item.

**Comment by elgatito** [comment]
> [choose stream auto] 

I don't understand this. 
There are two modes how to play video: 
1) do search and select the first item automatically - this is when you select "choose stream automatically"
2) do search and display links so user will choose the stream.

When you add something to Kodi library - it writes .strm files with "play/links" mode, that is selected at the moment of strm creation. So if you change the mode - it will use the one that is in strm file.
There is an option "Force stream ..." which makes sure that plugin reads mode from settings and not from strm file (so you don't care what is in the file).

When you browse plugin directories (like search/in trend/most popular and so on) your default action (when you click enter/OK) is the one you have selected in the settings and in context menu you will always have an opposite action. That is done to be able to use another option.

Context plugin "Elementum Play" action is always looking for your active mode and starts it. It does not mean "Play" as a play mode, it can be play or links.

When you change settings in Kodi and press "OK" (saving settings) - plugin reads it and uses later this changed setting.

But there is a caching system for every directory page, so it's cached for some minutes and your changed settings will not become active until that time.

**Comment by denisNic** [comment]
> Can you do the following (and post the log): 
Open movie/episode from Kodi library
Wait at least 200 seconds or seek somewhere more than 3 minutes.
Close, wait about 10 seconds.
Open same item.

I already did it, when I press "resume from", playback starts from the very beginning(0.00). This problem is only in the library
[Log](https://paste.ubuntu.com/26528905/)

> I don't understand this.
When I enable or disable it in the settings, it only works after restarting Kodi

**Comment by denisNic** [comment]
BUMP

**Comment by elgatito** [comment]
Can be tested with 0.0.43 to check if there is a progress.

**Comment by denisNic** [comment]
Not working...[Log](https://paste.ubuntu.com/p/JCF9yYDFvM/)

> 19:38:35 T:2400   DEBUG: [plugin.video.elementum] Watched: 612.478027344, duration: 1357.39807129
19:38:35 T:3360  NOTICE: [plugin.video.elementum] DEBU  main         ▶ Notification     Got notification from xbmc/Player.OnPlay: {"item":{"episode":2,"season":3,"showtitle":"Рик и Морти","title":"3x02 Эпизод #2","type":"episode"},"player":{"playerid":1,"speed":1}}
19:38:35 T:3360  NOTICE: [plugin.video.elementum] INFO  btplayer     ▶ playerLoop       Got playback: 612.478027s / 1357.398071s
19:38:36 T:3360  NOTICE: [plugin.video.elementum] DEBU  memory       ▶ Start            Cap: 104857600 | Size: 83886080 | Items: 5 | Capacity: 9
19:38:36 T:3360  NOTICE: [plugin.video.elementum] DEBU  bittorrent   ▶ progressEvent    d58c2e: 7.8 MB/38 kB | Queued (16.35%)
19:38:36 T:2400   DEBUG: [plugin.video.elementum] Watched: 1.0, duration: 1357.39807129

**Comment by Rick987** [comment]
It happens to me too, when you stop and try to resume it starts from beginning

**Comment by elgatito** [comment]
"Resume from" was rearranged in latest versions. Should be fixed.
