### ISSUE TITLE
[Question] Why does the assets files are larger in 0.1.87?

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#902]
Hi, @elgatito 

Just a general question:
Why does the assets files are larger in 0.1.87 than previous versions? (~10M)

**Comment by elgatito** [comment]
@burekas7 https://github.com/elgatito/elementum-binaries/tree/master/linux_arm64
Each platform has additional shared library to allow running when system does not allow running something in the background.
