### ISSUE TITLE
Проблема на версиях от 38 до 41

### ISSUE THREAD

**Issue by yatsek20** [elgatito/plugin.video.elementum#91]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

**Comment by yatsek20** [comment]
2часа мучался с Елементум. 41 версия глючит страшно. Долгий вход в разделы, нажав на несколько фильмов стримов нет, причём ранее их в данном плагине смотрел на старой версии. В настройках Бустера оставляю один рутор фильм что не было стримов уже есть. Всё показывает. Выбираю др фильм всё уходить плагин в задумчивость. И помогает только перезагрузка коди. Ставил версии елементума 38,39 и к ним бустер 13 версию, с одним трекером работает нормально, но выбор др фильма обратно задумчивость. На старых версиях вообще такого не было до 38. Всё летало на ура. После выхода из Елементум др плагины типо резки, фильммикс очень долгий вход в них. Уже не знаю куда копать. Чтобы пользоваться другими плагинами надо перегружать приставку и тогда др плагины работают нормально.

**Comment by elgatito** [comment]
Без лога в режиме отладки никто помочь не сможет.

**Comment by yatsek20** [comment]
просто кинуть весь файл лога это не проблема,но как в режиме отладки я лично не знаю

**Comment by elgatito** [comment]
https://kodi.wiki/view/Log_file/Easy
Можно весь, я разберусь в нём.

**Comment by yatsek20** [comment]
вот лог https://yadi.sk/i/TjbzjhjH3S44B9

**Comment by elgatito** [comment]
Яндекс диск заблокирован, можно на любой другой. Сюда можно http://dropmefiles.com

**Comment by yatsek20** [comment]
https://paste.ubuntu.com/26511445/ вот в режиме отладки но насколько правильно сделал не знаю и вот что кидал ранее на яндекс http://dropmefiles.com/t0MBz

**Comment by yatsek20** [comment]
не разбирались в чем причина?

**Comment by elgatito** [comment]
Проблемы в том логе не видно, загрузилось и работает. Можете прислать лог ситуации когда глючит? И версию ставьте последние elementum/burst.

**Comment by yatsek20** [comment]
стоит последняя версия 41 . вкл раздел фильмы-в тренде(долгая загрузка)-выбираю ТорРагнарек- идет долгий поиск торрентов (если один торрент типо руторга) то находит раздачу если более 2-х то не находит и пишите что ни чего нет. После этого в обеих случаях след фильм идет вечный поиск раздач. И после не нахождения а это 100% вариант что не находит. то др плагины вкл очень долго или вообще коди виснет и помогает перезагрузка. На старых версиях до 38 такого не было вообще все четко работало.

**Comment by yatsek20** [comment]
лог кину чуть позже когда вкл более 2-х трекеров,но 2-й лог что я кидал как раз более 2-х торрентов и ни чего не нашло и не показывало.

**Comment by yatsek20** [comment]
сейчас все окей и ни чего не делал, плагин работает идеально , более 3-х провайдеров в настройках .Спасибо за плагин. Я так же с Украины как и вы исходя из вашего профиля.

**Comment by yatsek20** [comment]
и снова на 41 и 42 версии старая проблема появилась - долгий поиск фильмов раздач и в итоге ни чего не найдено,хотя начинал смотреть уже

**Comment by yatsek20** [comment]
ошибок нет, стрим не найден фильм лига справедливости

**Comment by elgatito** [comment]
> ошибок нет, стрим не найден фильм лига справедливости
Без лога никто не поможет. У меня всё работает.

**Comment by yatsek20** [comment]
в прошлый раз логи высылал, но это не помогло именно логи ,само все заработало каким то образом

**Comment by yatsek20** [comment]
вот лог http://dropmefiles.com/1koAs

**Comment by yatsek20** [comment]
вот еще лог , но выбрал запустил но запустил не тот стрим , повторный запуск Стримы не найдены. Ток были и уже нет http://dropmefiles.com/ULvnQ

**Comment by elgatito** [comment]
```
16:32:01.942 T:3420447584   ERROR: [script.elementum.burst] [rutracker] Login failed: Wrong username or password
16:32:01.944 T:3420447584  NOTICE: [script.elementum.burst] >>        RuTracker returned  0 results in 31.7 seconds
```

Логин и пароль от рутрекера не принимает.

Похоже на то что система убивает плагин. Возможно из-за нехватки памяти. Пробуйте 100мб, а не 200мб.

**Comment by yatsek20** [comment]
при этих же параметрах все раньше показывало и логин с паролем не менял.попробую поменять размер памяти, но памяти у меня на приставке свободных 60% хоть и стоит кои в либер на сд карте размером 32 гига

**Comment by yatsek20** [comment]
поставил 100мб, исправил пароль, проблема осталось и еще тайм-аут елементум. http://dropmefiles.com/7xsaJ

**Comment by yatsek20** [comment]
добавил публич днс везде ,без изменений http://dropmefiles.com/wXy6w

**Comment by elgatito** [comment]
Последний лог:
```
23:04:59.964 T:2933773152 WARNING: [script.elementum.burst] Status for 'https://rutracker.lib/forum/login.php' : gaierror(-2, 'Name or service not known')
```
```
23:04:59.953 T:2986341216 WARNING: [script.elementum.burst] Status for 'https://nnm-club.lib/forum/login.php' : gaierror(-2, 'Name or service not known')
```

```
23:05:07.055 T:2942161760   ERROR: [script.elementum.burst] [bluebird] Login failed: Wrong username or password
```

Если включаете публичные ДНС в Burst - нужно их включать и в самом Elementum. Если нету блокировок от провайдера, то лучше не включать публичные ДНС.
Для bluebird или прописать логин/пароль или выключить. 

По опыту, если нету блокировки то для Украины регистрируйтесь на rutracker, nnm-club, toloka, + rutor (там не нужно региться) и этого с головой будет.

**Comment by elgatito** [comment]
Один отваливающийся провайдер тянет за собой остальные. Отключайте bluebird, перезагружайтесь и пробуйте.

**Comment by yatsek20** [comment]
Спасибо, понял

12 февр. 2018 г. 3:39 ПП пользователь "Denis" <notifications@github.com>
написал:

**Comment by elgatito** [comment]
Пробуйте самую последнюю версию 0.0.43.

**Comment by yatsek20** [comment]
спасибо попробую

2018-02-14 14:45 GMT+02:00 Denis <notifications@github.com>:

**Comment by elgatito** [comment]
Есть прогресс по проблеме?
