### ISSUE TITLE
TV Pack with mkv files below 100MB are not listed

### ISSUE THREAD

**Issue by wwark** [elgatito/plugin.video.elementum#912]
Hi,

## Expected Behavior

List all playable files on a torrent file

## Current Behavior

Just playable files above 100Mb are listed

## Steps to Reproduce (for bugs)

1. Add Torrent with playable files below 100MB (like features)
2.
3.
4.

## Your Environment

* Version used:

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

Kodi Nexus on Ubuntu with last version of elementum

Maybe it is a configuration already available.
Thanks for your help

**Comment by antonsoroko** [comment]
@wwark 
>Maybe it is a configuration already available.

it is. default min size is 100mb. simply change it.
options names are like these:
https://github.com/elgatito/plugin.video.elementum/blob/7680e0bd365644a9cdae2e6b50bb55868f27593c/resources/language/messages.pot#L1548-L1558

**Comment by wwark** [comment]
thank you will test it

**Comment by elgatito** [comment]
Closing, as @antonsoroko did respond with a proper option to change.
