### ISSUE TITLE
Wrong version install from "All in one" pac - on LibreElec 12 , which is 64 bit, install armv7

### ISSUE THREAD

**Issue by g79petova** [elgatito/plugin.video.elementum#914]
## Current Behavior

When install from 'All in one' just armv7 is installed, when forcing install arm64 , show message"armv7 is needed"
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment 

* Version used: Elementum 1.87

* Environment name and version:Kodi 20-RC

* Operating System and version:Libre Elec 12 aarch64

* Link to Kodi debug log:

**Comment by antonsoroko** [comment]
@g79petova  hi.
not sure if this will be fixed anytime soon.
to fix it locally - try to set "platform" in settings to (probably) "linux_arm64".
see
https://github.com/elgatito/plugin.video.elementum/blob/7680e0bd365644a9cdae2e6b50bb55868f27593c/resources/settings.xml#L9 
and https://github.com/elgatito/plugin.video.elementum/blob/7680e0bd365644a9cdae2e6b50bb55868f27593c/resources/language/messages.pot#L1888-L1889

this issue looks similar to 
https://github.com/elgatito/plugin.video.elementum/issues/821#issuecomment-976088790
https://github.com/elgatito/plugin.video.elementum/issues/849#issuecomment-986256927
read those comments for alternative fix.

**Comment by g79petova** [comment]
default="Auto" mast be "linux_arm64"

**Comment by elgatito** [comment]
@g79petova 
Version 0.1.88 uses different approach to detect the platform. 
It should fix the problem.
