### ISSUE TITLE
Elementum last version for ipad ios 16 kodi error name ''Looks like elementum is still starting up, give it a few second'' please update and fix addon

### ISSUE THREAD

**Issue by Yus01443** [elgatito/plugin.video.elementum#915]
Elementum last version for ipad ios 16 kodi error name ''Looks like elementum is still starting up, give it a few second'' please update and fix addon
![6C1916D7-9964-48D0-8CA6-068B1439EE74](https://user-images.githubusercontent.com/131427572/233542508-d9d2566f-7c41-4cee-be9e-2a8cc5dc7590.png)

**Comment by Borzoff** [comment]
Same problem, using Raspberry Pi 4 on RpiOs 64 bit.

**Comment by elgatito** [comment]
There is no build for iOS, only for x64 MacOS, so it would not run there.
