### ISSUE TITLE
Not working [RPiOS64]

### ISSUE THREAD

**Issue by Borzoff** [elgatito/plugin.video.elementum#916]
Hello, I have a problem with the plugin not running on the raspberry pi os 64-bit

Kodi matrix

logs:
https://paste.kodi.tv/enedalogaq.kodi

**Comment by antonsoroko** [comment]
@Borzoff 
see line 2071
`2023-05-25 13:58:55.905 T:3851    FATAL <general>: [plugin.video.elementum] Unable to start library: /home/borzoff/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_armv7/elementum.so: wrong ELF class: ELFCLASS32`

looks like you need to manually set appropriate arch in elementum's settings.

see https://github.com/elgatito/plugin.video.elementum/issues/914
same issue i believe.

**Comment by elgatito** [comment]
@Borzoff  Try to install latest v0.1.88 and set platform to "Auto".
