### ISSUE TITLE
Elementum stuck in restart loop

### ISSUE THREAD

**Issue by paskal** [elgatito/plugin.video.elementum#92]
I've noticed during the film blue box with download stats. I wanted it to disappear, pushed "Exit" on remote controller (something like Backspace if you want to do the same on keyboard) to go to main menu and back.

My Raspberry Pi3 (model B, armv7) with latest [OSMC](https://osmc.tv/) stuck and I've stop\started it by unplugging power cable.

After restart I've started the plugin, go to film via "Torrent" menu item (it contained only film I've started watching before, 0% ready instead of 70% before restart), started it - it should start downloading, shown seeds and peers, but never made any progress in 5 minutes (stuck on 0% and zero speed, only showing seeds and peers).

I've tried to go out and back to torrent, something stuck, I've stop\started machine with power cable and repeated previous paragraph exactly.

Again, no progress - I've pushed "Cancel", "No" for "Proceed with download?" and "Yes" for "Delete files?", but torrent remained in place. I've repeated this a few times, machine stuck - I've power cycled it again.

After next boot I can't start Elementum, it's immediately crashing and restarting.

[Here is the log](https://pastebin.com/QJV94FEB) of constant restarts. Elementum previously updated from ~0.28 to 0.31 via repository and downloaded wrong architecture, so I had to remove it and install from [full ZIP](https://github.com/elgatito/plugin.video.elementum/releases/download/v0.0.41/plugin.video.elementum-0.0.41.linux_arm-7.zip), settings persisted after that reinstall. Burst plugin version was v0.0.9 or v0.0.10.

---

Please tell me, if I could provide any more useful info for investigation. I'll try to clear cache and everything and finally watch the film.

**Comment by paskal** [comment]
Also repository points to localhost, that's kind of strange. I've tried to uninstall and reinstall plugin from repo, and found this in log:
```20:33:05.765 T:1517196032   ERROR: CCurlFile::Stat - Failed: Couldn't connect to server(7) for http://localhost:65220/repository/elgatito/plugin.video.elementum/plugin.video.elementum-0.0.41.zip```

**Comment by paskal** [comment]
Regarding that part:
> My Raspberry Pi3 (model B, armv7) with latest OSMC stuck and I've stop\started it by unplugging power cable.

I've just reproduced it. Film on pause and downloading, I push "Exit" on remote, it opens blue screen with stuck download stats blue box on top right and "Video" title in top-left, that's it. Nothing could be done from here, it seems.

[Here is non-debug kodi.log](https://pastebin.com/mf0RzfsG). From log I see what download continues, just the UI stuck:

```
[osmc@osmc-Hamilton ~]$ tail -3 .kodi/temp/kodi.log ; date
21:06:45.218 T:1524282112  NOTICE: [plugin.video.elementum] DEBU  bittorrent   ▶ progressEvent    PR: 386662 (393216)/0; "Downloading" = 59.92
21:06:46.219 T:1524282112  NOTICE: [plugin.video.elementum] DEBU  bittorrent   ▶ progressEvent    PR: 527564 (1179648)/0; "Downloading" = 60.00
21:06:47.217 T:1524282112  NOTICE: [plugin.video.elementum] DEBU  bittorrent   ▶ progressEvent    PR: 543948 (638976)/0; "Downloading" = 60.04
Сб фев  3 21:06:48 MSK 2018```

**Comment by elgatito** [comment]
You have corrupted the database file (when used hard reset), try deleting it:
/home/osmc/.kodi/userdata/addon_data/plugin.video.elementum/library.db

**Comment by elgatito** [comment]
> Also repository points to localhost, that's kind of strange.

Elementum repository is virtual and managed by addon itself.

> I still have annoying blue box in top right with download status, this issue is originally meant to be created about it - blue box is not OK and distracts from watching;)

I don't know what is the "blue box", can you make a screenshot/photo to show it?

**Comment by paskal** [comment]
>You have corrupted the database file (when used hard reset), try deleting it:
> /home/osmc/.kodi/userdata/addon_data/plugin.video.elementum/library.db
I guess right behavior there might be detecting corrupted database and moving it to .bac, and starting over the clear one. I believe no matter what I do with my machine I don't need to know anything about `.kodi/userdata/addon_data/plugin.video.elementum/` location - this case can be fixed by the plugin itself.
>I don't know what is the "blue box", can you make a screenshot/photo to show it?
Will do.

**Comment by elgatito** [comment]
> I guess right behavior there might be detecting corrupted database and moving it to .bac, and starting over the clear one

There is database corruption detection, but your database opens fine and throws errors later.

**Comment by paskal** [comment]
> There is database corruption detection, but your database opens fine and throws errors later.

Ha, room for improvement!;)

**Comment by paskal** [comment]
> I don't know what is the "blue box", can you make a screenshot/photo to show it?
![img_1306](https://user-images.githubusercontent.com/712534/37540216-3859d690-2967-11e8-81e2-576f6533ae9e.jpg)
