### ISSUE TITLE
"Looks like Elementum is still starting up" on iPhone

### ISSUE THREAD

**Issue by trankien200691** [elgatito/plugin.video.elementum#921]
## Current Behavior
I have sideloaded Kodi 20.1 onto my iPhone (iOS 16.2) and installed Elementum (plugin.video.elementum-0.1.87.darwin_x64) and Burst (script.elementum.burst-0.0.73) from a zip file. However, when I tap on Elementum, a notification pops up saying, "Looks like Elementum is still starting up, ...". I have waited for a while, but nothing has happened.

[kodi.log](https://github.com/elgatito/plugin.video.elementum/files/11755906/kodi.log)

**Comment by elgatito** [comment]
@trankien200691 Elementum cannot run on iOS due to platform limitations.

**Comment by trankien200691** [comment]
> @trankien200691 Elementum cannot run on iOS due to platform limitations.

thank you!

**Comment by Hex34568** [comment]
> @trankien200691 Elementum cannot run on iOS due to platform limitations.

Do you of any other addons like elementum on IOS? bummer it can't work on ios :(

**Comment by Hex34568** [comment]
> > @trankien200691 Elementum cannot run on iOS due to platform limitations.
> 
> thank you!

yo dude did you find something similar to this?
