### ISSUE TITLE
[Bug] Wrong container content type

### ISSUE THREAD

**Issue by matke-84** [elgatito/plugin.video.elementum#923]
In this instance, it is a case of wrong container content type.
![111](https://github.com/elgatito/plugin.video.elementum/assets/74268331/2078b67c-415c-4867-b011-0b53b9aab5c3)
![222](https://github.com/elgatito/plugin.video.elementum/assets/74268331/7b6c9d26-7b74-4a9c-aba5-5e6bce40a9da)
![333](https://github.com/elgatito/plugin.video.elementum/assets/74268331/9dc4028f-c549-4b41-8525-32e585dfd7c8)
This leads to many problems. Elementum is setting "movies"/ "tv shows" so TMDbHelper is looking up movies. It also causes a lot of problems with the views because it shares the same view with movies and tv shows.
The genres directory should have container content of "genres" not "movies"/ "tv shows"
The base dir directory with search should have container content as "none" not "movies"/ "tv shows".

**Comment by elgatito** [comment]
@matke-84 Elementum is not settings `content_type` to `movies`, it sets to `menus_movies`.

**Comment by elgatito** [comment]
And it is not set to empty value, to allow changing the view for that type of content and save that selection.

**Comment by matke-84** [comment]
@elgatito I don't doubt that you set the container to menu_movies, but as you can see in the picture (upper left corner), Kodi registers it as a movies/tv shows container. This creates quite a problem with listitem monitors that pull data directly from the network. Also, if I change the view of the menu, the view of the movie/tv show container changes also and vice versa.I have checked some other similar addons for movies and they are set up properly and do not have these problems.

**Comment by elgatito** [comment]
@matke-84 You can check Elementum v0.1.88.

**Comment by matke-84** [comment]
@elgatito I would like to try it, but the installation is broken. Maybe you messed something up while packing files. I tried it android arm package as always. 0.1.87 is working.

**Comment by matke-84** [comment]
@elgatito Now I noticed that some packages are missing, for example for windows.

**Comment by elgatito** [comment]
After I removed `menu_movies` - people complain that it is not working as they used to.

I'm looking at what values are accepted and can't see anything good for lists  of subctegories - https://alwinesch.github.io/group__python__xbmcplugin.html#gaa30572d1e5d9d589e1cd3bfc1e2318d6

**Comment by matke-84** [comment]
I don't understand what they are complaining about? Now it finally works properly.

**Comment by elgatito** [comment]
I think in some skins skin does not like that empty `content_type`.
I'm looking what tmdbhelper is doing and they set empty values if there are no movies/shows listed.

**Comment by matke-84** [comment]
I always test first with the default kodi skin and then with my titan bingie mod. It works perfectly with both. I'll try a little later with another skins and let you know the results. Of course, if you find a better solution, great. Let's just not go back to the old ways.

**Comment by elgatito** [comment]
@matke-84 Well, on default skin it always work fine, because it does not matter what content you have there :)

**Comment by matke-84** [comment]
I just tried a few popular skins.
Aeon nox, Artic zephyr reloaded, Aura mod, Titan bingie mod, Embuary... Each works perfectly.
The only one that doesn't work is Artic horizon 2. Which means it's up to the skins and not to elementum. A skin developer needs to sort out his skin.

**Comment by elgatito** [comment]
I've changed a little bit default value and verifies with Arctic Horizon, should be fine with 0.1.92.

**Comment by matke-84** [comment]
Yeap. Everything is fine. 👍
