### ISSUE TITLE
[Bug] Cannot install new update 0.1.88

### ISSUE THREAD

**Issue by matke-84** [elgatito/plugin.video.elementum#924]
Same error every time. Tried it on Windows and Android platforms.

`error <general>: CAddonInstaller: installing addon failed 'D:\Downloads\plugin.video.elementum-0.1.88.windows_x64(1).zip' - itemsize: 2, first item is folder: true`

It also doesn't show up with auto-update.

**Comment by elgatito** [comment]
Reverting whole release.

**Comment by matke-84** [comment]
OK. I hope you will quickly find where the problem is.

**Comment by elgatito** [comment]
@matke-84 Please, try it now.

**Comment by matke-84** [comment]
@elgatito Something is wrong with the installation on android, more precisely with 0.1.89 repository. When I manually install version 0.1.89 android arm, elementum installs normally, then it starts to install burst, after a few seconds it says that it couldn't install automatically. I go to elementum repository and it says could not connect to repository. I delete version 0.1.89, install version 0.1.87, everything works normally. Version 0.1.89 works normally on windows.

**Comment by matke-84** [comment]
@elgatito Still the same problem with version 0.1.91. In order to install version 0.1.91, specifically burst and context menu, I need to install version 0.1.87 first, since this is the last version that the elementum repository works on.
What happened with elementum repository in the new versions? Android 11, Kodi 20.2.

**Comment by giddyup69** [comment]
I believe I am having a similar problem. Trying to run fresh libreelec install. When I install most recent version of elementum Kodi crashes. Then on reboot it automatically crashes entering the os. This will happen a few times then it enters safe mode. I ssh in and delete elementum and j can boot again. I found an older release 0.88 and it works even with newest burst.

**Comment by Bequiet19** [comment]
Absolutely the same problem as @matke-84. Elementum 0.1.91 is installed, but the burst will not. When I go to manually install it, it can't connect to the repository. 0.1.87 works.

**Comment by elgatito** [comment]
@Bequiet19 @giddyup69 Provide a Kodi log file.
https://elementum.surge.sh/contribute/log/

**Comment by elgatito** [comment]
This issue should be related to repository issue. Should work fine with 0.1.92.
