### ISSUE TITLE
Kodi 18.9 Install Failed  with .88, .89, AND .91

### ISSUE THREAD

**Issue by Dhuntley0000** [elgatito/plugin.video.elementum#931]
The title says it all. Kodi 18.9 Install Failed  with .88, .89, AND .91

In addition, when the install fails, it leaves itself in the temp directory with each failed install and temp files must be removed manually.

Any ideas would be appreciated.

**Comment by Dhuntley0000** [comment]
More info. This appears to occur ONLY with .91 generic (All In One) The Platform specific version seems to install OK. Only issue I have now, is after downloading, the file will not autoplay, I have to navigate to the download and play it manually. Not a big deal, but was working OK in .86

**Comment by elgatito** [comment]
You should provide log file from Kodi. You don't even say your platform.

**Comment by antonsoroko** [comment]
@Dhuntley0000 http://elementum.surge.sh/contribute/log/ 
next time please use the template (that you erased), it has all the info you need to provide.

**Comment by Dhuntley0000** [comment]
Sorry, didnt realize

**Comment by elgatito** [comment]
@Dhuntley0000 Closing this one.
Make sure you download 0.1.92 version (or later) and if it does not work - try to re-download zip file and install it again (on top).
