### ISSUE TITLE
[Question] force start as a library

### ISSUE THREAD

**Issue by ShlomiD83** [elgatito/plugin.video.elementum#937]
Hi @elgatito ,
Sorry for opening an issue for a question but you haven't allowed discussions..

I would like to know the meaning of this setting.
![16894459306634940930354887455869](https://github.com/elgatito/plugin.video.elementum/assets/17053215/6a4932b4-5953-4d97-92d7-ea69661b92cf)

Thanks.

**Comment by elgatito** [comment]
Which one?

**Comment by ShlomiD83** [comment]
It's in the title my friend.
"force start as a library"

**Comment by elgatito** [comment]
Elementum is now built in 2 variants: as binary (as it always was) and as shared library, so that it would run as part of Kodi process.
That is helping to run on android, or elsewhere if starting binary is disallowed.

**Comment by ShlomiD83** [comment]
Cool, thanks for the quick answer.
