### ISSUE TITLE
[Request] Add options to hide progress when Kodi Player is active

### ISSUE THREAD

**Issue by johndoe71rus** [elgatito/plugin.video.elementum#94]
## Expected Behavior
часы и время окончания в правом углу при паузе или движении курсором
## Current Behavior
отсутствие выше указанного при сохранении в память или mmap
при сохранении в файл часы присутствуют
## Possible Solution
возможно теряется заголовок с длительностью файла и коди не может вычислить длительность окончания.

## Your Environment
Kodi version 17 [Krypton] lubuntu 14.04

**Comment by elgatito** [comment]
Я не нахожу никакой информации как управляется вывод часов и управляется ли вообще чем-то кроме скина Коди.
Всё что мы передаём для воспроизведения видео это duration.
У меня и для файлов часы не выводятся. 

Если найдете причину - будем разбираться. Пока я не нахожу ничего.

**Comment by johndoe71rus** [comment]
как найти причину я к сожалению не знаю.
Из наблюдений, сделал логофф и часы в углу появились. Обрадовался что бы временный глюк. Но потом заметил, так же как у вас, иногда пропадает иногда появляется. Закономерности выявить не удалось.

**Comment by elgatito** [comment]
> иногда пропадает иногда появляется

Совершенно верно. В одном и том же файле можно показывать/убирать управление - результат будет разный.

**Comment by vevsvevs** [comment]
На Libre/CoreELEC опция "Disable background progress dialog" решает проблему с часами.

**Comment by johndoe71rus** [comment]
на что влияет эта опция? Какие функции отключает

**Comment by elgatito** [comment]
Показывает прогресс скачивания в углу экрана.

**Comment by johndoe71rus** [comment]
наверно этот прогресс в углу и вылезал, в соседнем топике. Он наверно и не нужен, на паузе чуть выше линии прогресса инфа выводится

**Comment by elgatito** [comment]
Forgot to mention it's added into 0.0.48. 
By default, progress is hidden when player is playing something. Clock is now always shown.
