### ISSUE TITLE
Kodi 20.2 stopping working ELEMENTUM 0.1.95

### ISSUE THREAD

**Issue by icarok99** [elgatito/plugin.video.elementum#940]
This problem only happens on devices with Android_ARM64 architecture.

[Video](https://youtu.be/cQ9U1334t54) 

[Kodi log](https://drive.google.com/file/d/1-H4pLiZYMmv1H7etfqxfqDHfBZ_aQttZ/view?usp=drivesdk)

**Comment by elgatito** [comment]
There is already #903 , why you create another issue?
