### ISSUE TITLE
Torrent with multiples files dont open

### ISSUE THREAD

**Issue by MichaelAndoid** [elgatito/plugin.video.elementum#942]
Wen i have a torrent with many files only let me choose one time the inside file to play, wen i go to torrents and click on "Select file to download" or "Select File to play" shows message "Internal error", tested with 2 android boxs and same error, i have last Kodi and last Elementun.

In the past 2022 already used this without problems.

**Comment by antonsoroko** [comment]
@MichaelAndoid why you ignored "issue template"? it has a link about how to provide log file, which is crucial.

**Comment by elgatito** [comment]
@MichaelAndoid The reason why there is an issue template asking to provide information, is that people create issues without showing logs and without even saying which version they use.

**Comment by MichaelAndoid** [comment]
You are right but iam afraid to put sensitive information on public.
Is there other option to send private the log only to you?

Regards

**Comment by elgatito** [comment]
@MichaelAndoid I think I have found a root cause.

**Comment by MichaelAndoid** [comment]
If you need me to test something please say.

Thanks for all the great work

**Comment by elgatito** [comment]
@MichaelAndoid Sorry for the delay. It took a while to come over this change.

Please, try v0.1.98, it should fix the issue.

**Comment by MichaelAndoid** [comment]
You are the Boss, now its working on this new version 0.1.98.

Thanks ;)
