### ISSUE TITLE
Elementum is crashing from today not opening on Kodi android tv.

### ISSUE THREAD

**Issue by kumar624** [elgatito/plugin.video.elementum#947]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

**Comment by pavelmxx** [comment]
Meybe this would help.
`https://github.com/elgatito/plugin.video.elementum/issues/646`

**Comment by elgatito** [comment]
@kumar624 Should work fine with latest Elementum version. If not - please, share Kodi log, as issue template is asking to.
