### ISSUE TITLE
After shared library change elementum stopped to show error in UI

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/plugin.video.elementum#958]
## Current Behavior

после https://github.com/elgatito/elementum/commit/98bc2fbeea6b27e53f2b6bfe61ff9b5567fb49d9
если сделать папку загрузок незаписываемой, то https://github.com/elgatito/elementum/blob/6aea37dab272b523d6ec42dd75ef123031e388d6/config/config.go#L474 мы идём в https://github.com/elgatito/elementum/blob/6aea37dab272b523d6ec42dd75ef123031e388d6/exit/exit.go#L64 но там не паникуем.
соответственно defer recover не срабатывает https://github.com/elgatito/elementum/blob/6aea37dab272b523d6ec42dd75ef123031e388d6/config/config.go#L346 

## Possible Solution

добавить в конец [PanicWithCode](https://github.com/elgatito/elementum/blob/6aea37dab272b523d6ec42dd75ef123031e388d6/exit/exit.go#L64) `panic(err.Error())`? у меня тогда работает и в режиме бинаря и библиотеки.
но я могу что-то не учитывать, потому не стал делать PR.

правда для библиотеки  - неважно починишь путь или нет - коди сегфолтится. для бинаря просто рестарт и всё ок.
upd: ан нет, коди всегда у меня `Segmentation fault (core dumped)` если библиотекой запускать элементум.

## Steps to Reproduce (for bugs)

1. remove write permission from download directory
2. start kodi
3. see errors in log
4. but not in IU

## Your Environment

* Version used: 0.1.98

* Environment name and version: kodi 20.2

* Operating System and version: linux 6.5.0-14-generic

* Link to Kodi debug log:

binary https://paste.ubuntu.com/p/jsTxp3Knwk/
library without fixing directory permissions https://paste.ubuntu.com/p/vwGKz2dsGK/
library with fixing directory permissions https://paste.ubuntu.com/p/DCKZn2pNYH/

**Comment by elgatito** [comment]
Любой `exit` (а `panic` включает в себя `exit 1`) в библиотеке вызовет segfault.
Идея в том чтоб довести любую критическую ошибку до `PanicWithCode` которая должна закончить функцию входа в библиотеку и питон перезапустит сам. Segfault в любом случае не должно быть, ошибка должна показаться и попытка перезапуститься несколько раз.

**Comment by antonsoroko** [comment]
@elgatito тут смешались 2 вещи
1. сейчас нету panic в коде config и соотв нету вывода ошибки в UI через defer для бинаря и для бибилиотеки

2. для библиотеки у меня сегфолт и с добавленной паникой и без (без изменения кода). тут какая-то отдельная история, для отдельного бага.

**Comment by antonsoroko** [comment]
fixed by https://github.com/elgatito/elementum/commit/cebb67d98a088930422746d92613175de649a93d
