### ISSUE TITLE
[Bug] File Handling Issues / Torrent state Percentage stuck in Gui but keeps Downloading

### ISSUE THREAD

**Issue by Bloodhunter4rc** [elgatito/plugin.video.elementum#96]
Having issues with file handling and torrent handling. It does not happen all the time but often when using File Storage the Download Percentage is stuck and does not Increase inside Elementum -> Torrents and not on the Webinterface (http://127.0.0.1:65220) however the Torrent still keeps downloading you can see that in http://127.0.0.1:65220/info.

So torrent ist stuck  at 64% or 39% etc in Gui but it still finishes to download after that it never moves the completed files cause it probably believes its not finished so it keeps seeding forever even if seedtime is set to 1 hour. With manual selection "Move to completed" it sometimes works to move the files when it seems not finished in gui.

I also never were able to pause Torrents in Elementum -> Torrents, maybe that is a known issue or currently not implanted?

Additional to that if it works and it moves the file to Completed folder it never deletes any folders in the Download Directory so its full with empty folders. Sometimes it also just keeps the completed file in the Download folder and never moves the file to the completed directory even though its stated as finished and seedtime (1 hour) has passed.

Quasar on same system set to same directory seems to move the files fine.

Maybe have the download state checked against the torrent engine, if thats not  allready the case cause that seems more accurate?

Also it should delete the source directory after moving the files to completed directory.

**Will provide log when i am able to reproduce.**

## Your Environment
Elementum 0.0.42 Android ARM64
External HDD storage NTFS /android/data/xbmc.org/elementum/

**Comment by jaapie1989** [comment]
I have exactly the same problem on my NVIDIA shield.

**Comment by elgatito** [comment]
@Bloodhunter4rc  can you check with the latest 0.0.43 version and send a kodi.log file if you still have an issue?

**Comment by elgatito** [comment]
Closing without response.
