### ISSUE TITLE
Is it possible to recover from all non critical panics in golang part of elementum?

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/plugin.video.elementum#964]
## Current Behavior

сейчас очень точечно сделаны `recover()` ( https://github.com/search?q=repo%3Aelgatito%2Felementum%20recover()&type=code ) и только для cache мы не выходим из демона.
хотя для всяких нестрашных ситуаций, аля серия равна nil, или там какая-то информация о шоу равна nil - мы могли бы просто показывать визуальную ошибку в kodi, чтобы пользователь увидел и мог прислать баг, но при этом не убивать демон.
может можно как-то это реализовать красиво и правильно?
сейчас в коде везде пытаемся превентивно проверять на nil, порой даже если nil быть не должно, но часто что-то проскакивает всё равно. 
плюс с таким recover будет лучше user experience.

просто идея. поднадоели эти проверки на nil и падания из-за того что где-то проверку забыли :-)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

**Comment by antonsoroko** [comment]
@elgatito 
увидел что недавно был сделан https://github.com/elgatito/elementum/commit/9783be58d4a7cb23c4df5259730ec1cde1a3179a с кучей проверок на nil от nilaway, прикольно.

но всё таки интересно, можно ли как-то сделать recover для всех некритических паник?

**Comment by elgatito** [comment]
@antonsoroko `recover` действует только в пределах функции где он был объявлен, так что не получится.

**Comment by antonsoroko** [comment]
блин, как-то я это пропустил.
они даже обсуждали это и отказали: https://github.com/golang/go/issues/ 32333
https://stackoverflow.com/questions/73697230/does-golang-support-global-recovery
