### ISSUE TITLE
Elementum on WebOS

### ISSUE THREAD

**Issue by Blkp927** [elgatito/plugin.video.elementum#967]
This is proably gonna sound really dumb but how do I even get elementum on Kodi if I cant download file on webos or how do I get kodi

**Comment by antonsoroko** [comment]
@Blkp927 how about using google/bing/yandex/duckduckgo/baidu or similar web search engine? :-)

type something like "lg webos install kodi" and you will get link to official kodi wiki:

https://kodi.wiki/view/HOW-TO:Install_Kodi_for_webOS

**Comment by Blkp927** [comment]
oh no that was really bad i meant i have kodi but i cant download elementum because I can’t find a way to download zip files without a repo

**Comment by antonsoroko** [comment]
@Blkp927 please **read** wiki page i provided. it has a link to tool that can upload files to webos, as i can see on screenshots.

**Comment by Kasiqno** [comment]
Hi Blkp927 I have the same problem, have you fixed it up? how did you install Elementum in Webos tv?

**Comment by antonsoroko** [comment]
@Kasiqno what problem? 
Everything was described above.

You install DevMode Manager for webOS TV, you install Kodi via that app, you upload zip file with Elementum softfp version, again via that app. 

https://user-images.githubusercontent.com/830358/215522354-50997437-e3de-43a9-89cc-52cdaecb0502.png

You can read Kodi wiki and devmode manager's readme for details (link is in message I posted earlier).

**Comment by Kasiqno** [comment]
My problem is: I got Kodi installed by DevMode Manager ok, but after that I can't install Elementum by adding source, and the other ways I've found to do it is getting a zip file and copy in USB unit, but the problem then is when I try to install it (menu: installation from zip) the LG tv can't find the zip file in USB. Do you know how can I get the USB read?

**Comment by antonsoroko** [comment]
@Kasiqno have you tried to upload zip file via DevMode Manager like i suggested twice already? like on this screenshot
https://user-images.githubusercontent.com/830358/215522354-50997437-e3de-43a9-89cc-52cdaecb0502.png

i do not have webos, so i can't test it.
BUT people here https://forum.kodi.tv/showthread.php?tid=368381&pid=3211802#pid3211802 were able to install addons via zip files.
**but not via USB, it seems. so just use "DevMode Manager" to upload files, or use "SCP / SFTP, local webserver/ SMB /NFS share" as people suggest in kodi forum.**

---

(also, on "android tv" to see zip files you need to grant kodi access to all files, not only to media files, maybe there is similar setting in webos, i do no know. but try to use  "DevMode Manager" first.)

also, guys from 2 issues that  i posted above were able to install elementum, so you also should be able to.
good luck!

**Comment by Kasiqno** [comment]
My problem now is to take the zip downloaded from my Mac to LG tv webos using DevMode Manager.

**Comment by antonsoroko** [comment]
Based on screenshot (that I posted twice already), you just need to open "files'"  tab and click "upload" button.

**Comment by Blkp927** [comment]
> My problem now is to take the zip downloaded from my Mac to LG tv webos using DevMode Manager.

Exactly what i tried doing i don't really remember but i think i never got the the files on there because in dev manger it wouldn't let me access the right files because it needed root access which i dint have because my tv wasn't jailbreaked

**Comment by antonsoroko** [comment]
@Blkp927 I think you should ask this question in some specialized LG forum or search in internet. 
In theory, you just need to upload file to any writable location (like /home/<username>/ or /tmp/), so root access should not be needed. 

But again, better to ask in specialized place.

**Comment by Kasiqno** [comment]
When I try I get this:

**Comment by antonsoroko** [comment]
@Kasiqno If you wanted to attach image then you should do it here via browser, not via email. Your message is empty.

But anyway, I already wrote above my thoughts:

I think you should ask this question in some specialized LG forum or search in internet.
In theory, you just need to upload file to any writable location (like /home/some_user_name_here/ or /tmp/), so root access should not be needed.

But again, better to ask in specialized place.

This is not Elementum issue. It is not even Kodi issue.

**Comment by elgatito** [comment]
Closing the issue.

For WebOS please use `armv7_softfp` as the platform, if Kodi cannot properly detect which one to use. 

The goal is to somehow get plugin zip or repository zip into your Kodi, then Kodi will be able to install addon and run it.
