### ISSUE TITLE
Opensubtitles.com : cannot find subtitles for movie show. Always have to type manually the name of the show

### ISSUE THREAD

**Issue by jfhautenauven** [elgatito/plugin.video.elementum#969]
Hello,

Since OpenSubtitles.org has shut down its access, I switched to OpenSubtitles.com official add-on.

Only issue is that I have to always type via the manual search the name of the movie show, season and episode.
This does not happen with the other sources (integrated Elementum, or the old OpenSubtitles.org).

Is there some kind of integration that has to be adapted for Elementum to do it transparently ? 

Thanks in advance for your help.

Running Elementum latest version 1.99

**Comment by elgatito** [comment]
@jfhautenauven There is already an issue #952 that tracks OpenSubtitles migration. 

Currently opensubtitles**.org** is in use.

**Comment by antonsoroko** [comment]
@jfhautenauven 

>Is there some kind of integration that has to be adapted for Elementum to do it transparently ?

as far as i remember - no, there is no some specific "integration" for "external" OpenSubtitles.org addon.

so i guess in OpenSubtitles.com addon they do search somehow different from old ORG addon.
