### ISSUE TITLE
Постоянный перезапуск и краш из-за большого кол-ва ошибок

### ISSUE THREAD

**Issue by promidrol** [elgatito/plugin.video.elementum#97]
Версия .42 система win10
При запуске KODI версия 18
Сверху появляется несколько раз диалоговое окно с надписью "Упс перезапуск", а потом "не удалось запустить из-за большого кол-ва ошибок"
Лог выкладываю [http://paste.ubuntu.com/26541219](url)

**Comment by elgatito** [comment]
Приложению не даёт система создать файл. Можете проверить путь, есть ли такой: `C:\Users\wizz\AppData\Roaming\Kodi\addons\plugin.video.elementum\.lockfile`

```
16:30:24.604 T:17400  NOTICE: [plugin.video.elementum] WARN  main         ▶ ensureSingleInstance  Unable to acquire lock "C:\\Users\\wizz\\AppData\\Roaming\\Kodi\\addons\\plugin.video.elementum\\.lockfile": The handle is invalid., killing...
16:30:24.605 T:17400  NOTICE: [plugin.video.elementum] WARN  main         ▶ ensureSingleInstance  Unable to find other process: OpenProcess: Access is denied.
16:30:24.605 T:17400  NOTICE: [plugin.video.elementum] WARN  main         ▶ main             Unable to acquire lock "C:\\Users\\wizz\\AppData\\Roaming\\Kodi\\addons\\plugin.video.elementum\\.lockfile": OpenProcess: Access is denied., exiting...
16:30:24.608 T:17400  NOTICE: [plugin.video.elementum]
```

**Comment by promidrol** [comment]
Да есть такой файл

**Comment by elgatito** [comment]
Ваша система не даёт писать файл/перезапускать. Можете попробовать удалить файл. Если ошибка останется - пробуйте менять настройки безопасности для приложения (Коди). Само дополнение ничем не поможет.

**Comment by promidrol** [comment]
Понял спасибо)
