### ISSUE TITLE
Trakt calendar is not updating

### ISSUE THREAD

**Issue by HotEdik** [elgatito/plugin.video.elementum#982]
The list of upcoming TV episodes is not updated until you manually clear the Trakt cache. Watched and overdue episodes do not disappear. New episodes do not appear. Once the list is cached from Trakt, Elementum takes it from cache always. 
## Expected Behavior

Trakt Calendar in Elementum addon is updated once the source (information on Trakt site) is updated without necessity of manual cache cleaning.
## Current Behavior

Trakt Calendar is updated only after Trakt cache is cleaned manually.
## Steps to Reproduce (for bugs)

1. In Elementum go to TV Shows > Trakt Calendars > My TV Shows. 
2. Once list is loaded and cached, watch some of the episodes or wait couple of days until some of the episodes are expired.
3. Go to TV Shows > Trakt Calendars > My TV Shows again.
4. Cached list with outdated and watched episodes is shown. New episodes from the calendar are not shown.
5. Go to Settings > Additional > Clean Trakt Cache.
6. Go to TV Shows > Trakt Calendars > My TV Shows again. 
7. Updated list is shown without outdated and watched episodes and with new episodes from the calendar.

## Context

Very inconvinient to use Trakt Calendar as a list for skin widgets as well as using it from the addon menu.
## Your Environment

* Version used: 0.1.99

* Environment name and version: Kodi v. 20.3, ARMv7a

* Operating System and version: Android 11

* Link to Kodi debug log:

**Comment by antonsoroko** [comment]
in version 0.1.99 cache is used to be 7 days for calendars, that's why you did not see new episodes. in "in development" version it is 6 hours. i made a change to make 1 hour for "my" calendars (since you can add new show) and 1 day for "all" calendars (or maybe 7 days, since user can change it anyhow).

as for watched episodes - we never hide them in calendar. i added this feature as optional.

(btw, to avoid confusion about release dates - also check your settings to see if you allow to show episodes on same day.)

**Comment by HotEdik** [comment]
В пул-реквесте увидел, что можно и по-русски :) 
Про 7 дней понял. Теперь яснее стало, почему на другой приставке иногда календарь все-таки обновляется (потому что я ее долго не включал :))). 
Пожалуй, подожду тогда новой версии. Спасибо за труды!

**Comment by HotEdik** [comment]
> in version 0.1.99 cache is used to be 7 days for calendars, that's why you did not see new episodes. in "in development" version it is 6 hours. i made a change to make 1 hour for "my" calendars (since you can add new show) and 1 day for "all" calendars (or maybe 7 days, since user can change it anyhow).

В пул-реквесте увидел, что можно и по-русски :)
Про 7 дней понял. Теперь яснее стало, почему на другой приставке иногда календарь все-таки обновляется (потому что я ее долго не включал :))).
Пожалуй, подожду тогда новой версии. Спасибо за труды!
