### ISSUE TITLE
Elementum can not open official Trakt public lists

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/plugin.video.elementum#985]
## Current Behavior

Elementum can not open official Trakt public lists, we use `user.ids.slug` in code - it is null for such lists.
And I guess we must use https://trakt.docs.apiary.io/#reference/lists/list-items/get-items-on-a-list for such lists, not https://trakt.docs.apiary.io/#reference/users/list-items/get-items-on-a-personal-list

## Possible Solution

I guess we must use https://trakt.docs.apiary.io/#reference/lists/list-items/get-items-on-a-list for "official" lists.

Just a note: strange that https://api.trakt.tv/lists/41/items works but https://api.trakt.tv/lists/41 does not.
https://github.com / trakt / api-help / issues / 389#issuecomment-1948468907 (пробелы чтобы github не создал связь )
## Steps to Reproduce (for bugs)

1. open official lists https://trakt.tv/search/lists?page=1&sort=score&types=official
2. like any list, e.g. https://trakt.tv/lists/official/james-bond-collection?sort=rank,asc
3. open movies -> my lists -> "newly added list"
4. see "error->re-try" loop

## Your Environment

* Version used: 0.1.99 214aab5f32bf2f8c553a37419e9f22a2760d11c0

* Environment name and version: kodi 20.2

* Operating System and version: Ubuntu 23.10 x64

* Link to Kodi debug log: https://paste.ubuntu.com/p/wdpgpyJm2r/

**Comment by elgatito** [comment]
@antonsoroko I added support for public lists in latest Elementum code. Please, test if everything is working properly.

**Comment by antonsoroko** [comment]
@elgatito работает для официальных. только IsPersonal() странное что-то проверяет, User.Ids.Slug пустой только у официальных листов, это явно не Personal. И Slug() отдаёт или имя юзера или имя листа, что опять как-то странно, так как это разные идентификаторы.

>A slug is a human-readable, unique identifier, used to identify a resource instead of a less human-readable identifier like an id .

сделал фикс на мой вкус, может понравится полностью или частично - https://github.com/elgatito/elementum/pull/105

плюс ещё нашёл баг с пустым пользователем при фоновом обновлении списков - они перестали обновляться.
