### ISSUE TITLE
Use "Romanization of Japanese" title as 'original' for Anime search

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/plugin.video.elementum#987]
anime tracker usually use https://en.wikipedia.org/wiki/Romanization_of_Japanese (when you use Latin alphabet to write Japanese words).

so i think we can add an option that will set "original" to "jp" (not `:ja` (it is real Japanese) but `:jp`).
we already have an option to set "original" to "en":
https://github.com/elgatito/plugin.video.elementum/blob/214aab5f32bf2f8c553a37419e9f22a2760d11c0/resources/settings.xml#L288
https://github.com/elgatito/plugin.video.elementum/blob/214aab5f32bf2f8c553a37419e9f22a2760d11c0/resources/language/messages.pot#L1573
https://github.com/elgatito/elementum/blob/efdcb9af863f3fca5cf63afe3c80da8249cc0ccb/providers/xbmc.go#L407

## Current Behavior

https://github.com/elgatito/script.elementum.burst/issues/382

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: 0.1.99

* Environment name and version: 

* Operating System and version:

* Link to Kodi debug log:

**Comment by elgatito** [comment]
I don't think Elementum should overwrite any languages or have special cases. 
It should be implemented in a searcher addon if some language needs a special approach.
Elementum is returning all available information to searcher and expects results.

**Comment by antonsoroko** [comment]
But we already have "Use english title as 'original' for Anime search". But for anime English makes less sense than "romanized japanese".
But we can make such option (about "romanized japanese" I mean) in burst (instead of elementum).

**Comment by elgatito** [comment]
> But we already have "Use english title as 'original' for Anime search". But for anime English makes less sense than "romanized japanese".

There are special cases in Burst, how we replace "original" titles. 
We can extend with ` if language["original"] == "jp" then return ["jp", "ja"]`.
Unless you want to avoid making `jp` requests at all.

**Comment by antonsoroko** [comment]
@elgatito не нашёл где в burst мы меняем original. https://github.com/search?q=repo%3Aelgatito%2Fscript.elementum.burst+original+path%3A%2F%5Eburst%5C%2F%2F&type=code

мы используем original как fallback - это да, а вот чтобы мы перезаписывали original другим языком как в https://github.com/elgatito/elementum/blob/efdcb9af863f3fca5cf63afe3c80da8249cc0ccb/providers/xbmc.go#L407 - не вижу.

соответственно, не ясно куда лучше вставить такую перезапись.
сюда может? https://github.com/elgatito/script.elementum.burst/blob/61c513a026262cc273dd97e894db65c93fe8677b/burst/filtering.py#L311

по поводу примера, `ja` это иероглифы, а `jp` это латиница. ну и кажется нет смысла искать иероглифы в принципе.
по идее можно заменять `ja` на `jp` для всего японского, а не только для аниме, как сделано в elementum части.
