### ISSUE TITLE
Why are there 2 elementum repos?

### ISSUE THREAD

**Issue by pitsi** [elgatito/plugin.video.elementum#988]
I just noticed that there are 2 repos for elementum, the old one, named "Elementum Repository" and a new one, named "ElementumOrg Repository". Proof 
```
# ls .kodi/addons/ | grep elementum
plugin.video.elementum
repository.elementum
repository.elementumorg
script.elementum.burst
```
When did this happen? Do we keep the old repo too?

p.s. Sorry for not following the issue reporting guidelines. My questions are really simple to answer, so I skipped them.

**Comment by eeden003** [comment]
Hi there. I have nó answer, but I use both the repo's and indeed, there is a lot of difference between the two elementum addons on my tv-box, but they both work so I'm not worried.

**Comment by pitsi** [comment]
Which are your **two** elementum addons and what differences do they have? :/

**Comment by elgatito** [comment]
@pitsi In earlier versions Elementum was creating/installing repository addon and it was working through Elementum. Elementum is not working = repository is not working.

In latest versions Elementum is installing self-hosted repository (https://github.com/ElementumOrg/repository.elementumorg) that can work without Elementum.

**Comment by pitsi** [comment]
I knew all that, I have been using elementum for more than 5 years now.

> In latest versions Elementum is installing self-hosted repository that can work without Elementum.

Does this mean I **have** to keep them both?

p.s. I will be afk tomorrow, Monday the 26th, so please do not close the issue if I do not reply early. Thank you.

**Comment by elgatito** [comment]
@pitsi 

> Does this mean I have to keep them both?

Now, those are separate repositories. You can delete "repository.elementum". Or delete both of them, Elementum will re-install the one that is actual.

**Comment by pitsi** [comment]
Thank you. I just removed the old one.
