### ISSUE TITLE
use_original_title controls both UI and torrent search

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/plugin.video.elementum#991]
use_original_title was introduced in https://github.com/scakemyer/plugin.video.quasar/issues/200 for [UI](https://github.com/scakemyer/quasar/commit/e2df169a2973f14bb92254cf612497eb837857e9).
but after https://github.com/elgatito/elementum/commit/da47ba8408cc35a24210fc603b815e7a8d906999 + https://github.com/elgatito/plugin.video.elementum/commit/79cfb6050c04e0a9a266a9c2bb91f9798dbc6a65#diff-8e5952d4ad33bfc8e7b5b8739c8f898dd3f950d0f2548bc09f901489f50f6339R110
this option is also used for search.
which is inconvenient.
e.g. i want to see translated titles in UI but use original titles for torrent search.

## Expected Behavior

2 different options: one for UI and one for torrent search.

## Current Behavior

use_original_title controls both UI and torrent search.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

**Comment by antonsoroko** [comment]
also after https://github.com/elgatito/elementum/commit/d2e109b50ab092a70fff699412d435d9ff0b35f8 things about translated vs original titles became more complicated.
also UseOriginalTitle is used only for movie/show, but not for season/episode.

so maybe it makes sense to delete those
````
	if config.Get().UseOriginalTitle && show.OriginalName != "" {
		name = show.OriginalName
	}
```
and use `UseOriginalTitle` only for search?

or new `UseOriginalTitleUI` option can be added and used inside those new `GetTitle()`/`GetName()` functions.

**Comment by antonsoroko** [comment]
как-то всё намешано выходит.

в burst есть ещё `kodi_language` ("Использовать язык Kodi когда доступен перевод")
https://github.com/elgatito/script.elementum.burst/blob/61c513a026262cc273dd97e894db65c93fe8677b/resources/settings.xml#L395

соотв, если UseOriginalTitle не включена, то мы всегда передаём в burst переведённое имя, и kodi_language теряет смысл (название уже переведено). 

учитывая это, я бы предложил всегда в burst передавать `Original` имя, а там уже burst пусть переводит или нет.

а UseOriginalTitle использовать тогда только для UI (в этих новых `GetTitle()/GetName()`).

ну или для обратной совместимости оставить передачу по-умолчанию переведенного имени в burst (kodi_language так и останется бессмысленной опцией, но и пользователям не придётся её включать и они не заметят изменений), но тогда хотя бы разрезать UseOriginalTitle на UI и search части.

**Comment by antonsoroko** [comment]
@elgatito 
посмотрел ещё в
https://github.com/fugkco/script.elementum.jackett/blob/fceaee5ebe724da8b6da6e7840014ef70c587081/src/jackett.py#L108

`payload["search_title"] = payload["titles"][kodi_language]`

соотв script.elementum.jackett использует язык коди по умолчанию (если может), так что предложение всегда передавать провайдерам original имя не сломает ни его, ни burst (только в burst нам надо будет включить по-умолчанию `kodi_language`).

**Comment by elgatito** [comment]
@antonsoroko 

> Or new UseOriginalTitleUI option can be added and used inside those new GetTitle()/GetName() functions for all videos (movie/show/season/episode).

Yes. I would prefer this option. Get rid of any direct use of `OriginalName`/`OriginalTitle` fields and use it inside `GetName`/`GetTitle` methods.

**Comment by elgatito** [comment]
> this option is also used for search.

I don't think it is used in actual Burst code. 
It was used when there was no language specific searches in Burst and it was using `title` field as a name directly. So Elementum was only able to influence search by title.

Now Burst (or othre search addon) can decide what it wants to use, so not even sure if we need to override `title` with original names in search payload.

**Comment by antonsoroko** [comment]
@elgatito 

в таком случае готово:
https://github.com/elgatito/elementum/pull/113
https://github.com/elgatito/plugin.video.elementum/pull/995
