### ISSUE TITLE
[BUG] Small bug with episode duration

### ISSUE THREAD

**Issue by matke-84** [elgatito/plugin.video.elementum#997]
@elgatito @antonsoroko
As the title says, there is a bug with the duration of the episodes. It actually keeps showing the same running time for each episode and it's wrong. No episode of Stranger things lasts 30 minutes.
![episodes](https://github.com/elgatito/plugin.video.elementum/assets/74268331/330b4b81-c24d-4a50-ba9a-13b4ddabe237)
TMDb helper and other plugins they show a good running time of the episodes.
![tmdb](https://github.com/elgatito/plugin.video.elementum/assets/74268331/a138fd37-458f-4f11-a674-46354bdc8297)

**Comment by antonsoroko** [comment]
@matke-84 
i just check the code - elementum uses ether "default" show's runtime (if available) or 30m - for both show and for episode.
but we can use:
for episode: episode runtime - if available, if not - then default_runtime.
for show: number_of_episodes*default_runtime.

funny that nobody noticed that for 8 years! :-D
https://github.com/elgatito/elementum/commit/bfaf21c3fa9ebe98e51af87ec735d4c5c4f2d5df#diff-d216c3118d3c0b899b8815d434b5e63924ca8b0b6545ef434abcad7d1a994fb8R92

please test this build:
https://disk.yandex.ru/d/20qkkSdga6RHFA

**Comment by matke-84** [comment]
@antonsoroko 

Episodes now display good runtimes. Thank you.

> for show: number_of_episodes*default_runtime

This is interesting. I don't use in my skin, I know it uses Kodi's default skin. The only thing is that the default time doesn't have many tv shows, so somewhere it is displayed somewhere not.

**Comment by antonsoroko** [comment]
>The only thing is that the default time doesn't have many tv shows

sure, stranger things do not have "default runtime". so i calculate it only if it is available. anyway, it is obvious that it is just a estimation of total show's runtime, not a precise number. maybe it is not very useful, but i added it already.

**Comment by elgatito** [comment]
@matke-84 That is not a "bug", actually. There was no `runtime` field per episode on TMDB, and was only a common runtime for Show. 

Then `runtime` was added and now time episodes have own `runtime` value and some rely on `runtime` provider per Show.
